### ISSUE TITLE
azure vm shutdown is case sensitive

### ISSUE THREAD

**Issue by codingoutloud** [Azure/azure-xplat-cli#1055]
VM name is "VSPro"

This command does not find the VM:

azure vm shutdown vspro

The command shuts down the VM as expected:

azure vm shutdown VSPro

Seems this should not be case-sensitive. The portal will not allow me to create both VSPro and vspro VMs, so the portal is not case-sensitive, and tools ought to follow suit.

**Comment by anuchandy** [comment]
fixed in https://github.com/MSOpenTech/azure-xplat-cli/tree/dev

**Comment by sreekanthbs** [comment]
VM name is "XplatVM"
shutdown xplatvm is working fine. Xplat CLI is not case-sensitive
<pre>
<code>
C:\Jul2015\Jul-14\azure-xplat-cli-dev>node bin/azure vm shutdown xplatvm
info:    Executing command vm shutdown
+ Getting virtual machines
+ Shutting down VM
info:    vm shutdown command OK

C:\Jul2015\Jul-14\azure-xplat-cli-dev>node bin/azure vm list
info:    Executing command vm list
+ Getting virtual machines
data:    Name             Status              Location    DNS Name                      IP Address
data:    ---------------  ------------------  ----------  ----------------------------  --------------
data:    DnDJenkin        StoppedDeallocated  West US     dndjenkin.cloudapp.net
data:    XplatVM          StoppedDeallocated  West US     vmtestxplat.cloudapp.net
</code>
</pre>
