### ISSUE TITLE
Blob snapshotting functionality missing

### ISSUE THREAD

**Issue by priestjim** [Azure/azure-xplat-cli#1077]
Blob snapshotting functionality (i.e. extremely useful for backups) as described in http://msdn.microsoft.com/en-us/library/windowsazure/ee691971.aspx is missing from the toolkit as of release 0.7.4.

**Comment by pneumee** [comment]
Why was this closed? Snapshot functionality is needed, especially when the only place it seems to be available is via PowerShell. It's not even available via the web console, AFAIK.

**Comment by wyldbill** [comment]
+1

**Comment by amarzavery** [comment]
@yaxia @hasonmsft - Can you take a look at this feature request?

**Comment by yaxia** [comment]
ETA of supporting this is June release.

**Comment by howardatwork** [comment]
@yaxia Thanks for the update. I'm looking forward for this.

**Comment by yaxia** [comment]
We have added support for creating, copying and deleting the blob snapshot in the 0.10.1. Please take a try.
