### ISSUE TITLE
Feature Request for CLI: Remove-AzureService svcname -Force feature

### ISSUE THREAD

**Issue by rajinders** [Azure/azure-xplat-cli#1139]
In Powershell we can remove a cloud service and all the virtual machines in the cloud service with command Remove-AzureService servicename -Force.

In CLI when we try 
azure service delete -q servicename 
It fails with error
C:\Program Files\Microsoft SDKs\Windows Azure\.NET SDK\v2.1>azure service delete -q svcname
info:    Executing command service delete
+ Deleting cloud service
error:   A hosted service cannot be deleted while it still contains deployments.
info:    Error information has been recorded to azure.err
error:   service delete command failed

It will be great if -Force option is made available so we can deprovision services quickly.

**Comment by matt-gibbs** [comment]
prioritizing ARM investments over service command enhancements.
