### ISSUE TITLE
azure account import with moon cake publish settings file

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-xplat-cli#1179]
account import command with moon cake publish settings file fails, please see below:

C:\Users\anu>azure account import ".\AD Test Subscription D-4-14-2014-credentials.publishsettings"
info:    Executing command account import
error:   Could not find an environment with management endpoint https://management.core.chinacloudapi.cn. Create one and import this publishSettings file again.
info:    Error information has been recorded to azure.err
error:   account import command failed

**Comment by markcowl** [comment]
This should be fixed.  Please open a new issue if not.
