### ISSUE TITLE
Login failed - possibly special characters in password

### ISSUE THREAD

**Issue by devodev** [Azure/azure-xplat-cli#1228]
I was unable to do login via 'azure login' for azure tools version 0.8.4. The failure was

Get Token request returned http error: 401 and server response: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS50008: SAML token is invalid.\r\nTrace ID: b7e25d8d-42a8-4fde-94d1-5ea41c24a284\r\nCorrelation ID: 0f71bd80-16fc-4268-bb51-7f3806c86d95\r\nTimestamp: 2014-06-07 11:20:52Z","error_codes":[70002,50008],"timestamp":"2014-06-07 1:20:52Z","trace_id":"b7e25d8d-42a8-4fde-94d1-5ea41c24a284","correlation_id":"0f71bd80-16fc-4268-bb51-7f3806c86d95"}

The issue seems to be related to special characters in the password. The old password was "9aY2&8$2q1sC" (without the double quotes)

I suspect that the ampersand is causing javascript failure.

**Comment by amarzavery** [comment]
Closing this issue as ADAL needs to fix this issue.
