### ISSUE TITLE
Add "azure storage blob upload" move feature

### ISSUE THREAD

**Issue by orekdm** [Azure/azure-xplat-cli#1241]
Please add a switch that allows for the local file to be removed automatically after being successfully transferred to blob storage.

**Comment by gangsir** [comment]
Thanks for providing feedback. We will put this into our feature request backlog.

**Comment by amarzavery** [comment]
@hasonmsft @yaxia - Do you think this will be done? If no, then please feel free to close this issue.

**Comment by hasonmsft** [comment]
@orekdm , as it'll be very easy to remove the local file after uploading the file successfully via the script, we decide not to take this change for now.
