### ISSUE TITLE
When using -c, azure vm create requires -l, but then ignores it

### ISSUE THREAD

**Issue by bureado** [Azure/azure-xplat-cli#1283]
When using -c on azure vm create, it's assumed that I will use an existing cloud service and hence the same location. If -c is used and no -l is passed, command fails but if -l is passed then it is ignored. The desired behavior is for -l to not be required when -c is used.

**Comment by anuchandy** [comment]
This is fixed.

**Comment by sreekanthbs** [comment]
It is working fine. VM create with -c option doesn't require location.
<pre>
<code>
C:\Jul2015\Jul-2\azure-xplat-cli-dev>node bin/azure vm create DnsXplatTest bd507d3a70934695bc2128e3e5a255ba__RightImage-Windows-2012-x64-iis8-v13.4.12.2 azureus
er Brillio@2015 -n "XplatVMTest1" -c "DnsXplatTest"
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
+ Looking up image bd507d3a70934695bc2128e3e5a255ba__RightImage-Windows-2012-x64-iis8-v13.4.12.2
+ Looking up cloud service
+ Getting cloud service properties
+ Looking up deployment
+ Retrieving storage accounts
+ Creating VM
info:    vm create command OK
</code>
</pre>
