### ISSUE TITLE
Add  Customization HDInsight Cluster provisioning

### ISSUE THREAD

**Issue by SamuelRamond** [Azure/azure-xplat-cli#1307]
Hi
is it possible to add a command to change HDInsight mapreduce configuration files:
mapred-site.xml
hdfs-site.xml
core-site.xml
It is already possible using powershell or azure .NET sdk, see (http://blogs.msdn.com/b/bigdatasupport/archive/2014/04/15/customizing-hdinsight-cluster-provisioning-via-powershell-and-net-sdk.aspx)

**Comment by shefaliv** [comment]
This should be possible with the ARM HDInsight CLI tools.

**Comment by amarzavery** [comment]
@shefaliv - Can you provide the list of commands that the user can take a look at?
