### ISSUE TITLE
ENOENT error in azure vm docker create (on windows)

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1340]
I just made a clean installation of Node.js on Windows and azure-cli through npm.

```
C:\Users\ahmetb>azure vm docker create -z extrasmall -e 22 -s 041b0c0f-a2c3-4617-b5b1-4da7679d7255 -l 'West US' alp-docker3 b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04-LTS-amd64-server-20140724-en-us-30GB azureuser '$SomePassword'
info:    Executing command vm docker create
+ Generating docker certificates.
error:   spawn ENOENT
info:    Error information has been recorded to azure.err
```

azure.err:

```
Mon Aug 25 2014 22:33:42 GMT-0700 (Pacific Daylight Time):
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

```

The command creates the `.docker` folder under my home directory (c:\users\ahmetb) but it is empty.

**Comment by hopetobelievein** [comment]
Fixed in https://github.com/MSOpenTech/azure-sdk-tools-xplat/commit/34deb1f8952599078bc87b20a0fb32d42f0a6304. Will be part of PR from MSOpenTech.

**Comment by ahmetalpbalkan** [comment]
@hopetobelievein can't see where it's fixed with a friendly error message or a pre-check for openssl.exe  in 34deb1f.

**Comment by hopetobelievein** [comment]
@ahmetalpbalkan https://github.com/MSOpenTech/azure-sdk-tools-xplat/blob/dev/lib/commands/asm/vm/vmclient.js#L3892

**Comment by johngossman** [comment]
I had the problem that Openssl was not finding a conf file. My installation is from the git bash on Windows. I fixed by setting OPENSSL_CONF to point at the openssl.cnf file in git/ssl. The check that openssl is installed by asking for version is not enough.

**Comment by sauryadas** [comment]
@amarzavery Can you please assign this to the right owner?

**Comment by amarzavery** [comment]
@sauryadas - you are the right owner. It's an issue with the vm command and falls in your lap.

**Comment by amarzavery** [comment]
Looks like the command works.
```
azure vm docker create -z Small -e 22  -l "West US" foo2345nmj b39f27a8b8c64d52b0ebad85__Ubuntu-14_04-LTS-amd64-server-20140724-en-us-30GB tp2user HelloWorld!12
info:    Executing command vm docker create
info:    Found docker client certificates.
+ Looking up image b39f27a8b8c64d52b0ebad85__Ubuntu-14_04-LTS-amd64-server-20140724-en-us-30GB
+ Looking up cloud service
info:    cloud service foo2345nmj not found.
+ Creating cloud service
+ Retrieving storage accounts
+ Creating VM
info:    vm docker create command OK
```
