### ISSUE TITLE
SSH key option instead of SSH cert (PEM) option

### ISSUE THREAD

**Issue by smereczynski** [Azure/azure-xplat-cli#1387]
There is option in new Azure Portal, to create Linux VM with SSH key (RSA). With this option http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-use-root-privileges/ makes sens (using in example Ansible with no pass prompt) and there is no need to use -i switch with ssh command. There should be an option to use RSA key in xplat CLI tool.

**Comment by yugangw-msft** [comment]
@kmouss - Can you please take a look at this request?

**Comment by takekazuomi** [comment]
+1 I want use id_rsa.pub in azure create vm command. This is a simple and easy to understand.

**Comment by anuchandy** [comment]
Please follow this issue https://github.com/Azure/azure-xplat-cli/issues/1681. Closing this one.
