### ISSUE TITLE
Command-line tools documentation - site job upload - wrong description

### ISSUE THREAD

**Issue by kierenj** [Azure/azure-xplat-cli#1430]
Available at this URL: http://azure.microsoft.com/en-us/documentation/articles/command-line-tools/#Commands_to_manage_your_web_sites

The description for 'site job upload' is incorrectly, "This command deletes the specified web job.", as below:

**site job upload [options] <jobName> <jobType> [name]**

This command deletes the specified web job.

**Comment by amarzavery** [comment]
The CLI help looks accurate hence closing this issue.
