### ISSUE TITLE
Illegal setting in help for azure vm docker create (minor)

### ISSUE THREAD

**Issue by rstropek** [Azure/azure-xplat-cli#1477]
Help for *azure vm docker create* mentions *small* as a possible value for *--vm-size*. If you use it, you get the error *Value 'small' specified for parameter 'RoleSize' is invalid'*. To get things working, you have to use an initial capital letter (*Small*). Additionally, the help does not include all possible vm sizes without indicating that with e.g. *..., etc.*.

**Comment by hopetobelievein** [comment]
List of available sizes was removed from help here: https://github.com/MSOpenTech/azure-sdk-tools-xplat/commit/fb6d2ecd29a8fa1143e7031fcacdac86249ec7a2
Changed default VM size from "small" to "Small" in help text here: https://github.com/MSOpenTech/azure-sdk-tools-xplat/pull/131

**Comment by kmouss** [comment]
This will be part of next release

**Comment by anuchandy** [comment]
Closing this issue as fix is already released
