### ISSUE TITLE
azure vm create - seems that there isn't option to set the "storage account"

### ISSUE THREAD

**Issue by jruix** [Azure/azure-xplat-cli#1478]
I can't see the option to set the storage account where I want to place the vhd image of the VM I'm creating.

Seems that the VM is getting the first storage account is found in the location where th VM is created.

If the VM is created through the web interface I can set the storage account in the 3rd Step option "Storage Account"

**Comment by kmouss** [comment]
will track this issue under: azure vm create` fails for specialized image: "Cannot set property 'mediaLink' of undefined" #1516
