### ISSUE TITLE
Failed to connect docker deamon with --tlsverify option

### ISSUE THREAD

**Issue by phstudy** [Azure/azure-xplat-cli#1493]
The default certificate generated by `azure vm docker create ...` command will use `*` as `CN`, which does not work with `--tlsverify` option.

The default certificate works with `--tls` option
~~~
17:52:03 study-mbpr: azure-deploy$ docker --tls -H tcp://phstudy.azure.tw:4243 ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
~~~

The default certificate does not work with `--tlsverify` option
~~~
17:52:11 study-mbpr: azure-deploy$ docker --tlsverify -H tcp://phstudy.azure.tw:4243 --tlscacert="/Users/study/.docker/ca.pem" --tlscert="/Users/study/.docker/cert.pem" --tlskey="/Users/study/.docker/key.pem" ps
2014/12/18 17:52:19 Get https://phstudy.azure.tw:4243/v1.15/containers/json: x509: certificate is valid for *, not phstudy.azure.tw
~~~

If I set environment variable `DOCKER_TLS_VERIFY=1`, I will also get the same error as above.
~~~
11:00:34 study-mbpr: ~$ export DOCKER_TLS_VERIFY=1
11:00:35 study-mbpr: ~$ docker --tls -H tcp://phstudy.azure.tw:4243 ps
2014/12/19 11:00:40 Get https://phstudy.azure.tw:4243/v1.15/containers/json: x509: certificate is valid for *, not phstudy.azure.tw
~~~

And there seems no way to change default certificate in created docker vm, it will be replaced with the original one after rebooting.

**Comment by ahmetalpbalkan** [comment]
@phstudy your domain name does not have a SSL certificate. You need to purchase a SSL cert if you want to use --tlsverify. http://azure.microsoft.com/en-us/documentation/articles/cloud-services-configure-ssl-certificate/

Does this solve your problem?

**Comment by phstudy** [comment]
@ahmetalpbalkan I know if I want to use --tlsverify,  my domain should have a SSL certificate. But another question is how to renew the certificate? If I put new certificate in docker vm, it will be replaced with the old certificate.

**Comment by bureado** [comment]
azure-cli creates the server certificate in one go when ~/.docker doesn't exist and/or any of the files inside is missing. azure-cli should create a server certificate with the appropriate CN every time an azure vm docker create is called (or, docker should accept * in the CN) Here's a quick and dirty fix to do so: https://github.com/bureado/azure-xplat-cli/commit/ea212896c3559c928a1a0454af9d80a06573a88a

**Comment by ahmetalpbalkan** [comment]
@bureado I don't know much about TLS certs but are you going to contribute that back? looks like a very useful fix to me.

**Comment by bureado** [comment]
I've sent it in #1560 but I don't know if #1523 can be a simpler solution (yet that would still mean a single server certificate is shared among different Docker VM instances)

**Comment by ruslangabitov** [comment]
Fixed here: https://github.com/MSOpenTech/azure-xplat-cli/pull/344
Now command creates server certificates for each VM and default CN is set to *.cloudapp.net, but user can specify its own CN via --docker-cert-cn option if he wants to use <code>--tlsverify</code>.

**Comment by sreekanthbs** [comment]
No each vm docker create creating server certificates for each VM.
PFB screen shot of the .docker folder for reference.
![docker_certificates](https://cloud.githubusercontent.com/assets/11171941/8695826/6b6d315c-2b05-11e5-9fad-2a1d4cd206f6.JPG)

**Comment by ruslangabitov** [comment]
@sreekanthbs can you please explain what's wrong with the <code>.docker</code> folder on this screenshot? 
There are client certs: <code> ca.pem, ca-key.pem, cert.pem, key.pem, client.csr </code>
And server certs for each VM you've created: <code> vmname-server-* </code>

**Comment by sreekanthbs** [comment]
@ruslangabitov It is working fine as expected.
