### ISSUE TITLE
`azure vm docker create --blob-url=...` does not create vhd in correct blob storage account

### ISSUE THREAD

**Issue by phstudy** [Azure/azure-xplat-cli#1495]
If I specificed `--blob-url` argument in `create vm` command, `azure vm create` command will create in correct blob storage account, but `azure vm docker create` always creates in `portalvhdsxxxxxxxxxxxx` blob storage account.

**Comment by hopetobelievein** [comment]
Fixed in https://github.com/MSOpenTech/azure-sdk-tools-xplat/commit/b2bfde7fb1ae50ae38c398c27dc9d936d4c4f89f

**Comment by kmouss** [comment]
Fix planned as part of next release cycle.

**Comment by kmouss** [comment]
Issue has been merged.
