### ISSUE TITLE
The location Australia Southeast is not valid

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-xplat-cli#1498]
In Azure Resource Manager Mode, the Australian data centres cannot be used with the error given such that 'The location Australia Southeast is not valid'

In the portal I can create resource groups in these regions

**Comment by damienpontifex** [comment]
Further, doing the location list with `azure location list` the item with name "Resource Group" is not in either Australian data centre but resource with name "Microsoft.Resources/resourceGroups" is available in australiasoutheast and australiaeast 
(note all lower case and no caps compared to all other resource providers)

Are these not the same resource type? And if so, why are they available in different regions with different spelling types for the locations?

**Comment by yugangw-msft** [comment]
We will fix this in a future release. Thanks for reporting this.

**Comment by matt-gibbs** [comment]
This PR contains the fix
https://github.com/Azure/azure-xplat-cli/pull/1528
