### ISSUE TITLE
Unable to put comments in resource template file

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-xplat-cli#1499]
In the Channel 9 series, [Azure Resource Manager DevOps](http://channel9.msdn.com/Series/Azure-Resource-Manager-DevOps/03), they mention that json template files can be commented using either the // inline comment or /* */ block comment.

Although doing this in a template and using the azure cli results in an error of `Unexpected token /`. Is this type of comment meant to be supported as suggested in the course?

I am using azure-cli v0.8.13 in arm mode

**Comment by markcowl** [comment]
@damienpontifex  comments are not part of the json schema, these are not supported by all json serializers, and you should not use them in template files.
