### ISSUE TITLE
"azure vm endpoint acl-rule create" parser error: --description is incorrectly a bool

### ISSUE THREAD

**Issue by ghuntley** [Azure/azure-xplat-cli#1500]
# Stack-trace

    Mon Dec 22 2014 03:12:05 GMT+1100 (AUS Eastern Daylight Time):
    [TypeError: Object true has no method 'trim']
    TypeError: Object true has no method 'trim'
        at EndPointUtil._.extend.validateACLDescription (C:\Users\ghuntley\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\vm\endpointUtil.js:256:33)
        at VMClient._.extend.createEPAclRule (C:\Users\ghuntley\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\vm\vmclient.js:1739:36)
        at AzureCli.<anonymous> (C:\Users\ghuntley\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\asm\vm._js:385:14)
        at AzureCli.<anonymous> (C:\Users\ghuntley\AppData\Roaming\npm\node_modules\azure-cli\lib\cli.js:195:12)
        at AzureCli.<anonymous> (C:\Users\ghuntley\AppData\Roaming\npm\node_modules\azure-cli\node_modules\commander\lib\commander.js:235:8)
        at AzureCli.emit (events.js:98:17)
        at AzureCli.Command.parseArgs (C:\Users\ghuntley\AppData\Roaming\npm\node_modules\azure-cli\node_modules\commander\lib\commander.js:405:12)
        at AzureCli.Command.parse (C:\Users\ghuntley\AppData\Roaming\npm\node_modules\azure-cli\node_modules\commander\lib\commander.js:351:15)
        at AzureCli.<anonymous> (C:\Users\ghuntley\AppData\Roaming\npm\node_modules\azure-cli\lib\cli.js:552:13)
        at AzureCli.emit (events.js:95:17)

# Observation
A `bool` is being passed in over to the validation logic which contains `description.Trim()` which is a invalid operation on a `bool`. Specifically  `azure-cli\lib\commands\asm\vm\vmclient.js:1739` is passing a bool into `azure-cli\lib\commands\asm\vm\endpointUtil.js:256` which suggests a parser misconfiguration which is handing `--description` as a truthy `bool` instead of a` string`. 

# Suggested fix

Fix your parser! :cat: 

# Steps to reproduct
    > azure vm endpoint delete {cloudservice} rdp
    info:    Executing command vm endpoint delete
    + Getting virtual machines
    + Reading network configuration
    + Updating network configuration
    info:    vm endpoint delete command OK

    > azure vm endpoint create {cloudservice} 3389 3389 -n rdp
    info:    Executing command vm endpoint create
    + Getting virtual machines
    + Reading network configuration
    + Updating network configuration
    info:    vm endpoint create command OK

    > azure vm endpoint acl-rule create {cloudservice} rdp 1 permit 59.167.236.165/32 --description home
    info:    Executing command vm endpoint acl-rule create
    error:   Object true has no method 'trim'
    info:    Error information has been recorded to azure.err
    error:   vm endpoint acl-rule create command failed

# Version Info
    > npm install azure-cli -g
    C:\Users\ghuntley\AppData\Roaming\npm\azure -> C:\Users\ghuntley\AppData\Roaming\npm\node_modules\azure-cli\bin\azure
    azure-cli@0.8.13 C:\Users\ghuntley\AppData\Roaming\npm\node_modules\azure-cli
    ├── easy-table@0.0.1
    ├── eyes@0.1.8
    ├── xmlbuilder@0.4.3
    ├── through@2.3.4
    ├── azure-gallery@2.0.0-pre.12
    ├── colors@0.6.2
    ├── node-uuid@1.2.0
    ├── wordwrap@0.0.2
    ├── async@0.2.7
    ├── mime@1.2.11
    ├── validator@3.1.0
    ├── azure-mgmt-authorization@0.9.0-pre.3
    ├── azure-extra@0.1.4
    ├── underscore@1.4.4
    ├── caller-id@0.1.0 (stack-trace@0.0.9)
    ├── tunnel@0.0.2
    ├── commander@1.0.4 (keypress@0.1.0)
    ├── azure-mgmt-resource@2.0.0-pre.13
    ├── openssl-wrapper@0.2.1 (debug@0.7.4, q@0.9.7)
    ├── omelette@0.1.0
    ├── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
    ├── github@0.1.6
    ├── xml2js@0.1.14 (sax@0.6.1)
    ├── event-stream@3.1.5 (duplexer@0.1.1, stream-combiner@0.0.4, from@0.1.3, pause-stream@0.0.11, map-stream@0.1.0, split@0.2.10)
    ├── streamline@0.4.5
    ├── kuduscript@0.1.11 (commander@1.1.1, streamline@0.4.11)
    ├── winston@0.6.2 (cycle@1.0.3, stack-trace@0.0.9, async@0.1.22, pkginfo@0.2.3, request@2.9.203)
    ├── moment@2.6.0
    ├── azure-common@0.9.9 (duplexer@0.1.1, dateformat@1.0.2-1.2.3, envconf@0.0.4, xml2js@0.2.7)
    ├── adal-node@0.1.7 (node-uuid@1.4.1, xmldom@0.1.19, xpath.js@0.0.3, date-utils@1.2.16)
    ├── azure-storage-legacy@0.9.11 (azure-common@0.9.8)
    ├── request@2.27.0 (forever-agent@0.5.2, aws-sign@0.3.0, tunnel-agent@0.3.0, qs@0.6.6, json-stringify-safe@5.0.0, oauth-sign@0.3.0, cookie-jar@0.3.0, node-uuid@1.4.2, hawk@1.0.0, form-data@0.1.4, http-signature@0.10.0)
    ├── azure-storage@0.4.0 (extend@1.2.1, node-uuid@1.4.2, xml2js@0.2.7)
    └── azure@0.10.2 (azure-mgmt-subscription@0.9.13, azure-mgmt-hdinsight@0.9.12, azure-mgmt-storage@0.9.13, azure-mgmt@0.9.13, azure-mgmt-scheduler@0.9.1-pre.13, azure-monitoring@0.9.1-pre.13, azure-scheduler@0.9.1-pre.13, azure-mgmt-vnet@0.9.14, azure-rm-website@0.9.0-pre.7, azure-mgmt-sql@0.9.14, azure-mgmt-sb@0.9.13, azure-mgmt-website@0.9.13, azure-mgmt-compute@0.9.13, azure-storage@0.3.3, azure-sb@0.9.14)

    > npm show azure-cli

    { name: 'azure-cli',
      description: 'Microsoft Azure Cross Platform Command Line tool',
      'dist-tags': { latest: '0.8.13' },
      versions:
       [ '0.6.8',
         '0.6.9',
         '0.6.10',
         '0.6.11',
         '0.6.12',
         '0.6.13',
         '0.6.14',
         '0.6.15',
         '0.6.16',
         '0.6.17',
         '0.6.18',
         '0.7.0',
         '0.7.1',
         '0.7.2',
         '0.7.3',
         '0.7.4',
         '0.7.5',
         '0.8.0',
         '0.8.1',
         '0.8.2',
         '0.8.3',
         '0.8.4',
         '0.8.5',
         '0.8.6',
         '0.8.7',
         '0.8.8',
         '0.8.9',
         '0.8.10',
         '0.8.11',
         '0.8.12',
         '0.8.13' ],
      maintainers: 'windowsazure <azuresdk@outlook.com>',
      time:
       { modified: '2014-12-12T22:59:26.149Z',
         created: '2012-11-21T15:16:34.903Z',
         '0.6.8': '2012-11-21T15:16:44.292Z',
         '0.6.9': '2012-12-13T19:53:38.757Z',
         '0.6.10': '2012-12-24T22:10:28.021Z',
         '0.6.11': '2013-02-12T22:44:36.929Z',
         '0.6.12': '2013-03-13T15:57:39.027Z',
         '0.6.13': '2013-03-26T01:18:49.921Z',
         '0.6.14': '2013-04-05T20:59:39.806Z',
         '0.6.15': '2013-04-22T02:43:41.664Z',
         '0.6.16': '2013-05-10T17:41:30.997Z',
         '0.6.17': '2013-06-27T18:03:30.038Z',
         '0.6.18': '2013-07-16T18:03:13.518Z',
         '0.7.0': '2013-08-07T22:13:19.217Z',
         '0.7.1': '2013-08-26T23:15:19.924Z',
         '0.7.2': '2013-09-25T21:22:34.456Z',
         '0.7.3': '2013-10-21T21:14:58.312Z',
         '0.7.4': '2013-11-11T20:50:50.238Z',
         '0.7.5': '2014-02-13T19:53:08.767Z',
         '0.8.0': '2014-04-03T19:10:33.646Z',
         '0.8.1': '2014-04-03T19:20:53.255Z',
         '0.8.2': '2014-04-10T21:47:24.561Z',
         '0.8.3': '2014-05-08T18:42:08.854Z',
         '0.8.4': '2014-06-04T22:08:01.275Z',
         '0.8.5': '2014-07-07T21:06:06.566Z',
         '0.8.6': '2014-07-18T23:52:47.737Z',
         '0.8.7': '2014-08-11T19:52:04.334Z',
         '0.8.8': '2014-09-11T00:04:28.615Z',
         '0.8.9': '2014-09-15T22:28:14.655Z',
         '0.8.10': '2014-10-03T00:06:14.940Z',
         '0.8.11': '2014-10-27T18:08:40.884Z',
         '0.8.12': '2014-11-18T19:26:40.478Z',
         '0.8.13': '2014-12-12T22:59:26.149Z' },
      author: 'Microsoft Corporation',
      repository:
       { type: 'git',
         url: 'git@github.com:WindowsAzure/azure-xplat-cli.git' },
      readmeFilename: 'README.md',
      homepage: 'https://github.com/WindowsAzure/azure-xplat-cli',
      keywords:
       [ 'node',
         'azure',
         'cli',
         'cloud hosting',
         'deployment' ],
      contributors:
       [ 'Block, Glenn <gblock@microsoft.com>',
         'Cowlishaw, Mark <markcowl@microsoft.com>',
         'Dejardin, Louis <loudej@microsoft.com>',
         'Georgiev, Yavor <yavorg@microsoft.com>',
         'Janczuk, Tomasz <tjanczuk@microsoft.com>',
         'Rodrigues, Andre <andrerod@microsoft.com>',
         'Tavares, Chris <ctavares@microsoft.com>' ],
      bugs: { url: 'https://github.com/WindowsAzure/azure-xplat-cli/issues' },
      users: { jeffpar: true, italoacasas: true },
      version: '0.8.13',
      tags: [ 'azure', 'cli' ],
      main: './lib/cli.js',
      preferGlobal: 'true',
      engines: { node: '>= 0.8.26' },
      licenses:
       { type: 'Apache',
         url: 'http://www.apache.org/licenses/LICENSE-2.0' },
      dependencies:
       { 'adal-node': '0.1.7',
         async: '0.2.7',
         azure: '0.10.2',
         'azure-common': '0.9.9',
         'azure-gallery': '2.0.0-pre.12',
         'azure-mgmt-authorization': '0.9.0-pre.3',
         'azure-mgmt-resource': '2.0.0-pre.13',
         'azure-storage': '0.4.0',
         'azure-storage-legacy': '0.9.11',
         'azure-extra': '0.1.4',
         mime: '~1.2.4',
         colors: '0.x.x',
         commander: '1.0.4',
         'easy-table': '0.0.1',
         'event-stream': '3.1.5',
         eyes: '0.x.x',
         github: '0.1.6',
         kuduscript: '0.1.11',
         moment: '2.6.0',
         'node-uuid': '1.2.0',
         omelette: '0.1.0',
         request: '2.27.0',
         streamline: '0.4.5',
         through: '2.3.4',
         tunnel: '0.0.2',
         underscore: '1.4.x',
         validator: '~3.1.0',
         winston: '0.6.x',
         wordwrap: '0.0.2',
         xml2js: '0.1.x',
         xmlbuilder: '0.4.x',
         'readable-stream': '~1.0.0',
         'openssl-wrapper': '0.2.1',
         'caller-id': '0.1.x' },
      devDependencies:
       { mocha: '1.16.0',
         jshint: '>= 2.1.4',
         sinon: '*',
         should: '3.3.2',
         nock: '0.16',
         'winston-memory': '*',
         cucumber: '~0.3.0' },
      scripts:
       { test: 'npm -s run-script jshint && npm -s run-script unit && npm -s run-script unit-arm',
         unit: 'node scripts/unit.js testlist.txt',
         'unit-mc': 'node scripts/unit.js --mc testlistmc.txt',
         'unit-arm': 'node scripts/unit.js testlistarm.txt',
         jshint: 'jshint lib --jslint-reporter --extra-ext ._js',
         preci: 'jshint lib --reporter=checkstyle --extra-ext ._js > checkstyle-result.xml',
         ci: 'node scripts/unit.js testlist.txt -xunit',
         preacceptance: 'node scripts/cuke-environment.js setup',
         acceptance: 'node node_modules/cucumber/bin/cucumber.js',
         postacceptance: 'node scripts/cuke-environment.js teardown',
         'extract-labels': 'node scripts/extract-labels' },
      bin: { azure: './bin/azure' },
      gitHead: '9d3950d4eaababd7c95dad51e0a8505405051e24',
      dist:
       { shasum: 'e155c8bfc5be35a1c43084074a6c0c098bdd015e',
         tarball: 'http://registry.npmjs.org/azure-cli/-/azure-cli-0.8.13.tgz' },
      directories: {} }

**Comment by HimanshuBri** [comment]
@anuchandy. Working fine.

**Comment by anuchandy** [comment]
Closing this as fix is merged to upstream
