### ISSUE TITLE
No support for Notification Hub management

### ISSUE THREAD

**Issue by RocketPop** [Azure/azure-xplat-cli#1503]
I would like to request support for Notification Hub create/update/delete... None of the azure SDKs except for the .NET dlls support these features. It's something of an oversight IMO.
I see this issue: https://github.com/Azure/azure-xplat-cli/issues/754 was closed long ago. Not sure why.

**Comment by piyushjo** [comment]
Thanks for your feedback. This has been on our product backlog for some time. We just haven't received enough customer asks to implement this in the CLI. We do have Java/PHP/Python implementation for NH however at http://azure.microsoft.com/en-us/documentation/articles/notification-hubs-java-backend-how-to/.

**Comment by yugangw-msft** [comment]
closing this issue as it is a low priority for the service team. Please feel free to reopen it if necessary.

**Comment by RocketPop** [comment]
Hello! It seems to me that if both the product I'm subscribed to and underlying API supports it - this is something the CLI tools should keep current with. Why continue an unnecessary difference in feature coverage? :) It's one of the last things I had to write a custom tool for in my CI setup. Thanks!

**Comment by amarzavery** [comment]
@RocketPop 
I understand your frustration and I am with you. I hope the service team can do something about this.
@piyushjo
