### ISSUE TITLE
Issues when 2 accounts have the same name

### ISSUE THREAD

**Issue by serguer** [Azure/azure-xplat-cli#1504]
When we import an AzurePublishSettingsFile that contains 2 accounts with the same name but different subscription ids and you try to execute azure account list there is only showed one of them. The other one is ignored.

In Azure CLI the subscriptions are stored as a JSON object/ dictionary keyed on subscription name and not on subscription id. Hence it overwrites the second subscription with the same name.

**Comment by amarzavery** [comment]
This issue has been fixed. The PR https://github.com/Azure/azure-xplat-cli/pull/1533 has been merged to the dev branch and the changes will be out in the upcoming release 0.8.14
