### ISSUE TITLE
Reverse DNS for Azure Cloud Services

### ISSUE THREAD

**Issue by internalfx** [Azure/azure-xplat-cli#1508]
Can't create PTR record for cloud service with azure-cli

**Comment by kmouss** [comment]
Thank you. Could you please provide more details about this issue.

**Comment by matt-gibbs** [comment]
Closing. Feel free to re-open with additional details.

**Comment by aarsla** [comment]
Currently there is no way to add / modify Reverse DNS for Azure Cloud Services through azure-xplat-cli.
