### ISSUE TITLE
azure.err location is weird

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1509]
I'm running OS X (or Linux would be the same).

The `azure.err` file is created in the directory where I run the command (e.g. my project directory). This file should be in a place like `~/.azure.err` and should not go to where command is run for 2 main reasons:

* I can forget where I ran the command and I won't be able to find azure.err easily
* It contaminates my project (or other) directory with the file and source controls (e.g. git) will try to track it.

Please place it to `$HOME/.azure.err` (a dotfile would be even better as it wouldn't show up in file explorers normally since this is a diagnostics file).

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan 
You provided a good suggestion. We will work on it and provide a fix in the upcoming release.

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft thanks, great to hear.

**Comment by ahmetalpbalkan** [comment]
I just noticed we have a `~/.azure` directory already, so that one looks like a good candidate?

**Comment by amarzavery** [comment]
Yup this PR https://github.com/Azure/azure-xplat-cli/pull/1527 will add the azure.err file at ~/.azure and let the user know about it.

**Comment by amarzavery** [comment]
closing it as it is fixed in azure 0.8.14 to be released by Tuesday 01/27/2015
