### ISSUE TITLE
Internal load balancer management

### ISSUE THREAD

**Issue by johnddonnelly** [Azure/azure-xplat-cli#1513]
I've been searching for an equivalent here for the powershell New-AzureInternalLoadBalancerConfig. If no one objects (is anyone working on this already?) I'll add a DCR for wrappers for the service management API requests to Add, Delete and Update internal load balancers.

Add http://msdn.microsoft.com/en-us/library/azure/dn722411.aspx
Delete http://msdn.microsoft.com/en-us/library/azure/dn722410.aspx
Update http://msdn.microsoft.com/en-us/library/azure/dn775052.aspx

**Comment by kmouss** [comment]
This has been added in version # 0.8.13, try later version of the CLI azure service internal-load-balancer add, delete, set, list - Thank you
