### ISSUE TITLE
Enable specifying storage account type during storage account creation

### ISSUE THREAD

**Issue by kmouss** [Azure/azure-xplat-cli#1515]
Support the Storage Account type of Premium_LRS in  storage account type of: Standard_LRS, Standard_GRS, Standard_RAGRS, Standard_ZRS, and Premium_LRS. The ZRS and Premium storage account types can only be created using the new type-based storage account creation API

**Comment by amarzavery** [comment]
This is fixed in the upcoming release 0.8.14 made available on jan 27
