### ISSUE TITLE
ARM Cannot query DomainName or VirtualNetwork resources

### ISSUE THREAD

**Issue by McDonnellDean** [Azure/azure-xplat-cli#1518]
Hi,

When I try to fetch information on resources of the types: 
- microsoft.classiccompute/domainNames. 
- microsoft.classicnetwork/virtualNetworks. 

I did see this [SO question](http://stackoverflow.com/questions/27796995/azure-resource-manager-microsoft-classicstorage-storageaccounts-no-registered-re) on some providers not being available for use with ARM. Is this the same issue?

**Comment by yugangw-msft** [comment]
Thanks for reporting this issue. This feature/service is not yet supported in ARM mode.

**Comment by kmouss** [comment]
Assigning to Yugang to review and close as this isn't yet implemented.

**Comment by yugangw-msft** [comment]
Closing this as it is under development.

**Comment by McDonnellDean** [comment]
Awesome!
