### ISSUE TITLE
Feature request: remember site for current directory

### ISSUE THREAD

**Issue by simplyianm** [Azure/azure-xplat-cli#1520]
It would nice to not have to type the site name after every `azure site` command, a la Heroku. Is this possible?

**Comment by amarzavery** [comment]
@simplyianm 
We have that feature in xplat cli. If you create the site with --git and --gitusername option. 
Remember to execute this command in a new folder/directory. The new folder will have a .git directory in it. After that if you execute the site commands from the new directory, you need not provide the site name.

**Comment by simplyianm** [comment]
Is there a way to set this for the current directory?

**Comment by amarzavery** [comment]
@simplyianm - I think you can do this by executing the azure site create command again with --git and --gitusername options from the current directory. This should update your existing site with git options and will also add a .git directory under your current directory.

**Comment by simplyianm** [comment]
@amarzavery - Would this create a new Azure site though? Or would it just
somehow bind the Git repository to Azure? The analogous command in Heroku
is `heroku git:remote add`, which adds the "Heroku" remote to the repo.
Thanks.

**Comment by amarzavery** [comment]
@simplyianm - I think it will update the site with git configuration. It will not create a new site.

**Comment by yugangw-msft** [comment]
closing this issue as it seems to be resolved.
