### ISSUE TITLE
azure vm endpoint acl-rule create: unable to add rules

### ISSUE THREAD

**Issue by jruix** [Azure/azure-xplat-cli#1522]
Hi when I execute:

    azure vm endpoint acl-rule create virtual_machine_name end_point_name 1 permit 1.2.3.4/32

I've got the next error:

    error:   ACL rules do not match for endpoint in 'HTTP'. Mismatch in rule count. Specified '2'. Existing '1'.

changing the id to 2 or 3 doesn't make any difference:

     azure vm endpoint acl-rule create virtual_machine_name end_point_name 1 permit 1.2.3.4/32
     error:   ACL rules do not match for endpoint in 'HTTP'. Mismatch in rule count. Specified '2'. Existing '1'.

the End point I'm setting has already a rule defined to avoid another issue already reported when the id is 0, this is what happens if no acl rule is defined and we execute the command with 0 as ID:

    azure vm endpoint acl-rule create virtual_machine_name end_point_name 0 permit 1.2.3.4/32
    error:   The value for parameter 'EndpointAcl.Rules.Rule.Order' is null or empty.

latest case is related with the issue  https://github.com/Azure/azure-sdk-for-node/issues/1335 though. Other cases could be that the start id is 0 for the SDK and the cli tool is assuming 1 as the starting ID

**Comment by kmouss** [comment]
Thank you. This is a bug in the SDK - see: Azure/azure-sdk-for-node#1335 once SDK is updated you will be able to do acl-rule create with index 0

**Comment by tbartlett0** [comment]
This issue appears to still be occurring (the original one, not the index-0 one): 

`# azure vm endpoint acl-rule create -r Test MyVMName EndpointName 1 permit 10.0.0.0/8`
`info:    Executing command vm endpoint acl-rule create`
`+ Getting virtual machines                                                     `
`+ Reading network configuration                                                `
`+ Updating network configuration                                              `
`error:   ACL rules do not match for endpoint in 'LoadBalancedSetName'. Mismatch in rule count. Specified '2'. Existing '1'.`
`info:    Error information has been recorded to /home/user/.azure/azure.err`
`error:   vm endpoint acl-rule create command failed`

Could it be the case that I'm supposed to be using [these commands](https://github.com/Azure/azure-xplat-cli/wiki/Manage-load-balanced-set) instead, except that they're not implemented? If that's the case then it seems like azure-cli currently lacks the ability to manage load-balanced-set endpoint ACLs?
