### ISSUE TITLE
[proposal] Set the CN for the default docker certification to *.cloudapp.net

### ISSUE THREAD

**Issue by waitingkuo** [Azure/azure-xplat-cli#1523]
The proposal is to modify the Common Name of the default docker certification and solve #1493 

Currently, the CN we signed is *, it doesn't match the default DNS azure privided "mydomain.cloudapp.net"

I currently add a record in /etc/hosts to fix that.
If we modify the CN to *.cloudapp.net, then i'll match without modifying our /etc/hosts.

**Comment by kmouss** [comment]
This is dup of this: https://github.com/Azure/azure-xplat-cli/issues/1493
