### ISSUE TITLE
Running any command result in an error

### ISSUE THREAD

**Issue by aembury** [Azure/azure-xplat-cli#1530]
Running any command on the cli tools version 0.8.13, such as "azure" result in the following error:

```
fs.js:653
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOENT, no such file or directory 'Z:\'
    at Object.fs.mkdirSync (fs.js:653:18)
    at C:\Chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modules\azure-cli
\node_modules\streamline\lib\compiler\compile.js:326:71
    at Array.forEach (native)
    at mkdirsSync (C:\Chocolatey\lib\nodejs.commandline.0.10.33\tools\node_modul
es\azure-cli\node_modules\streamline\lib\compiler\compile.js:324:32)
    at cachedTransformSync (C:\Chocolatey\lib\nodejs.commandline.0.10.33\tools\n
ode_modules\azure-cli\node_modules\streamline\lib\compiler\compile.js:339:3)
    at exports.cachedTransformSync (C:\Chocolatey\lib\nodejs.commandline.0.10.33
\tools\node_modules\azure-cli\node_modules\streamline\lib\compiler\compile.js:35
9:10)
    at Object.streamliners._js [as ._js] (C:\Chocolatey\lib\nodejs.commandline.0
.10.33\tools\node_modules\azure-cli\node_modules\streamline\lib\compiler\undersc
ored.js:27:38)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

This is on a Windows 7 machine using Node JS installed via Chocolately. I have seen the other similar issues that mention deleting a .streamline folder but I can't seem to find this.

**Comment by amarzavery** [comment]
@aembury - why do you need to install node.js via Chocolately? You can install node.js directly by donwloading the MSI from [node.js website](http://nodejs.org/download/).

You can also install the azure-xplat-cli MSI which comes with a precompiled version of node.js for you. 
You can get the azure-xplat-cli MSI from [here](http://go.microsoft.com/?linkid=9828653&clcid=0x409).

**Comment by ltenison** [comment]
This is still an issue.  I'm getting the same error on a Windows 7 Ent laptop, from line 754 in fs.js.  I get that error no matter if using the Windows Platform Installer or if I de-install and re-install directly from GitHub.  Please re-open and suggest a solution.  thanks.
![captureazclibug](https://cloud.githubusercontent.com/assets/9934492/15521461/ca577d0a-21c0-11e6-98e6-6d923fe7cfa2.JPG)
