### ISSUE TITLE
[proposal] Allow the configuration and execution of VM Extension CustomScriptExtension

### ISSUE THREAD

**Issue by jliu70** [Azure/azure-xplat-cli#1539]
Currently azure-xplat-cli can get and set VM Extensions. 
If it is possible, I'd love to see azure-xplat-cli not just set the VM Extension CustomScriptExtension, but be able to configure (basically pass argument for the location of the powershell script), and then to call the CustomScriptExtension to run the powershell script on the remote VM.

Not sure if this is possible.   Thanks!

**Comment by jliu70** [comment]
I assume that it's currently limited by the lack of Service Management REST API?  I don't see the API list any operations for VM Extensions.
http://msdn.microsoft.com/en-us/library/azure/jj157206.aspx

**Comment by kmouss** [comment]
Please use: azure vm extension set command to pass in the extension parameters. Option:
-c, --public-config-path <public-config-path>    public configuration file path

Thank you

**Comment by jliu70** [comment]
If it is possible would you please provide an example?

Thanks,
Jeff

**Comment by tk421** [comment]
@jliu70 @kmouss It is unfortunate that examples are not provided. They are also very hard to find on Internet. [I posted a question in StackOverflow](http://stackoverflow.com/questions/33164650/azure-xplat-to-run-a-customscriptextension-in-a-windows-vm) to try to get an example.
