### ISSUE TITLE
Unable to use existing PublishSettings file to login

### ISSUE THREAD

**Issue by SumitBisht** [Azure/azure-xplat-cli#1540]
I am unable to use an existing PublishSettings file to connect with an azure account from cli.
The ```azure account import FILENAME.PublishSettings```  command fails with Invalid PublishSettings file error.

The file contains the following data:

```
<publishData>
<publishProfile profileName="XXX - Web Deploy" publishMethod="MSDeploy" publishUrl="XXX.scm.azurewebsites.net:443" msdeploySite="XXX" userName="$XXX" userPWD="XXX" destinationAppUrl="http://XXX.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
<databases/>
</publishProfile>
<publishProfile profileName="XXX - FTP" publishMethod="FTP" publishUrl="ftp://XXX.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="XXX\$XXX" userPWD="" destinationAppUrl="http://XXX.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
<databases/>
</publishProfile>
</publishData>
```
I tried editing the contents of xml with proper headers, renaming the file, as well as ran the azure import from same directory, but the error was same.
I am running node v0.10.9 on Ubuntu 13.04 (32bit).

**Comment by amarzavery** [comment]
@SumitBisht -

youcan try azure account download to download a new publish settings file associated with your subscription from the portal.

The execute account import to   import the newly downloaded file.

Hope that solves the problem.

If not an u please provide the content of azure.err file.

**Comment by SumitBisht** [comment]
@amarzavery Since I am using someone else's azure instance, I am unable to access the actual account.
My azure.err file has the following data:

```
Sun Jan 18 2015 21:56:04 GMT+0530 (IST):
{ [Error: Invalid publishSettings file. Use "azure account download" to download publishing credentials.]
  stack: [Getter/Setter],
  __frame: undefined,
  rawStack: [Getter] }
Error: Invalid publishSettings file. Use "azure account download" to download publishing credentials.
    at subscriptionsFromContents (/usr/local/lib/node_modules/azure-cli/lib/util/profile/publishSettings.js:52:11)
    at Object.importPublishSettings [as import] (/usr/local/lib/node_modules/azure-cli/lib/util/profile/publishSettings.js:92:10)
    at Profile._.extend.importPublishSettings (/usr/local/lib/node_modules/azure-cli/lib/util/profile/profile.js:193:34)
    at __5 (/usr/local/lib/node_modules/azure-cli/lib/commands/account._js:115:23)
```

**Comment by amarzavery** [comment]
@SumitBisht The template that you provided does not look like a publish settings file.

This is the template of publishsettings file
```
<?xml version="1.0" encoding="utf-8"?>
<PublishData>
  <PublishProfile
    SchemaVersion="2.0"
    PublishMethod="AzureServiceManagementAPI">
    <Subscription
      ServiceManagementUrl="https://management.core.windows.net"
      Id="some_id1"
      Name="some_name1"
      ManagementCertificate="some_cert1" />
    <Subscription
      ServiceManagementUrl="https://management.core.windows.net"
      Id="some_id2"
      Name="some_name2"
      ManagementCertificate="some_cert2" />
  </PublishProfile>
</PublishData>
```

**Comment by markcowl** [comment]
@SumitBisht Unfortunately, there are similar names between the publish profile used for websites content publishing (which you have provided here), and the publish settings used for azure management operations, which the cli uses and which you can obtain from the azure portal, or using the azure account download command as Amar describes.

**Comment by SumitBisht** [comment]
Thanks @amarzavery @markcowl will ask for the correct one for logging in.
