### ISSUE TITLE
"azure help vm disk attach-new" returns error

### ISSUE THREAD

**Issue by peterlimayo** [Azure/azure-xplat-cli#1542]
> azure help vm disk attach-new
info:    Executing command help

  error: option `-h, --host-caching <name>' argument missing

**Comment by peterlimayo** [comment]
same for "azure help vm disk attach"

> azure --version
0.8.13 (node: 0.10.23)

**Comment by kmouss** [comment]
Thanks, yes this is a bug, we are working on a fix: https://github.com/Azure/azure-xplat-cli/issues/1554

**Comment by kmouss** [comment]
closing this as we are tracking it as part of #1554
