### ISSUE TITLE
please add the ability to rename disk blobs

### ISSUE THREAD

**Issue by peterlimayo** [Azure/azure-xplat-cli#1543]
if we use 'azure vm disk attach-new', system autogenerates a new disk name
that can't be renamed for easy identification and future attach operation.
While I can specify the blob name in attach-new, but in 'azure vm disk attach' 
I have to use the image name, which is not the blob name.

**Comment by kmouss** [comment]
We auto generate the disk name in this case to avoid disk name conflicts. We are considering to add a command to update properties of the disk; it is under investigation currently - Thanks

**Comment by kmouss** [comment]
This is by design and not supported in the API currently. attach-new is design to create the disk for you while you specify the blob url.
