### ISSUE TITLE
How do you attach disks to a VM during VM Creation?

### ISSUE THREAD

**Issue by StephenOTT** [Azure/azure-xplat-cli#1545]
How do you attach disks to a VM during VM Creation?

Must be DURING the VM creation, not after the VM is created.

**Comment by StephenOTT** [comment]
@sylus

**Comment by kmouss** [comment]
Currently you have to create the VM and then attach or the other option currently is to create the VM using VM import with JSON. Thanks

**Comment by kmouss** [comment]
Closing for now, please reopen if necessary. Thank you
