### ISSUE TITLE
Azure vm disk attach properties (such as host-caching) not discoverable

### ISSUE THREAD

**Issue by kmouss** [Azure/azure-xplat-cli#1554]
I start by looking at all commands for “Azure vm disk” and see there is an attach command:
C:\>Azure vm disk -h
help:    Commands to manage your Virtual Machine data disks
help:
help:    Show details about a disk
help:      vm disk show [options] <name>
help:
help:    List disk images, or disks attached to a specified VM
help:      vm disk list [options] [vm-name]
help:
help:    Delete a disk image from personal repository
help:      vm disk delete [options] <name>
help:
help:    Upload and register a disk image
help:      vm disk create [options] <name> [source-path]
help:
help:    Upload a VHD to a storage account
help:      vm disk upload [options] <source-path> <blob-url> <storage-account-key>
help:
help:    Attach a data-disk to a VM
help:      vm disk attach [options] <vm-name> <disk-image-name>
help:
help:    Attach a new data-disk to a VM
help:      vm disk attach-new [options] <vm-name> <size-in-gb> [blob-url]
help:
help:    Detaches a data-disk attached to a VM
help:      vm disk detach [options] <vm-name> <lun>
help:
help:    Options:
help:      -h, --help  output usage information

Running without any commands provides no insight into the “options”
C:\>Azure vm disk attach

  error: missing required argument `vm-name'

Running with ‘-h’ seemed to be lucky. I still have no idea what the other options might be:
C:\>Azure vm disk attach -h

  error: option `-h, --host-caching <name>' argument missing

**Comment by kmouss** [comment]
Also if In this case if you run –help, it will give you more details, but there is spelling errors in the property: ReadyOnly -> ReadOnly (Behaviour -> Behavior)

azure vm disk attach --help
help:    Attach a data-disk to a VM
help:
help:    Usage: vm disk attach [options] <vm-name> <disk-image-name>
help:
help:    Options:
help:      -h, --help                 output usage information
help:      -v, --verbose              use verbose output
help:      --json                     use json output
help:      -h, --host-caching <name>  the caching behaviour of disk [None, ReadyOnly, ReadWrite]
help:      -d, --dns-name <name>      filter VMs for the specified DNS name
help:      -s, --subscription <id>    the subscription id

**Comment by kmouss** [comment]
Basically to summarize 3 issues:
1. -h is used as --help and as --host-cashing
2. the "Azure vm disk attach" command doesn't help me discover the options
3. I can only change the --host-cashing if I attach the disk, we need to be able to change it in an already attached disk.

**Comment by HimanshuBri** [comment]
@anuchandy. Working fine.

**Comment by anuchandy** [comment]
Closing this as fix is merged to upstream
