### ISSUE TITLE
Support deletion of blobs with snapshots

### ISSUE THREAD

**Issue by edevil** [Azure/azure-xplat-cli#1561]
I can't seem to be able to delete a blob which has a snapshot, or just manage blob snapshots in general.

**Comment by gangsir** [comment]
Hi, @edevil thank you for providing feedback to us. Sorry for late reply. We will add blob snapshot delete in next shipping sprint.

**Comment by yaxia** [comment]
We have added commands to support creating, copying and deleting the blob snapshot in the 0.10.1. Please take a try.
