### ISSUE TITLE
network vnet create destroys subscription's "local network"

### ISSUE THREAD

**Issue by peterlimayo** [Azure/azure-xplat-cli#1569]
I have a site-to-site vpn network setup, which requires "local network" specified.
But if I run "azure network vnet create" for a totally different network (separate range),
then it deletes the "local network", destroys the vpn gateway and lose connection
from local network to the vnet previously configured. Very painful to recover since I
have to reenter the network config for local network, start the azure vpn gateway
with a new key, that requires updating our local vpn gateway device.

The +new vnet through management portal works correctly, does not corrupt the
existing "local network".

Reported this to premier support already.

**Comment by HimanshuBri** [comment]
@anuchandy. Working fine.

**Comment by anuchandy** [comment]
Closing this as fix is merged to upstream
