### ISSUE TITLE
Feature request: add support for Publish-AzureServiceProject to the CLI

### ISSUE THREAD

**Issue by teomurgi** [Azure/azure-xplat-cli#1579]
Please the CLI has pretty good support of a lot of azure apis, but it's support for worker roles is quite absent... please add some sort of support for deploying to worker roles from xplat cli!!!

**Comment by mjyeaney** [comment]
Agreed - web/worker role support is strangely absent from the CLI...there is no other option for non-Win machines (no VS, no PowerShell). This is a big one!

**Comment by bureado** [comment]
I believe this is bound by availability of a tool to create cspkg files in non-Windows. Community efforts seem to have stalled though: https://github.com/cloud9ide/azure-cmdlet-node/issues/4

**Comment by yugangw-msft** [comment]
As bureado mentioned we do not have tools required to provide a good end to end experience on non windows platform such as .cspkg.
