### ISSUE TITLE
Need mechanism for tests to remove specific responses from nock recordings

### ISSUE THREAD

**Issue by jcookems** [Azure/azure-xplat-cli#1581]
The nock framework provided does not appear to provide a way for a test to request that specific responses be elided from the recording. This is useful is circumstances where a command has to poll and wait for a "success" response. The non-success messages can be skipped, which speeds up testing.

In particular, the Mobile Service `create` command polls the management endpoint until the app is created, waiting 5 seconds between requests. This means that when the test is run against the nock file, it will take about the same amount of time. In the past, when Mobile Service used their own test framework, it used something like this to remove the non-terminal responses:
```js
nockhelper.nock.recorder.play().forEach(function (line) { 
  if (line.indexOf('nock') >= 0) { 
    // skip async tracking operations that are other than success to speed things up 
    if (line.match(/\/operations\//) && !line.match(/\<Status\>Succeeded\<\/Status\>/)) { 
      return; 
    } 
    ...
```

It does not look like there is a way to do that with the current framework.

**Comment by markcowl** [comment]
@jcookems These don't necessarily need to be removed - for example, we could simply remove the wait interval so that polling occurs instantaneously.  I think that ensuring there aren't too many polls is a good safeguard.  Are you seeing long playback times, or are you concerned about the size of the mocks?

**Comment by jcookems** [comment]
The long playback time is the main issue. There was an issue with the Mobile Services polling code where we pinged the Azure management endpoint immediately after getting an "In Progress" response, flooding the endpoint with requests and going against best practices. Now it waits 5 seconds between requests, so the nocks won't speed up those operations.

Because the wait delay is in production code, I am uneasy to alter it just for testing purposes.

**Comment by phvannor** [comment]
As an alternative, we could add a environment setting override to the polling I suppose.  Something like process.env.AZURE_POLLING_INTERVAL || 5.  Then the test fw could set the interval to a small value (0.1?)  I'd worry that 0 may cause some unpredictable behavior in the test playback.  

It seems cleaner if the nock could adjust the recording, but possibly a general polling setting might be good to have anyways.

**Comment by markcowl** [comment]
@phvannor @jcookems this is the pattern we use in other repos, I would suggest using it here.  Closing for now
