### ISSUE TITLE
Allow AD setup on azure websites

### ISSUE THREAD

**Issue by luisrudge** [Azure/azure-xplat-cli#1582]
Currently, it's not possible to setup access control to a website with Azure Active Directory.

![image](https://cloud.githubusercontent.com/assets/941075/6181052/54b2325a-b314-11e4-84fa-f5e9e945c638.png)

**Comment by yugangw-msft** [comment]
Role Assignment is only possible in ARM mode.
```
azure config mode arm
azure resource list
```
In ARM mode everything is a resource in a resourcegroup. You can set access control on a resource group or on a resource for a particular user.

Website commands in arm mode are in development.
For now you can use the generic resource commands.

`` 
azure resource -h
```
