### ISSUE TITLE
Add support for changing cache policy of attached disk

### ISSUE THREAD

**Issue by kenazk** [Azure/azure-xplat-cli#1583]
Today, customers have to detach and reattach disks in order to change the cache policy on the disk because the only place that supports changing cache policy is on the attach. We need support to modify the cache policy of an already attached disk. This is a particularly bad scenario for customers with a bunch of disks they are trying to modify.

**Comment by HimanshuBri** [comment]
@anuchandy. Working fine.

**Comment by anuchandy** [comment]
Closing this as fix is merged to upstream
