### ISSUE TITLE
azure service create: How to set a static public IP address

### ISSUE THREAD

**Issue by jruix** [Azure/azure-xplat-cli#1586]
I'd like to have an static IP address for my cloud service, 

I've read in azure's documentation that now is not possible to set an static public ip address in an existent cloud service, so it has to be set  when a new cloud service is created.

I can't find the option to link the address I've reserved and the cloud service what I'm about to create.

Is it something that can be set up here or do I need to specify the static public ip address anywhere else?

**Comment by markcowl** [comment]
@jruix Thanks for the feedback, assigning to the appropriate service team

**Comment by anuchandy** [comment]
@jruix 

To assign a static-ip the service needs to have a deployment associated with it, in other words we assign static ip when we create the deployment.

For this, you need to use, --static-ip option in vm create command. The command creates a VM deployment under a cloud service and set the static-ip.

**Comment by sreekanthbs** [comment]
It is working fine with create vm with static-ip option.

**Comment by sauryadas** [comment]
@romangromov @FrankSiegemund  Can you guys please take a look at this?

**Comment by romangromov** [comment]
Adding @MikhailTryakhov for the same

**Comment by amarzavery** [comment]
Looks like the command is working. Hence closing this issue. Feel free to reopen if required.
