### ISSUE TITLE
How to upload a scheduled webjob?

### ISSUE THREAD

**Issue by fakedevil** [Azure/azure-xplat-cli#1587]
I am new to using Azure CLI and am looking through the list of commands here.
http://azure.microsoft.com/en-us/documentation/articles/command-line-tools

I don't see a way for me to upload a webjob and setup its schedule. Can someone help point me in the right direction?

**Comment by amitapl** [comment]
It is currently not supported

**Comment by amarzavery** [comment]
This wont be supported in ASM. Websites team will have to support this in ARM, whenever they have webapp commands ready.
