### ISSUE TITLE
Way to extend the CLI is needed

### ISSUE THREAD

**Issue by errordeveloper** [Azure/azure-xplat-cli#1588]
I originally wanted to submit to separate tickets, but it's probably better to describe the story.

In collaboration with @chanezon, I had been working on deploying Kubernetes in Azure.

Kubernetes requires a cluster of VMs and a virtual network, for provisioning these, I have written a [wrapper](https://github.com/errordeveloper/weave-demos/blob/471c463798764e198f287768b98a26bb74445b4a/coreos-azure/lib/azure_wrapper.js), which implements queueing of resource creation tasks along with a number of other things, including state files and ssh config generation.

My implementation of task queueing is rather poor and I really with I didn't have to write it, it'd be great to see some shape or form of this. Mine is lacking retry or error or anything of that sort, it just bails...

It would be great if this appeared as a sort of plugin, and I wouldn't have to come up with such kind of crufty wrapper. Something similar to what's there is in [AWS tools](https://github.com/aws/aws-cli/blob/develop/examples/new_command.py) would be awesome.

**Comment by matt-gibbs** [comment]
Thanks. We will take a look at potential improvements here.
