### ISSUE TITLE
azure cli via proxy

### ISSUE THREAD

**Issue by roldancer** [Azure/azure-xplat-cli#1593]
Hi All, 
I have the following error when I try to execute azure commands via a proxy, this is a generic proxy, it doesn't require authentication.

$ export HTTP_PROXY=http://proxy.bla.bla....:80
$ azure vm list

info:    Executing command vm list
/error:   The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.
info:    Error information has been recorded to /home/......./.azure/azure.err
error:   vm list command failed

Any idea ?

I have tried the following proxy variables, all of them return the same error.

HTTPS_PROXY
http_proxy
https_proxy

**Comment by active-low** [comment]
I have this exact same problem using the azure cli through my employer's proxy. Applying the proposed commit Azure#1593 fixes the issue for me.  Please merge!

**Comment by roldancer** [comment]
I have tested the pull request, it works OK, please merge it asap !!!!
