### ISSUE TITLE
azure vm endpoint create fails with lb-set option

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-xplat-cli#1594]
Trying add an endpoint which needs to be load balanced. Got below error:

azure vm endpoint create node2 -b httplb -o tcp 80 80
info:    Executing command vm endpoint create
+ Getting virtual machines
error:   name is not defined
info:    Error information has been recorded to c:\Users\.azure\azure.err

**Comment by HimanshuBri** [comment]
@anuchandy. Working fine.

**Comment by anuchandy** [comment]
Closing this as fix is merged to upstream
