### ISSUE TITLE
ASM: Add support for expandable disks

### ISSUE THREAD

**Issue by kenazk** [Azure/azure-xplat-cli#1598]
Add support for the ability data disks to up to 1 TB.

**Comment by anuchandy** [comment]
Will be adding a new command -  Under review

azure vm disk update-by-name &lt;disk-name&gt; --help
help:    Update properties of a data or OS disk registered in the disk repository
help:
help:    Usage: vm disk update-by-name [options] &lt;disk-name&gt;
help:
help:    Options:
help:      -h, --help                   output usage information
help:      -v, --verbose                use verbose output
help:      --json                       use json output
help:      -r, --resized-size &lt;number&gt;  the new size of OS disk of an OS image or data disk specified in GB (must be greater than current size)
help:      -s, --subscription &lt;id&gt;      the subscription id

**Comment by kmouss** [comment]
on plan for next CLI sprint after /build

**Comment by anuchandy** [comment]
To resolve this issue we need to call this REST API https://msdn.microsoft.com/en-us/library/azure/jj157205.aspx .

The request body needs to contain new size (as value of ResizedSizeInGB property).

```bash
Disk xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <Name>name-of-disk</Name>
  <Label>description-of-disk</Label>
  <ResizedSizeInGB>resized-size-in-GB</ResizedSizeInGB>
</Disk>
```

But I don’t a function in node SDK which conform to this. https://raw.githubusercontent.com/Azure/azure-sdk-for-node/dev/lib/services/computeManagement/lib/computeManagementClient.js

**Comment by huangpf** [comment]
It seems .NET SDK has it: 
https://github.com/Azure/azure-sdk-for-net/blob/master/src/ServiceManagement/Compute/ComputeManagement/Generated/VirtualMachineDiskOperations.cs

**Comment by anuchandy** [comment]
Tried generating the sdk from the latest spec and it has the method beginUpdatingDisk which set 'ResizedSizeInGB' property.

The sdk in production does not have this method, so the sdk needs to be refreshed.

**Comment by sauryadas** [comment]
@amarzavery we plan on implementing this in ARM but not in ASM.

**Comment by trentmswanson** [comment]
It's sad to see this was not implemented in ASM. There are still so many people that need to continue using ASM. I will give @anuchandy workaround a try.
