### ISSUE TITLE
ASM: Should prevent or warn about creation of Linux VMs without SSH keys or password option

### ISSUE THREAD

**Issue by bureado** [Azure/azure-xplat-cli#1601]
When creating a Linux VM, if no -e option is passed it's assumed SSH keys will be used, even with a password being provided. However, when you don't pass -e and you don't provide the key xplat-cli still creates the VM, but no user can log into the newly created VM because if no -e option is passed waagent will not allow password authentication, and because no SSH key was provided, there is no other auth method available for SSH.

To reproduce (and this might be a function of the specific flags used, or the image used, or the waagent version used)

    azure vm create --vm-size Basic_A3 --virtual-network-name MyNet \
    --subnet-names MySubNet --availability-set MyAS MyVM MyImage MyUser MyPassword

Then, when trying to SSH to MyVM with MyUser:

    Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

The image tested was an EL6 image but there's anecdotal evidence that this happens with other images, too. Here are potential outcomes:

1. -e 22 to be assumed if no SSH key is provided
2. vm create to fail if no SSH key and no -e option is provided, prompting user to either provide a key or provide a -e option
3. waagent to always allow password authentication regardless of the vm create parameters

**Comment by palonsoro** [comment]
Regarding to your suggestions, I should point the following: 
As `azure help vm create` command describes, there is a parameter called `--no-ssh-password` a.k.a. `-P` which "indicates that the password should be removed when using --ssh-cert".
By reading this, one may think that there should be no reason to disallow password login unless `--no-ssh-password` parameter is provided.
Therefore, I personally think that the most logic solution would be the third one you proposed, but taking `--no-ssh-password` parameter into account and disallowing password login whenever it is provided.

**Comment by kmouss** [comment]
Thank you, the user might have multiple VMs in the same Cloud Service; in which case -e will be required to specify a different SSH port number. Will investigate failing the create if the user misses to enter either -e or SSH key.

**Comment by palonsoro** [comment]
Ok. I understand your point regarding Cloud Services with multiple VMs. However, the strange thing here is that, when -e is not passed, an sshd is still available at port 22, but reconfigured to disallow password authentication (making impossible to log in due to the absence of a SSH key). This actually is the main problem.

**Comment by squillace** [comment]
+1. there should be no possibility that a user could create an unreachable VM from create **accidentally**. Can anyone think of a scenario in which a VM is unreachable? Perhaps VMs are deployed in a service and only do local/private processing and communication. But even in that case, at the very least there should be a warning and acceptance step (with an explicit --no-warn override in the cluster creation case) before an unconnectable VM is created, yes?

**Comment by sreekanthbs** [comment]
Verified and working fine
<pre>
<code>
C:\Jul2015\Jul-14\azure-xplat-cli-dev>node bin/azure vm create LinuxVMXplat "0b11de9248dd4d87b18621318e037d37__RightImage-Ubuntu-12.04-x64-v13.4" azureuser -l "
West US" -t "C:/.ssh/github_rsa.pub"
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
error:   --no-ssh-password and --ssh-cert can only be used with --ssh or --no-ssh-endpoint parameter
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   vm create command failed
</code>
</pre>

**Comment by tsaarni** [comment]
Sorry for spamming above.  Unfortunately I was not aware that mentions in fork generate messages into forked repo.

**Comment by sauryadas** [comment]
@bureado closing this. if still not fixed please reopen
