### ISSUE TITLE
No way to add a subnet to an existing vnet

### ISSUE THREAD

**Issue by pandemosth** [Azure/azure-xplat-cli#1604]
Unless I am missing something, there doesn't appear to be a way to add a subnet to an existing vnet using the cli (in the portal there is an 'Add subnet' button on the vnet config page)

**Comment by anuchandy** [comment]
To add new subnet, follow below steps:

1. Use 'azure network export' to export current network configuration to a file as json
2. Update the json file with details of new vnet.
3. Import this json file using 'azure vm import'

Refer wiki https://github.com/Azure/azure-xplat-cli/wiki/Network-Management for more details.

**Comment by pandemosth** [comment]
Thanks I found that in the docs, but it's not a great mechanism for automated config management when you have multiple environments within the same subscription - ideally adding a subnet to a test environment should not require you to edit a global config that can also impact your production environment.

Improvements would be 
- support adding/removing subnets directly via 'azure network vnet' command
- allow individual vnet configs to be exported and imported rather than all configs under subscription

Cheers

**Comment by anuchandy** [comment]
@pandemosth ,  glad that export/import worked for you. 

Yes, we have a plan to implement additional commands so that user don't have to use export-import.

**Comment by frntn** [comment]
+1 on this issue. 
This is a very important feature for automation !

Looking forward to see this feature released very soon

**Comment by anuchandy** [comment]
We started implementing this, will update this thread once testing and upstream merging is done

**Comment by anuchandy** [comment]
This is fixed in this branch https://github.com/MSOpenTech/azure-xplat-cli/tree/dev-asm-network, fix will be merged in the next release.

**Comment by frntn** [comment]
Great work :+1: 
Thanks for the update

**Comment by sreekanthbs** [comment]
It is working fine.
<pre>
<code>
C:\Jun2015\25-Jun\azure-xplat-cli-dev-asm-network>node bin/azure network vnet subnet create vnetsree subnet_sree -a 10.32.0.0/15
info:    Executing command network vnet subnet create
+ Looking up network configuration
+ Creating subnet "subnet_sree"
+ Setting network configuration
+ Looking up the subnet "subnet_sree"
+ Looking up network configuration
data:    Name                            : subnet_sree
data:    Address prefix                  : 10.32.0.0/15
info:    network vnet subnet create command OK

C:\Jun2015\25-Jun\azure-xplat-cli-dev-asm-network>node bin/azure network vnet show vnetsree
info:    Executing command network vnet show
+ Looking up the virtual network sites
data:    Name                            : vnetsree
data:    Location                        : West US
data:    State                           : Created
data:    Address space                   : 10.0.0.0/8
data:    Subnets:
data:      Name                          : Subnet-1
data:      Address prefix                : 10.0.0.0/11
data:
data:      Name                          : subnet_sree
data:      Address prefix                : 10.32.0.0/15
data:
info:    network vnet show command OK
</code>
</pre>
