### ISSUE TITLE
ASM: Improper JSON for "azure vm image show"

### ISSUE THREAD

**Issue by crawford** [Azure/azure-xplat-cli#1611]
Running `azure vm image show --json 2b171e93f07c4903bcad35bda10acf22__CoreOS-Beta-584.0.0` results in:

```json
{
  "location": "East Asia;Southeast Asia;Australia East;Australia Southeast;Brazil South;North Europe;West Europe;Japan East;Japan West;Central US;East US;East US 2;North Central US;South Central US;West US",
}
```

It would be much easier to parse if it were a list (maybe the key should be called locations):

```json
{
  "locations": [
    "East Asia",
    "Southeast Asia",
    "Australia East",
    "Australia Southeast",
    "Brazil South",
    "North Europe",
    "West Europe",
    "Japan East",
    "Japan West",
    "Central US",
    "East US",
    "East US 2",
    "North Central US",
    "South Central US",
    "West US"
  ]
}
```

**Comment by ahmetalpbalkan** [comment]
That might be because of compatibility reasons. The respective REST API is actually returning the Location field of the images like that separated with `;`.

**Comment by crawford** [comment]
Shouldn't the CLI fix that up? It seems reasonable to do the conversion once in the CLI, rather than requiring everyone to implement their own solution.

**Comment by kmouss** [comment]
This is fixed and will be part of next Azure CLI update.

**Comment by devigned** [comment]
I'm going to reopen this issue for the time being. @ahmetalpbalkan or @crawford would you verify the defect is resolved by the patch @amarzavery applied?

**Comment by ahmetalpbalkan** [comment]
Thanks @devigned. I think we must be closing the issues **until they're fixed in the stable release**. Otherwise people might report the same issue multiple times (will end up with duplicates). Open issues are more searchable.

**Comment by crawford** [comment]
@devigned LGTM, thank you.

**Comment by kmouss** [comment]
This fix has been merged. Please re-open if you still see the issue.
