### ISSUE TITLE
Make "azure login" error message friendlier

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1612]
I'm trying to use a personal account with `azure login`, I know it's not gonna work but it fails with an error which is hard to understand.

```
$ azure login
info:    Executing command login
warn:    Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
Username: ahmet@ahmetalpbalkan.com
Password: ********
+ Authenticating...
error:   Server returned an unknown AccountType: undefined
error:   Cannot read property 'Symbol(formatted stack trace)' of undefined
info:    Error information has been recorded to /Users/alp/.azure/azure.err
error:   login command failed
```

The part bothers me both is `Server returned an unknown AccountType: undefined`. Take this as an UX bug please.

@guangyang @squillace

**Comment by amarzavery** [comment]
@ahmetalpbalkan 
This is a typo in the adal-node module consume by xplat cli. This module is published by the Active Directory team.

```
TokenRequest.prototype.getTokenWithUsernamePassword = function(username, password, callback) {
  this._log.info('Acquiring token with username password');

  this._userId = username;
  this._getToken(callback, function(innerCallback) {
    var self = this;
    this._userRealm = this._createUserRealmRequest(username);
    this._userRealm.discover(function(err) {
      if (err) {
        innerCallback(err);
        return;
      }

      switch(self._userRealm.accountType) {
        case AccountType.Managed:
          self._getTokenUsernamePasswordManaged(username, password, innerCallback);
          return;
        case AccountType.Federated:
          self._getTokenUsernamePasswordFederated(username, password, innerCallback);
          return;
        default:
          innerCallback(self._log.createError('Server returned an unknown AccountType: ' + self._userRealm.AccountType));
      }
    });
  });
```

This should be self._userRealm.**a**ccountType instead of uppercase A.

Once this change is done, the error message looks like this:

```
Server returned an unknown AccountType: unknown
```

**Comment by ahmetalpbalkan** [comment]
@amarzavery yeah, that's my point. Why do we have an error message like `Server returned an unknown AccountType: unknown`?

**Comment by amarzavery** [comment]
@ahmetalpbalkan 
As it  is an unknown account type. If the account type is not Managed or Federated (look at the above code) then it falls into the **unknown** category. Which is the right thing.

**Comment by ahmetalpbalkan** [comment]
@amarzavery yes, you still prove my point.

I'm a user. I don't care about your internal string for handling the account types. Just show me a human readable error message like 

> This account is not an Active Directory account. You cannot use it with "azure login" command.

This is what we call UX bug.

**Comment by squillace** [comment]
+1. This is confusing also because MS also changes its account brand or marketing names, too. AD is a solid name that makes sense.

**Comment by johngossman** [comment]
+1. Error message is very confusing.

**Comment by koistya** [comment]
+1. This is also relevant to other azure-cli commands, e.g. `azure site domain add ...`

```
Tue Mar 10 2015 18:08:08 GMT+0300 (Russia TZ 2 Standard Time):
[TypeError: Cannot read property 'Symbol(formatted stack trace)' of undefined]
TypeError: Cannot read property 'Symbol(formatted stack trace)' of undefined
    at TypeError.stack (C:\Program Files\nodejs\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:224:27)
    at C:\Program Files\nodejs\node_modules\azure-cli\node_modules\eyes\lib\eyes.js:183:19
    at Array.forEach (native)
    at stringifyObject (C:\Program Files\nodejs\node_modules\azure-cli\node_modules\eyes\lib\eyes.js:181:10)
    at C:\Program Files\nodejs\node_modules\azure-cli\node_modules\eyes\lib\eyes.js:129:38
    at stringify (C:\Program Files\nodejs\node_modules\azure-cli\node_modules\eyes\lib\eyes.js:131:7)
    at Object.eyes.inspect (C:\Program Files\nodejs\node_modules\azure-cli\node_modules\eyes\lib\eyes.js:53:16)
    at Object.log.json (C:\Program Files\nodejs\node_modules\azure-cli\lib\util\logging.js:84:22)
    at callback (C:\Program Files\nodejs\node_modules\azure-cli\lib\cli.js:216:17)
    at __propagate (C:\Program Files\nodejs\node_modules\azure-cli\node_modules\streamline\lib\callbacks\runtime.js:124:4)

```

**Comment by RandalliLama** [comment]
The original issue is tracked at AzureAD/azure-activedirectory-library-for-nodejs#43.

**Comment by markcowl** [comment]
Closing, as this is a bug in AAD code, not in the xplat cli

**Comment by ahmetalpbalkan** [comment]
@markcowl can you please paste the error message that is going to be shown once it is fixed on AAD? I am not claiming this is a code bug, it's a problem with the user-friendliness of the CLI error messages.

**Comment by wesyao** [comment]
I'm still seeing this as an error message. This doesn't provide much context.
