### ISSUE TITLE
ARM mode with publishsettings fails with non-friendly message

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1614]
I set `azure config mode arm` and I run `azure account --help` and it shows that I can actually use .publishsettings file and I used `azure account download` then I used `azure account import` then I set the active subscription correctly. 

However when I run a command in authenticated mode. It fails in an ugly way with the following error message:

```
$  azure group list
info:    Executing command group list
+ Listing resource groups
error:   Authentication failed. The 'Authorization' header is not present or provided in an invalid format.
error:   Cannot read property 'Symbol(formatted stack trace)' of undefined
info:    Error information has been recorded to /Users/alp/.azure/azure.err
error:   group list command failed
```

I can't use a corporate account (because the account isn't) and I'm clueless about how can I possibly authenticate. **As a user, please tell me I'm using a wrong method to authenticate; not the Authorization header is invalid.**

I know this stuff is still in preview but I just wanted to make sure you guys are aware of the situation. @guangyang

**Comment by markcowl** [comment]
@ahmetalpbalkan Will look at improving the error message, or perhaps making the certificate cmdlets unabailable in ARM mode.

You need to have an OrgID account to authenticate - this is an AAD restriction. Tis blog post has details on how to create an org id account for your subscription if you're currently using AAD credentials:

http://azure.microsoft.com/blog/2014/08/27/azure-automation-authenticating-to-azure-using-azure-active-directory/

**Comment by ahmetalpbalkan** [comment]
@markcowl sounds perfect, can we have this URL in the error message? I already know the solution.

**Comment by matt-gibbs** [comment]
@ahmetalpbalkan, @johngossman 
The link might be an ok temporary solution. Making the commands unavailable would be better. Simplifying the auth configuration would be the longer-term even better solution.

**Comment by amarzavery** [comment]
@ahmetalpbalkan - The corresponding PR to improve the error message is [here] (https://github.com/Azure/azure-xplat-cli/pull/1637)

**Comment by amarzavery** [comment]
```
D:\sdk\xplat\azure-sdk-tools-xplat>node bin\azure group list
info:    Executing command group list
+ Listing resource groups
error:   Certificate based Authentication is not supported in current mode: 'arm'. Please authenticate using an organizational account via 'azure login' command.
info:    Error information has been recorded to C:\Users\amzavery\.azure\azure.err
error:   group list command failed

```

**Comment by amarzavery** [comment]
Fixed.
