### ISSUE TITLE
What's your development environment setup in Windows?

### ISSUE THREAD

**Issue by sebagomez** [Azure/azure-xplat-cli#1617]
I forked and cloned the project and I want to start "looking around". I found a azure.cli.sln file under tool/windows but I can't open it because I don't have Wix installed.I also noticed there's a wix folder so, should I run something from there? Is there a doc to help me start?

Thanks

**Comment by markcowl** [comment]
@sebagomez What are you trying to do?  The sln and wix file are just for creating the windows installer.  You can install the cli by just using npm install -g <path-to-repo-root>

**Comment by sebagomez** [comment]
I was just trying to get it to debug it...

**Comment by amarzavery** [comment]
@sebagomez - You can use visual studio for development in node.js http://nodejstools.codeplex.com/
You can also use sublime text and put console.log() statements to debug.

**Comment by sebagomez** [comment]
nice, thanks
