### ISSUE TITLE
Consider using $HOME/.config/azure

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1619]
I realized many things installed on my Linux dev machine are using `~/.config/project/` path to store their config. `gcloud` cli is another example. I'm wondering if we can be good citizens here and keep user's $HOME less crowded and use `~/.config/azure/*` instead.

**Comment by markcowl** [comment]
@ahmetalpbalkan XPlat cli supports many platforms, and we have standardized on using $/.azure for user-specific settings.  We are unlikely to use different locations for different platforms.
