### ISSUE TITLE
ASM: removing --ssh but specifying an admin/pw disables password auth on linux VM

### ISSUE THREAD

**Issue by magaal** [Azure/azure-xplat-cli#1625]
Hi - I'm deploying VM's via the x-plat CLI and if I remove the "--ssh" option, but do not specify a key, but do have options for admin name and password, it seems like it passes to the provisioning the command to disable password based SSH. I have my keys embedded in my image but I also need to preserve password SSH. I noticed this when provisioning a new VM from my clone:

2015/03/10 16:12:05 Disabled SSH password-based authentication methods.

Snippet of the command I'm using to provision:

azure vm create --connect --affinity-group $affinityGroupName --vm-size $clusterinstanceSize --vm-name $vmName  --virtual-network-name $vnetName --subnet-names $subnetName $dnsName $cloneImageName $adminUserName $adminPassword)

**Comment by bureado** [comment]
+1, seems dup of #1601

**Comment by kmouss** [comment]
We added a new option under this PR: https://github.com/Azure/azure-xplat-cli/pull/1667

**Comment by babumuralidharan** [comment]
Bug fix part of release 0.9.3. Closing this issue.
