### ISSUE TITLE
Update API version to '2014-02-14'

### ISSUE THREAD

**Issue by kmouss** [Azure/azure-xplat-cli#1634]
Change    this.apiVersion = '2012-02-12';
to  this.apiVersion = '2014-02-14' or later.

in Azure\CLI\node_modules\azure-storage-legacy\lib\blob\blobservice.js

**Comment by kmouss** [comment]
Need to be assigned to the Storage. This code in Azure SDK for node for Storage.

**Comment by yaxia** [comment]
If you need the new features in storage version 2014-02-14, replacing azure-storage-legacy with azure-storage may be a reasonable option. @slepox

**Comment by kmouss** [comment]
Target fix after /build spring .19

**Comment by amarzavery** [comment]
@kmouss - Has this been fixed? Should we close this issue?
