### ISSUE TITLE
add "azure vm size list"

### ISSUE THREAD

**Issue by avieru** [Azure/azure-xplat-cli#1636]
It would be great to add "azure vm size list", similar to "azure vm image list", so that I could look up sizes of vm's right via cli and not bing/google.

Thanks

**Comment by anuchandy** [comment]
@avieru You can use 'azure vm location list --json' command to see the VM sizes supported in each region. Note that not all sizes are supported in all regions.

**Comment by avieru** [comment]
Thanks, it helps.

**Comment by colemickens** [comment]
The workaround described earlier no longer works, as `azure vm location list` is no longer a command and `azure location list` does not include vm sizes per location. Please suggest another workaround, thanks.

**Comment by vijayrajah** [comment]
Commenting here, so it might be usefull for someone

I was able to use azure vm sizes --location <> to get the VM sizes

Example
```
# azure vm sizes --location eastus2
info:    Executing command vm sizes
+ Listing virtual machine sizes available in the location "eastus2"
data:    Name              CPU Cores  Memory (MB)  Max data-disks  Max data-disk Size (MB)  Max OS-disk Size (MB)
data:    ----------------  ---------  -----------  --------------  -----------------------  ---------------------
data:    Standard_A0       1          768          1               20480                    1047552
data:    Standard_A1       1          1792         2               71680                    1047552
.
data:    Standard_DS14     16         114688       32              229376                   1047552
info:    vm sizes command OK
```
