### ISSUE TITLE
detecting "azure site create <duplicate_site>"

### ISSUE THREAD

**Issue by requiredfield** [Azure/azure-xplat-cli#1641]
As recently as a week or two ago, if you ran `azure site create` with an already-created site name, the process would exit nonzero, allowing you to detect that it was an already-created site name (or at least some kind of failure to create a new site by that name) and try a new one.

Now if you try this, the process exits 0. Also, I'm pretty sure previously there was some indication of an error in the output, but now the output is:
```
info:    Executing command site create
+ Getting sites
info:    Updating existing site
+ Getting locations
info:    site create command OK
```
(Not quite sure what gets updated about the existing site when you do this.)

So to detect when you've attempted to create a duplicate site, you now have to check whether the output contains the string "Created website at" vs. "Updating existing site".

Is this likely to change again in the future, or is there a stable way to detect an attempt to create a duplicate site going forward?

Thanks for any help.

P.S. I tried passing the `--json` option on the theory that its output would be more friendly to machine consumption, but this causes nothing to be output whatsoever. :hankey:

**Comment by requiredfield** [comment]
Meant to say, this is with 0.8.15 and 0.8.16 (latest release as of now).

**Comment by amarzavery** [comment]
I think this has been like this, since a long time. I tested against the latest version 0.8.16 and a slightly older version 0.8.11. 

If you create an empty site
```
azure site create testfoo --location "West US"
```

Now, you want to add git support to it, you will still use the site create command

```
azure site create testfoo --location "West US" --git --gitusername awesomeness
```

This will update the exisiting site instead of complaining that the site exists.

If you try to create a site with the same name at a different location, it will throw an error saying that the site already exists.

**Comment by requiredfield** [comment]
Thanks for explaining @amarzavery. Didn't realize you could run `azure site create` on top of an existing site to e.g. add git support.

In the case of a no-op, however, I'd expect it to indicate nothing changed rather than outputting "Updating existing site".

And it'd be great if there were a better way to detect results of a command (from e.g. a script calling it) than string comparison, but I guess that's a more general ticket.
