### ISSUE TITLE
ARM: Xplat has a restriction where $schema cannot be specified in the template parameters file

### ISSUE THREAD

**Issue by clamanna** [Azure/azure-xplat-cli#1655]
The same file seems to be working on PSH fine. This is the parameter file which causes problems: 
{
    "$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "adminPassword": {
            "value": "user@123"
        }
    }
}

**Comment by markcowl** [comment]
@clamanna sounds like a great enhancement, assigning to the ARM team, who owns the xplat story for ARM

**Comment by vivsriaus** [comment]
This has been resolved, and will be included in the next Azure CLI release

**Comment by amarzavery** [comment]
@vivsriaus - Has this been resolved? If yes, then we can close this.
