### ISSUE TITLE
Add an equivalent to Test-AzureResourceGroupTemplate to xplat cli

### ISSUE THREAD

**Issue by clamanna** [Azure/azure-xplat-cli#1656]
The xplat cli is missing an equivalent to Test-AzureResourceGroupTemplate (perhaps called azure group deployment test ...?)

PS C:\Users\chlama\Desktop> get-help Test-AzureResourceGroupTemplate

NAME
    Test-AzureResourceGroupTemplate

SYNTAX
    Test-AzureResourceGroupTemplate -ResourceGroupName <string> -TemplateFile <string> [-StorageAccountName <string>]
    [-TemplateVersion <string>] [-Profile <AzureProfile>]  [<CommonParameters>]

    Test-AzureResourceGroupTemplate -ResourceGroupName <string> -TemplateParameterObject <hashtable> -TemplateUri
    <string> [-TemplateVersion <string>] [-Profile <AzureProfile>]  [<CommonParameters>]

    Test-AzureResourceGroupTemplate -ResourceGroupName <string> -TemplateParameterObject <hashtable>
    -GalleryTemplateIdentity <string> [-TemplateVersion <string>] [-Profile <AzureProfile>]  [<CommonParameters>]

    Test-AzureResourceGroupTemplate -ResourceGroupName <string> -TemplateParameterObject <hashtable> -TemplateFile
    <string> [-StorageAccountName <string>] [-TemplateVersion <string>] [-Profile <AzureProfile>]  [<CommonParameters>]

    Test-AzureResourceGroupTemplate -ResourceGroupName <string> -TemplateParameterFile <string>
    -GalleryTemplateIdentity <string> [-TemplateVersion <string>] [-Profile <AzureProfile>]  [<CommonParameters>]

    Test-AzureResourceGroupTemplate -ResourceGroupName <string> -TemplateParameterFile <string> -TemplateFile <string>
    [-StorageAccountName <string>] [-TemplateVersion <string>] [-Profile <AzureProfile>]  [<CommonParameters>]

    Test-AzureResourceGroupTemplate -ResourceGroupName <string> -TemplateParameterFile <string> -TemplateUri <string>
    [-TemplateVersion <string>] [-Profile <AzureProfile>]  [<CommonParameters>]

    Test-AzureResourceGroupTemplate -ResourceGroupName <string> -GalleryTemplateIdentity <string> [-TemplateVersion
    <string>] [-Profile <AzureProfile>]  [<CommonParameters>]

    Test-AzureResourceGroupTemplate -ResourceGroupName <string> -TemplateUri <string> [-TemplateVersion <string>]
    [-Profile <AzureProfile>]  [<CommonParameters>]

**Comment by amarzavery** [comment]
@clamanna 
Is this what you were looking for?

```
C:\Users\charmi>azure group template validate -h
help:    Validates a template to see whether it's using the right syntax, resource providers, resource types, etc.
help:
help:    Usage: group template validate [options] <resource-group>
help:
help:    Options:
help:      -h, --help                                output usage information
help:      -v, --verbose                             use verbose output
help:      --json                                    use json output
help:      -g --resource-group <resource-group>      the name of the resource group
help:      -y --gallery-template <gallery-template>  the name of the template in the gallery
help:      -f --template-file <template-file>        the path to the template file in the file system
help:      --template-uri <template-uri>             the uri to the remote template file
help:      --template-version <template-version>     the content version of the template
help:      -s --storage-account <storage-account>    the storage account where we will upload the template file
help:      -p --parameters <parameters>              a JSON-formatted string containing parameters
help:      -e --parameters-file <parametersFile>     a file containing parameters
help:      --subscription <subscription>             the subscription identifier

```

**Comment by clamanna** [comment]
Yes, perfect! I was looking in azure group deployment's branch of commands. Appreciate it.
