### ISSUE TITLE
ASM: Endpoint creation has no option to set ProbeInterval

### ISSUE THREAD

**Issue by juergenpf** [Azure/azure-xplat-cli#1669]
vm endpoint create doesn't allow me to specify the ProbeInterval.

**Comment by idofl** [comment]
Would also like to see this added. It exists in the PowerShell cmdlets.
Also the ProbeTimeout of course

**Comment by HimanshuBri** [comment]
@anuchandy  yes now there is a option available in vm endpoint create for ProbeInterval.
But its giving error when try to use that.
<pre>
<code>
C:\June\24june\azure-xplat-cli-dev>node bin/azure vm endpoint create DNdjava6 27 -k 27 -n vmEndpt1 -o tcp -m 15 -b LbSetTest1 -e 20 -f 40
info:    Executing command vm endpoint create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
error:   Value '0' specified for parameter 'LoadBalancerProbe.Port' is invalid. Allowed values are 'a number between 1 to 65535'.
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   vm endpoint create command failed


C:\June\24june\azure-xplat-cli-dev>node bin/azure vm endpoint create DNdjava6 27 -k 27 -n vmEndpt1 -o tcp -m 15 -b LbSetTest1
info:    Executing command vm endpoint create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    vm endpoint create command OK
</code>
</pre>

**Comment by sauryadas** [comment]
@romangromov Can you please verify this and close?

**Comment by romangromov** [comment]
@sauryadas sure, checked, working fine:

```
>azure vm endpoint create tryaVM 80 -n TestEndpoint --protocol TCP --probe-interval 18 --probe-port 60

info:    Executing command vm endpoint create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    vm endpoint create command OK

>azure vm endpoint list tryaVM

info:    Executing command vm endpoint list
+ Getting virtual machines
data:    Name            Protocol  Public Port  Private Port  Virtual IP    EnableDirectServerReturn  Load Balanced
data:    --------------  --------  -----------  ------------  ------------  ------------------------  -------------
data:    PowerShell      tcp       5986         5986          13.90.249.48  false                     No
data:    Remote Desktop  tcp       63504        3389          13.90.249.48  false                     No
data:    TestEndpoint    tcp       80           80            13.90.249.48  false                     No
data:    tryaEndpoint    tcp       12345        123           13.90.249.48  false                     No
```

Hence closing.
