### ISSUE TITLE
Deprecated "azure site" alternatives

### ISSUE THREAD

**Issue by mattcanty** [Azure/azure-xplat-cli#1670]
I've been trying to find a solution to configure azure **site** diagnostics. Azure Cmdlets don't appear to support them. I can see from your help in 0.8.17 that the commands have been deprecated.

Are there any alternatives around this. Ideally no manual steps as we have been able to configure all other settings via scripts.

Thanks

**Comment by NaveenGoli** [comment]
we are developing new arm based cmdlets, site diagnostics  will be available in that.
