### ISSUE TITLE
ASM: "azure vm endpoint acl-rule set"

### ISSUE THREAD

**Issue by secjex** [Azure/azure-xplat-cli#1672]
Cannot specify `--remote-subnet`

`azure vm endpoint acl-rule set vm_name endpoint_name order`
return
`error:   one of the optional parameter --new-order, --action, --remote-subnet or --description is required`

`azure vm endpoint acl-rule set vm_name endpoint_name order --remote-subnet new_subnet`
return
`error: unknown option --remote-subnet`

**Comment by sauryadas** [comment]
@romangromov can you please verify this and close?

**Comment by romangromov** [comment]
@sauryadas checked, working fine:
```
>azure vm endpoint acl-rule set tryaVm TestEndpoint 1 --remote-subnet "10.0.0.0/25"

info:    Executing command vm endpoint acl-rule set
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    vm endpoint acl-rule set command OK
```
But foundf another one related issue, started here https://github.com/Azure/azure-xplat-cli/issues/2851

Closing this now.
