### ISSUE TITLE
help for "azure vm create --connect" is incorrect

### ISSUE THREAD

**Issue by dsk-2015** [Azure/azure-xplat-cli#1676]
The help for this sub-command says it connects to an existing VM. But then it goes on to create a VM. The help for "--connect" is misleading; according to Ralph, the main writer on XPlat, "--connect" is used to connect a new VM to an existing cloud service. It always creates a new VM and --connect must be followed with the existing service' name. The help needs to be updated with this info. 

![image](https://cloud.githubusercontent.com/assets/11432319/7015292/3f1a9cd4-dc86-11e4-8c52-066d10857ac4.png)

**Comment by ruslangabitov** [comment]
Fixed this issue in MSOpenTech repo: https://github.com/MSOpenTech/azure-xplat-cli/tree/dev

**Comment by babumuralidharan** [comment]
Bug fix part of release 0.9.3. Closing this issue.
