### ISSUE TITLE
Linux 'vm create' with --ssh-cert & --no-ssh-password prompts for password

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1680]
If you go to the current Azure Portal and create a Linux VM (from Gallery, not Quick Create) and provide SSH key, it asks you for username and doesn't ask for password.

However xplat-cli with `--ssh-cert` and `--no-ssh-password` prompts you for a password, I don't know why it is enforced:

```
azure vm create -e \
    -z "Basic_A1" \
    -l "South Central US" --ssh-cert=/Users/alp/.ssh/id_rsa.pub \
    linuxtestvm \
    b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_2_LTS-amd64-server-20150309-en-us-30GB \
    azureuser
info:    Executing command vm create
+ Looking up image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_2_LTS-amd64-server-20150309-en-us-30GB
Enter VM 'azureuser' password:
```

Instead, it should proceed creating the VM. There's a discrepancy between portals and the CLI here.

cc: @paulmey @squillace

**Comment by ahmetalpbalkan** [comment]
Actually in the docs I see 

> **UserPassword**: Required in LinuxProvisioningConfiguration. Specifies the password for the user account. Passwords must be 6 to 72 characters long.

https://msdn.microsoft.com/en-us/library/azure/jj157194.aspx

Maybe portal provides a default password? In any case we have a discrepancy there.

**Comment by paulmey** [comment]
Docs must be wrong... :wink: 
packer-azure provisions with ssh-key only: https://github.com/MSOpenTech/packer-azure/blob/master/packer/builder/azure/driver_restapi/request/CreateVirtualMachineDeployment.go#L28-L41

**Comment by ahmetalpbalkan** [comment]
@paulmey Sounds like a RDFE bug then.

**Comment by paulmey** [comment]
@ahmetalpbalkan There is no `<UserPassword>` tag in the xml blob that goes to RDFE, so it's not really empty, it's just not there.

**Comment by squillace** [comment]
what does this mean? Can I pass ""??? I should try it....

**Comment by ahmetalpbalkan** [comment]
@squillace nope you can't. Because xplat-cli duplicates the password criteria logic that exists in the API on the client code. I don't know why this was the case bad IMO poor choice.

**Comment by jeffwilcox** [comment]
This one has regressed a ton of times, def. good one to fix. Part of the problem was that there was obfuscation (not intended) between the serialization code paths.

I never use a password for a VM so this is a major important one to fix!

**Comment by ahmetalpbalkan** [comment]
@jeffwilcox actually I realized this is a false report. I forgot `--no-ssh-password` above. Do you see the any issues? If not, I'll close this.

**Comment by jeffwilcox** [comment]
I don't see any issues right now, either. Good. :-) Hooray. Thanks...
