### ISSUE TITLE
'vm create' --ssh-cert argument doesn't accept RSA format

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1681]
Our REST API and XPLAT CLI accepts .PEM formats as ssh keys.

This is not the common practice in the cloud world and nobody stores their SSH keys in PEM format, simply because that's not what the ssh process uses or what ssh-keygen generates. PEM format is always converted through **OpenSSH** toolkit, specifically openssl(.exe) –a *horrible* tool which:

-  doesn't properly work on windows
- doesn't work the same way on Mac (as linux) and requires separate docs for Mac OS X.
- at least works on linux well but hey who's still using Linux for their devops machines?

In our new portal we allow SSH Keys in RSA format:
> ![](http://cl.ly/image/1F3p0K1r3m2z/Image%202015-04-07%20at%203.29.45%20PM.png)

I was quite frustrated when I did

    azure vm create -e --ssh-cert=~/.ssh/id_rsa.pub [...]

because first #1679 then #1680 and now this. I simply can't use the public key I've been using on AWS/GCE/DigitalOcean on Azure... 

Even though REST API doesn't accept RSA format, XPLAT CLI should be smartly should allow RSA format as well and convert that to PEM under the hood because **user doesn't care**.

Also it's notoriously hard to convert my existing public key (`id_rsa.pub`) to a PEM format, I had to re-create public key as PEM using my private key `id_rsa` with the openssl command.

We have a discrepancy between products here (new portal vs xplat-cli). I think **xplat-cli should just work fine** with RSA format (what `ssh-keygen` generates) as well. 

cc: @squillace

**Comment by squillace** [comment]
In addition, perhaps I'm reading the openssl docs incorrectly -- and I'd like to know if this were the case! -- but azure docs say to create a new public key to give to the azure vm thus:


> Generate a Key from an Existing OpenSSH Compatible Key

> The previous example describes how to create a new key for use with Azure. In some cases you may already have an existing OpenSSH compatible public & private key pair and wish to use the same keys with Azure.

> OpenSSH private keys are directly readable by the openssl utility. The following command will take an existing SSH private key (id_rsa in the example below) and create the .pem public key that is needed for Azure:

> `# openssl req -x509 -key ~/.ssh/id_rsa -nodes -days 365 -newkey rsa:2048 -out myCert.pem`

> The myCert.pem file is the public key that may then be used to provision a Linux virtual machine on Azure. During provisioning the .pem file will be translated into an openssh compatible public key and placed in ~/.ssh/authorized_keys.

The way I read this, `openssl` is **req**uesting a **-newkey** of type and size **rsa:2048** from the private key at **-key** and it wants the new key to be saved at **myCert.pem**. Right? 

Except... that [openssl req docs](https://www.openssl.org/docs/apps/req.html) say this (the emphasis is mine): 

> #### -newkey arg

>    this option creates a new certificate request and a new **<u>private key</u>**. The argument takes one of several forms. rsa:nbits, where nbits is the number of bits, generates an RSA key nbits in size. If nbits is omitted, i.e. -newkey rsa specified, the default key size, specified in the configuration file is used.

I read this to say that the output of this call is a *new private key*. Private keys are NOT, at all, to be installed on public machines. 

Do I read this incorrectly? To create a .pem version of a public key, we should be converting the id_rsa.pub file, not the id_rsa file, right? Or do I misunderstand all of this? It's easy to do, I confess...

**Comment by ahmetalpbalkan** [comment]
@squillace looks like you're right. From the size of the PEM key I can tell it contains private key as well. :)

    ssh-keygen -f id_rsa.pub -e -m pem > id_rsa.pub.pem

when I run this though, xplat-cli doesn't accept the `id_rsa.pub.pem` (says wrong format, although it looks perfectly OK to me).

Anyway this is too complicated even for me.

**Comment by squillace** [comment]
Ahmet, try [this](http://askubuntu.com/questions/53553/how-do-i-retrieve-the-public-key-from-a-ssh-private-key):

> `ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub`

Seems to work to create the .pub. Then call base64 to encoded it when necessary, but geez, what a mess. 

from http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/ssh-keygen.1?query=ssh-keygen&sec=1:


> I've found the answer on Serverfault: Create a public SSH key from the private key?

>The option -y outputs the public key:

>> ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
>As a side note, the comment of the public key is lost. I've had a site which required the comment (Launchpad?), so you need to edit ~/.ssh/id_rsa.pub and append a comment to the first line with a space between the comment and key data. An example public key is shown truncated below.

>>ssh-rsa AAAA..../VqDjtS5 ubuntu@ubuntu

the link indicates that you use the -N param to pass the passord assuming the default is that you have a password-secured private key. 

`ssh-keygen -f ~/.ssh/id_rsa -y `**-N "$PASSWORD"**` > ~/.ssh/id_rsa.pub`

**Comment by ahmetalpbalkan** [comment]
@squillace Just to be clear I am not trying to solve anything I can always copy the public key myself.

Problem is everybody's key is in RSA format already and what saved to authorized_keys is RSA format. I am not going to read any instructions for Azure. I will never visit our SSH docs. This issue is about making the tool work with RSA format. I already have id_rsa and .pub on my computer.

**Comment by squillace** [comment]
You are spot on.

**Comment by tmm1** [comment]
The help for this command indicates that it will accept a fingerprint:

```
help:      -t, --ssh-cert <pem-file|fingerprint>  the SSH certificate
```

However when I try to pass any the public fingerprint file it will blow up:

```
$ azure vm create --vm-size Standard_D3 --ssh --no-ssh-password --ssh-cert id_test.pub myubuntu b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_4-LTS-amd64-server-20140428-en-us-30GB admin
info:    Executing command vm create
+ Looking up image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_4-LTS-amd64-server-20140428-en-us-30GB
error:   Specified SSH certificate is not in PEM format
error:   vm create command failed
```

**Comment by ahmetalpbalkan** [comment]
@tmm1 I don't think id_test.pub is a fingerprint file in your case. it's just a file with public key in RSA format. Thumbprints look more like `ab:94:31:0a:7b:9c:af:21:3e:31:aa:d0:47:3b:be:fe`

**Comment by tmm1** [comment]
Same error when using a fingerprint:

```
$ ssh-keygen -lf id_test.pub | awk '{ print $2 }'
f3:9a:d9:40:ee:24:0a:6f:f6:70:55:e0:26:77:49:6c

$ ssh-keygen -lf id_test.pub | awk '{ print $2 }' > id_test.fingerprint

$ azure vm create --vm-size Standard_D3 --ssh --no-ssh-password --ssh-cert id_test.fingerprint myubuntu b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_4-LTS-amd64-server-20140428-en-us-30GB admin
info:    Executing command vm create
+ Looking up image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_4-LTS-amd64-server-20140428-en-us-30GB
error:   Specified SSH certificate is not in PEM format
error:   vm create command failed

$ azure vm create --vm-size Standard_D3 --ssh --no-ssh-password --ssh-cert "f3:9a:d9:40:ee:24:0a:6f:f6:70:55:e0:26:77:49:6c" myubuntu b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_4-LTS-amd64-server-20140428-en-us-30GB admin
info:    Executing command vm create
+ Looking up image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_4-LTS-amd64-server-20140428-en-us-30GB
error:   ENOENT, no such file or directory 'f3:9a:d9:40:ee:24:0a:6f:f6:70:55:e0:26:77:49:6c'
info:    Error information has been recorded to /home/tmm1/.azure/azure.err
```

**Comment by ahmetalpbalkan** [comment]
@tmm1 yeah the fingerprint might not have been implemented at all (or maybe works on windows, where  a centralized cert store exists, in that case docs are wrong for linux/mac).

**Comment by tmm1** [comment]
According to https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/asm/vm/vmclient.js#L4531-4533, you can pass in a 40 char sha1 hash as a fingerprint. But I'm not sure how to generate that, since `ssh-keygen -l` creates a 32 char md5 hash.

**Comment by tmm1** [comment]
This worked:

```
fingerprint=$(cat id_test.pub | awk '{ print $2 }' | openssl base64 -d -A | sha1sum | awk '{ print $1 }')
```

**Comment by ahmetalpbalkan** [comment]
@tmm interesting. are you running on Windows? (regardless, thumbprint stuff is separate from this issue).

**Comment by tmm1** [comment]
Not on windows.

The CLI accepted my 40 byte sha-1 checksum, but I wasn't able to actually boot the instance:

```
error:   The certificate with thumbprint AFA2EED1CB494DC38A6DDDAEB8C536BDFC5B9690 was not found.
2015-04-15T12:10:36.619466 info:    Error information has been recorded to /var/lib/jenkins/.azure/azure.err
error:   vm create command failed
```

It appears this only works if the key has been somehow pre-registered with azure.

I'm not sure why all these crazy hoops are required and really wish the CLI would accept the standard ssh pubkey format.

**Comment by ahmetalpbalkan** [comment]
@tmm1 cool to see you +1ing

**Comment by polarapfel** [comment]
Have to +1 this. Anything that drops out of ssh-keygen should be acceptable input to push to a new VM.

**Comment by devigned** [comment]
:+1:

**Comment by anuchandy** [comment]
This feature is added in this branch: https://github.com/anuchandy/azure-xplat-cli/commit/644db729cb17ddbc255b7e87f805fc2a1f74de60 

We take dependency on two NPM modules: jsrsasign and ssh-key-to-pem. The jsrsasign  NPM module is not up to date, we build the latest from source to unblock VM Create RSA implementation.  I have requested jsrsasign author to update NPM module [ _https://github.com/kjur/jsrsasign/issues/94 ], this is required to push our fix to upstream.

Hi @tmm1, the fingerprint is used in the following scenario:

1. User has an existing cloud service (with or without VM) with a certificate configured
2. User want to add a new VM to this cloud service and want to use the already configured certificate 
3. In this scenario while adding new VM, user can pass the fingerprint of existing certificate

**Comment by squillace** [comment]
@anuchandy is this merged? what build will this fix be in? It's NEEDED. :-)

**Comment by anuchandy** [comment]
@squillace it is merged in msopentech/dev branch https://github.com/msopentech/azure-xplat-cli/tree/dev . we will be sending PR to upstream by June/19

**Comment by anuchandy** [comment]
@squillace this has been merged with upstream and will be available in the current release
