### ISSUE TITLE
Rsync helper for blob storage

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-xplat-cli#1685]
Most linux developers copy things to remote servers or storage systems using "rsync" tools. It gives a great deal of flexibility and features. We make use of existing blob service properties and implement rsync in xplat-cli. 

An example use case: I want to host my statically generated blog (eg with jekyll, pelican) on azure blob storage. I need a rsync command to upload only the changed files to storage and sync the file list with my local directory and blob container. 

Google's gsutil tool has a rsync functionality that people actually find very useful.

**Comment by bureado** [comment]
+1 that this is better than multiple `azure storage blob upload` calls (what is done today) plus some heuristics for computing deltas. BTW, SSH is the transport for most of the `rsync` calls happening on a normal Linux sysadmin scenario, so whether this is implemented as an `rsync` transport or as `azure-cli` functionality it's useful, but I also think there's still need for something like azurefs in which case neither the azure-cli or the rsync functionality is needed as regular rsync would suffice.

**Comment by ahmetalpbalkan** [comment]
@bureado It's correct that most of the tools like rsync/scp/sftp work over SSH. however you can mimic the behavior of the protocol and handle 90% of the use case. 

If you are referring to "azurefs" as a FUSE driver like a mountable fs: https://github.com/ahmetalpbalkan/azurefs It's a solution that's far away from being durable and fast due to the nature of locally mounted remote filesystems.

This doesnt have to be in xplat-cli. Actually we have AzCopy.exe but it's not cross platform and doesnt quite work like rsync. Maybe this is a feature request for the Azure SDK team. But xplat-cli seemed like a good fit as we already have slme blob things going on in there.

**Comment by devigned** [comment]
I think something like this could be done using winrm (we do it in vagrant-azure) for the Windows side and rsync (or equivalent) for the *nix side.

**Comment by jeffwilcox** [comment]
+1

**Comment by ahmetalpbalkan** [comment]
looks like we got nice amount of +1s (like 3). that's a first.

**Comment by powareverb** [comment]
This is a huge +1 for me, would be even better if this was implemented for both blob and file.  ATM I'm probably going to look at using azurefs + rsync to achieve same result but I don't expect it'll be particularly reliable/stable.

**Comment by amarzavery** [comment]
@johanste - Something to be considered for increasing awesomeness.

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan, I will open an issue at new azure-cli repo and see whether we have bandwidth to work on it.

**Comment by brijrajsingh** [comment]
still open after 6 months, My huge +1 for this

**Comment by gjonespf** [comment]
Hey, just thought I'd chime in with my current workaround for this.  Likely it won't work for many, but may work for some, and is food for thought.  I'm using Azure with docker atm, so I'm using @ahmetalpbalkan awesome Azure volume driver https://github.com/Azure/azurefile-dockervolumedriver in conjunction with Minio mirroring https://www.minio.io.  I'd love to see rsync capability, but having an S3 compatible API would also be an excellent idea, given the amount of tooling around for S3. However, understand this may be a little contentious ;)

**Comment by ateska** [comment]
+1 for this.

**Comment by bartuer** [comment]
Blob stroage header already include MD checksum, and from rsync 3.0.0+, it "--checksum" already use MD5, why not ? +1

**Comment by davidlalonde** [comment]
1+

**Comment by matansag** [comment]
+1. will love to see it work in order to backup file from local Ubuntu machine.

**Comment by adamsteer** [comment]
+1 for rsync-like tools for file movement to Azure from the CLI :)

**Comment by brandonh-msft** [comment]
+1

**Comment by KoditkarVedant** [comment]
+1

**Comment by amarzavery** [comment]
There will be no new feature updates to this CLI. If you need this feature and if it is not present in the new python based azure-cli (https://github.com/azure/azure-cli) then please file an issue over there. The issue will get triaged and will be taken based on priority if it is filed over there. Commenting +1 over here will not be of any help. Thanks.

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-cli/issues/833
