### ISSUE TITLE
`azure storage account connectionstring show` hard to use programatically

### ISSUE THREAD

**Issue by tmm1** [Azure/azure-xplat-cli#1686]
The various `azure storage` commands require a `AZURE_STORAGE_CONNECTION_STRING` to be set. The token for this variable is available via the `connectionstring show` command, but has to be massaged into a format to make it usable:

``` shell
export AZURE_STORAGE_CONNECTION_STRING=$(azure storage account connectionstring show <name> | grep data: | grep connectionstring | awk '{ print $3 }')
```

It would be nice to add a `--env` or similar option that returns only the relevant token so that no output transformations are required.

**Comment by gangsir** [comment]
Thanks for the feedback. We will look at improving this in the future.

**Comment by amarzavery** [comment]
@hasonmsft @yaxia - Any plans to improve this? If no, then please close the issue.

**Comment by hasonmsft** [comment]
@tmm1 , currently the framework only have two output modes: normal and 'json'. For the normal mode, you are already doing the transformation correctly and we cannot write output without the status indicator. And for 'json' output format (--json), it'll also have some json format strings which still require the transformation.

@amarzavery , is any plan to support plain output in the framework? 

{
  "string": "[ConnectionStringHere]"
}
