### ISSUE TITLE
Creating premium storage containers that are publicly readable

### ISSUE THREAD

**Issue by mhp** [Azure/azure-xplat-cli#1687]
I am trying to create a publicly readable storage container, backed by a premium storage account.  

I can create a publicly readable container:
```
$ azure storage account create $myacct --label $myacct --location 'West US'
$ azure storage container create -c $connectionString -p container $mycontainer
...
data:        publicAccessLevel: 'Container'
```

But, as soon as I add `--type PLRS` to make a premium storage account, I get errors:
```
$ azure storage account create $myacct --label $myacct --location 'West US' --type PLRS
$ azure storage container create -c $connectionString -p container $mycontainer
...
warn:    Current storage account doesn't support setting ACL
...
data:        publicAccessLevel: null
```

How should I programmatically create a storage account and container so that I get both SSD storage and public visibility?

**Comment by siriusk-MSFT** [comment]
Premium Storage does not allow public containers. Instead you could use an infinite SAS for sharing

**Comment by tmm1** [comment]
@siriusk-MSFT Do you mean a SAS url with an expiry date that is many years in the future? Or is there some other way to create a SAS without expiry date altogether?

**Comment by siriusk-MSFT** [comment]
The former. You could specify the year as 9999

**Comment by ahmetalpbalkan** [comment]
@mhp does that solve your problem?

**Comment by yaxia** [comment]
Close it with @siriusk-MSFT 's answer.
