### ISSUE TITLE
Security warning about deprecated dependency

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1691]
While installing azure-cli I saw this

```sh
$ npm install -g azure-cli
npm WARN deprecated jws@1.0.1: Security update: Versions below 3.0.0 are deprecated.

> fibers@1.0.5 install /usr/local/lib/node_modules/azure-cli/node_modules/streamline/node_modules/fibers
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/fibers.node
  SOLINK_MODULE(target) Release/fibers.node: Finished
Installed in `/usr/local/lib/node_modules/azure-cli/node_modules/streamline/node_modules/fibers/bin/darwin-x64-v8-3.28/fibers.node`
/usr/local/bin/azure -> /usr/local/lib/node_modules/azure-cli/bin/azure
azure-cli@0.8.17 /usr/local/lib/node_modules/azure-cli
├── easy-table@0.0.1
├── eyes@0.1.8
├── xmlbuilder@0.4.3
├── through@2.3.4
├── azure-gallery@2.0.0-pre.15
├── colors@0.6.2
[...]
```

Reporting in case this is not in your radar.

**Comment by ahmetalpbalkan** [comment]
Looks like `adal-node` is causing this. https://www.npmjs.com/package/adal-node

**Comment by amarzavery** [comment]
Nope, this is caused due to streamline.js. It is a module used for ._js  files.
It is mentioned in npm over [here](https://www.npmjs.com/package/streamline#installation)

**Comment by ahmetalpbalkan** [comment]
@amarzavery are you sure? https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/a8a7936783358ac17cb0da566208f3c63eac1845/package.json#L26 I can see `1.x.x` here as well.

**Comment by stankovski** [comment]
@ahmetalpbalkan - We shall update the adal node dependency to 0.1.13

**Comment by ahmetalpbalkan** [comment]
@amarzavery can you please leave a comment or reference this issue from somewhere else (eg commit or PR) while closing issues? :-) Is this fixed in public release? If not, let's keep it open.
