### ISSUE TITLE
azure role assignment list fails

### ISSUE THREAD

**Issue by yangl900** [Azure/azure-xplat-cli#1692]
Running 

'''
azure role assignment list
'''

returns:
error:   The filter 'principalId eq ''' is not supported. Supported filters are either 'atScope()' or 'principalId eq '{value}''.

the default role assignment listing should not pass in principalId filter. this seems a regression.

**Comment by yugangw-msft** [comment]
Vivek, could you take a look? Come by if you need more context.

**Comment by amarzavery** [comment]
I have almost completed this issue. Will send a PR shortly. Please review it.

**Comment by amarzavery** [comment]
closing this issue as the corresponding PR has been merged.
