### ISSUE TITLE
Add support for AzCopy

### ISSUE THREAD

**Issue by thauburger** [Azure/azure-xplat-cli#1697]
AzCopy "is a command-line utility designed for high-performance uploading, downloading, and copying data to and from Microsoft Azure Blob, File, and Table storage."

Today, support only exists in PowerShell.

I found a limited workaround that is non-intuitive (and presumably slower) using:

`azure vm disk upload [options] <source> <dest-blob> <storage-account-key>`

[AzCopy Guide](http://azure.microsoft.com/en-us/documentation/articles/storage-use-azcopy/)

**Comment by ahmetalpbalkan** [comment]
+1

**Comment by zhimingyuan** [comment]
I suppose you are requesting to run xCLI on Linux and call AzCopy command line (run xCLI on Windows and call AzCopy is already supported).

AzCopy does not include the support for Linux, we have added it to our feature list, but no plan at this moment yet.

**Comment by jeffwilcox** [comment]
@zhimingyuan so are you recommending the closing of this issue?

**Comment by yaxia** [comment]
Close it for now as no plan on this requiement.
