### ISSUE TITLE
No error message for un-deletable blob

### ISSUE THREAD

**Issue by kenazk** [Azure/azure-xplat-cli#1704]
The issue is that the customer had a blob that was backing an existing disk. The disk was not yet deleted, and so when the customer deletes the blob, that call fails. However, there’s no error message to indicate that the blob fails to delete because it’s attached to the disk.

Can we provide this error message?

**Comment by gangsir** [comment]
Hi, @kenazk , thank you for your feedback. We will look at this and improve the error message.

**Comment by yaxia** [comment]
In the latest Azure CLI, it will tell the blob is leased which could be caused by an attached disk or leased by others. If you are sure that you want to delete the blob, you can break the lease (`azure storage blob lease break`) and delete it.
