### ISSUE TITLE
'azure vm endpoint create' '--enable-direct-server-return' argument is ignored

### ISSUE THREAD

**Issue by dhauge** [Azure/azure-xplat-cli#1705]
It seems that the --enable-direct-server-return endpoint is ignored in the 'azure vm endpoint create' command. I created the endpoint via
```bash
azure vm endpoint create msazulxd10 80 80\
    --endpoint-name http\
    --lb-set-name WebUiLbs\
    --endpoint-protocol tcp\
    --enable-direct-server-return false\
    --internal-load-balancer-name WebUiLoadBalancer
```
When I subsequently check the endpoint with
```bash
azure vm endpoint show msazulxd10
```
I get
```
info:    Executing command vm endpoint show
+ Getting virtual machines                                                     
data:    Network Endpoints 0 loadBalancedEndpointSetName "WebUiLbs"
data:    Network Endpoints 0 localPort 80
data:    Network Endpoints 0 name "http"
data:    Network Endpoints 0 port 80
data:    Network Endpoints 0 protocol "tcp"
data:    Network Endpoints 0 virtualIPAddress "xxx.xxx.xxx.xxx"
data:    Network Endpoints 0 enableDirectServerReturn true
data:    Network Endpoints 0 loadBalancerName "WebUiLoadBalancer"
data:    Network Endpoints 1 localPort 22
data:    Network Endpoints 1 name "ssh"
data:    Network Endpoints 1 port nnnnn
data:    Network Endpoints 1 protocol "tcp"
data:    Network Endpoints 1 virtualIPAddress "xxx.xxx.xxx.xxx"
data:    Network Endpoints 1 enableDirectServerReturn false
info:    vm endpoint show command OK
```
Note that 'Network Endpoints 0 enableDirectServerReturn' is set to 'true'.

Looking at the code in https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/asm/vm/vmclient.js, the error might be in lines 728-733:
```javascript
    if (options.enableDirectServerReturn) {
      epInput.directServerReturn = {
        'value': 'true',
        'argName': '--enable-direct-server-return'
      };
    }
```
Note that unlike other options, the value is set directly to 'true' instead of a value in 'options.' as in
```javascript
    if (options.internalLoadBalancerName) {
      epInput.internalLoadBalancerName = {
        'value': options.internalLoadBalancerName,
        'argName': '--internal-load-balancer-name'
      };
    }
```

**Comment by dhauge** [comment]
Note that using the 'create-multiple' command seems to work
```bash
azure vm endpoint create-multiple msazulxd10 80:80:tcp:false:WebUi:http:80:/:WebUiLoadBalancer
```
Which provides a workaround, with a minor annoyance in that the endpoint cannot be explicitly named.

**Comment by babumuralidharan** [comment]
@dhauge You have to pass the boolean value in "false" or 'false' like this

azure vm endpoint create msazulxd10 80 80\
    --endpoint-name http\
    --lb-set-name WebUiLbs\
    --endpoint-protocol tcp\
    --enable-direct-server-return 'false'\
    --internal-load-balancer-name WebUiLoadBalancer

we will update our help to reflect this.

**Comment by dhauge** [comment]
Are you sure? I just tried that and it still didn't work.

I ran
```bash
azure vm endpoint create msazulxd20 80 8450\
>     --endpoint-name http\
>     --lb-set-name assydsgnlbs\
>     --probe-port 8450\
>     --probe-protocol http\
>     --probe-path /digital-assays\
>     --endpoint-protocol tcp\
>     --enable-direct-server-return 'false'\
>     --internal-load-balancer-name assay-designer-lb
```
And then
```bash
azure vm endpoint list msazulxd20
```

returned
```bash
info:    Executing command vm endpoint list
+ Getting virtual machines                                                     
data:    Name  Protocol  Public Port  Private Port  Virtual IP  EnableDirectServerReturn  Load Balanced
data:    ----  --------  -----------  ------------  ----------  ------------------------  -------------
data:    http  tcp       80           8450          10.19.2.4   true                      Yes          
info:    vm endpoint list command OK
```

**Comment by dhauge** [comment]
Looks like it was a problem with my command, but not quite what was suggested above: the '--enable-direct-server-return' option does not take a parameter, it just enables direct server return it if the argument is specified, and disables it if not. I'd suggest the current document is slightly confusing; instead of
```
   -u, --enable-direct-server-return         whether to enable direct server return on this endpoint, disabled by default
```
it should be something like
```
   -u, --enable-direct-server-return        enables direct server return on this endpoint, disabled by default
```
(the 'whether' suggests it takes a parameter). Also, it would be nice if the command would fail if an argument was included after '--enable-direct-server-return'; currently any such arguments are ignored.

**Comment by anuchandy** [comment]
@dhauge this is fixed in updated endpoint command set, please check https://github.com/msopentech/azure-xplat-cli/tree/dev
