### ISSUE TITLE
azure cli commands take couple seconds to run: seems slow (even after initial run)

### ISSUE THREAD

**Issue by kmouss** [Azure/azure-xplat-cli#1707]
First time run take about 30 seconds to responds (something like % azure)
Subsequent runs take over 2 seconds on average

**Comment by yugangw-msft** [comment]
we had internal work item created to track this.

**Comment by yugangw-msft** [comment]
Khalid, did the slowness comes from running a command from an installer, or you just clone local and run from the repository root such as "node bin/azure". Under the latter case, there is a known perf issue that the streamline kicks in to compile all command ._js file on the fly.

**Comment by devigned** [comment]
@yugangw-msft He had run it post streamline code generation and saw over 2 seconds on average for command execution / listing.

**Comment by yugangw-msft** [comment]
@devigned  and @kmouss , so we have 2 issues here, the first run of 30 seconds delay and the consecutive  run of 2 seconds. I assume we will need to address both though priority might differ, correct?.
For the 30 seconds, one way to mitigate the experience is to display a little more progress text for the one time initialization. For the 2 seconds, let us profile to see the perf data first.

**Comment by kmouss** [comment]
the later is higher priority since the 30s issues is a one time hit. But the 2s issues happens every time you run most command if not all.

**Comment by yugangw-msft** [comment]
I made the following 2 changes which should just address this issue. 
#1832 
#1739 
Please note the fixes were about to remove all the overhead trying to find the command and load it, which used to be a very expensive operation; but if the commands is slow itself by doing lots of things, then the owner himself should improve it.
