### ISSUE TITLE
ARM: Support setting default resource group

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1708]
Like using `azure account set <subd-id>` and avoiding providing `--subscription-id` to all operations, ARM mode should support setting the default resource group to avoid passing resource group name argument to the commands over and over again.

cc: @kmouss

**Comment by amarzavery** [comment]
+1
 ```
Since, we already have azure group set for updating the group, how about -
azure group default <group-id>
```

**Comment by ahmetalpbalkan** [comment]
Sounds nice.

**Comment by ahmetalpbalkan** [comment]
EPROLLYNEVERGONNAHAPPEN
