### ISSUE TITLE
ARM Storage Account Create

### ISSUE THREAD

**Issue by karthmut** [Azure/azure-xplat-cli#1711]
If you leave off parameters, you get a prompt. For example, omitting Location gives you:

help:   Location:
1) South Central US
2) East US
3) East US 2
4) Central US
5) North Europe
6) West Europe
7) Southeast Asia
8) East Asia
/:

If you input the location name, it just keeps prompting you. You have to input the numerical value, but this is not clear. Also, only 8 locations are listed.

This applies to Type as well.

**Comment by ahmetalpbalkan** [comment]
+1. If we can prompt like:

    Please enter your numeric choice:

that'd be cool.

**Comment by ahmetalpbalkan** [comment]
@amarzavery why closed?
