### ISSUE TITLE
No Error Reported When Not Logged In (ARM mode)

### ISSUE THREAD

**Issue by gabrielhartmann** [Azure/azure-xplat-cli#1713]
When in ARM mode, without having logged in with "azure login", when attempting to list accounts, I get an empty list instead of an error indicating that I'm not logged in.

![image](https://cloud.githubusercontent.com/assets/567111/7264014/d0b2806a-e83b-11e4-8b8b-c8221b678042.png)

**Comment by amarzavery** [comment]
That is the way things are designed to be, irrespective of the mode(ARM or ASM):
```
D:\sdk\xplat-pr\azure-xplat-cli-pr\tools\windows>azure account list
info:    Executing command account list
data:
data:
info:    account list command OK

D:\sdk\xplat-pr\azure-xplat-cli-pr\tools\windows>azure config mode arm
info:    New mode is arm

D:\sdk\xplat-pr\azure-xplat-cli-pr\tools\windows>azure account list
info:    Executing command account list
data:
data:
info:    account list command OK

D:\sdk\xplat-pr\azure-xplat-cli-pr\tools\windows>
```
