### ISSUE TITLE
[question] How to retrieve VM system information?

### ISSUE THREAD

**Issue by fjaguero** [Azure/azure-xplat-cli#1717]
Hello,

I was wondering if it's possible to get system information from a specific VM: CPU/RAM/Load Average.

Thanks.

**Comment by anuchandy** [comment]
Looks like this requires 'Diagnostics' extension to be installed in the VM. Please refer https://www.simple-talk.com/cloud/development/azure-diagnostics-for-virtual-machines/

**Comment by fjaguero** [comment]
Thanks @anuchandy
