### ISSUE TITLE
Networkconfig.json upload doesn't honor site-to-site settings

### ISSUE THREAD

**Issue by joebelfu** [Azure/azure-xplat-cli#1719]
There does not seem to be a way to setup a site-to-site connection via modifying the networkconfig.xml/json file. If you add the necessary elements and upload the networkconfig.json file the site-to-site functionality is not enabled. It requires a manual setup in the Azure portal.

**Comment by amarzavery** [comment]
@joebelfu - Can you please tell us which command you are trying to execute?

**Comment by amarzavery** [comment]
@joebelfu - Please feel free to reopen this issue with more information.
OS type - ?
node version - ?
azure version - (azure -v) ?
what command is being executed ?
what is your expectation from the command ?
