### ISSUE TITLE
azure login can't be invoked in ruby script

### ISSUE THREAD

**Issue by qingfuwang** [Azure/azure-xplat-cli#1720]
Please look at https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/login._js#L87

var progress = cli.interaction.progress($('Authenticating...'))

interaction.process would fail.

after I add a waiter , it could sucess
  setInterval(function(){
  console.log('wait..');
}, 2 * 1000);

**Comment by amarzavery** [comment]
@qingfuwang - 
Are you trying to execute the login command via automation? If that is the case then, please execute the command with --json option. 
```azure login -u $username -p $password --json```
```azure account list --json```

Let me know if that worked for you.

**Comment by qingfuwang** [comment]
Thanks it works perfect.
