### ISSUE TITLE
Issue with custom-data to ubuntu image- does not get executed post deployment

### ISSUE THREAD

**Issue by sudhansh** [Azure/azure-xplat-cli#1721]
i'm trying to execute a simple shell script using the --custom-data param on a ubuntu image from the gallery, but it doesn't seem to execute. I see the /var/lib/waagent/ovf-env.xml has the CustomData base 64encoded to the the script i passed in, however it still does not execute this simple script. My test is to just create a directory under /home/.
The xplat-cli version is 0.8.17. What am i missing here?

**Comment by sudhansh** [comment]
here is the command i'm issuing to create the vm-
azure vm create <vm-name> b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_2-LTS-amd64-server-20130624-en-us-30GB -v --json -l "East US 2" -e 22 -g <username> -p <password> --custom-data "./custom_data1.sh" -w <vnet-info> -S 10.0.1.244 -z "Standard_D1" -u <blob-info>

**Comment by paulmey** [comment]
I think your command line is correct, but I haven't used this in a while. On Ubuntu, custom-data is passed to cloud-init. Does your script have a shebang (#!/bin/bash or something)?
According to https://help.ubuntu.com/community/CloudInit, it's considered to be a script if it starts with '#!'...

**Comment by sudhansh** [comment]
Yes, i have my script start with a "#!/bin/bash" and i started with complex script and nothing seemed to work so i reduced it down just a "mkdir" for test purposes. Below is my script:

#!/bin/bash
mkdir /home/<username>/test

**Comment by sudhansh** [comment]
I tried the same with ARM template deployment and the custom data in the template also that does not get executed.

**Comment by szarkos** [comment]
Can you repro this with a recent image, i.e. the latest 12.04 image is b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-12_04_5_LTS-amd64-server-20150413-en-us-30GB

The image you mention from 20130624 predates the existence of the Azure data provider for cloud-init (and actually the CustomData feature itself) :)

**Comment by paulmey** [comment]
I reproed with the old image, but with the new image that Steve mentions, it works as expected:
```sh
paulmey@pmtest147:~$ ll /home/
total 20
drwxr-xr-x  5 root    root    4096 Apr 30 05:27 ./
drwxr-xr-x 23 root    root    4096 Apr 30 05:27 ../
drwxr-xr-x  4 paulmey paulmey 4096 Apr 30 05:28 paulmey/
drwxr-xr-x  2 root    root    4096 Apr 30 05:27 test/
drwxr-xr-x  2 ubuntu  ubuntu  4096 Apr 13 16:43 ubuntu/
```
Fixed?

**Comment by kmouss** [comment]
Closing since using the newer image fixes the issue.
