### ISSUE TITLE
How to properly use vm endpoint create-multiple?

### ISSUE THREAD

**Issue by fjaguero** [Azure/azure-xplat-cli#1722]
Hi,

I'm wondering if I correctly understand the function of this command.

Example:
`azure vm endpoint create-multiple <vm-name> 881:80 221:22`

Is it possible to create two endpoints (like the example above) in one single commands?

Maybe I misunderstood the command and it can only create multiple private ports for a public port.

Thanks.

**Comment by tmm1** [comment]
Use commas:

```
azure vm endpoint create-multiple <vm-name> 122,80,8080,443,8443,9418,25,161:161:udp,1194:1194:udp
```

**Comment by fjaguero** [comment]
Thanks @tmm1, I will try it.

**Comment by fjaguero** [comment]
Tested and working. The thing is, am I the only one that doesn't understand that from the documentation? I asked 3 devs to write that command and no one did this.

**Comment by BrianEWhipple** [comment]
+1 to updating the help.  Reads like it should be space delimited list of endpoints not a comma delimited list.
