### ISSUE TITLE
(0.8.16)azure login --service-principal hang when password is incorrect

### ISSUE THREAD

**Issue by qingfuwang** [Azure/azure-xplat-cli#1723]
\ Authenticating... will never finish

rm /home/azureuser/.azure/*

azureuser@ubuntu:~/bosh$ azure login -u 7abc1644-9234-xxxxae71-897f943a7de6 -p 'wrongpassword' --tenant 72f988bf-86f1-41af-91ab-xxxx011db47 --service-principal --quiet
info:    Executing command login
warn:    Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
\ Authenticating...

azureuser@ubuntu:~/bosh$ npm list -g azure
/usr/local/lib
└─┬ azure-cli@0.8.16
  └── azure@0.10.4

**Comment by amarzavery** [comment]
@quingfuwang - Can you please install the latest version of CLI. ```npm install -g azure-cli``` and re-execute the login for service principal.

**Comment by yugangw-msft** [comment]
fixed by #1699
