### ISSUE TITLE
azure vm image list* not working

### ISSUE THREAD

**Issue by tmm1** [Azure/azure-xplat-cli#1726]
```
$ azure vm image list-publishers "West US"
info:    Executing command vm image list-publishers
+ Getting virtual machine image publishers (Location: "West US")
error:   Encountered internal server error. The tracking Id is 'f48d9f59-09a9-499a-9928-555bab446d42'.
info:    Error information has been recorded to /Users/tmm1/.azure/azure.err
error:   vm image list-publishers command failed
```

**Comment by tmm1** [comment]
```
$ azure vm image list "West US" "Ubuntu"
info:    Executing command vm image list
warn:    The parameters --offer and --sku if specified will be ignored
+ Getting virtual machine image offers (Publisher: "Ubuntu" Location:"West US")
error:   Encountered internal server error. The tracking Id is '34bc01a1-98dd-44c5-888a-ffa92b941981'.
info:    Error information has been recorded to /Users/tmm1/.azure/azure.err
error:   vm image list command failed
```

**Comment by tmm1** [comment]
Using latest version:

```
$ azure --version
0.9.1 (node: 0.10.21)
```

**Comment by kmouss** [comment]
@tmm1 - try it like this:
 azure vm image list-publishers westus or 
azure vm image list-publishers "westus"
Thanks

**Comment by tmm1** [comment]
That works, thanks.

Most of the other commands allow spaces in region names, so probably this should be updated to work that way as well.

**Comment by anuchandy** [comment]
@tmm1 thanks for reporting, will fix.

**Comment by tmm1** [comment]
East US 2 does not work:

```
$ azure vm image list EastUS2 GitHub
info:    Executing command vm image list
warn:    The parameters --offer and --sku if specified will be ignored
+ Getting virtual machine image offers (Publisher: "GitHub" Location:"EastUS2")
error:   Host name resolution failed for 'Microsoft.Compute'; cannot fulfill the request.
info:    Error information has been recorded to /Users/tmm1/.azure/azure.err
error:   vm image list command failed
```

**Comment by kmouss** [comment]
@tmm1 - The East US2 region isn't yet supported in public preview for Azure VM IaaS ARM - These regions are supported: East US, West US,West Europe, East Asia, Southeast Asia - Thanks

**Comment by HimanshuBri** [comment]
@anuchandy  @tmm1 azure vm image list working with space in region names
<pre>
<code>
C:\May\15May\azure-xplat-cli-dev>node bin/azure vm image list-publishers "West US"
info:    Executing command vm image list-publishers
+ Getting virtual machine image publishers (Location: "westus")
data:    Publisher                                       Location
data:    ----------------------------------------------  --------
data:    a10networks                                     westus
data:    adobe                                           westus
data:    aiscaler-cache-control-ddos-and-url-rewriting-  westus
data:    alachisoft                                      westus
data:    alertlogic                                      westus
data:    AlertLogic.Extension                            westus
data:    apprenda                                        westus
data:    appzero                                         westus
data:    aras                                            westus
data:    Barracuda.Azure.ConnectivityAgent               westus
data:    barracudanetworks                               westus
data:    basho                                           westus
data:    boundlessgeo                                    westus
data:    boxless                                         westus
data:    bssw                                            westus
data:    bwappengine                                     westus
data:    Canonical                                       westus
data:    checkpoint                                      westus
data:    chef-software                                   westus
data:    Chef.Bootstrap.WindowsAzure                     westus
data:    cires21                                         westus
data:    cloudera                                        westus
data:    cloudlink                                       westus
data:    CloudLink.SecureVM                              westus
data:    cohesive                                        westus
data:    commvault                                       westus
data:    corent-technology-pvt                           westus
data:    CoreOS                                          westus
data:    couchbase                                       westus
data:    Datadog.Agent                                   westus
data:    datastax                                        westus
data:    defacto_global_                                 westus
data:    dell-software                                   westus
data:    dell_software                                   westus
data:    derdack                                         westus
data:    egress                                          westus
data:    elastacloud                                     westus
data:    esri                                            westus
data:    filebridge                                      westus
data:    GitHub                                          westus
data:    hanu                                            westus
data:    hortonworks                                     westus
data:    imc                                             westus
data:    informatica-cloud                               westus
data:    infostrat                                       westus
data:    intelligent-plant-ltd                           westus
data:    jetnexus                                        westus
data:    kaspersky_lab                                   westus
data:    kemptech                                        westus
data:    le                                              westus
data:    liebsoft                                        westus
data:    loadbalancer                                    westus
data:    logi-analytics                                  westus
data:    loginpeople                                     westus
data:    logtrust                                        westus
data:    looker                                          westus
data:    McAfee.EndpointSecurity                         westus
data:    mesosphere                                      westus
data:    metavistech                                     westus
data:    mfiles                                          westus
data:    Microsoft.Azure.Applications                    westus
data:    Microsoft.Azure.Diagnostics                     westus
data:    Microsoft.Azure.RecoveryServices                westus
data:    Microsoft.Azure.Security                        westus
data:    Microsoft.AzureCAT.AzureEnhancedMonitoring      westus
data:    Microsoft.Compute                               westus
data:    Microsoft.EnterpriseCloud.Monitoring            westus
data:    Microsoft.HpcCompute                            westus
data:    Microsoft.HpcPack                               westus
data:    Microsoft.OSTCExtensions                        westus
data:    Microsoft.Powershell                            westus
data:    Microsoft.SqlServer.Management                  westus
data:    Microsoft.SystemCenter                          westus
data:    Microsoft.WindowsAzure.Compute                  westus
data:    MicrosoftAzureSiteRecovery                      westus
data:    MicrosoftBizTalkServer                          westus
data:    MicrosoftDynamicsAX                             westus
data:    MicrosoftDynamicsGP                             westus
data:    MicrosoftDynamicsNAV                            westus
data:    MicrosoftHybridCloudStorage                     westus
data:    MicrosoftSharePoint                             westus
data:    MicrosoftSQLServer                              westus
data:    MicrosoftVisualStudio                           westus
data:    MicrosoftWindowsServer                          westus
data:    MicrosoftWindowsServerEssentials                westus
data:    MicrosoftWindowsServerHPCPack                   westus
data:    MicrosoftWindowsServerRemoteDesktop             westus
data:    msopentech                                      westus
data:    MSOpenTech.Extensions                           westus
data:    mtnfog                                          westus
data:    nexus                                           westus
data:    nginxinc                                        westus
data:    OpenLogic                                       westus
data:    Oracle                                          westus
data:    predixion                                       westus
data:    primestream                                     westus
data:    PuppetLabs                                      westus
data:    redpoint-global                                 westus
data:    remotelearner                                   westus
data:    RightScaleLinux                                 westus
data:    RightScaleWindowsServer                         westus
data:    riverbed                                        westus
data:    RiverbedTechnology                              westus
data:    saltstack                                       westus
data:    sap                                             westus
data:    scalearc                                        westus
data:    seagate                                         westus
data:    searchblox                                      westus
data:    sharefile                                       westus
data:    sightapps                                       westus
data:    sios_datakeeper                                 westus
data:    sisense                                         westus
data:    softnas                                         westus
data:    SUSE                                            westus
data:    Symantec                                        westus
data:    tavendo                                         westus
data:    tentity                                         westus
data:    trendmicro                                      westus
data:    TrendMicro.DeepSecurity                         westus
data:    TrendMicro.PortalProtect                        westus
data:    typesafe                                        westus
data:    ubercloud                                       westus
data:    usp                                             westus
data:    veeam                                           westus
data:    vision_solutions                                westus
data:    waratek                                         westus
data:    wowza                                           westus
data:    xtremedata                                      westus
data:    your-shop-online                                westus
data:    zend                                            westus
info:    vm image list-publishers command OK
</code>
</pre>

**Comment by anuchandy** [comment]
Thanks @HimanshuBri  for validating. will close this once get merged to upstream
