### ISSUE TITLE
(0.8.16)azure login with  --service-principal  and after token is expired, .azure/accessTokens.json increase to 60M

### ISSUE THREAD

**Issue by qingfuwang** [Azure/azure-xplat-cli#1727]
use --service-principal login, and manually change the expired time, to rigger refresh

Then , the size of accesstokean increase to 60M, and azure command would hang 

root@qingfubosh2:/home/azureuser# ls -l /root/.azure/accessTokens.json
-rw------- 1 root root 458565 Apr 30 11:21 /root/.azure/accessTokens.json
root@qingfubosh2:/home/azureuser# azure group list >a.log
root@qingfubosh2:/home/azureuser# ls -l /root/.azure/accessTokens.json
-rw------- 1 root root 462645 Apr 30 11:22 /root/.azure/accessTokens.json
root@qingfubosh2:/home/azureuser# azure group list >a.log
root@qingfubosh2:/home/azureuser# ls -l /root/.azure/accessTokens.json
-rw------- 1 root root 466725 Apr 30 11:22 /root/.azure/accessTokens.json
root@qingfubosh2:/home/azureuser# azure group list >a.log
root@qingfubosh2:/home/azureuser# ls -l /root/.azure/accessTokens.json
-rw------- 1 root root 470805 Apr 30 11:22 /root/.azure/accessTokens.json
root@qingfubosh2:/home/azureuser# azure group list >a.log
root@qingfubosh2:/home/azureuser# ls -l /root/.azure/accessTokens.json
-rw------- 1 root root 945445 Apr 30 11:22 /root/.azure/accessTokens.json
root@qingfubosh2:/home/azureuser# azure group list >a.log
root@qingfubosh2:/home/azureuser# azure group list >a.log
root@qingfubosh2:/home/azureuser# azure group list >a.log
root@qingfubosh2:/home/azureuser# azure group list >a.log
root@qingfubosh2:/home/azureuser# azure group list >a.log
root@qingfubosh2:/home/azureuser# ls -l /root/.azure/accessTokens.json
-rw------- 1 root root 15249925 Apr 30 11:23 /root/.azure/accessTokens.json
root@qingfubosh2:/home/azureuser# azure group list >a.log
root@qingfubosh2:/home/azureuser# azure group list >a.log
^Croot@qingfubosh2:/home/azureuser#  ls -l /root/.azure/accessTokens.json
-rw------- 1 root root 61008485 Apr 30 11:28 /root/.azure/accessTokens.json

**Comment by amarzavery** [comment]
@qingfuwang - Can you please install the latest version 0.9.1 from npm.
At the same time can you provide
- the OStype ?
- node version ?

**Comment by qingfuwang** [comment]
@amarzavery  Error happens to 0.8.16, os ubuntu 1410 ,node 0.10.25.     with 0.9.1 it's better.  It will increase the size little by little. when execute a command ,it seems the expired token is read by cli , and new token is added every time.  it means if the first token is expired, the command will do token refresh every time.

**Comment by ljhljh235** [comment]
@qingfuwang 

We can reproduce the issue. We will prioritize this and fix this in a future release.
