### ISSUE TITLE
Implement equivalent of Get-AzureVMUsage -Location {} in ARM mode

### ISSUE THREAD

**Issue by BorisB2015** [Azure/azure-xplat-cli#1731]
Need functionality equivalent to PS:

> Get-AzureVMUsage -Location WestUS
CurrentValue : 20
Limit        : 20
Name         : {
                 "LocalizedValue": "Cores",
                 "Value": "cores"
               }
Unit         : 1

**Comment by anuchandy** [comment]
Feature has been added, patch available at https://github.com/MSOpenTech/azure-xplat-cli/tree/dev

**Comment by HimanshuBri** [comment]
@anuchandy @BorisB2015 Yes feature is added & working fine now 
<pre>
<code>
C:\May\15May\azure-xplat-cli-dev>node bin/azure vm list-usage westus
info:    Executing command vm list-usage
data:    Name   Unit   CurrentValue  Limit
data:    -----  -----  ------------  -----
data:    Cores  Count  11            20
info:    vm list-usage command OK

C:\May\15May\azure-xplat-cli-dev>node bin/azure vm list-usage westus --json
[
  {
    "unit": "Count",
    "currentValue": 11,
    "limit": 20,
    "name": {
      "value": "cores",
      "localizedValue": "Cores"
    }
  }
]
</code>
</pre>

**Comment by anuchandy** [comment]
Thanks @HimanshuBri for validating. We will close this once it merged to upstream

**Comment by babumuralidharan** [comment]
Fix part of sprint 49.
