### ISSUE TITLE
Object #<AzureCli> has no method 'registerResourceType' in 0.9.2

### ISSUE THREAD

**Issue by ciphertxt** [Azure/azure-xplat-cli#1734]
In the latest version of the cli on OSX (0.9.2) no commands can run due to a terminating error when running the *azure* command.

**Example:**
machine: ~user$ azure
error:   Object #<AzureCli> has no method 'registerResourceType'
info:    Error information has been recorded to /Users/user/.azure/azure.err
machine: ~user$

The full log from **azure.err** is:
[TypeError: Object #<AzureCli> has no method 'registerResourceType']
TypeError: Object #<AzureCli> has no method 'registerResourceType'
    at Object.exports.init (/usr/local/azure/lib/commands/mobile.js:27:27)
    at /usr/local/azure/lib/cli.js:747:51
    at Array.forEach (native)
    at AzureCli._.extend.harvestPlugins (/usr/local/azure/lib/cli.js:747:16)
    at new AzureCli (/usr/local/azure/lib/cli.js:59:15)
    at Object.<anonymous> (/usr/local/bin/azure:9:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by amarzavery** [comment]
@ciphertxt - Can you also provide the following information:
- What is the version of the operating system ?
- What version of node are you running? (node -v)
- How have you installed the CLI
   * npm ?
   * mac installer from [azure](http://azure.microsoft.com/en-us/downloads/)

**Comment by amarzavery** [comment]
@ciphertxt - It could be possible that the /Users/$username/.streamline folder might be corrupted. Can you please delete the .azure and .streamline directories inside the user's home directory and execute ```azure -v```. 

I tried the ```npm install azure-cli -g ``` and the mac installer and both of them worked.

```Amars-MacBook-Air:~ amzavery$ azure 
info:             _    _____   _ ___ ___
info:            /_\  |_  / | | | _ \ __|
info:      _ ___/ _ \__/ /| |_| |   / _|___ _ _
info:    (___  /_/ \_\/___|\___/|_|_\___| _____)
info:       (_______ _ _)         _ ______ _)_ _ 
info:              (______________ _ )   (___ _ _)
info:    
info:    Microsoft Azure: Microsoft's Cloud Platform
info:    
info:    Tool version 0.9.2
help:    
help:    Display help for a given command
help:      help [options] [command]
help:    
help:    Log in to an Azure subscription using Active Directory. Currently, the user can login only via Microsoft organizational account
help:      login [options] [username]
help:    
help:    Log out from Azure subscription using Active Directory. Currently, the user can log out only via Microsoft organizational account
help:      logout [options] [username]
help:    
help:    Open the portal in a browser
help:      portal [options]
help:    
help:    Commands:
help:      account        Commands to manage your account information and publish settings
help:      ad             Commands to display active directory objects
help:      apiapp         Commands to manage ApiApps
help:      availset       Commands to manage your availablilty sets
help:      config         Commands to manage your local settings
help:      feature        Commands to manage your features
help:      group          Commands to manage your resource groups
help:      insights       Commands related to monitoring Insights (events, alert rules, autoscale settings, metrics)
help:      keyvault       Commands to manage key vault instances in the Azure Key Vault service
help:      location       Commands to get the available locations for all resource types
help:      network        Commands to manage network resources
help:      provider       Commands to manage resource provider registrations
help:      resource       Commands to manage your resources
help:      role           Commands to manage your Azure roles
help:      storage        Commands to manage your Storage objects
help:      tag            Commands to manage your resource manager tags
help:      vm             Commands to manage your virtual machines
help:    
help:    Options:
help:      -h, --help     output usage information
help:      -v, --version  output the application version
Amars-MacBook-Air:~ amzavery$ 
```

**Comment by ciphertxt** [comment]
I removed the .streamline and .azure folders and still get the same error.

I'm on OSX 10.10.3. Node version is v0.12.0. I installed from the azure.com DMG installer.

**Comment by amarzavery** [comment]
Well I updated my mac to OSX 10.10.3 and node to 0.12.2. I installed from the DMG installer and everything just works fine.

```
Amars-MacBook-Air:~ amzavery$ azure
info:             _    _____   _ ___ ___
info:            /_\  |_  / | | | _ \ __|
info:      _ ___/ _ \__/ /| |_| |   / _|___ _ _
info:    (___  /_/ \_\/___|\___/|_|_\___| _____)
info:       (_______ _ _)         _ ______ _)_ _ 
info:              (______________ _ )   (___ _ _)
info:    
info:    Microsoft Azure: Microsoft's Cloud Platform
info:    
info:    Tool version 0.9.2
help:    
help:    Display help for a given command
help:      help [options] [command]
help:    
help:    Log in to an Azure subscription using Active Directory. Currently, the user can login only via Microsoft organizational account
help:      login [options] [username]
help:    
help:    Log out from Azure subscription using Active Directory. Currently, the user can log out only via Microsoft organizational account
help:      logout [options] [username]
help:    
help:    Open the portal in a browser
help:      portal [options]
help:    
help:    Commands:
help:      account        Commands to manage your account information and publish settings
help:      config         Commands to manage your local settings
help:      hdinsight      Commands to manage your HDInsight accounts
help:      mobile         Commands to manage your Mobile Services
help:      network        Commands to manage your Networks
help:      sb             Commands to manage your Service Bus configuration
help:      service        Commands to manage your Cloud Services
help:      site           Commands to manage your Web Sites
help:      sql            Commands to manage your SQL Server accounts
help:      storage        Commands to manage your Storage objects
help:      vm             Commands to manage your Virtual Machines
help:    
help:    Options:
help:      -h, --help     output usage information
help:      -v, --version  output the application version
Amars-MacBook-Air:~ amzavery$ node -v
v0.12.2
Amars-MacBook-Air:~ amzavery$ azure -v
0.9.2
Amars-MacBook-Air:~ amzavery$ 
```

**Comment by ciphertxt** [comment]
I'm glad it works for you, but I'm reporting that it doesn't work for and I'm trying to provide as much detail as possible in the event it happens to someone else and they end up here.

All the previous versions of the xpat-cli have worked just fine on this same machine.

**Comment by amarzavery** [comment]
I completely understand and thanks for providing the info. I am trying my best to reproduce the issue. 

Can you uninstall ```sudo azure-uninstall``` the installed CLI via azure-cli.0.9.2.dmg and try installing from npm.
```npm install azure-cli -g```. Hope this unblocks you.

**Comment by ciphertxt** [comment]
The downside of that particular error is that I was unable to do a clean uninstall as well. (*e.g.* `azure -uninstall` failed with the same error).

Installing directly with npm (`npm install azure-cli -g`) got it going. It wasn't taking at all from the DMG installer.

**Comment by amarzavery** [comment]
I am glad to know that you are unblocked. 

I was looking at the error stack "at Object.exports.init (**/usr/local/azure/lib/commands/mobile.js**:27:27)" and found something weird: the file  **mobile.js** should not exist at this location - "/usr/local/azure/lib/commands/mobile.js". It should rather be at "/usr/local/azure/lib/commands/**asm**/mobile.js"

```
Amars-MacBook-Air:commands amzavery$ cd asm
Amars-MacBook-Air:asm amzavery$ ls
account.affinitygroup._js	provider.js			site.config.js			site.js
account.affinitygroup.js	sb._js				site.connectionstring._js	site.log._js
account.cert._js		sb.js				site.connectionstring.js	site.log.js
account.cert.js			service._js			site.defaultdocument._js	site.repository._js
hdinsight._js			service.cert._js		site.defaultdocument.js		site.repository.js
hdinsight.js			service.cert.js			site.deployment._js		site.scale._js
iaas				service.internallb._js		site.deployment.js		site.scale.js
mobile				service.internallb.js		site.domain._js			sql._js
mobile._js			service.js			site.domain.js			sql.js
mobile.js			site._js			site.handler._js		vm
network				site.appsetting._js		site.handler.js			vm._js
network._js			site.appsetting.js		site.jobs._js			vm.js
network.js			site.config._js			site.jobs.js			websites
Amars-MacBook-Air:asm amzavery$ pwd
/usr/local/azure/lib/commands/asm
```

Looks like the previous installation was completely messed up.
