### ISSUE TITLE
Windows 0.9.2:  [SyntaxError: Unexpected token '] when creating storage account after login with service principle.

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-xplat-cli#1735]
OS: Windows 8.1 

Download Windows Installer from http://go.microsoft.com/?linkid=9828653&clcid=0x409 and install it.

I type below command successfully.
azure config mode arm
azure login -u my_client_id -p my_client_secret --tenant my_tenant_id --service-principal --quiet
azure group create bosh-rg-crp EastAsia

But when I create storage account with below command, it fails.
azure resource create bosh-rg-crp -n boshcrp Microsoft.Storage/storageAccounts –o 2015-05-01-preview -p '{"accountType":"Standard_LRS"}'

Error:
Tue May 05 2015 17:27:41 GMT+0800 (China Standard Time):
{ [SyntaxError: Unexpected token ']
  stack: [Getter/Setter],
  __frame: 
   { name: 'resource_createResource__3',
     line: 72,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\resource\\resource.js',
     prev: 
      { name: '__1',
        line: 51,
        file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\resource\\resource.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 1,
        col: 15 },
     calls: 1,
     active: true,
     offset: 23,
     col: 19 },
  rawStack: [Getter] }
SyntaxError: Unexpected token '
  <<< async stack >>>
  at resource_createResource__3 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\resource\resource.js:95:20)
  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\resource\resource.js:52:16)
  <<< raw stack >>>
    at Object.parse (native)
    at ___ (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\resource\resource.js:103:29)
    at ___ (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\interaction.js:134:16
    at ___ (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\group\groupUtils.js:53:9
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure\node_modules\azure-mgmt-resource\lib\resourceManagementClient.js:5197:16
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\utils.js:308:7
    at handleRedirect (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\utils.js:285:9)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\logging.js:244:7

**Comment by amarzavery** [comment]
@AbelHu - I found the problem.
The single quotes for the properties **'**{"accountType":"Standard_LRS"}**'**
If you provide it in double quotes then you wont see the error. "{\"accountType\":\"Standard_LRS\"}"

You also need to provide the location in which you need to create the resource. It was not provided in the command specified above.

Is there a specific reason to use the generic resource create command.

How about using the azure storage create command:
```
D:\sdk\xplat1\azure-sdk-for-node>azure storage account create -l "West US" --type LRS -g csmrg7947 mytestac101
info:    Executing command storage account create
+ Creating storage account
info:    storage account create command OK

D:\sdk\xplat1\azure-sdk-for-node>azure storage account list
info:    Executing command storage account list
+ Getting storage accounts
data:    Name         Type          Location  Resource Group
data:    -----------  ------------  --------  --------------
data:    mytest121    Standard_LRS  West US   csmrg7947
data:    mytest122    Standard_LRS  West US   csmrg7947
data:    mytestac101  Standard_LRS  West US   csmrg7947
info:    storage account list command OK
```

List of storage account commands in ARM mode -
```
D:\sdk\xplat1\azure-sdk-for-node>azure storage account -h
help:    Commands to manage your Storage accounts
help:
help:    List storage accounts
help:      storage account list [options]
help:
help:    Show a storage account
help:      storage account show [options] <name>
help:
help:    Create a storage account
help:      storage account create [options] <name>
help:
help:    Update a storage account
help:      storage account set [options] <name>
help:
help:    Delete a storage account
help:      storage account delete [options] <name>
help:
help:    Commands to manage your Storage account keys
help:      storage account keys list [options] <name>
help:      storage account keys renew [options] <name>
help:
help:    Commands to show your Storage connection string
help:      storage account connectionstring show [options] <name>
help:
help:    Options:
help:      -h, --help  output usage information
```

**Comment by AbelHu** [comment]
Thanks. You are right. That is the difference between Linux commands and Windows commands.
