### ISSUE TITLE
Error: Reauthenticate when azure <service> create.

### ISSUE THREAD

**Issue by tofteit** [Azure/azure-xplat-cli#1742]
When I try to create a mobile service (example) it says I need to reauthenticate, but I have already tried that.

I have even tried to delete the C:\Users\<user>\.azure folder without success?

Heres the error:
Wed May 06 2015 18:46:28 GMT+0200 (Rom, sommertid):
{ [Error: Credentials have expired, please reauthenticate Detailed error message from ADAL is as follows: Error: Entry not found in cache.]
  stack: [Getter/Setter],
  __frame: 
   { name: '__5',
     line: 1609,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\mobile.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 26,
     col: 32 },
  rawStack: [Getter] }
Error: Credentials have expired, please reauthenticate Detailed error message from ADAL is as follows: Error: Entry not found in cache.
  <<< async stack >>>
  at __5 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\asm\mobile.js:1635:33)
  <<< raw stack >>>
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\adalAuth.js:126:20
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\token-request.js:141:11
    at TokenRequest.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\token-request.js:468:5)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\token-request.js:138:20
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\cache-driver.js:353:7
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\cache-driver.js:227:9
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\adal-node\lib\cache-driver.js:167:5
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\token-cache.js:172:7
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\token-cache.js:50:7
    at Stream.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\authentication\win-token-storage.js:149:7)

How do I overcome this issue?

Kind Regards Alex
![error](https://cloud.githubusercontent.com/assets/11132613/7498366/8740498a-f420-11e4-913a-cf984c29b8b5.PNG)

**Comment by yugangw-msft** [comment]
run the following commands to see whether it works 
1. azure account clear -q
2. azure login
3. azure account list (to see the selected subscription is the one)
4. (run your command again)

**Comment by yugangw-msft** [comment]
also what is the azure-cli version you are using? You can type "azure -v"

**Comment by tofteit** [comment]
Hello,
Please see screenshot:
![error2](https://cloud.githubusercontent.com/assets/11132613/7500745/df5d758e-f42f-11e4-8bcf-0b0faedd0057.PNG)

Any ideas?

**Comment by yugangw-msft** [comment]
please do 2 things for further diagnostic.
1. To rule out the slim possibility of legacy old token, could you please run 'bin\windows\creds -d -t AzureXplatCli:target=* -g”' to clear up token storage of cli, then run the command again?
2. If #1 does not deal, could you turn on the environment variable of "AZURE_ADAL_LOGGING_ENABLED", and run the command, then take a look at the verbose log. If you need assistance, feel free to send the report to me: yugangw at microsoft.com. Remember to remove the password entry.  

Also are you using the account for the first time? If it is, then could you try log in using old working  account  to see whether that still works.

**Comment by tofteit** [comment]
Hello,
Seems
"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\bin\windows\creds.exe" -d -t AzureXplatCli:target=* -g
does the trick!

This is not the first time I use the account, I have used a few times before.

**Comment by stankovski** [comment]
This has been fixed in the latest version of CLI.

**Comment by benjguin** [comment]
I encountered the issue on v0.9.9 too

**Comment by djanosik** [comment]
I can confirm it's still an issue.

**Comment by yugangw-msft** [comment]
@djanosik @benjguin 
Same error like the original report? also you are on OSX, windows, or nix?

**Comment by djanosik** [comment]
Same error report. I am on Windows.

**Comment by yugangw-msft** [comment]
@djanosik 
Could you please set the environment variable of "AZURE_ADAL_LOGGING_ENABLED" to 1, run the login, and share out the console log or send it to me at yugangw at microsoft dot com. Make sure to remove your password from the log.
Also want to confirm you are using version 0.9.9, the latest, right?

**Comment by djanosik** [comment]
@yugangw-msft Here it is... https://gist.github.com/djanosik/49be12b4b4f010fd4d39

**Comment by yugangw-msft** [comment]
@djanosik thanks. Most likely the login command didn't clean up old entries before acquire new one. Could you run the command "[creds.exe](https://github.com/Azure/azure-xplat-cli/blob/dev/bin/windows/creds.exe) -s -t AzureXplatCli:target=* -g" and share out the output? You can omit the portion of "Credential: "

**Comment by djanosik** [comment]
@yugangw-msft I will try to share the output later. But I know it will fix the problem.
