### ISSUE TITLE
ASM: "LoadBalancerDistribution" flag

### ISSUE THREAD

**Issue by matiasdecarli** [Azure/azure-xplat-cli#1752]
I was looking for this option to be available using the xplat-cli, but it doesnt seem to be this way.

I can see [here](http://azure.microsoft.com/blog/2014/10/30/azure-load-balancer-new-distribution-mode/) that using the Powershell, a flag can be passed with options (In this case –LoadBalancerDistribution “sourceIP”)

Is there any way to accomplish this using the xplat-cli?

Thanks in advance

**Comment by anuchandy** [comment]
Fix: https://github.com/msopentech/azure-xplat-cli/tree/dev

**Comment by sreekanthbs** [comment]
New endpoint refactored code has the fix. It is working fine
![issue_1752_1817](https://cloud.githubusercontent.com/assets/11171941/8428146/20b83458-1f3a-11e5-9443-f3282dc7dc3b.jpg)
