### ISSUE TITLE
azure vm create Picks Undesired Storage Accounts

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1753]
Any time `azure vm create` is used to create a VM, xplat-cli goes to the subscription, lists the existing storage accounts in the specified region, picks the alphabetically first one and drops the VHD there, which is most likely a storage account that has nothing to do with VM VHDs. That's hardly the desired behavior for anyone and causes contention.

Portal does this same except it only looks at storage accounts prefixed with `portalvhds` and picks first one among those so it at least provides a better experience. 

 Also there is no option in `vm create` command to specify a storage account name or a prefix (such as `portalvhds` to use an existing set of storage accounts for VHDs --or-- create one).

Repro:

1. create a storage account named like `aaaaaa$RANDOM` in subscription in location $LOC
2. `azure vm create -l $LOC ...`
3. VHD will be dropped to the create storage account.

cc:@devigned

**Comment by anuchandy** [comment]
@ahmetalpbalkan the argument '-u, --blob-url <url>' can be used specify the storage account and container to use, but this requires the full url including name for vhd.

**Comment by ahmetalpbalkan** [comment]
@anuchandy. Oh I see. Thanks for letting me know. It looks like the experience needs to be fixed for the default case (without -u).

**Comment by anuchandy** [comment]
@ahmetalpbalkan I agree, we need a better experience. This is something we considered and implemented in ARM vm create, will come up with a plan for ASM

**Comment by kmouss** [comment]
In ARM this is supported --storage-name. We'll evaluation bringing this back to ASM mode too.

**Comment by ahmetalpbalkan** [comment]
In the ARM it looks like storage accounts created will have a "cli" prefix (e.g. `cli9d0ca3da108a9c0114314`

I'm not sure if it's worth backporting this to ASM mode. Not closing for now until either gets fixed or gets wontfix-ed.

**Comment by anuchandy** [comment]
adding fix reference: https://github.com/MSOpenTech/azure-xplat-cli/pull/349

**Comment by ahmetalpbalkan** [comment]
awesome thanks folks

**Comment by sreekanthbs** [comment]
Azure vm create default storage account changed to portalvhds* 

![issue_1753](https://cloud.githubusercontent.com/assets/11171941/8471841/b4483102-20b9-11e5-985c-14defae74a42.jpg)
