### ISSUE TITLE
[0.9.2] One typo in the result of "azure account list"

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-xplat-cli#1756]
Version: 0.9.2
When executing "azure account list", the "Tenandt Id" should be "Tenant id" in the result.

azure account list
info:    Executing command account list
data:    Name                 Id                                    Tenandt Id                            Current
data:    -------------------  ------------------------------------  ------------------------------------  -------

**Comment by yugangw-msft** [comment]
#1762 
thanks.
