### ISSUE TITLE
ARM: Always return empty

### ISSUE THREAD

**Issue by matiasdecarli** [Azure/azure-xplat-cli#1757]
Im using ARM with the correct user logged & subscription.

```
root@ubuntu-desktop:/home/matias/Workspace# azure vm list 
info:    Executing command vm list
Resource group name: resource001
+ Getting virtual machines                                                     
info:    No VMs found
info:    vm list command OK
```

Going to the new Azure Portal I can see 2 VM under that Resource Group. Am I doing something wrong here? Any command that I excecute with that (or any) resource group returns empty

**Comment by kmouss** [comment]
@matiasdecarli - how did you create these VMs using ARM or ASM? if you created them through ASM they won't show up using ARM mode. You will need to switch to the ASM mode in Azure CLI.

**Comment by matiasdecarli** [comment]
I've created them using the azure portal. Where does that leave me? ASM or ARM?

**Comment by kmouss** [comment]
Then they are built using ASM. Do you see the VM when you switch the mode to ASM: azure config mode asm

**Comment by matiasdecarli** [comment]
Yes, usign ASM mode I can see them

**Comment by kmouss** [comment]
Closing it for now.
