### ISSUE TITLE
ARM: `azure vm create [...] -p` no longer prompts for password?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1759]
In the ASM mode when I did:

    azure vm create -e 22 -l "West US" ahmetb-test.cloudapp.net "2b171e93f07c4903bcad35bda10acf22__CoreOS-Alpha-647.0.0" "azureuser"

This was assuming I was gonna use an admin password and used to prompt me a password like:

```
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
+ Looking up image 2b171e93f07c4903bcad35bda10acf22__CoreOS-Alpha-647.0.0
Enter VM 'azureuser' password:
```

Now in the ASM mode:

    azure vm create "ahmet-rg" "ahmet-testvm" "westus" "Linux" --image-name "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB" \
      -u azureuser

It gives:

```
info:    Executing command vm create
+ Looking up the VM "ahmet-testvm"
error:   You need to enable one of the following SSH login support for Linux VM:
 [1] Password only (adminPassword)
 [2] Public key only (sshPublickeyPemFile)
 [3] Both password and public key
```

So I still want to use `[1] Password only` option but I don't want to give it in the command (because I don't want anybody to read my `~/.bash_history` doesn't compromise my VMs), therefore I _may_ still need cli to prompt me for password.

* omitting `-p` but having `-u` printed above
* Adding an empty `-p` raised "argument missing" error

As a user I couldn't discover how can I get a password prompt for `vm create`. (please close if this feature is removed in the ARM mode intentionally). @devigned

**Comment by ruslangabitov** [comment]
Fixed here: https://github.com/MSOpenTech/azure-xplat-cli/pull/195

**Comment by babumuralidharan** [comment]
fix part of sprint 49
