### ISSUE TITLE
ARM: network lb address-pool create json not returning any info

### ISSUE THREAD

**Issue by HimanshuBri** [Azure/azure-xplat-cli#1763]
network lb address-pool create --json not returning any info
![lb inbound-nat-rule json problem](https://cloud.githubusercontent.com/assets/10084788/7627298/aed7c770-fa33-11e4-801f-5b2ff0fdc03a.PNG)
![lb inbound-nat-rule](https://cloud.githubusercontent.com/assets/10084788/7633766/e6926ec8-fa73-11e4-98fe-28cdb794fe51.PNG)

**Comment by anuchandy** [comment]
@HimanshuBri, @babumuralidharan Could you please verify this in this branch https://github.com/MikhailTryakhov/azure-xplat-cli .

**Comment by HimanshuBri** [comment]
@anuchandy  Working fine now,Hence Closing the issue
<pre>
<code>
C:\May\21May\azure-xplat-cli-dev>node bin/azure network lb address-pool create armresgrp21M lb21 lbadd21 --json
{
  "backendIpConfigurations": [],
  "loadBalancingRules": [],
  "provisioningState": "Succeeded",
  "name": "lbadd21",
  "etag": "W/\"00aa78bc-a802-43d5-8dc5-7fbfbef656b4\"",
  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp21M/providers/Microsoft.Network/loadBalancers/lb21/backendAddressPools/lbadd21"
}
</code>
</pre>

**Comment by anuchandy** [comment]
@HimanshuBri could you please verify this once again in dev branch?

**Comment by HimanshuBri** [comment]
@anuchandy  yes its working fine for me.I again verified.

<pre>
<code>
C:\May\22May\azure-xplat-cli-dev>node bin/azure network lb address-pool create armresgrp21M lb21 lbadd21 --json
{
  "backendIpConfigurations": [],
  "loadBalancingRules": [],
  "provisioningState": "Succeeded",
  "name": "lbadd21",
  "etag": "W/\"d004c931-f2c6-44ba-93f6-af480c6e0b59\"",
  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp21M/providers/Microsoft.Network/loadBalancers/lb21/backendAddressPools/lbadd21"
}

C:\May\22May\azure-xplat-cli-dev>node bin/azure network lb inbound-nat-rule create armresgrp21M lb21 lbinbound21 -p tcp -f 3380 -b 3381  --json
{
  "frontendIPConfiguration": {
    "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp21M/providers/Microsoft.Network/loadBalancers/lb21/frontendIPConfigurations/vip
21"
  },
  "protocol": "Tcp",
  "frontendPort": 3380,
  "backendPort": 3381,
  "idleTimeoutInMinutes": 4,
  "enableFloatingIP": false,
  "provisioningState": "Succeeded",
  "name": "lbinbound21",
  "etag": "W/\"f14cad2c-dcb3-497a-806e-53b942005eee\"",
  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp21M/providers/Microsoft.Network/loadBalancers/lb21/inboundNatRules/lbinbound21"
}
</code>
</pre>

**Comment by HimanshuBri** [comment]
@anuchandy  can we close it?

**Comment by babumuralidharan** [comment]
fix part of sprint 49
