### ISSUE TITLE
ARM: network dns-zone record-set add-record not working

### ISSUE THREAD

**Issue by sreekanthbs** [Azure/azure-xplat-cli#1764]
network dns-zone record-set add-record giving error
<pre>
<code>
C:\Apr2015\14-5\azure-xplat-cli-dev>node bin/azure network dns-zone record-set add-record azuregroup azuregroup.dnszone2 record1 AAAA -b 10.0.0.0
info:    Executing command network dns-zone record-set add-record
<b>error:   type is not defined</b>
info:    Error information has been recorded to C:\Users\sreekanthb\.azure\azure.err
error:   network dns-zone record-set add-record command failed
</code>
</pre>

**Comment by jtuliani** [comment]
Thanks for flagging.  This is a known issue, we are looking into it.  Definitely a must-fix!

**Comment by HimanshuBri** [comment]
'dns-zone record-set' not working. Have attached the screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/7698834/f2732802-fe30-11e4-9fcf-924525c87dc7.png)

**Comment by HimanshuBri** [comment]
Working fine now.

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
