### ISSUE TITLE
Help text change for dnszone commands

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1767]
All the help talks about zones ‘within a resource group’.  The words ‘within a resource group’ are unnecessary.Keep it on ‘azure network dns-zone create’. Eliminate it in all other networking commands. 
tagging @jtuliani here.

**Comment by anuchandy** [comment]
Discussed with @kmouss, @devigned and content dev @dlepow. Decided to remove the text "within the resource group"

It is not necessary to say 'within the resource group' since the command requires the resource group when necessary, so it is kind of implicit.

**Comment by HimanshuBri** [comment]
@babumuralidharan. Working fine for all network related commands. Do we need to implement the same for 'vm commands' as well.

**Comment by anuchandy** [comment]
@HimanshuBri yes we need the same change for vm commands but that we will be a different PR.

**Comment by romangromov** [comment]
Hi @babumuralidharan , @HimanshuBri it's fixed now, please make sure all is fine

**Comment by HimanshuBri** [comment]
@romangromov. Working fine for network commands. Will test for vm commands once we get a separate PR for the same.

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
