### ISSUE TITLE
remove help text in network dns-zone create --help

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1768]
Message “Must not end with a dot. Terminating ‘.’ will be removed” is too strong (it’s not a ‘must’ if we fix it for them, after all.)  Let’s just remove the message altogether.

Same applies to all commands taking the zone name as a parameter

tagging @jtuliani here.

**Comment by HimanshuBri** [comment]
@babumuralidharan. Working fine now.

**Comment by romangromov** [comment]
Hi @babumuralidharan , @HimanshuBri it's fixed now, please make sure all is fine

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
