### ISSUE TITLE
Avoid the GET if zone exists during Network dns-zone create

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1769]
The command first does a GET to see if the zone exists.  This is the wrong approach, since it is slow (an extra call) and is not resilient to concurrency issues.

Please remove the GET and instead include the HTTP header ‘if-none-match: *’ on the PUT request.  This will mean the PUT only works if the zone does not already exist in the resource group

tagging @jtuliani here

**Comment by HimanshuBri** [comment]
@babumuralidharan.
Have two doubts.
First of all after creating a DNS-zone why it is looking for the same DNS-zone. Have attached the screenshot for the same.
Secondly the error message for already created DNS-zone is not proper.
![image](https://cloud.githubusercontent.com/assets/10084788/7681139/e4abeb7e-fd8a-11e4-8a06-5bd5c98da7bf.png)

**Comment by HimanshuBri** [comment]
@babumuralidharan. Also Can we have similar implementation for during Network Dns-zone set as well. Have attached the screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/7681380/6ea578de-fd8d-11e4-9b39-d99dee9b879c.png)

**Comment by anuchandy** [comment]
@jtuliani 

As @HimanshuBri mentioned when we try to create a zone with a name already taken by another zone, the error message from server is:

"The condition * in the If-None-Match header was not satisfied"

Are you fine with showing this message as it is?

**Comment by jtuliani** [comment]
Yes.  We also display it in PowerShell, and will make it better on the server side.

**Comment by romangromov** [comment]
Hi @HimanshuBri, could you please make sure all is fine now?

**Comment by HimanshuBri** [comment]
@romangromov. The raised issue is working fine, but have two doubts can you please clarify them. Have added you in my previous comments in the same thread. Please have a look.

**Comment by romangromov** [comment]
@HimanshuBri 
* "after creating a DNS-zone why it is looking for the same DNS-zone" 
- we need to call GET to fetch and show created object
* "the error message for already created DNS-zone is not proper"
- this will be handled on server side as per @jtuliani comment

**Comment by HimanshuBri** [comment]
@romangromov. Thanks. Everything else looks fine. You can close this issue.

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
