### ISSUE TITLE
Show max no of record sets in Network dns-zone show

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1770]
Output shows number of record sets (good) but not the max number of record sets (bad).  Please add output for ‘Max number of record sets:’ immediately *after* the number of record sets.  The data is in the JSON properties for the zone.

tagging @jtuliani here.

**Comment by HimanshuBri** [comment]
@babumuralidharan. Working fine.

**Comment by romangromov** [comment]
Hi @babumuralidharan , @HimanshuBri it's fixed now, please make sure all is fine

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
