### ISSUE TITLE
Changes needed in Network dns-zone list

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1771]
Following changes are needed to be incorporated in network dns-zone list.

**1**   The location and type are kind of pointless (type is always “Microsoft.Network/dnszones” and location is always “global”, I suggest these be removed.

**2**   In future, we will support enumeration across resource groups.  In preparation for this, please add the resource group name as a column in the output.

**3**  It would be useful instead to include the number of record sets / max number of record sets as columns in the output. I.e. Columns should be Name, Resource Group, # Record Sets, Max Record Sets.

**4**  The output may be truncated.  You can detect this by the presence of the ‘nextLink’ to get the next page.  Give a warning if output was truncated.

**5**  We need to add a new parameter ‘EndsWith’.  

tagging @jtuliani here

**Comment by romangromov** [comment]
Hi @anuchandy, 
**1** and **2** will be updated.

for **3**: `number of record sets / max number of record sets` are not returned by NRP Service when call to 'list' method, related issue https://github.com/MSOpenTech/azure-xplat-cli-pr/issues/464 . Possible approach is to call `get` for every zone inside loop while listing all zones (bad approach)

for **4**: no need to show `warn` here, we have implemented `paging` feature to handle `nextLink`, related issue https://github.com/MSOpenTech/azure-xplat-cli-pr/issues/458

for **5**: please clarify `EndsWith` parameter behavior, how it will affect list output if provided? I guess it's kind of `filter`, which is used inside SDK method to filter zones

**Comment by jtuliani** [comment]
Re #3...agree that calling GET for each zone would be bad. Please ignore this ask unless/until we change the server-side behaviour.

RE #4...fantastic that you can support paging fully!  Please follow up by email to explain the customer experience.

Re #5...let's park this one for now.

**Comment by HimanshuBri** [comment]
@romangromov. Working fine.

**Comment by romangromov** [comment]
Hi @babumuralidharan , @HimanshuBri it's fixed now, please make sure all is fine

**Comment by romangromov** [comment]
@amarzavery this can be closed, implemented
