### ISSUE TITLE
Changes needed in network dns-zone set command

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1772]
__Sample command used :__ network dns-zone set --json -t a=b;c=d RG1 cli.com

*  Even though the resource group and zone name are specified on the command line, they don’t get picked up by the command, which instead prompts for them to be entered again.

* Only the first tag ‘a=b’ is recorded, the second tag ‘c=d’ is not shown in the JSON output.  Please check this works correctly for create and set commands for both zones and record sets.

@anuchandy is the tag behavior changed ? When we need to pass multiple tags we always give tags within "" or '' like "tag1=value1;tag2=value2"

tagging @jtuliani here

**Comment by romangromov** [comment]
Hi @babumuralidharan, the same case works fine for me (I'm on Windows). Looks like it's external issue on Mac/Linux inside `commander.js`. It's caused by using ";" delimiter for tags here.

@anuchandy, should we report this to One SDK team? Related issue https://github.com/MSOpenTech/azure-xplat-cli-pr/issues/302

**Comment by anuchandy** [comment]
@romangromov thank you debugging. 

One question, how commander.js behaves if we include the tag value in double quotes (also single quotes)  for example "a=b;c=d" ?

**Comment by romangromov** [comment]
@anuchandy: in `double ""` or `single ''` quotes it works fine on Linux. As far as know, ';' is operating symbol on Linux bash and will be treated as end of the command, so we can't use it as delimiter char for list of tags `wothout` quotes.

**Comment by anuchandy** [comment]
Thanks @romangromov for validating.

Hi @amarzavery, @yugangw-msft , the delimiting character for tag is ';' which will not working in Linux unless user enclose tag in single or double quotes.  I guess we need to update the documentation OR fix tagUtils. I am not sure updating tagUtil is feasible now as it will be a breaking change.

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
