### ISSUE TITLE
Changes in Network dns-zone set –-help

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1773]
Help does not explain that existing tag values will be replaced.   Suggest adding the line “Existing tag values will be replaced by the values specified”.

**Comment by romangromov** [comment]
Hi @anuchandy, when providing `--tags` in `SET` we always append, right? It's done this way for all `set` commands in ARM right now.

Should we actually replace existing `tags` in `dns-zone set` command **only** and update `help` message as well for this case only? Please, confirm.

**Comment by romangromov** [comment]
Hi @anuchandy, should we apply this change to `dns-zone set` command only or for **all** commands in ARM? Please, confirm.

**Comment by anuchandy** [comment]
Hi @romangromov, for consistency the help message for tag should be updated for all commands

**Comment by HimanshuBri** [comment]
@romangromov. Working fine.

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
