### ISSUE TITLE
Avoid get in Network dns-zone set command

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1774]
There’s no need to do any GETs beforehand.  This command should make a single API call to PATCH (as opposed to PUT) the new tags, leaving the zone properties collection empty.

Using PATCH ensures that 

a) the zone must already exist and 
b) if we add a new zone property in future, this command will not fail or overwrite that property.

If neither –tags nor –no-tags is specified, simply send a PATCH with the tags missing.  This is kind of a no operation but it serves the purpose of triggering an error if the zone does not exist, and is extensible if we add new zone properties in future.

Tagging @jtuliani here.

**Comment by romangromov** [comment]
Hi @anuchandy, I just noticed that `createOrUpdate` method actually replaces **all existing tags** instead of append new one. In this case, no way to append tags in 'SET' command without fetching zone wit `GET` call beforehand. Should we remove `GET` call beforehand anyway?

**Comment by anuchandy** [comment]
@jtuliani the SDK uses PUT for both create and update scenario, in fact SDK exposes only one method 'CreateOrUpdate' for both. 

Pointers to SDK code:

1.CreateOrUpdate Method: https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/armsdk/dnsManagementClient.js#L2470
2. Using PUT, no PATCH HTTP method used https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/armsdk/dnsManagementClient.js#L2523

**Comment by jtuliani** [comment]
Yes, it does. We will update the SDK. Let's keep this open until then.

**Comment by amarzavery** [comment]
@jtuliani @MikhailTryakhov - Any update on this?

**Comment by jtuliani** [comment]
@MikhailTryakhov can we see if the new Swagger-based SDK allows us to use PATCH as suggested above? If the SDK doesn't support PATCH then we need to fix the SDK.

**Comment by MikhailTryakhov** [comment]
Hi @jtuliani 
unfortunately there is still no PATCH command in updated SDK.
We can use PATCH only for record sets, not zones.

**Comment by MikhailTryakhov** [comment]
Moved in SDK issues
