### ISSUE TITLE
Avoid server check if zone exists during Network dns-zone delete command

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1775]
Currently this command looks up if the zone exists first.  This isn’t necessary for a delete!

If you want to differentiate the output for existing vs non-existing zones, just use the HTTP header ‘if-match: *’.  This will only work if the zone already exists.

tagging @jtuliani here

**Comment by romangromov** [comment]
Hi @babumuralidharan , @HimanshuBri it's fixed now, please make sure all is fine

**Comment by HimanshuBri** [comment]
@romangromov. Working fine for dns-zone delete. 
But i have a doubt, while trying to delete a unexisting dns-zone the message is coming as warning and info, i feel it shoulb be an error instead.have attached the screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7699909/b57879ae-fe38-11e4-9aab-3066424cd14c.png)

Also can we have the same implementation for dns-record-set as well. Have attached the screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/7699949/fe3e609a-fe38-11e4-99c6-fb5524d2dad9.png)

**Comment by romangromov** [comment]
@HimanshuBri thank you, updated for `dns-zone delete`.
Looping @roman-boltunov for `dns-record-set delete`

**Comment by HimanshuBri** [comment]
thanks @romangromov. working fine for dns-zone delete.

**Comment by roman-boltunov** [comment]
@HimanshuBri thanks for checking. For dns-record-set its on the way, PR 164.

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
