### ISSUE TITLE
changes needed in network dns-zone record-set

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1776]
The pair of parameters ‘dns-zone’ ‘record-set’ is a bit clumsy.  Whilst the record sets are child resources of the zone, the customer knows they’re working on record set resources within a zone.  Please replace with a single parameter ‘dns-record-set’ across all record set commands set.

tagging @jtuliani here

**Comment by HimanshuBri** [comment]
Working fine now.

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
