### ISSUE TITLE
Avoid making GET calls in network dns-zone record-set command

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1778]
Similar to ‘set’ on dns-zone resources, this command should not make any GET calls, instead it should call PATCH specifying only those parameters (tags / ttl) included in the command line and omitting any others.

tagging @jtuliani here

**Comment by anuchandy** [comment]
@jtuliani the SDK uses PUT for both create and update scenario, in fact SDK exposes only one method 'CreateOrUpdate' for both.

Pointers to SDK code:

1.CreateOrUpdate Method: https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/armsdk/dnsManagementClient.js#L214

2. Using PUT, no PATCH HTTP method usedhttps://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/armsdk/dnsManagementClient.js#L378

**Comment by jtuliani** [comment]
Yes, it does.  We will update the SDK.  Let's keep this open until then.

**Comment by amarzavery** [comment]
@MikhailTryakhov @jtuliani - Has this issue been resolved? If so, can this be closed?

**Comment by jtuliani** [comment]
@MikhailTryakhov can we see if the new Swagger-based SDK allows us to use PATCH as suggested above?  If the SDK doesn't support PATCH then we need to fix the SDK.

**Comment by MikhailTryakhov** [comment]
duplicates issue [#1774](https://github.com/Azure/azure-xplat-cli/issues/1774)
