### ISSUE TITLE
changes needed for network dns-zone record-set list command

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1779]
Following are the changes needed for dnszone record set list command

* No need to look up the zone first

* Remove Location column, this field is always global and is a waste of space

* Type should be truncated to show only the DNS type, not the ARM resource type, e.g. it should simply say ‘A’, ‘AAAA’, ‘CNAME’ etc.

* Remove blank lines between record sets in the output (Actually, I see this depends on screen width, but weirdly one long line means blank lines appear throughout the output, which should be fixed).

* Make sure TTL column is wide enough for large TTLs

*  Insert a new column between ‘Type’ and ‘Tags’.  Column heading should be “Records” and content is as follows:
• A records: the IP address (just the IP address, no label/prefix)
• AAAA records: the IP address
• CNAME records: the CNAME target
• MX records: preference  mailexchange (just the values, space separated, no label/prefix)
• NS records: nsdname
• SOA records: email expireTime host minimumTTL refreshTime retryTime (just the values, space separated, no labels etc)
• SRV records: priority weight port target
• TXT records: value (the txt data string)
I.e. in every case you just take the record properties and output the value of each property, space-separated.

Where multiple records exist in the record set, use one line per record, for example

![image](https://cloud.githubusercontent.com/assets/1501823/7648030/b61ddc04-fa92-11e4-85bb-d69cde410262.png)

Where records are very long, truncate them.  I suggest allowing about 35 characters. 

* The output may be truncated.  You can detect this by the presence of the ‘nextLink’ to get the next page.  Give a warning if output was truncated.

*  We need to add a new parameter ‘EndsWith’. 

tagging @jtuliani here.

**Comment by anuchandy** [comment]
@jtuliani 

Feed back: Remove of back line & splitting column value into multiple line.
 
Comment: We have known limitation related to showing long entries in tables. We use the table helper that comes with node interaction module. This is an issue that affect all CLI commands which uses this table control. 

@amarzavery @yugangw-msft @kmouss not sure but thought of asking since this is a known issue, do  you have any feedback?

**Comment by jtuliani** [comment]
OK, where there's an external constraint please focus on the other issues and we can review again.  Maybe we need to file a bug on table helper!

**Comment by HimanshuBri** [comment]
Following issues seems to be working fine 
1. No need to look up the zone first
2. Remove Location column, this field is always global and is a waste of space
3. Type should be truncated to show only the DNS type, not the ARM resource type, e.g. it should simply say ‘A’, ‘AAAA’, ‘CNAME’ etc.
4. Make sure TTL column is wide enough for large TTLs

![1779](https://cloud.githubusercontent.com/assets/10084788/7681475/3751eee8-fd8e-11e4-974f-847f4b12624a.PNG)

**Comment by anuchandy** [comment]
@HimanshuBri  thank you. @jtuliani  sure will discuss with onesdk team @amarzavery @yugangw-msft

**Comment by romangromov** [comment]
@yugangw-msft this can be closed now

**Comment by romangromov** [comment]
https://github.com/Azure/azure-xplat-cli/issues/1779

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
