### ISSUE TITLE
Fix record name to accept * during network dns-zone record-set show command

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1780]
__Sample command used__: network dns-zone record-set show rg1 jonathan.com * A

Specifying a record name as * doesn’t work.  It needs quotes, i.e. “*”.  Please fix so * can be used without the quotes.

tagging @jtuliani here.

**Comment by anuchandy** [comment]
It is the behavior of the shell + commander module. I would suggest updating the help text to reflect this.

**Comment by jtuliani** [comment]
OK

**Comment by romangromov** [comment]
@yugangw-msft this can be closed, because we always need to escape reserved terminal chars on Linux
