### ISSUE TITLE
change needed in Network dns-zone record-set delete command

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1782]
While deleting record-set under a dns-zone , no need to look up zone / record set first, just prompt and then call DELETE.

tagging @jtuliani here

**Comment by anuchandy** [comment]
@jtuliani 

For non-existing record when we issue DELETE server response is OK. Seems a server issue.

In CLI if we remove the lookup in case of delete, user always see success irrespective of existing and non-existing records.

**Comment by jtuliani** [comment]
If you use the "if-match: *" HTTP header you can differentiate existing records (200 OK) vs non-existing records (204 No Content)

**Comment by jtuliani** [comment]
Actually, the 200 / 204 split works even without the HTTP header!

**Comment by roman-boltunov** [comment]
Hi @jtuliani 
I've tried to call delete method with "if-match: *" on a non-existing record and it still returns 200 OK.
We're using API version "2015-05-04-preview".

**Comment by jtuliani** [comment]
I tried it, and I get 200 on delete of existing record and 204 on delete of non-existing record, using the same API version.  Please can you double-check?

**Comment by roman-boltunov** [comment]
@jtuliani you're right, thank you, for non-existing records it returns code 204 using -vv output. Should we handle status code 204 as an error? Please comment.

**Comment by jtuliani** [comment]
What do we do for other (non-DNS) commands?  We should be consistent.
Personally, I think it's fine not to treat this as an error.

**Comment by roman-boltunov** [comment]
@jtuliani In the other commands there are a lot look ups, so the errors are handled by they.

**Comment by anuchandy** [comment]
Other commands do a look up and throw exception in case of resource absence.

We have a plan to remove look ups in other commands, Once we do this, we will be getting "404 not found" exception  when we issue delete on non-exist resource. All server exception we surface to client (like powershell). So if we need consistency we might have to throw a custom exception in case of 204.

**Comment by jtuliani** [comment]
I'm reaching out to ARM/SDK owners for guidance on the right approach.

**Comment by anuchandy** [comment]
Thanks @jtuliani

**Comment by amarzavery** [comment]
@jtuliani @MikhailTryakhov - Has this issue been resolved?

**Comment by jtuliani** [comment]
@MikhailTryakhov My take:
•	We should either give an error or not give an error when deleting a non-existent zone, depending upon what other CLI commands for other resources do (e.g. what happens when you delete a resource group that doesn’t exist?)
•	Either way, there’s no need to GET first, since the API gives a different response in each case.

**Comment by MikhailTryakhov** [comment]
Hi @jtuliani 
I assume we can work here like in other cases with non-existing commands - throw the error if deleting record set does not exist. 
That might be not clear for user if he tried to remove record set, mistyped and got successful result.
He thinks he has deleted item, but he didn't.
Would be fixed.

**Comment by jtuliani** [comment]
Yes, error makes sense, it's a better experience in the case where the user has a typo, as you point out.
