### ISSUE TITLE
changes needed in network dns-zone record-set delete-record

### ISSUE THREAD

**Issue by babumuralidharan** [Azure/azure-xplat-cli#1783]
Following are the changes needed during record-set delete command run. 

* No need to look up the DNS zone

* After updating the record, there’s no need to look it up again.  The updated record is already returned from the PUT that did the update.

* Does not prompt for confirmation before deleting, but from the –help it looks like it should (-q –quiet mode is supported).

tagging @jtuliani here.

**Comment by anuchandy** [comment]
You mentioned that result returned by Update cannot be used to show the result. Could you please share more details - What is the difference between response of update and response of look up?

Issue reference: Azure#1783

**Comment by jtuliani** [comment]
The result returned by update CAN AND SHOULD be used to show the result.  Right now, it seems a separate GET call it made, unnecessarily.

**Comment by roman-boltunov** [comment]
@anuchandy, @jtuliani 
Let me clarify this a bit :). I actually mentioned that we need to make some look ups for DNS zone and record set just to make a proper object for 'delete-record' request. I mean the deletion of a single record of a record-set is executed via createOrUpdate method of a record-set. So here we must first obtain DNS zone, find record-set, delete a record from the javascript object and finally call createOrUpdate for record-set using this object as a parameter.
You can see it how it works here:
https://github.com/roman-boltunov/azure-xplat-cli/blob/dev-azure-bug-1783/lib/commands/arm/network/dnsRecordSet._js#L227-L251

Please reply.

**Comment by jtuliani** [comment]
Delete-record, since it removes a single record from a record set, DOES require you to GET the record set first.  It does not require you to GET the zone.

**Comment by roman-boltunov** [comment]
@jtuliani yes, you're right, I finally got it, will remove DNS zone look up.
Thank you!

**Comment by HimanshuBri** [comment]
Following issues is working fine now
1. Does not prompt for confirmation before deleting, but from the –help it looks like it should (-q –quiet mode is supported).
![1783](https://cloud.githubusercontent.com/assets/10084788/7681681/aad270c6-fd8f-11e4-9489-f5ac0ae62258.PNG)

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
