### ISSUE TITLE
ASM: Prepare design document for Network Security Group (NSG)

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-xplat-cli#1786]

**Comment by anuchandy** [comment]
Done with design documentation, review in progress. Keeping this issue open until review & implementation  is done

**Comment by sreekanthbs** [comment]
@anuchandy implementation working fine now.

**Comment by ArneCoder** [comment]
Hi all - is this already implemented in latest Version?, wondering if iam able to use NSGs with Azure-Xpat-Cli

**Comment by anuchandy** [comment]
@ArneCoder  this got merged with upstream yesterday. https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/asm/network/network._js#L262, you will see this command set in next couple of days.

**Comment by ArneCoder** [comment]
Thanks will check it out the next days!

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
