### ISSUE TITLE
ASM: Prepare design document for VPN Gateway

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-xplat-cli#1787]

**Comment by anuchandy** [comment]
Done with design documentation, review in progress. Keeping this issue open until review & implementation  is done

**Comment by anuchandy** [comment]
@devigned cloud you please re-open this issue, closed by mistake.

**Comment by anuchandy** [comment]
@devigned I found I can re-open issues so opened this.

**Comment by sreekanthbs** [comment]
@anuchandy following issues still there
#243
#244
#258

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
