### ISSUE TITLE
ASM: Prepare design document for local networks and to manage association between local network and vnet

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-xplat-cli#1805]

**Comment by anuchandy** [comment]
Done with design documentation, review in progress. Keeping this issue open until review & implementation is done

**Comment by HimanshuBri** [comment]
@anuchandy network vnet local-netwok add & remove commands are working fine now.

**Comment by romangromov** [comment]
@yugangw-msft this can be closed
