### ISSUE TITLE
Add 'vm extension remove'?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1809]
I realized `azure vm extension` does not have a subcommand to remove an extension from the VM. I feel like it's a common task that users might need.

How do you feel about adding this? @devigned @kmouss 

![image](https://cloud.githubusercontent.com/assets/159209/7852381/7ab2cc78-04b1-11e5-8cc2-5e0614131eed.png)

![image](https://cloud.githubusercontent.com/assets/159209/7852389/9a9adfee-04b1-11e5-8fc4-e6f25efa0deb.png)

**Comment by anuchandy** [comment]
running vm extension set with --uninstall flag will remove the extension from the VM.

**Comment by ahmetalpbalkan** [comment]
Aaaah totally my bad not seeing that. Thx @anuchandy.
