### ISSUE TITLE
ASM: Port conflict while creating a new VM in an existing cloud service

### ISSUE THREAD

**Issue by kmouss** [Azure/azure-xplat-cli#1810]
it seems to always complaint about the same port

#azure vm create -c -w mstorepoc -n zms-master-1 -d /var/folders/zz/5_36g6912t53xzcb1_tg667c38zlrp/T/zms.XXXXXX.ZEyfwzzg/zms-master-1.sh -t ./mstore_azure.pem -e 22004 -P -z Small -S 10.64.1.4 zmsmaster mstore-udocker-node0.11 mstore
info:    Executing command vm create
+ Looking up image mstore-udocker-node0.11
+ Looking up virtual network
+ Looking up cloud service
+ Getting cloud service properties
+ Looking up deployment
+ Configuring certificate
+ Creating VM
info:    OK
info:    vm create command OK

#azure vm endpoint create-multiple zms-master-1 5051:5050,8091:8090,8090:8090:TCP:FALSE:MARATHON:HTTP:8090:/
info:    Executing command vm endpoint create-multiple
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    Error information has been recorded to /Users/ybubnov/.azure/azure.err
error:   BadRequest : Local Port 8090 for endpoint tcp-8090-8090 is already in use by one of the other endpoints in this role. Ensure that the local port numbers are unique across endpoints within a role.
error:   vm endpoint create-multiple command failed

**Comment by anuchandy** [comment]
Here the issue is, user is trying to map two different external ports 8091 and 8090 to the same local portal 8090, which is not supported in RDFE. May i know what exactly user want to achieve by mapping multiple ports to same local port?

**Comment by anuchandy** [comment]
Are you trying to create load balanced endpoint?

There are two type of load balancer

1.	Internal Load balancer
2.	Load balancer (external facing)

When we create an end point, User may want to associate the end point with one type of LB.

To define an endpoint as part of internal load balancer (#1), we need to pass the name of the internal load balancer via --internal-load-balancer-name of endpoint create command.

To define an endpoint as part of externally facing load balancer (#2), we need to pass the name of the external facing load balancer via --lb-set-name parameter of endpoint create command. 

To refer an internal load balancer in ‘endpoint create’ via --internal-load-balancer-name, you need to first create an internal load balancer using ‘service internal-load-balancer add’ command. Please refer this article https://azure.microsoft.com/en-us/documentation/articles/load-balancer-internal-getstarted/ to understand more on internal load balancer.

To refer an external facing load balancer in ‘endpoint create’ via --lb-set-name, we don’t have to create a load balancer explicitly, it gets created when you create first endpoint with --lb-set-name parameter. Please refer this article http://blogs.technet.com/b/canitpro/archive/2015/02/05/step-by-step-load-balancing-workloads-in-azure.aspx

**Comment by kmouss** [comment]
Closing for now - unblocked.
