### ISSUE TITLE
Feature Request: SAS signatures with full URL

### ISSUE THREAD

**Issue by nyetsche** [Azure/azure-xplat-cli#1811]
It would be great if the `azure storage blob sas create` function could output an entire URL. Right now it only outputs the signature.

Ex:

```
USER at LAPTOP in ~[0] $ azure storage blob sas create VHD-STORE VHD-FILE r 2015-06-15
info:    Executing command storage blob sas create
+ Creating shared access signature for blob VHD-FILE in container VHD-STORE
data:    Shared Access Signature se=2015-06-15T00%3A00%3A00Z&sp=r&sv=2014-02-14&sr=b&sig=SIGNATURE
info:    storage blob sas create command OK
```

Ideally, it would output something like:

```
https://ACCCOUNT.blob.core.windows.net/VHD-STORE/VHD-FILE?sv=2014-02-14&sr=c&sig=SIGNATURE&st=2015-05-28T00%3A00%3A00Z&se=2015-06-05T00%3A00%3A00Z&sp=r
```

Similarly for the `azure storage container sas create`.

Right now I am using release 0.8.17.

There's precedence for this, the [Azure Storage Explorer](https://azurestorageexplorer.codeplex.com/SourceControl/latest) outputs a full URL. 

Considering that the container may need 'read' and 'list' permissions for blobs within the container, perhaps also a way to provide the 'list' permission for a blob? Even though this should only be permitted for the container, as per https://msdn.microsoft.com/en-us/library/azure/dn140255.aspx and https://github.com/Azure/azure-xplat-cli/issues/1639.

**Comment by matt-gibbs** [comment]
Thank you @nyetsche 
Closing this issue. Thank you for the fix.
