### ISSUE TITLE
azure vm delete returns success for wrong VM name

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1815]
Mode: ASM.

```sh
$ azure vm delete foo
info:    Executing command vm delete
+ Getting virtual machines
warn:    No VMs found            <-- !!!
info:    vm delete command OK
```

I think this is not good. Returning success from this command for a non-existent VM name would heavily break the scripting use case with the xplat cli. For a caller, there's no way to find out the behavior if the specified VM name was valid or not.

For a good example, look at `rm` command in POSIX. `rm foo` would fail and exit with an error code if foo does not exist; however `rm -f foo` doesn't prompt for any confirmation (semi-silent mode) and does not fail if foo doesn't exist.

I think this command should fail, but the `azure vm delete -q` (quiet mode) should pass (like the output I pasted above) if the VM doesn't exist. This would be more Unix-y way of doing this.

Thoughts? @anuchandy @devigned

**Comment by ahmetalpbalkan** [comment]
Any comments?

**Comment by devigned** [comment]
You make a great point, @ahmetalpbalkan. It should definitely fail unless quieted or forced.

**Comment by ahmetalpbalkan** [comment]
I doubt if quiet means ignoring error. For that unix tools do `-f` (like rm -rf doesnt fail if file doesnt exist).

**Comment by ahmetalpbalkan** [comment]
hopefully nobody uses ASM anymore so we're cool
