### ISSUE TITLE
ASM: VM Load balanced set endpoint view and update

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-xplat-cli#1817]
Currently once we assign load balanced set to an endpoint (thus it become load balanced set endpoint) there is no way to update any of the properties of the endpoint. Calling 'endpoint update' will fail if there are multiple endpoints associated with the lb set.

We need commands for following operations:

1. List all load balanced set in a cloud service, which should show also endpoint in different VM under the cloud service that belongs to the lb set.

2. provide a way to update the load balanced set endpoint

referring https://github.com/Azure/azure-xplat-cli/issues/1752 since distribution flag also can be updated using 2

**Comment by sreekanthbs** [comment]
Implemented List all load balanced set in a cloud service
<pre>
<code>
C:\Jul2015\Jul-2\azure-xplat-cli-dev>node bin/azure service load-balanced-set list vmetodelacl
info:    Executing command service load-balanced-set list
+ Getting cloud service deployment
data:    Name         Port
data:    -----------  ----
data:    lbTestSet33  33
info:    service load-balanced-set list command OK
</code>
</pre>

Implemented update the load balanced set endpoint
<pre>
<code>
C:\Jul2015\Jul-2\azure-xplat-cli-dev>node bin/azure vm endpoint show vmetodelacl tcp-33-33
info:    Executing command vm endpoint show
+ Getting virtual machines
data:      Name                          : tcp-33-33
data:      Local port                    : 33
data:      Protcol                       : tcp
data:      Virtual IP Address            : 23.99.80.158
data:      Direct server return          : Disabled
data:      Load balanced set name        : lbTestSet26
info:    vm endpoint show command OK
C:\Jul2015\Jul-2\azure-xplat-cli-dev>node bin/azure vm endpoint set vmetodelacl tcp-33-33 -n testLB33 -d vmetodelacl -b lbTestSet33 -i testloadname
info:    Executing command vm endpoint set
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    vm endpoint set command OK
</code>
</pre>
