### ISSUE TITLE
ASM: VM correcting endpoint parameter names

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-xplat-cli#1818]
The parameters for the 'vm endpoint' commands should be consistent with portal & power shell.

The parameter 'lb-port' should renamed to 'public-port'
The parameter 'vm-port' should be renamed to 'local-port' or private-port

**Comment by HimanshuBri** [comment]
@anuchandy  yes its working fine now
![image](https://cloud.githubusercontent.com/assets/10084788/8376341/edcd109a-1c23-11e5-990b-72d7a6bef93f.png)
