### ISSUE TITLE
ARM: 'azure vm extension list' does not exist

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1826]
$ azure vm extension list

This command does not exist in ARM mode but it does in ASM.

**Comment by anuchandy** [comment]
@ahmetalpbalkan this is a known issue, we don't have an ARM API to enumerate the extensions. We have plan to enable this command as soon as the SDK + server is updated to support this.

cc: @kmouss

**Comment by djberg96** [comment]
Was wondering about this myself, as I was writing my own wrapper and this was failing. Thanks for the heads up.

**Comment by squillace** [comment]
tagging it to get notified when it drops. Thanks!

**Comment by ahmetalpbalkan** [comment]
We now have some commandlet to do this. Closing.
