### ISSUE TITLE
Cosmetics in authentication failure message

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1840]
![image](https://cloud.githubusercontent.com/assets/159209/8146803/10723430-1202-11e5-9475-b98b0852cbdc.png)

I think this rather should be like:

> error:   Credentials have expired, please reauthenticate.
> error: Detailed error message from ADAL is as follows: Error: Entry not found in cache.

with proper sentences and punctuation.

I also think the `Detailed error message from ADAL is as follows` part should be printed when a verbose flag is present, as it totally looks like it's there for debugging reasons.

**Comment by romangromov** [comment]
Agree with @ahmetalpbalkan
