### ISSUE TITLE
Failure to login to azure config mode arm

### ISSUE THREAD

**Issue by kennetham** [Azure/azure-xplat-cli#1843]
Hi I am trying to deploy Cloud Foundry on Azure and it required me to set this up with service principal etc using Azure Xplat Cli with mode ARM.

I have been getting this error and have no idea what's the reason. I have a valid Microsoft account and Azure subscription.

```text
+ Authenticating...                                                            
error:   Server returned an unknown AccountType: undefined
info:    Error information has been recorded to /Users/kennetham/.azure/azure.err
error:   login command failed
```

Please advise what have I missed or configured wrongly or I am required to configure.

**Comment by devigned** [comment]
Try running `azure account clear -q` and then login again.

**Comment by yugangw-msft** [comment]
what does your Microsoft account look like? a live account? If yes, no, it is not supported by xcli,

**Comment by kennetham** [comment]
@devigned I will try that.
@yugangw-msft I'm on Bizspark Subscription so my Microsoft account is using my company's email. It's not a live account. I linked my company email to a Microsoft account.

**Comment by kennetham** [comment]
@devigned I tried `azure account clear -q` and I still get the same error. I checked out the log it says that there is an undefined service. What could be the reason? I am on a Microsoft account, do I need some kind of different account setup within Azure?

**Comment by devigned** [comment]
@kennetham it sounds like you are trying to use an account that is not an Azure organization account (an Azure Active Directory user account) or a service principal. 

If your login doesn't end with onmicrosoft.com, you will need to create an [organization account](https://azure.microsoft.com/en-gb/documentation/articles/resource-group-create-work-id-from-personal/) or a [service principal](https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/) to login.

**Comment by kennetham** [comment]
@devigned OH I need this step before I can do a `azure login`? I suppose this is what I need to achieve eventually. I will try that out thanks!

**Comment by kennetham** [comment]
@devigned alright it's fixed! That's the one I needed to setup! Thank you!

**Comment by devigned** [comment]
@kennetham we are working to improve this auth flow. Glad we could help you get going.
