### ISSUE TITLE
Add support to run arbitrary commands on Web Apps

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-xplat-cli#1849]
I have a Web App that I'm deploying via FTP.  I'd like to be able to trigger actions in my environment after successful upload.  These actions don't require scripts and simply involve calling code that is already deployed to the environment.

It would be nice if there was a way to just remotely run something, without the overhead of making it a permanent web job.

**Comment by amarzavery** [comment]
@NaveenGoli - Can you please respond to this feature request?

**Comment by NaveenGoli** [comment]
is there a reason why you wouldn't like to use webjob?

**Comment by atrauzzi** [comment]
Because they are extremely slow and unfriendly for one-off tasks like running migrations.  I have no feedback on when a job completes, so I can't sequence anything.

This story is made worse by the fact that you can only automatically trigger behaviour cloud-side when deploying via git.

AWS offers the ability to run one-off remote tasks simply by taking a command to run on the remote.  It's an extremely useful feature and necessary in many cases for things like migrations.

**Comment by davidebbo** [comment]
Please see similar question [on forum](https://social.msdn.microsoft.com/Forums/azure/en-US/ade4e9c8-ac69-4dad-9073-12eaa46ffb33/remotely-trigger-work-without-creating-a-web-job?forum=windowsazurewebsitespreview), which is a better place than here (it's not an xplat cli issue).

**Comment by davidebbo** [comment]
BTW, the Kudu [Command API](https://github.com/projectkudu/kudu/wiki/REST-API#command) does that.

**Comment by atrauzzi** [comment]
Again, a question I already asked and got an unsatisfactory answer.  The answer there was webjobs as well.  Which I've already described here as not being sufficient.

**Comment by amarzavery** [comment]
As described in the comments above that this is not an xplat cli issue but a websites service issue. Hence closing this one.
