### ISSUE TITLE
autocomplete bash script very slow

### ISSUE THREAD

**Issue by kangman** [Azure/azure-xplat-cli#1850]
using the instructions provided on the readme.md page to enable autocomplete for the cli.  When I press tab to see option it takes a few seconds for options to populate as well as two tab presses. 

Also there is no documentation within the cli tool for the --completion flag.

**Comment by yugangw-msft** [comment]
This performance issue have been fixed in the dev branch and we plan to publish out next week.
FYI, you can take a look at the simple gif file displaying the perf improvement
https://github.com/Azure/azure-xplat-cli/pull/1829

**Comment by yugangw-msft** [comment]
#1832 addressed this.
