### ISSUE TITLE
ASM: VM endpoint create is ignoring --load-balanced-set-name parameter

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-xplat-cli#1865]

**Comment by HimanshuBri** [comment]
@anuchandy  working fine now
<pre>
<code>
C:\June\24june\azure-xplat-cli-dev>node bin/azure vm endpoint create DNdjava6 27 -k 27 -n vmEndpt1 -o tcp -m 15 -b LbSetTest1
info:    Executing command vm endpoint create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    vm endpoint create command OK

C:\June\24june\azure-xplat-cli-dev>node bin/azure vm endpoint show Dndjava6 vmEndpt1
info:    Executing command vm endpoint show
+ Getting virtual machines
data:      Name                          : vmEndpt1
data:      Local port                    : 27
data:      Protcol                       : tcp
data:      Virtual IP Address            : 191.239.51.219
data:      Direct server return          : Disabled
data:      Connection timeout (minutes)  : 15
<b>data:      Load balanced set name        : LbSetTest1</b>
info:    vm endpoint show command OK
</code>
</pre>
