### ISSUE TITLE
storage account list not working

### ISSUE THREAD

**Issue by cmdrkeene** [Azure/azure-xplat-cli#1866]
I have an account set and have been able to complete other tasks (create docker hosts, create a vnet, etc.) but something is broken with the storage command:

This is for version 0.9.3.

Trying to install 0.9.4 but no OS X installer has been released

![screen shot 2015-06-23 at 3 14 19 pm](https://cloud.githubusercontent.com/assets/22959/8314922/bf72d6dc-19ba-11e5-95ad-53108350a4dd.png)

**Comment by yugangw-msft** [comment]
So you are using osx installer version 0.9.3, correct? Could you paste here the stack traces from azure.err?

**Comment by cmdrkeene** [comment]
This is fixed in 0.9.4 - closing :)
