### ISSUE TITLE
azure login would reset current subscription

### ISSUE THREAD

**Issue by qingfuwang** [Azure/azure-xplat-cli#1875]
In arm mode
Steps:
1 azure login 
2 set azure account
3 azure login
Expect
after step 3, the default subscription  set in step 2, remain default
Actual
the default subscription is reset

**Comment by amarzavery** [comment]
That is not the desired behavior. On every login, CLI sets the first subscription in the list as the default subscription.

**Comment by qingfuwang** [comment]
Thanks for your confirm , i also thought it could be by design , but may be it's a scenario you team over look.

**Comment by yugangw-msft** [comment]
@qingfuwang. Agreed, imo, we should do better when we have resources, for 2 reasons.
1.  Most time I log in just for the reason to refresh the token, so to continue to use the commands, so i have 0 interests to see the account get switched
2. A good system should remember user's references and make users' life easier. This ask essentially is the same with many cookie usage in a browser, the IDE settings of Visual Studio. The software tries to remember your settings, and make you feel it gets personalized for you.
Yes, for this bug we can take a look. Please let me know if anything is missing.

**Comment by ahmetalpbalkan** [comment]
@amarzavery 

> On every login, CLI sets the first subscription in the list as the default subscription.

why is this a desired behavior?
