### ISSUE TITLE
ASM: 0.9.5 update breaks `azure vm create` semantics

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1888]
This command used to work in 0.9.4:

    azure vm create -e -l 'West US' mytestvm b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB  azureuser 'myPa$$w0rd'

Now what happens after 0.9.5 is, I try ssh-ing to the VM and what I get is:

```
$  ssh azureuser@mytestvm.cloudapp.net
The authenticity of host 'mytestvm.cloudapp.net (23.99.55.87)' can't be established.
RSA key fingerprint is re:da:ct:ed:34:e5:c3:13:f4:1a:01:3c:ee:8e:cd:f3.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'mytestvm.cloudapp.net,23.99.55.xx' (RSA) to the list of known hosts.
Permission denied (publickey).
```

I tried explicitly specifying username/password with -g/-p, that doesn't work either. My suspicion is, this command is not sending the username/password to the API correctly. 

When I go back to 0.9.4, **exact same command works just fine**. This is **breaking change** in terms of semantics/behavior of how CLI works, have we documented this behavior if it's intended?

@kmouss @devigned

**Comment by devigned** [comment]
We need to have a test for each regression. This shouldn't happen.

**Comment by ahmetalpbalkan** [comment]
@devigned can you please verify it's valid and not just me?

**Comment by kmouss** [comment]
@ahmetalpbalkan, I've just tried this with 0.9.5 and I was able to login; the only difference I created a VM in Central US. Maybe you can run your command with verbose to further debugging. Adding @babumuralidharan 
```
AzureBook:~ kmouss$ azure vm create -e -l 'Central US' kmtestvm1 b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB  azureuser 'myPa$$w0rd' 
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
+ Looking up image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_10-amd64-server-20141020-en-us-30GB
+ Looking up cloud service                                                     
info:    cloud service kmtestvm1 not found.
+ Creating cloud service                                                       
+ Retrieving storage accounts                                                  
+ Creating VM                                                                  
info:    vm create command OK
```

```
AzureBook:~ kmouss$ ssh azureuser@kmtestvm1.cloudapp.net
The authenticity of host 'kmtestvm1.cloudapp.net (104.43.173.50)' can't be established.
RSA key fingerprint is d4:ba:53:8e:52:71:01:3d:e8:65:bc:af:d7:1e:18:c2.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'kmtestvm1.cloudapp.net,104.43.173.50' (RSA) to the list of known hosts.
azureuser@kmtestvm1.cloudapp.net's password: 
Welcome to Ubuntu 14.10 (GNU/Linux 3.16.0-23-generic x86_64)
```

**Comment by ahmetalpbalkan** [comment]
@kmouss yes it worked me as well. Looks like I was reusing the hostname and it collided with ~/.ssh/known_hosts even though I cleared the file in advance. Rebooting solved the problem.
