### ISSUE TITLE
ARM: -vv (more verbose) option is not documented

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1894]
![image](https://cloud.githubusercontent.com/assets/159209/8439343/4796b474-1f20-11e5-9375-88afd7239e6b.png)

So I just ran this `azure vm disk attach-new` command with `-v` flag, I was expecting to see some verbose output, all I saw actually was `info` level strings.

The reason I tried to use `-v` was more analogous to `curl -v` as I wanted to see what comes and goes in the wire (i.e. HTTP requests) to trace if the issue I'm hitting indeed is a bug... 

I can't use fiddler as I'm on Mac, and in #1163 I saw that proxy support was rejected so I can't do mitmproxy either. So I don't know how to debug this. I thought -v is for that but it disappointed me.

What do you think about making -v actually verbose? @devigned

**Comment by devigned** [comment]
What about `-vv`? That should give you very verbose.

**Comment by devigned** [comment]
or as it displays on the screen 'silly:'...

**Comment by ahmetalpbalkan** [comment]
OK it does the job although it is not documented :)

**Comment by devigned** [comment]
I'm currently working on some nice templates to take our `azure help --json` and transforming it into some pretty documentation.

**Comment by devigned** [comment]
it's documented, but not very well: https://github.com/Azure/azure-xplat-cli/blob/master/Documentation/Debugging.md

**Comment by ahmetalpbalkan** [comment]
I read this as “it's written somewhere on the interwebs; not where people would usually look for it at”. :wink:

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan , @devigned 
We already documented it in the read.md. With the PR, I have re-organized the text under a top level section called "error diagnostic". The mentioned will appear along with setting up the "web debug proxy"

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft If it's a valid input to the program (esp. if it's a command line option) IMO should be documented on the program itself as well. If I'm using this tool for a few months, I am just going to run `azure -h` and see if there's a verbose flag. And if it's not there, I'm going to come to github (definitely not going to read that long README), and open an issue (like I did here).

All tools out there define their verbosity flags like `-D`, `--debug`, `-v`, `-vv`, `-vvv` in the help string for a few decades now. Let's not break this convention. If there's a special output format or an extra verbosity level, we can use environment variables and document them on README, however not documenting `-vv` on the CLI does not make sense to me.

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan 
okay, I didn't get the original point, but it is just reasonable. So take a look what i have in my box, and let me know. 
Since I am touching the command rendering, I also took other folks' suggestions and display the current mode. 
![image](https://cloud.githubusercontent.com/assets/6014209/9149102/a2ea916a-3d4d-11e5-850a-f3a9184f0428.png)

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft that's good progress. I think I can live with that. But if we want to make it totally right, here's one suggestion: In the screenshot above, the main cmd is `azure` and subcmd is `vm` which has another subcmd `start`.

Since `-vv` is `azure`-wide, it would be better to have it as `azure -vv vm start -h`. This reads as: “azure in debug mode, show help for `vm start`”. Many command line tools that has sub-commands I know out there follow this convention and define their verbosity flag on the main cmd rather than subcmd. Ideally what I'd like to see is

* we only show `-vv` in the `azure --help`
* the command above should be like `azure -vv vm start [args]`

This is a clear logical separation and makes the docs of subcommands shorter and clearer. But I will let you guys decide.

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan thanks for the suggestion. My comments here,
1. Cli has 4 default options including "-h", "--json", "-v", and "-vv". Have you thought of accommodating all of them in the suggestion. If we only do it for "-vv", we have consistency loss.
2. "-vv" is just to output more information. We can understand it as "azure in debug mode", but it is a subjective view. For now Cli treats as a default option like the rest 3, I like to keep it that way as it is pretty clear at conceptual level. I can reconsider when it confuses users of using the commands.
3.  I don't use lots of other clis. Could you mention a comparable one which does your suggested and I can cross check. I checked out the "git" commands. Commands I regular use have a common option "--dry-run" and "-v", but I don't see the help is organized like suggested.

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft yeah I guess that layout is not necessary. your screenshot above sounds good. Shall we go with that?

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan, yes, let us go with that. PR was merged.

**Comment by ahmetalpbalkan** [comment]
Thanks.
