### ISSUE TITLE
ARM: 'vm disk attach-new' does not take --disk-name param

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1895]
Based on `-vv` this command creates a disk name like `VMName-YYYYMMDD-HHmmss` and uses it. This can be great default, however I'd like to provide my own disk name as well (with something like `--disk-name`).

**Comment by devigned** [comment]
That seems like it could be a pretty quick PR if you are interested.

**Comment by ahmetalpbalkan** [comment]
It'll probably take a lot of time of mine to get familiar with node.js, add the feature, figure out how to add tests+docs etc than somebody who's already familiar with the codebase :-) So I'm just leaving this here. If this was in #golang, I could just jump in but I can't :-(

**Comment by devigned** [comment]
No worries. We'll give it a look. Thank you for the suggestion.

**Comment by ruslangabitov** [comment]
Change command a bit: https://github.com/MSOpenTech/azure-xplat-cli/pull/403
Now you can set disk's name via --vhd-name option

**Comment by ahmetalpbalkan** [comment]
@ruslangabitov you rock!

**Comment by sreekanthbs** [comment]
@ruslangabitov  its working fine now  we can set disk's name via --vhd-name option
![image](https://cloud.githubusercontent.com/assets/11171941/8795403/70738da0-2faa-11e5-992b-8e015f3f5be6.png)
