### ISSUE TITLE
ARM: azure vault : Issues while importing or creating keys to azure vault

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#1898]
I have created new software vault as below:

azure config mode arm
azure group create 'testresourcegroup' 'North Europe'
azure provider register Microsoft.KeyVault
azure keyvault create --vault-name 'testkeyvault' --resource-group 'testresourcegroup' --location 'North Europe'

The output is below:

info:    Executing command keyvault create
+ Checking pre-condition                                                       
warn:    No object ID is selected. The current user's object ID will be used by default
+ Creating vault testkeyvault                                              
info:    Created vault testkeyvault
data:    properties sku family "A"
data:    properties sku name "Standard"
data:    properties tenantId "xxxxxxxxxxxxxxxxxxxxxxxxx"
data:    properties accessPolicies 0 tenantId "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
data:    properties accessPolicies 0 objectId "yyyyyyyyyyyyyyyyyyyyyyyyyyyyy (upn=test@testmail.com)"
data:    properties accessPolicies 0 permissions keys 0 "get"
data:    properties accessPolicies 0 permissions keys 1 "create"
data:    properties accessPolicies 0 permissions keys 2 "delete"
data:    properties accessPolicies 0 permissions keys 3 "list"
data:    properties accessPolicies 0 permissions keys 4 "update"
data:    properties accessPolicies 0 permissions keys 5 "import"
data:    properties accessPolicies 0 permissions keys 6 "backup"
data:    properties accessPolicies 0 permissions keys 7 "restore"
data:    properties accessPolicies 0 permissions secrets 0 "all"
data:    properties enabledForDeployment false
data:    properties vaultUri "https://testkeyvault.vault.azure.net"
data:    id "/subscriptions/xxxxxxxxxxxxxxxxxxxxxx/resourceGroups/test/providers/Microsoft.KeyVault/vaults/testkeyvault"
data:    name "testkeyvault"
data:    type "Microsoft.KeyVault/vaults"
data:    location "North Europe"
warn:    This vault does not support HSM-protected keys. Please refer to http://go.microsoft.com/fwlink/?linkid=512521 for the vault service tiers.
warn:    When creating a vault, specify the --sku parameter to select a service tier that supports HSM-protected keys.
info:    keyvault create command OK

When I try to add or import new keys, i'm getting below error:

azure keyvault key create --vault-name 'testkeyvault' --key-name 'testkey' --destination software
info:    Executing command keyvault key create
+ Creating key https://testkeyvault.vault.azure.net/keys/testkey           
error:   Cannot call method 'create' of undefined
info:    Error information has been recorded to /home/testuser/.azure/azure.err
error:   keyvault key create command failed

i'm using 0.9.5 version of azure cli

**Comment by akshaycj47** [comment]
I am facing the same issue. Were you able to fix this?

**Comment by amarzavery** [comment]
@karlaugsten, @msfcolombo - Any plans to fix this issue?

**Comment by msfcolombo** [comment]
Investigating...

**Comment by msfcolombo** [comment]
Works for me on 0.9.10, Windows. Verifying Linux...

**Comment by akshaycj47** [comment]
I am able to login, list subscriptions, change the config mode to 'arm', show all locations, create resource group.

But when I try to create a key vault, I get an error. I am getting the following error stack:

2016-02-23T22:12:02.401Z:
{ [Error: Unauthorized]
  stack: [Getter/Setter],
  code: 'Unauthorized',
  statusCode: 401,
  requestId: 'e6ebce7a-6180-45f9-bd4f-2205e40d9729',
  __frame:
   { name: '__1',
     line: 51,
     file: '/usr/local/azure/lib/commands/arm/keyvault/keyvault.key.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 26,
     col: 33 },
  rawStack: [Getter] }
Error: Unauthorized
  <<< async stack >>>
  at __1 (/usr/local/azure/lib/commands/arm/keyvault/keyvault.key.js:77:34)
  <<< raw stack >>>
    at Function.ServiceClient._normalizeError (/usr/local/azure/node_modules/azure-common/lib/services/serviceclient.js:815:23)
    at /usr/local/azure/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:44:29
    at Request._callback (/usr/local/azure/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/local/azure/node_modules/azure-common/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/azure/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/azure/node_modules/azure-common/node_modules/request/request.js:1111:12)

**Comment by msfcolombo** [comment]
@akshaycj47, your trace indicates you are doing a key operation on an existing vault, not creating a new vault. The unauthorized means you don't have required permissions in the vault. Please use the keyvault show command to query permissions. In case you can't fix or find the issue, please send the result of keyvault show, plus the exact command that is failing. Thanks.

**Comment by msfcolombo** [comment]
@amarzavery Works for me on 0.9.15, Linux. I think we can close this.

**Comment by amarzavery** [comment]
@msfcolombo - Sounds good. closing this one.
