### ISSUE TITLE
Passwordless SSH key prompts password for ARM azure vm create

### ISSUE THREAD

**Issue by sedouard** [Azure/azure-xplat-cli#1900]
Working with @aglazer On version 0.95 Set to arm mode and do:

```
azure vm create --resource-group USEast --name mongo-az-us-e-03 --location eastus --os-type Linux --image-urn Canonical:UbuntuServer:14.04.2-LTS:14.04.201506100 --admin-username ubuntu --admin-password alsAA33daldkjads$ --ssh-publickey-file path/to/passwordless/pemfile.pem --vm-size Standard_DS12 --vnet-name VNetUSEast --vnet-subnet-name DatabaseSubnet --nic-name mongo-az-us-e-03 --availset-name Mongo-US-East --storage-account-name mongouseastgrs 
```

The CLI prompts for a password but it should not.

**Comment by ruslangabitov** [comment]
Fixed here: https://github.com/Azure/azure-xplat-cli/commit/68913c8361469cca6e3a8f6fd9dedd863687ed7f

**Comment by sreekanthbs** [comment]
@ruslangabitov yes its working fine now.Thanks

![image](https://cloud.githubusercontent.com/assets/11171941/9135389/6889ae84-3d2a-11e5-93bb-78fc08827cc4.png)

**Comment by sedouard** [comment]
Closing this out. Thanks!
