### ISSUE TITLE
Aspnet5 deployment script generator still references KRE instead of DNX

### ISSUE THREAD

**Issue by madhon** [Azure/azure-xplat-cli#1901]
doing the following should generate a deploy.cmd which uses DNX/DNVM etc not KRE as it is at the moment

```
azure site deploymentscript --aspNet5 path\to\project.json
```

**Comment by amarzavery** [comment]
@davidebbo @aelnably - any plans to fix this?

**Comment by davidebbo** [comment]
Just sent PR: https://github.com/Azure/azure-xplat-cli/pull/3048
