### ISSUE TITLE
Still getting the multiple interfaces error while attempting to create VM in Azure

### ISSUE THREAD

**Issue by Kahelek** [Azure/azure-xplat-cli#1910]
This is bumming me out .. 

C:\Windows\System32>azure vm create -z Large -l "South Central US" -n MyBrandNew-VM -w traffictrace -b "Frontend,Backend-2,Backend-3" -s "ABCDE" -f "port1:Frontend::traffictrace:Enabled","port2:Backend-2::traffictrace:Enabled","port3:Backend-3::traffictrace:Enabled" tr
affictrace.cloudapp.net Forti-disk-image azure Azure12345678!
info:    Executing command vm create
+ Looking up image Forti-disk-image
+ Looking up virtual network
+ Looking up cloud service
warn:    --location option will be ignored
+ Getting cloud service properties
+ Looking up deployment
+ Creating VM
error:   Roles with secondary network interfaces can only be part of ONE subnet.
info:    Error information has been recorded to C:\Users\kkoenig\.azure\azure.err
error:   vm create command failed

**Comment by Kahelek** [comment]
This is with node.js.  This is supposed to be fixed, per the post here:
https://github.com/Azure/azure-xplat-cli/issues/1785

I installed the latest .MSI from this article, node.js is running fine.  Just not this procedure.

**Comment by Kahelek** [comment]
I think my problem is that azure-xplat-cli is not installed with the Windows version, although it seems logical that would be available per the MSI file to install at https://github.com/MSOpenTech/azure-xplat-cli/tree/dev 

The problem is, even using that MSI file on that link, azure-xplat-cli is not installed anywhere that you can find on your system, afterward. 

Directory of C:\Users\kahelek\AppData\Roaming\npm\node_modules

07/12/2015 12:39 PM 
.
 07/12/2015 12:39 PM ..
 07/12/2015 12:39 PM azure-cli
 0 File(s) 0 bytes
 3 Dir(s) 108,462,469,120 bytes free

so, it's not clear where I should clone this package and get the paths to align properly to test this out..

**Comment by Kahelek** [comment]
Cloned this in Desktop to node_modules, still not working,  bug doesnt seem fixed on windows



C:\Users\kahelek\AppData\Roaming\npm\node_modules\azure-xplat-cli [master]> azure vm create -z Large -l "South Central US" -n MyBrandNew-VM -w traffictrace -b "Frontend,Backend-2,Backend-3" -s "16c05fab-1b55-48fa-bdaa-2101ea2bedf1" -f "port1:Frontend:10.0.1.10:traffictrace:Enabled,port2:Backend-2:10
.0.2.10:traffictrace:Enabled,port3:Backend-3:10.0.3.10:traffictrace:Enabled" traffictrace.cloudapp.net Forti-disk-image azureadmin Passwordyy123!!
info:    Executing command vm create
+ Looking up image Forti-disk-image
+ Looking up virtual network
+ Looking up cloud service
warn:    --location option will be ignored
+ Getting cloud service properties
+ Looking up deployment
+ Creating VM
error:   Roles with secondary network interfaces can only be part of ONE subnet.
info:    Error information has been recorded to C:\Users\kahelek\.azure\azure.err
error:   vm create command failed

C:\Users\kahelek\AppData\Roaming\npm\node_modules\azure-xplat-cli [master]>

**Comment by anuchandy** [comment]
@Kahelek The error from  Azure server says 'The virtual machine can be part of only one subnet when there are more than one NIC', looking at the command you have used, here we are trying to associate the VM to more than one subnet.

This error also means - all NICs of a VM must be part of one and only one subnet associated with the VM.

**Comment by Kahelek** [comment]
Hi Anu,  hope all's well.  you missed the point.  :-)  This is not a constraint.

By your own admission, and prior submission:

Currently PS supports adding multiple NIC to VM http://azure.microsoft.com/blog/2014/10/30/multiple-vm-nics-and-network-virtual-appliances-in-azure/

This is with node.js. This is supposed to be fixed, per the post here:
#1785

I am running into the same error this #1785 post professes to have fixed..

**Comment by anuchandy** [comment]
@Kahelek , you are right, the statement "all NICs of a VM must be part of one and only one subnet associated with the VM." is wrong. 

Can you please try below:

Specify only one subnet as value for --subnet-names argument. This should be considered as the subnet for primary and default NIC of the VM.

For the other two NICs specify required subnet as a part of --nic-config param, where each nic info is in the form <nicName>:<subnetName>:[vnetStaticIP]:[nsgName]:[ipForwarding] . Use comma to separate nic infos.

**Comment by Kahelek** [comment]
Hi Anu

Indeed that did the trick. it wasn't clear at first that the proper selection was to constrain the identifiable subnets for the VM to the front-facing subnet, but sure enough.  That did it.

Thanks again ! ! !
