### ISSUE TITLE
Cmd: `azure vm image list` in arm mode is tough to use

### ISSUE THREAD

**Issue by devigned** [Azure/azure-xplat-cli#1912]
Azure vm image list is difficult to use when in arm mode. Say I would like to grab the latest 14.04 Ubuntu box. I need to know too much information to find the box. I need to determine the region and the publisher prior to searching for an image.

I should be able to type `azure vm image search ubuntu` and get all of the ubuntu boxes back.

As a user, I don't care who the publisher and where the boxes are located until after is see what I want.

**Comment by amarzavery** [comment]
closing this as it is a low priority issue for the service team.
