### ISSUE TITLE
Switching between azure config mode arm and asm

### ISSUE THREAD

**Issue by devigned** [Azure/azure-xplat-cli#1913]
I first login with asm via `azure account download` and `azure account import [file path]`. I run some asm commands and everything works fine. 

- Then I switch to ARM mode, I should be prompted to login if I have no Azure Active Directory credentials available.
- Upon successful `azure login`, after working in asm, I am unable to execute calls against arm as I'm greeted with the following
```bash
info:    Executing command vm image list
/error:   The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.
info:    Error information has been recorded to /Users/david/.azure/azure.err
error:   vm image list command failed
```
I must run `azure account clear` to remove all of my credentials and run `azure login` again to be able to use arm.

- The same thing will happen if I start in arm mode with `azure login` and shift back to asm mode.

The credential switching between these two modes is misleading and prone to failure. Users should have an intuitive experience when shifting between modes. The credentials for asm should not be mixed with arm unless they can be, and users should be warned that they will need to login with new credentials to allow access to arm. Finally, after the user logs in to the second mode, the credentials should work and not require running `azure account clear`.

**Comment by huangpf** [comment]
+1

**Comment by yugangw-msft** [comment]
I fixed. No "account clear"  will be needed
