### ISSUE TITLE
How to load balance docker containers

### ISSUE THREAD

**Issue by mpilant** [Azure/azure-xplat-cli#1916]
I would like to know if it is possible, using the Azure CLI on Ubuntu 14.04 LTS, to create a set of VMs with the Docker Extension to use the Azure Load Balancer.  Looking at the "azure vm docker create" it looks like it *might* be possible, but everything I've tried has failed.
Suggestions greatly appreciated.
- Mark

**Comment by amarzavery** [comment]
@kmouss , @devigned - Is this possible? What do you guys think?

**Comment by mpilant** [comment]
I still have not been able to determine if it is possible with the Azure CLI, but I was able to do it using *both* portals (both current and preview portals are required).  Although at the moment, there seems to be a real network performance hit resulting in the two VMs I'm using having only about half the transaction performance of a single non-load balanced VM.  Very strange.

**Comment by devigned** [comment]
I have not done this, but I imagine you should be able to. You'd just have to make sure you are load balancing on publicly exposed container ports.

@Azure/azure-linux-team what do you think about this one?

**Comment by ahmetalpbalkan** [comment]
I don't think the question has anything to do with Docker.  At the end, it's web servers running on virtual machines.

@mpilant I'm not sure I understood the question fully here. I am assuming you have servers created through portal and load balancing works just fine jn those (and you checked) however the azure CLI docker command for some reason associate the VM correctly with the Azure Load Balancer. Is that the case?

**Comment by ahmetalpbalkan** [comment]
@mpilant I think `azure vm [docker] create` command is designed to support quickstart scenario where user just wants to have one VM up and running with no other topology specified. In other words, I don't think everything is allowed through the CLI (David can comment better on this).

Have you looked at our new ARM templates model where you can describe the entire topology (including having docker engine on a VM) as JSON files and deploy through CLI/portal? In your scenario, you can create a template file describing your load balancer and multiple VMs part of the atomic deployment unit and everything will be created the same way every time you deploy it. It's more configurable and givest finest control over what's happening compared to the CLI commands.

**Comment by mpilant** [comment]
@ahmetalpbalkan So if I understand you correctly, the short answer is it is not possible to create a load balanced set using the Azure CLI.  However, with that being said, there may be another method allowing the creation without having to use the Azure portals.
Does that sound correct?

**Comment by ahmetalpbalkan** [comment]
I am not sure about supporting load balanced sets through the CLI. @devigned want to comment on this? ^

**Comment by amarzavery** [comment]
@mpilant - The V2 version (ARM) of Azure provides you a capability to create a loadbalancer and have multiple vms in it.

This [article](https://azure.microsoft.com/en-us/documentation/articles/load-balancer-get-started-internet-arm-cli/) provides you more info on how to create one. The next steps in this article also provide you more info on different variations of the loadbalancer.

I am closing this issue for now. Please feel free to reopen this issue or open a new issue if you find any problems with the new approach.
