### ISSUE TITLE
ARM: Add complete mode when creating new deployment

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-xplat-cli#1921]
Add complete mode when creating new deployment

**Comment by devigned** [comment]
:+1: + @squillace

**Comment by squillace** [comment]
Yes. Definitely must have support for incremental and complete.

**Comment by sedouard** [comment]
:+1: +1000

**Comment by vivsriaus** [comment]
This has already been implemented and will be out in the next CLI release (next week).
