### ISSUE TITLE
No license field. when installing from source via npm

### ISSUE THREAD

**Issue by kangman** [Azure/azure-xplat-cli#1923]
getting this error

```
npm WARN package.json azure-cli@0.9.5 
```

**Comment by amarzavery** [comment]
@kangman - I do not see the warning "No license field". Can you pull from upstream dev and verify?
```
D:\sdk\xplat1\azure-xplat-cli>npm install
npm WARN package.json eyes@0.1.8 No repository field.
npm WARN package.json node-uuid@1.2.0 No repository field.
npm WARN package.json swagger-schema-official@2.0.0-a33091a No repository field.
npm WARN package.json tunnel@0.0.2 'repositories' (plural) Not supported. Please pick one as the 'repository' field
```

**Comment by kangman** [comment]
Hey @amarzavery,

I messed around with the package.json and it seems the license portion is not reading correctly when running npm install.  pulled the dev branch and tried npm install.  same error.  

removed the "licenses" section and replaced it with 

```
"license": "Apache-2.0",
```

after that the install worked fine.

**Comment by kangman** [comment]
Also when playing with the original licenses section I get

npm WARN package.json azure-cli@0.9.5 license should be a valid SPDX license expression

Also it was weird that your license is plural with an array with type and url in there which was causing the SPDX issue. 

https://docs.npmjs.com/files/package.json#license

for reference the SPDX licenses https://spdx.org/licenses/

**Comment by namdiemefo** [comment]
hello guys , im pretty new to Node.js and im trying to install the cat-me dependency and the node_modules folder isnt showing in my project folder . 

here is the error irs showing -  `npm WARN namdi@1.0.0 No repository field.`

**Comment by namdiemefo** [comment]
hello guys , im pretty new to Node.js and im trying to install the cat-me dependency and the node_modules folder isnt showing in my project folder . i use visual studio code

here is the error its showing - npm WARN namdi@1.0.0 No repository field.

**Comment by namdiemefo** [comment]
hello guys , im pretty new to Node.js and im trying to install the cat-me dependency and the node_modules folder isnt showing in my project folder . i use visual studio code

here is the error its showing - `npm WARN namdi@1.0.0 No repository field.`
