### ISSUE TITLE
Remember default subscription choice between logins

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1925]
Every time my `azure login` credentials expire (pretty much happens 5 times a day), my default subscription choice (`azure account set {subsid}`) goes away and after I `azure login` the first subscription that appears in `azure account list` is selected as default.

I don't know how this subscription list is sorted but choosing the first subscription never makes sense to me and I keep redeploying things to wrong subscription by mistake.

I actually aliased my command to 

    alias azurelogin="azure login -u my@email && azure account set {mysubsid}"

That's a broken user experience right here. We should remember user's default subscription preference between logins and honor it if possible (i.e. logged in with the same account again) OR stop choosing a default for the user.

**Comment by yugangw-msft** [comment]
Agreed. See my comment at https://github.com/Azure/azure-xplat-cli/issues/1875 with similar ask.
We will address it.

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft thanks. Let's keep this open until fixed publicly.
