### ISSUE TITLE
`azure login` error sentence punctuation

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1931]
![image](https://cloud.githubusercontent.com/assets/159209/8734763/0b1efecc-2bc1-11e5-9713-e49976bd29f5.png)

The highlighted sentence is what %99.9 of the users are interested in. It should end with a period followed by a `\n` or "Detailed error message from ADAL" probably should go to a more verbose logging level (-vv)?

**Comment by ahmetalpbalkan** [comment]
It's very weird, I just re-ran the same command without reauthenticating and it worked.

**Comment by amarzavery** [comment]
This has been partially fixed in this PR https://github.com/Azure/azure-xplat-cli/pull/1907.

**Comment by ahmetalpbalkan** [comment]
Looks good enough. Thanks.
