### ISSUE TITLE
--run-list does not appear to work

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-xplat-cli#1933]
When I enable the chef extension and pass in a run list, it does not run it. I'm not sure if I have the syntax incorrect or if this is an incomplete parameter. This is the command i'm using:

    azure vm extension set-chef appserv1 --validation-pem /etc/chef/my-validator.pem --run-list ['appserver'] --client-config /etc/chef/client.rb --verbose

**Comment by anuchandy** [comment]
+ @siddheshwar-more

**Comment by aarsan** [comment]
I had the syntax wrong. It does actually work.
