### ISSUE TITLE
Admin password should be optional for Linux if ssh public key is specified

### ISSUE THREAD

**Issue by greenmang0** [Azure/azure-xplat-cli#1938]
In `azure vm create`, specifying `--admin-password` should be optional, if `--ssh-publickey-file` is specified for `--os-type Linux`

**Comment by ruslangabitov** [comment]
@greenmang0 I assumed that you are using CLI in ARM mode.
We had this issue in previous release, it is fixed now. Can you try it again?

**Comment by greenmang0** [comment]
@ruslangabitov, 

Yes, I am using CLI in ARM mode. Following command worked for me.

`azure vm create -g foorg -n foovm -l westus -y Linux -Q "Canonical:UbuntuServer:12.04.5-LTS:12.04.201507070" -M ~/.ssh/fookey.pub -F foovnet -j foosubnet -r foostorage -u foouser -f foonic` 

Thanks.
