### ISSUE TITLE
Creating a VNet with "azure network vnet create" destroys the VPN configuration of another network

### ISSUE THREAD

**Issue by mgarstecki** [Azure/azure-xplat-cli#1943]
Network manipulations with the CLI seem to erase informations about VPNs in the network configuration.

Scenario :
* I have a VNet (let's name it VNet-A) with a VPN connection to a distant network (let's name it CORP). The link is up and working.
* I execute a vnet create command. For example : 
```shell
azure network vnet create --vnet test-VNet --address-space 10.82.0.0 --cidr 16 --subnet-name main --subnet-start-ip 10.82.0.0 --subnet-cidr 24 --location "West Europe"
```
* The VNet is correctly created, however VNet-A has lost its VPN connection.
* When I download the network XML file, the `LocalNetworkSite` for the CORP network is still present, however the `Gateway` element of VNet-A has disappeared, including the `LocalNetworkSiteRef` for the CORP network.

I suspect this is due to a serialization/deserialization problem, that doesn't handle the Gateway element in the XML and filters it out. I couldn't confirm this with a rapid look at the code though.

This is quite an important bug to us, as we can't automate network operations through the CLI with this problem.

Azure CLI --version : "0.9.4 (node: 0.10.25)" on Ubuntu 14.04 LTS.

Edit : in ASM mode.

**Comment by anuchandy** [comment]
@mgarstecki could you check version 0.9.6? We did fixed this issue https://github.com/Azure/azure-xplat-cli/issues/1806. Please let us know if you see issue with this version..

**Comment by mgarstecki** [comment]
Thank you for your reply, I'll test the new version as soon as I can mount an isolated subscription (I don't want to kill my VPN again).

Hopefully I can do that tomorrow, I'll keep this issue updated.

**Comment by mgarstecki** [comment]
I've tested version 0.9.6 and can confirm the issue is fixed.

Thanks !
