### ISSUE TITLE
ARM: `group deployment create` bad JSON file causes a vague error message

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1956]
I have an `azuredeploy.parameters.json` file which has bad JSON syntax in it, but I don't know yet.

Then I'm running and getting a vague error message like:

```
$ azure group deployment create -g ahmetb-swarm-0 -n swarm-0 -f azuredeploy.json -e azuredeploy.parameters.json
info:    Executing command group deployment create
error:   Unexpected token a
info:    Error information has been recorded to /Users/alp/.azure/azure.err
error:   group deployment create command failed
```

I think we should simply parse those two files once and see if the JSON parsing fails. 

I opened the issue originally without knowing my JSON file was malformed and this error message led to a lot of confusion and I thought CLI was buggy.

**Comment by ahmetalpbalkan** [comment]
Happens in full parameter names as well...

```
azure group deployment create \
  --resource-group ahmetb-swarm-0 \
  --template-file azuredeploy.json \
  --parameters-file azuredeploy.parameters.json
```

**Comment by devigned** [comment]
Looks like it's choking on the parameters.json when it's parsing. At least that's my guess based only on the stack trace.

**Comment by ahmetalpbalkan** [comment]
@devigned you're right looks like JSON syntax was invalid. We should probably come up with a better error message here. Editing the issue.

**Comment by devigned** [comment]
Yes, absolutely. The error needs to be helpful.

**Comment by ravbhatnagar** [comment]
Fixed
