### ISSUE TITLE
service principal works on Windows but doesn't work on a Mac

### ISSUE THREAD

**Issue by flomader** [Azure/azure-xplat-cli#1958]
I created a Service Principal in Azure Active Directory in order to login to the Azure xplat cli. On my Windows machine everything works fine - i can login with the service princial and manage my resources.
When I run 'azure login --service-principal' with the same service principal on my Mac I can also log in and the subscription gets added. But when I run a command like 'azure group list' (or any other command to manage my resources) I get the error 'error:   No service key found for appid xxx'.

**Comment by amarzavery** [comment]
@flmader - Can you provide the following info:

- node version (node -v)
- azure version (azure -v)
- how did you install CI on Mac (via mac installer or via npm)?

**Comment by flmader** [comment]
Windows: 
node - v.0.12.2
azure - 0.9.6
npm - 2.7.4

Mac:
node - v0.12.7
azure - 0.9.6
npm - 2.11.3

I installed azure-cli on both machines via npm:
npm install -g azure-cli

Thanks!

**Comment by yugangw-msft** [comment]
@flomader I am able to reproduce it on mac, i will take a look and let you know when the fix is made
