### ISSUE TITLE
ARM: Show output object of template deployment result

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1961]
Some templates emit outputs like this:

![image](https://cloud.githubusercontent.com/assets/159209/8895799/1320c1fa-339b-11e5-8f09-29576c291087.png)

And they get shown on the portal like:

> ![image](https://cloud.githubusercontent.com/assets/159209/8895801/216a4542-339b-11e5-81dd-451d77344e87.png)

when the deployment succeeds.

However when I deploy from CLI, that's not shown there and I have to go to the portal to find out about the output. That can be more seamless...

For instance, instead of showing me the template parameters I already know about, the CLI can show me the output of the deployment perhaps?

---------------

Current template deployment success output for reference:

![image](https://cloud.githubusercontent.com/assets/159209/8895824/2a62689a-339c-11e5-942c-5678ff9254ba.png)

**Comment by ahmetalpbalkan** [comment]
@devigned any ideas here?

**Comment by devigned** [comment]
Yeah, the output of the deployment would be convenient. Hmm... that shouldn't be that hard considering it's on the GET for the deployment (https://msdn.microsoft.com/en-us/library/azure/dn790565.aspx).

**Comment by ahmetalpbalkan** [comment]
Let's do this, this'll be a very cool feature, I promise. I've been postponing giving certain talks just b/c this feature is missing.

**Comment by jameshowe** [comment]
+1 This would really help in scenarios where you need to some post processing e.g. update a config file with a connection string.

**Comment by ahmetalpbalkan** [comment]
I realized this is now fixed. And looks very cool. Thank you all.

![image](https://cloud.githubusercontent.com/assets/159209/9807542/6c224b7e-5809-11e5-9f85-a829b1d4feb7.png)
