### ISSUE TITLE
Can't see resource group logs. Throws incorrect api version

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-xplat-cli#1976]
When "azure group log show" is executed, the following error is returned:

The resource type 'eventtypes' could not be found in the namespace 'microsoft.insights' for api version '2014-04'. The supported api-versions are '2014-04-01,2014-11-01,2015-04-01'.

**Comment by yugangw-msft** [comment]
should be addressed by #1975.we are rolling out a new release
