### ISSUE TITLE
Docs needed for How to use CLI for Azure China

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1978]
Issue #1880 still goes on...

I have an account on Azure China realm and I'm using `azure login` to sign in to the subscription using an AAD account:

```
➭ azure account clear -q
info:    Executing command account clear
info:    Account settings cleared successfully
info:    account clear command OK

➭ azure login
info:    Executing command login
warn:    Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
Username: ahmetb@[REDACTED].partner.onmschina.cn
Password: **************
+ Authenticating...
error:   Server returned an unknown AccountType: undefined
info:    Error information has been recorded to /home/azureuser/.azure/azure.err
error:   login command failed
```

This experience seems broken. @devigned @yugangw-msft 

Also I should mention that as a user, I could not find any instructions on the web on how to use Azure CLI in China by Googling for quite a while. I came to GitHub repo and searched among closed issues (something we should not expect from a user) and came across this method. This info should not stay buried here. @squillace

**Comment by devigned** [comment]
We will get this documented. The following should work:
```bash
azure login -e AzureChinaCloud
```
That should acquire a token from the onmschina.cn graph endpoint and be used for future requests.

**Comment by ahmetalpbalkan** [comment]
@devigned that solved, changed the issue title to reflect we need clear for this.

**Comment by devigned** [comment]
Fantastic! Glad that helped. 

Thank you for bringing this issue up. We'll get this documented.

**Comment by ahmetalpbalkan** [comment]
Thanks




—Alp
http://alp.im
