### ISSUE TITLE
"azure storage" commands do not honor China API choice

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#1979]
I used

    azure login -e AzureChinaCloud

to log in to the Azure China Cloud and all the ASM commands like `azure vm list -vv` are correctly honored this choice, requests are made to `management.core.chinacloudapi.cn`. However when I run storage commands like:

    azure storage blob      upload  -a $account -k $key [...] -vv
    azure storage container list  -a $account -k $key [...] -vv

I can see them being routed to `.blob.core.windows.net` and thus I get an authentication error back:

```
➭ azure storage container list -a $account -k $key -vv
info:    Executing command storage container list
verbose: Getting storage containers
[2015-08-04T21:27:53.490Z]debug : FINAL REQUEST OPTIONS:
{ url: 'https://myaccount.blob.core.windows.net:443/?comp=list&include=metadata',
  method: 'GET',
[...]
[.... REDACTED....]
[...]
info:    Executing command storage container list
+ Getting storage containers
error:   Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:62cbc3d3-0001-0004-13fc-cea388000000
Time:2015-08-04T21:28:50.6618545Z
info:    Error information has been recorded to /home/azureuser/.azure/azure.err
```

I'm currently **blocked** on a task due to this. I appreciate any private fix drops.

@devigned @yugangw-msft

**Comment by yugangw-msft** [comment]
@yaxia could you please clarify? Note, the storage endpoint is not defined as part of azure environment property, so i do not know anywhere to cross check.
All china cloud environment is defined here: https://github.com/Azure/azure-xplat-cli/blob/dev/lib/util/profile/environment.js#L225

**Comment by gangsir** [comment]
We will get this fixed in next release. For now, I suggest you to set an environment variable with name "AZURE_STORAGE_CONNECTION_STRING" and specify the endpoints explicitly in the connection string like this:
BlobEndpoint=https://<accountname>.blob.core.chinacloudapi.cn/;QueueEndpoint=https://<accountname>.queue.core.chinacloudapi.cn/;TableEndpoint=https://<accountname>.table.core.chinacloudapi.cn/;FileEndpoint=https://<accountname>.file.core.chinacloudapi.cn/;AccountName=<accountname>;AccountKey=<account key>;

More details here: https://azure.microsoft.com/en-us/documentation/articles/storage-azure-cli/

**Comment by ahmetalpbalkan** [comment]
@gangsir the request still goes to `core.windows.net`. Here's the env and the command executed with it. It parses `AccountName` just fine however ignores `BlobEndpoint`:

```
$ AZURE_STORAGE_CONNECTION_STRING=BlobEndpoint=https://dockerextension.blob.core.chinacloudapi.cn/;AccountName="dockerextension";AccountKey="tlOwh[...REDACTED...]Lv1w==;" \
    azure storage container list -vv

[2015-08-05T17:29:03.035Z]debug : FINAL REQUEST OPTIONS:
{ url: 'https://dockerextension.blob.core.windows.net:443/bundle/docker-20150804-181925.zip',
  method: 'PUT',
...
```

**Comment by ahmetalpbalkan** [comment]
@gangsir any ETAs for the next release or the fix?

**Comment by ahmetalpbalkan** [comment]
@gangsir any ETAs for the next release or the fix? We have a product that relies on the xplat-cli in its release cycle and this is currently blocking the China release.

**Comment by ahmetalpbalkan** [comment]
@gangsir any ETAs for the next release or the fix?

**Comment by gangsir** [comment]
@ahmetalpbalkan sorry for late reply. Did you double check that you have an environment variable set correctly?

**Comment by ahmetalpbalkan** [comment]
@gangsir thanks, realized I had an extra `"` in my connection string and instead of erroring out, it was defaulting to Azure PROD realm. It works now.
