### ISSUE TITLE
Network Security Group command rejects single IP addresses

### ISSUE THREAD

**Issue by kleptog** [Azure/azure-xplat-cli#1980]
While creating an nsg I get an error:

    $ azure network nsg rule create my-nsg allow-me --type inbound -f 8.8.8.8/32 -o '*' -e '*' -u '*' --action Allow --priority 100

The address is obviously fictional, but it fails with an error:

    info:    Executing command network nsg rule create
    warn:    Using default protocol: Tcp
    error:   IPv4 source address prefix must be in CIDR format. Asterix can also be used
    info:    Error information has been recorded to /.../.azure/azure.err
    error:   network nsg rule create command failed

The problem is in lib/util/vnet.util._js where it defines a defaultCidrRange to be 8..29, so I can't add single IP using /32. Given this is about firewall rules it's annoying that you can't limit access to a single IP. I suggest changing the 29 to 32 since it is clearly a valid CIDR.

**Comment by roopafelix** [comment]
I created NSG for my subnet abc.
Added two rules 
Here i have application deployed into  VM.After applying these two rules. .It should deny accessing from all IP's Except 8.8.8.8/32 .But Issue here is
"I am unable to access my application in 8.8.8.8/32 also"

Name     : MyVNetSG
Location : South Central US
Label    : Security group for my Vnet in South central  US
Rules    : 
           
              Type: Inbound
           
           Name                 Priority  Action   Source Address  Source Port   Destination      Destination    Protocol
                                                   Prefix          Range         Address Prefix   Port Range             
           ----                 --------  ------   --------------- ------------- ---------------- -------------- --------
           Allow IP             100       Allow    8.8.8.8/32  *             *                *              TCP     
           Deny all             500       Deny     0.0.0.0/0       *             *                *              TCP     
           ALLOW VNET INBOUND   65000     Allow    VIRTUAL_NETWORK *             VIRTUAL_NETWORK  *              *       
           ALLOW AZURE LOAD     65001     Allow    AZURE_LOADBALAN *             *                *              *       
           BALANCER INBOUND                        CER                                                                   
           DENY ALL INBOUND     65500     Deny     *               *             *                *              *       
           
           
              Type: Outbound
           
           Name                 Priority  Action   Source Address  Source Port   Destination      Destination    Protocol
                                                   Prefix          Range         Address Prefix   Port Range             
           ----                 --------  ------   --------------- ------------- ---------------- -------------- --------
           ALLOW VNET OUTBOUND  65000     Allow    VIRTUAL_NETWORK *             VIRTUAL_NETWORK  *              *       
           ALLOW INTERNET       65001     Allow    *               *             INTERNET         *              *       
           OUTBOUND                                                                                                      
           DENY ALL OUTBOUND    65500     Deny     *               *             *                *              *     

I am trying this from past two days.Please help
