### ISSUE TITLE
Error: tenantID cannot be null

### ISSUE THREAD

**Issue by garimakhulbe** [Azure/azure-xplat-cli#1985]
I am trying to create a service principal using below CLI command:

 azure ad app create --name "testscale" --home-page "https://testscale" --identifier-uris "https://testscale" --password <password> --verbose

I am getting this error "tenantID cannot be null."
![image](https://cloud.githubusercontent.com/assets/9362976/9102679/f3498be8-3ba9-11e5-8e64-c4100ca9a452.png)

When I do 'azure account list', few of my subscriptions have tenantId as 'undefined'. Don't know how/why.
![image](https://cloud.githubusercontent.com/assets/9362976/9102740/e0784846-3baa-11e5-9ede-609482406cd2.png)

I am not able to add roles in service principle due to this error. How can I set tenantId for the subscription or any other solution to this? Please help. Thanks.

**Comment by devigned** [comment]
@amarzavery @yugangw-msft why would we have a tenant id that is null? That seems like a bug.

**Comment by yugangw-msft** [comment]
@devigned, most likely the user is not logging in as a org-id. I suggest reference to this issue for explanation https://github.com/Azure/azure-xplat-cli/issues/1948

**Comment by garimakhulbe** [comment]
Thanks.
