### ISSUE TITLE
Azure AD not working with MFA

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#1986]
Issue similar to bug:1935

I had an organizational account with MFA enabled, but login worked fine with CLI (0.9.6) until yesterday (both for asm and arm mode). But it is not allowing to login today.

error: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50079: Strong authentication enrollment (proof-up) is required.\r\nTrace ID: 4510b277-97b7-4fdf-8864-b35d2b1d2db4\r\nCorrelation ID: 8f4b18db-1a94-45b8-8374-7b0ff1816bb9\r\nTimestamp: 2015-08-06 10:11:56Z","error_codes":[50079],"timestamp":"2015-08-06 10:11:56Z","trace_id":"4510b277-97b7-4fdf-8864-b35d2b1d2db4","correlation_id":"8f4b18db-1a94-45b8-8374-7b0ff1816bb9","submit_url":null,"context":null}

I'm not able to figure out why. Also, do we have any option of using CLI in arm mode now?

**Comment by devigned** [comment]
Why comment on the other issue and open a new one? I have responded to your comment on the other issue. Please use a service principal as explained in #1935.
