### ISSUE TITLE
ASM: Attaching reserved ip to cloud service

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#1988]
Do we have any support for Attaching reserved ip to cloud service using CLI?

Equivalent command of Get-AzureReservedIPAssociation - ReservedIPName xxx -ServiceName yyyy

**Comment by danielschonfeld** [comment]
+1 well needed!

**Comment by MikhailTryakhov** [comment]
Fixed and already on Prod
