### ISSUE TITLE
ASM: NSG rule creation with netmask 32 has error

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#1990]
I tried to create nsg rule using
azure network nsg rule create --source-address-prefix xx.xx.xx.xx/32

it complains of below error in cli 0.9.6

info:    Executing command network nsg rule create
error:   IPv4 source address prefix must be in CIDR format. Asterix can also be used

I am able to do the same with azure powershell

**Comment by keymon** [comment]
+1

**Comment by romangromov** [comment]
@infosatheesh2020 can you please show me an example cmdlet you are using in `azure powershell` to work with `xx.xx.xx.xx/32` ? Thanks in advance

**Comment by infosatheesh2020** [comment]
@romangromov The below command works with powershell
Get-AzureNetworkSecurityGroup -Name PerftestNSG | Set-AzureNetworkSecurityRule -Name AllowBastionInbound-1-P-any -Type Inbound -Priority 1010 -Action Allow -SourceAddressPrefix 191.205.141.6/32 -SourcePortRange * -DestinationAddressPrefix * -DestinationPortRange * -Protocol TCP

**Comment by romangromov** [comment]
@infosatheesh2020 this can be closed

**Comment by infosatheesh2020** [comment]
@romangromov Thanks!
