### ISSUE TITLE
ASM: NSG rule creation with source port Asterik has error

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#2002]
azure network nsg rule create --nsg-name SatheeshTestNSG --name DenySSH --protocol TCP --source-address-prefix * --source-port-range * --destination-address-prefix * --destination-port-range 22 --action Deny --priority 1009 --type Inbound 
info:    Executing command network nsg rule create
error:   source port parameter must be an integer between 0 and 65535

**Comment by romangromov** [comment]
@infosatheesh2020 can't repro this issue, the `Asterisk` for `--source-port-range` works fine for me

**Comment by infosatheesh2020** [comment]
@romangromov , Atleast it is reproduceable for me in 0.9.7

[test@bigboy scripts]$ azure network nsg rule create --nsg-name AdminNet_NSG --name "ALLOW VNET OUTBOUND" --protocol * --source-address-prefix "VIRTUAL_NETWORK" --destination-address-prefix "VIRTUAL_NETWORK" --destination-port-range * --action Allow --priority 900 --type Outbound
info:    Executing command network nsg rule create
error:   Given protocol is invalid, supported values are Tcp, Udp, *
info:    Error information has been recorded to /home/test/.azure/azure.err
error:   network nsg rule create command failed

[test@bigboy scripts]$ azure network nsg rule create --nsg-name AdminNet_NSG --name "ALLOW VNET OUTBOUND" --protocol "*" --source-address-prefix "VIRTUAL_NETWORK" --source-port-range "*" --destination-address-prefix "VIRTUAL_NETWORK" --destination-port-range "*" --action Allow --priority 900 --type Outbound
info:    Executing command network nsg rule create
error:   IPv4 source address prefix must be in CIDR format. Asterix can also be used
info:    Error information has been recorded to /home/test/.azure/azure.err
error:   network nsg rule create command failed

[test@bigboy scripts]$ azure -v
0.9.7

**Comment by sreekanthbs** [comment]
@infosatheesh2020  @romangromov  can't repro this issue. the Asterisk for --source-port-range works fine for me.
![image](https://cloud.githubusercontent.com/assets/11171941/9464736/fa7a60fa-4b43-11e5-8a73-4864481fa183.png)

**Comment by romangromov** [comment]
@sreekanthbswe need to verify on Mac/Linux as well, looks like it's environment related issue

**Comment by sreekanthbs** [comment]
@romangromov yes in linux the issue is reproducible

![image](https://cloud.githubusercontent.com/assets/11171941/9465604/9b540ef2-4b4b-11e5-8b32-0d47c4bce5c8.png)

**Comment by romangromov** [comment]
@sreekanthbs thanks, please verify fix in our repo

**Comment by sreekanthbs** [comment]
@romangromov its working for me for all the below cases : 
--source-port-range \* or
--source-port-range '*' or
--source-port-range "*"
![p1](https://cloud.githubusercontent.com/assets/11171941/9491073/fd177bba-4c09-11e5-98f0-13d7f17a54b5.png)
![p2](https://cloud.githubusercontent.com/assets/11171941/9491074/fd323446-4c09-11e5-8b68-ef6663d90794.png)

**Comment by romangromov** [comment]
Thank you @sreekanthbs.

Hi @infosatheesh2020, we will include fix for reported issue in next release, thank you

**Comment by infosatheesh2020** [comment]
@romangromov, will this fix in next release includes fix for /32 CIDR ranges in NSG? because Both needs to be fixed so that end user can really use it. until then people really can't use CLI for managing all their needs in NSG

**Comment by romangromov** [comment]
Hi @infosatheesh2020, please get latest Xplat-CLI `v0.9.9`, this issue should be fixed, please let me know, thanks in advance

**Comment by infosatheesh2020** [comment]
@romangromov nice to hear. Since v0.9.9 is not available in npm, i tried 

git clone https://github.com/Azure/azure-xplat-cli.git
cd ./azure-xplat-cli
npm install

But still its showing v0.9.8. Do I need to wait until release..

**Comment by romangromov** [comment]
@infosatheesh2020 please switch branch with `git checkout release-0.9.9`

**Comment by infosatheesh2020** [comment]
Am I missing something?
[samanoha@bigboy azure-xplat-cli]$ git branch
  dev
* release-0.9.9
[samanoha@bigboy azure-xplat-cli]$ git pull -r
Current branch release-0.9.9 is up to date.
[samanoha@bigboy azure-xplat-cli]$ npm install
npm WARN package.json eyes@0.1.8 No repository field.
npm WARN package.json node-uuid@1.2.0 No repository field.
npm WARN package.json swagger-schema-official@2.0.0-a33091a No repository field.
npm WARN package.json tunnel@0.0.2 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
[samanoha@bigboy azure-xplat-cli]$ azure -v
0.9.8

**Comment by romangromov** [comment]
please run `git checkout release-0.9.9`. Also note: issue with types `INTERNET, VIRTUAL_NETWORK, AZURE_LOADBALANCER` still exist, I'm working on fix now, will post update here

**Comment by infosatheesh2020** [comment]
@romangromov i'm not able to get it through :) No issues, I can wait until npm package is available.

[samanoha@bigboy azure-xplat-cli]$ git checkout release-0.9.9
Already on 'release-0.9.9'
Your branch is up-to-date with 'origin/release-0.9.9'.

[samanoha@bigboy azure-xplat-cli]$ npm install
npm WARN package.json eyes@0.1.8 No repository field.
npm WARN package.json node-uuid@1.2.0 No repository field.
npm WARN package.json swagger-schema-official@2.0.0-a33091a No repository field.
npm WARN package.json tunnel@0.0.2 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field

[samanoha@bigboy azure-xplat-cli]$ azure -v
0.9.8

Thanks for looking into fixes for VIRTUAL_NETWORK, etc.. This will help us to manage all rules with CLI :+1:

**Comment by sreekanthbs** [comment]
Hi @romangromov verified  asterisk, INTERNET, VIRTUAL_NETWORK, AZURE_LOADBALANCER are supported for prefixes as well as CIDR format.
root@DndLinuxVM:/home/azureuser/azure-xplat-cli-dev-asm-nsg-fixes# node bin/azure network nsg rule list TESTNSG7SEP
info:    Executing command network nsg rule list
+ Looking up the network security group "TESTNSG7SEP"
data:    Name                               Source address prefix  Source port rangr  Destination address prefix  Destination port range  Protocol  Type      Action  Priority
data:    ---------------------------------  ---------------------  -----------------  --------------------------  ----------------------  --------  --------  ------  --------
data:    testnsgrule7sep                    *                      *                  *                           22                      TCP       Inbound   Deny    1009
data:    testnsgrule7sep1                   10.0.0.0/22            22                 10.0.1.0                    22                      TCP       Inbound   Deny    1010
data:    testnsgrule7sep2                   VIRTUAL_NETWORK        22                 VIRTUAL_NETWORK             22                      TCP       Outbound  Deny    1011
data:    testnsgrule7sep3                   AZURE_LOADBALANCER     22                 INTERNET                    22                      TCP       Outbound  Deny    1013
data:    testnsgrule7sep4                   10.0.0.0               80                 *                           22                      TCP       Outbound  Deny    1014
data:    testnsgrule7sep5                   INTERNET               80                 10.0.1.0                    22                      TCP       Outbound  Deny    1015
data:    testnsgrule7sep6                   INTERNET               80                 AZURE_LOADBALANCER          22                      TCP       Outbound  Deny    1016
data:    ALLOW VNET OUTBOUND                VIRTUAL_NETWORK        *                  VIRTUAL_NETWORK             *                       *         Outbound  Allow   65000
data:    ALLOW VNET INBOUND                 VIRTUAL_NETWORK        *                  VIRTUAL_NETWORK             *                       *         Inbound   Allow   65000
data:    ALLOW INTERNET OUTBOUND            *                      *                  INTERNET                    *                       *         Outbound  Allow   65001
data:    ALLOW AZURE LOAD BALANCER INBOUND  AZURE_LOADBALANCER     *                  *                           *                       *         Inbound   Allow   65001
data:    DENY ALL OUTBOUND                  *                      *                  *                           *                       *         Outbound  Deny    65500
data:    DENY ALL INBOUND                   *                      *                  *                           *                       *         Inbound   Deny    65500
info:    network nsg rule list command OK

**Comment by romangromov** [comment]
@sreekanthbs nice to hear, thank you!

**Comment by infosatheesh2020** [comment]
@romangromov, Still I am having the below error while creating NSG rules

[samanoha@test tools]$ azure network nsg rule create --nsg-name GatewayNSG --name ALLOW_AZURE_LOAD_BALANCER_INBOUND --source-address-prefix AZURE_LOADBALANCER --source-port-range * --protocol * --destination-address-prefix * --destination-port-range * --action Allow --priority 1001 --type Inbound
info:    Executing command network nsg rule create
error:   Given protocol is invalid, supported values are Tcp, Udp, *
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   network nsg rule create command failed

[samanoha@test tools]$ azure network nsg rule create --nsg-name GatewayNSG --name ALLOW_AZURE_LOAD_BALANCER_INBOUND --source-address-prefix AZURE_LOADBALANCER --source-port-range * --protocol "*" --destination-address-prefix * --destination-port-range * --action Allow --priority 1001 --type Inbound
info:    Executing command network nsg rule create
error:   source port parameter must be an integer between 0 and 65535. Asterisk can be used also.
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   network nsg rule create command failed

[samanoha@test tools]$ azure -v
0.9.9
[samanoha@test tools]$ node -v
v0.10.40
[samanoha@test tools]$ cat /etc/redhat-release
CentOS release 6.6 (Final)
[samanoha@test tools]$

**Comment by romangromov** [comment]
@infosatheesh2020 on Linux based environment you have to escape Asterisk symbol, like so:
* --source-port-range \* or
* --source-port-range '*' or
* --source-port-range "*"

**Comment by infosatheesh2020** [comment]
Thanks @romangromov . I'm still getting error for AZURE_LOADBALANCER source address

[samanoha@crystal scripts]$ azure network nsg rule create --nsg-name TestNSG --name test --source-address-prefix AZURE_LOADBALANCER --source-port-range '*' --protocol '*' --destination-address-prefix '*' --destination-port-range '*' --action Allow --priority 1005 --type Inbound
info:    Executing command network nsg rule create
error:   IPv4 source address prefix must be in CIDR format. Asterisk can be used also.
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   network nsg rule create command failed

[samanoha@crystal scripts]$ cat /home/samanoha/.azure/azure.err
Tue Oct 06 2015 22:40:56 GMT+0300 (EEST):
{ [Error: IPv4 source address prefix must be in CIDR format. Asterisk can be used also.]
  stack: [Getter/Setter],
  __frame: 
   { name: '__21',
     line: 335,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/asm/network/network._js',
     prev: undefined,
     calls: 3,
     active: false,
     offset: 6,
     col: 10 },
  rawStack: [Getter] }
Error: IPv4 source address prefix must be in CIDR format. Asterisk can be used also.
  <<< async stack >>>
    at Nsg.__.extend._validateAddressPrefix (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:607:13)
    at Nsg.__.extend._parseSecurityRule (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:682:46)
    at createRule__6 (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:305:26)
  at __21 (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/network._js:341:11)
  <<< raw stack >>>
    at Nsg.__.extend._validateAddressPrefix (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:607:13)
    at Nsg.__.extend._parseSecurityRule (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:682:46)
    at __$createRule__6 (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:305:26)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Nsg.createRule__6 [as createRule] (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:303:12)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/network._js:368:22)
    at ___ (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at /usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:99:14
    at Object.__g.trampoline.flush (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:24:29)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:58:61)
_______________________________________________________________________




[samanoha@crystal tmp]$ azure network nsg rule create --nsg-name TestNSG --name test --source-address-prefix 'AZURE_LOADBALANCER' --source-port-range '*' --protocol '*' --destination-address-prefix '*' --destination-port-range '*' --action Allow --priority 1005 --type Inbound
info:    Executing command network nsg rule create
error:   IPv4 source address prefix must be in CIDR format. Asterisk can be used also.
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   network nsg rule create command failed

[samanoha@crystal tmp]$ 
[samanoha@crystal tmp]$ 
[samanoha@crystal tmp]$ cat /home/samanoha/.azure/azure.err
Tue Oct 06 2015 22:59:57 GMT+0300 (EEST):
{ [Error: IPv4 source address prefix must be in CIDR format. Asterisk can be used also.]
  stack: [Getter/Setter],
  __frame: 
   { name: '__21',
     line: 335,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/asm/network/network._js',
     prev: undefined,
     calls: 3,
     active: false,
     offset: 6,
     col: 10 },
  rawStack: [Getter] }
Error: IPv4 source address prefix must be in CIDR format. Asterisk can be used also.
  <<< async stack >>>
    at Nsg.__.extend._validateAddressPrefix (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:607:13)
    at Nsg.__.extend._parseSecurityRule (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:682:46)
    at createRule__6 (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:305:26)
  at __21 (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/network._js:341:11)
  <<< raw stack >>>
    at Nsg.__.extend._validateAddressPrefix (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:607:13)
    at Nsg.__.extend._parseSecurityRule (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:682:46)
    at __$createRule__6 (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:305:26)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Nsg.createRule__6 [as createRule] (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/nsg._js:303:12)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/asm/network/network._js:368:22)
    at ___ (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at /usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:99:14
    at Object.__g.trampoline.flush (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:24:29)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:58:61)

**Comment by romangromov** [comment]
@infosatheesh2020 you have to wait for `v.0.9.10` xplat-cli release. `AZURE_LOADBALANCER` reported above is not fixed in `0.9.9`, but fixed in `v.0.9.10`

@amarzavery Hi Amar, when we can expect `v.0.9.10` release will be pushed to npm public?

**Comment by infosatheesh2020** [comment]
@romangromov Thank you very much for the information, much appreciated!

**Comment by infosatheesh2020** [comment]
@romangromov I try to use 0.9.10 branch, it complains me that underscore module is missing, but I already have it from npm.

[samanoha@crystal azure-xplat-cli]$ git branch
  dev
* release-0.9.10
[samanoha@crystal azure-xplat-cli]$ node bin/azure -v

module.js:340
    throw err;
          ^
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/samanoha/versioncontrol/azure-xplat-cli/lib/autocomplete.js:17:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
[samanoha@crystal azure-xplat-cli]$ underscore -V
0.2.18
Do you have any suggestion for me?

**Comment by romangromov** [comment]
@infosatheesh2020 try to run `npm install` at first. 
Yes, `VIRTUAL_NETWORK` fshould work fine as well as `AZURE_LOADBALANCER`

**Comment by infosatheesh2020** [comment]
Thanks @romangromov

**Comment by romangromov** [comment]
@infosatheesh2020 please let me know if it working fine for you or not

**Comment by infosatheesh2020** [comment]
@romangromov, it didn't worked for me

[samanoha@crystal azure-xplat-cli]$ node -v
v0.10.36


[samanoha@crystal azure-xplat-cli]$ sudo npm install underscore-cli
npm WARN package.json node@0.0.0 No repository field.
npm http GET https://registry.npmjs.org/underscore-cli
npm http 304 https://registry.npmjs.org/underscore-cli
npm http GET https://registry.npmjs.org/JSONSelect
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/msgpack
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/commander/1.0.5
npm http GET https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/msgpack
npm http 304 https://registry.npmjs.org/commander/1.0.5
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/JSONSelect
npm WARN engine msgpack@1.0.2: wanted: {"node":">=0.12.7"} (current: {"node":"v0.10.36","npm":"1.3.6"})
npm http GET https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/keypress

> msgpack@1.0.2 install /home/samanoha/versioncontrol/azure-xplat-cli/node_modules/underscore-cli/node_modules/msgpack
> node-gyp rebuild

make: Entering directory '/home/samanoha/versioncontrol/azure-xplat-cli/node_modules/underscore-cli/node_modules/msgpack/build'
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
  AR(target) Release/obj.target/deps/msgpack/msgpack.a
  COPY Release/msgpack.a
  CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
In file included from ../src/msgpack.cc:9:0:
../../../../nan/nan.h:316:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
../src/msgpack.cc: In function ‘void v8_to_msgpack(v8::Handle<v8::Value>, msgpack_object*, msgpack_zone*, size_t)’:
../src/msgpack.cc:126:93: error: could not convert ‘v8obj’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(v8obj, Nan::Encoding::UTF8));
                                                                                             ^
../src/msgpack.cc:129:94: error: could not convert ‘v8obj’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         Nan::DecodeWrite((char*)mo->via.str.ptr, mo->via.str.size, v8obj, Nan::Encoding::UTF8);
                                                                                              ^
../src/msgpack.cc:136:94: error: could not convert ‘result’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(result, Nan::Encoding::UTF8));
                                                                                              ^
../src/msgpack.cc:139:95: error: could not convert ‘result’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         Nan::DecodeWrite((char*)mo->via.str.ptr, mo->via.str.size, result, Nan::Encoding::UTF8);
                                                                                               ^
msgpackBinding.target.mk:102: recipe for target 'Release/obj.target/msgpackBinding/src/msgpack.o' failed
make: *** [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
make: Leaving directory '/home/samanoha/versioncontrol/azure-xplat-cli/node_modules/underscore-cli/node_modules/msgpack/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.1.6-201.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/samanoha/versioncontrol/azure-xplat-cli/node_modules/underscore-cli/node_modules/msgpack
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm WARN optional dep failed, continuing msgpack@1.0.2
underscore-cli@0.2.18 node_modules/underscore-cli
├── underscore@1.8.3
├── coffee-script@1.10.0
├── underscore.string@3.2.2
├── commander@1.0.5 (keypress@0.1.0)
└── JSONSelect@0.4.0


I tried the same with latest node as well, but not able to get through

[samanoha@crystal azure-xplat-cli]$ node -v
v0.12.7
[samanoha@crystal azure-xplat-cli]$ sudo npm install underscore-cli
npm WARN package.json node@0.0.0 No repository field.
npm http GET https://registry.npmjs.org/underscore-cli
npm http 304 https://registry.npmjs.org/underscore-cli
npm http GET https://registry.npmjs.org/commander/1.0.5
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/JSONSelect
npm http GET https://registry.npmjs.org/msgpack
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/msgpack
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/commander/1.0.5
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/JSONSelect
npm http GET https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/keypress

> msgpack@1.0.2 install /home/samanoha/versioncontrol/azure-xplat-cli/node_modules/underscore-cli/node_modules/msgpack
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/samanoha/versioncontrol/azure-xplat-cli/node_modules/underscore-cli/node_modules/msgpack/build'
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
  AR(target) Release/obj.target/deps/msgpack/msgpack.a
  COPY Release/msgpack.a
  CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
In file included from ../src/msgpack.cc:9:0:
../../../../nan/nan.h:316:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
../src/msgpack.cc: In function ‘void v8_to_msgpack(v8::Handle<v8::Value>, msgpack_object*, msgpack_zone*, size_t)’:
../src/msgpack.cc:126:93: error: could not convert ‘v8obj’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(v8obj, Nan::Encoding::UTF8));
                                                                                             ^
../src/msgpack.cc:129:94: error: could not convert ‘v8obj’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         Nan::DecodeWrite((char*)mo->via.str.ptr, mo->via.str.size, v8obj, Nan::Encoding::UTF8);
                                                                                              ^
../src/msgpack.cc:136:94: error: could not convert ‘result’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(result, Nan::Encoding::UTF8));
                                                                                              ^
../src/msgpack.cc:139:95: error: could not convert ‘result’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         Nan::DecodeWrite((char*)mo->via.str.ptr, mo->via.str.size, result, Nan::Encoding::UTF8);
                                                                                               ^
msgpackBinding.target.mk:103: recipe for target 'Release/obj.target/msgpackBinding/src/msgpack.o' failed
make: *** [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
make: Leaving directory '/home/samanoha/versioncontrol/azure-xplat-cli/node_modules/underscore-cli/node_modules/msgpack/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.6-201.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/samanoha/versioncontrol/azure-xplat-cli/node_modules/underscore-cli/node_modules/msgpack
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm WARN optional dep failed, continuing msgpack@1.0.2
underscore-cli@0.2.18 node_modules/underscore-cli
├── underscore@1.8.3
├── coffee-script@1.10.0
├── underscore.string@3.2.2
├── JSONSelect@0.4.0
└── commander@1.0.5 (keypress@0.1.0)

**Comment by romangromov** [comment]
@infosatheesh2020 
1) clone the project: `git clone https://github.com/Azure/azure-xplat-cli.git`
2) checkout release-0.9.10 branch: `git checkout release-0.9.10`
3) install project dependencies: `npm install` (not `npm install underscore-cli`)
4) try to reproduce actual issues related to this topic.

If you are not able to set-up project for some reason following steps above - please start another issue for it.

**Comment by infosatheesh2020** [comment]
@romangromov Thank you very much, i'm able to setup the project and everything (VIRTUAL_NETWORK, AZURE_LOADBALANCER and * ) works like a charm. Good that I don't need to wait for npm official release, and thanks again for helping me this much!

**Comment by romangromov** [comment]
@infosatheesh2020 glad to help you!

**Comment by infosatheesh2020** [comment]
@romangromov One comment here.. Destination port range is not working.. 
Ex: --destination-port-range "22-24"
The same works in powershell. Can you have a look

**Comment by romangromov** [comment]
@infosatheesh2020 bug, will fix, started separate issue for this https://github.com/Azure/azure-xplat-cli/issues/2177
