### ISSUE TITLE
support for managing CDNs

### ISSUE THREAD

**Issue by requiredfield** [Azure/azure-xplat-cli#2004]
Azure announced custom origin support for CDNs a couple months ago:
https://azure.microsoft.com/blog/2015/06/04/announcing-custom-origin-support-for-azure-cdn/

It appears there's still no way to manage this through the azure command line tool, is that right? If so, are you planning to add this or would you consider it?

Thanks in advance.

**Comment by caleteeter** [comment]
+1 on this, is the option to create profiles, endpoints, etc for CDNs in the near term roadmap fro the CLI?

**Comment by amarzavery** [comment]
@requiredfield , @caleteeter -CDN is now supported in V2 version of Azure(ARM)

azure config mode arm

azure cdn -h
