### ISSUE TITLE
Failed to install CLI on ubuntu 14.04.2 on Mooncake (China Azure)

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2016]
I tried to install CLI on China Azure with the following cmd.

sudo apt-get install nodejs-legacy
sudo apt-get install npm
sudo npm install -g azure-cli

I got:
npm ERR! fetch failed https://registry.npmjs.org/azure-asm-website/-/azure-asm-website-0.10.1.tgz
npm http 200 https://registry.npmjs.org/azure-asm-subscription/-/azure-asm-subscription-0.10.1.tgz
npm http 200 https://registry.npmjs.org/azure-storage-legacy/-/azure-storage-legacy-0.9.13.tgz
npm http 200 https://registry.npmjs.org/azure-asm-sql/-/azure-asm-sql-0.10.1.tgz
npm http 200 https://registry.npmjs.org/azure-asm-storage/-/azure-asm-storage-0.10.1.tgz
npm ERR! Error: shasum check failed for /home/azureuser/tmp/npm-11147-Nlsnnjhd/1439358426947-0.5591313887853175/tmp.tgz
npm ERR! Expected: 048abbe0b056048365916f2f626902728ef9e6a6
npm ERR! Actual:   04e2e175a9a56056772b053871405284f924c4cd
npm ERR!     at /usr/lib/nodejs/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/lib/nodejs/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-43-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "azure-cli"
npm ERR! cwd /home/azureuser
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10

**Comment by markcowl** [comment]
@bingosummer Thanks for the report, we will take a look

**Comment by yugangw-msft** [comment]
This is not related with azure-cli because the error surfaces on downloading the package. 
I would suggest either retry, or upgrade the npm version. The version being used is 1.3.10 which is rather old.
Anyway, this is the bug which should be reported to npm.

**Comment by yugangw-msft** [comment]
closing. feel free to reactivate with more information
