### ISSUE TITLE
ARM: list /locations ; not /providers in "azure location list"

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2021]
In ARM mode, `azure location list` currently prints locations for each RP in **human-readable form**:

```
$ azure location list --json
[
  {
    "name": "Microsoft.AppService/apiapps",
    "location": "East US,West US,South Central US,North Europe,East Asia,Japan East,West Europe,Southeast Asia,Japan West,North Central US,Central US,Brazil South,East US 2,Australia Southeast,Australia East"
  },
...
```

However I don't care about RPs at all. I just want to see the locations. There is an endpoint like:

    https://management.azure.com/subscriptions/<subs>/locations

that is used in the portal that gives me system-names for the locations (which is something I need) in the following format. In my current scenario I don't care about RPs, I just need to get the list of the location `"name"`s (such as `eastasia`, `westus`) using the CLI and I can't see if this is possible.

Maybe `azure location list` should use this `subscriptions/<id>/locations` endpoint instead of  `subscriptions/<id>/providers` and we can move this to `azure providers list` if needed?

cc: @yugangw-msft @devigned 

```
{
    "value": [
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/eastasia",
            "name": "eastasia",
            "displayName": "East Asia",
            "longitude": "114.188",
            "latitude": "22.267"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/southeastasia",
            "name": "southeastasia",
            "displayName": "Southeast Asia",
            "longitude": "103.833",
            "latitude": "1.283"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/centralus",
            "name": "centralus",
            "displayName": "Central US",
            "longitude": "-93.6208",
            "latitude": "41.5908"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/eastus",
            "name": "eastus",
            "displayName": "East US",
            "longitude": "-79.8164",
            "latitude": "37.3719"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/eastus2",
            "name": "eastus2",
            "displayName": "East US 2",
            "longitude": "-78.3889",
            "latitude": "36.6681"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/westus",
            "name": "westus",
            "displayName": "West US",
            "longitude": "-122.417",
            "latitude": "37.783"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/northcentralus",
            "name": "northcentralus",
            "displayName": "North Central US",
            "longitude": "-87.6278",
            "latitude": "41.8819"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/southcentralus",
            "name": "southcentralus",
            "displayName": "South Central US",
            "longitude": "-98.5",
            "latitude": "29.4167"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/northeurope",
            "name": "northeurope",
            "displayName": "North Europe",
            "longitude": "-6.2597",
            "latitude": "53.3478"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/westeurope",
            "name": "westeurope",
            "displayName": "West Europe",
            "longitude": "4.9",
            "latitude": "52.3667"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/japanwest",
            "name": "japanwest",
            "displayName": "Japan West",
            "longitude": "135.5022",
            "latitude": "34.6939"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/japaneast",
            "name": "japaneast",
            "displayName": "Japan East",
            "longitude": "139.77",
            "latitude": "35.68"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/brazilsouth",
            "name": "brazilsouth",
            "displayName": "Brazil South",
            "longitude": "-46.633",
            "latitude": "-23.55"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/australiaeast",
            "name": "australiaeast",
            "displayName": "Australia East",
            "longitude": "151.2094",
            "latitude": "-33.86"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/australiasoutheast",
            "name": "australiasoutheast",
            "displayName": "Australia Southeast",
            "longitude": "144.9631",
            "latitude": "-37.8136"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/southindia",
            "name": "southindia",
            "displayName": "South India",
            "longitude": "80.1636",
            "latitude": "12.9822"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/centralindia",
            "name": "centralindia",
            "displayName": "Central India",
            "longitude": "73.9197",
            "latitude": "18.5822"
        },
        {
            "id": "/subscriptions/c3dfd792-49a4-4b06-80fc-6fc6d06c4742/locations/westindia",
            "name": "westindia",
            "displayName": "West India",
            "longitude": "72.868",
            "latitude": "19.088"
        }
    ]
}
```

**Comment by yugangw-msft** [comment]
Yes, we should take this suggestion.

**Comment by ahmetalpbalkan** [comment]
5 months and still not fixed :)

**Comment by pcgeek86** [comment]
@ahmetalpbalkan I had a **massive** discussion around this same thing in the Azure PowerShell module.

@devigned Can we get this fixed in both Azure xPlat and Azure Resource Manager (ARM) PowerShell?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan, this specific ask belongs to the cmdlet area of azure resource manager team, we (onesdk team) usually let them schedule the work. But this has been there for 4 months, from multiple people, with good values, so i went ahead and made the change this time. This will get out in next week's release

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft thanks a bunch for being proactive.

**Comment by yugangw-msft** [comment]
Fix is in dev branch

**Comment by ahmetalpbalkan** [comment]
Looks good, thanks.

![image](https://cloud.githubusercontent.com/assets/159209/11524996/978a6e52-9884-11e5-9aa0-fbb00c029975.png)

**Comment by fulky** [comment]
What's the Rest API call equivalent to get the location list?

**Comment by devigned** [comment]
@fulky I believe this is the API https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/subscriptions/2016-06-01/swagger/subscriptions.json#L37

**Comment by amarzavery** [comment]
@fulky - execute the command with -vv option and it will show you the underlying REST call.

**Comment by fulky** [comment]
@amarzavery  and @devigned .  Thank you for your reply.   The call that works (in Powershell and other places) is something like this https://management.azure.com/subscriptions/{your subscriptionId}/locations?api-version=2016-09-01

**Comment by ncacace** [comment]
Can someone please just feed me a line of code because I'm getting nowhere with their help without examples

<img width="747" alt="screen shot 2018-07-19 at 12 09 51 am" src="https://user-images.githubusercontent.com/1590147/42910568-53a28216-8ae8-11e8-8419-46fb24a1ba20.png">

**Comment by amarzavery** [comment]
@ncacace - This is the wrong repo. Please file an issue over here https://github.com/Azure/azure-cli
/cc @yugangw-msft

**Comment by diggoran** [comment]
I have no idea what I’m talking about when it comes to this app in particular, but the usage seems to be telling you to use the “--sku” flag before adding the “F1” string. So:

az appservice list-locations --sku F1

Thanks,
Tracy

**Comment by ncacace** [comment]
Having just that simple line of code now makes it so easy to understand how the other options work.
How hard could it be for Microsoft to Add 1 line of example code like that so as to close the loop of communication...??

Thanks

**Comment by diggoran** [comment]
This is standard command line flag annotation. Things in square brackets are optional. Things not in square brackets are not optional. `--sku` is not in square brackets, and the error message says you're missing `--sku`. If I'll give you anything, it's that the text wrapping might be a little unfortunately placed. But next time, just be aware of what the bracket notation is trying to tell you.

**Comment by CastielWong** [comment]
For anyone who is using Azure CLI, `az account list-locations -o table` should the one
