### ISSUE TITLE
Installation failed in ubuntu 15.04 by default. Requires node version >=0.11.10.

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-xplat-cli#2023]
root@rhui-ubt-cli:~/node-v0.12.7# npm install -g azure-cli
npm WARN engine galaxy@0.1.12: wanted: {"node":">=0.11.10"} (current: {"node":"0.10.25","npm":"1.4.21"})
/
> fibers@1.0.6 install /usr/local/lib/node_modules/azure-cli/node_modules/streamline/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-v8-3.28` exists; testing
Binary is fine; exiting
/usr/local/bin/azure -> /usr/local/lib/node_modules/azure-cli/bin/azure
azure-cli@0.9.7 /usr/local/lib/node_modules/azure-cli

**Comment by devigned** [comment]
Did you install using the ubuntu instructions here: https://github.com/Azure/azure-xplat-cli#install-on-ubuntu?

**Comment by andyzhangx** [comment]
I have tried 
sudo apt-get install nodejs-legacy
sudo apt-get install npm
sudo npm install -g azure-cli

or 
sudo apt-get install node
sudo apt-get install npm
sudo npm install -g azure-cli

In ubuntu 15.04, it still not works. I need to install higher node version manually, the instruction should include how do we install azure-cli and necessary node packages in ubuntu 15.04.

**Comment by yugangw-msft** [comment]
@andyzhangx, i will take a look

**Comment by yugangw-msft** [comment]
@andyzhangx It works for me, what error did you get?

![image](https://cloud.githubusercontent.com/assets/6014209/9291933/7d67468c-4391-11e5-9321-b8a9a2cd16f9.png)

**Comment by yugangw-msft** [comment]
@andyzhangx, also the output you mentioned early on only contains a warning, and the last line appeared the azure-cli was installed. Have you tried to run the "azure" and see it works or not.
The warning itself is known, and it has been there for long while, as far as i can remember. We can clarify that separately.

**Comment by andyzhangx** [comment]
the following installation method seems to be working now:
 sudo apt-get install nodejs-legacy
 sudo apt-get install npm
 sudo npm install -g azure-cli
