### ISSUE TITLE
[P2]azure vm list error (there are about 130 VMs totally, this bug does not always repro)

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-xplat-cli#2024]
root@rhui-ubt-cli2:~# azure account set 4be8920b-2978-43d7-ab14-04d8549c1d05
	info:    Executing command account set
	info:    Setting subscription to "OSTC Shanghai Test" with id "4be8920b-2978-43d7-ab14-04d8549c1d05".
	info:    Changes saved
	info:    account set command OK
	root@rhui-ubt-cli2:~# azure vm list
	info:    Executing command vm list
	+ Getting virtual machines
	error:   Parameter 'url' must be a string, not undefined
	info:    Error information has been recorded to /root/.azure/azure.err

**Comment by andyzhangx** [comment]
azure.err:

Tue Aug 11 2015 06:29:30 GMT+0000 (UTC):
[TypeError: Parameter 'url' must be a string, not undefined]
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at Object.urlParse [as parse] (url.js:101:5)
    at createVMView (/usr/local/lib/node_modules/azure-cli/lib/commands/asm/vm/vmclient.js:3104:18)
    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/vm/vmclient.js:218:28
    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/vm/vmclient.js:2279:16
    at /usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:113:25
    at /usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:24:16
    at /usr/local/lib/node_modules/azure-cli/lib/commands/asm/vm/vmclient.js:2275:11
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-asm-compute/lib/computeManagementClient.js:7599:14
    at /usr/local/lib/node_modules/azure-cli/lib/util/utils.js:348:7

**Comment by amarzavery** [comment]
unable to repro. Please feel free to reopen if required.
