### ISSUE TITLE
how to upload recursive subdirectories with files to azure

### ISSUE THREAD

**Issue by brendonco** [Azure/azure-xplat-cli#2025]
I have a for loop to upload one by one but subdirectories are not uploaded into Azure.  If it encounter a folder from my local, the upload will failed ```error:   storage blob upload command failed``` image is not a file.

How do I upload recursively using ```azure storage blob upload```?

```
		filter="$directory*"
		for file in $filter; do
		    echo $file $(basename $file) 
		    azure storage blob upload -q $file $container_name $(basename $file)
		done
```

**Comment by yaxia** [comment]
You might want to try:
```
find <local_folder> -type f | parallel -P 4 -u azure storage blob upload --container <container_name> -q
```

**Comment by yaxia** [comment]
@yugangw-msft Please help close it. @brendonco Please feel free to reopen it if it doesn't help.
