### ISSUE TITLE
The "azure storage account create" command doesn't accecpt "-n"

### ISSUE THREAD

**Issue by greenmang0** [Azure/azure-xplat-cli#2029]
```
[~] $ azure storage account create -h
help:    Create a storage account
help:
help:    Usage: storage account create [options] <name>
help:
help:    Options:
help:      -h, --help                            output usage information
help:      -v, --verbose                         use verbose output
help:      --json                                use json output
help:      -l, --location <name>                 the location
help:      --type <type>                         the account type(LRS/ZRS/GRS/RAGRS/PLRS)
help:      -g, --resource-group <resourceGroup>  the resource group name
help:      -s, --subscription <id>               the subscription id

[~] $ azure storage account create -l westus --type PLRS -g foo-rg01 -n foo-plrs01

  error: unknown option `-n'
```

**Comment by yugangw-msft** [comment]
@yaxia , this might have been fixed in the dev branch, but double check. Also the "-l, --location" argument is little confusing by using the "name"

**Comment by yaxia** [comment]
@greenmang0 The account name is marked as <name> which means a mandatory parameter without an option name. Besides, storage account names must be between 3 and 24 characters in length and may contain numbers and lower-case letters only. Would you please try:
```
[~] $ azure storage account create fooplrs01 -l westus --type PLRS -g foo-rg01
```

For the "-l, --location" issue, I will fix it in a later release.

**Comment by greenmang0** [comment]
@yaxia , what do you mean by `The account name is marked as which means a mandatory parameter without an option name.` ?

I understand that `storage account name` doesn't accept `-` as mentioned earlier, (edited above in issue def) but every other `azure` command accepts  `-n` for the `resource name`, so was expecting the same from this command as well. This is just for the consistency purpose. Your command works as expected.

**Comment by yaxia** [comment]
@greenmang0 Sorry, the text \<name\> was hidden because of the Markdown syntax. I've modified the reply.

For the consistency, we may fix it in a later release. Thanks for your suggestion.

**Comment by Arcisnetdev** [comment]
I have a same problem, this is a report. How can I create a resource group name?.
Help me, please.

AdminUser@script-vm:~$    azure storage account create -l centralus homlab --sku-name GRS

info:    Executing command storage account create
+ Checking availability of the storage account name
help:    Kind:
  1) Storage
  2) BlobStorage
:   1
Resource group name:  homelabd
+ Creating storage account
error:   Resource group 'homelabd' could not be found.
error:   Error information has been recorded to /home/AdminUser/.azure/azure.err
error:   storage account create command failed
