### ISSUE TITLE
Replace (first) hyphen with space for 'dns-zone' and 'dns-record-set'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-xplat-cli#2030]
Currently, for the Azure DNS service we have commands that look like:
```
> azure network dns-zone <whatever>
> azure network dns-record-set <whatever>
```
'Network' is a category. 'DNS' is the service name.  'Zones' and 'record sets' are resource types.  It would therefore be much more intuitive and more consistent with other services within 'azure network' if these commands are re-formatted to turn the first hyphen into a space:
```
> azure network dns zone <whatever>
> azure network dns record-set <whatever>
```

**Comment by jtuliani** [comment]
We will of course have to add help content for 'azure network dns -h'.  That's easy enough though.

**Comment by romangromov** [comment]
Thank you @jtuliani, looks nice for better user experience, will change
