### ISSUE TITLE
Support for creating and managing Event Hubs

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-xplat-cli#2034]
With Azure Powershell, we can manage Event Hubs by adding the Service Bus dll and using the management libraries from there.

We already have service bus namespace support, but can support for creating and managing event hubs be added to the xplat cli?

**Comment by devigned** [comment]
@djrosanova ideas?

**Comment by damienpontifex** [comment]
I believe I can do this using the ARM resources now so closing.
