### ISSUE TITLE
Failed to login with an co-administrator account

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2036]
I created a Microsoft account (outlook.com) and set it as a co-administrator in Azure Portal.
But when I login CLI, it failed with the following error.
+ Authenticating...
error:   Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE
info:    Error information has been recorded to /home/azureuser/.azure/azure.err
error:   login command failed

What should I do to fix it? Thanks

**Comment by bingosummer** [comment]
And I can login using Powershell with the same account.

**Comment by devigned** [comment]
You can only login to Azure CLI with service principals or Azure Active Directory organizational accounts (only in non-multi-factor auth domains). See #1986

**Comment by bingosummer** [comment]
As a service administrator, I created an Azure Active Directory, and added a user with an existing Microsoft account. And it did not work for Azure CLI login.
So, what I should do is to create a new user in my organization, right? Just like XXX@XXX.onmicrosoft.com?
But I can't add XXX@XXX.onmicrosoft.com as a co-administrator because "The co-administrator must be a Microsoft account, or a user in the Microsoft (microsoft.onmicrosoft.com) directory.".
If XXX@XXX.onmicrosoft.com is not a co-administrator account, then can I login CLI with it and create service principal?

**Comment by yugangw-msft** [comment]
Please refer to  #1948 with details for you to configure a user and be able to use cli

**Comment by bingosummer** [comment]
@yugangw-msft Thanks. I have followed the steps in #1948, but the new user (XXX@XXX.onmicrosoft.com ) I created is not in the Microsoft (microsoft.onmicrosoft.com) directory, ant it is also not a Microsoft account. So what should I do to set XXX@XXX.onmicrosoft.com as a co-administrator? Should I link it to a subscription? How?
Thanks again.

**Comment by yugangw-msft** [comment]
@bingosummer 
The walk-through doesn't require be in the microsoft's org. Did you try the step 4 and did it work for you or not? I have tried using my personal subscription, and it worked.
  "From the Azure portal, select Settings and then select Administrators. Select Add, and add the new user as a co-administrator. This allows the work or school account to manage your Azure subscription."
