### ISSUE TITLE
Getting "The server failed to authenticate the request" after login as service principal in ASM

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2040]
Hi there,

I've configured a web Application inside my Active Directory via Management Portal and now able to login with `azure login --service-principal` command. Also, I've granted rights for this application to  `Access Azure Service Management (preview)`. CLI works fine in `ARM` mode, but when I try to perform any kind of command in `ASM` mode I'm always getting this error:

```
azure network vnet list
info:    Executing command network vnet list
+ Looking up the virtual network sites
error:   The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.
info:    Error information has been recorded to C:\Users\roman.gromov\.azure\azure.err
error:   network vnet list command failed
```

Also I was able to upload certificate for my application using this [tutorial](http://www.dushyantgill.com/blog/2015/05/23/developers-guide-to-auth-with-azure-resource-manager-api/) and associate the same certificate with my subscription via Management Portal - no luck. Also tried to `azure logout` and `azure account clear` then `azure login` - still the same error.

What I missed here? Please let me know if you need one more info about this issue.
Thank you in advance!

**Comment by yugangw-msft** [comment]
Service principal's permission granted through RBAC only works  on ARM. It doesn't work on ASM, which requires co-admin.

**Comment by markcowl** [comment]
@romangromov So, the best thing to do would be to use separate credentials for each mode - you can use ```azure account download``` and  ```azure account import`` to download a cert for use with asm mode, and you can use service principal authentication using appid and secret in arm mode.

**Comment by romangromov** [comment]
@markcowl thank you so much, works fine now!

**Comment by bearrito** [comment]
I'm not following the solution. Are these steps spelled out somewhere in the official docs?

**Comment by amarzavery** [comment]
service principal login is by default applicable only for ARM (Azure Resource Manager) Version 2 of the Azure API.

You can grant it access by going to the old portal www.manage.windowsazure.com.
Click on the Active Directory Icon on the left pane. Click on the tenant and then on the application created in that tenant. Click on Configure and Add permissions to other applications.

Provide permissions to Windows Azure Service Management API (Windows Azure Service ...)

1. ![image](https://cloud.githubusercontent.com/assets/4521223/21373676/9580fe7a-c6d5-11e6-9fc1-e38ae5d07386.png)


2. ![image](https://cloud.githubusercontent.com/assets/4521223/21373683/a5c565d2-c6d5-11e6-8988-27f045bb48b6.png)

3. ![image](https://cloud.githubusercontent.com/assets/4521223/21373703/c917057c-c6d5-11e6-9bfd-5c4ce665f06c.png)



Then Save the application. This should provide access to the service principal for ASM (Azure Service Manager) (Version 1 of the Azure API).

Hope that resolves this issue.

**Comment by andrerav** [comment]
Hi! I am facing a very similar issue. I am trying to modify a service bus using ASM and a service principal from a console application. The steps outlined by @amarzavery above have been followed to grant access to the ASM API to the application. I am confused by the comment made by @yugangw-msft above; does the service principal also need to be a co-admin for this to work? Thanks!
