### ISSUE TITLE
ASM: `azure vm location list` shows only a little information

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2050]
The API response actually returns a lot of valuable info (such as which VM sizes or storage types available) to the client, but the client doesn't show any of it... I was trying to look up which VM sizes are available where (I don't know where else to go) and I'm guessing not many users are aware of `--json` parameter and they will be missing out here...

![image](https://cloud.githubusercontent.com/assets/159209/9403032/08089066-4798-11e5-8d6d-d8976f45d379.png)

Adding `--json`:

![image](https://cloud.githubusercontent.com/assets/159209/9403039/19451fc0-4798-11e5-8cdc-b1c67105db96.png)

**Comment by ahmetalpbalkan** [comment]
Any comments?

**Comment by ahmetalpbalkan** [comment]
Updates? I feel like this is somewhat important and simple to fix.

**Comment by ramayer** [comment]
Agreed it doesn't look hard to fix technologically - but the process of signing things like "contributor license agreements", etc makes it kinda a pain ( http://windowsazure.github.io/guidelines.html ).

Maybe I should just post a patch in the comment here?

**Comment by ahmetalpbalkan** [comment]
@ramayer our CLAs are actually not that hard and it takes less than a minute to fill the form out. If you have a fix, please send out. :)

**Comment by ramayer** [comment]
@ahmetalpbalkan : "our CLAs are actually not that hard and it takes less than a minute"

Quoting your CLA page:  " Please carefully review the document; you may also need to have your employer sign the document. "

that'll take well over a minute to get my employer to sign such an agreement.

**Comment by ahmetalpbalkan** [comment]
@ramayer understood. Makes sense to defer this to the product team to fix. @devigned is this planned? I think this is rather an important functionality and currently calls to the wrong endpoint and returns wrong info.

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan, we have couple of active issues about "location", for this one, my understanding is specific to the VM location command. Based on that, the fix should be made by the service team.

**Comment by yugangw-msft** [comment]
@huangpf , please comment. I have checked in the change for general "location list", this  one is specific to your VM cmdlet.

**Comment by huangpf** [comment]
@sauryadas

**Comment by sauryadas** [comment]
Thanks for the feedback! We will take a look at this sometime in the future. Please run the same command 
>azure location list
in ARM mode and you will see useful information.
