### ISSUE TITLE
ASM: 'azure site set' : cannot select Java version

### ISSUE THREAD

**Issue by mraber** [Azure/azure-xplat-cli#2062]
It's not possible to enable Java with Tomcat or Jetty for a webapp (website).

CLI version : 0.9.7

**Comment by ChrisCompy** [comment]
The site settings javaVersion, javaContainer and  javaContainerVersion should work in CLI – they are settings on the updateWebsiteConfig rest api.

**Comment by mraber** [comment]
I'm not sure to understand your answer. The command `azure site set` does not provide any option to set the Java version.
The only available options are : `--net-version` and `--php-version`

**Comment by ChrisCompy** [comment]
Sorry, I was thinking about powershell where it should work fine.  To answer your question, we do not have support for setting Java via the azure cli at this time.

**Comment by amarzavery** [comment]
This will not be supported in ASM in the CLI.

**Comment by aswathyraveendran** [comment]
How to set up javaVersion, javaContainer and javaContainerVersion using powershell?
