### ISSUE TITLE
ARM: Accept only canonical location formats as inputs

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2068]
For the location parameters we should only accept the canonical form (`westus`) and be less forgiving to build up a user behavior.

Opening an issue per internal email thread. @devigned

**Comment by devigned** [comment]
Thank you, kind sir.

We should definitely warn people that are using locations formatted outside of the canonical format. That is, if a command is executed with "West US" rather than "westus" we should warn. Some services accept either, but other are less forgiving.

**Comment by ahmetalpbalkan** [comment]
@devigned I was actually reading rpcapi spec yesterday and spec explicitly says all RPs must handle "west us", "westus", "West US" in inputs but in the responses proxied through CSM, RPs are supposed to tell location of the resources as well, but the spec doesn't make it clear if they should respond with any particular format or anything is fine... Looks like an irreversible mistake but anyways, as we talked CLI might help making it canonical and after a while we may see only the canonical format coming to the APIs if our SDKs/xplat-cli/PowerShell is all enforcing canonical format..

**Comment by nmackenzie** [comment]
I would argue that it is not at all well known that there is a canonical format. For example, the output of azure vm location list is the full name of the region NOT the canonical format.

**Comment by ahmetalpbalkan** [comment]
@nmackenzie it has its own problems :-) currently it actually lists the wrong info https://github.com/Azure/azure-xplat-cli/issues/2050

Going forward that should be fixed and we can change  "location list" to show the canonical name primarily. I don't think that'd be a showstopper, this is just a first step.

**Comment by ahmetalpbalkan** [comment]
Any updates?

**Comment by ahmetalpbalkan** [comment]
Due to the bad nature of ARM API design accepting location name in multiple forms, this is not possible.
