### ISSUE TITLE
Passing in JSON as inline parameter does not seem to work.

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-xplat-cli#2070]
Using the example from the documentation, using inline parameters from azure cli does not seem to work. 

     azure group deployment create -f <PathToTemplate> {"ParameterName":"ParameterValue"} -g ExampleResourceGroup -n ExampleDeployment

I tried this from PowerShell, CMD, and Bash (cygwin). The error I have given is:

    Error converting value "myValue" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.myKey', line 1, position 8404.'

**Comment by ahmetalpbalkan** [comment]
@aarsan can you please try surrounding the json with single quotes (`'`)? In shells like bash if you do:

```sh
$ echo {"ParameterName":"ParameterValue"}
{ParameterName:ParameterValue}
```

you can see the quotes are gone.

**Comment by aarsan** [comment]
@ahmetalpbalkan It turns out, the problem wasn't the way I was escaping. Instead of:

    {"ParameterName":"ParameterValue"}
it worked as:

    {"ParameterName":{"value":"ParameterValue"}}

None of the documentation I saw stated it this way.

**Comment by aarsan** [comment]
And in case anyone is wondering, the way I escaped this in PowerShell was like this:

    '{\"ParameterName\":{\"value\":\"ParameterValue\"}}'

**Comment by ahmetalpbalkan** [comment]
@aarsan please refer to Deloying Templates documentation Parameters File section here: https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-deploy/#parameter-file
