### ISSUE TITLE
azure portal --environment can be automatically inferred.

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2074]
I only have accounts from AzureChina environment and I'm signed in to them. Based on that the CLI probably can determine the `-e AzureChina` argument and user can omit this parameter in the `azure portal` command for convenience...

It makes sense to have `-e` if the user is not logged in, but if they are it's just inconvenient (and users are logged in, most of the time?).

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan Agreed, if the "env" is missing, we should load the one associated with the current account/subscription.

**Comment by ahmetalpbalkan** [comment]
Maybe someday we'll have this? 😭

**Comment by balajikris** [comment]
Fixed by #3426
