### ISSUE TITLE
resume from interrupted upload on `vm disk create`

### ISSUE THREAD

**Issue by keturn** [Azure/azure-xplat-cli#2085]
A `vm disk create` task was interrupted with ECONNRESET. It'd be great if it were able to pick up where it left off. There's no indication in the UI of whether it's doing this or not; the web view of Storage shows the entire image size allocated; the command line doesn't make any mention of a previous upload attempt for this VHD, nor does it complain that there was already something by that name.

A progress indicator as mentioned in #2084 would help clarify how much upload remains.

```
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
```

**Comment by sauryadas** [comment]
Since there no action required here i will close this issue.
