### ISSUE TITLE
Can not create a ARM template using Azure CLI

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2086]
When I create a template (101-simple-linux-vm) using Azure CLI;
azure group create -n "xxx" -l "xxx" -d "xxx" -f azuredeploy.json -e azuredeploy.parameters.json
I got:
error: The request content was invalid and could not be deserialized: 'Error converting value "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.$schema', line 1, position 4273.'.

$ azure -v
0.9.8

**Comment by bingosummer** [comment]
Same issue in azure-quickstart-templates repo.
https://github.com/Azure/azure-quickstart-templates/issues/584

Feel free to close this issue after you fix the bug.

**Comment by amarzavery** [comment]
This seems to be a quickstart template issue and not a CLI issue. Hence closing this.
