### ISSUE TITLE
"sql db list" fails on V12 sql servers

### ISSUE THREAD

**Issue by shalupov** [Azure/azure-xplat-cli#2090]
STR:
- Create SQL server via "sql server create"
- Check "sql db list" works on it
- Upgraded SQL server in Azure portal to V12
- "sql db list" fails with "HTTP Error 503. The service is unavailable"

**Comment by yooakim** [comment]
I experience this issue as well when trying to work with a V12 database. It works fine to list the server:

```
C:\Users\yooak> azure sql server show xxxx
info:    Executing command sql server show
+ Getting SQL server
data:    SQL Server name xxxx
data:    SQL Server administratorUserName xxxx
data:    SQL Server location North Europe
data:    SQL Server fullyQualifiedDomainName xxxx.database.windows.net
data:    SQL Server state Ready
data:    SQL Server version 12.0
info:    sql server show command OK
```

but when I try to use the CLI to list the databases it does not work:

```
C:\Users\yooak> azure sql db list xxxx 
info:    Executing command sql db list
Administrator password: ********
+ Getting SQL server databases
error:   <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Service Unavailable</h2>
<hr><p>HTTP Error 503. The service is unavailable.</p>
</BODY></HTML>

info:    Error information has been recorded to C:\Users\yooak\.azure\azure.err
error:   sql db list command failed
```

The error file contains the following:

```
Sun Nov 29 2015 09:53:28 GMT+0100 (W. Europe Standard Time):
{ [Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Service Unavailable</h2>
<hr><p>HTTP Error 503. The service is unavailable.</p>
</BODY></HTML>
]
  __frame: 
   { name: '__10',
     line: 401,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\asm\\sql.js',
     prev: undefined,
     calls: 3,
     active: false,
     offset: 10,
     col: 31 },
  rawStack: [Getter] }
Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Service Unavailable</h2>
<hr><p>HTTP Error 503. The service is unavailable.</p>
</BODY></HTML>

    at Function.ServiceClient._normalizeError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\lib\services\serviceclient.js:758:12)
    at SqlServerAcs.ServiceClient._processResponse (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\lib\services\serviceclient.js:456:41)
    at Request.processResponseCallback [as _callback] (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\lib\services\serviceclient.js:213:35)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\node_modules\request\request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\node_modules\request\request.js:1160:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-common\node_modules\request\request.js:1111:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

**Comment by orlandow** [comment]
I'm having this issue too, `azure sql server

**Comment by amarzavery** [comment]
@yaakoviyun, @akromm - Can you please take a look at this issue? Customers are having issues since a long time.

**Comment by euroclydon37** [comment]
Still nothing on this?

**Comment by amarzavery** [comment]
It seems this is a low priority item for the sql team. @akromm @yaakoviyun - Can you please respond and give a timeline for this issue?

**Comment by akromm** [comment]
We have this on our list of work to do.  We plan to completely rewrite all the CLI commands to make them better.  Our ETA is sometime this year :)

**Comment by euroclydon37** [comment]
Awesome. Thanks.

**Comment by smbecker** [comment]
This is a complete show stopper for me right now. I can't create a server with a different version and it seems that all of my other servers were auto-upgraded. So I can't manage them at all through the CLI. Any progress on this?

**Comment by yaakoviyun** [comment]
+ Adam

**Comment by akromm** [comment]
@jamestao @smbecker 

This is still on our todo list.  We have someone actively working on generating a swagger file for our APIs which will then be used to generate new client libraries which will be used to rewrite the functionality in the xPlat CLI.

**Comment by smbecker** [comment]
Is there any timeline for that effort? Is there any way that the community can help?

**Comment by danyandresh** [comment]
As I've seen this issue was originally posted 11 months ago, just want to let you know it is still there (I encountered it yesterday)

**Comment by akromm** [comment]
@danyandresh This is still on our todo list.

**Comment by amarzavery** [comment]
@akromm - I understand that the sql team is working on tight deadlines. However, it would be great if customers can get a rough time line on when this can be available.

**Comment by smbecker** [comment]
Now, my database servers are being forcibly upgraded to V12 by Microsoft and yet I still have no way to manage V12 servers with this command line. Any idea when this will be available?

**Comment by amarzavery** [comment]
@akromm @jaredmoo - Please provide an approximate timeline.

**Comment by francolaiuppa** [comment]
I wanted to add that you can create a new server (manually) and uncheck the "use V12 box". 

Then any `azure sql db` commands you run using this server will work. 
I know it's not a final solution as not everyone can create new servers / migrate databases, but at least it allowed me to keep going with my automation. 

Hope it helps you too!

**Comment by smbecker** [comment]
But that's also not a permanent solution because Microsoft will auto-upgrade those servers at some point. At least that is what happened to me.

**Comment by akromm** [comment]
@smbecker @francolaiuppa @nathannfan 
I would like to update that we are actively working on the Swagger spec for Azure SQL which will be used to create a new and updated xPlat CLI for SQL.

**Comment by aonu** [comment]
This still doesn't work using CLI 👎

**Comment by akromm** [comment]
Azure CLI should solve this issue and many others in the SQL space.
