### ISSUE TITLE
Usability issues: azure usage list (0.9.8; mac) sports options using brackets, but requires (yet does not prompt)

### ISSUE THREAD

**Issue by squillace** [Azure/azure-xplat-cli#2091]
Azure usage list --help indicates (with brackets, which typically signal _optional_ usage) that reportedStartTime and reportedEndTime are optional. Then if not specified, instead of prompting for the values (as do other commands like vm quick-create and group deployment create with templates) just fails you out, forcing you to retype the entire command when it could just prompt you for the TWO values it knows must exist. 

```
rasquill•~» azure usage                                                                                    [11:37:57]
help:    Command to view your aggregated Azure usage data
help:
help:    List the usage aggregates for a provided time range
help:      usage list [options] [reportedStartTime] [reportedEndTime]
help:
help:    Options:
help:      -h, --help  output usage information
help:
help:    Current Mode: arm (Azure Resource Management)
rasquill•~» azure usage list                                                                               [11:38:08]
info:    Executing command usage list

  error: missing required argument `reportedStartTime'
```

**Comment by squillace** [comment]
@devigned @kmouss

**Comment by devigned** [comment]
@Matt-Westphal thoughts?

**Comment by Matt-Westphal** [comment]
thanks for the info.  I'll take a look at this as soon as a can.

**Comment by Matt-Westphal** [comment]
I'll modify the code to prompt for start and end date if it's not supplied as a parameter

**Comment by squillace** [comment]
@Matt-Westphal Thanks.

**Comment by eduardkoller** [comment]
@Matt-Westphal - do we have an update on this - is it fixed?

**Comment by Matt-Westphal** [comment]
This has been fixed and deployed in Sept 2015
