### ISSUE TITLE
Create and manage App Service Plans

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-xplat-cli#2111]
There doesn't seem to be a way to create a new App Service Plan (aka ServerFarm) from the CLI.
In fact, there doesn't seem to be a way to create a new App Service Plan from the portal either without creating a *App.

As a result, I can't create a new webapp entirely from the CLI.

Can you add that ability?

**Comment by ahmedelnably** [comment]
Thanks Josh for reporting that, we are looking into that and will update soon

**Comment by ahmedelnably** [comment]
Hello Josh,
We have this in PowerShell, we are looking in ways to get the same support in CLI
-Ahmed

**Comment by ahmedelnably** [comment]
Hello Josh,
This is now available in CLI
http://aka.ms/webapp-cli
