### ISSUE TITLE
Comments in arm templates makes the template invalid

### ISSUE THREAD

**Issue by sjkp** [Azure/azure-xplat-cli#2112]
If an ARM template contains comments (//) with containing / the template deployment will fail. 

I have a ARM template that looks like this:
```json
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "sitename": {
            "type": "string"
        },
        "hostingPlanName": {
            "type": "string"
        },
        "siteLocation": {
            "type": "string"
        },
        "sku": {
            "type": "string",
            "defaultValue": "f1",
            "metadata": {
                "description": "The hosting plan sku"
            }
        },
        "tier": {
            "type": "string",
            "defaultValue": "Free",
            "allowedValues": [
                "Free",
                "Shared",
                "Basic",
                "Standard",
                "Premium"
            ],
            "metadata": {
                "description": "the pricing tier"
            }
        }
    },
    "resources": [
        {
            "apiVersion": "2015-08-01",
            "location": "[parameters('siteLocation')]",
            "name": "[parameters('hostingPlanName')]",
            "type": "Microsoft.Web/serverfarms",
            "properties": {
                "name": "[parameters('hostingPlanName')]",
                "numberOfWorkers": 1
            },
            "sku": {
                "name": "[parameters('sku')]",
                "tier": "[parameters('tier')]"
            }           
        },
//Comments Microsoft.Web/serverfarms --
        {
            "apiVersion": "2015-08-01",
            "location": "[parameters('siteLocation')]",
            "name": "[parameters('sitename')]",
            "type": "Microsoft.Web/sites",
            "dependsOn": [ "[concat('Microsoft.Web/serverFarms/', parameters('hostingPlanName'))]" ],
            "properties": {
                "name": "[parameters('sitename')]",
                "serverFarmId": "[parameters('hostingPlanName')]"
            }
        }
    ]
}
```
When i try to deploy it with: 
azure group create -n website -l westeurope -f website.json -e website.param.dev.json -d website

I get the following error
info:    Executing command group create
+ Getting resource group sjkpwebsite
+ Updating resource group sjkpwebsite
info:    Updated resource group sjkpwebsite
+ Initializing template configurations and parameters
error:   Unexpected token /

**Comment by romangromov** [comment]
BTW: JSON do not supports comments, please see RFC 4627 for details

**Comment by sjkp** [comment]
Fair enough if that is the reason, but then it would be cool, if the error was not just when using the Xplat-CLI. Because the template works fine when using. e.g. powershell.

**Comment by devigned** [comment]
If it does work in PowerShell, it's because JSON.Net handles comments, which I would say is less of a feature than a bug. Azure CLI will not support comments, which are outside of the RFC.

Rather, I could see a time when the templates could be in yaml format, which support comments and is much more concise.

**Comment by kamoljan** [comment]
+1

**Comment by sjkp** [comment]
Resources have a comment property now, that you can use to write comments in.

**Comment by BenyaminFamili** [comment]
// Single comments feature accepted by azure ARM

**Comment by m4masood** [comment]
From the UI (Deploy a custom template) it does not work.
![image](https://user-images.githubusercontent.com/7548298/60940955-b3109480-a320-11e9-92cf-72b7a161191c.png)

**Comment by RehanSaeed** [comment]
Comments are allowed in JSON for configuration files. Please implement this feature, it makes no sense to stick to a rigid spec when it's a feature all users of ARM templates want.

> "Suppose you are using JSON to keep configuration files, which you would like to annotate. Go ahead and insert all the comments you like. Then pipe it through JSMin before handing it to your JSON parser."
> Douglas Crockford, 2012

Please re-open this. The lack of this feature is forcing me to use PowerShell instead.

**Comment by amarzavery** [comment]
@RehanSaeed - This CLI is deprecated. Please use the new V2 CLI https://github.com/azure/azure-cli

**Comment by amarzavery** [comment]
Please read this WARNING message https://github.com/Azure/azure-xplat-cli#please-consider-using-azure-cli-20-the-preferred-choice-for-arm-azure-resource-manager-commands

**Comment by ctahok** [comment]
As per https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-best-practices#resources you can use them now:

"resources": [
   {
       "name": "[variables('storageAccountName')]",
       "type": "Microsoft.Storage/storageAccounts",
       "apiVersion": "2019-06-01",
       "location": "[resourceGroup().location]",
       "**comments**": "This storage account is used to store the VM disks.",
       ...
   }
]
