### ISSUE TITLE
ARM: `azure vm image list` prompts for publisher

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2113]
Hello, I'm new to Azure and I don't know the publishers you folks have. I just want to list all the VM images you got and  pick from there:

```
➜  ~  azure vm image list
info:    Executing command vm image list
Location: eastus
Publisher:
```

but this command does not let me do that by prompting me for publisher name. Why? @devigned @yugangw-msft

**Comment by devigned** [comment]
I know... This something that needs to change.

**Comment by devigned** [comment]
@kmouss can we do away with publisher?

**Comment by ahmetalpbalkan** [comment]
This is inherently due to bad API design in CRM. ETOOBAD...
