### ISSUE TITLE
ARM: `azure ad` branding of "Active Directory"

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2118]
I wonder since when "active directory" is all lowercase. :) 

![image](https://cloud.githubusercontent.com/assets/159209/9971156/975a48ea-5e0e-11e5-82aa-20a5851ae3dc.png)

**Comment by devigned** [comment]
nice nit. We'll get that updated

**Comment by haocs** [comment]
Changed to "Active Directory" in this PR https://github.com/Azure/azure-xplat-cli/pull/2774
