### ISSUE TITLE
azure vm docker create fails to understand the resource group parameter (arm mode)

### ISSUE THREAD

**Issue by squillace** [Azure/azure-xplat-cli#2121]
When using 0.9.9 in ARM mode, passing the resourcegroup parameter fails, though the group exists and the arguments are to spec with the docs. Repro machine, macbookpro 2015, azure-cli 0.9.9.

```
rasquill•~/workspace/keygen» azure group create DockerRG northcentralus                                                                                     [14:02:31]
info:    Executing command group create
+ Getting resource group DockerRG
+ Creating resource group DockerRG
info:    Created resource group DockerRG
data:    Id:                  /subscriptions/guid/resourceGroups/DockerRG
data:    Name:                DockerRG
data:    Location:            northcentralus
data:    Provisioning State:  Succeeded
data:    Tags: null
data:
info:    group create command OK
rasquill•~/workspace/keygen» azure vm docker create -n DummyDockerEngineHost -l "South Central US" -e 20 -y Linux -q UbuntuServer:14.04.3-LTS:14.04.201509080 -g DockerRG -D DummyDockerEngineHostNic -u myuser -p NotMyPassword123!
info:    Executing command vm docker create
+ Generating docker certificates.
+ Looking up the VM "DummyDockerEngineHost"
info:    Using the VM Size "Standard_A1"
warn:    The image "UbuntuServer:14.04.3-LTS:14.04.201509080" will be used for VM
info:    The [OS, Data] Disk or image configuration requires storage account
+ Retrieving storage accounts
info:    Could not find any storage accounts in the region "southcentralus", trying to create new one
+ Creating storage account "clibb772100f8cf359d14426" in "southcentralus"
+ Looking up the storage account clibb772100f8cf359d14426
info:    Found NIC Id parameter, NIC name if specified will be ignored
+ Looking up the NIC "DummyDockerEngineHostNic"
error:   resourceGroupName cannot be null.
info:    Error information has been recorded to /Users/rasquill/.azure/azure.err
error:   vm docker create command failed
```

@ahmetalpbalkan @ruslangabitov

**Comment by ahmetalpbalkan** [comment]
@ruslangabitov just fyi, looks like you're unassigned by the bot.

**Comment by devigned** [comment]
@stankovski why would @ruslangabitov get unassigned by the bot?

**Comment by stankovski** [comment]
Not sure, we'll need to take a look at the bot on Monday. Bot should not be making any changes to the issues in GitHub.

**Comment by ahmetalpbalkan** [comment]
@stankovski @devigned rough guess from my experience, you're using (_a library that uses_) HTTP PATCH operation to update the issue, and in the request you send, there's a field "assigned_to", even though it's empty string/number or simply null, GitHub will interpret is as "unassignment" and make it so. Might be related to the Github library you're using. Similar problem here: https://willnorris.com/2014/05/go-rest-apis-and-pointers

**Comment by ruslangabitov** [comment]
That's not a Docker issue, but problem with 'vm create' in general.
You were specifying <code>NIC Name</code> instead of <code>NIC ID</code>.
To create a VM using <code>NIC name</code> you have to use <code>-f</code> option instead of <code>-D</code>
![image](https://cloud.githubusercontent.com/assets/6327511/10001341/21e3fd50-6056-11e5-9783-5d358c456635.png)

Anyway I've added validation for NIC IDs and fixed error handling.
Now it will throw accurate error message.
![image](https://cloud.githubusercontent.com/assets/6327511/10001265/bf3a5f82-6055-11e5-92b5-2f6c16eaa434.png)

https://github.com/MSOpenTech/azure-xplat-cli/pull/505

**Comment by sreekanthbs** [comment]
@ruslangabitov i verified in azure-dev branch & the issue is reproducible.
![image](https://cloud.githubusercontent.com/assets/11171941/10139267/b299eb7e-661f-11e5-83eb-d191eea0afa6.png)

**Comment by ahmetalpbalkan** [comment]
@sreekanthbs as Ruslan mentioned above can you please try `-f` instead of `-D` if you're using NIC Name, not ID.

**Comment by ruslangabitov** [comment]
@sreekanthbs can you please verify in MSOpenTech's dev branch https://github.com/MSOpenTech/azure-xplat-cli/tree/dev? It's not in Azure's repo yet.

**Comment by sreekanthbs** [comment]
@ruslangabitov yes its working fine in  https://github.com/MSOpenTech/azure-xplat-cli/tree/dev branch.
Now it is throwing accurate error message.
![image](https://cloud.githubusercontent.com/assets/11171941/10156300/1f1a3ed4-669d-11e5-9f22-55a29c4f0f67.png)
