### ISSUE TITLE
ARM: `azure vm quick-create` maliciously using alphabetically-first subscription

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2125]
When I use `azure vm quick-create`, this command picks the alphabetically first Storage Account in the region to store VHDs. This is the same mistake fixed in #1753 for asm...

We don't do this, you never know what a user does on a particular storage account that's not explicitly created by portal. Right now by running this command, I just contaminated a storage account that has nothing to do with VHDs.

You need use the convention (`portalvhd` prefix) that exists in manage.windowsazure.com Portal and the ASM version of CLI. If needed, please create a new storage account for this command.

@devigned can you please prioritize?

**Comment by devigned** [comment]
@singhkay thoughts on this one?

**Comment by singhkay** [comment]
I'll defer to @kmouss on CLI :)

**Comment by ahmetalpbalkan** [comment]
cc: @anuchandy as well. He helped on earlier issue on asm mode.

**Comment by ahmetalpbalkan** [comment]
@kmouss please comment.

I also realized if storage account is missing, the cli creates one named `cli$RANDOMSTRING`, this is different than `portal$RANDOMSTRING` and if there's one already, it might be weird to not to reuse the portal one.

**Comment by huangpf** [comment]
ASM?

**Comment by ahmetalpbalkan** [comment]
@huangpf no this was reported for ARM

**Comment by huangpf** [comment]
It's not feasible to tell what a storage account name means without peeking into the content... (which is also not any close to feasible), so I think it's safer not to randomly pick a storage account. Instead, it shall either create a new one, or use the specified one, if given.

**Comment by ahmetalpbalkan** [comment]
@huangpf I'm not even sure if this is valid anymore. Are we reusing storage accounts now in case of quick-create?

**Comment by huangpf** [comment]
@ahmetalpbalkan Good point. I checked, and we will generate the storage account for quick create. Close...
