### ISSUE TITLE
ARM: delete for `azure vm quick-create`

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2126]
`azure vm quick-create` is really useful to get a VM to try something and play with things, however it provisions multiple resources (IP, NIC, VNET, VM) and after the user is done with the VM, deleting those is _a bit_ painful: User has to go to portal and locate the resources... 

If multiple VMs are `quick-create`d within the same RG with similar names, it becomes even harder to distinguish names of the IP/NIC resources (command uses random strings) and becomes even harder to selectively delete resources of a VM...

If there was a way to delete the  `quick-create`d VM and resources associated to it, it would be pleasant.

**Comment by huangpf** [comment]
Sorry, there is no optimal way to distinguish our quick-created VM from any other methods, quick or non-quick.

It's up to the users to manage, e.g. apply some quickness tags on the resource group...

**Comment by ahmetalpbalkan** [comment]
> It's up to the users to manage, e.g. apply some quickness tags on the resource group...

or it is up to you, you can add tags while creating those resources. :)

**Comment by mw007** [comment]
@ahmetalpbalkan, are you saying you can apply tags to everything created via `azure vm quick-create`?

If so, how can this be done? I'm very interested in being able to do this. :+1:

**Comment by ahmetalpbalkan** [comment]
> are you saying you can apply tags to everything created via azure vm quick-create?

no. I'm saying quick-create should apply tags to resources it creates so that it can have a nice and clean delete method for the resources it has created.

**Comment by mw007** [comment]
Ahh agreed. This would be extremely useful.
