### ISSUE TITLE
Create website associated for a pricing plan

### ISSUE THREAD

**Issue by jaimetotal** [Azure/azure-xplat-cli#2130]
By the management portal is possible to create a website associated with a given pricing plan/server farm but it seems that any server farm related configuration is still not possible.

Is it possible to include this feature?

**Comment by devigned** [comment]
@davidebbo if there is no existing plan, then you are not able to create a web app. This is a rough experience for a consumer.

I had to resort to creating a webapp with a resource template. That was not nearly as fun as `azure webapp create ...`

**Comment by davidebbo** [comment]
I haven't used on the xplat much, but my understand is that for the most part, each command becomes a single PUT. And creating an app service plan is a very separate action from creating an app that goes within it. So I'm not convinced we want to combine them, as that would create a very complex command (there are many switches for the plan creation).

**Comment by ahmedelnably** [comment]
Unfortunately we don't have ARM support for our CLI right now, we are looking on supporting that soon, though no ETA yet for that

We have that supported in PowerShell if that is a viable option for you

**Comment by ylulloa** [comment]
any ETA on this?

**Comment by ahmedelnably** [comment]
Hello @ylulloa 
This is now available in CLI
please check the following article: http://aka.ms/webapp-cli
