### ISSUE TITLE
Login was failing and now "no subscriptions found for this account"

### ISSUE THREAD

**Issue by ericis** [Azure/azure-xplat-cli#2137]
v0.9.9

Originally, I was getting "password expired" although I could log into Azure management portal just fine. The sign-in process would prompt me to choose Personal vs. Organizational account and I always choose Personal.

I tried selecting "Organizational" account during portal login and was prompted to reset my password. A few hours later I was suddenly able to login to CLI tools (prompted by an Azure support call).  But, no subscriptions are listed.  (the billing support specialist said they don't deal directly with CLI or technical support, so I'd have to follow-up with a technical ticket if I continued experiencing problems)

So, my guess would be that the CLI tools are trying to log me in via Organizational and something is going awry.  Ideas?  I can provide details as necessary. Tell me what to run.

    azure login [xxxxxxxx@xxxxxxxxxxxxxxxx.xxxx]
    info:    Executing command login
    Password: ************************
    \info:    No subscriptions found for this account
    +
    info:    login command OK

**Comment by amarzavery** [comment]
@ericis - Sorry for the experience. Currently CLI can only login via Organizational account. If you have a subscription linked to the organizational account then the CLI will list the subscription, once the login via organizational account is successful.

How did you create an organizational account ?

**Comment by yugangw-msft** [comment]
With #2178, you can login using non org-id. Either way, this is not an issue any more
