### ISSUE TITLE
Provide more evident error cause for case of incorrect value template-url

### ISSUE THREAD

**Issue by BorisB2015** [Azure/azure-xplat-cli#2142]
Repro:

1. Create appropriate group (TestRG) and run: 

azure group deployment create TestRG TestDeploy --template-uri https://raw.githubusercontent.com/gbowerman/azure-myriad/master/vmss-vnet-storage-ubuntu.json

2. You will get (among other things):

error:   Unexpected token N

which is not obvious that it is the result of 

GET https://raw.githubusercontent.com/gbowerman/azure-myriad/master/vmss-vnet-storage-ubuntu.json ==> Not Found, i.e. wrong URL provided. 

No detailed error file contains actual fragment of what was read from provided template URI.

Expected: fragment of input is captured and displayed at least in the azure.detail.err file or azure.err file, something like:

error: Unexpected token N
info: Content received from --template-uri (https://raw.githubusercontent.com/gbowerman/azure-myriad/master/vmss-vnet-storage-ubuntu.json): "Not found..." (provide at least few hundred bytes of output in the detail file)

**Comment by yugangw-msft** [comment]
@vivsriaus, please consider

**Comment by amarzavery** [comment]
```
azure group deployment create TestRG TestDeploy --template-uri https://raw.githubusercontent.com/gbowerman/azure-myriad/master/vmss-vnet-storage-ubuntu.json
info:    Executing command group deployment create
info:    Supply values for the following parameters
error:   Parse error on line 1:
404: Not Found
---^
Expecting 'EOF', '}', ',', ']', got ':'
error:   Error information has been recorded to C:\Users\amzavery\.azure\azure.err
error:   group deployment create command failed
````
