### ISSUE TITLE
[ARM] --tags format option seems to throw arg parsing (azure vm create; 0.9.9 mac yosemite)

### ISSUE THREAD

**Issue by squillace** [Azure/azure-xplat-cli#2147]
Have a look. It looks right:

I don’t know what to do here. Imperatively creating a full network infrastructure for a VM, and I go to create the vm and….

```
─(~/workspace/keygen/newkeys)────────────────────────────────────────────────────────────────────────────────────────────(rasquill@macbookpro:s001)─┐
└─(17:42:46)──> azure vm create \                                                                                              
──()── --resource-group testrg \
──()── --name testvm \
──()── --location westeurope \
──()── --os-type linux \
──()── --nic-name testnic \
──()── --public-ip-name testpip \
──()── --vnet-name testvnet \
──()── --vnet-subnet-name FrontEnd \
──()── --storage-account-name computeteststore \
──()── --tags deploy=imperative;distro=ubuntu \
──()── --image-urn canonical:UbuntuServer:14.04.3-LTS:latest \
──()── --admin-username ops \
──()── --ssh-publickey-file ~/.ssh/id_rsa \
──()──
info:    Executing command vm create
+ Looking up the VM "testvm"
error:   image-name, image-urn or os-disk-vhd parameter is required to create a VM
info:    Error information has been recorded to /Users/rasquill/.azure/azure.err
error:   vm create command failed
```

Here’s the docs:

```
help:      -Q, --image-urn <image-urn>                                            the image URN in the form publisherName:offer:skus:version [image-urn and image-name parameters are mutually exclusive]
``` 

I think it’s the tags string; I removed that, and it all goes through. Did I misformat the tags?

```
azure vm create \                                                                                                      
--resource-group testrg \
--name testvm \
--location westeurope \
--os-type linux \
--nic-name testnic \
--public-ip-name testpip \
--vnet-name testvnet \
--vnet-subnet-name FrontEnd \
--storage-account-name computeteststore \
--image-urn canonical:UbuntuServer:14.04.3-LTS:14.04.201509080 \
--admin-username ops \
--ssh-publickey-file ~/.ssh/id_rsa.pub
```

It sure looks like I did... but I think I obeyed the docs on tags:

```
help:      --tags <tags>                                                          
Tags to set to the virtual machine. Can be multiple. In the format of 'name=value'. Name is required and value is optional. For example, --tags tag1=value1;tag2
```

@ahmetalpbalkan fyi

**Comment by ahmetalpbalkan** [comment]
looks like a bug if you removed `--tags` and it all worked. can you move `--image-urn` above `--tags` and see it still works?

**Comment by squillace** [comment]
Hmmm. Did that, now it doesn't pick up the last argument:

```
azure vm create \                                                                                                                                                                                                                                                                                                     130 ↵ ──(Mon,Sep28)─┘
--resource-group testrg \
--name testvm \
--location westeurope \
--os-type linux \
--nic-name testnic \
--vnet-name testvnet \
--vnet-subnet-name FrontEnd \
--storage-account-name computeteststore \
--image-urn canonical:UbuntuServer:14.04.3-LTS:14.04.latest \
--tags distro=ubuntu;deploymode=imperative \
--ssh-publickey-file ~/.ssh/id_rsa.pub \
--admin-username ops
info:    Executing command vm create
+ Looking up the VM "testvm"
Enter username:
```

**Comment by ahmetalpbalkan** [comment]
I think I know what might be happening here. ; is a command delimeter in bash. Can you try surrounding value of --tags with single quotes?




If that works this cmd is suboptimal. 




It should allow multiple usages like: --tag a=b --tag c=d. That's a better convention/design. 



— Ahmet Alp Balkan http://alp.im

On Mon, Sep 28, 2015 at 11:36 AM, Ralph Squillace
<notifications@github.com> wrote:

> Hmmm. Did that, now it doesn't pick up the last argument:
> ```
> azure vm create \                                                                                                                                                                                                                                                                                                     130 ↵ ──(Mon,Sep28)─┘
> --resource-group testrg \
> --name testvm \
> --location westeurope \
> --os-type linux \
> --nic-name testnic \
> --vnet-name testvnet \
> --vnet-subnet-name FrontEnd \
> --storage-account-name computeteststore \
> --image-urn canonical:UbuntuServer:14.04.3-LTS:14.04.latest \
> --tags distro=ubuntu;deploymode=imperative \
> --ssh-publickey-file ~/.ssh/id_rsa.pub \
> --admin-username ops
> info:    Executing command vm create
> + Looking up the VM "testvm"
> Enter username:
> ```
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Azure/azure-xplat-cli/issues/2147#issuecomment-143837166

**Comment by ahmetalpbalkan** [comment]
I think what's happening here. `;` is a command delimeter in bash. Can you try surrounding value of --tags with single quotes? If that works this cmd is suboptimal.

It should allow multiple usages like: `--tag a=b --tag c=d`. That would be a better convention/design.

**Comment by yugangw-msft** [comment]
@squillace, did Ahmet's suggestion work? If that works, we can close this, and open a new one for tag value format improvement

**Comment by squillace** [comment]
I did not try it; I'll try it today and let you know.

**Comment by ahmetalpbalkan** [comment]
@squillace ping

**Comment by squillace** [comment]
OK, @yugangw-msft,  clearly this was hi-pri. Tags **does** in fact work fine when you wrap it in quotes; @ahmetalpbalkan's right.

> data:    Tags                            :deploy=imperative;distro=ubuntu

Since this kind of escaping is common, I propose we leave it, doc it, and move on. Sorry for the delay.
