### ISSUE TITLE
Unfriendly communication in MFA login

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2165]
What does exactly "Try again..." mean below?

![image](https://cloud.githubusercontent.com/assets/159209/10230202/c789faa2-6830-11e5-9961-adceb0e35e27.png)

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan 
This is a text introduced by the re-try logic (will be removed shortly), that cli launches the old flow first, and on err it retries with new device flow.  The text is outputted to justify, that you need to input password twice, once in the command flow and the other in the browser, which is a redundant cli forces on you.
2 notes,
a. In the upcoming release, we will expose the flag "--interactive" so you will not be asked to input password in the command line. For all 2fa enabled, you need to use this.
b. The token cli persisted at local will be valid for 3 months, so as long as you use the cli at least once every 2 weeks, you do not need to login every day.
Hope this explains.

**Comment by ahmetalpbalkan** [comment]
I see thanks for the heads up. 

It'd be better to not to expose inner workings of the cli to the user as the default behavior. Great to hear it'll be fixed. Keeping it open for tracking.

**Comment by yugangw-msft** [comment]
Addressed by #2178, and will be out with the release of 0.9.10
