### ISSUE TITLE
Travis build failure due to 'arm group template' test cases

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2167]
The reason is merged PR https://github.com/Azure/azure-xplat-cli/pull/2164 with failed Travis build https://travis-ci.org/Azure/azure-xplat-cli/jobs/83047750

**Comment by yugangw-msft** [comment]
This is a known test flakiness. The test should not replay a public gallery template which will change and and fail test.

**Comment by yugangw-msft** [comment]
Fixed through #2176
