### ISSUE TITLE
ASM: NSG Rule create do not supports port range

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2177]
ASM: `azure nsg rule create` commands should support port range for `--source-port-range` and `--destination-port-range` options.

Example of allowed values: `80, 80-81, *`

**Comment by romangromov** [comment]
will fix

**Comment by infosatheesh2020** [comment]
Thanks! @romangromov can we expect this in 0.9.10 release?

**Comment by romangromov** [comment]
@infosatheesh2020 not sure about that, will try and let you know

**Comment by romangromov** [comment]
@sreekanthbs please verify fix in our repo, thanks

**Comment by sreekanthbs** [comment]
@romangromov verified.its working fine  for --source-port-range and --destination-port-range options.
Verified in both windows & linux env.
![image](https://cloud.githubusercontent.com/assets/11171941/10387879/aa0fc346-6e82-11e5-8b63-6a9d2373e4a0.png)

**Comment by infosatheesh2020** [comment]
@romangromov can you let me know the branch so that even if this fix is not in 0.9.10 npm version, I can still use it from branch..

**Comment by yugangw-msft** [comment]
Closing as the fix was in

**Comment by romangromov** [comment]
@yugangw-msft fix for this issue is not yet merged, related PR with fix https://github.com/Azure/azure-xplat-cli/pull/2182

**Comment by romangromov** [comment]
@infosatheesh2020 now fix merged to `dev` branch, `git checkout dev`

**Comment by infosatheesh2020** [comment]
@romangromov Thank you!

**Comment by infosatheesh2020** [comment]
@romangromov Shall we get a feature to specify destination port in Comma?

Like below:
--destination-port-range "22,25,80,8080"

**Comment by romangromov** [comment]
@infosatheesh2020 currently, only this notations supported on server end: `80, 80-81, *`

**Comment by infosatheesh2020** [comment]
@romangromov Thanks for the info
