### ISSUE TITLE
Two-factor authentication was not released in 0.9.9 (or 0.9.10)

### ISSUE THREAD

**Issue by sondreb** [Azure/azure-xplat-cli#2199]
Previously it was communicated that two-factor authentication (2FA) was coming in v0.9.9, this did not happen and now that 0.9.10 is out, it's still not supported.

https://azure.microsoft.com/en-us/blog/azure-cli-supports-microsoft-account-logins/

Are you planning to support two-factor authentication? Is there major hurdles and issues that makes it impossible from the command prompt? Why can't you rely on app-passwords?

Previous issue: https://github.com/Azure/azure-xplat-cli/issues/1935

Would be awesome if you could keep your Milestones up-to-date, so we know what you are working on, or not: https://github.com/Azure/azure-xplat-cli/milestones

**Comment by yugangw-msft** [comment]
@sondreb 
2FA does happen with 0.9.10. If you use the interactive flow though "azure login", that will log you in.
Do you expect all done in the command prompt, w/o browser interaction? If yes, then no, that is a different thing that we never claimed to deliver.

**Comment by sondreb** [comment]
This works great, thanks! I simply wish you had communicated this better in the press release, it does not come across as it supports 2FA. I have no issues with the web flow, though it would be nice if you could auto-launch the URL.

**Comment by yugangw-msft** [comment]
@sondreb, thanks for the confirmation.
Yes, we are looking at the part of "auto-launch the URL", and will let you know if we have made progress
