### ISSUE TITLE
Method to remove NSG from a nic

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-xplat-cli#2200]
How do I remove a NSG from a nic?

I wound up doing it through the portal for now...

**Comment by romangromov** [comment]
@colemickens try this one `azure network nic set your-res-group YourNic --network-security-group-id ""`

**Comment by colemickens** [comment]
Looks like that worked. I had tried something similar but with `--network-security-group-name`. This indeed worked. Thanks.

**Comment by romangromov** [comment]
@colemickens glad to help
