### ISSUE TITLE
azure login: getting error 'Credentials have expired, please reauthenticate'

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2205]
I've changed my password for  `v-...@microsoft.com` email, and now `azure login` doesn't work anymore for me:
1)  `azure login` prompts to open browser:
```
D:\Gromov\Projects\NodeJS\xplat-cli\azure-xplat-cli-ms>azure login
info:    Executing command login
\info:    To sign in, use a web browser to open the page http://aka.ms/devicelogin. Enter the code CRPDMSHJF to authenticate. If you're signing in as an Azure AD application, use the --username and --password parameters
```
2) Ok, done, we should be good here:
![screenshot_5](https://cloud.githubusercontent.com/assets/1655573/10573634/7c1f7f1a-7659-11e5-8f35-4966512b4878.png)

3) Xplat-CLI fails with error details below:
```
D:\Gromov\Projects\NodeJS\xplat-cli\azure-xplat-cli-ms>azure login
info:    Executing command login
\info:    To sign in, use a web browser to open the page http://aka.ms/devicelogin. Enter the code CRPDMSHJF to authenticate. If you're signing in as an Azure AD application, use the --username and --password parameters
.
+
error:   Credentials have expired, please reauthenticate.
         Detailed error message from ADAL is as follows: Error: Entry not found in cache.
info:    Error information has been recorded to C:\Users\roman.gromov\.azure\azure.err
error:   login command failed
```
4) tried `azure account clear`, no luck

@yugangw-msft can you please help me to figure this out?
Attaching verbose logs, hope this helps https://gist.github.com/romangromov/db4852944df09cc55a3d#file-credentials-expired-error

**Comment by yugangw-msft** [comment]
@romangromov , are you still blocked? 
You can use the script "\<azure-cli-repo-root\>tools\\windows\\scripts\\listTokens.cmd" to check out whether tokens were ever issued.
If still no clue, please [turn on fiddler](https://github.com/Azure/azure-xplat-cli/blob/dev/tools/windows/scripts/enableFiddler.cmd), capture the traffic and send to me at yugangw at microsoft dot com, and i will forward to AAD team

**Comment by romangromov** [comment]
@yugangw-msft after some experiments, I was able to checkout outdated branch and login. This issue happens only in latest `dev` branch

**Comment by yugangw-msft** [comment]
@romangromov, since recent release, there is no change occurred which could impact sign-in https://github.com/Azure/azure-xplat-cli/compare/release-0.9.10...dev
I am able to log in using my corp account with the latest dev. Could you try again and let me know whether it is still broken?

**Comment by yugangw-msft** [comment]
@romangromov , please reopen if you see it with the latest dev

**Comment by romangromov** [comment]
@yugangw-msft checked on latest `dev`, working fine now, thanks for looking into this!
