### ISSUE TITLE
ASM - azure network application-gateway issue

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-xplat-cli#2212]
First I run below command to create a AG successfully.

azure network application-gateway create liliag liliagvnet subnet-1 --instance-count 2 --gateway-size 

Then wants to add backend pool by below command, but it needs me to add one frontendport port firstly.

azure network application-gateway address-pool add -w liliag -n liliagbackendpool -r 192.168.2.36,192.168.2.37
info:    Executing command network application-gateway address-pool add
+ Getting configuration for an Application Gateway "liliag"
+ Setting configuration for an Application Gateway "liliag"
error:   Error Setting Application Gateway Configuration- 'Atleast one FrontendPort must be specified'.
info:    Error information has been recorded to C:\Users\v-lide\.azure\azure.err
error:   network application-gateway address-pool add command failed

So I use below command to create frontend port, but it needs me to create a backendaddresspool. Does anyone know how to resolve this?

azure network application-gateway frontend-port add -w liliag -n lilifrontport1 -o 80
info:    Executing command network application-gateway frontend-port add
+ Getting configuration for an Application Gateway "liliag"
+ Setting configuration for an Application Gateway "liliag"
error:   Error Setting Application Gateway Configuration- 'Atleast one BackendAddressPool must be specified'.
info:    Error information has been recorded to C:\Users\v-lide\.azure\azure.err
error:   network application-gateway frontend-port add command failed

**Comment by romangromov** [comment]
@LiliDeng once Application Gateway create, the next step is to import it's configuration:
`azure network application-gateway config import your-gateway-name "D:\config.json"`.
After this you can modify child resources, like frontend ports, address pools, etc.

Here is an example of `config.json`, Note: all of nodes (frontend ports, pools, etc.) are required:

```json
{
    "backendAddressPools": [{
        "backendServers": [{
            "iPAddress": "10.0.0.1"
        }],
        "name": "pool1"
    }, {
        "backendServers": [{
            "iPAddress": "10.0.0.2"
        }],
        "name": "MyPool"
    }, {
        "backendServers": [{
            "iPAddress": "10.0.0.2"
        }, {
            "iPAddress": "10.0.0.2"
        }],
        "name": "TestPool"
    }],
    "backendHttpSettingsList": [{
        "name": "setting1",
        "port": 80,
        "protocol": "Http",
        "cookieBasedAffinity": "Enabled"
    }, {
        "name": "MySettings",
        "port": 81,
        "protocol": "Http",
        "cookieBasedAffinity": "Enabled"
    }, {
        "name": "settings2",
        "port": 888,
        "protocol": "Http",
        "cookieBasedAffinity": "Disabled"
    }, {
        "name": "settings3",
        "port": 999,
        "protocol": "Http",
        "cookieBasedAffinity": "Disabled"
    }],
    "frontendIPConfigurations": [{
        "name": "fip1",
        "type": "Private",
        "staticIPAddress": "10.0.0.10"
    }],
    "frontendPorts": [{
        "name": "fep1",
        "port": 80
    }, {
        "name": "test-port1",
        "port": 6556
    }],
    "httpListeners": [{
        "name": "listener1",
        "frontendPort": "fep1",
        "protocol": "Http"
    }, {
        "name": "test-http-listener",
        "frontendPort": "test-port1",
        "protocol": "Http"
    }],
    "httpLoadBalancingRules": [{
        "name": "rule1",
        "type": "Basic",
        "backendHttpSettings": "setting1",
        "listener": "listener1",
        "backendAddressPool": "pool1"
    }, {
        "name": "test-rule",
        "type": "Basic",
        "backendHttpSettings": "setting1",
        "listener": "listener1",
        "backendAddressPool": "pool1"
    }]
}
```

**Comment by LiliDeng** [comment]
Thanks Roman, currently I do like this way, so it is the only way that we configure AG?

**Comment by romangromov** [comment]
@LiliDeng yes, this is only one way to get it work. We know, it's not obvious, but you have to do this because of it's designed this way on server end

**Comment by LiliDeng** [comment]
@romangromov thanks so much, I cost some time investigating it before I got the answer.

**Comment by yugangw-msft** [comment]
Solution is available. Closing
