### ISSUE TITLE
ARM: 'azure network nic inbound-nat-rule/address-pool add' throws error

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2236]
```
azure network nic inbound-nat-rule add -g cspname -n nic1 -l lb -r ib1
info:    Executing command network nic inbound-nat-rule add
+ Looking up the network interface "nic1"
+ Looking up the load balancer "lb"
error:   Cannot read property 'inboundNatRules' of undefined
info:    Error information has been recorded to C:\Users\derajen\.azure\azure.err
error:   network nic inbound-nat-rule add command failed
```

**Comment by romangromov** [comment]
Will fix, + @DeepakRajendranMsft for visibility

**Comment by sreekanthbs** [comment]
@romangromov network nic inbound-nat-rule add is working fine in azure-xplat-cli-arm-nic-fix branch
<pre>
<code>
C:\Oct\29Oct\azure-xplat-cli-arm-nic-fix>node bin/azure network nic inbound-nat-rule add armresgrp29O nic29 -l lb1 -r natrule1
info:    Executing command network nic inbound-nat-rule add
+ Looking up the network interface "nic29"
+ Looking up the load balancer "lb1"
+ Updating network interface "nic29"
info:    network nic inbound-nat-rule add command OK
</code>
</pre>

**Comment by sreekanthbs** [comment]
@romangromov  the same issue is with network nic address-pool add .
I verified in azure-xplat-cli-arm-nic-fix branch also its not working for address-pool name option.
<pre>
<code>C:\Oct\29Oct\azure-xplat-cli-arm-nic-fix>node bin/azure network nic address-pool add armresgrp29O nic29 -l lb1 -a pool1
info:    Executing command network nic address-pool add
+ Looking up the network interface "nic29"
+ Looking up the load balancer "lb1"
error:   Cannot read property 'backendAddressPools' of undefined
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network nic address-pool add command failed
</pre>
</code>

**Comment by romangromov** [comment]
@sreekanthbs fixed for `address-pool add` as well

**Comment by sreekanthbs** [comment]
@romangromov yes its working fine now for both nic  inbound-nat-rule add & nic address-pool add .
