### ISSUE TITLE
Unable to set port range on network security group rule

### ISSUE THREAD

**Issue by tung-jin-chew-hp** [Azure/azure-xplat-cli#2238]
It's currently not possible to set a port range when creating/editing a network security group due to a bug in lib/commands/arm/network/nsg._js validatePortRange.js. The Web UI allows ranges, e.g. 9000-10000. 

Here's an example:
```
tungj@tungj-notebook:~$ azure network nsg rule create SecurityResourceGroup ESFGroup AllowESFIncoming -d 'Allow incoming traffic from proxy' -p 'Tcp' -f '15.203.169.110/32' -o '*' -e 'VirtualNetwork' -u '9000-9500' -c Allow -r Inbound
info:    Executing command network nsg rule create
error:   destination port parameter must be an integer between 0 and 65535
info:    Error information has been recorded to /home/tungj/.azure/azure.err
error:   network nsg rule create command failed

```

**Comment by tung-jin-chew-hp** [comment]
This is an example of it working with the #2239 patch (both add and set use the same _validatePortRange function):
```
  tungj@tungj-notebook:~$ azure network nsg rule set SecurityResourceGroup ESFGroup AllowESFIncoming -d 'Allow incoming traffic from proxy' -p 'Tcp' -f '15.203.169.110/32' -o '*' -e 'VirtualNetwork' -u '9000-9500' -c Allow -r Inbound
  info:    Executing command network nsg rule set
  + Looking up the network security group "ESFGroup"                             
  + Setting a network security rule "AllowESFIncoming"                           
  + Looking up the network security group "ESFGroup"                             
  data:    Id                              : /subscriptions/4ac6dfb0-3b4a-480e-ab8f-a89c540f74b1/resourceGroups/SecurityResourceGroup/providers/Microsoft.Network/networkSecurityGroups/ESFGroup/securityRules/AllowESFIncoming
  data:    Name                            : AllowESFIncoming
  data:    Type                            : Microsoft.Network/networkSecurityGroups/securityRules
  data:    Provisioning state              : Succeeded
  data:    Description                     : Allow incoming traffic from proxy
  data:    Source IP                       : 15.203.169.110/32
  data:    Source Port                     : *
  data:    Destination IP                  : VirtualNetwork
  data:    Destination Port                : 9000-9500
  data:    Protocol                        : Tcp
  data:    Direction                       : Inbound
  data:    Access                          : Allow
  data:    Priority                        : 100
  info:    network nsg rule set command OK
```

**Comment by romangromov** [comment]
@yugangw-msft bug, will fix

**Comment by romangromov** [comment]
+@sreekanthbs

**Comment by sreekanthbs** [comment]
Verified and it is working fine.
<pre>
<code>
root@dndubuntu1204:/home/azureuser/azure-xplat-cli-azure-dev# node bin/azure network nsg rule set armrestestgrp2n nsg2n nsgrule2n -d 'Allow incoming traffic from proxy22' -p 'Tcp' -f '15.203.169.110/16' -o '*' -e 'VirtualNetwork' -u '7000-7500' -c Allow -r Outbound
info:    Executing command network nsg rule set
+ Looking up the network security group "nsg2n"
+ Setting a network security rule "nsgrule2n"
+ Looking up the network security group "nsg2n"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armrestestgrp2n/providers/Microsoft.Network/networkSecurityGroups/nsg2n/securityRules/nsgrule2n
data:    Name                            : nsgrule2n
data:    Type                            : Microsoft.Network/networkSecurityGroups/securityRules
data:    Provisioning state              : Succeeded
data:    Description                     : Allow incoming traffic from proxy22
data:    Source IP                       : 15.203.169.110/16
data:    Source Port                     : *
data:    Destination IP                  : VirtualNetwork
data:    Destination Port                : 7000-7500
data:    Protocol                        : Tcp
data:    Direction                       : Outbound
data:    Access                          : Allow
data:    Priority                        : 100
info:    network nsg rule set command OK


root@dndubuntu1204:/home/azureuser/azure-xplat-cli-azure-dev# node bin/azure network nsg rule set armrestestgrp2n nsg2n nsgrule2n -d 'Allow incoming traffic from proxy22' -p 'Tcp' -f '15.203.169.110/16' -o 10000-10500 -e 'VirtualNetwork' -u '7000-7500' -c Allow -r Outbound
info:    Executing command network nsg rule set
+ Looking up the network security group "nsg2n"
+ Setting a network security rule "nsgrule2n"
+ Looking up the network security group "nsg2n"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armrestestgrp2n/providers/Microsoft.Network/networkSecurityGroups/nsg2n/securityRules/nsgrule2n
data:    Name                            : nsgrule2n
data:    Type                            : Microsoft.Network/networkSecurityGroups/securityRules
data:    Provisioning state              : Succeeded
data:    Description                     : Allow incoming traffic from proxy22
data:    Source IP                       : 15.203.169.110/16
data:    Source Port                     : 10000-10500
data:    Destination IP                  : VirtualNetwork
data:    Destination Port                : 7000-7500
data:    Protocol                        : Tcp
data:    Direction                       : Outbound
data:    Access                          : Allow
data:    Priority                        : 100
info:    network nsg rule set command OK

root@dndubuntu1204:/home/azureuser/azure-xplat-cli-azure-dev# node bin/azure network nsg rule set armrestestgrp2n nsg2n nsgrule2n -d 'Allow incoming traffic from proxy22' -p 'Tcp' -f '15.203.169.110/16' -o 10000-10500 -e 'VirtualNetwork' -u '*' -c Allow -r Outbound
info:    Executing command network nsg rule set
+ Looking up the network security group "nsg2n"
+ Setting a network security rule "nsgrule2n"
+ Looking up the network security group "nsg2n"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armrestestgrp2n/providers/Microsoft.Network/networkSecurityGroups/nsg2n/securityRules/nsgrule2n
data:    Name                            : nsgrule2n
data:    Type                            : Microsoft.Network/networkSecurityGroups/securityRules
data:    Provisioning state              : Succeeded
data:    Description                     : Allow incoming traffic from proxy22
data:    Source IP                       : 15.203.169.110/16
data:    Source Port                     : 10000-10500
data:    Destination IP                  : VirtualNetwork
data:    Destination Port                : *
data:    Protocol                        : Tcp
data:    Direction                       : Outbound
data:    Access                          : Allow
data:    Priority                        : 100
info:    network nsg rule set command OK

</code>
</pre>

**Comment by romangromov** [comment]
@tung-jin-chew-hp please make sure `azure network nsg rule set` working fine now and let me know, otherwise please close the issue, Thanx!

**Comment by romangromov** [comment]
@yugangw-msft this can be closed, fixed

**Comment by prakashsingh2910** [comment]
It can be fixed using following code snippet-
 $nsgRuleDestinationPortRange = "443;5300;1025-5000"
 Add-AzNetworkSecurityRuleConfig -Name $nsgRuleName  -DestinationPortRange $nsgRuleDestinationPortRange.split(";") -Verbose | 
        Set-AzNetworkSecurityGroup -Verbose
