### ISSUE TITLE
ARM: `azure network traffic-manager profile endpoint create` throws Error

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2247]
```
 azure network traffic-manager profile endpoint create test-roman-group MyTM MyEndpoint eastus -y externalEndpoint -e myendptdns.azure.com -u Enabled -w 100 -p 322
info:    Executing command network traffic-manager profile endpoint create
+ Looking up the Traffic Manager profile "MyTM"
+ Updating Traffic Manager "MyTM"
error:   Error
info:    Error information has been recorded to C:\Users\roman.gromov\.azure\azure.err
error:   network traffic-manager profile endpoint create command failed

```

**Comment by romangromov** [comment]
Will fix,

@sreekanthbs please verify fix in our repo, `arm-fixes` branch

**Comment by sreekanthbs** [comment]
It is working fine now.
<pre>
<code>
azure network traffic-manager profile endpoint create armresgrpdnszone xplatTestTMPE xplatTestTMPEndPoint eastus -y externalEndpoint -e xplatTMPEndptdns1.azure.com -u Enabled -w 100 -p 200
info:    Executing command network traffic-manager profile endpoint create
+ Looking up the Traffic Manager profile "xplatTestTMPE"
+ Updating Traffic Manager "xplatTestTMPE"
+ Looking up the Traffic Manager profile "xplatTestTMPE"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpdnszone/providers/Microsoft.Network/traff
icManagerProfiles/xplatTestTMPE
data:    Name                            : xplatTestTMPE
data:    Type                            : Microsoft.Network/trafficManagerProfiles
data:    Location                        : global
data:    Status                          : Enabled
data:    Routing method                  : Weighted
data:    DNS name                        : xplattmpendptdns1
data:    Time to live                    : 300
data:    Monitoring protoco              : HTTP
data:    Monitoring path                 : /index.html
data:    Monitoring port                 : 80
data:    Endpoints:
data:    Name                  Location  Target                       Status   Weight  Priority  Type
data:    --------------------  --------  ---------------------------  -------  ------  --------  ----------------------------------------------------------
data:    xplatTestTMPEndPoint  East US   xplattmpendptdns1.azure.com  Enabled  100     200       Microsoft.Network/trafficManagerProfiles/externalEndpoints
info:    network traffic-manager profile endpoint create command OK
</code>
</pre>
