### ISSUE TITLE
ARM: Add VPN gateway creation commands

### ISSUE THREAD

**Issue by luisfcorreia** [Azure/azure-xplat-cli#2248]
Add whatever is necessary to implement these Powershell Azure 0.9.8 (in Resource Mode) commands:

New-AzureVirtualNetworkGateway
New-AzureVirtualNetworkGatewayConnection

**Comment by romangromov** [comment]
@luisfcorreia Vnet gateway CRUD commands in ARM already available in Xplat-CLI, and gateway connections is on the road

**Comment by romangromov** [comment]
@luisfcorreia please let us know you are not blocked and able to use `VPN gateway` commands in Xplat-CLI. Please let me know if you have any other additional questions or close the issue

**Comment by luisfcorreia** [comment]
I'm not able to create the actual Connection as there is no command for that.

I have to use a template for that specific operation

**Comment by romangromov** [comment]
@luisfcorreia yes, `connection`-related commands are in progress, we are sorry for delay. Will respond here since it included

**Comment by romangromov** [comment]
@luisfcorreia `connection` CRUD commands now merged to dev branch, will be available in next xplat-cli release (0.9.12)

**Comment by luisfcorreia** [comment]
great, will test soon
