### ISSUE TITLE
ARM: 'azure network gateway vnet create' throws error

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2249]
```
>azure network gateway vnet create -g test-roman-group -n TestGateway -l eastasia -y RouteBased -p IPforGateway -m VnetForGateway1 -e GatewaySubnet -a 10.0.0.11 -b t
rue -t tag1=val1
info:    Executing command network gateway vnet create
+ Looking up the public ip "IPforGateway"
+ Looking up the subnet "GatewaySubnet"
+ Looking up virtual network gateway "TestGateway"
+ Creating virtual network gateway "TestGateway"
error:   Virtual network gateway's Enable BGP property cannot be set for non express route gateway /subscriptions/5893435f-6990-4bb3-bebb-b12f3535f990/resourceGroups/test-roman-group/providers/Microsoft.Network/virtualN
etworkGateways/TestGateway
info:    Error information has been recorded to C:\Users\roman.gromov\.azure\azure.err
error:   network gateway vnet create command failed
```

**Comment by romangromov** [comment]
Will fix,

@sreekanthbs please verify fix in our repo, `arm-fixes` branch. Comment: `enable-bgp` should be `false` by default, so you have to update related test case.

+@yugangw-msft for visibility

**Comment by sreekanthbs** [comment]
@romangromov yes with enable-bgp as false its working.
But sometime its giving error for connect Etimedout
![image](https://cloud.githubusercontent.com/assets/11171941/10846184/9a5250ce-7f33-11e5-87aa-cb1f959c7f37.png)

**Comment by romangromov** [comment]
About `Etimedout` - it's external, reported, no updated about this

**Comment by sreekanthbs** [comment]
@romangromov With Enablebgp as true we are still getting the same issue
<pre>
<code>
C:\Oct\30Oct\Arm-Fixes\azure-xplat-cli-arm-fixes>node bin/azure network gateway vnet create -g xplatTestGroupVnetGateway25637 -n xplatTestvpngateway2050 -l eastus -y
RouteBased -p xplatTestIpGateway9052 -m xplatTestVnetGateway9921 -e GatewaySubnet -a 10.0.0.11 -b true
info:    Executing command network gateway vnet create
+ Looking up the public ip "xplatTestIpGateway9052"
+ Looking up the subnet "GatewaySubnet"
+ Looking up virtual network gateway "xplatTestvpngateway2050"
+ Creating virtual network gateway "xplatTestvpngateway2050"
error:   Virtual network gateway's Enable BGP property cannot be set for non express route gateway /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/
xplatTestGroupVnetGateway25637/providers/Microsoft.Network/virtualNetworkGateways/xplatTestvpngateway2050
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network gateway vnet create command failed
</code>
</pre>

**Comment by romangromov** [comment]
@sreekanthbs because of `Enable BGP property cannot be set for non express route gateway`. Maybe  we need to choose another type for this gateway?
