### ISSUE TITLE
ARM : network application-gateway commands are very long running

### ISSUE THREAD

**Issue by sreekanthbs** [Azure/azure-xplat-cli#2250]
Most of the app-gateway commands run for 20 or more minutes.
Even after one command complete we need to wait for 10-15 mins before running another command otherwise error comes - Another operation on this resource is in progress.

![app-gatewayissue tmp](https://cloud.githubusercontent.com/assets/11171941/10849775/5167651a-7f48-11e5-8c57-8a5ad73a95f8.PNG)

**Comment by romangromov** [comment]
Anyway, this is `external` for Xplat-CLI

**Comment by bingosummer** [comment]
Does Xplat-CLI has `network application-gateway` command in ARM mode?
I can only find the command in ASM mode.

**Comment by romangromov** [comment]
@bingosummer not yet, it's on the road.
+@MikhailTryakhov who owns `network application-gateway` in `ARM`: when we can expect mentioned commands to be merged?

**Comment by MikhailTryakhov** [comment]
@bingosummer it's on review now - will be in next release (I hope)
@sreekanthbs please move this issue to another repo.
@romangromov  thank you, we still wait for review

**Comment by squillace** [comment]
I'm looking at 0.9.13, and it's not there. where is this? @MikhailTryakhov

**Comment by sreekanthbs** [comment]
@MikhailTryakhov Moving this issue to MSOpentech repo. Reference to the issue 
https://github.com/MSOpenTech/azure-xplat-cli/issues/560
