### ISSUE TITLE
ARM: network lb frontend-ip create with  -b, --subnet-id giving error but provisioning state is succeeded

### ISSUE THREAD

**Issue by sreekanthbs** [Azure/azure-xplat-cli#2262]
ARM network lb frontend-ip create with -b, subnet-id, as well as -e, --subnet-name and  -m, --vnet-name without --json option is giving some error message but the provisioning state is Succeeded.
It created lb frontend-ip when we checking frontend-ip list. 
When we execute the same commands with --json it is not giving any error messages.

Identified this issue in release-0.9.11 branch.
![image](https://cloud.githubusercontent.com/assets/11171941/10934887/90b30bf2-8308-11e5-9a29-98d5db559f27.png)

![image](https://cloud.githubusercontent.com/assets/11171941/10934915/b300dfa4-8308-11e5-8629-83156b4cbbb8.png)

**Comment by romangromov** [comment]
@sreekanthbs I will take a look into this

**Comment by romangromov** [comment]
@sreekanthbs please verify fix in our repo, `arm-lb-fip-fix` branch

**Comment by sreekanthbs** [comment]
@romangromov verified in arm-lb-fip-fix with all options and it is working fine.
