### ISSUE TITLE
Resizing Azure VM throws exception about boot diagnostics

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2263]
I'm trying to resize an Azure VM, using Resource Manager (ARM) mode, and I'm getting an error about boot diagnostics. What might cause this?

<img width="753" alt="screen shot 2015-11-04 at 12 25 16 pm" src="https://cloud.githubusercontent.com/assets/466713/10950933/534c3efa-82ef-11e5-8186-09ae90e780c4.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by huangpf** [comment]
@pcgeek86 May I know what's the version of your CLI? The new release ```0.9.11``` shall have this fixed.

**Comment by pcgeek86** [comment]
@huangpf Interesting, I re-installed xPlat CLI the other day in preparation for a demo, and must have inadvertently updated it. I just retried the command, and it worked correctly.

Thank you sir!

**closing as "fixed in 0.9.11**

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
