### ISSUE TITLE
Wrong graph end point for AzureChinaCloud

### ISSUE THREAD

**Issue by amanda0411** [Azure/azure-xplat-cli#2268]
Hi 
I see that the value of "activeDirectoryGraphResourceId" for "AzureChinaCloud" is "https://graph.windows.net/" in file envrionment.js. Actually, the value for AzureChinaCloud should be "http://graph.chinacloudapi.cn". Could you have a look? :)

**Comment by yugangw-msft** [comment]
fixed it
