### ISSUE TITLE
azure service show --json <servicename> doesn't show PaaS role IPs

### ISSUE THREAD

**Issue by mohitarora** [Azure/azure-xplat-cli#2274]
When I run azure service show --json <servicename> it doesn't show the detailed information. No information about instances and deployments of cloudservice is shown,

**Comment by eduardkoller** [comment]
@amarzavery can you please take a look? It would be nice to show public IP and info about roles/instances (similarly to the portal)

**Comment by amarzavery** [comment]
@eduardkoller - The code was calling the get() method instead of getDetailed(). Now, if the user uses the command with --json option, he/she should be able to see the deployment info.
Based on the REST API doc over here: https://msdn.microsoft.com/library/azure/ee460806.aspx
