### ISSUE TITLE
0.9.11 xPlat CLI :: azure location list --json outputs comma-separated string for locations

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2275]
I think that it would be better to output a JSON array for locations, instead of a comma-separated string. See screenshot.

<img width="759" alt="screen shot 2015-11-10 at 10 32 00 am" src="https://cloud.githubusercontent.com/assets/466713/11068341/7c36fe8a-8796-11e5-9ca4-b86030a884dc.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by romangromov** [comment]
+1

**Comment by amarzavery** [comment]
This is what the server sends currently. The intention is to stay close to the wire so the cmd does not break due to server side changes.
Roping in Vivek from the ARM team to comment on this.

@vivsriaus - What are your thoughts on this?

**Comment by pcgeek86** [comment]
Thanks for the explanation @amarzavery. My suggestion would be to update the REST API. 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by ahmetalpbalkan** [comment]
@amarzavery I reported this long time ago. My thoughts: #2021, #2050.

**Comment by yugangw-msft** [comment]
@pcgeek86, with the fix to #2021, this bug should not reproduce because it is gone. The output of "provider show" has already used the array format. 
Let me know if you have any other comments/suggestions

![image](https://cloud.githubusercontent.com/assets/6014209/11479747/74fe988c-9748-11e5-867c-9865adf22c4e.png)

**Comment by pcgeek86** [comment]
@yugangw-msft This ticket is in regards to `azure location list`, not `azure provider show`. The two commands provide two different perspectives.

1. Someone wants to know the locations that a specific service (Resource Provider) is supported in (`azure provider show ...`).
2. Someone wants to know all of the Azure locations globally (`azure location list`)

This ticket pertains to item #2.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by yugangw-msft** [comment]
@pcgeek86, yes, this is what we are heading to.  The PR #2327 will address the item 2 you mentioned, which is to display all global locations available to the selected subscription. Like Ahmet mentioned in #2021, the new "location list" command will display the system name as well, which is required in some resources cmdlets.
The current version of "location list" does the same of "provider list/show", which is plain redundant.

Let me know if we are not on the same page.

**Comment by pcgeek86** [comment]
@yugangw-msft Thanks -- I will check out the new version when it is released.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
