### ISSUE TITLE
ARM: 'network express-route provider list' should output comma separated bandwidth

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2281]
As per Amit Srivastava <amsriva@microsoft.com>:

>In CLI when I do a ‘azure network express-route provider list’ the peering location is comma separated but the bandwidth is shown as a range. Exact bandwidth details should be shown as a comma separated list. 50Mbps, 100Mbps, 200Mbps etc.
Could you please get this fixed?

**Comment by romangromov** [comment]
Will fix

**Comment by romangromov** [comment]
+@sreekanthbs to verify fix

**Comment by sreekanthbs** [comment]
@romangromov  Its working fine now , bandwidth details are getting displayed  as a comma separated list. 50Mbps, 100Mbps, 200Mbps etc.

**Comment by romangromov** [comment]
It's done, closing issue
