### ISSUE TITLE
Built-in help for "azure role" is messy

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2283]
Most of the Azure xPlat CLI commands provide easy-to-consume, structured, built-in help. The `azure role` command provides a bunch of examples that cause the output to become extremely long, and very messy. This should be fixed up, to be more consistent with the other Azure xPlat commands.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by amarzavery** [comment]
The examples were provided in the help to make the users better understand the usage.
@namratab - From the Authorization team should be able to give more context for this approach.

**Comment by pcgeek86** [comment]
Thanks @amarzavery for the response. While I appreciate the examples, I think the documentation should be more easy to understand.

Look at all the other commands under Azure xPlat CLI. They clearly list out (one command per line) the sub-commands, but the `azure role` command does not. Examples are fine, but they should be provided under a different context.

This looks clean and readable:

![image](https://cloud.githubusercontent.com/assets/466713/11226699/c3892ecc-8d3e-11e5-97ae-3a0fe7863a71.png)

This does **not** look clean and readable:

![image](https://cloud.githubusercontent.com/assets/466713/11226798/6feb5fa0-8d3f-11e5-9bcb-d688e0b5662f.png)


Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by namratab** [comment]
Thanks for the feedback, @pcgeek86 .
From what I remember, there wasn't any separate 'context' for xplat commands (similar to the Description, Syntax, Examples sections that are present in PowerShell help documentation) where we could provide a detailed (greater than one-line) summary and provide examples. 
@amarzavery I can sync with you to see how this can be improved.

**Comment by pcgeek86** [comment]
@namratab Thanks for the response. I guess I wasn't suggesting that there was a separate "section" of help, but rather that the help should be organized a bit more. When I am viewing the `azure role` sub-commands, I shouldn't see all of the information that is specific to each sub-command. I should only see a summary of the sub-commands. When I enter a more specific sub-command (eg. `azure role show`), you can include more comprehensive documentation there.

The issue isn't that the information in there is unnecessary. It is simply a matter of how the information is organized. As I mentioned, you can use the other Azure xPlat command contexts as a reference for how to pretty things up.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by amarzavery** [comment]
closing this as it is a low priority issue.
