### ISSUE TITLE
New JSON parsing errors

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2285]
I have just started receiving error messages from the JSON output emitted by the Azure cross-platform CLI tool. I used to be able to use tools like `jsawk` to parse output, but now it's getting truncated, which is causing JSON parsing errors.

I'm using Mac OS X 10.11.1 with `azure` xPlat 0.9.11 on Bash 3.2.57(1)-release.

<img width="577" alt="screen shot 2015-11-14 at 12 04 07 pm" src="https://cloud.githubusercontent.com/assets/466713/11165275/e1f296ec-8ac7-11e5-8f04-331e92dd5841.png">

- I've tried both `azure account list --json` and `azure group list --json`
- I've tried both Terminal and iTerm2

NOTE: This isn't happening for other commands, such as `ls -lR;`.

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by pcgeek86** [comment]
1. I've downgraded to Azure xPlat CLI 0.9.10, which exhibited the same issue. I'm thinking it's not a fault of the tool itself.
2. I've also tried `zsh` instead of `bash` on Mac OS X. The behavior is the same there.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by stuartpreston** [comment]
I was able to repro this on OSX when I am using a binstub that points at the version of Node in my path (5.0.0 in my case). If using the Azure-cli downloadable package that bundles v0.12.7 and points the binstub at it then I don't have the issue described.

It looks like a 64KB limit is being hit somewhere that isn't being hit when redirecting stdout, when using Node 5.0.0 on OSX at least...

![2015-11-26_19-23-16](https://cloud.githubusercontent.com/assets/6384654/11429689/4b081b0c-9473-11e5-870d-5cd6e0b58211.png)

NB: On Linux where you are forced to use the npm route, I don't have the issue at all. (tested on Ubuntu 15.04 with Node 5.0.0)

**Comment by pcgeek86** [comment]
@yugangw-msft @devigned Any thoughts on this, folks? It's not just me. I'd prefer to have xPlat CLI use the installed version of Node.js, instead of installing a local copy of Node.js just for xPlat CLI.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by yugangw-msft** [comment]
@pcgeek86, i have not looked this issue in detail, but if it is because you used node 4+ version, my suggestion is to stay with 0.12.x, unless you do have the need to use newer version
Azure-cli doesn't work with node 4.0 and 5.0 very well, mainly because of the key input bug (https://github.com/nodejs/node/issues/2996). The fix went in with 5.1.0, and i plan to give another try this month to sort out the rest issues. Once it is good, I will post updates, and will also let installer to package in the new executable

**Comment by devigned** [comment]
@pcgeek86 I don't think it's the version of node. I was able to replicate with node 5.1.

**Comment by pcgeek86** [comment]
@devigned When @stuartpreston pointed out that the packaged version (included with the azure-cli DMG package) of Nodejs worked fine, and that he was able to reproduce it by installing the latest version of Nodejs, I think we kind of nailed down that it's a problem with the newer version of Nodejs. Wouldn't you agree? I think it works fine on old versions of Nodejs, but breaks with the newest versions.

Your reproduction matches this.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by devigned** [comment]
I believe I misunderstood. I stand corrected.

**Comment by pcgeek86** [comment]
@yugangw-msft Thank you for resolving this bug!!! I'm hoping to use the latest version of Node.js to run Azure xPlat.
