### ISSUE TITLE
Issue with login when specific version of xplat cli is installed

### ISSUE THREAD

**Issue by greenmang0** [Azure/azure-xplat-cli#2294]
```
[~] $ sudo npm install azure-cli@0.9.8 -g
[~] $ azure --version
0.9.8 (node: 4.1.0)
[~] $ azure login
error:   Cannot find module '../util/profile/account'
info:    Error information has been recorded to /Users/abhishek/.azure/azure.err
```

Works with a latest version.

**Comment by amarzavery** [comment]
As you said azure login works with the latest version. Then, is there a reason to specifically use 0.9.8 ?

**Comment by greenmang0** [comment]
@amarzavery, Yes since I do not update packages (especially third party) on production unless required.

**Comment by amarzavery** [comment]
@greenmang0 - Can you post the details of the azure.err file? If you installed via npm  ```npm install -g azure-cli``` then it could be a streamline issue. If you remove the .streamline file under the User's home profile directory `~` then most likely this will be fixed.

That being said, we cannot publish a patch to the same version 0.9.8 of azure-cli to npm. I don't think this is possible via npm. I understand it is a production system. However, upgrading to the latest package would be a cleaner and a safer approach.

**Comment by greenmang0** [comment]
@amarzavery, removal of `~/.streamline` did the trick, thanks.
