### ISSUE TITLE
ASM: 'network traffic-manager profile endpoint create/set' ignores Status option

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2309]
```
azure network traffic-manager profile endpoint set MyTM MyCoolEP -u Disabled
info:    Executing command network traffic-manager profile endpoint set
+ Looking up the Traffic Manager profile "MyTM"
+ Looking up the Traffic Manager definition "MyTM"
+ Updating endpoint "MyCoolEP" for Traffic Manager profile "MyTM"
+ Looking up the Traffic Manager profile "MyTM"
+ Looking up the Traffic Manager definition "MyTM"
data:    Name                            : MyTM
data:    Domain name                     : mytmagain.trafficmanager.net
data:    Status                          : Enabled
data:    TTL                             : 30
data:    Load balancing method           : Performance
data:    Monitor status                  : Degraded
data:    Monitors:
data:      Interval in seconds           : 30
data:      Timeout in seconds            : 10
data:      Tolerated number of failures  : 3
data:      Protocol                      : HTTPS
data:      Port                          : 30
data:      Verb                          : GET
data:      Relative path                 : /index
data:      Expected status code          : 200
data:    Endpoints:
data:      Domain name                   : mycoolep
data:      Status                        : Enabled
data:      Type                          : Any
data:      Location                      : West US
data:      Weight                        : 1
info:    network traffic-manager profile endpoint set command OK
```

**Comment by romangromov** [comment]
Will fix

**Comment by romangromov** [comment]
Just for reference https://github.com/Azure/azure-xplat-cli/pull/2306

**Comment by sreekanthbs** [comment]
@romangromov yes its working fine now.Verified for both create & set its taking the status option now.
<pre>
<code>
C:\Nov\20Nov\azure-xplat-cli-asm-tm-fixes>node bin/azure network traffic-manager profile endpoint create ClitmpTest1 CliServiceTest1.cloudapp.net CloudService -u Disa
bled
info:    Executing command network traffic-manager profile endpoint create
+ Looking up the Traffic Manager profile "ClitmpTest1"
+ Looking up the Traffic Manager definition "ClitmpTest1"
+ Creating endpoint CliServiceTest1.cloudapp.net for Traffic Manager profile "ClitmpTest1"
+ Looking up the Traffic Manager profile "ClitmpTest1"
+ Looking up the Traffic Manager definition "ClitmpTest1"
data:    Name                            : ClitmpTest1
data:    Domain name                     : CliDomTest1.trafficmanager.net
data:    Status                          : Enabled
data:    TTL                             : 200
data:    Load balancing method           : Failover
data:    Monitor status                  : Inactive
data:    Monitors:
data:    Verb  Protocol  Port  Relative path  Expected status code  Interval, seconds  Timeout, seconds  Tolerated number of failures
data:    ----  --------  ----  -------------  --------------------  -----------------  ----------------  ----------------------------
data:    GET   HTTP      6550  /health.aspx   200                   30                 10                3
data:    Endpoints:
data:    Domain name                   Location   Status    Type          Monitor status  Weight
data:    ----------------------------  ---------  --------  ------------  --------------  ------
data:    cliservicetest1.cloudapp.net  undefined  Disabled  CloudService  Disabled        1
info:    network traffic-manager profile endpoint create command OK


C:\Nov\20Nov\azure-xplat-cli-asm-tm-fixes>node bin/azure network traffic-manager profile endpoint set ClitmpTest1 CliServiceTest1.cloudapp.net -u Enabled
info:    Executing command network traffic-manager profile endpoint set
+ Looking up the Traffic Manager profile "ClitmpTest1"
+ Looking up the Traffic Manager definition "ClitmpTest1"
+ Updating endpoint "CliServiceTest1.cloudapp.net" for Traffic Manager profile "ClitmpTest1"
+ Looking up the Traffic Manager profile "ClitmpTest1"
+ Looking up the Traffic Manager definition "ClitmpTest1"
data:    Name                            : ClitmpTest1
data:    Domain name                     : CliDomTest1.trafficmanager.net
data:    Status                          : Enabled
data:    TTL                             : 200
data:    Load balancing method           : Failover
data:    Monitor status                  : CheckingEndpoints
data:    Monitors:
data:    Verb  Protocol  Port  Relative path  Expected status code  Interval, seconds  Timeout, seconds  Tolerated number of failures
data:    ----  --------  ----  -------------  --------------------  -----------------  ----------------  ----------------------------
data:    GET   HTTP      6550  /health.aspx   200                   30                 10                3
data:    Endpoints:
data:    Domain name                   Location   Status   Type          Monitor status    Weight
data:    ----------------------------  ---------  -------  ------------  ----------------  ------
data:    cliservicetest1.cloudapp.net  undefined  Enabled  CloudService  CheckingEndpoint  1
info:    network traffic-manager profile endpoint set command OK
</code>
</pre>

**Comment by romangromov** [comment]
@sreekanthbs good, thanx!
