### ISSUE TITLE
Urgent: Need ability to create Azure AD Users

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2311]
The Azure xPlat CLI Tool currently does not support the ability to create Azure Active Directory (AAD) User Accounts. The only sub-commands available are `show` and `list`. 

We have an urgent need to create Azure AD user accounts through Azure xPlat CLI.

![image](https://cloud.githubusercontent.com/assets/466713/11307707/264fc6c6-8f77-11e5-9ac7-46f2f9309b5a.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by amarzavery** [comment]
@namratab - Authorization team would be in a better position to comment on that.

**Comment by amarzavery** [comment]
@shuagarw - Authorization team any ideas?

**Comment by alexandreweiss** [comment]
Also created issue https://github.com/Azure/azure-xplat-cli/issues/2336 for ability to create groups
Thanks !
Alex

**Comment by yugangw-msft** [comment]
@vivsriaus , your team still owns the graph cmdlets?

**Comment by amarzavery** [comment]
This will be a part of July 2016 release.
