### ISSUE TITLE
Azure Group Deployment JSON Output broken

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-xplat-cli#2313]
https://gist.github.com/3d693f78a9d1ebd7ca3d

That's the output of `azure group deployment show -g <group> <deploy-id>`.

**Comment by amarzavery** [comment]
@vivsriaus - Can you please take a look at this?

**Comment by stuart-shelton-hp** [comment]
It looks as if, for certain operations, the CLI with the '--json' option is only outputting values and not keys:

```bash
$ azure group create --json -n "<name>" --location "<location>" --tags "<kv-pairs>"
"/subscriptions/<uuid>/resourceGroups/<name>"
"<name>"
"<location>"
"Succeeded"
{}
{}
```

(Tested with azure-cli versions 0.9.10 && 0.9.12)

**Comment by ravbhatnagar** [comment]
Will be fixed in the March release of CLI.

**Comment by ravbhatnagar** [comment]
Fixed in March release
