### ISSUE TITLE
ASM: "azure vm image list --json" works wrong

### ISSUE THREAD

**Issue by mumrik58** [Azure/azure-xplat-cli#2321]
When I called "azure vm image list", it works.

```
$ azure vm image list
info:    Executing command vm image list
+ Fetching VM images

### a table of vm images ###

info:    vm image list command OK
```

But when I called "azure vm image list --json", it returns broken json.
It seems to become interrupted on the way. 

here is the snapshots.

![image](https://cloud.githubusercontent.com/assets/2739701/11581579/d9abaebe-9a86-11e5-830d-f27111455b3b.png)

I had a interrupted json.

![image](https://cloud.githubusercontent.com/assets/2739701/11581847/2cf0cad4-9a8a-11e5-9a20-3f7870e63075.png)

please support me.
I am using azure-cli@0.9.9.
I tried v0.9.12, but It has not improved it.

thanks.

**Comment by sauryadas** [comment]
Can you please elaborate on what you mean by "It seems to become interrupted on the way."? provide a snapshot maybe? .. I tried to do a repro and had no issues viewing the complete json.

**Comment by mumrik58** [comment]
I added the snapshots. >sauryadas
thanks.

**Comment by huangpf** [comment]
@mumrik58 Is the ```WebLogic``` image shown in your screenshot a user image created/captured by your subscription? I can't seem to find this one under mine, and I only saw this one ```c290a6b031d841e09f2da759bbabe71f__WebLogic-Linux-6-12c-2014```.

BTW, is it feasible for you to share the result of ```vm image list -vv``` with us for further debugging?

And how about ```vm image show xxx --json``` for the particular image that causes the interruption problem?

**Comment by mumrik58** [comment]
@huangpf I didn't create ```the WebLogic``` image. 
Here is the result the execution of  "vm image show xxx --json".
```
root@fb0544a2d8f2:/# azure vm image show 0c0083a6d9a24f2d91800e52cad83950__Weblogic-10.3.6-EE-JDK-1.7.0_85-20151018-Win-GA --json       
{
  "category": "Public",
  "label": "\"Oracle WebLogic Server 11g Enterprise Edition on Windows Server 2008 R2\"",
  "location": [
    "East Asia",
    "Southeast Asia",
    "Australia East",
    "Australia Southeast",
    "Brazil South",
    "North Europe",
    "West Europe",
    "Central India",
    "South India",
    "West India",
    "Japan East",
    "Japan West",
    "Central US",
    "East US",
    "East US 2",
    "North Central US",
    "South Central US",
    "West US"
  ],
  "logicalSizeInGB": 128,
  "name": "0c0083a6d9a24f2d91800e52cad83950__Weblogic-10.3.6-EE-JDK-1.7.0_85-20151018-Win-GA",
  "operatingSystemType": "Windows",
  "eula": "http://go.microsoft.com/fwlink/?LinkID=321682",
  "description": "[Oracle WebLogic Server|http://www.oracle.com/weblogicserver|_blank] 11g Enterprise Edition (10.3.6) is a leading Java application server for modern data centers. It takes full advantage of the latest hardware architectures including 64-bit addressable memory, multi-core computing systems and high-speed networks. Minimum recommended virtual machine size for this image is [Standard_D12|http://go.microsoft.com/fwlink/?LinkID=309169|_blank]. [Learn More|http://msdn.microsoft.com/en-us/library/dn466428.aspx|_blank]",
  "imageFamily": "Oracle WebLogic Server 11g Enterprise Edition on Windows Server 2008 R2",
  "publishedDate": "2015-10-18T00:00:00.000Z",
  "isPremium": true,
  "iconUri": "OracleWeblogic11_100.png",
  "privacyUri": "http://go.microsoft.com/fwlink/?LinkId=321693",
  "recommendedVMSize": "Standard_D12",
  "publisherName": "Microsoft",
  "smallIconUri": "OracleWeblogic11_45.png",
  "iOType": "Standard_LRS"
}
``` 

And the result of  ```vm image list -vv``` is also interrupted.
```
root@fb0544a2d8f2:/# azure vm image list -vv
info:    Executing command vm image list
verbose: Fetching VM images
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { x-ms-version: '2015-04-01', user-agent: 'WindowsAzureXplatCLI/0.9.9' },
silly:       url: 'https://management.core.windows.net/8c81875e-a7d7-4451-9a12-b1e38aa3748b/services/images'
silly:   }
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { x-ms-version: '2015-04-01', user-agent: 'WindowsAzureXplatCLI/0.9.9' },
silly:       url: 'https://management.core.windows.net/8c81875e-a7d7-4451-9a12-b1e38aa3748b/services/vmimages'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           content-length: '176988',
silly:           content-type: 'application/xml; charset=utf-8',
silly:           server: '1.0.6198.292 (rd_rdfe_stable.151121-1554) Microsoft-HTTPAPI/2.0',
silly:           x-ms-servedbyregion: 'ussouth3',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           x-ms-request-id: 'f0398b5c98ce3aee86b6f0e7f32bdff0',
silly:           date: 'Sun, 06 Dec 2015 15:08:53 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '<VMImages xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">

### shorten (because of too long XML response) ###

<Name>2b171e93f07c4903bcad35bda10acf22__CoreOS-Beta-668.3.0</Name><OS>Linux</OS><Description>The Beta channel consists of promoted Alpha releases. Mix a few Beta machines into your production clusters to catch any bugs specific to your hardware or configuration.</Description><ImageFamily>CoreOS Beta</ImageFamily><root@fb0544a2d8f2:/#
```

thanks.

**Comment by huangpf** [comment]
@mumrik58 
I can't reproduce the error on my dev machine (Windows + node v0.12.7), but from your first and second sets of logs, it seems the interruption occurred at different item of the list. Also, if you can ```show``` the image that was broken from the ```list``` command, it means that that format of the response has no problem.

So, I would guess it might be because the CLI installed on your system with the network setting etc. can't handle the large amount of request/response? @yugangw-msft @amarzavery  Any thoughts?

First : ```c290a6b031d841e09f2da759bbabe71f__WebLogic-Linux-6-12c-2014```

![image](https://cloud.githubusercontent.com/assets/2739701/11581847/2cf0cad4-9a8a-11e5-9a20-3f7870e63075.png)

Second : ```2b171e93f07c4903bcad35bda10acf22__CoreOS-Beta-668.3.0```

<Name>2b171e93f07c4903bcad35bda10acf22__CoreOS-Beta-668.3.0</Name><OS>Linux</OS><Description>The Beta channel consists of promoted Alpha releases. Mix a few Beta machines into your production clusters to catch any bugs specific to your hardware or configuration.</Description><ImageFamily>CoreOS Beta</ImageFamily><root@fb0544a2d8f2:/#
```

**Comment by huangpf** [comment]
Close for now. Please reopen if reproduced.
