### ISSUE TITLE
ARM: equivalent to

### ISSUE THREAD

**Issue by sachamicrosoft** [Azure/azure-xplat-cli#2324]
Is there a Resize-AzureVNetGateway command implemented for the CLI to upgrade VPN Gateways to the High-Performance version? 

IE: equivalent to this PS command: https://msdn.microsoft.com/en-us/library/azure/mt270352.aspx?

**Comment by romangromov** [comment]
@sachamicrosoft the `HighPerformance` is SKU type in `ASM` mode. There is special command in `ASM` to resize an existing Vnet Gateway *azure network vpn-gateway resize*:

```
azure network vpn-gateway resize -h
help:    Resize a virtual network gateway
help:
help:    Usage: network vpn-gateway resize [options] <vnet-name> <sku>
help:
help:    Options:
help:      -h, --help                         output usage information
help:      -v, --verbose                      use verbose output
help:      -vv                                more verbose with debug output
help:      --json                             use json output
help:      -n, --vnet-name <vnet-name>        the name of the virtual network
help:      -k, --sku <sku>                    the SKU that the existing gateway will be resized to,
help:             valid values are [Default or HighPerformance]
help:      -s, --subscription <subscription>  the subscription identifier
help:
help:    Current Mode: asm (Azure Service Management)
```

Example:
`azure network vpn-gateway resize vnet1 HighPerformance`

**Comment by romangromov** [comment]
UPD: `azure network vpn-gateway resize` is broken on server end, related issue https://github.com/MSOpenTech/azure-xplat-cli/issues/244

**Comment by romangromov** [comment]
@amarzavery this can be closed
