### ISSUE TITLE
macos: create a homebrew recipe

### ISSUE THREAD

**Issue by squillace** [Azure/azure-xplat-cli#2334]
There's no reason not to support the default package manager of mac dev. @devigned

**Comment by pcgeek86** [comment]
Big +1 for this

**Comment by squillace** [comment]
I'm +1ing my own issue. Just on principle.

**Comment by devigned** [comment]
+1 agreed. Perhaps, I'll do that this weekend.

**Comment by yugangw-msft** [comment]
@devigned , @pcgeek86 @squillace 
I know nothing on homebew, one simple question here, if i use homebrew to install azure-cli, will that conflict with prior/later installations through npm, particularly the common "/use/local/bin/azure"?

**Comment by devigned** [comment]
```bash
brew update && brew install azure-cli 
```

Should do it :)

**Comment by pcgeek86** [comment]
@devigned Very nice. :)
