### ISSUE TITLE
Need ability to create Azure AD Groups

### ISSUE THREAD

**Issue by alexandreweiss** [Azure/azure-xplat-cli#2336]
The Azure xPlat CLI Tool currently does not support the ability to create Azure Active Directory (AAD) Groups. The only sub-commands available are  show  and  list and member list.
 
![xplat](https://cloud.githubusercontent.com/assets/15915851/11527054/e16d28d4-98de-11e5-8a3c-2b7bf27b2284.PNG)

We have a need to automate Azure AD group creation through Azure xPlat CLI to be able to apply RBAC through template just after deploying Azure Resource Group

Thanks
alweiss
MSFT Consultant

**Comment by alexandreweiss** [comment]
Issue 2311 also exists for Users https://github.com/Azure/azure-xplat-cli/issues/2311

**Comment by yugangw-msft** [comment]
@vivsriaus, does you team still own it?

**Comment by amarzavery** [comment]
This will be a part of the July 2016 release.
