### ISSUE TITLE
azure arm mode error

### ISSUE THREAD

**Issue by fbejarano** [Azure/azure-xplat-cli#2337]
Hi

I have azure 0.9.12 y nodejs v0.10.37

I want to create a new VM than I have created yesterday, and today, I can not create it because an error to add it to my Virtual Networt. Ok I have seen in MS doc that you can not add a vm to a Virtual Network if use de asm. Yesterday yes, today not OK...  I have done the change to the cli from asm to arm with login authentication, etc. OK. I have too many scripts to create new VMs with different things (cloudservices, storage accounts, etc) in an automatization way. I use different images to create different vm types. To use those images a need to know the storage account key but when I show de group resources that contains the storage account, it is there but when I want to list the keys of that storage account, it fails because the path is not the same:  **Microsoft.ClassicStorage/storageAccounts/oknstgcontrol000** is true path but the azure storage account key list command search **Microsoft.Storage/storageAccounts/oknstgcontrol000** ... How could I resolve this? All my scripts are invalid now???

```bash
$ azure group show Default-Storage-WestEurope | grep oknstgcontrol000
data:      Id      : /subscriptions/mysuscripcionhere/resourceGroups/Default-Storage-WestEurope/providers/Microsoft.ClassicStorage/storageAccounts/oknstgcontrol000
data:      Name    : oknstgcontrol000

$ azure storage account keys list -g 'Default-Storage-WestEurope' oknstgcontrol000
info:    Executing command storage account keys list
+ Getting storage account keys                                                 
error:   The Resource 'Microsoft.Storage/storageAccounts/oknstgcontrol000' under resource group 'Default-Storage-WestEurope' was not found.
info:    Error information has been recorded to /home/fbejarano/.azure/azure.err
error:   storage account keys list command failed
```

**Comment by yugangw-msft** [comment]
@fbejarano, I think the resource type of "Default-Storage-WestEurope" might not be what you expect, because it is Microsoft.ClassicStorage. Why the command of "azure storage account keys list" assumes the "Microsoft.Storage". Different things. Do you mean to use the "Default-Storage-WestEurope" type. @yaxia for further suggestions.

**Comment by fbejarano** [comment]
Default-Storage-WestEurope is a resource group, I know that the command assumes Microsoft.Storage but why it not assumes the differents Ids? If you have an infrastructure with a virtual network you can not add VMs to that network in asm and then if you change to arm you can not do operations to Classic??

**Comment by yaxia** [comment]
How about this work around: when you want to operate on a classic storage account in a script for the ARM mode, add `azure config mode asm` and add `azure config mode arm` after the storage account commends?

**Comment by yaxia** [comment]
Close it. @fbejarano Please feel free to reopen it if the work around doesn't work for you.
