### ISSUE TITLE
Role assignment failure for service principal object

### ISSUE THREAD

**Issue by anweiss** [Azure/azure-xplat-cli#2338]
I'm having an issue when executing an `azure role assignment create` command like so:

```sh
azure role assignment create --objectId <sp_id> -o Owner -c /subscriptions/<sub_id>/
```

The error is as follows:

```
Principals of type Application cannot validly be used in role assignments.
```

Using v0.11 of the CLI

**Comment by yugangw-msft** [comment]
@anweiss, if the service principal was freshly created, could you wait couple of minutes and try again. There is a known latency on propagating AAD graph object change to RBAC service

**Comment by anweiss** [comment]
Thanks @yugangw-msft. Indeed that was the issue.
