### ISSUE TITLE
Azure login not persistent 

### ISSUE THREAD

**Issue by AyeJeigh** [Azure/azure-xplat-cli#2339]
Hello,

For some reason, I can't get my azure-cli login to be persistent.  When I get into work in the morning, I have to manually run "azure login" or "azure account import" and it works for the rest of the day.  However, the next morning none of my commands work and I get this error:

"error:   We don't have a valid access token. Please run "azure login" again."

I've tried clearing my creds like so:

azure logout me@website.com
azure account clear -q
azure login
azure account set 'Name of My Account'

I'm running version 0.9.12 on Ubuntu 15.04

For the time being, I set up a cron job to import my cert every morning.  Does anyone have any ideas?

**Comment by yugangw-msft** [comment]
@AyeJeigh if you used MSA account such as "live id", the token your got is valid for 12 hours. So you need to login ever day.
If you like longer life span, I suggest you create org-id from your subscription, a one time setup to create a user like "Aye@ayehotmail.onmicrosoft.com", then logging using that will give you token lasting up to till 90 days. 
Hope this help.

**Comment by AyeJeigh** [comment]
Thank you for your quick response yugangw,  I was thinking it had something to do with my account itself.  I appreciate you taking the time to help me out.

Thanks again!

**Comment by AyeJeigh** [comment]
One more thing Yugangw.  Does the token for a "live id" expire after 12 hours from login or 12 hours from last activity?

**Comment by yugangw-msft** [comment]
@AyeJeigh it is "from login". More accurately, login gets "access token" and "refresh token". The "access token" always expires after a hour, but with the "refresh token", the expired "access token" can be exchanged for a valid one automatically. The crucial part is the "refresh token" from a "live id" is only good for 12 hours. For org-id, the "refresh token", is good for 2 weeks, and can be automatically extended for another 2 weeks as long as it gets used once every 2 weeks. This can go on for up to 3 months.

**Comment by AyeJeigh** [comment]
Thank you for the valuable information @yugangw-msft
