### ISSUE TITLE
ARM 0.9.11 :: azure vm extension list-image-publishers should not have mandatory --location parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2341]
The `azure vm extension list-image-publishers` should not have mandatory `--location` parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by huangpf** [comment]
@pcgeek86 The parameter is required in the command, because it's currently required in the client library API, and it doesn't handle optional, default, or omitted ```location``` input in the command level yet.

**Comment by huangpf** [comment]
Given that we are triaging the overall issue in #2343, can we close this one? Thanks.

**Comment by pcgeek86** [comment]
@huangpf Sure, that makes sense to track it in #2343.
