### ISSUE TITLE
ARM 0.9.11 :: azure network nic list should not have mandatory --resource-group parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2342]
The `azure network nic list` command should not have a mandatory `--resource-group` parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by romangromov** [comment]
@pcgeek86 the ability to list all nics in subscription was presented only in latest swagger-based SDK for node. It's not possible to list all nics in 0.9.11. Currently, I'm working on moving Xplat-CLI networking commands to use swagger-based SDK.

FYI: @DeepakRajendranMsft

**Comment by romangromov** [comment]
@pcgeek86 `azure network` commands migrated to SDK from `autorest`, merged to `dev`, now `--resource-group` is optional where it is possible.

**Comment by yugangw-msft** [comment]
Closing. Fix will be in the upcoming release
