### ISSUE TITLE
Major design flaw in Azure VM Extensions interface

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2343]
The Azure VM Extensions interface suffers from the same, major design problem that the Azure VM Image Gallery interface has. This was reported months ago (by me), and supported by other, prominent members of the community, and ultimately hasn't seen any action.

In order to obtain an authoritative list of all VM Extensions, a user would have to call into the Azure Resource Manager (ARM) REST API **several hundred times**, for each Publisher, for each "Type," for each "Version," for each "Image."

https://github.com/Azure/azure-powershell/issues/691

<img width="793" alt="screen shot 2015-12-02 at 1 13 14 pm" src="https://cloud.githubusercontent.com/assets/466713/11544748/6c89f348-98f8-11e5-9082-00d24c75a385.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by huangpf** [comment]
@pcgeek86 The listed commands are mostly in line with the design of REST APIs.

+@sauryadas & @singhkay Maybe a smart ```quick-list``` method is what users want for both PS & CLI?

**Comment by ahmetalpbalkan** [comment]
+1 for this.

**Comment by pcgeek86** [comment]
@huangpf From an end user perspective, they don't care if the tool matches the REST APIs or not. This is not valid criteria to judge success against. Your software design goal should not be to "match the REST API."

Please talk to @kmouss and @squillace about this.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by huangpf** [comment]
@pcgeek86 
Thanks for the suggestion. We are not having the design goal to match the REST API, but rather it's this current REST API for listing images that is limiting our design goal. With that said, we are aware of this issue on both PS & CLI ends, and trying to come up with a suitable solutions. Please keep let us know the feedback, and we would also keep you posted. Thanks.

**Comment by squillace** [comment]
@huangpf +1. We need to have a client experience that is actually good. 

We can assert that the REST api should be fixed; that's one possiblity. We can assert that the client should do the looping for us; that's another possibility. 

Where the actual bug should be fixed is irrelevant to the customer, however, except insofar as roundtrips or performance is concerned. As any client is going to have to loop in order to do this with the current REST api, I'd assess how far out a new REST list api is going to take, and given that, fix with a simple quick-list api that does the looping for us, knowing in advance that it'll be pointless whenever the REST api is fixed. 

But you all will know what to do with the resources you have. It is clear, based on customer usage, that the original REST list api was deeply mistaken.

**Comment by squillace** [comment]
@johngossman so that I can gripe over the vacation.

**Comment by pcgeek86** [comment]
> "Where the actual bug should be fixed is irrelevant to the customer, however, except insofar as roundtrips or performance is concerned."

Perfectly stated, Ralph. *Perfectly.*

@huangpf I would recommend that your focus be on end user experience, instead of trying to make the front-end interface "match the REST API." I'm basically just repeating myself here, but I feel that it needs to be said, because there is clearly a lack of focus on the user experience.

**Should** the user have access to the raw API? Of course, so that they can handle fringe scenarios. However, the core focus for tooling should be on user experience. This isn't the first time I've heard the "match the REST API" argument used, and it isn't a valid argument. As an end user, no one cares what the back-end API looks like, except for those unfortunate enough to be coding directly against the REST interface. For Azure xPlat CLI, ARM PowerShell, and the C# SDK for Azure (and other SDKs), these details should be abstracted from the user.

As Ralph so keenly pointed out, the user doesn't care how the bug is fixed, except in that it severely impacts performance. Since the *reality* is that there is a *huge* performance impact here (I've crunched and published the numbers myself), the end customer actually *does* have a stake in the back-end API.

On that note: when can we see an improvement in this REST API? The old API should be deprecated, and be clearly communicated.

**Comment by huangpf** [comment]
The extension image cmdlets will be changed to ```vm extension-image list/show/list-publishers/list-versions```, which will be similar to the ```vm image``` pattern.

https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/Compute/ComputeManagement/Generated/VirtualMachineExtensionImageOperations.cs#L37

https://msdn.microsoft.com/en-us/library/mt150024.aspx

Note that the commands to adding/getting extensions to VMs remain the same, i.e. ```vm extension set/get ...```. The change is only about querying the source images of the extension published by different publishers that can be instantiated and then added to VMs, which is aligned with the current REST API, client library & PS cmdlet naming convention.

Related item: #2397

**Comment by pcgeek86** [comment]
@huangpf It seems like you're putting effort into side-stepping the issue, instead of fixing it.

Cheers,
Trevor Sullivan

**Comment by huangpf** [comment]
```list``` command will list all available ones, and the only parameter it takes is location.

```
azure vm extension-image list westus
info:    Executing command vm extension-image list
+ Getting virtual machine and/or extension image publishers (Location: "westus")
data:    Publisher                                             Type                                 Version           Location
data:    ----------------------------------------------------  -----------------------------------  ----------------  --------
data:    alertlogic                                            AlertLogicLM                         1.3.0.1           westus
data:    AlertLogic.Extension                                  AlertLogicLM                         1.3.0.0           westus
data:    AlertLogic.Extension                                  AlertLogicLM                         1.4.0.0           westus
data:    AlertLogic.Extension                                  AlertLogicLM                         1.9.0.0           westus
data:    AlertLogic.Extension                                  AlertLogicLM                         1.9.1.0           westus
data:    Chef.Bootstrap.WindowsAzure                           CentosChefClient                     11.12.4.2         westus
data:    Chef.Bootstrap.WindowsAzure                           CentosChefClient                     11.14.6.1         westus
data:    Chef.Bootstrap.WindowsAzure                           ChefClient                           11.10.4           westus
data:    Chef.Bootstrap.WindowsAzure                           ChefClient                           11.12.0.0         westus
data:    Chef.Bootstrap.WindowsAzure                           ChefClient                           11.18.6.2         westus
...
```

**Comment by huangpf** [comment]
@pcgeek86 
Users now can list all available ones and filter or process it on the console. Data query feature (like filtering) by the command itself needs to be decided alongside with the request on the PS side, re: Azure/azure-powershell#691.

**Comment by pcgeek86** [comment]
@huangpf Thanks, I understand now. I didn't see the `list` command by itself, when I first read your comment. I appreciate you pointing out my oversight.

Cheers,
Trevor Sullivan

**Comment by huangpf** [comment]
Close this issue for now, as the code has been checked in by PR #2398

```
Lists the virtual machines images
  vm image list [options] <location> <publisher> [offer] [sku]
```

Listing all images from a location:
```
azure vm extension-image list westus
info:    Executing command vm extension-image list
data:    Publisher                                             Type                                 Version           Location
data:    ----------------------------------------------------  -----------------------------------  ----------------  --------
data:    alertlogic                                            AlertLogicLM                         1.3.0.1           westus
data:    AlertLogic.Extension                                  AlertLogicLM                         1.3.0.0           westus
data:    AlertLogic.Extension                                  AlertLogicLM                         1.4.0.0           westus
data:    AlertLogic.Extension                                  AlertLogicLM                         1.9.0.0           westus
data:    AlertLogic.Extension                                  AlertLogicLM                         1.9.1.0           westus
data:    Chef.Bootstrap.WindowsAzure                           CentosChefClient                     11.12.4.2         westus
data:    Chef.Bootstrap.WindowsAzure                           CentosChefClient                     11.14.6.1         westus
data:    Chef.Bootstrap.WindowsAzure                           ChefClient                           11.10.4           westus
data:    Chef.Bootstrap.WindowsAzure                           ChefClient                           11.12.0.0         westus
data:    Chef.Bootstrap.WindowsAzure                           ChefClient                           11.18.6.2         westus
...
```

Listing all images from a location and publisher:
```
azure vm image list westus alertlogic
```

Listing all images from a location and publisher:
```
azure vm extension-image list westus alertlogic

data:    Publisher   Type          Version  Location
data:    ----------  ------------  -------  --------
data:    alertlogic  AlertLogicLM  1.3.0.1  westus
```

Listing all images from a location, publisher, and type:
```
azure vm extension-image list westus alertlogic AlertLogicLM

data:    Publisher   Type          Version  Location
data:    ----------  ------------  -------  --------
data:    alertlogic  AlertLogicLM  1.3.0.1  westus
```

**Comment by pcgeek86** [comment]
@huangpf Thanks, just to be sure, the `list` command also supports `--json` parameter?

Cheers,
Trevor Sullivan

**Comment by huangpf** [comment]
Yes, it's as follows:

```
azure vm extension-image list westus --json
[
  {
    "publisher": "alertlogic",
    "location": "westus",
    "typeName": "AlertLogicLM",
    "name": "1.3.0.1"
  },
  {
    "publisher": "AlertLogic.Extension",
    "location": "westus",
    "typeName": "AlertLogicLM",
    "name": "1.3.0.0"
  }, ...
```

**Comment by pcgeek86** [comment]
@huangpf Thanks, I'll keep an eye out for the next release.

**Comment by dukedougal** [comment]
So is there an ARM REST command to list/search VM images?

**Comment by huangpf** [comment]
@sauryadas Could you please help address @dukedougal's question? Thanks.
