### ISSUE TITLE
"azure resource move" doesn't support moving between different subscriptions

### ISSUE THREAD

**Issue by DavidKarlas** [Azure/azure-xplat-cli#2350]
I tried pretty much every combination of supplying --subscription in different places but all it seems to do is use it for both resources... Source and Destination so either SourceGroup reports error that it doesn't exist or Destination depending on which subscription I provide via --subscription...

/cc @vivsriaus because you implemented (https://github.com/Azure/azure-xplat-cli/pull/2181)

**Comment by vivsriaus** [comment]
@DavidKarlas Thanks for bringing this to our attention. Indeed, the resource move command was lacking the -destination-subscriptionId parameter. I've fixed this in this PR: https://github.com/Azure/azure-xplat-cli/pull/2355

I'll respond to this thread when this is merged and available in the upcoming Azure CLI release.

**Comment by amarzavery** [comment]
This fix is a part of release-0.9.13 https://github.com/Azure/azure-xplat-cli/releases/tag/v0.9.13-December2015
