### ISSUE TITLE
Downloading the publish profile for ARM Webapp

### ISSUE THREAD

**Issue by bhagyasri7** [Azure/azure-xplat-cli#2371]
Hello, I find the Azure CLI very helpful. I am looking for a way to download the publish profile for the webapp in CLI.

**Comment by ahmedelnably** [comment]
Hello bhagyasri7.
Thanks for reporting that, will try and find you the answer and follow up soon
Regards,
Ahmed

**Comment by ahmedelnably** [comment]
Hello @bhagyasri7 
You can now do that through CLI
Here is the article explaining that: http://aka.ms/webapp-cli
