### ISSUE TITLE
Blob snapshot functionality needed

### ISSUE THREAD

**Issue by caleteeter** [Azure/azure-xplat-cli#2377]
The cli does not have provisions for snapshotting blobs.  I know this was raised before but the issue was closed.  Is there an update on when this feature will be added?

**Comment by yugangw-msft** [comment]
@yaxia please comment

**Comment by yaxia** [comment]
Ack. I will update the when the plan is finalized.

**Comment by nbering** [comment]
Is there any update on this? I'm generally working with blobs from the Node API, but having snapshot support in the CLI would definitely help for diagnostic/operational purposes.

**Comment by yaxia** [comment]
ETA of the fix: June release

**Comment by yaxia** [comment]
We have added `azure storage blob snapshot` in the 0.10.1. Please take a try.
