### ISSUE TITLE
0.9.13 ARM :: Error message about Boot Diagnostics Extension on Premium Storage

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2380]
The error message about Boot Diagnostics not being supported on Premium Storage doesn't explicitly point the user to use the `--boot-diagnostics-storage-uri` parameter. It isn't immediately clear what the correct course of action is, but rather only the fact that Premium Storage accounts don't support Boot Diagnostics.

<img width="1680" alt="screen shot 2015-12-14 at 9 12 23 am" src="https://cloud.githubusercontent.com/assets/466713/11787976/cea87ea8-a24b-11e5-9985-11e39ee99b48.png">
<img width="1680" alt="screen shot 2015-12-14 at 8 44 14 am" src="https://cloud.githubusercontent.com/assets/466713/11787977/ceaab056-a24b-11e5-87fa-17a335bc9f71.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by huangpf** [comment]
+@sauryadas
I think the fix (or wait) shall depend on the timeline of having premium support boot diagnostics.

**Comment by pcgeek86** [comment]
@huangpf If you talk to Sirius, I think the "solution" for VMs on Premium Storage is to specify a Standard Storage Account. As best I can tell, Premium Storage Accounts are specifically designed for Virtual Machines, and as such, I don't see any plans for them to implement block or append blobs.

Let me know what he says. For the foreseeable future though, I think users should probably be directed to use the `--boot-diagnostics-storage` parameter.

Cheers,
Trevor Sullivan

**Comment by huangpf** [comment]
@pcgeek86 Thanks for the feedback. We would triage and consider it.

**Comment by huangpf** [comment]
Fixed by https://github.com/Azure/azure-xplat-cli/pull/2398

Will be available in the incoming release. Close for now.
