### ISSUE TITLE
Implement session persistence option in network loadbalancer rule create and set

### ISSUE THREAD

**Issue by colrack** [Azure/azure-xplat-cli#2382]
Please implement the ability to change session persistence on a load balancer rule.

This is currently possible from the new Azure Portal and from Resource Explorer at resources.azure.com (see attached files). As for now it seems to be an implemented feature in Azure/azure-sdk-for-node.
Parameter name is `loadDistribution` and possible values are `Default` , `SourceIP` and `SourceIPProtocol`.

The option would be something like `--session-persistence` or `--load-distribution` and as an example the resulting cmd would be like `azure network lb rule create --session-persistence sourceip` .

Thanks!

<img width="280" alt="azure_lb_session_persistence" src="https://cloud.githubusercontent.com/assets/2183293/11811159/1cbf7806-a334-11e5-9fa6-6636fe5865f7.png">
<img width="1116" alt="azure_resources_lb" src="https://cloud.githubusercontent.com/assets/2183293/11811158/1c8f978a-a334-11e5-9693-05b9d0c93a49.png">

**Comment by romangromov** [comment]
@colrack thanks, let me check if we can implement this for next release or not

**Comment by yugangw-msft** [comment]
@colrack , thanks for the contribution!
