### ISSUE TITLE
azure vm quick-create should create any non-existing resource groups

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-xplat-cli#2386]
It seems that in quick-create, in the interest of being quick, we should create (or at least offer to create) the resource group ahead of the VM instance.

**Comment by colemickens** [comment]
For example, it creates the storage account for the user.

**Comment by ahmetalpbalkan** [comment]
+1 (#2387)

**Comment by huangpf** [comment]
+@sauryadas

**Comment by squillace** [comment]
+1

**Comment by sauryadas** [comment]
+1. Work item created and should be available in the feb CLI release. 
1)Will be available in ARM mode only. 
2)The user will need to provide a resource group name. We will not create one by default.

**Comment by huangpf** [comment]
In ```0.9.15```. Close for now.

**Comment by ahmetalpbalkan** [comment]
Thanks!
