### ISSUE TITLE
[ARM] vm quick-create should probably create the resource group, too

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2387]
The 

    $ azure vm quick-create <group> <vm> <location> linux ...

fails if `<group>` does not exist. I think if we create the `<group>` in `<location>` for the user if it's missing it would be great for a newcomer customer to get things going without having to figure out all details of Azure. 

Even as an experienced user, I want to see quick-create to be quick. Every time I run this it fails with "resource group does not exist" error, just because I'm forgetting this every time probably means we can improve the situation. :smile: 

@sauryadas

**Comment by colemickens** [comment]
:+1: https://github.com/Azure/azure-xplat-cli/issues/2386

**Comment by ahmetalpbalkan** [comment]
@colemickens ah you beat me
