### ISSUE TITLE
Azure-xplat-cli on Windows.... where did it go?

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-xplat-cli#2388]
So the README of this repo and [this page]() say to install the MSI. And then nothing else.

Where did they go? How do I use them? Etc?

**Comment by yugangw-msft** [comment]
@colemickens, click [this link](http://aka.ms/webpi-azure-cli), the browser will download the msi and you can double click it so invoke windows installer engine and install the azure-cli. After it is done, you open any command window, and type "azure" to start.

**Comment by colemickens** [comment]
I tries this. It did not work. Does it require a logout and login to pick
up the new PATH?

**Comment by yugangw-msft** [comment]
Logout is not necessary. Did you open a branch new command window?

**Comment by colemickens** [comment]
I thought I had. It works now anyhow. Thanks for the support!

**Comment by colemickens** [comment]
I just went through this process again.

I've closed and reopened all command prompt (and Powershell) windows and `azure` is still not available.

Signed out, signed in, everything works. It'd be nice if that step was explicitly called out and  not necessary.

**Comment by yugangw-msft** [comment]
fixed
