### ISSUE TITLE
[ARM] azure vm list: resource group names printed uppercase

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2389]
```
➜  ~  azure vm list
+ Getting virtual machines
data:    ResourceGroupName  Name               ProvisioningState  PowerState  Location  Size
data:    -----------------  -----------------  -----------------  ----------  --------  -----------
data:    AHMET-TEST         myVM               Succeeded          VM running  westus    Standard_D1
data:    AZLINUX-AUTOPILOT  azlinux-autopilot  Succeeded          VM running  westus    Standard_D1
```

why?

(0.9.13)

**Comment by huangpf** [comment]
The service returns upper cases values, and you can see them from ```-vv``` logs.

It's possible to make additional calls to query the actual group names, but we decided not to slower the calls, and thus just leave it as-is.

**Comment by ahmetalpbalkan** [comment]
Wow very interesting, I did not expect that. :) Thanks. I guess that's a wontfix. I followed up other uppercase vs lowercase issues with xRP folks before, often nothing is coming out of those discussions.
