### ISSUE TITLE
0.9.13 ARM :: azure network vnet show "[object Object]" for NSG

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2391]
When I run the `azure network vnet show` command, a Virtual Network Subnet that has a Network Security Group (NSG) associated with it, shows `[object Object]`.

This could be improved to show the name of the NSG that is associated with the VNet Subnet.

![screen shot 2015-12-18 at 9 12 52 pm](https://cloud.githubusercontent.com/assets/466713/11911283/3c7e754c-a5ce-11e5-9096-ab4c89d07dde.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by romangromov** [comment]
Will fix

**Comment by romangromov** [comment]
+@sreekanthbs to verify fix

**Comment by sreekanthbs** [comment]
@romangromov It is working fine. Showing Network security group id
![image](https://cloud.githubusercontent.com/assets/11171941/11927179/af61c2d4-a7f0-11e5-965b-e936d181abea.png)

**Comment by romangromov** [comment]
PR with fix merged, please close the issue. Thanks

**Comment by pcgeek86** [comment]
@romangromov @sreekanthbs Thanks for resolving this!

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
