### ISSUE TITLE
Need way to override default error log location (~/.azure)

### ISSUE THREAD

**Issue by smith1511** [Azure/azure-xplat-cli#2401]
When trying to use the Azure CLI from a service account on Linux the CLI will attempt to write to the directory "$HOME/.azure".  However some service/system accounts don't have a home directory set.

It would be good if this location could be specified for each command, or possible globally using the 'azure config...' commands.

**Comment by yugangw-msft** [comment]
@smith1511, there is "AZURE_CONFIG_DIR" environment variable you can use to re-direct.

**Comment by smith1511** [comment]
Perfect - i'll close the CR.
