### ISSUE TITLE
How do you create a VPN Gateway?

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2414]
I'm trying to create a VPN Gateway, which I thought would be fairly straightforward, but I'm getting prompted for a "Private IP Address" parameter. There's no documentation for this parameter, so I have no idea how to create one.

1. Please ensure documentation is detailed.
2. Please provide an example for creating a VPN Gateway.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by colrack** [comment]
Hi
I played with vpn connections few months ago so I can answer
Following cmds are for ARM mode

1) create a group
`azure group create vpngroup --location westeurope`

2) create a public ip for the gateway
`azure network public-ip create --resource-group vpngroup --name gwpip --location westeurope`

3) create a vnet
`azure network vnet create --resource-group vpngroup --name gwvnet --location westeurope --address-prefixes 10.0.0.0/16`

4) create a subnet for the gateway; notice as for now the name must be `GatewaySubnet` for some technical reasons
`azure network vnet subnet create --resource-group vpngroup --vnet-name gwvnet --name GatewaySubnet --address-prefix 10.0.1.0/24`

5) create the vpn gateway (this will take a little time so be patient, ~30 min)
`azure network vpn-gateway create --resource-group vpngroup --name gw --location westeurope --vnet-name gwvnet --subnet-name GatewaySubnet --private-ip-address 10.0.1.4 --public-ip-name gwpip`

The  --private-ip-address parameter is the local ip address for the gateway in the vnet; virtual machines traffic will be routed to the gw to reach VMs in another vnet or on premise network. Notice that a VM can be placed in another subnet of the same vnet (it is not necessary to place it in the `GatewaySubnet `).

Docs are poor actually but I came to a working VPN connection (obviously cmds above are not enough to establish an actual connection you have to setup at least another point to connect to).

Hope it helps
Bye

**Comment by pcgeek86** [comment]
@colrack Wow, thanks so much for that. I really appreciate the help. Let's leave this issue open so that the documentation can be fixed. :) The `--private-ip-address` parameter is what confused me the most. I haven't ever seen the requirement to configure a private IP address on a VPN Gateway before. You don't should have to specify the subnet name or subnet ID, at least in theory. :)

Ciao!
Trevor Sullivan

**Comment by romangromov** [comment]
@pcgeek86 please suggest description for `--private-ip-address` parameter - will update

**Comment by pcgeek86** [comment]
@romangromov I don't have a suggestion, because I don't know how it is intended to work. The Azure engineering team that's responsible for this feature should be held responsible for providing a description. This goes for every feature of the platform.

Cheers,
Trevor Sullivan

**Comment by colrack** [comment]
@romangromov https://github.com/Azure/azure-xplat-cli/pull/2427 LGTM

Since as of now `--subnet-name` must be `GatewaySubnet`, default to it if not provided would be nice.
It would be also nice to assign a dynamic ip to the gateway if `--private-ip-address` is not provided.

**Comment by romangromov** [comment]
@colrack this make sense, both proposal implemented now, thanks

**Comment by pcgeek86** [comment]
Great suggestions, @colrack. Thanks for implementing them, @romangromov.

Cheers,
Trevor Sullivan

**Comment by kevindente** [comment]
Is there a way to upload a certificate? That's the one missing piece I haven't been able to find, and as far as I can tell there's no UI for it either.

**Comment by colrack** [comment]
This is not something possible right now. This is a new feature introduced in [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/commit/a5f60ba0b1d60cf5307f6e3afe9a765d2c2ad967) in December and recently in [azure-sdk-for-node](https://github.com/Azure/azure-sdk-for-node/commit/4d219e20714eb81fedd22f6aa539f88a2a339844#diff-4adc6f587014463acc1f6da08de6c912).
In the meantime you can use powershell (see related [article](https://azure.microsoft.com/en-us/documentation/articles/vpn-gateway-howto-point-to-site-rm-ps/)), call REST API or use [Azure Resource Explorer](https://resources.azure.com).
This will be implemented for sure; if you want you can open an issue to track it.
/cc @romangromov 
Bye
