### ISSUE TITLE
Bugs: KeyVault key create Invalid URI

### ISSUE THREAD

**Issue by kahwooi** [Azure/azure-xplat-cli#2415]
I am using:

```
Windows 10 Pro
Nodejs v4.2.4
Azure CLI 0.9.13
```

When I try to add a key to the KeyVault with the following command:
```
azure keyvault key create --vault-name 'ContosoKeyVault' --key-name 'ContosoFirstKey' --destination software
```

I got the failed message below:
```
+ Creating key https://'ContosoKeyVault'.vault.azure.net/keys/'ContosoFirstKey'
error:   Invalid URI "https:///%27ContosoKeyVault%27.vault.azure.net/keys/%27ContosoFirstKey%27/create?api-version=2015-06-01"
info:    Error information has been recorded to C:\Users\Bugs\.azure\azure.err
error:   keyvault key create command failed
```

Solution:

I remove ```opening and closing apostrophe``` from --vault-name and --vault-key, it solve my problem.

**Comment by yugangw-msft** [comment]
@karlaugsten , please comment

**Comment by karlaugsten** [comment]
Hey @kahwooi, yes you will need to drop the single quotes if you are running the commands in a cmd.exe prompt. In a powershell prompt you can keep the quotes.
