### ISSUE TITLE
[ARM] azure vm image list, without knowing publishers

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2418]
**Claim:** Discovering and searching images in the ARM CLI without knowing the publisher name is impossible.

I'm not sure if this is an API [limitation | design] [mistake | success], but in the ARM mode I can't list all the images in the system without knowing the publisher name. For instance in ASM mode I can do:

```
$ azure vm image list | grep -i centos
...
data:    0b11de9248dd4d87b18621318e037d37__RightImage-CentOS-7.0-x64-v14.1.5.1                                                 Public    Linux    RightScale with Linux
data:    0b11de9248dd4d87b18621318e037d37__RightImage-CentOS-7.0-x64-v14.2                                                     Public    Linux    RightScale with Linux
data:    0b11de9248dd4d87b18621318e037d37__RightImage-CentOS-7.0-x64-v14.2.1                                                   Public    Linux    RightScale with Linux
data:    5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-65-20150128                                                        Public    Linux    OpenLogic
data:    5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-65-20150325                                                        Public    Linux    OpenLogic
...
```

and discover images easily (pay attention to the fact that as a user I don't **[ know | care ]** who RightImage or OpenLogic or whatever small ISV are, nor I should, I just want to get some CentOS).

Now, in the ARM mode, **all the `vm image` commands require a publisher argument**. This is deliberately limiting the discoverability. I'm trying to create an opensuse VM right now, I don't know what company is publishing that, so unless I go to the web portal I'm out of options.

 However, luckily, we have a list-publishers command:

    azure vm image list-publishers -l westus

that returns 409 lines of useless information (just company names really). (The author here is trying to say that if you can, please get rid of this subcommand, too.)

Please make this easier for people.

**Comment by sauryadas** [comment]
@ahmetalpbalkan Agree with what you have to say here. This has been discussed at length and it looks like this is not a trivial API change . I will update this bug when i have a work item for this.
Cant really get rid of any of the following commands. At the very least there is some option to discover an image, even though it is 4 levels deep.

![image](https://cloud.githubusercontent.com/assets/15387759/12568786/7f27327c-c37d-11e5-87d9-7605a493a7b1.png)

**Comment by ahmetalpbalkan** [comment]
By design, closing.
