### ISSUE TITLE
microsoft/azure-cli: can we get an updated Dockerfile

### ISSUE THREAD

**Issue by squillace** [Azure/azure-xplat-cli#2421]
The Dockerfile at https://hub.docker.com/r/microsoft/azure-cli/~/dockerfile/ pulls in some seriously old version. Can we get that updated? I pulled it the other day and I got .9.10; we're at .13.

**Comment by colrack** [comment]
Hi

I already opened https://github.com/Azure/azure-cli-docker/issues/23 for this.
[azure-cli-docker](https://github.com/Azure/azure-cli-docker) is at `0.9.13`, docker hub at `0.9.10`.

I propose to integrate `azure-cli-docker` releases as part of the release process of `azure-xplat-cli` and have in release notes instructions on how to run it, something like `docker run -it microsoft/azure-cli:X.X.X`, so you can't miss to update.

I think also having a Dockerfile in `azure-xplat-cli` to build the current version would be great, so we can clone the repo, build the image and run without having node on the host system. This would be great even to quickly test features of forks. This is something even other Azure projects have adopted, for instance [WALinuxAgent](https://github.com/Azure/WALinuxAgent).

**Comment by squillace** [comment]
+1 agreed. closing.

**Comment by ahmetalpbalkan** [comment]
@squillace I think @devigned is supposed to update dockerfiles and make releases on the azure-xplat-cli repo. :) 

@colrack the Dockerfile of WALinuxAgent is for development of that project, the Dockerfile at https://github.com/Azure/azure-xplat-cli/ is for releasing of software, which is a different thing. We must not confuse these two things.

**Comment by colrack** [comment]
@ahmetalpbalkan yes I know, but thanks for clarifying if others were confused.
I'm just saying having a Dockerfile for development would be nice. Maybe I'll open another issue
