### ISSUE TITLE
There doesn't appear to be a valid way to create an azure ad service principal

### ISSUE THREAD

**Issue by AlanSt** [Azure/azure-xplat-cli#2423]
azureuser@vm:~$ azure ad sp create  --applicationId blah

  error: missing required argument `application-id'

azureuser@vm:~$ azure ad sp create  --application-id blah

  error: unknown option `--application-id'

**Comment by yugangw-msft** [comment]
@AlanSt try what the [test code](https://github.com/Azure/azure-xplat-cli/blob/dev/test/commands/arm/ad/arm.ad-app-tests.js#L57) does

**Comment by yugangw-msft** [comment]
@AlanSt, this has been fixed in 0.9.14. the parameter is "--applicationId"
