### ISSUE TITLE
-h option returning help with any alphabet given after -h

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2426]
![screenshot_10](https://cloud.githubusercontent.com/assets/1655573/12287882/01baa7c4-b9e1-11e5-9ae2-e15b7c5954cc.png)

**Comment by haocs** [comment]
@romangromov thanks for reporting this issue. Added it to the backlog but not on top of priority list.

**Comment by romangromov** [comment]
@haocs thats totally fine, non blocking issue
