### ISSUE TITLE
ARM: azure vm quick-create should support instance size parameter

### ISSUE THREAD

**Issue by RevCBH** [Azure/azure-xplat-cli#2431]
When trying to create an image backed by a Premium_LRS storage account, there's no way to select an appropriate instance type.

**Comment by yugangw-msft** [comment]
@huangpf , @sauryadas

**Comment by huangpf** [comment]
I think this is a question about which parameters shall be exposed or not for the 'quick' command.

Premium storage is more of an advanced user case, so it shall be achieved by using ```vm create```? @sauryadas

**Comment by RevCBH** [comment]
Fair, but regardless of storage, it'd be nice to select a different size.

**Comment by huangpf** [comment]
@RevCBH May I know which image do you refer to? Is it available to all users? I would like to try to reproduce the problem and look a bit further into it. Thanks.

**Comment by RevCBH** [comment]
Yeah, it's a public image: openlogic:CentOS:6.7:6.7.20150815

I was trying to run a command like:

azure vm quick-create \
  --resource-group "$AZURE_RESOURCE_GROUP_NAME" \
  --name vendorimagebuildbox \
  --location "$AZURE_LOCATION" \
  --os-type "Linux" \
  --image-urn "openlogic:CentOS:6.7:6.7.20150815" \
  --admin-username username \
  --admin-password xxxxxx

With the goal of performing customizations and then capturing/generalizing it along the lines of:
https://github.com/Azure/azure-content/blob/master/articles/virtual-machines/virtual-machines-linux-capture-image-resource-manager.md

**Comment by huangpf** [comment]
Actually, I was able to quick-create a VM from the image ```openlogic:CentOS:6.7:6.7.20150815``` with that command's default size ```Standard_D1```:
```
{
  "properties": {
    "vmId": "d04468ea-6c6f-4ce3-8b54-be5ca2f72112",
    "hardwareProfile": {
      "vmSize": "Standard_D1"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "openlogic",
        "offer": "CentOS",
        "sku": "6.7",
        "version": "6.7.20150815"
      }, ...
```

And if you check it by the command ```azure vm image show westus openlogic CentOS 6.7 6.7.20150815```, it doesn't say anything about the VM size. So I guess the problem might be that the auto-creation of the storage account was ```Premium_LRS``` and it doesn't work with ```Standard_D1```. Can you send us your repro logs?

Anyhow, I tend to agree with you that instance size parameter is a fairly important variable for a VM, and it shall be exposed because it might block some quick-creation cases, unless the command can figure out the suitable default size (which seems to be tricky).

@sauryadas Thoughts?

**Comment by sauryadas** [comment]
@RevCBH You can update the VM size to your choice by running the following command after the quick-create .

>azure vm set [resource group name][vm-name] -z [new-vm-size]

**Comment by huangpf** [comment]
@RevCBH 
The following option is exposed in ```0.9.15```:
```
help:      -z, --vm-size <vm-size>                        the virtual machine size [Standard_D1]
```

Close for now.
