### ISSUE TITLE
Should resource group names be able to have a dash in it?

### ISSUE THREAD

**Issue by remkoboschker** [Azure/azure-xplat-cli#2435]
I'm trying to move a resource group named "Default-Web-WestEurope". However the move command throw an error on the the regular expression checking the resource group name.

https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/resource/resourceUtils.js line 103.

Is this the correct behaviour? If not I'll be happy to add the dash in a pull request.

**Comment by romangromov** [comment]
btw: I'm able to create resource group with dash in it's name: `test-roman-group`

**Comment by remkoboschker** [comment]
So, I guess it should be allowed in the getResourceGroupForMove function. I'll try a move with a dash in the name in a forked cli tomorrow.

**Comment by romangromov** [comment]
@remkoboschker your fix merged, please verify and close the issue, Thanx!
