### ISSUE TITLE
'vm reset-access' --ssh-cert argument doesn't accept RSA format

### ISSUE THREAD

**Issue by tonymitchell** [Azure/azure-xplat-cli#2437]
The 'vm create' command was updated (https://github.com/Azure/azure-xplat-cli/issues/1681) to support specifying the users SSH RSA public key (e.g. id_rsa.pub), however the related 'vm reset-access' command was not.  If you've created a VM with an SSH RSA key, you should be able to reset-access to it as well should something go wrong.  Additionally, if you use the reset-access command to add new users, it would be nice to be able to create them with SSH RSA keys as well.

**Comment by CrazyPython** [comment]
Looks like no one bothered to update the docs that say it's still unsupported. Azure has to be the worst cloud existing; lots of tooling, but little *good* tooling...

**Comment by CrazyPython** [comment]
`Either password or SSH key are required to reset access for user james.` doesn't tell you how to give supply of those arguments.
