### ISSUE TITLE
~/.azure/azureProfile.json should be chmod 0600

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2447]
This `$HOME/.azure/azureProfile.json` file contains subscription IDs and names, what we consider as medium-sensitive information. It has permissions `(0644/-rw-r--r--)`.

It should be `(0600/-rw-------)`.

**Comment by mayurid** [comment]
@yugangw-msft: Any concerns with this change?

**Comment by yugangw-msft** [comment]
@mayurid, no safe to change

**Comment by ahmetalpbalkan** [comment]
🔔 🔔 🔔

**Comment by haocs** [comment]
Fixed https://github.com/Azure/azure-xplat-cli/pull/3080
