### ISSUE TITLE
"azure webapp list" has incorrect help usage

### ISSUE THREAD

**Issue by colhountech** [Azure/azure-xplat-cli#2455]
[resource group] is not an optional argument. Optional arguments should be enclosed in square braces. Required arguments should be enclosed in angular brackets.
e.g.
```
azure webapp list --help
help:    List your webapps
help:    Usage: webapp list [options] [resource-group]
```
should be:

```
azure webapp list --help
help:    List your webapps
help:    Usage: webapp list [options] <resource-group>
```
for further reference, see [a similiar issue with dotnet-cli](https://github.com/aspnet/dnvm/issues/479)

This issue exists in an inconsistent manner across the app.

**Comment by haocs** [comment]
@colhountech thank you for reporting. This issue has been fixed in PR https://github.com/Azure/azure-xplat-cli/pull/2782
