### ISSUE TITLE
ARM: Setting vnet tags not working in MITM mode

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2456]
I'm running `mitmproxy` on my Mac to eavesdrop on the requests via a man-in-the-middle proxy.

I'm running the command:

    azure network vnet set -t "tag1=value1" my-rg my-vnet -vv

What I see on the wire (in mitmproxy) that "GET Virtual Network" call happens and gets a response and nothing happens later on....

What I see on `-vv` output is that in addition to the "GET Virtual Network" request & response, I see a request is issued to "PUT Virtual Network" but this never makes it to mitmproxy and **hangs indefinitely**. So nothing happens.

# Simple repro:

run in your console:
```sh
$ mitmproxy
```

open another terminal and run these:
```sh

$ export HTTPS_PROXY=http://127.0.0.1:8080; export NODE_TLS_REJECT_UNAUTHORIZED=0
$ azure network vnet set -t "tag1=value1" my-rg my-vnet -vv
```

watch `mitmproxy` and `azure` outputs and see it is getting hang.  I'm not sure if this is any specific to vnet at all but seemed pretty weird.

Any ideas?

**Comment by yugangw-msft** [comment]
I will take a look first

**Comment by yugangw-msft** [comment]
This should have been fixed. Checked out the #2390 for details

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft thanks!
