### ISSUE TITLE
Public IP Address not binding to NIC

### ISSUE THREAD

**Issue by seesharprun** [Azure/azure-xplat-cli#2481]
I'm writing a lab using Azure CLI to create a VM with some basic ARM concepts. This may be user error but I've been trying to figure out why my PIP is not being associated to my NIC.

After running the below lab steps, I have to go to the portal manually and **enable** my PIP on the NIC.  

I suspect there is an issue with the *"--public-ip-name"* parameter or that I may not be using it correctly.

Steps below:

---

1.  Create a new Resource Group:
  -   **Name:** CLITestGroup
  -   **Location:** West US
  ```
  azure group create –n “CLITestGroup” –l “West US”
  ```
2.  Create a new Public IP address:
  -   **Name:** TestPIP
  -   **Allocation Method:** Dynamic
  -   **Location:** West US
  -   **Group Name:** CLITestGroup
  -   **Domain Name Label:** \[Your unique name here\]
  ```
  azure network public-ip create -g "CLITestGroup" -n "TestPIP" -l "West US"
  –-allocation-method “Dynamic” --domain-name-label "demoexample"
  ```
> **Note:** if you label is not unique or otherwise not valid, you will
receive a message that your request has failed when you try to set the
domain name. Simply try again with another domain name label.
1.  Create a new Virtual Network:
  -   **Name:** TestVNET
  -   **Location:** West US
  -   **Group Name:** CLITestGroup
  ```
  azure network vnet create –g "CLITestGroup" –n “TestVNET” -l "West US"
  ```
1.  Create a new Subnet:
  -   **Name:** TestSubnet
  -   **Address Prefix:** 10.0.1.0/24
  -   **VNET Name:** TestVNET
  -   **Group Name:** CLITestGroup
  ```
  azure network vnet subnet create -g "CLITestGroup" --vnet-name "TestVNET" -n "TestSubnet"
  --address-prefix 10.0.1.0/24
  ```
1.  Create a new Network Interface Card:
  -   **Name:** TestNIC
  -   **Location:** West US
  -   **Public IP Address Name:** TestPIP
  -   **Subnet Name:** TestSubnet
  -   **VNET Name:** TestVNET
  -   **Group Name:** CLITestGroup
  ```
  azure network nic create -g "CLITestGroup" -l "West US" -n "TestNIC"
  --subnet-name "TestSubnet" --subnet-vnet-name "TestVNET"
  –-public-ip-name “TestPIP”
  ```

**Comment by romangromov** [comment]
@seesharprun thank you for flagging, As workaround, try to place `--public-ip-name` parameter before specifying `--subnet-name`, like:

`azure network nic create -g "CLITestGroup" -l "West US" -n "TestNIC" –-public-ip-name “TestPIP
--subnet-name "TestSubnet" --subnet-vnet-name "TestVNET"
”`

**Comment by seesharprun** [comment]
I can't believe it was user error! Thanks for the assist.

**Comment by seesharprun** [comment]
Spoke too quick, I tried 
```
azure network nic create -g "CLITestGroup" -l "West US" -n "TestNIC" --subnet-name "TestSubnet" --subnet-vnet-name "TestVNET" --public-ip-name "TestPIP" 
```

and even tried
```
azure network nic set -g "CLITestGroup" -n "TestNIC" --public-ip-name"TestPIP"
```
I see in the verbose output: ``Looking up the public ip "TestPIP"` but the NIC and VM still do not have a public IP address, just internal.  Not sure what the next step is from here.

**Comment by romangromov** [comment]
@seesharprun known issue in official installer v.0.9.14, already fixed in `dev` branch of this repo, will be shipped with release of `0.9.15`.

Duplicates this #2436, 
PR with fix here #2440

You can apply fix on your Xplat-CLI local copy or clone this repo and switch to dev branch or wait for next release of 0.9.15.

Hope this helps,
-Roman

**Comment by romangromov** [comment]
@seesharprun please confirm all is fine now

**Comment by romangromov** [comment]
@amarzavery this can be closed

**Comment by seesharprun** [comment]
Apologies for the delay, 

I validated myself and with my trainers that the bug is resolved and steps are working as expected.

Thanks!
