### ISSUE TITLE
Cannot delete blobs with snapshots.

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-xplat-cli#2483]
Do you have a plan to implement this feature?
https://github.com/Azure/azure-xplat-cli/blob/896b1bae02e56c5a732358b665ebf3bab2f9d7b7/lib/commands/storage/storage.blob._js#L189-L191

**Comment by amarzavery** [comment]
@yaxia - Can you please take a look at this issue ?

**Comment by amarzavery** [comment]
Based on the documentation provided over here : https://msdn.microsoft.com/en-us/library/azure/dd179413.aspx 
```

x-ms-delete-snapshots: {include, only}
 
Required if the blob has associated snapshots. Specify one of the following two options:

•include: Delete the base blob and all of its snapshots.


•only: Delete only the blob's snapshots and not the blob itself.


This header should be specified only for a request against the base blob resource. If this header is specified on a request to delete an individual snapshot, the Blob service returns status code 400 (Bad Request). 

If this header is not specified on the request and the blob has associated snapshots, the Blob service returns status code 409 (Conflict).
 ```

The CLI should expose two options for deleting the snapshot, such that the x-ms-delete-snapshots request header is provided the right value.

This is consuming the storage data plane client. The storage management client exposes to consume custom request headers on every operation for [example](https://github.com/Azure/azure-sdk-for-node/blob/autorest/lib/services/storageManagement2/lib/operations/storageAccounts.js#L41). If the data plane client follows the same approach then this feature request can be resolved.

@hasonmsft, @yaxia - What do you guys think about this?

@emgerner-msft - Do you think having a swagger spec for the data plane clients would be a good idea ?

**Comment by yaxia** [comment]
It's a valid issue. We are going to fix it. Thanks.

**Comment by yaxia** [comment]
We have added the support for deleting snapshot the 0.10.1. Please take a try.
`azure storage blob delete -h`
