### ISSUE TITLE
Cannot connect to storage emulator

### ISSUE THREAD

**Issue by jkdufair** [Azure/azure-xplat-cli#2485]
Trying to use this tool with the storage emulator. Tried specifying connection string as `"UseDevelopmentStorage=true" `to no avail. Was able to connect using:

`$ export AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;"`

But when I try to, i.e. create a container, it appears to be trying to send requests to http://127.0.0.1/containername instead of http://127.0.0.1/devstoreaccount1/containername

**Comment by amarzavery** [comment]
@yaxia - Can you please take a look at this issue ?

**Comment by yaxia** [comment]
@jkdufair Thanks for reporting the issue. We will support storage emulator in a later release.

**Comment by yaxia** [comment]
We have added the support for it in the 0.10.1. Please take a try.
