### ISSUE TITLE
Azure CLI json output only a subset of ARM REST endpoint return json

### ISSUE THREAD

**Issue by polarapfel** [Azure/azure-xplat-cli#2486]
Hi there,

I noticed that Azure CLI is not passing through the ARM REST API return json when running with the --json parameter. For example, when creating template deployments, the json output written by Azure CLI does not show the correlationId even though I can see it in the debug output (-vv parameter).

Can you please pass through the unfiltered ARM REST json return object? Or at least add things like the correlationId to your rewritten json output? This is important as without the correlationId, it's difficult to map a specific template deployment action to the correlated entries in the audit logs.

Thanks,

Tobias W.

**Comment by amarzavery** [comment]
@vivsriaus - Can you please take a look at this issue ?
