### ISSUE TITLE
Travis build failing in dev branch

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2489]
due to the following test cases:

1) arm compute vm create for extension get and set:
2) arm compute vm Enable diagnostics extension on created VM in a resource group:
3) arm compute vm Set AEM for the created vm:

This blocked pending PRs from merge.

@amarzavery @yugangw-msft

**Comment by amarzavery** [comment]
@huangpf  - I am working on this right now. It seems the compute team did not update the chef extension commands to use the latest ARM compute client

**Comment by huangpf** [comment]
I had run the live test cases for VM, i.e. ```npm run unit-arm-vm-live```. Are there other test cases that cover these issues?

**Comment by amarzavery** [comment]
@huangpf - This test "commands/arm/vm/arm.vm.enable-aem-tests.js" is present in testlist-arm.txt but not in testlist-arm-vm-live.txt or testlist-vm-live.txt or testlist-arm-vm.txt

**Comment by huangpf** [comment]
I think the 3rd party extension team should be notified to add their tests into the live test file ```testlist-arm-vm-live.txt```.

```testlist-arm-vm.txt``` should be short and quick, so it shouldn't be included here.

**Comment by amarzavery** [comment]
This has been fixed and the PR has been merged.
