### ISSUE TITLE
vm create error with --admin-username and --ssh-publickey-file on v0.9.15

### ISSUE THREAD

**Issue by MasaGon** [Azure/azure-xplat-cli#2502]
When using vm create on ARM mode with both --admin-username and --ssh-publickey-file,

error:   Authentication using either SSH or by user name and password must be enabled in Linux profile.

It is NOT reproduced on v0.9.14.

**Comment by DuskEagle** [comment]
We observed the same thing, except adding --admin-password in addition to --ssh-publickey-file made it work again.

**Comment by huangpf** [comment]
@amarzavery Did you fix this in the following PR? #2508

**Comment by amarzavery** [comment]
yup

**Comment by kevin-brown** [comment]
Just ran into this issue when using `--generate-ssh-keys` and `--admin-username`. Upgrading to the lastest dev fixed the issue.
