### ISSUE TITLE
endpoint documentation

### ISSUE THREAD

**Issue by kangman** [Azure/azure-xplat-cli#2504]
can we have some please?   I just see a todo staring back at me in the wiki

**Comment by amarzavery** [comment]
@kangman - Can you please provide more context on this?

**Comment by kangman** [comment]
hey @amarzavery  please see this https://github.com/Azure/azure-xplat-cli/wiki/Endpoint-Management

There's nothing there.

**Comment by amarzavery** [comment]
@kangman - I see. I think the page was created by someone for documenting something about endpoints. Eventually this ended up as commands.

so you can say,
```
D:\sdk\azure-xplat-cli>azure account env list
info:    Executing command account env list
data:    Name
data:    -----------------
data:    AzureCloud
data:    AzureChinaCloud
data:    AzureUSGovernment
info:    account env list command OK
```

and then get detailed info about an environment that provides you all the endpoints for that environment

```
D:\sdk\azure-xplat-cli>azure account env show AzureCloud
info:    Executing command account env show
data:    Name:                                              AzureCloud
data:    activeDirectoryEndpointUrl:                        https://login.microsoftonline.com
data:    activeDirectoryGraphApiVersion:                    2013-04-05
data:    activeDirectoryGraphResourceId:                    https://graph.windows.net/
data:    activeDirectoryResourceId:                         https://management.core.windows.net/
data:    azureDataLakeAnalyticsCatalogAndJobEndpointSuffix: azuredatalakeanalytics.net
data:    azureDataLakeStoreFileSystemEndpointSuffix:        azuredatalakestore.net
data:    galleryEndpointUrl:                                https://gallery.azure.com/
data:    isPublicEnvironment:                               true
data:    keyVaultDnsSuffix:                                 .vault.azure.net
data:    managementEndpointUrl:                             https://management.core.windows.net
data:    portalUrl:                                         http://go.microsoft.com/fwlink/?LinkId=254433
data:    publishingProfileUrl:                              http://go.microsoft.com/fwlink/?LinkId=254432
data:    resourceManagerEndpointUrl:                        https://management.azure.com/
data:    sqlManagementEndpointUrl:                          https://management.core.windows.net:8443/
data:    sqlServerHostnameSuffix:                           .database.windows.net
data:    storageEndpointSuffix:                             .core.windows.net
info:    account env show command OK
```

I hope this, is what you were looking for. If not, then please let us know what exactly you meant with endpoint documentation.

**Comment by kangman** [comment]
yeah thanks for that illustration but while this one use case is helpful I
would like to see the documentation of this option for azure xplat cli
expanded on github or wherever you guys keep documentation for this tool so
that users like myself can learn about what endpoints does and what they
can use it for in their use case.    It is a bit discouraging to see a tool
made generally available without any documentation to go with it.

On Wed, Feb 10, 2016 at 7:53 PM, Amar Zavery <notifications@github.com>
wrote:

> @kangman <https://github.com/kangman> - I see. I think the page was
> created by someone for documenting something about endpoints. Eventually
> this ended up as commands.
>
> so you can say,
>
> D:\sdk\azure-xplat-cli>azure account env list
> info:    Executing command account env list
> data:    Name
> data:    -----------------
> data:    AzureCloud
> data:    AzureChinaCloud
> data:    AzureUSGovernment
> info:    account env list command OK
>
> and then get detailed info about an environment that provides you all the
> endpoints for that environment
>
> D:\sdk\azure-xplat-cli>azure account env show AzureCloud
> info:    Executing command account env show
> data:    Name:                                              AzureCloud
> data:    activeDirectoryEndpointUrl:                        https://login.microsoftonline.com
> data:    activeDirectoryGraphApiVersion:                    2013-04-05
> data:    activeDirectoryGraphResourceId:                    https://graph.windows.net/
> data:    activeDirectoryResourceId:                         https://management.core.windows.net/
> data:    azureDataLakeAnalyticsCatalogAndJobEndpointSuffix: azuredatalakeanalytics.net
> data:    azureDataLakeStoreFileSystemEndpointSuffix:        azuredatalakestore.net
> data:    galleryEndpointUrl:                                https://gallery.azure.com/
> data:    isPublicEnvironment:                               true
> data:    keyVaultDnsSuffix:                                 .vault.azure.net
> data:    managementEndpointUrl:                             https://management.core.windows.net
> data:    portalUrl:                                         http://go.microsoft.com/fwlink/?LinkId=254433
> data:    publishingProfileUrl:                              http://go.microsoft.com/fwlink/?LinkId=254432
> data:    resourceManagerEndpointUrl:                        https://management.azure.com/
> data:    sqlManagementEndpointUrl:                          https://management.core.windows.net:8443/
> data:    sqlServerHostnameSuffix:                           .database.windows.net
> data:    storageEndpointSuffix:                             .core.windows.net
> info:    account env show command OK
>
> I hope this, is what you were looking for. If not, then please let us know
> what exactly you meant with endpoint documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-xplat-cli/issues/2504#issuecomment-182660789>
> .
>



-- 

All the best,


Daniel S Kang

<http://www.d-kang.com>
<http://www.linkedin.com/pub/daniel-kang/6/58a/53a/>
<https://www.twitter.com/kangman>

**Comment by amarzavery** [comment]
@kangman - That is correct. We we will look into this. Usually keeping the documentation for endpoint in sync is problematic, as they have changed over time. Hence, we thought of exposing them as commands as the best way of showing accurate info. That being said, we should definitely update our documentation on how to get information about different endpoints. We will update our documentation accordingly. Btw, most of the documentation resides in the Documentation folder as a part of the repo over [here](https://github.com/Azure/azure-xplat-cli/blob/dev/Documentation/README.md). Hope this helps :).

**Comment by kangman** [comment]
Cool, it looks like the documentation is if I wanted to contribute to the
xplat-cli source which is great but the usage of the tool itself is not
that link.

On Thu, Feb 11, 2016 at 12:10 AM, Amar Zavery <notifications@github.com>
wrote:

> @kangman <https://github.com/kangman> - That is correct. We we will look
> into this. Usually keeping the documentation for endpoint in sync is
> problematic, as they have changed over time. Hence, we thought of exposing
> them as commands as the best way of showing accurate info. That being said,
> we should definitely update our documentation on how to get information
> about different endpoints. We will update our documentation accordingly.
> Btw, most of the documentation resides in the Documentation folder as a
> part of the repo over here
> <https://github.com/Azure/azure-xplat-cli/blob/dev/Documentation/README.md>.
> Hope this helps :).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-xplat-cli/issues/2504#issuecomment-182711095>
> .
>



-- 

All the best,


Daniel S Kang

<http://www.d-kang.com>
<http://www.linkedin.com/pub/daniel-kang/6/58a/53a/>
<https://www.twitter.com/kangman>

**Comment by amarzavery** [comment]
Have updated the main README.md file, the wiki and the documentation folder with information about getting endpoints for different environments supported in Azure.

**Comment by amarzavery** [comment]
Closing this for now. Feel free to open if required.
