### ISSUE TITLE
New VM not getting availability set assigned

### ISSUE THREAD

**Issue by dbarentine** [Azure/azure-xplat-cli#2507]
When I create a new VM it is not getting added to the availability set specified on the command line.

The command line parameter I'm using is:
--availset-name myavailset \

CLI Version: 0.9.15 (node: 0.10.25)

I think what is happening is the params that the CLI is sending to the underlying SDK look like:
   "availabilitySetReference": {
      "referenceUri": "..."
   },

But looking at the underlying SDK it looks like it should be something like:
"availabilitySet": {
  "id": "..."
},

And so it's getting omitted in the JSON being sent to the Azure API.

**Comment by amarzavery** [comment]
@huangpf - we need to add tests for this scenario as well.

**Comment by huangpf** [comment]
ok

**Comment by huangpf** [comment]
PR for the fix: #2512
