### ISSUE TITLE
ARM template deployment fails if parameters item is not in the azuredeploy.json file

### ISSUE THREAD

**Issue by PeterJausovec** [Azure/azure-xplat-cli#2518]
If I try to deploy an ARM template with the following command line: 

`azure group deployment create Group XXX --template-file azuredeploy.json` 

deployment fails with `Cannot convert undefined or null to object`, because I don't have a "parameters" set in the json file (see file groupUtils.js, function getTemplateParams(...)). 

However, if I take the same azuredeploy.json file and try to deploy it directly on Azure portal, it works and deploys fine. 

CC @damolina-ms

**Comment by amarzavery** [comment]
@PeterJausovec - I was able to repro this issue when I just had an empty object `{}` in a `deployment.json` file. 
```
D:\sdk\azure-xplat-cli>azure group deployment create -g group101 -n tempdep345 -f deployment.json
info:    Executing command group deployment create
info:    Supply values for the following parameters
error:   Cannot convert undefined or null to object
info:    Error information has been recorded to C:\Users\amzavery\.azure\azure.err
error:   group deployment create command failed
```
This should definitely get fixed. 

However, I am wondering, why does your template not have any parameters? Usually all templates ask for something or the other. Can you share your template file "azuredeploy.json"?

**Comment by PeterJausovec** [comment]
I am pre-filling all information in the template, so users don't have to enter anything when being redirected to Azure or when template file deployed through Azure CLI.

**Comment by amarzavery** [comment]
@PeterJausovec - This PR https://github.com/Azure/azure-xplat-cli/pull/2523 should fix the described issue.

**Comment by PeterJausovec** [comment]
Thanks @amarzavery!

**Comment by amarzavery** [comment]
@PeterJausovec 
If you want this fix then please uninstall the previously installed cli
```
npm uninstall azure-cli -g (if you installed via npm)
```
Or 
```
sudo azure-uninstall (if you installed from a mac installer)
``
Windows msi uninstallation should be simple :)

and then download the tarball from here https://github.com/Azure/azure-xplat-cli/archive/dev.tar.gz

After that, 
```
npm cache clear -g
npm install -g path-to-the downloaded-tar.gz
```
and you should be good to go.

**Comment by PeterJausovec** [comment]
Thanks @amarzavery!

CC @damolina-ms
