### ISSUE TITLE
Login through .publishsettings breaks 'azure logout' command

### ISSUE THREAD

**Issue by damolina-ms** [Azure/azure-xplat-cli#2529]
Repro: 

1. Run: _azure account download_
2. Save file  (example: _x.publishsettings_)
3. Run: _azure account import <.publishsetting file>_
4. Verify account works (example: _azure account show_)
5. Try to logout: _azure logout --username <username>_

**Bug **
No matter what user name you use, logout fails with 
TypeError: Cannot read property 'name' of undefined
...\azure-cli\lib\util\profile\profile.js:140:54

The problem is code assumes subscription has a defined 'user' but it seems with publishsettings is not the case.

**Comment by yugangw-msft** [comment]
Should be addressed at the same time with #1913.  The "logout" command should not be exposed under asm. 
The account management under asm generally is not good.
For now, you can use "account clear"

**Comment by yugangw-msft** [comment]
@amarzavery for fyi.

**Comment by yugangw-msft** [comment]
@damolina-ms, fix was in. If you like dogfood the latest bits, you can get it using npm like
    npm install -g https://github.com/Azure/azure-xplat-cli/tarball/dev
Let me know if you see other issues
