### ISSUE TITLE
ASM: Assign and remove static IP address to VM

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#2535]
Do we have support for adding a static IP to an existing VM and remove them? I see options for checking the availability, not to assign
# network vnet static-ip check [options] <vnet> <ip-address>

Equivalent powershell commands:
Get-AzureVM -ServiceName TestService -Name TestVM ` | Remove-AzureStaticVNetIP ` | Update-AzureVM

Get-AzureVM -ServiceName TestService000 -Name TestVM ` | Set-AzureStaticVNetIP -IPAddress 10.10.0.7 ` | Update-AzureVM

**Comment by amarzavery** [comment]
@romangromov - Can you provide some input on this?

**Comment by romangromov** [comment]
@amarzavery there is no support for add/remove staticIP to VM in `azure-asm-network` package.
This question should be addressed to owner of `compute` commands stack in Xplat-CLI
