### ISSUE TITLE
Location value accepted by "azure service create" is not accepted by "azure network vnet create"

### ISSUE THREAD

**Issue by sivaedupuganti** [Azure/azure-xplat-cli#2548]
Config mode: ASM

"ussouth" as location value is accepted by "azure service create", but not accepted by "azure network vnet create". 

```
$ azure service create --serviceName test-cli-cloud-svc --location ussouth
info:    Executing command service create
+ Creating cloud service
data:    Cloud service name test-cli-cloud-svc
info:    service create command OK

$ azure network vnet create --vnet classic-cli-vnet -e 192.168.2.0 -i 16 -n backend -p 192.168.2.0 -r 24 -l ussouth
info:    Executing command network vnet create
+ Looking up network configuration
+ Looking up locations
error:   Location group with name "ussouth" not found
info:    Error information has been recorded to /home/sivae/.azure/azure.err
error:   network vnet create command failed
```

**Comment by romangromov** [comment]
@sivaedupuganti actually service gets created in `South Central US` instead of `US South`, you can verify with `azure service show`. Please use `--location "South Central US"` in `vnet create`:

`$ azure network vnet create --vnet classic-cli-vnet -e 192.168.2.0 -i 16 -n backend -p 192.168.2.0 -r 24 -l "South Central US"`

**Comment by sivaedupuganti** [comment]
Yes, I saw that and got my vnet created earlier. However, I'm trying to understand why 'service create' would accept 'ussouth' as location, whereas 'network vnet create' wouldn't.

How can we fix this to be a consistent behavior?

**Comment by romangromov** [comment]
@sivaedupuganti in `azure service create` Azure backend takes care of resolving `USSouth` string to correct location, but in `azure network vnet create` we have more complicated logic on Xplat-CLI side, so we are fetching list of available locations to check  support for `PersistentVMRole` beforehand. In this case, value provided in `--location` should be exactly the same as location name ("South Central US")
