### ISSUE TITLE
azure vm create does not upload ssh pub key (0.9.15) (ARM)

### ISSUE THREAD

**Issue by Trepliev** [Azure/azure-xplat-cli#2550]
In 0.9.14 after "azure vm create ..... -M /path/to/key.pub -u xy -p password" is possible to log in into vm with user xy and the key OR password. In 0.9.15 key does not work because in the xy home directory there is no .ssh directory with authorized_keys file.

info:    Verifying the public key SSH file: /path/to/key.pub

and no error

**Comment by huangpf** [comment]
@amarzavery This was just patched in the dev branch by #2508, right?

**Comment by amarzavery** [comment]
@huangpf - That is correct.
