### ISSUE TITLE
'azure group create' does not seem to respect '--json' flag

### ISSUE THREAD

**Issue by damolina-ms** [Azure/azure-xplat-cli#2557]
### Repro
Run: 

    azure group create <name> <location> --json 

### Issue
Received result is not json.  It looks like this:

    "/subscriptions/_id_/resourceGroups/<name>
    "<name>"
    "<location>"
    "Succeeded"
    {}
    {}

**Comment by amarzavery** [comment]
There was a PR to fix this https://github.com/Azure/azure-xplat-cli/pull/2545 was merged into the dev branch today. Can you please `npm install <path-to-downloaded-tarball>` after downloading the tarball from this link https://github.com/Azure/azure-xplat-cli/archive/dev.tar.gz

**Comment by amarzavery** [comment]
@vivsriaus - Does your PR fix the issue for group create command as well ?

**Comment by amarzavery** [comment]
I am not able to repro this issue. It works fine for me.

```
D:\sdk>azure group create -l westus testfoo678 --json
{
  "id": "/subscriptions/00898db-163f-435f-89868-39ec8879861f4d/resourceGroups/testfoo678",
  "name": "testfoo678",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "location": "westus",
  "tags": {}
}
```
Which version of cli are you using and which os are you using?

**Comment by damolina-ms** [comment]
Odd, still repros for me.
OS: Win10 / CLI: 0.9.15

**Comment by amarzavery** [comment]
I think, it could be because of streamline issue. Can you delete the C:/USers/<username>/.streamline folder?

**Comment by damolina-ms** [comment]
I deleted C:/Users/_myuser_/.streamline but still repros.

**Comment by amarzavery** [comment]
Did you  `npm install <path-to-downloaded-tarball>` after downloading the tarball from this link https://github.com/Azure/azure-xplat-cli/archive/dev.tar.gz as mentioned in my response to the other github issue filed by you.

**Comment by damolina-ms** [comment]
I was replying to your message "I am not able to repro this issue. It works fine for me.". I assume you were referring to a build with the PR.
After d/l and installing the tarball, I get version 0.9.16 and command works correctly with it. Thanks.

**Comment by amarzavery** [comment]
Ah I see.. Sorry for the confusion. I thought you would have looked at my reply for the other issue (deployment create) https://github.com/Azure/azure-xplat-cli/issues/2558 as well. Glad to know that the issue has been resolved for you.
