### ISSUE TITLE
'azure group deployment create' doesn't seem to respect --json flag

### ISSUE THREAD

**Issue by damolina-ms** [Azure/azure-xplat-cli#2558]
### Repro

Run:
  `  azure group deployment create <resource-group> <deployment-name> --template-file <file> --json 
`
### Issue
Received result is not json. It looks like this (e.g. for VM deployment):

```
  "<resource-group>"
  "<deployment-name>"
  "Succeeded"
  "2016-02-19T02:25:24.9362304Z"
  "Incremental"
  {}
  {
    "vmUrl": {
      "type": "String",
      "value": "<other>.cloudapp.azure.com"
      }
  }
```

**Comment by amarzavery** [comment]
There was a PR to fix this https://github.com/Azure/azure-xplat-cli/pull/2545 was merged into the dev branch today. Can you please `npm install <path-to-downloaded-tarball>` after downloading the tarball from this link https://github.com/Azure/azure-xplat-cli/archive/dev.tar.gz

**Comment by damolina-ms** [comment]
The tarball with version 0.9.16 fixes the issue. Thanks.
