### ISSUE TITLE
Enable template parameter prompts 

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-xplat-cli#2561]
PS supports it. We should add this support to CLI as well.

**Comment by amarzavery** [comment]
@ravbhatnagar - This has been supported in CLI from day1. Unless I am missing something..

D:\sdk\AutoRest>**azure group deployment create -h**
help:    Creates a deployment
help:
help:    Usage: group deployment create [options] [resource-group] [name]
help:
help:    Options:
help:      -h, --help                             output usage information
help:      -v, --verbose                          use verbose output
help:      -vv                                    more verbose with debug output
help:      --json                                 use json output
help:      -g --resource-group <resource-group>   the name of the resource group
help:      -n --name <name>                       the name of the deployment
help:      -f --template-file <template-file>     the path to the template file in the file system
help:      --template-uri <template-uri>          the uri to the remote template file
help:      --template-version <template-version>  the content version of the template
**help:      -p --parameters <parameters>           a JSON-formatted string containing parameters**
**help:      -e --parameters-file <parametersFile>  a file containing parameters**
help:      -m --mode <mode>                       the deployment mode: specify one of Incremental or Complete. If no mode is specified, Incremental is used as default. When Complete mode is used, all the resources in the specified resource group, which are not included in the template, will be deleted.
help:      -q --quiet                             quiet mode (when complete mode is specified, do not ask for deployment confirmation)
help:      --nowait                               does not wait for the deployment to complete. Returns as soon as the deployment is created
help:      --novalidate                           do not validate deployment
help:      --subscription <subscription>          the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)


D:\sdk\AutoRest>**azure group create -h**
help:    Creates a new resource group
help:
help:    Usage: group create [options] <name> <location>
help:
help:    Options:
help:      -h, --help                              output usage information
help:      -v, --verbose                           use verbose output
help:      -vv                                     more verbose with debug output
help:      --json                                  use json output
help:      -n --name <name>                        the resource group name
help:      -l --location <location>                the location where we will create the group
help:      -d --deployment-name <deployment-name>  the name of the deployment we will create (only valid when a template is used)
help:      -f --template-file <template-file>      the path to the template file in the file system
help:      --template-uri <template-uri>           the uri to the remote template file
help:      --template-version <template-version>   the content version of the template
**help:      -p --parameters <parameters>            a JSON-formatted string containing parameters**
**help:      -e --parameters-file <parametersFile>   a file containing parameters**
help:      -t --tags <tags>                        Tags to set to the resource group. Can be multiple. In the format of 'name=value'. Name is required and value is optional. For example, -t tag1=value1;tag2
help:      --subscription <subscription>           the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)

**Comment by ravbhatnagar** [comment]
@amarzavery - This is for the ability to provide both in the same call and the inline params override the ones in the param file.

**Comment by amarzavery** [comment]
@ravbhatnagar - Oh I see.. Based on my experience, providing json parameters on the cmd line is pain (Esacping double qutoes).. I would prefer defining them in a file and pass the filename.

Killer feature would be to provide autocompletion for template parameters that Powershell provides today..

**Comment by ravbhatnagar** [comment]
@amarzavery - Agreed, on both parts.

**Comment by amarzavery** [comment]
We can certainly make it interactive in CLI. Let the user pass the template url or a template file along with template version.
The CLI can then parse the template to get the parameters and prompt the user for every parameter.
In interactive mode CLI can validate the values passed for every parameter (allowed values, string, bool, number) and ask to provide another value if it fails validation. That would be pretty much at parity with powershell.

Something on the following lines that we have for azure site create in asm mode:
```
D:\sdk\AutoRest>azure site create
info:    Executing command site create
help:    Need a site name
Name: testfoo<<<<<<<<<<<<
+ Getting locations
+ Getting sites
+ Getting locations
help:    Choose a location
  1) East Asia
  2) North Europe
  3) West Europe
  4) Southeast Asia
  5) West US
  6) East US
  7) Japan West
  8) Japan East
  9) South Central US
  10) East US 2
  11) North Central US
  12) Central US
  13) Brazil South
  14) Australia East
  15) Australia Southeast
  16) Central India
  17) West India
  18) South India
  : 16<<<<<<<
```

**Comment by jgreat** [comment]
+1 - Would love it if CLI would prompt for missing ARM template parameters like the Powershell equivalent does.

**Comment by ravbhatnagar** [comment]
Fixed
