### ISSUE TITLE
ASM: Azure network application gateway overriding individual settings

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#2562]
I initially created an application gateway and imported the json config file.

But I tried to override the listener settings using individual commands. Since there is no set option (would be great if we have set option here),  I tried to remove and add the listener again. but it fails to do the same.

1. Tried to add listener1 settings, but since it is already imported in json, it fails

[samanoha@bigboy ~]$ azure network application-gateway http-listener add --gateway-name testgw --name listener1 --frontend-ip-name fip1 --frontend-port-name fep1 --protocol Http
info:    Executing command network application-gateway http-listener add
+ Getting configuration for an Application Gateway "testgw"                    
error:   An http listener with name "listener1" already exists for an Application Gateway "testgw"
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   network application-gateway http-listener add command failed

2. So tried to remove listener1, but it complains that it needs at least one listener

[samanoha@bigboy ~]$ azure network application-gateway http-listener remove --gateway-name testgw --name listener1
info:    Executing command network application-gateway http-listener remove
+ Getting configuration for an Application Gateway "testgw"                    
Delete http listener "listener1?" [y/n] y
+ Setting configuration for an Application Gateway "testgw"                    
error:   Error Setting Application Gateway Configuration- 'Atleast one HttpListener must be specified'.
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   network application-gateway http-listener remove command failed

3. So added listener2, so that we can remove listener1 now

[samanoha@bigboy ~]$ azure network application-gateway http-listener add --gateway-name testgw --name listener2 --frontend-ip-name fip1 --frontend-port-name fep1 --protocol Http
info:    Executing command network application-gateway http-listener add
+ Getting configuration for an Application Gateway "testgw"                    
+ Setting configuration for an Application Gateway "testgw"                    
+ Looking up an Application Gateway "testgw"                                   
data:    Name                            : testgw
data:    State                           : Stopped
data:    Description                     : 
data:    Instance count                  : 1
data:    Gateway size                    : Small
data:    Virtual network name            : TestNet
data:    Subnets:
data:      Name                          : Subnet-1
info:    network application-gateway http-listener add command OK

4. Now trying to remove listener1, but fails with error like no reference.

[samanoha@bigboy ~]$ azure network application-gateway http-listener remove --gateway-name testgw --name listener1
info:    Executing command network application-gateway http-listener remove
+ Getting configuration for an Application Gateway "testgw"                    
Delete http listener "listener1?" [y/n] y
+ Setting configuration for an Application Gateway "testgw"                    
error:   Error Setting Application Gateway Configuration- 'HttpListener: listener1 reference does not exist'.
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   network application-gateway http-listener remove command failed

5. So assuming that listener1 got removed, adding listener1 gives error

[samanoha@bigboy ~]$ azure network application-gateway http-listener add --gateway-name testgw --name listener1 --frontend-ip-name fip1 --frontend-port-name fep1 --protocol Http
info:    Executing command network application-gateway http-listener add
+ Getting configuration for an Application Gateway "testgw"                    
error:   An http listener with name "listener1" already exists for an Application Gateway "testgw"
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   network application-gateway http-listener add command failed

Json config file used initially
=================================
{
    "backendAddressPools": [{
        "backendServers": [{
            "iPAddress": "10.1.0.22"
        }, {
            "iPAddress": "10.1.0.23"
            }],
        "name": "pool1"
    }],
    "backendHttpSettingsList": [{
        "name": "setting1",
        "port": 80,
        "protocol": "Http",
        "cookieBasedAffinity": "Enabled"
    }],
    "frontendIPConfigurations": [{
        "name": "fip1",
        "type": "Private",
        "staticIPAddress": "10.1.0.5"
    }],
    "frontendPorts": [{
        "name": "fep1",
        "port": 80
    }],
    "httpListeners": [{
        "name": "listener1",
        "frontendIP": "fip1",
        "frontendPort": "fep1",
        "protocol": "Http"
    }],
    "httpLoadBalancingRules": [{
        "name": "rule1",
        "type": "Basic",
        "backendHttpSettings": "setting1",
        "listener": "listener1",
        "backendAddressPool": "pool1"
    }]
}
====================================

**Comment by infosatheesh2020** [comment]
When i directly remove listener2, it allows. So the referencing of listener1 in httpLoadBalancingRules might be the issue. but if we have set command to override listener configs, this would be very easier.

**Comment by romangromov** [comment]
Adding owner for this command: @MikhailTryakhov

**Comment by MikhailTryakhov** [comment]
Hi @infosatheesh2020 thank you for a great question!
The easiest way to update existing functionality is to modify configuration file and re-export data.

I will communicate with team about other ways to set sub-items easier.

**Comment by infosatheesh2020** [comment]
@MikhailTryakhov thanks. my initial opinion was that it redeploys everything. Thanks for clarification. Also since we were not able to see private IP currently, i thought of debugging only that parameter (removing and adding it again), so I didn't find easy way for that.

Since we have possibility for creating configuration from power shell using configuration object (configuring individual items separately), Is there any specific logic not allowing the same in CLI.

**Comment by MikhailTryakhov** [comment]
There are differences in Azure CLI and PowerShell commands logic.
You may review all available commands via ```azure --help``` or lb commands via ```azure network lb --help```.
Please let me know if you have any other questions

**Comment by infosatheesh2020** [comment]
thanks, this helps!
