### ISSUE TITLE
ASM : azure network application gateway doesn't list frontendIP in HttpListener

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#2563]
I configured application gateway using Json config file and the listener section is below:

    "httpListeners": [{
        "name": "listener1",
        "frontendIP": "fip1",
        "frontendPort": "fep1",
        "protocol": "Http"
    }]

When i list the configuration using azure network application-gateway config show testgw command,

I don't see the frontendIP configured.

data:    Http listeners:
data:      Name                          : listener1
data:      Frontend port                 : fep1
data:      Protocol                      : Http
data:   

But when i export config to json, I am able to see those settings. 

"httpListeners":[{"name":"listener1","frontendIP":"fip1","frontendPort":"fep1","protocol":"Http"}]

Please add the settings to list the IP address in config show command since it is bit confusing.

**Comment by romangromov** [comment]
Adding owner for this command: @MikhailTryakhov

**Comment by MikhailTryakhov** [comment]
Hi @infosatheesh2020 thank you for a great job!
Would be fixed ASAP

**Comment by infosatheesh2020** [comment]
@MikhailTryakhov is it possible to show the public IP and DNS name when configuring as external load balancer? Currently we don't see any options and have to check from powershell.

**Comment by MikhailTryakhov** [comment]
@infosatheesh2020 you can review publuc IP name in Frontend IP section
![lb frontend IP](http://i.imgur.com/qPfwgeu.png)
To see public IP details you may use  ``` azure network public-ip show ``` command and review DNS name and other details there.
```lb show``` command format doesn't support all sub-items chain displaying.

**Comment by infosatheesh2020** [comment]
@MikhailTryakhov Do we have equivalent commands to view public IP and DNS names in ASM mode?

**Comment by MikhailTryakhov** [comment]
@infosatheesh2020 nope, public IP is supported in new ARM mode only.
If you have already deployed infrastructure - you can review hybrid solutions - f.e. [here](https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-arm-asm-s2s)

**Comment by infosatheesh2020** [comment]
@MikhailTryakhov thank you!
