### ISSUE TITLE
Client not listing HDI clusters created on azure protal

### ISSUE THREAD

**Issue by MortI2C** [Azure/azure-xplat-cli#2568]
Hi,
I'm having an issue with this client not showing the list of HDInsight clusters that I have created manually on the new azure portal (portal.azure.com).
I guess that as it happens with azure storage accounts, clusters created on that portal are treated differently than those created in the old one, and so this azure client is not taking that into consideration. Hope this has an easy fix.

**Comment by amarzavery** [comment]
@MortI2C 
Which mode are you in? when you type the help for any command, it explicitly displays the current mode in the end.
for example:
```
D:\sdk\azure-xplat-cli>azure hdinsight cluster list -h
help:    List all the clusters (in a specific resource group if provided) .
help:
help:    Usage: hdinsight cluster list [options]
help:
help:    Options:
help:      -h, --help                            output usage information
help:      -v, --verbose                         use verbose output
help:      -vv                                   more verbose with debug output
help:      --json                                use json output
help:      -g --resource-group <resource-group>  The name of the resource group
help:      -s, --subscription <id>               The subscription id
help:
help:    Current Mode: arm (Azure Resource Management)
```

For changing mode, please execute the following command: (valid values are: arm, asm)
```
D:\sdk\azure-xplat-cli>azure config mode arm
info:    Executing command config mode
info:    New mode is arm
info:    config mode command OK
```

I think changing the mode (asm is version v1 of azure api and arm is version v2 of azure api) should mostly solve the issue.
If you have previously logged in via `azure login` then you should be fine. If not, then please login.

**Comment by MortI2C** [comment]
Oh, thank you very much amarzavery. Apparently client changed quite a lot since last time I used it (back then didn't have two modes).
This perfectly solved my issue, thanks!
