### ISSUE TITLE
Is this a design flaw in the Azure ARM REST API?

### ISSUE THREAD

**Issue by dukedougal** [Azure/azure-xplat-cli#2569]
I want to get a list of virtual machines and display that list along with the state of each VM - running or stopped.

As far as I can tell, after the initial request to list the VM's, I then need to send a new REST API request for every single VM to determine what its running state is.

Hopefully I'm wrong because this seems pretty hard to understand.  Why would the list of VM's not include the running state of each VM?

So if I have a list of 200 VMs then I need to send 201 ARM REST API requests to display them all along with their running state?

**Comment by amarzavery** [comment]
This is a service side API design issue. It would be nice if @sauryadas , @singhkay , @mahthi can respond to this.

**Comment by amarzavery** [comment]
@dukedougal - that is correct. The CLI provides a command to hide that.

PowerState tells you the status.
```
D:\sdk\azure-xplat-cli>azure vm list
info:    Executing command vm list
+ Getting virtual machines
data:    ResourceGroupName      Name                        ProvisioningState  PowerState      Location            Size
data:    ---------------------  --------------------------  -----------------  --------------  ------------------  --------------
data:    VM456TestgROUP       vm456                              Succeeded          VM running      eastus              Basic_A0
data:    CRP3df2              est3df2                            Succeeded          VM running      eastus              Standard_A2
```

This issue is more about the REST API design of the Compute/ARM service and not the CLI itself. Hence I am closing this one.
@singhkay @mahthi would be in a better position to comment if at all there would ever be a change in the REST API of the service.
