### ISSUE TITLE
ARM group deployment create fails with 'msRest.addSerializationMixin is not a function'

### ISSUE THREAD

**Issue by nitrat7** [Azure/azure-xplat-cli#2573]
running on OS X (installed via package) 0.9.15

info:    Executing command group deployment create
error:   Unexpected token 

silly:   {
silly:       stack: 'SyntaxError: Unexpected token \n\n  <<< async stack >>>\n    at Object.parse (native)\n    at createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:229:37)\n  at exports_createDeployment__1 (/usr/local/azure/lib/commands/arm/group/groupUtils.js:69:28)\n  at __1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:62:35)\n  <<< raw stack >>>\n    at Object.parse (native)\n    at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:229:37)\n    at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:245:98)\n    at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)\n    at createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:213:276)\n    at __$exports_createDeployment__1 (/usr/local/azure/lib/commands/arm/group/groupUtils.js:69:12)\n    at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)\n    at Object.exports_createDeployment__1 [as createDeployment] (/usr/local/azure/lib/commands/arm/group/groupUtils.js:65:263)\n    at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:62:29)\n    at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:58:450)',
silly:       rawStack: 'SyntaxError: Unexpected token \n\n    at Object.parse (native)\n    at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:229:37)\n    at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:245:98)\n    at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)\n    at createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:213:276)\n    at __$exports_createDeployment__1 (/usr/local/azure/lib/commands/arm/group/groupUtils.js:69:12)\n    at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)\n    at Object.exports_createDeployment__1 [as createDeployment] (/usr/local/azure/lib/commands/arm/group/groupUtils.js:65:263)\n    at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:62:29)\n    at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:58:450)',
silly:       message: 'Unexpected token \n',
silly:       __frame: {
silly:           name: 'exports_createDeployment__1',
silly:           line: 65,
silly:           file: '/usr/local/azure/lib/commands/arm/group/groupUtils.js',
silly:           prev: {
silly:               name: '__1',
silly:               line: 48,
silly:               file: '/usr/local/azure/lib/commands/arm/group/group.deployment.js',
silly:               prev: undefined,
silly:               calls: 1,
silly:               active: false,
silly:               offset: 14,
silly:               col: 34
silly:           },
silly:           calls: 1,
silly:           active: false,
silly:           offset: 4,
silly:           col: 27
silly:       }
silly:   }
info:    Error information has been recorded to /Users/martingrohme/.azure/azure.err
verbose: SyntaxError: Unexpected token 

  <<< async stack >>>
    at Object.parse (native)
    at createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:229:37)
  at exports_createDeployment__1 (/usr/local/azure/lib/commands/arm/group/groupUtils.js:69:28)
  at __1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:62:35)
  <<< raw stack >>>
    at Object.parse (native)
    at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:229:37)
    at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:245:98)
    at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:213:276)
    at __$exports_createDeployment__1 (/usr/local/azure/lib/commands/arm/group/groupUtils.js:69:12)
    at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.exports_createDeployment__1 [as createDeployment] (/usr/local/azure/lib/commands/arm/group/groupUtils.js:65:263)
    at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:62:29)
    at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:58:450)
error:   group deployment create command failed

msRest.addSerializationMixin is not a function

**Comment by amarzavery** [comment]
Please uninstall the cli.
Npm uninstall azure-cli -g if installed via npm
Sudo azure uninstall -g if installed via Mac installer
Delete ~/.streamline folder.
Now install again via npm or Mac installer
If via npm then Npm install azure-cli -g
And mostly you should be good to go

Thanks,
Amar Zavery

On Feb 23, 2016, at 3:56 AM, "nitrat7" <notifications@github.com<mailto:notifications@github.com>> wrote:


running on OS X (installed via package) 0.9.15

info: Executing command group deployment create
error: Unexpected token

silly: {
silly: stack: 'SyntaxError: Unexpected token \n\n <<< async stack >>>\n at Object.parse (native)\n at createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:229:37)\n at exports_createDeployment__1 (/usr/local/azure/lib/commands/arm/group/groupUtils.js:69:28)\n at __1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:62:35)\n <<< raw stack >>>\n at Object.parse (native)\n at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:229:37)\n at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:245:98)\n at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)\n at createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:213:276)\n at __$exports_createDeployment__1 (/usr/local/azure/lib/commands/arm/group/groupUtils.js:69:12)\n at __func (/usr/local/azure/n ode_modu les/streamline/lib/callbacks/runtime.js:47:5)\n at Object.exports_createDeployment__1 as createDeployment</usr/local/azure/lib/commands/arm/group/groupUtils.js:65:263>\n at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:62:29)\n at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:58:450)',
silly: rawStack: 'SyntaxError: Unexpected token \n\n at Object.parse (native)\n at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:229:37)\n at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:245:98)\n at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)\n at createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:213:276)\n at __$exports_createDeployment__1 (/usr/local/azure/lib/commands/arm/group/groupUtils.js:69:12)\n at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)\n at Object.exports_createDeployment__1 as createDeployment</usr/local/azure/lib/commands/arm/group/groupUtils.js:65:263>\n at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:62:29)\n at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:58:450)',
silly: message: 'Unexpected token \n',
silly: __frame: {
silly: name: 'exports_createDeployment__1',
silly: line: 65,
silly: file: '/usr/local/azure/lib/commands/arm/group/groupUtils.js',
silly: prev: {
silly: name: '__1',
silly: line: 48,
silly: file: '/usr/local/azure/lib/commands/arm/group/group.deployment.js',
silly: prev: undefined,
silly: calls: 1,
silly: active: false,
silly: offset: 14,
silly: col: 34
silly: },
silly: calls: 1,
silly: active: false,
silly: offset: 4,
silly: col: 27
silly: }
silly: }
info: Error information has been recorded to /Users/martingrohme/.azure/azure.err
verbose: SyntaxError: Unexpected token

<<< async stack >>>
at Object.parse (native)
at createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:229:37)
at exports_createDeployment__1 (/usr/local/azure/lib/commands/arm/group/groupUtils.js:69:28)
at __1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:62:35)
<<< raw stack >>>
at Object.parse (native)
at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:229:37)
at __$createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:245:98)
at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)
at createDeploymentParameters (/usr/local/azure/lib/commands/arm/group/groupUtils.js:213:276)
at __$exports_createDeployment__1 (/usr/local/azure/lib/commands/arm/group/groupUtils.js:69:12)
at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)
at Object.exports_createDeployment__1 as createDeployment</usr/local/azure/lib/commands/arm/group/groupUtils.js:65:263>
at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:62:29)
at __$__1 (/usr/local/azure/lib/commands/arm/group/group.deployment.js:58:450)
error: group deployment create command failed

msRest.addSerializationMixin is not a function

-

**Comment by nitrat7** [comment]
Hello Amar, thanks for fast feedback!

I uninstalled azure-cli, deleted .streamline-folder and installed azure-cli via NPM...

but group deployment create still fails with exact same error-message - no audit-logs visible in Azure-portal :-(

**Comment by nitrat7** [comment]
Hello Amar,
I found problem, passed over json-string with "-e" parameter, that was malformed.
This has lead to this strange error-message..

maybe you can validate json and give appropriate error-message?

Thanks for fast reply!

**Comment by amarzavery** [comment]
@nitrat7 - Thanks for the feedback, we will improve the experience.
