### ISSUE TITLE
ASM: Azure network application gateway ssl-cert add has issues

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#2575]
CLI Version: **0.9.15**
OS Type: RedHat 6.7
Installation via:  npm

Mode: **ASM**

Description:
`azure network application-gateway ssl-cert add` command doesn't add the SSL certificates.

Steps to reproduce:
1) Run `azure network application-gateway create --name testgw --vnet-name TestNet --subnet-names "Subnet-1" --gateway-size "Small"`
2) Then run `azure network application-gateway ssl-cert add --name testgw --cert-name GWCert --cert-file selfcert/my_pkcs12.pfx`

Error:
**info:    Executing command network application-gateway ssl-cert add
Certificate password: test
+ Adding SSL certificate "GWCert" to Application Gateway "testgw"              
error:   object is not a function
info:    Error information has been recorded to /home/samanoha/.azure/azure.err**

Error stack trace:

**2016-02-24T10:08:46.866Z:
[TypeError: object is not a function]
TypeError: object is not a function
    at /usr/lib/node_modules/azure-cli/node_modules/azure-asm-network/lib/networkManagementClient.js:360:24
    at /usr/lib/node_modules/azure-cli/node_modules/azure-asm-network/lib/networkManagementClient.js:2488:14
    at /usr/lib/node_modules/azure-cli/lib/util/logging.js:401:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/lib/util/utils.js:459:9)
    at /usr/lib/node_modules/azure-cli/lib/util/utils.js:482:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/redirectfilter.js:36:9)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:49:7
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.emit (events.js:98:17)
**

If verbose mode output is needed, i can send via email

**Comment by MikhailTryakhov** [comment]
Hi @infosatheesh2020 thank you again for your feedback. Would provide you details soon

**Comment by MikhailTryakhov** [comment]
Fixed
