### ISSUE TITLE
Remove the apiapp commands

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-xplat-cli#2586]
The backend service is pulled down and commands are useless now.
So, start with the [commands](https://github.com/Azure/azure-xplat-cli/tree/dev/lib/commands/arm/apiapp) 
and test, and then all global file change, such as the 4 new package references added into the package.json. 
Just get rid of everything,

**Comment by romangromov** [comment]
@yugangw-msft can I do this? :)

**Comment by yugangw-msft** [comment]
@romangromov , thank you!
