### ISSUE TITLE
azure account download / import

### ISSUE THREAD

**Issue by ptman** [Azure/azure-xplat-cli#2595]
CLI Version: 0.9.14
OS Type: Linux (Debian)
Installation via: docker

Mode: ARM

Description:
The README.md lists commands in the "Get Started" -section that don't appear to work: <https://github.com/Azure/azure-xplat-cli/blame/dev/README.md#L124>

**Comment by romangromov** [comment]
related issue https://github.com/Azure/azure-xplat-cli/issues/2452

**Comment by amarzavery** [comment]
@ptman - azure account download tries to open a browser for downloading the publish settings file. This command will not work on an ssh terminal. It still displays the link from which one can download. 

We need to improve the user experience. 
1. Provide an info or a warning to the user about the command trying to open a browser.
2. Try and find out if, the browser cannot be opened then try to do a wget or curl

**Comment by ptman** [comment]
@amarzavery 

No link:

    $ docker run -it microsoft/azure-cli
    # azure account download
    error:   'download' is not an azure command. See 'azure help'.

**Comment by amarzavery** [comment]
@ptman - You must be in ARM mode (V2 Azure API)
please execute: `azure config mode asm`
ARM APIs use token based authentication and ASM APIs use cert based auth. `azure account download` downloads the publish settings file which is used to authenticate via cert based auth for ASM (V1) APIs.

**Comment by amarzavery** [comment]
```
D:\sdk>azure account download
info:    Executing command account download
info:    Launching browser to http://go.microsoft.com/fwlink/?LinkId=254432
help:    Save the downloaded file, then execute the command
help:      account import <file>
info:    account download command OK
```

**Comment by ptman** [comment]
In that case I suggest the README make it clear which ones work for ARM and which ones need ASM.

**Comment by bjtucker** [comment]
Also please fix up the error message. Shouldn't need to dig into the source repo to find this kind of simple stuff out. What a frustrating waste of time.
