### ISSUE TITLE
ARM: Role deletion has issues

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#2599]
CLI Version: **0.9.15**
OS Type: RHEL6
Installation via:  npm

Mode: **ARM**

Description:
`azure role delete --id xxxxx` command doesn't delete the assigned role from portal

Steps to reproduce:
1) Create a resource group in ARM
2) Add a user as reader role for the resource group using azure portal
2) Then try to delete the resource group using CLI. (get the role definition id using 'azure role assignment list')
azure role delete --id xxxx
info:    Executing command role delete
Delete role definition "xxxx"? [y/n] y
+ Deleting role definition with id "xxxx"      
error:   Error
info:    Error information has been recorded to /home/samanoha/.azure/azure.err
error:   role delete command failed

Error stack trace:

**2016-03-04T11:12:07.710Z:
{ [Error]
  stack: [Getter/Setter],
  statusCode: 204,
  __frame: 
   { name: '__5',
     line: 341,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/role/role.definition._js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 47,
     col: 44 },
  rawStack: [Getter] }
Error: 
  <<< async stack >>>
  at __5 (/usr/lib/node_modules/azure-cli/lib/commands/arm/role/role.definition._js:388:45)
  <<< raw stack >>>
    at /usr/lib/node_modules/azure-cli/node_modules/azure-arm-authorization/lib/authorizationManagementClient.js:3039:21
    at /usr/lib/node_modules/azure-cli/lib/util/logging.js:401:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/redirectfilter.js:36:9)
    at /usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/services/filters/errorhandlingfilter.js:49:7
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/lib/http/request-pipeline.js:109:14)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:199:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1160:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/azure-cli/node_modules/azure-common/node_modules/request/request.js:1111:12)
**

I can send verbose output via email if required.

**Comment by amarzavery** [comment]
The Authorization team is coming with an update to the Authorization commands in the next release due (in the month of April). 
@shuagarw - Please take a look at this issue and make sure this does not occur in the update.

**Comment by amarzavery** [comment]
infosatheesh2020 - there was a hotfix for role commands in the last week. Can you try to install 0.9.18 version from npm and see if that solves your issue?

**Comment by infosatheesh2020** [comment]
@amarzavery Still this issue occurs in 0.9.18 as well

**Comment by shuagarw** [comment]
@infosatheesh2020 - I don't understand the actual issue here. So, you are trying to delete a resource/resourceGroup here or role definition? For deleting resource - please use "azure resource delete" command.
You can only delete custom roles, which you have created in your subscription. For e.g. you can't delete builtIn roles like (Reader, VM Contributor etc.). Please give me a concrete example of which role you are trying to delete with the role entity.

**Comment by amarzavery** [comment]
@infosatheesh2020 -  The command to execute is
`azure role assignment delete` . The command `azure role delete` is about deleting the role definition and the former is for deleting the role assignment.

Have verified that both commands work. As @shuagarw mentioned that **inbuilt role definitions** cannot be deleted. However role assignments and custom role definitions can be deleted.

Closing this issue.
