### ISSUE TITLE
Break Blog Lease

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/azure-xplat-cli#2600]
There is still some issues with VMs not cleaning up their leases on blob disks when deleted. This leaves some substantially large files blocked from being deleted until the lease is broken.

Providing a facility in the CLI to break the lease would make this much easier to over come.

**Comment by yaxia** [comment]
ETA of the fix: June release

**Comment by yaxia** [comment]
We have added lease commands in the 0.10.1. Please take a try.
