### ISSUE TITLE
Feature Request: CLI doesn't support resizing OS disk though Powershell API does

### ISSUE THREAD

**Issue by kirpasingh** [Azure/azure-xplat-cli#2601]
CLI Version: **0.9.X**
OS Type: Mac / Win / Linux (Ubuntu, RedHat, etc.)
Installation via:  npm / brew / win-or-mac installer / docker / github repo

Mode: **ARM**

Description:
`azure vm disk -h` command shows the following options:
Attach a new data-disk to a VM in a resource group
```vm disk attach-new [options] <resource-group> <vm-name> <size-in-gb> [vhd-name]```

Detach a data-disk attached to a VM in a resource group
```vm disk detach [options] <resource-group> <vm-name> <lun>```

Attach a new data-disk to a VM in a resource group
 ```vm disk attach [options] <resource-group> <vm-name> [vhd-url]```

Get all data disks of a VM in a resource group
 ```vm disk list [options] <resource-group> <vm-name>```

Apparently no disk resizing operation is supported.

Here are the steps to resize OS disk in Powershell: 

```Powershell
$vm = Get-AzureRmVM -ResourceGroupName <resource-group-name> -Name <vm-name>
$vm.StorageProfile.OSDisk.DiskSizeGB = 1023
Update-AzureRmVM -ResourceGroupName <resource-group-name> -VM $vm
```

**Comment by squillace** [comment]
@kirpasingh love it. What I want to know is whether there's any `azure resource set` command and json that can perform the same action in the meanwhile.

**Comment by kirpasingh** [comment]
@squillace Apparently I didn't know much about ```azure resource set``` command and thank you very much for bringing this up! It's not something obvious as I had to spend more than an hour to figure this out but here's a possible way (worked for me):
```
azure vm deallocate -g my-resource-group -n my-vm
azure resource set --resource-group bluedsctest --name bluemanaged00 --resource-type Microsoft.Compute/VirtualMachines --properties "{ \"storageProfile\":{\"osDisk\":{\"diskSizeGB\": 1023}}}" -o 2015-06-15
azure vm start -g my-resource-group -n my-vm
```
And I did a dump afterwards using ```azure resource show``` with json output showing the new size!

**Comment by squillace** [comment]
@kirpasingh hey, that's GREAT! I'll try to repro tomorrow; if we can, I'd like to use this to doc the OS resizing version. I noticed that in PS, other than which disk you grab, resizing both the os disk and any datadisks are the same. With this method, I trust you still have to go in and resize the partition before it can be used? I work with linux, hence my thoughts here. I want one topic on "resizing OS and data disks with the CLI" and we'll use this method. What do you think? I'll sketch it out, using what you have, and we can write it together.

**Comment by kirpasingh** [comment]
@squillace Thanks! In Windows, you have to log in and format the partition before using, so I guess the same applies for Linux as you mentioned. I'd definitely love to get this out, so please feel free to sketch it out when you've time!

**Comment by singhkay** [comment]
A possible solution that doesn't involve the hacky way above was discussed this week. As for timelines @sauryadas @huangpf are your best people

**Comment by squillace** [comment]
@singhkay the question is how do you apply it now. :-)

**Comment by kirpasingh** [comment]
@singhkay Thank you for looping in folks! However I'm not sure why the aforementioned method is "hackish"? It seems like a REST API PATCH call under the covers to update the resource [as documented here](https://msdn.microsoft.com/en-us/library/azure/mt163591.aspx#bk_osdisk) and moreover isn't the cmdlet ```azure set resource``` built for updating (or even adding) resources to an Azure resource such as a VM (as in this case)? Though, please excuse my oversight if I'm missing something here!

**Comment by singhkay** [comment]
@kirpasingh That's what I mean. You shouldn't have to call the REST api form CLI to do this. The `azure resource set` command should be updated to allow this and call the REST API under the covers

**Comment by squillace** [comment]
@singhkay do you mean, "we should add a direct utility command for this to something like "azure vm disk-resize" to the CRP commands? I agree. But for now, this is exactly how the "generic" resource set command should work.

**Comment by amarzavery** [comment]
@singhkay
The customer needs to know the api-version, resource provider, parent resources if any to achieve this. This is a bad user experience. The compute team should provide a proper command to do the disk resize operation.

Thanks,
Amar Zavery

On Mar 11, 2016, at 11:01 AM, "Kay Singh" <notifications@github.com<mailto:notifications@github.com>> wrote:


@kirpasingh<https://github.com/kirpasingh> That's what I mean. You shouldn't have to call the REST api form CLI to do this. The azure resource set command should be updated to allow this and call the REST API under the covers

-

**Comment by squillace** [comment]
Yep. All the same, it's the same experience as REST. In other words, crappy, but functional for now. :-)

**Comment by squillace** [comment]
Hey, @amarzavery, where are we on this one?

**Comment by amarzavery** [comment]
It is the compute team, who has to triage this and provide a timeline for the fix.
@mahthi @singhkays @huangpf @sauryadas - Please let us know when can this be done?

**Comment by iandow** [comment]
I'm looking forward to this feature.

**Comment by phagunbaya** [comment]
Hey guys,

Is there any way to pass on OS disk size property while provisioning the VM from azure client or azure template ?

**Comment by amarzavery** [comment]
As you can see the PR #2601 for resizing disk was merged 5 days ago. The new release will be out by 9/28.

If you need this right now then follow the instructions over [here](https://github.com/Azure/azure-xplat-cli#installation-from-a-particular-branch-of-this-repository) to install the source code from dev branch of this repo and you should be good to go.

**Comment by phagunbaya** [comment]
@amarzavery : Yes, I see that resizing is available. But what I wanted to know - is there any support to change the OS disk size while **creating** a VM.

**Comment by amarzavery** [comment]
`azure vm create` has an option
`help:      -e, --data-disk-size <data-disk-size>                                  data disk size in GB`
the help should tell you more about it.

Once you have specified this option and the command is being executed then while the VM is being provisioned I dont think you can change the size. After it is provisioned if you want to change the disk-size then use the `azure vm set` command.

**Comment by huangpf** [comment]
@phagunbaya Please file a new issue to track, as it's different.
