### ISSUE TITLE
Login for AzureUSGovernment is throwing an error for endpoint

### ISSUE THREAD

**Issue by shuagarw** [Azure/azure-xplat-cli#2602]
CLI Version: **0.9.19**
OS Type: Win
Installation via:  Installer

Mode: ARM

Description:
`azure login -e AzureUSGovernment` gives an error

e:\>azure login -e AzureUSGovernment
info:    Executing command login
\info:    To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code BGLT7F4C5 to authenticate.
+
error:   The access token has been obtained from wrong audience or resource 'https://management.core.usgovcloudapi.net/'. It should exactly match (including forward slash) with one of the allowed audiences 'https://management.core.windows.net/','https://management.azure.com/'.
info:    Error information has been recorded to C:\Users\shuagarw\.azure\azure.err
error:   login command failed

Error stack trace:

2016-03-04T23:07:22.743Z:
{ [Error: The access token has been obtained from wrong audience or resource 'https://management.core.usgovcloudapi.net/'. It should exactly match (including forward slash) with one of the allowed audiences 'https://management.core.windows.net/','https://management.azure.com/'.]
  stack: [Getter/Setter],
  statusCode: 401,
  request: 
   { rawResponse: false,
     queryString: {},
     method: 'GET',
     headers: 
      { 'x-ms-client-request-id': '99c7e77d-ea69-423b-9310-9d4b6bbe0a61',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8' },
     url: 'https://management.azure.com/tenants?api-version=2015-11-01',
     body: null },
  response: 
   { body: '{"error":{"code":"InvalidAuthenticationTokenAudience","message":"The access token has been obtained from wrong audience or resource \'https://management.core.usgovcloudapi.net/\'. It should exactly match (including forward slash) with one of the allowed audiences \'https://management.core.windows.net/\',\'https://management.azure.com/\'."}}',
     headers: 
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'www-authenticate': 'Bearer authorization_uri="https://login.windows.net/", error="invalid_token", error_description="The access token is from wrong audience or resource."',
        'x-ms-failure-cause': 'gateway',
        'x-ms-request-id': '487b6425-16c4-4db7-bea3-5d473cc41fec',
        'x-ms-correlation-request-id': '487b6425-16c4-4db7-bea3-5d473cc41fec',
        'x-ms-routing-request-id': 'WESTUS:20160304T230722Z:487b6425-16c4-4db7-bea3-5d473cc41fec',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        date: 'Fri, 04 Mar 2016 23:07:22 GMT',
        connection: 'close',
        'content-length': '336' },
     statusCode: 401 },
  code: 'InvalidAuthenticationTokenAudience',
  body: 
   { code: 'InvalidAuthenticationTokenAudience',
     message: 'The access token has been obtained from wrong audience or resource \'https://management.core.usgovcloudapi.net/\'. It should exactly match (including forward slash) with one of the allowed audiences \'https://management.core.windows.net/\',\'https://management.azure.com/\'.' },
  __frame: 
   { name: '__1',
     line: 49,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\login.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 64,
     col: 27 },
  rawStack: [Getter] }
Error: The access token has been obtained from wrong audience or resource 'https://management.core.usgovcloudapi.net/'. It should exactly match (including forward slash) with one of the allowed audiences 'https://management.core.windows.net/','https://management.azure.com/'.
  <<< async stack >>>
  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\login.js:113:28)
  <<< raw stack >>>
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-arm-resource\lib\subscription\operations\tenants.js:114:19
    at retryCallback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\node_modules\ms-rest\lib\filters\redirectFilter.js:36:9)
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\node_modules\ms-rest\lib\requestPipeline.js:125:16)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:344:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:1239:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)

**Comment by yugangw-msft** [comment]
This is a bug which might get exposed by ADD tightening up the token sharing for multiple resources.
The code line which need to change is on. [The line](https://github.com/Azure/azure-xplat-cli/blob/dev/lib/util/profile/account.js#L202) need to change to use the baseuri from current environment.
@shuagarw, can you confirm this is regression from previous version. It doesn't really look like
