### ISSUE TITLE
ARM: Keyvault creation using templates

### ISSUE THREAD

**Issue by infosatheesh2020** [Azure/azure-xplat-cli#2606]
CLI Version: **0.9.15**
OS Type: RHEL6
Installation via:  npm

Mode: **ARM**

Description:
I am trying to create keyvault from ARM template similar to https://azure.microsoft.com/en-in/documentation/articles/resource-manager-template-keyvault-secret/

But I dont find CLI commands to pass the template file or template URI as input in 'azure keyvault create' command. Do we have any plans to support this (and when)?

**Comment by colemickens** [comment]
You can create KeyVaults using ARM templates. All ARM template creation is done via `azure group create`.

**Comment by infosatheesh2020** [comment]
@colemickens, Thanks. Got it.

can you help me to get a template to add keys to vault (how to reference keys from local machine to add in vault)

**Comment by colemickens** [comment]
If you show me what you have I can try to see if there's something obviously wrong. This is the schema file that describes what the KeyVault JSON should look like:

https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2015-06-01/Microsoft.KeyVault.json

You can read that to see what the schema looks like for adding keys/secrets via a template.

**Comment by infosatheesh2020** [comment]
@colemickens Thanks for the help.

I use below json snippet to add secrets in existing vault

"resources": [
        {
            "type": "Microsoft.KeyVault/vaults/secrets",
            "apiVersion": "2015-06-01",
            "name": "[concat(parameters('keyVaultName'), '/', parameters('secretName'))]",
            "properties": {
                "value": "[parameters('secretValue')]"
            }
        },
        {
            "type": "Microsoft.KeyVault/vaults/keys",
            "apiVersion": "2015-06-01",
            "name": "[concat(parameters('keyVaultName'), '/', parameters('keyName'))]",
            "properties": {
                "value": "[parameters('keyValue')]"
            }
        }
    ]

And the parameter json is:
{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "keyVaultName": {
      "value": "myvault1"
    },
    "secretName": {
      "value": "mypassword"
    },
    "secretValue": {
      "value": "test"
    }
  }
}

Similarly, I have a local PEM file which needs to be added in vault using template. can you help me the syntax for referencing "keyValue" to local PEM in parameters file.

Also, I want to reference the key added to vault into the provisioning script and I use format as below:

"sshRSAPublicKey": {
      "reference": {
        "keyVault": {
          "id": "/subscriptions/xxxxxx/resourceGroups/vaultRG/providers/Microsoft.KeyVault/vaults/mmdvault"
        },
        "keyName": "qa-key"
      }
    },

But error is "The request content was invalid and could not be deserialized: 'Could not find member 'keyName' on object of type 'KeyVaultParameterReference'. Path 'properties.parameters.sshRSAPublicKey.reference.keyName'"

I use the same in OS profile of VM

"osProfile": {
          "computerName": "[variables('vmName')]",
          "adminUsername": "[parameters('adminUsername')]",
          "ssh": {
            "publicKeys": [
              {
                "keyData": "[parameters('sshRSAPublicKey')]"
              }
            ]
          }
        }
But when I refer secret i use "secretName" instead of keyName in parameters and it works.

can you please help me here.

**Comment by colemickens** [comment]
I'm not 100% sure here.

I would recommend you file an issue over at https://github.com/Azure/azure-quickstart-templates. They have a few KeyVault examples, but I didn't see anything that shows how to add keys/secrets as part of the template deployment. It would make for a good sample and help unblock you.

**Comment by infosatheesh2020** [comment]
@colemickens thanks!

Issue raised in https://github.com/Azure/azure-quickstart-templates. (1350 & 1349)
