### ISSUE TITLE
ARM: App Gateways commands not available

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2607]
Opened an issue to track the process of the App Gateways commands in ARM mode.

#2413 is closed and could anyone please update the current status of the latest PR?

Thanks

**Comment by MikhailTryakhov** [comment]
There is still an issue on the SDK side - it blocks any set operation on app gateway.
We're working on the fix

**Comment by romangromov** [comment]
@MikhailTryakhov we are using SDK from Autorest, so you can fix SDK issue, send PR [here](https://github.com/Azure/autorest), gererate SDK for Node and send PR
[here](https://github.com/Azure/azure-sdk-for-node/tree/autorest/lib/services/networkManagement2)

**Comment by MikhailTryakhov** [comment]
Sorry @romangromov, issue not on SDK side, but on the server side

**Comment by amarzavery** [comment]
@bingosummer - This should be available in the upcoming release 0.9.19 which should be out by April 1.
The commands were implemented in the PR https://github.com/Azure/azure-xplat-cli/pull/2680
@MikhailTryakhov - Is that correct ?

**Comment by MikhailTryakhov** [comment]
@amarzavery, @bingosummer absolutelly correct.

**Comment by bingosummer** [comment]
Thanks @MikhailTryakhov , @amarzavery  and @romangromov .
Appreciate all your help.
Will test it after 0.9.19 is released.

**Comment by romangromov** [comment]
Hi @bingosummer, `0.9.20` realized, app gateways commands included. Can you give it a chance try and come back? Thanks

**Comment by bingosummer** [comment]
sure.I will try it.

**Comment by bingosummer** [comment]
@romangromov 
Since I have some other works in hand, it will take some time to try app gateways commands.
