### ISSUE TITLE
vm create with --json doesn't work

### ISSUE THREAD

**Issue by clayrichardson** [Azure/azure-xplat-cli#2613]
CLI Version: **0.9.15**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Description:
`azure vm create --ssh-publickey-file` doesn't populate authorized_keys with ssh key
it doesn't produce any json out either.

Steps to reproduce:
1) Run `azure vm create ` (details attached below)
2) Use your eyeballs

```
azure vm create --name jumpbox3 --nic-name concourse-jumpbox3-nic --location westus --os-type Linux --image-urn Canonical:UbuntuServer:14.04.2-LTS:latest --admin-username vcap --admin-password 'REDACTED' --vm-size Standard_D2_v2 --vnet-name concourse-network --vnet-subnet-name jumpbox1 --storage-account-name REDACTED --subscription REDACTED --resource-group REDACTED --ssh-publickey-file /concourse/bosh.key.pub --verbose --json
info:    Executing command vm create
verbose: Looking up the VM "jumpbox3"
info:    Verifying the public key SSH file: /concourse/bosh.key.pub
info:    Using the VM Size "Standard_D2_v2"
info:    The [OS, Data] Disk or image configuration requires storage account
verbose: Looking up the storage account concoursecfhosted2016
verbose: Looking up the NIC "concourse-jumpbox3-nic"
info:    An nic with given name "concourse-jumpbox3-nic" not found, creating a new one
verbose: Looking up the virtual network "concourse-network"
info:    Found an existing virtual network "concourse-network"
info:    Existing Subnets:
info:      jumpbox1:10.10.4.0/24
info:      jumpbox2:10.10.5.0/24
info:    Verifying subnet
verbose: Looking up the subnet "jumpbox1" under the virtual network "concourse-network"
info:    Subnet with given name "jumpbox1" exists under the virtual network "concourse-network", using this subnet
info:    No public ip parameters found, the ip configuration of new NIC will have only subnet configured
verbose: Creating NIC "concourse-jumpbox3-nic"
verbose: Looking up the NIC "concourse-jumpbox3-nic"
info:    The storage URI 'https://REDACTED.blob.core.windows.net/' will be used for boot diagnostics settings, and it can be overwritten by the parameter input of '--boot-diagnostics-storage-uri'.
verbose: Creating VM "jumpbox3"
info:    vm create command OK
```

**Comment by amarzavery** [comment]
@huangpf - The info messages should not be displayed in the --json mode. Nothing should be displayed except crisp json.

**Comment by huangpf** [comment]
@clayrichardson 
To debug the actual request/response payloads, please use the ```-vv``` option.

I'm looking at your other related issue about SSH public key, and would follow up to clean up the ```verbose``` & ```json``` display issues.

**Comment by clayrichardson** [comment]
@huangpf — Thanks!

**Comment by amarzavery** [comment]
@clayrichardson - This PR https://github.com/Azure/azure-xplat-cli/pull/2634 should fix the --json issue.

You can download the tarball from the dev branch of xplat-cli https://github.com/Azure/azure-xplat-cli/archive/dev.tar.gz and then execute 
1. `sudo rm -rf ~/.streamline`
2. `sudo npm uninstall azure-cli -g`
3. `sudo npm install -g "path-to-downlaoded-tar.gz"` 

to verify if the merged PR solves your issue. If you find any issues then let us know.

**Comment by sauryadas** [comment]
@amarzavery closing this. The creator of the bug @clayrichardson  can reopen if this is not fixed yet.
