### ISSUE TITLE
Failed ARM commands on windows return exit code 0

### ISSUE THREAD

**Issue by robbyt** [Azure/azure-xplat-cli#2615]
CLI Version: **0.9.16**
OS Type: Windows 7 
Installation via:  win installer

Mode: **ARM**

Description:
When a command fails, it should return a non-zero exit code. This is broken in 0.9.16:

```
C:\Users\rob>azure group list
info:    Executing command group list
+ Listing resource groups
error:   We don't have a valid access token. Please run "azure login" again.
info:    Error information has been recorded to C:\Users\rob\.azure\azure.err
error:   group list command failed


C:\Users\rob>echo Exit Code is %errorlevel%
Exit Code is 0
```

Steps to reproduce:
1) set azure cli to arm mode
2) run a command that should fail (example above)
2) text exit code

**Comment by robbyt** [comment]
A bit more information on this.

When a command line program runs successfully, it should return an exit code of 0, if there are errors, it should return another exit code to communicate information about the error (the most common is 1).

The behavior of the azure cli is inconsistent on Windows. On non-Windows platforms (Linux/OSX), the azure cli returns exit code 1, when there are errors. However, on Windows the azure cli always returns exit code 0 regardless if there's an error.

The reason why people use cli tools is for scripting & automation purposes. Since the azure cli on Windows does not return a valid exit code, it makes scripting very difficult.

**Comment by amarzavery** [comment]
Thanks for reporting this issue. This has been fixed now.
```
D:\sdk\azure-xplat-cli>azure group list
info:    Executing command group list
+ Listing resource groups
error:   We don't have a valid access token. Please run "azure login" again.
info:    Error information has been recorded to C:\Users\amzavery\.azure\azure.err
error:   group list command failed

D:\sdk\azure-xplat-cli>echo Exit Code is %errorlevel%
Exit Code is 1
```
