### ISSUE TITLE
bug: azure group log show <rg> command unable to find resource group

### ISSUE THREAD

**Issue by lbrader** [Azure/azure-xplat-cli#2625]
CLI Version: **0.9.16**
OS Type: Win 10
Installation via:   github repo

Mode: **ARM **

Description:
''azure group log show <some resource group>'  errors out saying the deployment doesn't exist

Steps to reproduce:
1) Run `azure resource create ....' create a resource group
OR
2) Run 'azure group list' select any resource
3) Then run `azure group log show <existing RG>'

NOTE
4) Run 'azure group log show -a <same existing RG>'  THIS COMMAND works. 
None of the others work

Error stack trace:
2016-03-10T23:29:40.885Z:
{ [Error: Deployment not found]
  stack: [Getter/Setter],
  __frame: 
   { name: '_read',
     line: 235,
     file: 'C:\\Users\\lbrader\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\node_modules\\streamline-streams\\lib\\streams._js',
     prev: 
      { name: 'self_read__1',
        line: 234,
        file: 'C:\\Users\\lbrader\\AppData\\Roaming\\npm\\node_modules\\azure-cli\\node_modules\\streamline-streams\\lib\\streams._js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 22,
        col: 93 },
     calls: 0,
     active: false,
     offset: 2,
     col: 27 },
  rawStack: [Getter] }
Error: Deployment not found
  <<< async stack >>>
  at _read (C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline-streams\lib\streams._js:237:28)
  at self_read__1 (C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\node_modules\streamline-streams\lib\streams._js:256:94)
  at __7 (C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\group._js:382:32)
  <<< raw stack >>>
    at C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\lib\commands\arm\group\groupUtils._js:194:28
    at C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\node_modules\azure-arm-resource\lib\resource\operations\deployments.js:1358:12
    at retryCallback (C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\node_modules\ms-rest-azure\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\node_modules\ms-rest-azure\node_modules\ms-rest\lib\filters\redirectFilter.js:36:9)
    at C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:493:7
    at handleRedirect (C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\lib\util\utils.js:470:9)
    at C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\lib\util\logging.js:401:7
    at Request._callback (C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\node_modules\ms-rest-azure\node_modules\ms-rest\lib\requestPipeline.js:125:16)
    at Request.self.callback (C:\Users\lbrader\AppData\Roaming\npm\node_modules\azure-cli\node_modules\ms-rest-azure\node_modules\ms-rest\node_modules\request\request.js:199:22)
    at emitTwo (events.js:87:13)

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).

**Comment by amarzavery** [comment]
@lbrader - The `azure group log show` command is used for showing the deployment logs.
For example: After deploying a template via `azure group deployment create` command, if you want to see the deployment logs then you would execute the `azure group log show` command.

To get more info about the resource group you created, you can execute `azure group show` command.

Let us know, exactly what are you trying to achieve.

**Comment by lbrader** [comment]
I understand the command.  It doesn't work.  See filed bug.  I just tried again - same result.  
Did you even try this command?  If it worked for you what version are you running?

"azure group log show" comes back as says' enter a resource group name. SO
"azure group log show <someRG>"  .  

It fails - Deployment not found.  

What am I trying to do is build a tool to query through the log file looking for errors and warnings.

**Comment by amarzavery** [comment]
Yes I have run the command. 
The group log show command requires resource group as a required parameter. If not provided then it will enter in interactive mode and prompt the user to provide resource group name.

The **basic pre-requisite** to do a group log show is to actually create a deployment via `group deployment create` command. The group log show command displays the logs of the last deployment that was created under the resource group, if the deployment name was not provided.

If this command is used with --json switch then it will display detailed logs sent from the server

```
D:\work\sdk>azure group log show -h
help:    Retrieves and shows logs for resource group operations
help:
help:    Usage: group log show [options] [name]
help:
help:    Options:
help:      -h, --help                        output usage information
help:      -v, --verbose                     use verbose output
help:      -vv                               more verbose with debug output
help:      --json                            use json output
help:      -n --name <name>                  the resource group name
help:      -a --all                          returns logs for all operations (including CRUD and deployment)
help:      -l --last-deployment              returns logs for the last deployment
help:      -d --deployment <name>            the name of the deployment whose logs you want to see
help:      -s --subscription <subscription>  the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)

```

**Comment by lbrader** [comment]
Thanks for following up.  So, the confusion may be in our understanding how we are doing our deployment.
And what is meant by "azure group deployment" in CLI

We have created a CLI script to create a resource group and build out VNET, load balancer and 2 VMs with a public IP.   We can then see this deployment via the Portal.

We have never used the command "azure group deployment create"  .Why should we? 
Is this critical in building out any deployment?  Do you links to do further reading/examples?

I still believe there is an error.  I can create a Resource Group and deploy various artifacts into the Resource Group. And the deployment functions as expected.  

If I enter the command "azure group log show app1-dev-rg"
I get an error : group log show command failed

If I enter the same command "azure group log show app1-dev-rg --all" I get the log file. And if I add --json, I get a JSON output.

So is the reason the first command failed is because we didn't use create our deployment with the CLI command "azure group deployment create 'resourcegroup'"?  

Are we missing an important step in creating our deployments?  

I haven't looked at any ARM template generated resource groups.  I'll look at that today.

**Comment by lbrader** [comment]
The simple fix is to update the documentation.  Where is it located and I could take a pass.

**Comment by ravbhatnagar** [comment]
@lbrader - When you run azure group log show command without any params, by default it will show the logs from the last template deployment. In your case, you didn't had any, but still it should not have failed but returned and empty object. We will fix this. 

When you ran this command with the --all, it will return the logs for all the operations (including CRUD and template deployment). And which is why you saw the log file. 

As far as the part about using templates for your deployment is concerned, it is the recommended way since it will allow you to make your deployments repeatable, idempotent. You will be able to create the same set of resources in any environment (dev, test, prod etc.) using that template without having to manually create/configure resources every time. If you want to learn more about template deployments a good starting point is this - https://azure.microsoft.com/en-us/documentation/articles/resource-group-overview/#template-deployment

Please let us know if you have more questions.

**Comment by ravbhatnagar** [comment]
Looks like this has been addressed. Let us know if anything is missing. Closing for now.
