### ISSUE TITLE
Missing support for setting gateway SKU on VPN gateways

### ISSUE THREAD

**Issue by manikrish** [Azure/azure-xplat-cli#2637]
CLI Version: **0.9.16**
OS Type: Win 
Installation via:  win-or-mac installer
Mode: **ARM**

Description:
azure network vpn-gateway create does not allow setting the Gateway SKU

Steps to reproduce:
1) azure network vpn-gateway create -h
The vpn gateway can be "Basic" "Standard" or "HighPerformance"
The equivalent powershell script New-AzureRmVirtualNetworkGateway allows setting the SKU but the cli does not. This blocks customers from being able to select a particular SKU. Each SKU has different performance characteristics.

**Comment by romangromov** [comment]
@manikrish thanks for flagging, will add support for SKU

**Comment by romangromov** [comment]
@manikrish ok, I've send PR to **dev** branch, You can apply patch locally or just wait for next cli public release of 0.9.19.

Also adding more info about SKU in VPN Gateways:
```

1)	What is difference between SKU name and tire? 
[manjuch] In case of Gateway resource these 2 are same.  Tier signifies the features enabled for that SKU. Name is the name of the SKU.  Capacity is the number of instances or IPs allocated to the resource for that particular SKU. It’s always 2 for gateway. 
2)	Is it possible to create VPN Gateway with different SKU name and tire, for example: skuName=Standard, skuTier=HighPerfomance? Or SKU name must always be the same as tier?
[manjuch] NO
3)	Is it possible to change VPN Gateway SKU after Gateway creation? I mean change SKU with PATCH method;
[manjuch] yes. SKU can be changed
4)	Is it possible  to provide SKU Capacity on client side or it is read-only field which will be assigned by server after gateway creation? (capacity of 2 is default value now)
[manjuch] Read only
5)	What is valid range for SKU Capacity? Which value should I use if capacity not provided on Xplat-CLI side?
[manjuch] capacity is readonly and its always 2
```

Hope this helps
