### ISSUE TITLE
azure login failing to login to AzureUSGoverernament cloud

### ISSUE THREAD

**Issue by ccassagnol** [Azure/azure-xplat-cli#2645]
CLI Version: **0.9.16**
OS Type: Win
Installation via:  win-or-mac installer

Mode: **ASM**

Description:
`azure login failing to login to AzureUSGoverernament cloud

Steps to reproduce:
1) Run azure login -u $username -p $password -e AzureUSGovernment

Error stack trace:

2016-03-16T20:20:41.687Z:
{ [Error: The access token has been obtained from wrong audience or resource 'https://management.core.usgovcloudapi.net/'. It should exactly match (including forward slash) with one of the allowed audiences 'https://management.core.windows.net/','https://management.azure.com/'.]
  stack: [Getter/Setter],
  statusCode: 401,
  request: 
   { rawResponse: false,
     queryString: {},
     method: 'GET',
     headers: 
      { 'x-ms-client-request-id': 'd95523ad-0f8b-4505-a152-8154b156d0e7',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8' },
     url: 'https://management.azure.com/tenants?api-version=2015-11-01',
     body: null },
  response: 
   { body: '{"error":{"code":"InvalidAuthenticationTokenAudience","message":"The access token has been obtained from wrong audience or resource \'https://management.core.usgovcloudapi.net/\'. It should exactly match (including forward slash) with one of the allowed audiences \'https://management.core.windows.net/\',\'https://management.azure.com/\'."}}',
     headers: 
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'www-authenticate': 'Bearer authorization_uri="https://login.windows.net/", error="invalid_token", error_description="The access token is from wrong audience or resource."',
        'x-ms-failure-cause': 'gateway',
        'x-ms-request-id': '7768536c-f26b-4bee-812d-315b4f154d68',
        'x-ms-correlation-request-id': '7768536c-f26b-4bee-812d-315b4f154d68',
        'x-ms-routing-request-id': 'WESTUS:20160316T202040Z:7768536c-f26b-4bee-812d-315b4f154d68',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        date: 'Wed, 16 Mar 2016 20:20:40 GMT',
        connection: 'close',
        'content-length': '336' },
     statusCode: 401 },
  code: 'InvalidAuthenticationTokenAudience',
  body: 
   { code: 'InvalidAuthenticationTokenAudience',
     message: 'The access token has been obtained from wrong audience or resource \'https://management.core.usgovcloudapi.net/\'. It should exactly match (including forward slash) with one of the allowed audiences \'https://management.core.windows.net/\',\'https://management.azure.com/\'.' },
  __frame: 
   { name: '__1',
     line: 49,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\login.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 64,
     col: 27 },
  rawStack: [Getter] }
Error: The access token has been obtained from wrong audience or resource 'https://management.core.usgovcloudapi.net/'. It should exactly match (including forward slash) with one of the allowed audiences 'https://management.core.windows.net/','https://management.azure.com/'.
  <<< async stack >>>
  at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\login.js:113:28)
  <<< raw stack >>>
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-arm-resource\lib\subscription\operations\tenants.js:114:19
    at retryCallback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\node_modules\ms-rest\lib\filters\redirectFilter.js:36:9)
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\node_modules\ms-rest\lib\requestPipeline.js:125:16)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:344:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:1239:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)

########################

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).

**Comment by amarzavery** [comment]
@ccassagnol - This is a known issue. There was a hotfix done for this issue.
Please uninstall the CLI installed via MSI and then install via npm.
`npm install azure-cli -g`
The latest version 0.9.18 from npm should resolve this issue.

**Comment by amarzavery** [comment]
@ccassagnol - If you have 2FA enabled for your user account then just execute `azure login` and follow the process directed by the command.

**Comment by ccassagnol** [comment]
That fixed the issue.
