### ISSUE TITLE
Question about connection type

### ISSUE THREAD

**Issue by ccassagnol** [Azure/azure-xplat-cli#2652]
CLI Version: **0.9.16** 
OS Type: **WIN**
Installation via:  **win-installer** 

Mode: **ARM / ASM**

Description:
I would like to know how `azure login -u <AppGUID> -p <AppKey> -e AzureUSGovernment --service-principal --tenant <tenantGUID>` command connection is processed as I have an environment behind a web-proxy that allows `Add-AzureAccount -Credential $cred -Tenant $tenantid -ServicePrincipal -Environment "AzureGovernmentCloud" but fails using AzureCLI

Steps to reproduce:
1) Run `azure login -u <AppGUID> -p <AppKey> -e AzureUSGovernment --service-principal --tenant <tenantGUID>`

Info:
I am unable to use npm in this environement as that site and downloading is prohibitied, so I cannot go to the newer versions that way until such time as an msi is provisioned. I have a request out to have port 443 opened but just wanted to make sure that this is going over tcp and not as a web call.

Error stack trace:

**Please paste the content of ~/.azure/azure.err or C:\Users\username\\.azure\azure.err over here**
info:    Executing command login
- Authenticating...info:    Thu, 17 Mar 2016 19:51:51 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - Authority: VERBOSE: Performing instance discovery: https://login.microsoftonline.com/8d444d31-f45d-45aa-895b-168798d40690
info:    Thu, 17 Mar 2016 19:51:51 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - Authority: VERBOSE: Performing static instance discovery
info:    Thu, 17 Mar 2016 19:51:51 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - Authority: VERBOSE: Authority validated via static instance discovery.
info:    Thu, 17 Mar 2016 19:51:51 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - TokenRequest: INFO: Getting token with client credentials.
info:    Thu, 17 Mar 2016 19:51:51 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - TokenRequest: VERBOSE: No userId passed for cache query.
info:    Thu, 17 Mar 2016 19:51:51 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - CacheDriver: VERBOSE: finding with query:{"clientId":"GUID"}
info:    Thu, 17 Mar 2016 19:51:51 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - CacheDriver: VERBOSE: Looking for potential cache entries:
info:    Thu, 17 Mar 2016 19:51:51 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - CacheDriver: VERBOSE: {"_clientId":"GUID"}
info:    Thu, 17 Mar 2016 19:51:51 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - CacheDriver: VERBOSE: Found 0 potential entries.
info:    Thu, 17 Mar 2016 19:51:51 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - TokenRequest: VERBOSE: No appropriate cached token found.
-info:    Thu, 17 Mar 2016 19:52:12 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - OAuth2Client: ERROR: Get Token request failed with
Stack:
Error: connect ETIMEDOUT 168.62.176.34:443
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
error:   Error: connect ETIMEDOUT 168.62.176.34:443
info:    Thu, 17 Mar 2016 19:52:12 GMT:a17fbbb2-f027-4117-b030-12024a89aeb5 - TokenRequest: VERBOSE: getTokenFunc returned with err
+
error:   Unable to acquire token due to error: connect ETIMEDOUT 168.62.176.34:443
info:    Error information has been recorded to D:\Users\charlcas\.azure\azure.err
error:   login command failed

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).

**Comment by amarzavery** [comment]
There is one more way to install the CLI. Download the source code (tar.gz format) of the CLI from the [0.9.18 github release page](https://github.com/Azure/azure-xplat-cli/releases/tag/v0.9.18-hotfix).
After you have downloaded, (uninstall the MSI) and then execute `npm install -g "path-to-downloaded-tar.gz"`. Hopefully, the github download should be same as downloading the MSI and should not be blocked by your environment.

**Comment by ccassagnol** [comment]
The offline install also tries to connect externally: (to fastly.com owned ip)...

PS C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy> npm install -g D:\Tools\azure-xplat-cli-0.9.18-hotfix.tar.gz
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "-g" "D:\\Tools\\azure-xplat-cli-0.9.18-hotfix.tar.gz"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 23.235.44.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy\npm-debug.log

**Comment by ccassagnol** [comment]
I figured out how to do the offline install using [npmbox](https://github.com/arei/npmbox). The `npmunbox` command didn't work, but the `npm install --global --cache .\.npmbox.cache --optional --cache-min 99999 --shrinkwrap false azure-cli` did.
