### ISSUE TITLE
Is it possible to upload a file to a blob container using SAS authentication?

### ISSUE THREAD

**Issue by ciberado** [Azure/azure-xplat-cli#2665]
I see there is a --sas option in the azure storage blob list command but I cannot find the equivalent in the upload command.

CLI Version: 0.9.18
OS Type: Win 7
Installation via:  npm 

Mode: ARM

**Comment by amarzavery** [comment]
@hasonmsft @yaxia - Can you please respond ?

**Comment by yaxia** [comment]
No, we don't support uploading a new blob with a SAS yet. We are working on it and will have it in a later release.

**Comment by ciberado** [comment]
Thanks guys. In he meanwhile I'll keep using blobxfer, it works nicely. Thumbs up for your work, btw!
