### ISSUE TITLE
ARM: 'network express-route provider list' throws error

### ISSUE THREAD

**Issue by atoakley** [Azure/azure-xplat-cli#2667]
CLI Version: 0.9.18
OS Type: Win
Installation via: npm

Mode: ARM

Description:
'network express-route provider list' fails with an error

Steps to reproduce:
 1) Run azure network express-route provider list

Results are:
```
info:    Executing command network express-route provider list
+ Looking up express route service providers
error:   Cannot read property 'bandwidthsOffered' of undefined
error:   network express-route provider list command failed
```

**Comment by romangromov** [comment]
@amarzavery  the responce body from server has changed a little bit - that is the resason of getting this issue.

@atoakley thanks for contributing.
