### ISSUE TITLE
`azure network lb address-pool add` is missing

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-xplat-cli#2684]
https://azure.microsoft.com/en-us/documentation/articles/azure-cli-arm-commands/

says that `azure network lb address-pool add` should be a command, but it's not.

0.9.17

**Comment by colemickens** [comment]
https://azure.microsoft.com/en-us/documentation/articles/azure-cli-arm-commands/#comment-2203022592

And it's been missing for 7 months?

**Comment by romangromov** [comment]
@colemickens there is support for backend address pool operations in xplat-cli:

```
azure network lb address-pool -h
help:    Commands to manage backend address pools of a load balancer
help:
help:    Add a backend address pool to the load balancer
help:      network lb address-pool create [options] <resource-group> <lb-name> <name>
help:
help:    Get all backend address pools in the load balancer
help:      network lb address-pool list [options] <resource-group> <lb-name>
help:
help:    Delete a backend address pool from a load balancer
help:      network lb address-pool delete [options] <resource-group> <lb-name> <name>
help:
help:    Options:
help:      -h, --help  output usage information
help:
help:    Current Mode: arm (Azure Resource Management)
```

Looks like docs shared above do not match naming convention currently used (create/set/delete instead of add/temove)

**Comment by colemickens** [comment]
That help says create/list/delete, nothing about set. Anyway, I think this functionality is on the nic now. You have the nic declare it's participation in the backend pool. This looks like it's just a docs issue.
