### ISSUE TITLE
"azure resource show" command should support --id parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#2689]
CLI Version: **0.9.18**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Description:
`azure resource show` command doesn't support an `--id` parameter.

Steps to reproduce:
1) Run `azure resource list --resource-group MyCoolResourceGroup`
2) Then run `azure resource show --id <resourceId>`

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by amarzavery** [comment]
The resource show command currently does not support the entire resource id. This is what it supports currently.

It would be a better user experience to support id and the current set of parameters as mutually exclusive parameter sets.

```
D:\sdk>azure resource show -h
help:    Gets one resource within a resource group or subscription
help:
help:    Usage: resource show [options] <resource-group> <name> <resource-type> <api-version>
help:
help:    Options:
help:      -h, --help                            output usage information
help:      -v, --verbose                         use verbose output
help:      -vv                                   more verbose with debug output
help:      --json                                use json output
help:      -g --resource-group <resource-group>  the resource group name
help:      -n --name <name>                      the resource name
help:      -r --resource-type <resource-type>    the resource type
help:      -o --api-version <api-version>        the API version of the resource provider
help:      --parent <parent>                     the name of the parent resource (if needed), in path/path/path format
help:      --subscription <subscription>         the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)

D:\sdk>azure -v
0.9.18
```

**Comment by amarzavery** [comment]
@ravbhatnagar @vivsriaus Can you get this issue fixed in the upcoming release?

**Comment by ravbhatnagar** [comment]
Agreed, there are other places in CLI where we don't support the Id parameter. We should be apply the fix consistently across other commands too.

**Comment by amarzavery** [comment]
@ravbhatnagar @vivsriaus - Any timeline for this fix?

**Comment by ravbhatnagar** [comment]
No timeline yet on this one.

**Comment by andrew-mestas** [comment]
Have a working version for resource show by id, currently testing for review. Will be coming soon along with other updates to azure resource commands.

**Comment by ravbhatnagar** [comment]
Fixed.
