### ISSUE TITLE
azure vm images list always return empty list

### ISSUE THREAD

**Issue by xiaoyongaz** [Azure/azure-xplat-cli#2697]
CLI Version: 0.9.18
OS Type: Mac  and Linux (Ubuntu)
Installation via:  npm 

Mode: **ARM 

Description:
azure vm images list always return empty list

Steps to reproduce:
1) Run `azure vm create ...`
2) Then run `azure vm show ...`

Error stack trace:

**Please paste the content of ~/.azure/azure.err or C:\Users\username\\.azure\azure.err over here**

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).

**Comment by amarzavery** [comment]
@xiaoyongaz - The steps to reproduce do not look related to the issue.
After creating the vm you may want to execute `azure vm list`.

`azure vm image list` command gets the images from the gallery .

**Comment by amarzavery** [comment]
Closing this due to no response. Please feel free to open if required.
