### ISSUE TITLE
Azure CLI vm create doesnt not create azure dns entry

### ISSUE THREAD

**Issue by kali-rms** [Azure/azure-xplat-cli#2699]
Hi,

I have successfully created a VM using the Azure CLI. However I noticed, that the VM's do not have a computer name and the Azure auto DNS is not working.

If i create a VM manually via the portal and provide it all the information and default DNS entry is created.

is this expected behaviour?

**Comment by amarzavery** [comment]
@huangpf and @romangromov - Can you please confirm this behavior?

**Comment by amarzavery** [comment]
@kali-rms - Were you creating the vm in ARM mode? What version of cli were you using?

**Comment by kali-rms** [comment]
ok so the issue was not with the CLI - basically the image i was using was the Openlogic Centos 7.2 image. However i followed instructions on how to modified the VM then create your own image (capture). It seems though this process misses something which helps the DNS record get generated.

**Comment by huangpf** [comment]
@kali-rms 
Please run the commands with ```-vv``` option to collect the request/response logs and share them with us for further triage.

**Comment by yugangw-msft** [comment]
@kali-rms , before the issue gets investigated and fixed, for now you can update VM's public IP address with a dns label
```bash
   azure network public-ip set --domain-name-label 
```

**Comment by romangromov** [comment]
Adding @MikhailTryakhov for the same

**Comment by MikhailTryakhov** [comment]
@kali-rms still no actions from your side - closing issue
