### ISSUE TITLE
Cannot get verbose output for azure account list

### ISSUE THREAD

**Issue by djberg96** [Azure/azure-xplat-cli#2713]
CLI Version: 0.9.19 (node: 4.2.4)
OS Type: Mac
Installation via:  mac installer

Mode: ARM

Description:
`azure account list -vv` command doesn't show verbose output.

Steps to reproduce:
1) Run `azure account list -vv`

Neither the -v nor -vv (nor --verbose) options actually show the request being made.

There's no error. The command just executes without displaying verbose output.

**Comment by amarzavery** [comment]
@djberg96 
-vv is not applicable on this command. `azure account list` just provides the list of subscriptions present in azureProfile.json. This file is present in the .azure folder inside the User's home profile.
This file is populated as the outcome of a successful login `azure login`.
We should remove the -v and -vv option as it is misleading.

To get the details of a particular subscription, you can execute `azure account show`

```
D:\sdk>azure account show -h
help:    Show details about a subscription
help:
help:    Usage: account show [options] [subscriptionNameOrId]
help:
help:    Options:
help:      -h, --help                                        output usage information
help:      -v, --verbose                                     use verbose output
help:      -vv                                               more verbose with debug output
help:      --json                                            use json output
help:      -s --subscriptionNameOrId <subscriptionNameOrId>  The subscription to show
help:      -d --details                                      Show extra information about the subscription
help:
help:    Current Mode: arm (Azure Resource Management)
```

Note: you can use the account list/show commands with --json option .

**Comment by djberg96** [comment]
@amarzavery Ok, I thought it was making an actual request out to "https://management.azure.com/subscriptions" or something.

Please, remove the -v and -vv options from help, then.

**Comment by amarzavery** [comment]
Will do. Thanks for filing this issue.
