### ISSUE TITLE
Cannot list Data Lake stores

### ISSUE THREAD

**Issue by edevil** [Azure/azure-xplat-cli#2719]
CLI Version: **0.9.19**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Description:

Cannot list Data Lake stores.

Steps to reproduce:

```
$ azure datalake store account list
info:    Executing command datalake store account list
error:   The resource type could not be found in the namespace 'Microsoft.DataLakeStore' for api version '2015-10-01-preview'.
info:    Error information has been recorded to /Users/andre/.azure/azure.err
error:   datalake store account list command failed
```
Error stack trace:

2016-04-07T15:15:06.870Z:
{ [Error: The resource type could not be found in the namespace 'Microsoft.DataLakeStore' for api version '2015-10-01-preview'.]
  stack: [Getter/Setter],
  statusCode: 404,
  request:
   { rawResponse: false,
     queryString: {},
     method: 'GET',
     headers:
      { 'x-ms-client-request-id': '6a6d382b-2ac1-4bba-b804-02ce56a61898',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8',
        'user-agent': 'WindowsAzureXplatCLI/0.9.19' },
     url: 'https://management.azure.com/subscriptions/97e0176d-1f4a-460d-96a5-b0eb2648c7b8/providers/Microsoft.DataLakeStore/accounts?api-version=2015-10-01-preview',
     body: null },
  response:
   { body: '{"error":{"code":"InvalidResourceType","message":"The resource type could not be found in the namespace \'Microsoft.DataLakeStore\' for api version \'2015-10-01-preview\'."}}',
     headers:
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'x-ms-failure-cause': 'gateway',
        'x-ms-request-id': '58c6165e-45b3-415f-a7b9-c060f07b4dc2',
        'x-ms-correlation-request-id': '58c6165e-45b3-415f-a7b9-c060f07b4dc2',
        'x-ms-routing-request-id': 'WESTEUROPE:20160407T151506Z:58c6165e-45b3-415f-a7b9-c060f07b4dc2',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        date: 'Thu, 07 Apr 2016 15:15:06 GMT',
        connection: 'close',
        'content-length': '170' },
     statusCode: 404 },
  code: 'InvalidResourceType',
  body:
   { code: 'InvalidResourceType',
     message: 'The resource type could not be found in the namespace \'Microsoft.DataLakeStore\' for api version \'2015-10-01-preview\'.' },
  __frame:
   { name: 'listAllDataLakeStoreAccounts',
     line: 833,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js',
     prev:
      { name: '__15',
        line: 683,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 2,
        col: 21 },
     calls: 0,
     active: false,
     offset: 5,
     col: 32 },
  rawStack: [Getter] }
Error: The resource type could not be found in the namespace 'Microsoft.DataLakeStore' for api version '2015-10-01-preview'.
  <<< async stack >>>
  at listAllDataLakeStoreAccounts (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js:838:33)
  at __15 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js:685:22)
  <<< raw stack >>>
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-datalake-store/lib/account/operations/account.js:2168:19
    at retryCallback (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/local/lib/node_modules/azure-cli/lib/util/utils.js:535:7
    at handleRedirect (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:512:9)
    at /usr/local/lib/node_modules/azure-cli/lib/util/logging.js:412:7
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)

**Comment by amarzavery** [comment]
Ben,

Can you take a look at this?

Thanks,
Amar Zavery

On Apr 7, 2016, at 8:18 AM, "Andr? Cruz" <notifications@github.com<mailto:notifications@github.com>> wrote:


CLI Version: 0.9.19
OS Type: Mac
Installation via: npm

Mode: ARM

Description:

Cannot list Data Lake stores.

Steps to reproduce:

$ azure datalake store account list
info:    Executing command datalake store account list
error:   The resource type could not be found in the namespace 'Microsoft.DataLakeStore' for api version '2015-10-01-preview'.
info:    Error information has been recorded to /Users/andre/.azure/azure.err
error:   datalake store account list command failed


Error stack trace:

2016-04-07T15:15:06.870Z:
{ [Error: The resource type could not be found in the namespace 'Microsoft.DataLakeStore' for api version '2015-10-01-preview'.]
stack: [Getter/Setter],
statusCode: 404,
request:
{ rawResponse: false,
queryString: {},
method: 'GET',
headers:
{ 'x-ms-client-request-id': '6a6d382b-2ac1-4bba-b804-02ce56a61898',
'accept-language': 'en-US',
'Content-Type': 'application/json; charset=utf-8',
'user-agent': 'WindowsAzureXplatCLI/0.9.19' },
url: 'https://management.azure.com/subscriptions/97e0176d-1f4a-460d-96a5-b0eb2648c7b8/providers/Microsoft.DataLakeStore/accounts?api-version=2015-10-01-preview<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fmanagement.azure.com%2fsubscriptions%2f97e0176d-1f4a-460d-96a5-b0eb2648c7b8%2fproviders%2fMicrosoft.DataLakeStore%2faccounts%3fapi-version%3d2015-10-01-preview&data=01%7c01%7camzavery%40microsoft.com%7c264457951ca74272a1fa08d35ef7e89f%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=oZMPuGTv%2bYOoQsf%2f4EliJzZ8QRChpnFauRorqZcmBII%3d>',
body: null },
response:
{ body: '{"error":{"code":"InvalidResourceType","message":"The resource type could not be found in the namespace \'Microsoft.DataLakeStore\' for api version \'2015-10-01-preview\'."}}',
headers:
{ 'cache-control': 'no-cache',
pragma: 'no-cache',
'content-type': 'application/json; charset=utf-8',
expires: '-1',
'x-ms-failure-cause': 'gateway',
'x-ms-request-id': '58c6165e-45b3-415f-a7b9-c060f07b4dc2',
'x-ms-correlation-request-id': '58c6165e-45b3-415f-a7b9-c060f07b4dc2',
'x-ms-routing-request-id': 'WESTEUROPE:20160407T151506Z:58c6165e-45b3-415f-a7b9-c060f07b4dc2',
'strict-transport-security': 'max-age=31536000; includeSubDomains',
date: 'Thu, 07 Apr 2016 15:15:06 GMT',
connection: 'close',
'content-length': '170' },
statusCode: 404 },
code: 'InvalidResourceType',
body:
{ code: 'InvalidResourceType',
message: 'The resource type could not be found in the namespace \'Microsoft.DataLakeStore\' for api version \'2015-10-01-preview\'.' },
__frame:
{ name: 'listAllDataLakeStoreAccounts',
line: 833,
file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js',
prev:
{ name: '__15',
line: 683,
file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js',
prev: undefined,
calls: 1,
active: false,
offset: 2,
col: 21 },
calls: 0,
active: false,
offset: 5,
col: 32 },
rawStack: [Getter] }
Error: The resource type could not be found in the namespace 'Microsoft.DataLakeStore' for api version '2015-10-01-preview'.
<<< async stack >>>
at listAllDataLakeStoreAccounts (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js:838:33)
at __15 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js:685:22)
<<< raw stack >>>
at /usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-datalake-store/lib/account/operations/account.js:2168:19
at retryCallback (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
at handleRedirect (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
at /usr/local/lib/node_modules/azure-cli/lib/util/utils.js:535:7
at handleRedirect (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:512:9)
at /usr/local/lib/node_modules/azure-cli/lib/util/logging.js:412:7
at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:199:22)
at emitTwo (events.js[:100:]13)
at Request.emit (events.js:185:7)

-

**Comment by begoldsm** [comment]
@edevil your subscription was not whitelisted to use our service. We have added your subscription to the whitelist for you to continue your testing. Please let me know if you continue to see these types of issues or if it is now resolved for you.

**Comment by edevil** [comment]
Thank you. In fact I was using the wrong subscription, I already have access with another one. The error message is a bit misleading.

**Comment by keejh** [comment]
My trial account keejh@docnetsolutions.onmicrosoft.com also having this error :(
The resource type could not be found in the namespace 'Microsoft.DataLakeStore' for api version '2015-10-01-preview'. (Code: InvalidResourceType)

**Comment by amarzavery** [comment]
@begoldsm - does @keejh have the same problem as the previous user?

@keejh - one thing you can try.

When you execute:

`azure provider list` you will see that "Microsoft.DataLakeStore" is not registered for your subscription. 
This should `azure provider register Microsoft.DataLakeStore` register it. It is a one time thing.

**Comment by begoldsm** [comment]
@amarzavery is right. @keejh you need to register the resource provider just once and this should be resolved.
I am looking into fixing this in the code so the user doesn't have to manually perform this step, so ideally this will be a non-issue in the next release.

**Comment by amarzavery** [comment]
@begoldsm - This is by design. All the services that arent ring0 are not registered by default. However, we could look at improving the experience,  by guiding the customer what to do in an error message or even better try registering internally by looking for specific error message.

**Comment by keejh** [comment]
I got the same error after I registered the provider.

Sample url on how to register datalakestore provider
https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-get-started-powershell/
PS C:\Users\Administrator> $resourceGroupName = "rsgdatalake"
$dataLakeStoreName = "datalake8"
New-AzureRmDataLakeStoreAccount -ResourceGroupName $resourceGroupName -Name $dataLakeStoreName -Location "East US 2"
New-AzureRmDataLakeStoreAccount : The resource type could not be found in the namespace 
'Microsoft.DataLakeStore' for api version '2015-10-01-preview'.
At line:3 char:1
+ New-AzureRmDataLakeStoreAccount -ResourceGroupName $resourceGroupName -Name $dat ...
+ 
    + CategoryInfo          : CloseError: (:) [New-AzureRmDataLakeStoreAccount], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataLakeStore.NewAzureDataLakeStoreAccount

**Comment by begoldsm** [comment]
@keejh Has your subscription been whitelisted to access Data Lake? You can check on this by attempting to create a Data Lake account through the web experience (ms.portal.azure.com). If your subscription is not approved, you will see a "request access" message, which can be used to trigger the approval workflow to get into the data lake preview.
