### ISSUE TITLE
OS X intermittent keychain error from SecKeychainSearchCopyNext

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2720]
CLI Version: **0.9.18**
OS Type: Mac
Installation via:  npm

Mode: ARM

This one is not easily reproducible, in fact I hit it only once.

I logged in using "azure login" yesterday, but a long running operation (ARM template deployment polling) just failed in the middle of the operation with an OS X keychain error:

> Original error:Could not remove account from keychain, security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.

Full output:

```
$ azure group deployment create --template-file azuredeploy.json --parameters-file azuredeploy.parameters.json --resource-group acr-6
info:    Executing command group deployment create
+ Initializing template configurations and parameters
+ Creating a deployment
error:   Long running operation failed with error: 'We don't have a valid access token.
Please run "azure login" again.
Original error:Could not remove account from keychain, security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
'.
info:    Error information has been recorded to /Users/alp/.azure/azure.err
error:   group deployment create command failed
```

After the error I ran `azure group list` and that API call worked just fine. So this means, if we fail to access keychain for some reason, we tell users to "azure login" when it is in fact unnecessary.

I'm not running into this all the time, but this is not the first time either. It probably happened to me 5-6 times over the course of a year or so.

If we have a better way of telling keychain errors from the others, this may improve the user experience.

**Comment by ahmetalpbalkan** [comment]
I so good at reopening my own duplicate issue #2348 which also happens to be a duplicate issue.  :)

But I will leave this open because apparently it is claimed as "fixed" but v0.9.18 still runs into this issue.

**Comment by mayurid** [comment]
@yugangw-msft : This looks the same as the one that you may be looking at with Kevin already.

**Comment by amarzavery** [comment]
with 0.10.1, you can switch to file based token storage once you turn on the env variable of "AZURE_USE_FILE_TOKEN_STORAGE". If you run into login failure, please turn this on and share out the ~/.azure/accessTokens.json with us(feel free to mask out the acesstoken entries).
Note, azure-cli for linux has already used file storage. We enable it for osx and windows as well for easier diagnostic.
