### ISSUE TITLE
[P1] "azure login -e AzureChinaCloud" does not work in Linux

### ISSUE THREAD

**Issue by andyzhangx** [Azure/azure-xplat-cli#2726]
CLI Version: 0.9.19
OS Type: Ubuntu 14.04.4 LTS
Installation via:  npm
Mode: **ARM / ASM**

Description:
"azure login -e AzureChinaCloud" does not work in Linux

Steps to reproduce:
1) sudo apt-get install nodejs-legacy
2) sudo apt-get install npm
3) sudo npm install -g azure-cli
4) azure login -e AzureChinaCloud

Error stack trace:

|^Croot@andy-test-ubt:/tmp# azure login -e AzureChinaCloud
info:    Executing command login
/info:    To sign in, use a web browser to open the page https://aka.ms/deviceloginchina. Enter the code AB74HL5YU to authenticate.
+
error:   CERT_UNTRUSTED
info:    Error information has been recorded to /root/.azure/azure.err
error:   login command failed

Note:
If I use global azure account, it works:
root@andy-test-ubt:/tmp# azure login
info:    Executing command login
- Authenticating...info:    To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code APS7W3KUH to authenticate.
\info:    Added subscription Azure RHUI Production
info:    Added subscription OSTC Shanghai Test
info:    Setting subscription "Azure RHUI Production" as default
+
info:    login command OK

**Comment by ahmetalpbalkan** [comment]
duplicate of #2726

**Comment by amarzavery** [comment]
@andyzhangx - What version of node.js are you using. I think this error should go away after installing the latest version (4.x). This [link](https://nodejs.org/en/download/package-manager/#installing-node-js-via-package-manager) provides simple steps to install the latest version of node.js on different flavors of Linux.

**Comment by andyzhangx** [comment]
Thanks, it works.
