### ISSUE TITLE
ARM express-route peering list/show failed

### ISSUE THREAD

**Issue by MikhailTryakhov** [Azure/azure-xplat-cli#2748]
Trying to create Azure CLI ``` network express-route peering list``` command.
Throwing error described at the screenshot below
![](http://i.imgur.com/Mt67To6.png)

At the same time AzurePublicPeering and MicrosoftPeering both exist

**Comment by MikhailTryakhov** [comment]
The same issue occurs for show command non-regularly
![](http://i.imgur.com/5OyYZWD.png)

**Comment by romangromov** [comment]
@MikhailTryakhov is this still reproducable on PROD?

**Comment by MikhailTryakhov** [comment]
@romangromov Deepak recommended to move important issues here too.
