### ISSUE TITLE
Azure Datalake Import cmd Providing FileAlreadyExists exception when Filesystem is empty

### ISSUE THREAD

**Issue by brharr** [Azure/azure-xplat-cli#2749]
CLI Version: **0.9.X**
OS Type: Mac / Win / Linux (Ubuntu, RedHat, etc.)
Installation via:  npm 

Mode: **ARM / ASM**

Description:
When I run the following command, I get a bogus FileAlreadyExists exception:
azure datalake store filesystem import --accountName accudl --path KBWI-H.csv --destination /Accuweather-Data

Steps to reproduce:
1) Run `azure datalake store filesystem list --accountName accudl --path /Accuweather-Data` to validate that there are no documents within the folder
2) Then run `azure datalake store filesystem import --accountName accudl --path KBWI-H.csv --destination /Accuweather-Data` 

Error stack trace:

info:    Executing command datalake store filesystem list
info:    datalake store filesystem list command OK
Brians-MBP:AW-Test-Data brianharrison$ azure datalake store filesystem import --accountName accudl --path KBWI-H.csv --destination /Accuweather-Data
info:    Executing command datalake store filesystem import
+ Uploading file KBWI-H.csv to the Data Lake Store location: /Accuweather-Data 
error:   {"RemoteException":{"exception":"FileAlreadyExistsException","message":"FsOpenStream failed with error 0x83090180 (). [06eee4b62029472aadf70b0ac883aa3a] failed with error 0x83090180 (). [06eee4b62029472aadf70b0ac883aa3a]","javaClassName":"org.apache.hadoop.fs.FileAlreadyExistsException"}}
info:    Error information has been recorded to /Users/brianharrison/.azure/azure.err
error:   datalake store filesystem import command failed

**Comment by amarzavery** [comment]
@begoldsm - Can you take a look at one more datalake issue?

**Comment by begoldsm** [comment]
@brharr this is unfortunately a bug in the error message being returned from the server. The usage for this is to include the full path to the destination file to create, not just the folder you want to import into (although that is a good feature request for the future 😄 ). Per the help for destination:

"the full path in the Data Lake Store where the file should be imported to (e.g. /someFolder/**someFile.txt**"
