### ISSUE TITLE
azure resource show should not require api-version, resource group, type as mandatory

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-xplat-cli#2751]
C:\Windows\system32>azure resource show --name ravtestws501 -g ravdemo3 -r Microsoft.Web/sites
info: Executing command resource show

error: missing required argument apiVersion' error: missing required argumentresourceType' --> when run without the type

**Comment by amarzavery** [comment]
@ravbhatnagar - This is the correct behavior. As far as I understand all of this is required to uniquely identify a resource from the generic resource manager view point. 

Has the Generic ARM API changed?

To make this more useful for end users, the ARM team can modify the `azure resource show` command to accept a resourceId where, resourceId and all the above parameters can be mutually exclusive.

**Comment by ravbhatnagar** [comment]
Added the resource Id support. Closing this issue
