### ISSUE TITLE
azure-cli failing every time on SecKeychainSearchCopyNext

### ISSUE THREAD

**Issue by kevinday** [Azure/azure-xplat-cli#2756]
CLI Version: **0.9.19**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

I can 'azure login' just fine, but the following command I see:

``` 
$ azure group list
info:    Executing command group list
+ Listing resource groups                                                      
error:   Could not remove account from keychain, security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.

info:    Error information has been recorded to /Users/k_day/.azure/azure.err
error:   group list command failed 
```

This seems different than #2720, since this happens every single time I attempt a group command.

Also, I don't have any non-ascii characters in my username/family name in my live.com profile  #2349, nor do I see any azure related entries to remove in my keystore.

My azure.err:
```
2016-04-13T21:50:31.777Z:
{ [Error: Could not remove account from keychain, security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
]
  stack: [Getter/Setter],
  __frame: 
   { name: '__5',
     line: 157,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group._js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 12,
     col: 45 },
  rawStack: [Getter] }
Error: Could not remove account from keychain, security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.

  <<< async stack >>>
  at __5 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group._js:169:46)
  <<< raw stack >>>
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/osx-keychain.js:123:23
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by yugangw-msft** [comment]
@kevinday, when you open the keychain-access manually, are you seeing any entries with type of "azure access token"? If there are, could you share out what they look like (you can hash away sensitive information); then can you delete them, and login and execute the command again.

**Comment by kevinday** [comment]
@yugangw-msft I did see two azure entries in my keystore earlier, which I deleted. Trying again after I deleted them gave me the same result.

**Comment by yugangw-msft** [comment]
@kevinday  could you share more details or email the entries to me (yugangw at microsoft dot com). I like very much to figure out what is wrong.

**Comment by gredondogc** [comment]
I had the same problem. I Rename a user that had a "special character" in his last name and then deleted the keystore entries. The problem seems to be solved.

**Comment by kevinday** [comment]
Yeah, I've seen that fix it for other people too but it seems to bee a different issue than what I'm experiencing. In my case I don't have (nor have ever had) any non ascii characters in my name/username. I've tried deleting all azure entries from my keystore, emailing a dump of my keystore to some msft devs, running azure account clear –q, etc. So far nothing has worked.

**Comment by eduardkoller** [comment]
@amarzavery - are you able to repro this?

**Comment by ritazh** [comment]
I also ran into this issue today when trying to login using a service principal from the CLI. After I removed all access tokens containing the word "azure" from Keychains, login worked again. Please give that a try and see if it resolves your issue.

**Comment by kevinday** [comment]
I've tried deleting all azure related entries from my keychain multiple times but it doesn't help me. The entries are recreated when I azure login, and then are removed when the next command fails.

**Comment by mh0rkk** [comment]
I have the same issue since i installed the azure command line tools. It happens for every command i try to run, also deleting all tokens from the keychain does not seem to help. I also tried to remove the .azure directory and reinstalling the azure cli, but to no avail.

**Comment by yugangw-msft** [comment]
with 0.10.1, you can switch to file based token storage once you turn on the env variable of "AZURE_USE_FILE_TOKEN_STORAGE".  If you run into login failure, please turn this on and share out the ~/.azure/accessTokens.json with us(feel free to mask out the acesstoken entries).
Note, azure-cli for linux has already used file storage. We enable it for osx for easier diagnostic.
