### ISSUE TITLE
azure storage blob: lease features missing

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2760]
I am currently trying to break a lease on an Azure Storage blob and that really seems impossible with Azure CLI.

Even with Azure PowerShell people need to go through far too many hoops [[1]](https://gallery.technet.microsoft.com/scriptcenter/How-to-break-the-locked-c2cd6492)[[2]](https://msdn.microsoft.com/en-us/library/jj919145.aspx).

I am right now on a Mac OS X with no access to PowerShell, Visual Studio, C# and the lack of this feature on the cross-platform CLI has just blocked me.

**Comment by yaxia** [comment]
ETA of the fix: June release

**Comment by yaxia** [comment]
We have added lease commands in the 0.10.1. Please take a try.

**Comment by ahmetalpbalkan** [comment]
Thanks a lot.
