### ISSUE TITLE
vm extension set: No way to specify autoUpgradeMinorVersion

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2767]
CLI Version: **0.9.19**
Mode: **ARM**

ASM mode had a feature to let users pick the highest minor version of a VM extension through version syntax, such as `1.*`. So if I run:

    [asm] azure vm extension set [...] Extension Namespace 1.*

I will get the highest `minor` version with `major=1`. This feature was already there in ASM because it's a feature of Service Management APIs and has nothing to do with client-side.

Now, in ARM, there is no way of doing this and this is actually a pretty useful/important feature we should be encouraging users to follow. ARM does not accept `1.*` syntax anymore, but in the extension properties it accepts an object:

    "autoUpgradeMinorVersion": true,

With that, users can pick the highest version and just type `1.0` but a version like `1.5` will get installed to their VM. To make this happen we need a `--autoUpgradeMinorVersion` argument that would set the respective object key in request JSON to true.

Don't ever worry what autoUpgradeMinorVersion means, it is a long story and it doesn't mean an upgrade.

**Comment by sauryadas** [comment]
@huangpf Is this something available in the API that we could set or does the service API need to be modified to allow for a autoUpgradeMinorVersion parameter?

**Comment by ahmetalpbalkan** [comment]
@sauryadas it exists in the API already, but no way to set it in the CLI, that's the issue.

**Comment by ahmetalpbalkan** [comment]
folks, any updates? this should be very easy to add.

**Comment by yugangw-msft** [comment]
@huangpf, I assume your own the command? This field is already circulated in the help file, and you just need to expose the option.

**Comment by ahmetalpbalkan** [comment]
@huangpf ping.

**Comment by huangpf** [comment]
I think we shall expose this parameter for users. + @sauryadas @sharadagarwal FYI

**Comment by huangpf** [comment]
![tumblr_nncf71ayoa1qaorn7o1_r4_500 1](https://cloud.githubusercontent.com/assets/3858524/16087151/db7f89ca-32d6-11e6-9c23-97e97a43ee3d.gif)
