### ISSUE TITLE
Azure CLI Test Infra doesn't support random values

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-xplat-cli#2775]
CLI Version: 0.9.20
OS Type: Any
Installation via:  Any

Mode: Both

Description:
Azure CLI Test Infra doesn't support random values. It's blocking us from verifying the user caes of using completely automated/randomized resource names. Unlike PS & .NET SDK, they support it.

So I have to use hash function for this limitation:
* https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/vmss/vmss._js#L188

**Comment by amarzavery** [comment]
@huangpf - Did you take a look at suite.generateId() method.
Several tests use it to create names for resources, resource groups, vms, etc. 
Take a look at some examples over here
- https://github.com/Azure/azure-xplat-cli/blob/dev/test/commands/arm/group/arm.group-tests.js#L68 
- https://github.com/Azure/azure-xplat-cli/blob/dev/test/commands/arm/role/arm.role-tests.js#L59 

We also provide a method `utils.uuidGen()` to generate Random GUID. This will generate a random GUID in record mode and will provide the same value in playback mode after restoring it from the recording file.

Take a look at some examples over here:
- https://github.com/Azure/azure-xplat-cli/blob/984313e0715f5b093955df532af5d48bf7828039/test/commands/arm/role/arm.role-tests.js#L219
- https://github.com/Azure/azure-xplat-cli/blob/984313e0715f5b093955df532af5d48bf7828039/test/commands/arm/role/arm.role-tests.js#L354

Hope this helps.

**Comment by huangpf** [comment]
If I use ```utils.uuidGen()``` inside the command code, i.e. ```vm quick-create```, and then we write test code for this command, will it work in both record and playback modes? Just want to confirm. Thanks.

**Comment by amarzavery** [comment]
The example above shows how it is used in the test. Whatever is used in the test is recorded. How can we record something that is used inside the command?

What is it that you are trying to achieve?

Is suite.generateId() useful for you?

**Comment by huangpf** [comment]
Essentially, I'm looking for a way to test any generated resources inside the command itself, not the inputs to a command (which we can generate using the functions you gave).

I think the code, let say, ```vm._js``` would be like:
```
var oneNewRandomResource = generate();
```

And ```generate()``` would be:
```
function generate() {
  if (isPlayback() === true) {
    var result = readFromRecordQueue();
  }
  else if (isRecord() === true) {
    var result = generateImpl();
    writeToRecordQueue(result);
  }
  else {
    // live & non-recording mode
    var result = generateImpl();
  }

  return result;
}
```

By having this support, we can extend the testibility for commands that use randomized values internally.

**Comment by eduardkoller** [comment]
Thank you for the suggestion, @huangpf. Added this to the backlog, but not on top of the priority list right now.

**Comment by haocs** [comment]
Related: https://github.com/Azure/azure-xplat-cli/issues/2963

**Comment by huangpf** [comment]
Reopen until the follow-up code change using the new utils function.

**Comment by amarzavery** [comment]
closing it as the ci passed for #3105
