### ISSUE TITLE
Client side telemetry: add error category to error events 

### ISSUE THREAD

**Issue by eduardkoller** [Azure/azure-xplat-cli#2779]
Currently the cli telemetry for error events only contain a free text for the error encountered.
Ideally we should add some type of classification/grouping to the errors, so we can aggregate/report on different classes of errors.

**Comment by haocs** [comment]
@eduardkoller thanks for the suggestion. Added it to backlog.

**Comment by amarzavery** [comment]
Classify errors:
CLI_Error - For all internal CLI errors
{HTTP_STATUSCODE} - For all errors that are caused because of making a request to the service.
