### ISSUE TITLE
`azure group delete` command doesn't support asynchronous operation.

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2785]
CLI Version: **0.9.17**
OS Type: Linux (Ubuntu)
Installation via:  npm

Mode: **ARM**

Description:
`azure group delete` command doesn't support asynchronous operation. My expectation is that the deleting command returns right after it's executed. Then I can do other operations instead of waiting the command finishes. Maybe after several minutes, I can run `azure group list or show` to poll the state of the group to make sure it's deleted.

Steps to reproduce:
1) Run `azure group delete  ...`

**Comment by amarzavery** [comment]
@bingosummer - As of today, the group delete command calls the `ResourceGroups.deleteMethod(..)` in the node sdk, which will do the polling for you  and return when the server sends a 204/200 (terminal state reached).

However, we could have an option --nowait (which will call the `ResourceGroups.beginDeleteMethod(...)` in the node sdk that returns after the initial request.

This mechanism is available in 
```
D:\sdk>azure group deployment create -h
help:    Creates a deployment
help:
help:    Usage: group deployment create [options] [resource-group] [name]
help:
help:    Options:
help:      -h, --help                             output usage information
help:      -v, --verbose                          use verbose output
help:      -vv                                    more verbose with debug output
help:      --json                                 use json output
help:      -g --resource-group <resource-group>   the name of the resource group
help:      -n --name <name>                       the name of the deployment
help:      -f --template-file <template-file>     the path to the template file in the file system
help:      --template-uri <template-uri>          the uri to the remote template file
help:      --template-version <template-version>  the content version of the template
help:      -p --parameters <parameters>           a JSON-formatted string containing parameters
help:      -e --parameters-file <parametersFile>  a file containing parameters
help:      -m --mode <mode>                       the deployment mode: specify one of Incremental or Complete. If no mode is specified, Incremental is used as default. When Complete mode is used, all the resources in the specified resource group, which are not included in the template, will be deleted.
help:      -d --debug-setting <debugSetting>      the debug setting for deployment logs. Valid values include RequestContent, ResponseContent, All or None. None is the default value. When All is specified, both request content and response content will be logged, which will be visible in deployment operations.
help:      -q --quiet                             quiet mode (when complete mode is specified, do not ask for deployment confirmation)
>>>>>>>>>>>>>>>>>>>>help:      --nowait                               does not wait for the deployment to complete. Returns as soon as the deployment is created
help:      --subscription <subscription>          the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)
````

**Comment by amarzavery** [comment]
@vivsriaus - If possible, try to add this feature request in the upcoming release for which the code freeze is  04/27.

**Comment by bingosummer** [comment]
@amarzavery - Thanks for your quick response. `--nowait` is perfect for me.

**Comment by amarzavery** [comment]
@bingosummer 

Once the PR https://github.com/Azure/azure-xplat-cli/pull/2784  is merged into the dev branch, you can download the tarball from [here](https://github.com/Azure/azure-xplat-cli/archive/devtar.gz).

- Uninstall the previously installed CLI
   - execute: `npm uninstall azure-cli –g`
- Clear the global cache: `npm cache clear –g`
- Delete the .streamline folder from the your home profile `~/.streamline`, if present.
- Install from the downloaded tarball: `npm install –g <path to the downloaded tarball>`

And you should be good to go :). 
Note: You may require admin prompt or sudo access to install via npm.
