### ISSUE TITLE
Login to AzureGermanCloud fails: unauthorized_client

### ISSUE THREAD

**Issue by waldiTM** [Azure/azure-xplat-cli#2788]
After fixing #2787, login to AzureGermanCloud fails:

    Get Token request returned http error: 400 and server response
    {
    "error":"unauthorized_client",
    "error_description":
        "AADSTS70001: Application with identifier '04b07795-8ddb-461a-bbee-02f9e1bf7b46' was not found in the directory […].onmicrosoft.de
        Trace ID: 17d466ac-5ec8-4207-9b23-463027555839
        Correlation ID: 73387517-a530-4f23-abfe-a6d36f169563
        Timestamp: 2016-04-21 14:12:13Z",
    "error_codes":[70001],"timestamp":"2016-04-21 14:12:13Z",
    "trace_id":"17d466ac-5ec8-4207-9b23-463027555839",
    "correlation_id":"73387517-a530-4f23-abfe-a6d36f169563"
    }

**Comment by amarzavery** [comment]
@waldiTM - This should have been fixed by now. Please reopen the issue if required.
