### ISSUE TITLE
`azure account list` does not return the correct subscriptions names. 

### ISSUE THREAD

**Issue by gredondogc** [Azure/azure-xplat-cli#2796]
CLI Version: **0.9.20**
OS Type: Mac
Installation via:  win-or-mac installer

Mode: **ASM**

Description:
`azure account list` return a list of subscriptions with some names incorrect.

Steps to reproduce:
1) Have an account that can manage several other accounts.
2) With the old portal rename some subscriptions. In this case from 'BizSpark' to 'UsernameBizSpark'.
3) Use `azure account list`

Result:
Some subscriptions names appear correctly renamed, others maintain the original name. I cannot suggest a pattern.

**Comment by haocs** [comment]
@gredondogc could you try logout and login again using cli to see if the issue remains? The subscription data is cached on local for cli. You will need to refresh the subscription info once you changed it via portal.

**Comment by gredondogc** [comment]
@haocs After doing a login, because of the 'We don't have a valid access token. Please run "azure login" again' message, the list of subscriptions presented showed the correct names but the 'azure account list' command did not.

Following your suggestion, I tried the logout and login and it seems to have worked.

Thank you.

**Comment by haocs** [comment]
@gredondogc you are welcome. I will close this issue and feel free to reopen it if you observe other issues.
