### ISSUE TITLE
-a flag on "datalake analytics job list" does not work

### ISSUE THREAD

**Issue by edevil** [Azure/azure-xplat-cli#2798]
CLI Version: **0.9.20**
OS Type: Mac
Installation via:  brew

Mode: **ARM**

Description:
`azure datalake analytics job list -a` does not work.

Steps to reproduce:
```
$ azure datalake analytics job list brpxlaketest -a 2016-04-22
info:    Executing command datalake analytics job list
info:    client created
+ Retrieving job list for account: brpxlaketest
error:   Could not find a property named 'SubmitTime' on type 'Microsoft.DataLakeAnalytics.JobContract.JobInformation'.
info:    Error information has been recorded to /Users/andre/.azure/azure.err
error:   datalake analytics job list command failed
```
Error stack trace:

2016-04-22T23:31:23.297Z:
{ [Error: Could not find a property named 'SubmitTime' on type 'Microsoft.DataLakeAnalytics.JobContract.JobInformation'.]
  stack: [Getter/Setter],
  statusCode: 400,
  request: 
   { rawResponse: false,
     queryString: {},
     method: 'GET',
     headers: 
      { 'x-ms-client-request-id': 'b9332bf9-53b9-4b57-b4d8-60ec0f7d6ef2',
        subscriptionId: '4df9b22d-85c6-440a-a1ab-f230d65e619c',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8',
        'user-agent': 'WindowsAzureXplatCLI/0.9.19' },
     url: 'https://brpxlaketest.azuredatalakeanalytics.net/Jobs?$filter=SubmitTime%20ge%20datetimeoffset\'2016-04-22\'&api-version=2015-11-01-preview',
     body: null },
  response: 
   { body: '{"error":{"code":"InvalidOperation","message":"Could not find a property named \'SubmitTime\' on type \'Microsoft.DataLakeAnalytics.JobContract.JobInformation\'."}}',
     headers: 
      { 'cache-control': 'private',
        pragma: 'no-cache',
        'transfer-encoding': 'chunked',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'x-ms-request-id': '42b05801-5b83-42e0-8572-f0856d240cfa',
        'x-content-type-options': 'nosniff',
        'strict-transport-security': 'max-age=15724800; includeSubDomains',
        date: 'Fri, 22 Apr 2016 23:31:22 GMT',
        connection: 'close' },
     statusCode: 400 },
  code: 'InvalidOperation',
  body: 
   { code: 'InvalidOperation',
     message: 'Could not find a property named \'SubmitTime\' on type \'Microsoft.DataLakeAnalytics.JobContract.JobInformation\'.' },
  __frame: 
   { name: '__1',
     line: 282,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakeanalytics/datalakeanalytics.js',
     prev: 
      { name: '__4',
        line: 222,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakeanalytics/datalakeanalytics.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 59,
        col: 6 },
     calls: 0,
     active: false,
     offset: 1,
     col: 36 },
  rawStack: [Getter] }
Error: Could not find a property named 'SubmitTime' on type 'Microsoft.DataLakeAnalytics.JobContract.JobInformation'.
  <<< async stack >>>
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakeanalytics/datalakeanalytics.js:283:37)
  at __4 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakeanalytics/datalakeanalytics.js:281:7)
  <<< raw stack >>>
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-arm-datalake-analytics/lib/job/operations/job.js:1220:19
    at retryCallback (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/local/lib/node_modules/azure-cli/lib/util/utils.js:535:7
    at handleRedirect (/usr/local/lib/node_modules/azure-cli/lib/util/utils.js:512:9)
    at /usr/local/lib/node_modules/azure-cli/lib/util/logging.js:412:7
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)

**Comment by amarzavery** [comment]
@begoldsm -Please take a look at this issue.

**Comment by begoldsm** [comment]
Looking at this now. I think I know the issue.

**Comment by amarzavery** [comment]
Closing this as the PR for this issue is merged.
