### ISSUE TITLE
Unable to create ExpressRoute VPN Connection

### ISSUE THREAD

**Issue by atoakley** [Azure/azure-xplat-cli#2804]
Unable to create an ExpressRoute VPN Connection using ```network vpn-connection create``` because the ExpressRoute Circuit ID cannot be specified using the existing parameter list.

The --type parameter does accept ExpressRoute as an option, but the Id parameter needed to create the connection cannot be passed to the command.

**Comment by eduardkoller** [comment]
@romangromov - can you please take a look?

**Comment by romangromov** [comment]
@atoakley thanks for flagging, I'm looking into this, stay tuned, will chare update

**Comment by romangromov** [comment]
As for [reference](https://azure.microsoft.com/en-us/documentation/articles/expressroute-howto-linkvnet-arm/):

To link a VirtualNetwork to an ExpressRouteCircuit we have to create an ExpressRouteCircuit with **private peering** of type `AzurePrivatePeering` before hand, but `network express-route peering` commands still not included in Xplat-CLI, already started issue here https://github.com/Azure/azure-xplat-cli/issues/2644

**Comment by romangromov** [comment]
@atoakley thanks for bringing this up. Currently, requested feature (link a VirtualNetwork to an ExpressRouteCircuit) not supported by Xplat-CLI, so I've started related work to get things done.

This will take some time to implement, let me comeback later and update thread. As workaround,
please use PS cmdlets instead. Sorry for the inconvenience

**Comment by atoakley** [comment]
@romangromov  The document you linked to also links to [this one](https://azure.microsoft.com/en-us/documentation/articles/expressroute-howto-circuit-arm/#7-create-your-routing-configuration) which explains why the peering commands may, or may not, be needed.

To sum up, there are two types of ExpressRoute provider types:  Layer 2 and Layer 3.  You only need the peering commands for Layer 2 types.  With Layer 3 types, **private peering** is already enabled.

I did test a local change to the CLI to test, and for a Layer 3 provider, the only change that is needed is the ability to pass the _Peer ID_ (the ARM id) of the Express Route circuit instead of the _gateway2_ parameters.  In the existing command, there are safety checks that make sure _gateway1_ **AND** _gateway2_ are passed.  With ExpressRoute, it would need to validate _gateway1_ and _gateway2_ **OR** _gateway1_ and _Peer ID_.  I just commented out the safety checks to make it run.

**Comment by MikhailTryakhov** [comment]
Fixed and would be published in upcoming release
