### ISSUE TITLE
Azure vm list does not work as documented

### ISSUE THREAD

**Issue by adammartin** [Azure/azure-xplat-cli#2807]
Attempted to follow official documentation: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-cli-ps-findimage/

CLI Version: **0.9.20**
OS Type: Mac 
Installation via:  npm 

Mode: ARM

Description:

Attempting to follow https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-cli-ps-findimage/ 

Specifically azure vm image list westus canonical ubuntuserver
When I run this command I expect filtration matching the output in the blog so I can get the sku, version, etc.

Instead I get an unfiltered list with the following headers:
Name                          Category  OS       Publisher

Steps to reproduce:
1) Run `azure vm image list westus canonical ubuntuserver`

**Comment by yugangw-msft** [comment]
Sorry if i miss some here, but it works for for me. Could you also share some text output or snapshot?
![screen shot 2016-04-25 at 1 58 09 pm](https://cloud.githubusercontent.com/assets/6014209/14798709/c6b23a26-0aed-11e6-8fda-e4bc3ef567e8.png)

**Comment by adammartin** [comment]
Here you go ... obviously I used a --version instead of a -v so you could see the node version I am running.

![screen shot 2016-04-25 at 5 09 20 pm](https://cloud.githubusercontent.com/assets/728069/14800628/9622487c-0b08-11e6-97d1-10d384e809c7.png)

**Comment by yugangw-msft** [comment]
@adammartin, this is caused by a confusing part of azure-cli that it has 2 modes (asm vs arm). You are in asm, but the command appears only work for arm. So run this command first "azure config mode arm".
/CC @huangpf

**Comment by adammartin** [comment]
That is the issue.  Thanks!

It also appears that that step is in the notes of the walk through so this is user error.

Thanks for still helping!

**Comment by huangpf** [comment]
Thanks for confirming~ Close~
