### ISSUE TITLE
azure group export: argument name confusing

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2809]
Mode: **ARM**

excerpt from `azure group --help`:

```
help:    Shows a resource group for your subscription
help:      group show [options] <name>
help:
help:    Captures a resource group as a template, and saves it as file on disk.
help:      group export [options] <name> [directory]
help:
help:    Commands to manage your deployment in a resource group
help:      group deployment create [options] [resource-group] [name]
help:      group deployment list [options] <resource-group> [state]
help:      group deployment show [options] <resource-group> [deployment-name]
help:      group deployment stop [options] <resource-group> [deployment-name]
help:      group deployment delete [options] <resource-group> <deployment-name>
help:
help:    Commands to manager your deployment template in a resource group
help:      group deployment template download [options] [resource-group] [name] [directory]
help:
help:    Commands to list deployment operations in a resource group
help:      group deployment operation list [options] [resource-group] [name]
```

in this help message, the resource group argument is often referred to as `[resource-group]`, except in the `export` subcommand which reads:

    group export [options] <name> [directory]

I got confused and had to `export --help` to see if name actually refers to resource group. I think for this particular subcommand, we should replace `<name>` with `<resource-group>` to be consistent with the other subcommands.

**Comment by amarzavery** [comment]
This is not a subcommand. It is an operation on the group.
group deployment is a sub category inside group, where name refers to the deployment name and hence we have --resource-group.

The export operation is on the resource group. It is just another operation like `create/show/delete` hence has the switch `--name and -n`

**Comment by ahmetalpbalkan** [comment]
In that case, that's fair. Closing.
