### ISSUE TITLE
group export: should export indented/readable JSON

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2810]
CLI Version: **0.9.20**
OS Type: Mac

Mode: **ARM**

I just ran `azure group export <rg> <dir>` and this created me a 8 KB json file **with a single line**.

This command should create JSON files that are well indented and readable as ARM templates are meant to read by humans as well. I don't think there is any argument here that favors disk-space over readability.

**Comment by amarzavery** [comment]
@ravbhatnagar @vivsriaus - Can you take a look at this issue?

I think `JSON.stringify(object)` before writing it to the file does that.

If you use the 3rd parameter to JSON.stringify() that should pretty print it.
`JSON.stringify(object, null, 2)`// 2 spaces
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

**Comment by ravbhatnagar** [comment]
@vivsriaus - lets fix this. Agreed the output should be human readable.

**Comment by ahmetalpbalkan** [comment]
thanks!
