### ISSUE TITLE
group export: should generate parameters.json as well?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2811]
CLI Version: **0.9.20**
Mode: **ARM**

When you export a resource group from Azure Portal, it downloads a directory with contents:

![image](https://cloud.githubusercontent.com/assets/159209/14800348/eedfdc08-0af5-11e6-91bf-99686a38d1f4.png)

However `azure group export` command only creates a `template.json`, and not the `parameters.json`. I believe the common pattern that we advise to the users is to have is to have both files, so the xplat-cli should generate the `parameters.json` as well.

**Comment by amarzavery** [comment]
@ravbhatnagar @vivsriaus - Can you take a look at this issue?

**Comment by ravbhatnagar** [comment]
This was the current design. We are exploring the option of adding support for this in our API. Adding this to backlog. I will provide an update when I have more details.

**Comment by ravbhatnagar** [comment]
Fixed.
