### ISSUE TITLE
vm list: maybe IP address is more useful than Size?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2818]
CLI Version: **0.9.20**
Mode: **ARM**

If I run `azure vm list` I'm probably trying to figure out what my VMs are and what are their IP addresses (or maybe that's just me). But I think Public IP address is more relevant than Size/Location.

```
$ azure vm list -g ahmet-test
info:    Executing command vm list
+ Getting virtual machines
data:    ResourceGroupName  Name  ProvisioningState  PowerState  Location  Size
data:    -----------------  ----  -----------------  ----------  --------  -----------
data:    ahmet-test         myvm  Succeeded          VM running  westus    Standard_D1
data:    ahmet-test         vm    Succeeded          VM running  westus    Standard_D1
```

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan, want to get more user data. Could you let me know what the next steps you would do which need the ip address? For me, I need the ip address because sometimes i forgot to attach the dns label, so i ended up w/o the logical vm name.

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft I just created a VM with quick-create and closed the window that contains the IP address. Then I wanted to SSH, obviously I'm gonna need the IP address. I don't create FQDN names (they're more tedious to deal with) and without data I cannot comment on if that's something most people do.

**Comment by huangpf** [comment]
@devigned @sauryadas 
We shall tag these types of items as feature requests, instead of the ```IAAS``` tag that usually put?

**Comment by ahmetalpbalkan** [comment]
just this issue again, it's pretty annoying not seeing IP address in VM list result.

**Comment by huangpf** [comment]
A new command will be provided to fetch the IP info:
https://github.com/Azure/azure-xplat-cli/pull/2968

**Comment by ahmetalpbalkan** [comment]
@huangpf I don't think I'll type such a long command. 😵  closing apparently adding another column is tough...
