### ISSUE TITLE
Azure-cli throws exception with nodejs 6.0.0

### ISSUE THREAD

**Issue by waldner** [Azure/azure-xplat-cli#2825]
CLI Version: **0.9.20**
OS Type: Linux (Archlinux)
Installation via:  npm

Mode: **ARM**

Description:
`azure` throws exception

<pre>
$ azure
buffer.js:106
      throw new Error(
      ^
Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:106:13)
    at Interactor.__.extend.initProgressBars (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:41:24)
    at new Interactor (/usr/lib/node_modules/azure-cli/lib/util/interaction.js:32:8)
    at new AzureCli (/usr/lib/node_modules/azure-cli/lib/cli.js:43:22)
    at /usr/lib/node_modules/azure-cli/bin/azure.js:35:11
    at Object.exports.isTelemetryEnabled (/usr/lib/node_modules/azure-cli/lib/util/utilsCore.js:181:12)
    at Object.<anonymous> (/usr/lib/node_modules/azure-cli/bin/azure.js:27:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
</pre>

Steps to reproduce:
1) Run `azure` with node.js v6.0.0 (also with any argument, same thing)

**Comment by amarzavery** [comment]
@waldner - The issue was fixed yesterday in this PR https://github.com/Azure/azure-xplat-cli/pull/2821

**Comment by waldner** [comment]
Thanks. So how long will it take to get into npm?

**Comment by amarzavery** [comment]
@waldner 

This should be out by ~05/04.
If you wan to try the bits from dev branch to be unblocked then you can follow the instructions for installing from a branch of this repository over [here](https://github.com/Azure/azure-xplat-cli#installation-from-a-particular-branch-of-this-repository).

Basically you will have to download the tarball from the dev branch and install it via npm.

**Comment by waldner** [comment]
Ok, thanks!

**Comment by shaiksphere** [comment]
@amarzavery Any idea when this fix will be released?

**Comment by kendersec** [comment]
I'm still getting the error on a version that presumably fixed this:

> $ azure --version
> 0.10.0 (node: 6.1.0)

> $ azure storage file upload
> verbose: Error: If encoding is specified then the first argument must be a string
>     at new Buffer (buffer.js:106:13)
>     at Object.StorageUtil.getSpeedPrinter (/usr/lib/node_modules/azure-cli/lib/util/storage.util.js:748:21)
>     at __$uploadFile (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.file.js:866:45)
>     at __$uploadFile (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.file.js:854:140)
>     at __$uploadFile (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.file.js:854:156)
>     at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
>     at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.file.js:848:186)
>     at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.file.js:848:119)
>     at __tryCatch (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:150:4)
>     at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.file.js:848:74)
> error:   storage file upload command failed

**Comment by kendersec** [comment]
I guess based on the previous PR this was actually fixed 2 days ago as part of some other changes?

https://github.com/Azure/azure-xplat-cli/blame/dev/lib/util/storage.util._js#L761

When will that make it into npm?

**Comment by haocs** [comment]
@kendersec our next release will be 06/01. This fix should be available then.

**Comment by auridevil** [comment]
this worked for me, node 6.6, osx 10.10.5 :

```
sudo npm update -g npm
sudo npm install -g azure
sudo npm install -g azure-cli
```
