### ISSUE TITLE
Azure CLI is broken with Node v6.0.0.

### ISSUE THREAD

**Issue by macshonle** [Azure/azure-xplat-cli#2827]
### OS X Setup
CLI Version: **0.9.X**
OS Type: Mac:
```
$ uname -prsv
Darwin 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 i386
```

Installation via:  npm
```
$ node -v
v6.0.0
```
Also, I reinstalled it in this manner (before I filed this bug):
```
$ npm uninstall azure-cli -g
$ npm cache clear -g
$ \rm -rf ~/.streamline
$ npm install -g azure-cli
/usr/local/bin/azure -> /usr/local/lib/node_modules/azure-cli/bin/azure

> fibers@1.0.10 install /usr/local/lib/node_modules/azure-cli/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:454:6: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'?
      [-Wmismatched-new-delete]
                                        delete data;
                                        ^
                                              []
../src/fibers.cc:449:19: note: allocated with 'new[]' here
                                void** data = new void*[2];
                                              ^
1 warning generated.
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/fibers.node
Installed in `/usr/local/lib/node_modules/azure-cli/node_modules/fibers/bin/darwin-x64-v8-5.0/fibers.node`
/usr/local/lib
```
[Note, the compiler warning above seems unrelated, but I've included it for completion.]

### What Goes Wrong
The command cannot start, not even a simple `azure`, `azure -v`, or `azure help`:
```
$ azure help
buffer.js:106
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:106:13)
    at Interactor.__.extend.initProgressBars (/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:41:24)
    at new Interactor (/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:32:8)
    at new AzureCli (/usr/local/lib/node_modules/azure-cli/lib/cli.js:43:22)
    at /usr/local/lib/node_modules/azure-cli/bin/azure.js:35:11
    at Object.exports.isTelemetryEnabled (/usr/local/lib/node_modules/azure-cli/lib/util/utilsCore.js:181:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/azure-cli/bin/azure.js:27:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
```
This is unexpected, because the Azure CLI tools worked on my machine before I upgraded node.

Mode: **ARM** [although, technically we can't even set that yet, because the command crashes too soon]

Description:
`azure` command doesn't work at all

Steps to reproduce: [See above]

Error stack trace: [See above.]

**Please paste the content of ~/.azure/azure.err or C:\Users\username\\.azure\azure.err over here**
[Note: The files `~/.azure/azure.err` and `~/.azure/azure.details.err` exist on my machine, but are from previous errors due to human error: `resourceGroupName cannot be null`]

**Comment by amarzavery** [comment]
Fixed in the PR  #2821 that is merged in the dev branch. The new version will be available ~5/4.
Duplicate - https://github.com/Azure/azure-xplat-cli/issues/2825 
If you need the bits from dev branch follow the instructions [here](https://github.com/Azure/azure-xplat-cli#installation-from-a-particular-branch-of-this-repository).

**Comment by macshonle** [comment]
Thank you! I only searched the list of recent open bugs; I forgot to check the list of recent closed bugs.

**Comment by amarzavery** [comment]
No worries.
