### ISSUE TITLE
azure cli in ubuntu, "/usr/bin/env: 'node': No such file or directory"

### ISSUE THREAD

**Issue by bbetstcw** [Azure/azure-xplat-cli#2830]
I am using nodejs4.2.6 in Ubuntu. After installing the Azure CLI with `npm install azure-cli -g`, if I run `azure`, I get the error `/usr/bin/env: 'node': No such file or directory`. The error can be solved by creating a link with the command `ln -s /usr/bin/nodejs /usr/bin/node`. It's kind of silly to have this error, because the solution is so simple.

**Comment by amarzavery** [comment]
@bbetstcw - This is weird. I haven't seen that issue before. I am using azure-cli on Ubuntu on a regular basis and I have always got the installation correct.

**Comment by haocs** [comment]
@amarzavery - On Ubuntu, If 'node' is installed from Package manager it is named as 'nodejs' since node is referenced to another package.  And our bin/azure script is look for node instead of nodejs.

**Comment by haocs** [comment]
@bbetstcw please see this issue. https://github.com/nodejs/node-v0.x-archive/issues/3911

**Comment by amarzavery** [comment]
@bbetstcw - If you follow the instructions for installing node.js on Ubuntu or any other Linux flavor from [here](https://github.com/Azure/azure-xplat-cli#installing-the-latest-version-of-nodejs-on-different-linux-flavors) then it will install node.js with keyword node instead nodeJS. Basically, it will install node correctly.

And doing `npm install -g azure-cli` post that should work fine.

**Comment by eduardkoller** [comment]
@bbetstcw - can you please try installing node following these instructions, and let us know if this fixes the issue: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
