### ISSUE TITLE
docker-machine error when creaet vm

### ISSUE THREAD

**Issue by fthamura** [Azure/azure-xplat-cli#2839]
CLI Version: **0.9.20**Ubuntu
Mac / Win / Linux (Ubuntu, RedHat, etc.)
Installation via:  npm

Mode: **ARM / ASM**

Description:
cannot create azure vm

Steps to reproduce:

docker-machine create -d azure \
--azure-subscription-id="5d6b8a30-2988-xxx-a39a-5502c8f72220" \
--azure-subscription-cert="myCert.pem" \
--azure-location="East US" \
--azure-size=Small \
--azure-username="meruvian" \
merv-docker-machine

Error stack trace:

unning pre-create checks...
Error with pre-create check: "Get https://management.core.windows.net/5d6b8a30-2988-4700-a39a-5502c8f72220/services/hostedservices/operations/isavailable/merv-docker-machine: local error: internal error"

**Comment by amarzavery** [comment]
@huangpf @sauryadas - Please take a look.

**Comment by huangpf** [comment]
This seems to be service API internal error. Any logs for the VM creation?

**Comment by ahmetalpbalkan** [comment]
@fthamura it looks like you're using docker machine. can you please open an issue at https://github.com/docker/machine/issues instead?

**Comment by ahmetalpbalkan** [comment]
@fthamura also we strongly suggest updating to docker-machine 0.7.0 which is reimplemented using Azure Resource Manager stack. You can get it from docker machine github repo or Docker Toolbox as well.

**Comment by eduardkoller** [comment]
Will close this issue now - @fthamura, please open an issue at https://github.com/docker/machine/issues as suggested.
