### ISSUE TITLE
[asm] Not all images are returned with `vm image list`

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-xplat-cli#2855]
I have uploaded some images to a subscription which is enabled for publishing. I have published and replicated the image.

In PowerShell, I can see that RDFE knows about the image: `Get-AzureVMImage | ? { $_.PublisherName -icontains "Red Hat" }` shows me my private image.

In Xplat-Cli (asm mode), even when I'm in the correct subscription, `azure vm image list` does not contain my image.

**Comment by colemickens** [comment]
Looks like this was fixed in `0.9.20`.

**Comment by amarzavery** [comment]
@colemickens - The new release 0.10.0 was out 5 minutes ago https://github.com/Azure/azure-xplat-cli/releases/tag/v0.10.0-May2016

**Comment by colemickens** [comment]
Yeah, I saw you add the Dockerfile and was waiting for it to pop up on npm. I'll give it a shot now! Thanks!
