### ISSUE TITLE
Test for unique DNS name via Azure CLI

### ISSUE THREAD

**Issue by deltadan** [Azure/azure-xplat-cli#2860]
CLI Version: **0.9.X**
OS Type: Mac / Win 
Installation via: mac installer

Mode: ARM

Question:
Is there a command that will inform the user that there is a unique DNS name available in a region?  I'm looking for the equivalent to this PS: 
Test-AzureRmDnsAvailability -DomainNameLabel "[unique DNS name]"
                         -Location "[the location of your storage account]"

Thanks,
Dan

**Comment by amarzavery** [comment]
@romangromov - Are you aware of any command that provides the above functionality?

**Comment by romangromov** [comment]
@deltadan thanks for reinging this up. Please take a look at
```
>azure network traffic-manager profile is-dns-available -h
help:    Checks whether the specified DNS prefix is available for creating a Traffic Manager profile
help:
help:    Usage: network traffic-manager profile is-dns-available [options] <relative-dns-name>
help:
help:    Options:
help:      -h, --help                                   output usage information
help:      -v, --verbose                                use verbose output
help:      -vv                                          more verbose with debug output
help:      --json                                       use json output
help:      -r, --relative-dns-name <relative-dns-name>  the relative DNS name to check for availability
help:      -s, --subscription <subscription>            the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)
```

One thing I mention that there is no ability to specify region/location, let consult with responsible Azure DNS team and come back, stay tuned

**Comment by romangromov** [comment]
@deltadan thanks, reseived some feedback from Azure DNS team:
```
The Test-AzureRmDnsAvailability is not an Azure DNS cmdlet, it’s from NRP.  Test-AzureRmDnsAvailability is a confusing name.
```
Currently there is no support for DNS name availability check in Xplat-CLI ARM mode
