### ISSUE TITLE
template validate with --json parameter returns text

### ISSUE THREAD

**Issue by DustinVenegas** [Azure/azure-xplat-cli#2863]
CLI Version: **0.9.20**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Description:
`azure group template validate --json` command returns text instead of JSON on error. Even on an error it should return JSON for parsing purposes, especially since JSON is being returned with the correct error message. 

Steps to reproduce:
1) Run `azure group template validate ... --json` and notice the output text is not JSON. 
2) Run `azure group template validate ... --json -vv` and notice the return object body is JSON. 

Error stack trace:

**No error stack trace created**

**Comment by amarzavery** [comment]
@vivsriaus @ravbhatnagar - Was this fixed off lately?

**Comment by ravbhatnagar** [comment]
This has been fixed. Please reopen if you see the issue
