### ISSUE TITLE
[AzureChinaCloud][ARM] Failed to list the storage accounts because of unsupported api-versions

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2864]
CLI Version: **0.10.0**
OS Type: Linux (Ubuntu)
Installation via:  npm

Mode: **ARM**

Description:
`azure storage account list` command failed.

```
The resource type 'storageAccounts' could not be found in the namespace 'Microsoft.Storage' for api version '2016-01-01'. The supported api-versions are '2015-06-15,2015-05-01-preview'.
```

Steps to reproduce:
1) Run `azure login -e AzureChinaCloud`
2) Then run `azure storage account list`

Similar to #2824

**Comment by eduardkoller** [comment]
This is caused by the fact that the API version of Azure China is older than the API version of Azure global. The workaround here is to use the previous version (0.9.18) of the released CLI: https://github.com/Azure/azure-xplat-cli/releases/tag/v0.9.18-hotfix

**Comment by bingosummer** [comment]
It's fixed.
https://github.com/Azure/azure-xplat-cli/issues/2824#issuecomment-227054319
