### ISSUE TITLE
Creating general purpose storage option is missing

### ISSUE THREAD

**Issue by stevenlivz** [Azure/azure-xplat-cli#2865]
In order to get a general purpose storage account - and hence file storage, i seem to have to create a "RAGRS" account type first which does give me what I need and then I can change it to "LRS" and so on. I can't seem to create one directly - it always create a blob storage account and so my scripts fail.

`azure storage account create -l "westeurope" -g "my-rg" --type LRS test54321` #fails to create file/table

`azure storage account create -l "westeurope" -g "my-rg" --type RAGRS test54321` #works

I think we need to be able to specify the account type but i can't see this even in the [REST api documentation](https://msdn.microsoft.com/en-us/library/azure/hh264518.aspx).

**Comment by eduardkoller** [comment]
@yaxia - is this posssible?

**Comment by yaxia** [comment]
@stevenlivz Which version of Azure CLI are you using? I can create a LRS storage account that supports file/table directly. 
Could you please try the latest Azure CLI (0.10.0) with the following script:
    
    azure storage account create -l "westeurope" -g "my-rg" --sku-name LRS --kind storage test54321

**Comment by stevenlivz** [comment]
@yaxia Thanks. I was on OSX client 0.9.20 which i upgraded and with the new --sku-name option it works perfectly. Thanks!
