### ISSUE TITLE
Cannot Install SSL Cert .pfx file to Application Gateway via CLI

### ISSUE THREAD

**Issue by mrgoldsmith** [Azure/azure-xplat-cli#2866]
CLI Version: **10.0.x**
OS Type: Win
Installation via:  win-installer

Mode: **ARM**

Description:
`Cannot load SSL-cert to Application Gateway

Steps to reproduce:
1) Run `azure network application-gateway ssl-cert create %Resource Group% %Application Gateway% -c %certname% -f D:\whereever\mycert.pfx -p Password`

Error stack trace:

Password for the Cert has been verified.

2016-05-06T13:40:25.085Z:
{ [Error: Password not specified for certificate /subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/sslCertificates/crttest.]
  stack: [Getter/Setter],
  statusCode: 400,
  request: 
   { rawResponse: false,
     queryString: {},
     method: 'PUT',
     headers: 
      { 'x-ms-client-request-id': 'b829378c-1537-4020-8949-fd7a5a00ce13',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8',
        'user-agent': 'WindowsAzureXplatCLI/0.10.0' },
     url: 'https://management.azure.com/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway?api-version=2016-03-30',
     body: '{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway","location":"eastus","properties":{"sku":{"name":"Standard_Small","tier":"Standard","capacity":1},"gatewayIPConfigurations":[{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/gatewayIPConfigurations/appGatewayIpConfig","properties":{"subnet":{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/virtualNetworks/CLiVnet/subnets/CliSubNet"},"provisioningState":"Succeeded"},"name":"appGatewayIpConfig","etag":"W/\\"f6a8df63-bf1b-42cb-b4b4-148085c082c8\\""}],"sslCertificates":[{"properties":{"data":"MIIJ/AIBAzCCCbgGCSqGSIb3DQEHAaCCCakEggmlMIIJoTCCBfIGCSqGSIb3DQEHAaCCBeMEggXfMIIF2zCCBdcGCyqGSIb3DQEMCgECoIIE9jCCBPIwHAYKKoZIhvcNAQwBAzAOBAhw4OkT0yedNgICB9AEggTQ/WFlRVFSprYT/6+Jvbc4UcoYK+O5csAoAt4FDXMRje7qV7748xD7/KGgS93kLR1xHHd63BR92q+8wCSXakuw/y3AXCn9sdn9Mq3dfHzV/Fk34/s16SyLARIZMBczJHRLfffoItDPWMi/Q9R0cTTAbA0i0I1SxQEdQfjCrLq4awZYjDEqknDn7G9SzwTkgVopKfFeMIMo6SYFCdzKsc7B87dA1rto3YPvmQaskHQNxhy4BfY6WSSD1QrbHLwSurpMvs6TZmMJEiq/qEqOTRhtq0r5AJxxvjXHMMc62ZzGHSmJok6mgfwdqcjrpCFjlCCbNnz58rdtput5knVrF3qXycnYVZYrUrvn3BZdDGfD5NDoruDHWwgjUJZkMoDMQVQuwrezwh5QjRzVHo+JZYKc6ybMWDl4xo8vBc7NnIsbRuiOVx5UIK4xq5ocLEC1teKuUT2COr58mGBrWydKEt6pak/wNxPK5vx/EO2yXvT1P5T8u+HDyhu3OMwdQ9sX9BKanCiLnKsC/HW0a+7iMYD1Ykq/B5CQKEBMOMDt214gLZrvx3vRRxf7XTZea65/mOJFZH1QnmJfJfmkH5W+SJaBAq554/Ga1VLUc8GHWxzhvzW73EPF0nggg1QBGIWEmliq6wofilu+3B9p/Mu74+CnXW9ev54wKMjlYngSXr1OVG+JAlY01FYo6eMhsBacYfsP+UknufMGzuoIqE4t0Nzw+IsorA5ESm0pVxEFqzASMeCYLvKiMD3IZvvJXC7duz7WtfNbyr76pCiDJVXbJd/XxxEMQTTOtqB6Uf+PK74ECUQf2seAJgNtUFUGVJS2X7uCibK81AH7c/UxSWgXO9RzS/DXxdbIROhrdF02fdZ1IlohnyOq/Q7t5UvZuR8K77obHHyCofCGwT+gpd9sRy4JLbSdCXR/JXRm2MAitQAfh527viSPFqx+ayuutk7X1oVRGoc3cVbxBPNi+6Gbux6BfohEmCv1pEaAoM2e6QXXh4qTB2Ii8FhoCBZbt0RPQ/0DQaup8udypJcdvTYRq8cPn2NF7e12w6+hCIIYo4/gSbi7f4O7bTa7KRCDD6+azrSS2Ofye0kMJ2oc2VqJ+D/dM2PnWNR/VTjX2FCpXqW6brOGrQFCsNxbespNromovJkldElwk1PZ+nHsrhViLmqYam/TGOhtOunAZ5/tPMQHG6xDM5VcvTREZvqz6mHvqZIbeE4nyAJeL3iwdxS36t9Zfp49aVhaLI7xNex0SZxNM49y/FDH0a/ypyMKTvS5+AJZus5yQFGIwX5VRnAImlYzbqHu1kbRFHx+CbjL8ft5IVQnp7JKpd5Z4EYgH59GCVwfGCkybhrriUZSJtLOycGgPqaYZgVzL2ruYbL9pVpfTxNl896Y29gpKZ4/uKakqTRqTJP/EZR2kTsCD/zCDkPuMH84/bLowRKK6wzI+zD+rh6Lj3tpdqipW0qoEoKilCaRuKPFS+pvcga4Mb8p5qTJfD3lF5A5UAMhdAvkFrxNZBOvWqCBbHGv+T+JXUIz4xMtxZvlkCNvtx4O2MCEPiLmFB91IuO86L1nMM0K2Fj9lWA35SjRhtZFyu8GaYceGU4djMYT2VAI5ya1bMBaBfvOpKvXUJ/VIlSQIsaBz585Pecxgc0wEwYJKoZIhvcNAQkVMQYEBAEAAAAwVwYJKoZIhvcNAQkUMUoeSAA1ADAAMgA1AGQANwBjADMALQA1AGYAYwAwAC0ANABiAGUANwAtAGEAMgBjADIALQA3ADAAOAA4ADUAZABhADAAMgAxADYAMjBdBgkrBgEEAYI3EQExUB5OAE0AaQBjAHIAbwBzAG8AZgB0ACAAUwB0AHIAbwBuAGcAIABDAHIAeQBwAHQAbwBnAHIAYQBwAGgAaQBjACAAUAByAG8AdgBpAGQAZQByMIIDpwYJKoZIhvcNAQcGoIIDmDCCA5QCAQAwggONBgkqhkiG9w0BBwEwHAYKKoZIhvcNAQwBBjAOBAhdoclI1WRM9gICB9CAggNgEtLqRzEQCbWtsNlMEQcaX+wXmaW7i+dPyu3Cdrohta0fgBcSbPxYQF6uFNpatJ1ZlrXGy36b8l6p7npMADnP8kD8gOUbN/9b0dU/iQ50eBpEJKluEi/2mECjJBGs1b/wFx3YJYVcZefx+iV0dNuiPwF8mAtKN6KcT6Oowclem5837R+XzVc1PP/WehfIiZAWVva9vsJZvc7yrCGxGqaZZJP48u6r5F+nfZfmbDfGt9NtgzWA1zJ1utwOZJX0EvlKM1i/wexuEBnwOHwj/0p6CCR7b76ylSHqivIy+84V2DYeYikkOr8fqzIf3qDVVk0KNnty8rHG1d9F7BYPiMqWyvifVsLi5teUi8gQiNttuZmJp5o+S15qNcw1c5MHFZRXu2C3CW1ufriLCpmMF0qXsYMO/Ajno8fT8NeRbI/GDLwoo/lNXGXUGtrCzLaGffKB4xTpIu/arceNWCvvqci54qNN4SVbEzUQpYevgfp6rPw4nojt26g5qQ+8husvMWlVISjVzp+mK0PqLwdVXAWoV9VPcAPWtL76hrA+B6iC6DzxfxTmb9a4CaNMCUFbSdXXxQoe/2A79Qf5DOP6eraNJR4C9sDYwlRQjEsrcgCZ9Xjazsumwk75QpElCscGULp2Lxk1YHfGUiStuFdjCSqA40Cy4B7gE9RWiyEw2Pet+XUojXKUqejTDu2Y4IqjOyLsNPXpFvVeTnSZWvixJSl/PAajmE74kRryh36uk7RDQEG4SQaoIRha4UZKKm9mm5/URwPk3kHvAKRx2MFh+5NCYn+GsZa+PaoMBgnPFLGtfICQi5cd0H0NjAIlZj+erchZvZsKjZuf2K/pqQkm1mS215Bp+VSY6AUhEx7gx7GzNCqgnLfwzM6UUHeSdaYvDPPi6HpDK/vphY2CQ7lonUxG6ODHFUoei5nTv7WxiA/8I56ZIt2mrP0c3D8AAPR/2RQaiYsRZX4WN9xGbYfg84MVUehdhiPCQQKUR+Hpv74FoT2UVTHtjy6QQqM3Lm4K994yinOHumtm5FGgzsEFX55sLSyCeOHxDhGHslzNrlPH/5a/pl720nSNRSoPLe6m4tEG7NG3IjejNTinkC7EdygJomAr9eE8zNquP4mCmqAKtu1pl/rUyyAk/RCfLFYU817aMDswHzAHBgUrDgMCGgQUEG/RyLtKqEJH286qNuBdKNa52lYEFGdwhuykbq184PbGdhX19deR01ITAgIH0A=="},"name":"crttest"}],"frontendIPConfigurations":[{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/frontendIPConfigurations/appGatewayFrontendIP","properties":{"privateIPAddress":"10.0.0.5","privateIPAllocationMethod":"Dynamic","subnet":{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/virtualNetworks/CLiVnet/subnets/CliSubNet"},"provisioningState":"Succeeded"},"name":"appGatewayFrontendIP","etag":"W/\\"f6a8df63-bf1b-42cb-b4b4-148085c082c8\\""}],"frontendPorts":[{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/frontendPorts/appGatewayFrontendPort","properties":{"port":80,"provisioningState":"Succeeded"},"name":"appGatewayFrontendPort","etag":"W/\\"f6a8df63-bf1b-42cb-b4b4-148085c082c8\\""}],"probes":[],"backendAddressPools":[{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/backendAddressPools/appGatewayBackendPool","properties":{"backendAddresses":[{"ipAddress":"10.0.1.10"},{"ipAddress":"10.0.1.11"}],"provisioningState":"Succeeded"},"name":"appGatewayBackendPool","etag":"W/\\"f6a8df63-bf1b-42cb-b4b4-148085c082c8\\""}],"backendHttpSettingsCollection":[{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/backendHttpSettingsCollection/appGatewayBackendHttpSettings","properties":{"port":80,"protocol":"Http","cookieBasedAffinity":"Disabled","requestTimeout":30,"provisioningState":"Succeeded"},"name":"appGatewayBackendHttpSettings","etag":"W/\\"f6a8df63-bf1b-42cb-b4b4-148085c082c8\\""}],"httpListeners":[{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/httpListeners/appGatewayHttpListener","properties":{"frontendIPConfiguration":{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/frontendIPConfigurations/appGatewayFrontendIP"},"frontendPort":{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/frontendPorts/appGatewayFrontendPort"},"protocol":"Http","requireServerNameIndication":false,"provisioningState":"Succeeded"},"name":"appGatewayHttpListener","etag":"W/\\"f6a8df63-bf1b-42cb-b4b4-148085c082c8\\""}],"urlPathMaps":[],"requestRoutingRules":[{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/requestRoutingRules/rule1","properties":{"ruleType":"Basic","backendAddressPool":{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/backendAddressPools/appGatewayBackendPool"},"backendHttpSettings":{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/backendHttpSettingsCollection/appGatewayBackendHttpSettings"},"httpListener":{"id":"/subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/httpListeners/appGatewayHttpListener"},"provisioningState":"Succeeded"},"name":"rule1","etag":"W/\\"f6a8df63-bf1b-42cb-b4b4-148085c082c8\\""}],"resourceGuid":"116724a9-402f-44df-ac74-e913e1e686c4","provisioningState":"Succeeded"},"etag":"W/\\"f6a8df63-bf1b-42cb-b4b4-148085c082c8\\""}' },
  response: 
   { body: '{\r\n  "error": {\r\n    "code": "ApplicationGatewaySslCertificatePasswordMissing",\r\n    "message": "Password not specified for certificate /subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/sslCertificates/crttest.",\r\n    "details": []\r\n  }\r\n}',
     headers: 
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-length': '324',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'x-ms-request-id': '36ede5cd-9812-4852-8336-23b8ce06adcd',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
        'x-ms-ratelimit-remaining-subscription-writes': '1199',
        'x-ms-correlation-request-id': '27135e5a-2bd0-4210-b17b-b8dbe1b201fd',
        'x-ms-routing-request-id': 'WESTUS:20160506T134025Z:27135e5a-2bd0-4210-b17b-b8dbe1b201fd',
        date: 'Fri, 06 May 2016 13:40:24 GMT',
        connection: 'close' },
     statusCode: 400 },
  code: 'ApplicationGatewaySslCertificatePasswordMissing',
  body: 
   { code: 'ApplicationGatewaySslCertificatePasswordMissing',
     message: 'Password not specified for certificate /subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/sslCertificates/crttest.',
     details: [] },
  __frame: 
   { name: '_setAppGateway__30',
     line: 989,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\network\\appGateway.js',
     prev: 
      { name: 'addSsl__9',
        line: 291,
        file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\network\\appGateway.js',
        prev: [Object],
        calls: 2,
        active: false,
        offset: 26,
        col: 9 },
     calls: 0,
     active: false,
     offset: 6,
     col: 75 },
  rawStack: [Getter] }
Error: Password not specified for certificate /subscriptions/299cc140-7d19-419f-a30f-92618bc65968/resourceGroups/TSCLi/providers/Microsoft.Network/applicationGateways/CliAppGateway/sslCertificates/crttest.
  <<< async stack >>>
  at _setAppGateway__30 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\network\appGateway.js:995:76)
  at addSsl__9 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\network\appGateway.js:317:10)
  at __126 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\network\network.js:2628:18)
  <<< raw stack >>>
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-arm-network\lib\operations\applicationGateways.js:681:19
    at retryCallback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest\lib\filters\redirectFilter.js:36:9)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\utils.js:543:7
    at handleRedirect (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\utils.js:520:9)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\logging.js:412:7
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest\lib\requestPipeline.js:125:16)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)

**Comment by eduardkoller** [comment]
@romangromov - can you please take a look?

**Comment by romangromov** [comment]
Adding @MikhailTryakhov as commands owner

**Comment by MikhailTryakhov** [comment]
Hi @eduardkoller  @mrgoldsmith thank you for your job!
This issues is fixed and would be published in next release 0.10.0.
I'll provide you details when it will be available soon.

**Comment by MikhailTryakhov** [comment]
Hi @mrgoldsmith @eduardkoller 
thank you for a great job.
This issues is fixed and would be published in next release.
I'll provide about you details soon. Will try to publish it ASAP,

**Comment by eduardkoller** [comment]
The fix will be included in the upcoming June release

**Comment by ronzionp** [comment]
@eduardkoller hi, i'm getting the exact same error using azure-cli 0.10.0 (node: 4.2.4) on Mac OS. Just wanted to ask if the fix will be available for Mac version too.

Thanks.

**Comment by MikhailTryakhov** [comment]
Hi @ronzionp 
Azure CLI is multi-platform tool and all the fixes would be available on Mac OS too.

Sorry for inconvenience.
