### ISSUE TITLE
Maximum call stack size exceeded when uploading large file to ADLS

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-xplat-cli#2868]
CLI Version: **0.9.20**
OS Type: Linux
Installation via:  npm

Mode: **ARM**

Description:
23GB file upload to ADLS fails with maximum call stack size exceeded error.

Steps to reproduce:
1. create a 23GB file
2. Run the following command: azure datalake store filesystem import -n <adls account> -p <local path to 20gb file, including name> -d /some/server/path/file.txt -f

**Here is the information received from the customer who reported this issue:**
When uploading a large file from one virtual machine to Azure Lake Store Data with the CLI tool, the transfer stops after about 23Gb with this message.

2016-05-03T04: 44: 17.140Z:
{[RangeError: Maximum call stack size exceeded]
 Stack: [Getter]
 __frame:
 {Name: '__1'
 line: 244
 file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js'
 prev:
 {Name: '__5'
 line: 207
 file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js'
 prev: undefined,
 calls: 1
 Active: false,
 offset: 36
 Pass: 6}
 calls: 0,
 Active: true,
 offset: 21
 Pass: 32}
 rawStack: [Getter]}
raw stack unavailable
 <<< >>> Async stack
 at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js:265:33)
 at __5 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/datalakestore/datalakestore.js:243:7)

**Comment by eduardkoller** [comment]
@begoldsm - we're trying to repro tis on our side in order to investigate. Will keep you posted

**Comment by amarzavery** [comment]
This PR https://github.com/Azure/autorest/pull/1342 fixes it.
