### ISSUE TITLE
ARM: DNS Zone import: how do escape a semicolon in a value?

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-xplat-cli#2869]
CLI Version: **0.10.0**
OS Type: Win
Installation via:  npm 

Mode: **ARM**

Description from customer:

> I am using the CLI (on Windows) to import a zone file into Azure DNS.  Several TXT values in the zone file include semi-colons.  E.g. “a=b; c=d”.  The import appears to be parsing the value and truncating everything after the semicolon (semicolons are a comment identifier).  How can I escape the semicolon (or make it a literal string)?  I have tried single quotes, escaping with “\;” and “;;”, adding “@” or “$” in front of the string.  
> Even if I manually enter the value in the Azure portal, export the zone file and then re-import the same file, the value is messed up.  Is this just a bug or is there some way to pass a semicolon in a value?

+@jtuliani for visibility

**Comment by eduardkoller** [comment]
@jtuliani - from Roman's second statement, looks like a server issue. Is this your team?

**Comment by jtuliani** [comment]
The API works fine, this is a CLI issue on zone file import (I was able to repro)

**Comment by eduardkoller** [comment]
?@romangromov - can you please investigate further?
btw, azure resource create --tags works fine with semicolons

**Comment by romangromov** [comment]
Hi @eduardkoller @jtuliani currently I'm working on `CLI Code-Generator` requested by DeepakRajendranMsft as higher priority task. Just started this issue for visibility and not to lose in e-mail thread

**Comment by silverl** [comment]
I just hit this issue as well. I'm importing a zone transfer file that contains DKIM key values. The DKIM key values contain semi-colons (for better or for worse). The CLI is truncating everything after the semi-colon. Perhaps it's some kind of automatic SQL injection protection, or it's an artifact of some kind of BIND heritage, where semicolons denote comments? 

This makes it much harder to automate using Azure DNS as a secondary DNS provider. I cannot easily automate the import.

**Comment by jtuliani** [comment]
@silverl Thanks for flagging, please can you provide an example zone file line that exhibits this problem?

@MikhailTryakhov please can you look at this?

**Comment by MikhailTryakhov** [comment]
@jtuliani that's very interesting question asked by Roman.
We can improve our existing RegExp but better to collect all available cases we can find now.

I mean that specified case may be fixed by rule, that if semicolon is **not** in quotes - it's a comment.
If quotes were added - it's just a semicolon,
```I'm_in_data;comment is here ```
```txt_record_name 3600 TXT "text has been started; still text is here" ;comment is here ```

That can make some problems because

**Comment by jtuliani** [comment]
I think we can go ahead with the simple 'if in quotes' rule.  For SPF records, for example, the RFC says to enclose the string in quotes.

**Comment by MikhailTryakhov** [comment]
Thanks, @jtuliani,
would be implemented soon

**Comment by demosdemon** [comment]
Hit this problem as well.

**Comment by demosdemon** [comment]
DMARC records as well

```    
_dmarc.pabu.co. 86400 IN TXT "v=DMARC1; p=quarantine; rua=mailto:55fb457be3@rep.dmarcanalyzer.com,mailto:dmarc@pabu.co; rf=afrf; pct=75;"
```

```
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'PUT',
silly:       headers: {
silly:           x-ms-client-request-id: '5e939639-e099-41fc-af10-76bd20626e2e',
silly:           accept-language: 'en-US',
silly:           Content-Type: 'application/json; charset=utf-8',
silly:           user-agent: 'WindowsAzureXplatCLI/0.10.7'
silly:       },
silly:       url: 'https://management.azure.com/subscriptions/.../resourceGroups/pabuco/providers/Microsoft.Network/dnszones/pabu.co/TXT/_dmarc?api-version=2016-04-01',
silly:       body: '{"name":"_dmarc","properties":{"TTL":86400,"TXTRecords":[{"value":["\\"v=DMARC1"]}]}}'
silly:   }
```

**Comment by demosdemon** [comment]
https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/network/zoneFile._js#L34
https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/network/zoneFile._js#L74

The problem is here where everything after a semicolon is indiscriminately removed. They should be handled on a line by line basis/

**Comment by MikhailTryakhov** [comment]
finally fixedand would be published in next release December, 14
