### ISSUE TITLE
Azure CLI on MAC - initial mode set to ASM instead of ARM

### ISSUE THREAD

**Issue by sivaedupuganti** [Azure/azure-xplat-cli#2870]
CLI Version: **0.10.0**
OS Type: Mac
Installation via:  mac installer

Mode: **ARM / ASM**

Description:
* Deployed Azure CLI for MAC from http://aka.ms/mac-azure-cli
* azure help shows the current mode is ASM
```
help:    Current Mode: asm (Azure Service Management)
```

**Comment by amarzavery** [comment]
@sivaedupuganti - You can flip it to ARM using `azure config mode arm`

**Comment by sivaedupuganti** [comment]
Yes, I did that. But shouldn't the default mode be set to ARM?

**Comment by amarzavery** [comment]
People who still use ASM more over ARM would want default to be ASM. It is a subjective thing.

**Comment by eduardkoller** [comment]
@amarzavery - let's use the telemetry data to see what mode is more often used, and default to that.

**Comment by Krylon360** [comment]
not all of Azure services have been migrated to ARM yet. There are still a lot that rely on ASM. I'd expect the default config to change once all things Azure have been migrated to ARM.

**Comment by amarzavery** [comment]
We shall be defaulting to ARM mode from the [August 2016 release](https://github.com/Azure/azure-xplat-cli/milestone/27). There will be more improvements over here:
1. As a last step in the login command, we shall check if `~/.azure/config.json` is present and has the mode set. If not then we shall set it with the default mode. This will preserve the current mode of the user.
2. `azure account clear -q` will clear everything except the "config.json". This will also preserve the current mode of the user.
3. If the user is in "asm" mode and executes a command of "arm" mode (example: `azure group list`) then the CLI throws an error `error: 'group' is not an azure command. See 'azure help'.`. Now, the error message will tell the user the current mode as well. This should help the user to know that he is in an incorrect mode.
```
error:   'group' is not an azure command. See 'azure help'.
The current mode is: asm (Azure Service Management).
```
