### ISSUE TITLE
Level 2 resource type is not supported by azure resource

### ISSUE THREAD

**Issue by bbetstcw** [Azure/azure-xplat-cli#2871]
I've found out that `azure resource show` only support level 1 resource type. For example, the below command is good.

    azure resource show Default-SQL-EastAsia <server> Microsoft.Sql/servers 2014-04-01-preview

However, if I want to get level 2 resource type. It's not working.

    azure resource show Default-SQL-EastAsia <server>/<database> Microsoft.Sql/servers/databases 2014-04-01-preview

I add `-vv` option to the command, and see the rest api it's using.

    https://management.azure.com/subscriptions/a679c265-5ef2-48fe-8378-5f435b48536b/resourcegroups/Default-SQL-EastAsia/providers/Microsoft.Sql/databases/<server>%2F<database>?api-version=2014-04-01-preview

This is not the same as PowerShell command `Get-AzureRmResource`.

**Comment by amarzavery** [comment]
@bbetstcw - You need to use the --parent switch to provide the parent or layer 1 resource.
```
Amars-MacBook-Pro:azure-xplat-cli amarz$ azure resource show -h
help:    Gets one resource within a resource group or subscription
help:    
help:    Usage: resource show [options] <resource-group> <name> <resource-type> <api-version>
help:    
help:    Options:
help:      -h, --help                            output usage information
help:      -v, --verbose                         use verbose output
help:      -vv                                   more verbose with debug output
help:      --json                                use json output
help:      -g --resource-group <resource-group>  the resource group name
help:      -n --name <name>                      the resource name
help:      -r --resource-type <resource-type>    the resource type
help:      -o --api-version <api-version>        the API version of the resource provider
help:      --parent <parent>                     the name of the parent resource (if needed), in path/path/path format
help:      --subscription <subscription>         the subscription identifier
help:    
help:    Current Mode: arm (Azure Resource Management)
Amars-MacBook-Pro:azure-xplat-cli amarz$ 
```

azure resource show ... --parent servers/<serverName> ....

**Comment by amarzavery** [comment]
@bbetstcw - Is this issue resolved for you? If so, then I can close it.

**Comment by bbetstcw** [comment]
Yes, the problem is solved. Thank you.
