### ISSUE TITLE
how to create AD user ?

### ISSUE THREAD

**Issue by jimyjohny** [Azure/azure-xplat-cli#2888]
CLI Version: **0.9.X**
OS Type: Mac / Win / Linux (Ubuntu, RedHat, etc.)
Installation via:  npm / github repo

Mode: **ARM **

Description:
Is there any option to create AD user ?  cli now supports RBAC , but we have to create user via web interface before assigning the role using cli.

**Comment by amarzavery** [comment]
@jimyjohny - That is a good point. This was not added because of a push from the service team.
@shuagarw - Can this be done with the latest version of graph library that we have in node sdk?

**Comment by amarzavery** [comment]
This will be a part of the August 2016 release
