### ISSUE TITLE
No way to get ftp credentials for site ("/publishxml" endpoint)

### ISSUE THREAD

**Issue by dudadornelles** [Azure/azure-xplat-cli#2893]
CLI Version: **0.10.X**
OS Type: Mac
Installation via:  npm

Mode: **ASM**

Environment: **AzureCloud**

Description:
No way to get ftp credentials ("/publishxml" endpoint)

I'm trying to automate the deployment on App Services using ftp to copy a couple of files over but I can't find a way to get the ftp credentials using the cli. In fact it doesn't seem to be a feature. Is there a workaround? Y'all planing on adding it?

**Comment by eduardkoller** [comment]
@ahmedelnably - can you assist with this?

**Comment by ahmedelnably** [comment]
@dudadornelles Unfortunately this is not available in the current CLI, we are planning to add the support for it, but only for ARM mode.
