### ISSUE TITLE
[Question] Does Azure CLI has the command to publish images?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2900]
There is a module `Microsoft.WindowsAzure.Commands.ServiceManagement.PlatformImageRepository` which is used to publish image in Azure Powershell.
Does Azure CLI has the similar command for this?

**Comment by bingosummer** [comment]
Any update about this issue? Thanks in advance.

**Comment by haocs** [comment]
@huangpf  - could you help answer this question?

**Comment by huangpf** [comment]
We don't have it yet. But I think @ahmetalpbalkan has a tool to do so?

**Comment by ahmetalpbalkan** [comment]
I developed a tool to publish VM extensions (it's in a private repo)

There is https://github.com/Microsoft/azure-vhd-utils-for-go that you can use to upload VHDs.

**Comment by bingosummer** [comment]
@huangpf 
Do you have a plan to support this command?

**Comment by huangpf** [comment]
+@sauryadas

**Comment by eduardkoller** [comment]
@bingosummer - can you please detail your scenario? What Powershell command are you using (and looking for an xPlat CLI equivalent to)?

**Comment by bingosummer** [comment]
My scenario is similar to https://azure.microsoft.com/en-us/documentation/articles/azure-stack-add-image-pir/.
But I want to publish an image to Platform Image Repository in Azure instead of Azure Stack.
For Powershell, I need to import the module `Microsoft.WindowsAzure.Commands.ServiceManagement.PlatformImageRepository` manually, and then run the command.

**Comment by eduardkoller** [comment]
Not supported in CLI at this time.
