### ISSUE TITLE
Error using Azure CLI to download file from Azure Data Lake Store

### ISSUE THREAD

**Issue by moapurva** [Azure/azure-xplat-cli#2901]
CLI Version: **0.9.X**
OS Type: Linux (CentOS)
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
I am getting an error using Azure CLI to download a 26GB file from ADLS to an Azure HDP sandbox VM that has a premium disk attached. Sandbox is in the same Azure region as ADLS.

Steps to reproduce:
1)  Run command: azure datalake store filesystem export myadlsname /myadlsrootdir/26GBzipfile.zip /mylocaldir/26GBzipfile.zip

Error stack trace:

node: ../src/node_object_wrap.h:60: static T* node::ObjectWrap::Unwrap(v8::Handle<v8::Object>) [with T = node::Buffer]: Assertion `!handle.IsEmpty()' failed.
Aborted

**Comment by haocs** [comment]
@begoldsm - could you please take a took?

**Comment by begoldsm** [comment]
@amarzavery can you help out? This does not look like an issue with ADLS directly, this looks like a deeper problem within node CLI, which I am not particularly familiar with.

**Comment by begoldsm** [comment]
Ping on this @amarzavery @haocs this appears to be an issue deeper in the stack with buffer management within the xplat CLI.

**Comment by moapurva** [comment]
The specific download error seems to be resolved - there is an issue I've opened #3149 to address a more general download problem.
