### ISSUE TITLE
First invocation is not thread safe 

### ISSUE THREAD

**Issue by devmanhinton** [Azure/azure-xplat-cli#2908]
Simple: https://github.com/Azure/azure-xplat-cli/blob/710dadee4ec88794a39f1d2164dcafe582e47549/lib/util/utilsCore.js#L42-#l44

There is a race condition possible here.
![screen shot 2016-05-27 at 10 54 22 pm](https://cloud.githubusercontent.com/assets/1439051/15624723/f92a276e-245d-11e6-9f3b-e6dbbc5591dd.png)

**Comment by haocs** [comment]
@devmanhinton - cli runs in single thread model so there should not be a race condition. Did you run two/more cli commands parallely?

**Comment by devmanhinton** [comment]
Yep -- if that was not clear that was the problem I was alluding to -- so `azure cli` is not safe to use with more then one caller at a time?

**Comment by haocs** [comment]
If there are multiple `azure cli` running at the same time and they are trying to write to the same file, there will be an issue(a race condition among processes). So I will suggest not running multiple commands at the same time.
