### ISSUE TITLE
Dockerfile is pointless

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2915]
Dockerfile in this repo is supposed to build from source code by COPYing the source code inside the image.

We already have a Dockerfile that does `npm install azure-cli` at https://github.com/Azure/azure-cli-docker, it is pointless to have a copy.

Also any github project you go, the Dockerfile is supposed to provide a containerized build environment for source code presented in the repo direcrtory. It is a convention.

**Comment by yugangw-msft** [comment]
@amarzavery, i agree with ahmet on this. Apologize if I don't have context on this. I suggest we remove the docker file in our repro, unless we build by copying source file, but that will introduce the flakiness coming with the streamline file(those *._js files). Use "npm install" is the most reliable way, which has been covered by azure-cli-docker

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft I think it is a really good practice to make the development environment buildable inside a docker container. This would help clean up the repo a little bit and feel the pain of someone trying to build from source on a clean machine.

**Comment by yugangw-msft** [comment]
I don't use docker that much. If we do want to build from repro, in the docker file we need to incorporate the [logic](https://github.com/Azure/azure-xplat-cli/blob/dev/compile-for-publish.sh) used for `npm publish azure-cli`. More or less we should get rid of those "*._js" files

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft that's fine you can just `RUN ./script.sh` as a step in dockerfile if that gets the job done. Dockerfiles are the modern makefiles.

**Comment by yugangw-msft** [comment]
Great, let us follow the convention and update the docker file.

**Comment by ahmetalpbalkan** [comment]
Still an issue.

**Comment by haocs** [comment]
@ahmetalpbalkan - Fix included in this PR https://github.com/Azure/azure-xplat-cli/pull/3001 which builds docker image based on source code. Could you help review it and let us if there is any issue found.

**Comment by ahmetalpbalkan** [comment]
@haocs ok reviewing, thx. my first impression is your docker context (i.e. stuff you're sending to docker engine to build) is enormous (=432 MB). I believe you're sending bunch of binaries etc inside Docker image that might not be necessary. I suggest evaluating that and potentially using a `.dockerignore` file (like a `.gitignore` but for docker builds basically).

**Comment by ahmetalpbalkan** [comment]
@haocs other than that it looks good to me and does the job 👍 .

**Comment by haocs** [comment]
@ahmetalpbalkan thanks for your suggestions. I added a .dockerignore file(basically ignore tests and node_modules folders) then files that sent to docker engine reduced to 100MB :)
