### ISSUE TITLE
ARM template with function app + GitHub + environment variables

### ISSUE THREAD

**Issue by morsh** [Azure/azure-xplat-cli#2925]
Hi,
I wanted to create a simple ARM templates with the following requirements:

1. The template with deploy a storage account and a function app
2. It will associate the function app with the deployed storage account via environment settings
3. The function app will be connected to a GitHub repo:

https://github.com/morsh/functions
The connecting env variable is: **AzureWebJobsStorage**

The following two cases occur:

### Case 1
I deploy the attached ARM template and the environment variables are omitted from the deployment and only the source control deployment is completed.

### Case 2
I separate the "sourcecontrol" section to another ARM template and perform 2 deployments - In this case the environment variables and the source control are both deployed successfully.

Please tell me if\when this is going to be fixed.

p.s. I attached the relevant ARM template and parameters + the commands I used for deployment.

[func-arm-temp.zip](https://github.com/Azure/azure-xplat-cli/files/300205/func-arm-temp.zip)

**Comment by eduardkoller** [comment]
@ravbhatnagar @vivsriaus - can you please take a look?

**Comment by ravbhatnagar** [comment]
@morsh - Can you please try adding an explicit depends on the StorageAccount in your appsettings resource and see if it solves this issue?
"apiVersion": "2016-03-01",
                    "name": "appsettings",
                    "type": "config",
                    "dependsOn": [
                        "[resourceId('Microsoft.Web/sites', variables('functionsWebAppName'))]"
                        "[resourceId('Microsoft.Storage/storageAccounts/', variables('STORAGE_ACCOUNT'))]"
                    ],

**Comment by morsh** [comment]
Hi @ravbhatnagar @vivsriaus @eduardkoller,
I tried your suggestion but this still doesn't work.

I need to perform two deployments. The first deployed CI, the second deployed the env. variables.

**Comment by morsh** [comment]
p.s. this happens in web apps as well as function apps.
Versions: npm - 4.4.4; azure-cli - 3.10.6

**Comment by morsh** [comment]
Hi,
As suggested by @davidebbo, adding a dependency between appsettings and source control deployment resources solves this issue.

I think that any order between appsettings and source control might work as long as there;s a dependency from the second to the first sub-resource, but I haven't tried it yet.

As it is, it seems this issue is fixed by the suggestion.

**Comment by morsh** [comment]
Hi,
As suggested by @davidebbo in https://github.com/Azure/azure-xplat-cli/issues/2618, adding a dependency between appsettings and source control deployment resources solves this issue.

I think that any order between appsettings and source control might work as long as there;s a dependency from the second to the first sub-resource, but I haven't tried it yet.

As it is, it seems this issue is fixed by the suggestion.

**Comment by ravbhatnagar** [comment]
Closing this.
