### ISSUE TITLE
'Azure ad app create' command does not provide means to set Reply URL

### ISSUE THREAD

**Issue by scotmoor** [Azure/azure-xplat-cli#2927]
CLI Version: 0.9.15
OS Type: Linux (Ubuntu)
Installation via:  ??

Mode: ARM

Environment: AzureCloud

Description:
'azure ad app create' does not support setting the Reply URL(s),

Steps to reproduce:
1) Run `azure ad app create --help'

Issue:
The 'azure ad app create' command does not provide a parameter to set the reply URL(s) for the application you are creating.

**Comment by eduardkoller** [comment]
@shuagarw @vivsriaus - can you please take a look?

**Comment by amarzavery** [comment]
This will be a part of the July 2016 release.
