### ISSUE TITLE
Outputs from `azure public-ip show ...` and `azure network nic show ...` do not include the VM instance ID

### ISSUE THREAD

**Issue by thomas1206** [Azure/azure-xplat-cli#2928]
Description:
Outputs from `azure public-ip show ...` and `azure network nic show ...` do not include the VM instance ID

Steps to reproduce:
1) Run `azure public-ip show ...`
2) Run 'azure netork nic show ...

Outputs from `azure public-ip show ...` and `azure network nic show ...` do not include the VM instance ID, making it difficult to identify the VM to which the NIC/IP is associated.

**Comment by eduardkoller** [comment]
@romangromov, @ DeepakRajendranMsft - is it possible to show the VM ID, if a VM is associated with the IP/NIC?

**Comment by romangromov** [comment]
Could you please clarify the version of CLI as I have "Virtual Machine" field in `azure network nic show ...` command results (0.10.1).

**Comment by MikhailTryakhov** [comment]
Hi @eduardkoller 
this may be added only on SDK side. Please let me know if we should make a thread about that.
Currently closing this issue
