### ISSUE TITLE
Intermittent DNS resolution errors against Azure China API

### ISSUE THREAD

**Issue by thomas1206** [Azure/azure-xplat-cli#2930]
CI operations intermittently encounter DNS resolution errors when invoking the Azure CLI
 
```
error:   getaddrinfo ENOTFOUND management.chinacloudapi.cn management.chinacloudapi.cn:443
error:   group deployment create command failed
 
 
{ [Error: getaddrinfo ENOTFOUND management.chinacloudapi.cn management.chinacloudapi.cn:443]
  stack: [Getter/Setter],
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'management.chinacloudapi.cn',
  host: 'management.chinacloudapi.cn',
  port: 443,
  __frame:
   { name: '__1',
     line: 57,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js',
     prev:
      { name: '__1',
        line: 46,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js',
        prev: undefined,
        calls: 2,
        active: false,
        offset: 10,
        col: 24 },
     calls: 0,
     active: false,
     offset: 2,
     col: 44 },
  rawStack: [Getter] }
Error: getaddrinfo ENOTFOUND management.chinacloudapi.cn management.chinacloudapi.cn:443
  <<< async stack >>>
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:59:45)
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/group/group.deployment.js:56:25)
  <<< raw stack >>>
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

**Comment by eduardkoller** [comment]
Are you on a corp firewall? Are you using a custom DNS server?

**Comment by ahmetalpbalkan** [comment]
I see the same behavior against the AzurePublicCloud within redmond corpnet.

For China I expect it to be more frequent as it is GFW.

**Comment by thomas1206** [comment]
It happened in our partner's environment. They are not within MSFT corp firewall, but they may have their own firewall.
@ahmetalpbalkan you are right, it is more frequent for Azure China Cloud API. But my guess is: it is not related to GFW, since the dev box is actually in US, not in China. It might be related to the API server?

**Comment by ahmetalpbalkan** [comment]
@thomas1206 But if the dev box was in China, this would happen less, right? Isn't that how GFW works?

**Comment by thomas1206** [comment]
Oh, I got your point. The ChinaCloud API endpoint is in China. I thought it was in US. Thanks @ahmetalpbalkan. 
Any suggestion for mitigation/workaround?

**Comment by ahmetalpbalkan** [comment]
Not as far as I know. We had the same problem in DockerExtension and docker-machine. If you're not in China, the API works very poorly. 

If you are in China, API works fine but this time it can't install anything from repos hosted on GitHub, AWS S3 etc. (such as docker).

Having retries might have helped, but not a lot. Some requests just get in, some don't. As far as I can tell it is so random. It sometimes is a timeout, sometimes a TLS cert error, sometimes totally unreachable for a while.

**Comment by thomas1206** [comment]
@eduardkoller Is that possible to setup China Cloud API endpoint in both US and China and add traffic manager? Or implement some failover logic.

**Comment by eduardkoller** [comment]
Targeting the China cloud from US-based clients is one of the mainstream scenarios.
