### ISSUE TITLE
Uri containing SaS token cant be used to deploy template

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-xplat-cli#2931]
The following command gives errors if the template-uri param contains sas token -
azure group deployment create -g sasgroup --template-uri

The following types of errors are shown-
'sp' is not recognized as an internal or external command,
operable program or batch file.
'sv' is not recognized as an internal or external command,
operable program or batch file.

The reason is that we try to construct the deployment name using the template-uri which is not a valid name as it contains certain special characters. 

Workaround: Explicitly specify the deployment name in the above command using -n param.

**Comment by ahmetalpbalkan** [comment]
@ravbhatnagar can you please surround the argument with `"` the  `&` character in the URL a special meaning in bash and other UNIX shells. I highly doubt this is an xplat-cli issue.

**Comment by ravbhatnagar** [comment]
@ahmetalpbalkan - yes " does not work. If the following command is given to create the deployment which includes the sas in the uri - 

group deployment create -g test --template-uri "https://storagecontosotemplates.blob.core.windows.net/templates/helloworld.json?se=2016-06-08T01%3A31%3A00Z&sp=r&sv=2015-02-21&sr=c&sig
=QdourkXfyw63%2BndpHF47zI2DBGCspa8BqimD9geDuIk%3D"

We will set the deployment name as follows - "helloworld.json?se=2016-06-08T01%3A31%3A00Z&sp=r&sv=2015-02-21&sr=c&sig=QdourkXfyw63%2BndpHF47zI2DBGCspa8BqimD9geDuIk%3D"

**Comment by andrew-mestas** [comment]
Just finished creating validation tests for a work around which will sanitize the provided name in the case a uri with a sas token is provided.

**Comment by ravbhatnagar** [comment]
This is fixed
