### ISSUE TITLE
Issue with login to azure china cloud, successful login but commands fail

### ISSUE THREAD

**Issue by azuretek** [Azure/azure-xplat-cli#2934]
CLI Version: 0.10.1 (node: 5.5.0)
OS Type: Mac
Installation via: npm

Mode: ASM

Environment: Azure China Cloud

Description:
I login to AzureChinaCloud, it works but then any subsequent commands seem to fail with a "We don't have a valid access token" error. My subscription name is in chinese, so it's using chinese characters. I'm wondering if it's storing the token in a way that it can't read it after it's written it? I can login just fine and manage my azure cloud using the powershell, but not via the azure cli on OSX which is my primary work computer. Not to mention I'd have to convert all of our azure-cli tools and configs to PowerShell, which would be a lot of work if I can't get this working.

```
azure login -e AzureChinaCloud`
info:    Executing command login
-info:    To sign in, use a web browser to open the page https://aka.ms/deviceloginchina. Enter the code APBDKG73A to authenticate.
/info:    Added subscription *******
info:    Setting subscription "*******" as default
+
info:    login command OK
```

```
azure vm list
info:    Executing command vm list
+ Getting virtual machines                                                     
error:   We don't have a valid access token. Please run "azure login" again.
info:    Error information has been recorded to /Users/arenhart/.azure/azure.err
error:   vm list command failed
```

Steps to reproduce:
1) Run `azure login -e AzureChinaCloud.`
2) Then run `azure vm list`

Error stack trace:

2016-06-10T18:05:48.423Z:
{ [Error: We don't have a valid access token. Please run "azure login" again.]
  stack: [Getter/Setter],
  __frame: 
   { name: 'getVMList__5',
     line: 67,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/vm/virtualMachine.js',
     prev: 
      { name: 'listVM__6',
        line: 386,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient.js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 5,
        col: 35 },
     calls: 0,
     active: false,
     offset: 15,
     col: 74 },
  rawStack: [Getter] }
Error: We don't have a valid access token. Please run "azure login" again.
  <<< async stack >>>
  at getVMList__5 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/vm/virtualMachine.js:82:75)
  at listVM__6 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient.js:391:36)
  at __3 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/vm/vm.js:183:16)
  <<< raw stack >>>
    at _polishError (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/adalAuthForUser.js:64:10)
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/adalAuthForUser.js:48:25
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:107:9
    at /usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:52:16
    at iterate (/usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:263:24)
    at Object.async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:284:9)
    at Object.async.forEachSeries.async.eachSeries (/usr/local/lib/node_modules/azure-cli/node_modules/async/lib/async.js:220:22)
    at KeychainTokenStorage._.extend.removeEntries (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/osx-token-storage.js:70:11)
    at /usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:103:26
    at TokenCache._.extend._loadEntries (/usr/local/lib/node_modules/azure-cli/lib/util/authentication/token-cache.js:45:14)

**Comment by yugangw-msft** [comment]
If you follow the [workaround] (https://github.com/Azure/azure-xplat-cli/issues/2756#issuecomment-224398671), are you able to see the token in the `~/.azure/accessTokens.json`? Also check out the `azureProfile.json` and see whether the Chinese characters get persist correctly?
Before you do it, please run `azure account clear` or just delete the 'azureProfile.json'

**Comment by azuretek** [comment]
The workaround resolved my issue!

`export AZURE_USE_FILE_TOKEN_STORAGE=1`

After logging in the token exists in the accessTokens.json file, I don't see any weird special characters that would've prevented this from working before. I'm wondering what caused the issue in the first place.
