### ISSUE TITLE
feature request: add flag to accept/reject telemetry for automated install scenarios

### ISSUE THREAD

**Issue by squillace** [Azure/azure-xplat-cli#2937]
CLI Version: **0.10.1+**
OS Type: Mac / Win / Linux (Ubuntu, RedHat, etc.)
Installation via:  npm / brew / win-or-mac installer / docker / github repo

Mode: **ARM**

Environment: **AzureCloud/Azure China Cloud/US Government/Blackforest/Azure Stack**

Description:
Automated install scenarios need to handle automatic telemetry "nag" prompt on first use. Suggest some `--telemetry-disable` or `--telemetry-enable` switch to enable the scenario.

Steps to reproduce:
Please make it such that we can do fully automated installs and automatic accept of telemery. Currently we get a "nag" screen, such that even if our first command to azure-cli is "azure-cli telemetry --disable" that command gets a prompt "do you want to disable telemetry".... yes... we do... which is why the command itself is telling it to. if the command is a command to active/disable telemetry... dont nag.

From: https://azure.microsoft.com/en-us/documentation/articles/xplat-cli-install/#comment-2717821148

**Comment by amarzavery** [comment]
Ah I see. We shall fix that. Its a one time thing. Once set, it will not bother you again until the .azure directory from the user's home profile is deleted.
@haocs FYI

**Comment by squillace** [comment]
Right. Feature ask was a way in automated installations to suppress/agree on installation/first run. maybe even an `azure --telemetry-accept` command that no-ops except setting that value. Dunno. but clearly the requestor was installing a LOT, or the "first time only" thing wouldn't be annoying, right? Automated installation scenario....

**Comment by squillace** [comment]
or perhaps an additional switch to `azure config`?

**Comment by terrancesnyder** [comment]
For the moment we worked around it by shoving into `~/.azure` the json file with the telemetry nag and then also did a `yes -n | azure`.

**Comment by amarzavery** [comment]
Telemetry is a one time ask. It defaults to no in 30 seconds. It saves the response in a file in ~/.azure/telemetry.json. It will only prompt you again if you delete the .azure folder or the telemetry.json file.

**Comment by terrancesnyder** [comment]
cool... i think by us using puppet to "prestage" the `~/.azure/telemtry.json` we've worked around it however, probably just a nit-pick as stated in ticket comments at this point that its a bit doggy for us to work around. thanks for looking into.

**Comment by squillace** [comment]
yeah, @amarzavery, @terrancesnyder is correct in this case, IMHO, because when you start using CI/CD you're going to create tons of these VMs and install crap in an automated fashion. I think we have to provide some way to say "yes" or "no" automatically. That's the ask. 

so if I understand, if @terrancesnyder drops a `~/.azure/telemetry.json` file with "yes" in it, it should work for his scenario? It's not an unusual one.

**Comment by amarzavery** [comment]
@squillace @terrancesnyder - So I understand one thing correctly for sure.

- The following behavior does not happen today. 
When you install the latest version of CLI on a brand new machine (in this context: ~/.azure/telemetry.json file does not exist) and execute `azure telemetry -d` or `azure telemetry -e` then CLI should not prompt you for telemetry and do as the user directed.

We will fix this in the upcoming release. 

Will this also solve the problem for automated installs?

**Comment by squillace** [comment]
Ah, ok. (Now I need to confirm. :-))

```
master ✔ $ azure telemetry --help
help:    Manages the data collection preference.
help:
help:    Usage: telemetry [options]
help:
help:    Options:
help:      -h, --help     output usage information
help:      -v, --verbose  use verbose output
help:      -vv            more verbose with debug output
help:      --json         use json output
help:      -e, --enable   use this flag to enable telemetry
help:      -d, --disable  use this flag to disable telemetry
help:
help:    Current Mode: arm (Azure Resource Management)
```

means that we can currently disable the telemetry prompt using that command? If so, I think this satisfies the requirement. 

@terrancesnyder ?

**Comment by amarzavery** [comment]
You can install the source code from the dev branch of the repo by following the instructions over [here](https://github.com/Azure/azure-xplat-cli#installation-from-a-particular-branch-of-this-repository) and test it out. Let me know if you find any issues.
