### ISSUE TITLE
"azure group delete" tries to delete group with name "undefined"

### ISSUE THREAD

**Issue by nathanleclaire** [Azure/azure-xplat-cli#2938]
CLI Version: 0.10.0
OS Type: Ubuntu
Installation via:  npm

Mode: ARM

Environment: AWS

Description / Steps to reproduce:

```console
$ azure group delete
Delete resource group undefined? [y/n] n
info:    group delete command OK
```
Wanted the help but it offered to delete a "undefined" group instead :)

**Comment by haocs** [comment]
@nathanleclaire - Thank you for reporting this issue. `azure group delete` should validate group name before execution. 
However, `azure group delete` shall not provide help info and It will try to execute this command instead. To get help of a command, `-h` is required.

**Comment by eduardkoller** [comment]
Yep, looks like a bug. Let's fix it.

**Comment by nathanleclaire** [comment]
👍
