### ISSUE TITLE
ARM CLI missing options for existing virtualNetworkResourceGroup and vnet-id

### ISSUE THREAD

**Issue by Krylon360** [Azure/azure-xplat-cli#2940]
CLI Version: **0.10.1**
OS Type: Mac 
Installation via:  npm, brew, mac installer

Mode: ARM

Environment: AzureCloud

Description:
`azure vm create` command doesn't have a flag to specify an existing virtualNetworkResouceGroup to be able to deploy a new VM / Deployment into an existing VNET.

Steps to reproduce:
1) Run `azure vm create --help`
2) no option for `--virtualNetwork-Resource-Group` or `--vnetID`. 

Should be an option for `-VN, --vnet-id`, and `-VRG, --vnet-resource-group`. If these options are flagged; then `-F, --vnet-name` should be required; however; at it's current state; if `-S / --subnet-id` is flagged; the cli will nullify the `-F/--vnet-name` key:value pair.

This would fall in line with how the REST API and Deployment Template works.
ex:
```
    "vnetID": "[resourceId(parameters('virtualNetworkResourceGroup'), 'Microsoft.Network/virtualNetworks', parameters('virtualNetworkName'))]",
    "subnet1Ref": "[concat(variables('vnetID'),'/subnets/',variables('subnet1Name'))]"
```

```
Existing Options:
 -S, --subnet-id <subnet-id>                                           the subnet identifier
help:           e.g. /subscriptions/<subscriptipn-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Network/virtualNetworks/<vnet-name>/subnets/<subnet-name>
help:      -F, --vnet-name <vnet-name>                                            the virtual network name
help:           If this is an existing vnet then it must exists under the current resource group identified by resource-group
help:           If this is an existing vnet then vnet-subnet-name is required
help:                If no subnet exists with name vnet-subnet-name then a new subnet will be created
help:                To create new subnet - vnet-subnet-address-prefix is required
help:           A new vnet will be created if no vnet exists with name vnet-name in the current resource group
help:           To create new vnet - vnet-address-prefix, vnet-subnet-name and vnet-subnet-address-prefix are required
help:           Please use subnet-id to refer an existing subnet under a vnet in a different resource group
help:           vnet-name, vnet-address-prefix, vnet-subnet-name and vnet-subnet-address-prefix will be ignored when subnet-id is specified
help:      -P, --vnet-address-prefix <vnet-address-prefix>                        the virtual network address prefix in IPv4/CIDR format
help:      -j, --vnet-subnet-name <vnet-subnet-name>                              the virtual network subnet name
help:      -k, --vnet-subnet-address-prefix <vnet-subnet-address-prefix>          the virtual network subnet address prefix in IPv4/CIDR format
```

Deployment Templates as well as the RestAPI contain this feature. 
This is a MUST HAVE / CRITICAL flag for any type of automated deployments.

**Comment by eduardkoller** [comment]
@romangromov - can you please investigate?

**Comment by MikhailTryakhov** [comment]
Hi @Krylon360 
thank you for a great fix you found. In such cases we usually do not add extra-options. 
To create VM using subnet from another resource group you can use ```subnet-id``` option, which contains all required info about existing subnet.
This subnet may be in any resource group you need.

This opportunity was blocked in CLI (thanks for you again!). I've made fixes for such cases and updated this helpful option description in [PR#3007](https://github.com/Azure/azure-xplat-cli/pull/3007) (on review now).
Please feel free to ping me if you have any questions
