### ISSUE TITLE
Non-interactive shells should not block waiting for user input

### ISSUE THREAD

**Issue by robbyt** [Azure/azure-xplat-cli#2946]
CLI Version: **0.10.1**
OS Type: Mac
Installation via: mac installer
Mode: ARM

Environment: AzureCloud

Description:
The new version of the Azure CLI blocks on non-interactive shells, asking if the user would like to enable telemetry. This breaks scripts that use the azure CLI for automation.

The reason that people use the CLI is for *scripting and automation*, and applications which block for user input must detect if they're being run in an interactive shell, and only block when it's appropriate. 

It is trivial to check if the application is being run from an interactive shell. E.g.,
https://www.gnu.org/software/bash/manual/html_node/Is-this-Shell-Interactive_003f.html
http://www.tldp.org/LDP/abs/html/intandnonint.html

EDIT: I noticed there's a timeout for the telemetry prompt, that defaults to false. Thank you for adding this feature. However, I think the best way to solve this in the future is to only show these prompts when the shell is interactive. If the prompt MUST be shown, then `exit 1` until the azure cli is run interactively.

**Comment by robbyt** [comment]
This is related to #2420 - however, the proposed fix is to add a new flag. I don't think this is necessary, because it's simple to detect if the shell is interactive.

**Comment by huangpf** [comment]
Calling ```azure telemetry --disable``` at the first place will solve the problem?

**Comment by robbyt** [comment]
@huangpf thank you for the suggestion.

However, there may be other features added later that block on non-interactive shells unless this is fixed.

The real solution is to always inspect the run-time shell environment before assuming it's interactive.

**Comment by amarzavery** [comment]
@robbyt - It is a one time thing unless you delete `~/.azure/telemetry.json` file. 
The PR https://github.com/Azure/azure-xplat-cli/pull/2952 fixes a bug where the CLI prompts for telemetry even when the telemetry command was the first command that was executed.

From the next release, you can enable `azure telemetry -e` or disable `azure telemetry -d` telemetry once in your script and it wont ever bother you again*. 

* - On the condition that  `~/.azure/telemetry.json` file is present and has the right content in it.

**Comment by robbyt** [comment]
@amarzavery thank you for the info.

The fact remains, non-interactive shells should not block waiting for user input.

And it's very easy to detect non-interactive shells.

**Comment by eduardkoller** [comment]
Low priority. Even in non-interactive shells, the only impact is that *the very first* execution of the cli is being delayed by 30 seconds.

**Comment by amarzavery** [comment]
We need a solution that will work cross platform (on windows commandprompt, git bash, windows bash, mac terminal, Linux bash shell as a minimum).

I have a better idea. We can come up with an environment variable named `AZURE_CLI_SCRITPING_MODE`, which when set, will never prompt, but throw an error saying that the required parameter was missing rather than waiting for an input from the user.

**Comment by robbyt** [comment]
Thanks for reopening this. It's an important feature for anyone who's done
any real sysadmin work.

I'd suggest taking some design inspiration from Debian/Ubuntu's dpkg. They
have a concept of "frontends", and the frontend can be forced via
environment variables, but it can also be automatically selected based on
context.

http://manpages.ubuntu.com/manpages/xenial/en/man7/debconf.7.html
