### ISSUE TITLE
azure vm show: wrong exit code semantics

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2955]
CLI Version: **0.9.10**
OS Type: Mac
Mode: **ARM**

When I run `azure vm show` on a non-existing VM it returns with exit code = 0. That's not cool. 

```
azure vm show ahmetb-rdma centos6; echo ExitCode=$?
info:    Executing command vm show
+ Looking up the VM "centos6"
warn:    No VMs found
info:    vm show command OK

ExitCode=0
```

How else you suggest people scripting with xplat CLI to determine if a VM exists or not?

**Comment by MikhailTryakhov** [comment]
Hi @ahmetalpbalkan 
this behavior is expected CLI ASM functionality - throw warnings instead of errors.

**Comment by huangpf** [comment]
Thanks @MikhailTryakhov for the info.

**Comment by ahmetalpbalkan** [comment]
> Hi @ahmetalpbalkan 
> this behavior is expected CLI ASM functionality - throw warnings instead of errors.

@MikhailTryakhov I don't understand please explain...  How else you suggest people scripting with xplat CLI to determine if a VM exists or not? What does ASM have anything to do with ideal behavior?

**Comment by ahmetalpbalkan** [comment]
@huangpf I don't see enough reasons to close this. I suggested what the ideal behavior should be and something probably makes more sense from a command-line design perspective.

**Comment by huangpf** [comment]
@ahmetalpbalkan OK, reopen for @kamaljit & @sauryadas to help triage.

**Comment by MikhailTryakhov** [comment]
Hi @ahmetalpbalkan 
my removed comment line was about ASM - current issue is for ARM and issue is fixed.

As for cases when we need to determine does the VM exist - you receive message, that VM with such name was not found. You can use ```vm list```command to find all existing VMs.

Assume that this issue is fixed and would be published in next release
