### ISSUE TITLE
A feature request for `azure network lb rule show[options] <resource-group> <lb-name> <name>`.

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#2957]
CLI Version: **0.10.1**
OS Type: Linux (Ubuntu)
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
There is no command to show the VMs in a backend address pool of a load balancer.

A feature request for `azure network lb rule show[options] <resource-group> <lb-name> <name>`.
This command should show the detail information of the address pool.

**Comment by eduardkoller** [comment]
@romangromov - can you please triage?

**Comment by MikhailTryakhov** [comment]
Hi @bingosummer 
now you can use ``` azure network lb show <resource-group> <lb-name> --json ``` command instead to review load balancer details. ``` Show ``` was excluded from sub-items commands because of that would be not so informative to make extra-command for that.

Hi @eduardkoller 
Please let me know if that would be better to add such extra-commands to lb block.

**Comment by bingosummer** [comment]
@MikhailTryakhov Thanks for your reply.

I can get the nic id from `azure network lb show <resource-group> <lb-name> --json`. However, without `--json`, I can't get the nic id.

From my understanding, `--json` should give the exactly same contents with a different format. So, the command `azure network lb show <resource-group> <lb-name>` should also show the nic id in the backend pools.

And it's fine for me if the `show` commands for sub-items are not so informative.

**Comment by bingosummer** [comment]
@MikhailTryakhov 

Sorry, my understanding may be not right. I tried some other command (e.g. `azure provider list --json`), and found `--json` can show more information.
So `--json` is not only a different format, but more information.

**Comment by MikhailTryakhov** [comment]
Hi @bingosummer, you're right. Lb case is very reprsentative: it's impossible to display so many related IDs without ``` --json ``` option - that would be ugly and unreadable.
That's why some details are shown using this option.

Please let me know if I can help anything els
