### ISSUE TITLE
The azure network nic address-pool add command has been renamed. Any chance that you could include text along the lines of "...the new command syntax is ....". Just to keep it friendlier and give folks an easy way to fix things when their scripts break. THanks - Planky

### ISSUE THREAD

**Issue by plankytronixx** [Azure/azure-xplat-cli#2958]
CLI Version: **0.9.X**
OS Type: Mac / Win / Linux (Ubuntu, RedHat, etc.)
Installation via:  npm / brew / win-or-mac installer / docker / github repo

Mode: **ARM / ASM**

Environment: **AzureCloud/Azure China Cloud/US Government/Blackforest/Azure Stack**

Description:
`azure vm show` command doesn't output VM name.

Steps to reproduce:
1) Run `azure vm create ...`
2) Then run `azure vm show ...`

Error stack trace:

**Please paste the content of ~/.azure/azure.err or C:\Users\username\\.azure\azure.err over here**

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).

**Comment by eduardkoller** [comment]
@plankytronixx - can you please clarify what command are you referring to? The issue's title talks about 'azure network nic', but in description you are referring to 'azure vm show'

**Comment by amarzavery** [comment]
@eduardkoller - @plankytronixx has not updated the default template that our repo provides in the issue description. He has described his problem in the issue title.

**Comment by eduardkoller** [comment]
The '-add' command has been in the cli just for 1 sub-release, and since then it has been always 'create'.
