### ISSUE TITLE
azure vm quick-create: The storage account already taken

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2963]
CLI Version: **0.10.0**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

```
➜  ~ azure vm quick-create ahmet-rdma centos6 westus linux openlogic:CentOS-HPC:6.5:latest alp --ssh-publickey-file ~/.ssh/id_rsa.pub -z Standard_A8
info:    Executing command vm quick-create
+ Looking up the VM "centos6"
info:    Verifying the public key SSH file: /Users/alp/.ssh/id_rsa.pub
info:    Using the VM Size "Standard_A8"
info:    The [OS, Data] Disk or image configuration requires storage account
+ Looking up the storage account cli4265626714193486306
info:    Could not find the storage account "cli4265626714193486306", trying to create new one
+ Creating storage account "cli4265626714193486306" in "westus"
error:   The storage account named cli4265626714193486306 is already taken.
info:    Error information has been recorded to /Users/alp/.azure/azure.err
error:   vm quick-create command failed
```

I don't know what kind of randomization seed being used in coming up with that storage account name, but it is coming up the same name all the time (for the same command on different subs).

I was deleting a VM with the same name (and created using the same command) **in my another subscription** but storage account names overlapped while the deletion is still going on.

I suggest randomizing this a little bit more.

**Comment by huangpf** [comment]
Currently, if the exactly same parameter input is used, it would generate the same storage name. One workaround is to change one of the inputs -- VM name, user name, RG name, image name, etc. -- even changing upper/lower cases may work...

**Comment by ahmetalpbalkan** [comment]
> Currently, if the exactly same parameter input is used, it would generate the same storage name.

even on different subscriptions? that does not sound like a good idea.

**Comment by huangpf** [comment]
The chance to get a conflict on storage account is more or less the same as someone stole one of your favorite random storage name, which should be minimal...

But with that said, we would definitely think about how to add more reasonable randomness in it, and yet deterministically testable...

**Comment by huangpf** [comment]
@haocs @amarzavery @yugangw-msft 
Is there a way in the code to determine whether this is a test run or non-test run? In that way, in the test we can generate deterministic value, or completely random value in the other way.

**Comment by ahmetalpbalkan** [comment]
@huangpf can't we just:

    hash(subscription+resourcegroup+vmname)

in this case if we get the same error it just means that we're very very unlucky.

**Comment by huangpf** [comment]
This will make the tests break, because tests run by different sub in record & playback modes will be using inconsistent hashes.

**Comment by huangpf** [comment]
Reopen until the follow-up code change using the new utils function.

**Comment by amarzavery** [comment]
closing it as the ci passed for #3105
