### ISSUE TITLE
Proposal: azure config get-mode

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2974]
Mode: ARM

I have a script that uses ARM commands, so I temporarily set `azure config mode arm` however now my script has a side effect on user's set up.

If you could give me a way to set this temporarily or a way to get it (such as `config get-mode` that returns `asm` or `arm`) I can now:

- figure out if I need to run this command at all
- set the mode back to its original value

**Comment by haocs** [comment]
@ahmetalpbalkan , could you explain the issue of  using ```azure config mode arm```? We don't have command like 'get-mode' for now. As a workaround, you could use ```azure | tail -n1 | grep -q 'arm'; echo $?``` in bash to tell current mode.

**Comment by ahmetalpbalkan** [comment]
> could you explain the issue of using azure config mode arm

side effects... If I write a script that uses azure CLI, it may change user's config mode (as a side effect) = not cool.

> As a workaround, you could use

I know but a cmdlet ideally would be better.

**Comment by ahmetalpbalkan** [comment]
To be more precise, can you guarantee that this `tail -1` trick is going to work forever? Probably not. A commandlet would be more reliable.

**Comment by yugangw-msft** [comment]
a workaround, use `config list`:
```bash
azure config list  --json
```
and you will get
```bash
{
  "mode": "arm"
}
```
If it is missing, you can assume it is `asm`

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft hah, when it is asm it actually returns asm. So this is good enough... Thanks!
