### ISSUE TITLE
azure vm extension: naming/terminology mistake

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#2984]
`azure vm extension` commands take arguments like `--public-config-path`/`--private-config-path` to describe data passed to the VM extensions.

If you go to PowerShell or the API itself (ARM templates and such) the terminology is `settings`; not `config`.

I understand it is too late to change. Please do not repeat the same mistake if you ever end up writing a new CLI. Having multiple terms to describe the same concept adds nothing but confusion.

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan, thanks for the notes. `settings` is the right name. It is used at basic swagger spec level as well.

**Comment by eduardkoller** [comment]
adding @jasonrshaver - this needs to be tracked for the future.
Closing the issue - no change to be done here.
