### ISSUE TITLE
Remove dependency on `$HOME` environment var?

### ISSUE THREAD

**Issue by kvz** [Azure/azure-xplat-cli#2991]
CLI Version: **0.9.10**
OS Type: Linux (Ubuntu)
Installation via:  npm

Description:
We're getting crashes when we try to run azure-cli in environments where HOME is not set. I believe HOME is set by Bash, but we're trying to execute it without wrapping a shell around it via child_process.spawn.

Error stack trace:

```
throw new Error('No HOME path available');
^

Error: No HOME path available
  at homeFolder (/srv/recent/11563/api2/node_modules/azure-cli/lib/util/utilsCore.js:56:9)
  at Object.exports.azureDir (/srv/recent/11563/api2/node_modules/azure-cli/lib/util/utilsCore.js:38:15)
  at Object.exports.readConfig (/srv/recent/11563/api2/node_module"
```

Seeing as there are modules such as https://www.npmjs.com/package/user-home, that are cross-platform and dealing with edge cases like these. I wonder if it would make sense to use that and remove relying on this variable?

**Comment by haocs** [comment]
@kvz - Based on implementation of `user-home`, it relies on `process.env.HOME/USER` too. I think if will return an `null` result if `process.env` is not given.
Could you try pass `process.env` explicitly when you call `child_process.spawn`?

**Comment by kvz** [comment]
Ah I see. This works when I start the program from the CLI (which is bash, providing HOME) but when I start the program as a deamon, there is no shell wrapping it. There is a user executing it though, and this user has a homedir. It seems there would be a way to establish this without relying on environment variables set by Bash. I had hoped/assumed user-home provided such mechanism

**Comment by haocs** [comment]
The purpose for looking up home dir is to find the default cli config folder(https://github.com/Azure/azure-xplat-cli/blob/dev/lib/util/utilsCore.js#L39). If `process.env.AZURE_CONFIG_DIR` is present,  cli won't look for home dir. I think you could pass `AZURE_CONFIG_DIR="path/to/config"` for each cli execution(or set env variable). This tells cli to look/store config in the specified directory instead of home directory.

**Comment by huangpf** [comment]
+1

**Comment by huangpf** [comment]
But why would users need to set any environments to proceed? Is it fine to assume a temporary or the current directory as what CLI is looking for?

I also encountered this issues in the following environments: 1) WS docker, and 2) our build server, and this is impacting the automation process.

**Comment by haocs** [comment]
I think config file is distinct for each user so it is reasonable to store config file at user's home folder separately. It is risky to store config files in a temporary or current directory. 
Currently, cli figures out config dir in the following strategy:
1. if `process.env.AZURE_CONFIG_DIR` is present, use it. Done.
2. if `process.env.AZURE_CONFIG_DIR` is not given, try to find out user's home dir
3. if neither of them is available throw error.
For most of  the cases, you don't have to set an environment variable to proceed.

**Comment by haocs** [comment]
@huangpf - Could you specify your issues? why is '$HOME'/process.env not present on your build server?

**Comment by huangpf** [comment]
The build server is provided by another team that we can't control the default environment variables. Also, by default a Windows machine without user login yet might not have these values setup, e.g. the latest Windows container image. You can try it out at: https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-container-samples/windowsservercore

A similar question from us is that why would CLI assume these 2 folders are always specified?

**Comment by haocs** [comment]
I see. If home directory is not available, you have to set up `AZURE_CONFIG_DIR' variable(set AZURE_CONFIG_DIR="folder you want to use") and cli will pick it up and write/read config file there. Otherwise, how could CLI find out configs in your next execution?
It is common to store personal config in user's home directory by default and it works for majority scenarios. Honestly, I did not see a better option that is distinct/private per user. 
What folder would you suggest as default folder for user config?

**Comment by huangpf** [comment]
In this case, it's a design decision that whether it's needed to persist the user data within a certain folder, or a temp folder that is only valid during that session.

Also, this condition indicates it's in an automated environment instead of user-interactive, so telemetry should be disabled.

**Comment by amarzavery** [comment]
Irrespective of user or automated environment, we would like to have the telemetry data to improve performance of commands. Authomated scripts or environments are configured by humans ;)

**Comment by huangpf** [comment]
@amarzavery You made a very good point, and I think we shall include telemetry. The problem I meant to say about telemetry is that -- an acknowledge ```Y``` keypress and ```Enter``` keypress for the initial prompt might not be feasible during automated run, so there should be an easier way for automation to opt in or out. Thanks.

**Comment by kvz** [comment]
> Based on implementation of user-home, it relies on process.env.HOME/USER too. I think if will return an null result if process.env is not given.

I've had a chance to look into this myself now, and while it indeed checks for `process.env.HOME`, if it does not find this, it will gracefully fall back to other methods of establishing the HOME dir, vs crashing hard, as Azure-CLI did for us in Production (where we run without a Bash wrapper), while tests passed in CI (tests are started from bash there).

For reference: user-home relies on os-homedir: https://github.com/sindresorhus/user-home/blob/master/index.js
and os-homedir has fallbacks as to not rely solely on environment being set: https://github.com/sindresorhus/os-homedir/blob/master/index.js#L18.

> why is '$HOME'/process.env not present on your build server?

HOME is provided by Bash. During development, there often is a parent Bash process that the developer is working in, so it's always around. If you however do not have a parent Bash process starting the cli, you don't have HOME. In many environments (production in our case), having an interactive shell to start processes is not desired for efficiency and security reasons. Instead, our node process is started by Upstart, which shells out to azure-cli via child_process.spawn direclty, meaning we don't needlessly bring an interactive shell into this transaction. Also meaning HOME is not set.

> What folder would you suggest as default folder for user config?

I'm fine with it Azure CLI wants to store data in our home directory. Anything in HOME is fine. If a single best location is up for discussion, I'd vote `~/.config/azure-cli`. If something more flexible yet still standardized is desired, I would vote using https://www.npmjs.com/package/rc. If a small change is desired to avoid crashed in production, I would vote keeping everything as is, but instead of relying on the environment solely to establish the path to the homedir, use the suggested user-home npm package instead, so that all platforms are covered in a more robust way. One might also have a look at Node's own [`os.homedir`](https://nodejs.org/api/os.html#os_os_homedir) function, but that excludes older Node platforms, so I regard this as less desirable.

**Comment by haocs** [comment]
@kvz , thanks for your specification. We'd like to take this dependence if it could solve your problem. 
But before that, I'd like to figure out your use scenario and make sure this fix would work as expected. Could you provide more info of how to repro your issue?

**Comment by kvz** [comment]
Say you want to run your Node.js server as an Upstart service, you might have a stanza like so

```bash
description "Transloadit.com Node.js API2"
author      "kvz"

stop on shutdown
respawn
respawn limit 20 5

limit nofile 32768 32768

script
  set -e
  mkfifo /tmp/api2-log-fifo
  ( logger -t api2 </tmp/api2-log-fifo & )
  exec >/tmp/api2-log-fifo
  rm /tmp/api2-log-fifo
  exec sudo -u www-data MASTERKEY=`cat /root/secrets/masterkey` /srv/current/bin/server 2>&1
end script
```

Inside your Node.js server, you might be calling azure-cli like so:

```javascript
const spawn = require('child_process').spawn
spawn('azure-cli', 'some' 'arg')
```

So you see, Bash (or any other interactive terminal program) does not come into play anywhere in this setup. Since `$HOME` is provided by the shell, HOME does not exist in your process.

But I think an easier way to test might be running your script through `env -i` (careful that env also strips `$PATH`, so you might want to provide the full path to node, or supply it specifically:

```bash
vagrant@vbox:/srv/current$ /srv/current/stack/bin/node -e 'console.log(process.env.HOME)'
/home/vagrant
vagrant@vbox:/srv/current$ env -i /srv/current/stack/bin/node -e 'console.log(process.env.HOME)'
undefined
```

**Comment by haocs** [comment]
@kvz , Thank you very much for providing repro steps.
However, I am not able to repro the issue on an Ubuntu box with upstart 1.12.1. Per my testings, $HOME and $USER are always present in node(child_process) process(neither of those variables is available in init process). Since user `www-data` is specified in init satanza, $HOME and $USER are set in node process. Pleae see the following scripts and results:
```bash
# init script
script
  set -e
  exec sudo -u www-data server_app >> /var/www/nserver.log 2>&1
end script
```
``` bash
# Node script
console.log('[USER]' + process.env.USER);
console.log('[HOME]' + process.env.HOME);
console.log('[PID]' + process.getuid());
const spawn = require('child_process').spawn;
var az = spawn('azure', ['telemetry', '-d']);
# =====output=====
#[USER]www-data
#[HOME]/var/www
#[PID]33
#stdout:info:    Executing command telemetry
#stdout:info:    You choose not to participate in Microsoft Azure CLI data collection.
#stdout:info:    telemetry command OK
```
I do think our current function(only base one $HOME var) will break some scenarios, but I am not sure if it is the root cause for your issue. Hence, I've created a [PR](https://github.com/Azure/azure-xplat-cli/pull/3018) that used `user-home` dependence. Could you give it a try and let me know if it fixes the issue?

**Comment by kvz** [comment]
Hi @haocs, that defies my understanding of how things work, since HOME is provided by bash, and bash is nowhere in this. Perhaps it only happens when you log out and the service respawns, so that your terminal is in no way connected to the next processes?

Whichever the case, I'm no in the position to dive much deeper into this issue, so I'm happy to assume there's a flaw somewhere in my understanding here.

**Comment by haocs** [comment]
@kvz , I think when`sudo -u` is called, it sets/resets $HOME, $USER and other env variables for the process according to the default sudoers policy. That's how we get $HOME present in node process.

It is kind tricky to figure out Upstart issues without taking a look at the configs. Anyway, thank you for pointing out the issue and we'll take `user-home` dependency to replace current HOME discover function per your suggestion. The fix should be available in our next release.

**Comment by haocs** [comment]
Fixed https://github.com/Azure/azure-xplat-cli/pull/3089
