### ISSUE TITLE
Formatting of feature deprecation text

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-xplat-cli#3003]
Is there a better way to format the text notifying users of deprecated features? Perhaps put it at the end of the output, so it doesn't interfere with the list of child commands?

![image](https://cloud.githubusercontent.com/assets/466713/16741964/f4cef46a-4762-11e6-800a-e26ddb89560f.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by eduardkoller** [comment]
Thank you for bringing this up. We'll look into making it prettier :-)

**Comment by pcgeek86** [comment]
@eduardkoller @amarzavery Why is this closed? I can open a new issue if need be.

**Comment by amarzavery** [comment]
I thought I had referenced this in the PR. Have updated the PR description to accurately represent it.
