### ISSUE TITLE
Attaching premium disk to non-premium storage ARM VM creates failed state (disk config updated despite failed message displayed)

### ISSUE THREAD

**Issue by danielstocker** [Azure/azure-xplat-cli#3008]
**My Microsoft alias:** "dasto"
**CLI Version:** 0.9.16
**OS Type:** Windows 10
**Installation via:**  win installer (web platform installer)

**Mode:** ARM

**Environment:** AzureCloud - PROD

**Description:**
Attaching premium disk to non-premium storage ARM VM creates failed state (disk config updated despite failed message displayed)

* Started by creating a standard Windows 2012 R2 Dv2 VM (Screenshot 1)
* Created a premium storage disk in a separate storage account (Screenshot 2)
* Used Azure CLI to attach the disk to the Dv2 VM 
** Operation fails (Screenshot 3)
* Viewing the disk config shows the disk as attached to the VM (Screenshot 4)
* VM is in a Failed state (Screenshot 5)

A customer showed me the issue and I am able to reproduce. 

Happy to provide more details. Please e-mail me or respond here. 

**azure.err content**

2016-07-12T16:17:10.524Z:
{ [Error: Long running operation failed with error: 'Storage account type Premium_LRS is not supported for VM size Standard_D2_v2.'.]
  stack: [Getter/Setter],
  request: 
   { rawResponse: false,
     queryString: {},
     method: 'GET',
     headers: { 'user-agent': 'WindowsAzureXplatCLI/0.9.16' },
     url: 'https://management.azure.com/subscriptions/c0d4110e-b0fd-45d7-b736-be96bfca9b74/providers/Microsoft.Compute/locations/northeurope/operations/cb6f9c6e-b1c8-42f3-b884-0ae040bdd15a?api-version=2015-06-15' },
  response: 
   { body: '{\r\n  "operationId": "cb6f9c6e-b1c8-42f3-b884-0ae040bdd15a",\r\n  "startTime": "2016-07-12T16:16:37.8618328+00:00",\r\n  "endTime": "2016-07-12T16:16:38.5337841+00:00",\r\n  "status": "Failed",\r\n  "error": {\r\n    "code": "VMSizeDoesntSupportPremiumStorage",\r\n    "message": "Storage account type Premium_LRS is not supported for VM size Standard_D2_v2."\r\n  }\r\n}',
     headers: 
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-length': '354',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'x-ms-served-by': '54c2f662-6cbb-4687-8a61-506f60a8e792_131100645709313263',
        'x-ms-request-id': 'aa876600-b2dc-4326-bad9-b473038ec168',
        server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
        'x-ms-ratelimit-remaining-subscription-reads': '14945',
        'x-ms-correlation-request-id': '49fd445f-40d7-4af2-9ef8-e39d54b52564',
        'x-ms-routing-request-id': 'NORTHEUROPE:20160712T161710Z:49fd445f-40d7-4af2-9ef8-e39d54b52564',
        date: 'Tue, 12 Jul 2016 16:17:09 GMT',
        connection: 'close' },
     statusCode: 200 },
  message: 'Long running operation failed with error: \'Storage account type Premium_LRS is not supported for VM size Standard_D2_v2.\'.',
  code: 'VMSizeDoesntSupportPremiumStorage',
  body: 
   { operationId: 'cb6f9c6e-b1c8-42f3-b884-0ae040bdd15a',
     startTime: '2016-07-12T16:16:37.8618328+00:00',
     endTime: '2016-07-12T16:16:38.5337841+00:00',
     status: 'Failed',
     error: 
      { code: 'VMSizeDoesntSupportPremiumStorage',
        message: 'Storage account type Premium_LRS is not supported for VM size Standard_D2_v2.' } },
  __frame: 
   { name: 'createOrUpdateVM__14',
     line: 180,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\vm\\virtualMachine.js',
     prev: 
      { name: 'attachNewDataDisk__20',
        line: 834,
        file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\vm\\vmClient.js',
        prev: [Object],
        calls: 3,
        active: false,
        offset: 35,
        col: 21 },
     calls: 0,
     active: false,
     offset: 18,
     col: 81 },
  rawStack: [Getter] }
Error: Long running operation failed with error: 'Storage account type Premium_LRS is not supported for VM size Standard_D2_v2.'.
  <<< async stack >>>
  at createOrUpdateVM__14 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\virtualMachine.js:198:82)
  at attachNewDataDisk__20 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\vmClient.js:869:22)
  at __22 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\vm\vm.js:480:18)
  <<< raw stack >>>
    at PollingState.getCloudError (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\lib\pollingState.js:119:15)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\lib\azureServiceClient.js:133:38
    at Object.async.whilst (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\node_modules\async\lib\async.js:621:13)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\node_modules\async\lib\async.js:617:23
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\lib\azureServiceClient.js:109:20
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\lib\azureServiceClient.js:231:5
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\lib\azureServiceClient.js:399:12
    at retryCallback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest-azure\node_modules\ms-rest\lib\filters\redirectFilter.js:36:9)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\utils.js:493:7

Screenshot 1
![screenshot1](https://cloud.githubusercontent.com/assets/9444698/16774702/2002ee8c-4855-11e6-8361-9c2dabfd219e.PNG)

Screenshot 2
![screenshot2](https://cloud.githubusercontent.com/assets/9444698/16774703/2003cb7c-4855-11e6-983d-50387aaab24c.PNG)

Screenshot 3
![screenshot3](https://cloud.githubusercontent.com/assets/9444698/16774705/209043a4-4855-11e6-90b4-43660086ef9e.PNG)

Screenshot 4
![screenshot4](https://cloud.githubusercontent.com/assets/9444698/16774707/20cde736-4855-11e6-919a-523b330f9d0f.PNG)

Screenshot 5
![screenshot5](https://cloud.githubusercontent.com/assets/9444698/16774706/20c00742-4855-11e6-8119-c592863df26e.PNG)

**Comment by huangpf** [comment]
I think this is by design. @sauryadas @singhkay Could you please help confirm?

**Comment by singhkay** [comment]
@danielstocker This is by design but the VM should not have allowed the disk to be attached instead of going into a failed state. The this is probably a bug in the compute platform that needs to be fixed.

**Comment by danielstocker** [comment]
@singhkay thank you very much for having a look at this from the CLI side. I will go through the proper internal escalation channels to get the compute team to have a look from their end.

**Comment by sgala** [comment]
Hi, I'm getting the same error "Storage account type 'Premium_LRS' is not supported for VM size Standard_D1_v2." When I try to create mostly every small VM in NorthEurope using the command:

```
az vm create --resource-group myGroup --name myGroupVM --image UbuntuLTS --size Standard_D1_v2 --admin-username myuser --public-ip-address-dns-name myName --generate-ssh-keys --ssh-key-value ~/.ssh/mykey.pub
```

This is blocking me and I can't find where to report it

**Comment by number213** [comment]
@sgala `az` means you're using Python CLI, that's another tool
https://github.com/Azure/azure-cli/

Regarding your case, premium storage can't be used with D-Series VMs. You would need to either use standard storage or use one of VM series with premium storage support (DS-series, DSv2-series, GS-series, Ls-series, and Fs-series).
https://docs.microsoft.com/en-us/azure/storage/storage-premium-storage

**Comment by sgala** [comment]
That would be good if I was requesting premium storage, but my call is just:

```bash
az vm create --resource-group ${RG}\
                      --name ${VM}\
                      --image UbuntuLTS\
                      --size Standard_D1_v2\
                      --admin-username ${VMUSER}\
                      --public-ip-address-dns-name ${SERVERNAME}\
                      --generate-ssh-keys\
                      --ssh-key-value ~/.ssh/<myPubKey>.pub
```
Where I can't really see where is this "premium storage" coming from. The parameters are quite straightforward. I guess they have an error in some template or not enough "plain" storage and a "clever" provisioning system.

Sorry for the spam. I'll keep trying to get it to work.

**Comment by number213** [comment]
Perhaps it is default value for `--storage-sku` in Python, this CLI defaults to `Premium_LRS` too.
https://docs.microsoft.com/en-us/cli/azure/vm#create

**Comment by sgala** [comment]
Thanks, it was this, to have a default value incompatible with half of the "--size" choices and a not clear error message was misleading me. :)

**Comment by shm007g** [comment]
this error happens to me when i what to resize my vm to Nv6. `Storage account type Premium_LRS is not supported for VM size Nv6.`

**Comment by ejarvi** [comment]
This broke my ARM (template).  Adding a line to explicitly override the default storage account type with Standard_LRS type fixed the issue in my case: 

`"managedDisk": { "storageAccountType": "Standard_LRS" }`

In context: 
```
        "storageProfile": {
          "imageReference": "[variables('imageReference')]",
          "osDisk": {
            "managedDisk": { "storageAccountType": "Standard_LRS" },
            "name": "[variables('OSDiskName')]",
            "caching": "ReadWrite",
            "createOption": "FromImage"
          }
        },
```
