### ISSUE TITLE
Property -Sku is not updateable for Set-AzurePlatformVMImage command

### ISSUE THREAD

**Issue by vani578** [Azure/azure-xplat-cli#3009]
Background:

In our Current RDFE based deployments we key off the “image family” field to identify the image to use when creating an Azure VM.  When we do an update to an image and publish we tack “preview” to the end of the image family field (eg “Pre-Requisites for Dynamics AX7 Developer Enterprise on Windows Server 2012 R2 RTWU1 Preview”).  This allows us to do some test deployments and validate the image before pushing to production.  When we are satisfied with our validation efforts we update the metadata of the image and remove the preview flag from the family name field (eg “Pre-Requisites for Dynamics AX7 Developer Enterprise on Windows Server 2012 R2 RTWU1”).  Once the “preview” flag is removed all production deployments start picking up the newly published image.

Problem:

We are moving to ARM based deployments and the “image family” field is no longer available to query.  Instead we thought we would use the “SKU” field to identify an image to use since this is available using ARM.  Just like the RDFE based deployments we need the ability to publish a new image without affecting production, do validation and quickly flip to production when we are satisfied with our validation.

Question:

We tried to publish a new image taking on “preview” to the end of SKU name (eg  “Pre-Req-AX7-Onebox-VSENT-RTWU1-Preview”) and this worked and we were able to do ARM based deployments using the SKU field to query for the correct image to work.  However removing “Preview” from the end of the SKU name (eg  “Pre-Req-AX7-Onebox-VSENT-RTWU1”)  does not seem to work.

Is it even possible to update the SKU field once an image has been published like we currently can with the image family field?  Attached is the script Anush created for publishing and updating images in the Azure gallery.

**Comment by MikhailTryakhov** [comment]
Hi @vani578 
could you please confirm, do you need a fix with PS command?
To find it better to use their repository issues list [here](https://github.com/Azure/azure-powershell/issues)

**Comment by vani578** [comment]
Hi Mikhail, yes I need this issue fixed. Why was this closed?
