### ISSUE TITLE
In version azure 0.10.1, the -a option to set a static IP address has been removed

### ISSUE THREAD

**Issue by hectoralicea** [Azure/azure-xplat-cli#3016]
CLI Version: 0.10.1,
OS Type: Mac
Installation via:  npm 
Mode: ARM
Environment: AzureCloud
Description:
command:

azure network nic set -g HLA_TEST_ResourceGroup -n hla-t-lnx-db1-dnic -a 10.0.2.230
  error: unknown option `-a'

Appears in the latest version of azure 0.10.1, the -a option to set to an IP address has been removed. 
I get ' error: unknown option `-a''
What's up with that. Is there a work around?

$ azure network nic set -help
help: Set a network interface
help: 
help: Usage: network nic set [options] <resource-group> <name>
help: 
help: Options:
help: -h, --help output usage information
help: -v, --verbose use verbose output
help: -vv more verbose with debug output
help: --json use json output
help: -g, --resource-group <resource-group> the name of the resource group
help: -n, --name <name> the name of the network interface
help: -w, --network-security-group-id [network-security-group-id] the network security group identifier.
help: e.g. /subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Network/networkSecurityGroups/<nsg-name>
help: -o, --network-security-group-name [network-security-group-name] the network security group name.
help: This network security group must exist in the same resource group as the nic.
help: Please use network-security-group-id if that is not the case.
help: -r, --internal-dns-name-label [internal-dns-name-label] the internal DNS name label
help: -f, --enable-ip-forwarding <enable-ip-forwarding> enable ip forwarding [true, false]
help: -t, --tags [tags] the list of tags.
help: Can be multiple. In the format of "name=value".
help: Name is required and value is optional.
help: Existing tag values will be replaced by the values specified.
help: For example, -t "tag1=value1;tag2"
help: -s, --subscription <subscription> the subscription identifier
help: 
help: Current Mode: arm (Azure Resource Management)

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you please take a look at this issue?

**Comment by amarzavery** [comment]
@hectoralicea - Does `azure network nic ip-config create -h` help ?

**Comment by hectoralicea** [comment]
wow yes, I think that will do it.  Let me give it a try and change my script to accommodate this change in this new version of CLI.

**Comment by hectoralicea** [comment]
Yes, that worked.  Thanks. Had to re-write that line of the script.

**Comment by amarzavery** [comment]
Awesome. Nice to know!
