### ISSUE TITLE
Snapshot restore doesn't appear to work

### ISSUE THREAD

**Issue by samirageb** [Azure/azure-xplat-cli#3034]
CLI Version: **0.10.2**
OS Type: Win 8.1
Installation via:  win installer
Mode: **ARM**
Environment: AzureCloud

Description:
The CLI command I am using is:
`azure storage blob copy start --source-uri "path-to-vhd" --snapshot "<timestamp>" --dest-container "<container name>" --dest-connection-string "<connectionstring>" --dest-blob "<new vhd name>"`

Steps to reproduce:
1) Run command above
2) Verify destination VHD has been created
3) Create new VM with new VHD and login
4) It appears to be a clone of the base, not snapshot

For the sake of clarity, here are formatting variations of the snapshot timestamp parameter I'm tried with no success:
2016-07-23T22:49:12.9377157Z
"2016-07-23T22:49:12.9377157Z"
2016-07-23T22%3A49%3A12.9377157Z

Also, I can put ANY value (even non-date strings) in for the snapshot parameter and command completes with error: null, isSuccessful: true  There are no azure.err files generated.

The result is the destination VHD is created, but it's a clone of the base VHD.

Please advise?

**Comment by amarzavery** [comment]
@hasonmsft @yaxia - Can you please take a look at this issue?

**Comment by hasonmsft** [comment]
@samirageb, as you are using the `--source-uri` option to start the async copy, the `--snapshot` option won't take effect. You can

1. Use `azure storage blob copy start --source-container <sourceContainer> --source-blob <sourceBlob> --snapshot <sourceSnapshot> --dest-container <destContainer> --dest-blob <destBlob> --dest-connection-string <destConnectionString>`

2. Add `?snapshot=<encoded snapshot>` to the `--source-uri` option.

**Comment by samirageb** [comment]
Thank you very much for the clarification @hasonmsft and assistance @amarzavery . I've confirmed this works as explained. If there is any way to improve the clarity around the CLI flags and CLI runtime assistance while it would help tremendously as there exists non-intuitive naming conventions (snapshot id vs snapshot timestamp) as well as flag dependencies that make the CLI extremely frustrating and time consuming to use. (The CLI snapshot async behavior for example appears undocumented and cost me at least 8 hrs of trial/error, research, etc.)

For anyone else reading this post, a 'snapshot id' **is** the snapshot timestamp. 
**Example:** 2016-07-23T22:49:12.9377157Z

Thank you again for the prompt assistance. I will consider this issue closed.

**Comment by amarzavery** [comment]
@samirageb - Thanks a ton for your feedback. We will work upon this to make sure that the help is adequate and the naming conventions are consistent.
@hasonmsft @yaxia - Can you send a PR to update the help and incorporate the feedback provided by samirageb?

**Comment by hasonmsft** [comment]
@samirageb , the help is updated and thanks for you great suggestion.

**Comment by samirageb** [comment]
I believe this can probably be closed at this time, confirm?

**Comment by yaxia** [comment]
Associated it with the PR #3115 and confirmed it can be closed. Thanks.
