### ISSUE TITLE
Config mode should be ARM by default

### ISSUE THREAD

**Issue by jadbox** [Azure/azure-xplat-cli#3041]
CLI Version: 0.10.2
OS Type: Ubuntu: Linux 4.6.4
npm: 3.10.3
node: v6.3.1
Installation via:

npm install -g azure-cli@0.10.2, npm install -g azure-cli, 
and release package npm i -g azure-cli.0.10.2.linux.tar.gz

Description:
As a new user, I spent some time trying to get the cli to work with my new Azure cluster (even filed an issue for it #3039). After some frustration, I found that the cli was in "service management" mode and needed to be explicitly set to ARM:
`azure config mode arm`

I'd recommend that the default mode should be ARM as its the recommended way to use Azure these days.

**Comment by amarzavery** [comment]
This issue has been fixed in https://github.com/Azure/azure-xplat-cli/pull/3019 and will be available as a part of the August release.
