### ISSUE TITLE
azure log tail - output only when accessing file via kudu shell

### ISSUE THREAD

**Issue by oak-tree** [Azure/azure-xplat-cli#3042]
CLI Version: **0.10.2**
OS Type: Win 
Installation via:  npm 

Mode: **ASM**

Environment: AzureCloud

Description:
`azure site log tail` output new log information to  `stdout` **only** when I reenter the `log` file via `kudu` editor

Details descriptions:
We have `tomcat` running on `webapp`. Our app is built with `spring`.  We use `log4js` to output the `logs`.  We output the log into `D:\home\LogFiles\'

This works good and we have 3 files at `LogFiles` Directory. We have `debug.log`, `error.log` and `info.log`. 

We are checking possible move from `Rackspace` to `Azure`. At `Rackspace` we are linux box. So output the `logfile`  its easy. We just to `tail` on one of the `log` file or on `catalina.out`. 

We are looking for a solution to do the same in `azure` as watching the `logfiles` in **real-time** is very critical to the `development process`.

It seems that `azure cli` should provide this kind of functionality.  But it refresh the `output` only when I access to the `log file`  (e.g the `debug.log`) throw `kudu system`. It seems like accessing the file `trigger` an event change or something like that. But without reentering the file there is no output to the `console`. 

Summary:  Any idea how to get `real-time` logging information?

Thanks
Alon

#Edit
I have test in in several different times and its only  output the `log` into the command line when I reenter the file via `kudu` file editor

**Comment by amarzavery** [comment]
@davidebbo @ahmedelnably -Can you help resolve this issue for the customer?

**Comment by davidebbo** [comment]
That's not normally the case, as log streaming works for many runtime generated log files that are not created fro Kudu.

To isolate from anything related to the xplat CLI, can you try accessing the stream directly via curl, per https://github.com/projectkudu/kudu/wiki/Diagnostic-Log-Stream? If issue happens there as well, we can close it here and instead open a Kudu issue.

**Comment by oak-tree** [comment]
I didnt figure out what to put as `username` because I use `private key` in order to do `git deploy`. So I enter the `logstream` url in the browser (`chrome`). Similar results: In our `development` version we write the log file on every action on `client side`. The browser does not get these updates. The only time it gets the update is when I access the `logfile` at `Kudu editor. The `stream` is being updated just after the fetching in the `Kudu editor is done`. i.e : after the `  Cancel Fetching contents...` replace with `file name`

**Comment by davidebbo** [comment]
Chrome has its own issues due to client caching (mentioned [here](https://github.com/projectkudu/kudu/wiki/Diagnostic-Log-Stream#connecting-the-logstream-using-a-web-browser)).

For curl, you can use either the site or user credential (see [this page](https://github.com/projectkudu/kudu/wiki/Deployment-credentials)).

**Comment by oak-tree** [comment]
Ok. I connected to a `linux server` on `azure` and did `curl`. The same result. For some reason it does not show the output of `tomcat logfiles` in `realtime`. It waits for something. If I open the `kudu` editor it triggers the output of the `curl`

**Comment by davidebbo** [comment]
Let's move this to a Kudu issue as we've now established that it's unrelated to xplat cli.

https://github.com/projectkudu/kudu/issues

**Comment by haocs** [comment]
Closed this issue since it is not related to cli.
