### ISSUE TITLE
azure network nic ip-config set: allow deallocating public ip

### ISSUE THREAD

**Issue by 2k0ri** [Azure/azure-xplat-cli#3052]
CLI Version: 0.10.2
OS Type: Mac
Installation via:  brew

Mode: ARM

Environment: AzureCloud

Description:
`azure network nic ip-config set` operation cannot remove public ip in the NIC.
An operation without `--public-ip-name` and `--public-ip-id` flag leads inherited configuration, and these flags cannot be provided `null`.

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you take a look at this?

**Comment by MikhailTryakhov** [comment]
Duplicates issue [3086](https://github.com/Azure/azure-xplat-cli/issues/3086)
