### ISSUE TITLE
git clone fails due to filenames too long (on Windows 10)

### ISSUE THREAD

**Issue by PeteH32** [Azure/azure-xplat-cli#3055]
CLI Version: **0.9.X**
OS Type: Mac / Win / Linux (Ubuntu, RedHat, etc.)
Installation via:  N/A (this is git clone issue with github repo)

Mode: N/A (this is git clone issue with github repo)

Environment: Windows 10

Description:
Cloning this repo fails due to filename too long (on Windows 10). Problem is that the "test" folder has filenames that are very long, which will fail on Windows due to limit on total path length cannot be more than MAX_PATH (260 characters) long. Some files in this github repo have huge names, with their path being 227 characters long which only leaves 33 characters for whatever folder you are cloning the repo into.

Here is example where it's sub-path is already 227 characters long:
 - azure-xplat-cli/test/recordings/arm-cli-HDInsight-cluster-create-tests/arm_hdinsight_cluster_script_action_should_not_succeed_on_hdinsight_linux_cluster_with_appName_when_roles_list_contains_nodetype_other_than_edgenode.nock.js

Steps to reproduce:
1) On Windows 10, open Windows Command Prompt
2) Change directory (cd) to a folder whose full path has at least 35 characters in it's full path. For example:
 - C:\petestuff\WorkAreas\Azure\github\Azure
3) Now try to do a "git clone" of this repo. 
 - git clone https://github.com/Azure/azure-xplat-cli
It will fail, with error "Filename too long".

Error stack trace:

C:\petestuff\WorkAreas\Azure\github\Azure>git clone https://github.com/Azure/azure-xplat-cli
Cloning into 'azure-xplat-cli'...
remote: Counting objects: 72578, done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 72578 (delta 48), reused 9 (delta 9), pack-reused 72496R
Receiving objects: 100% (72578/72578), 78.09 MiB | 159.00 KiB/s, done.
Resolving deltas: 100% (54490/54490), done.
Checking connectivity... done.

error: unable to create file test/recordings/arm-cli-HDInsight-cluster-create-tests/arm_hdinsight_cluster_script_action_should_not_succeed_on_hdinsight_linux_cluster_with_appName_when_roles_list_contains_nodetype_other_than_edgenode.nock.js (Filename too long)

Checking out files: 100% (2657/2657), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by amarzavery** [comment]
It is an environment issue. Please try to clone the repo at the top level in the directory.

**Comment by luisa123456** [comment]
Resolve the Path Too Long error with the help of ‘Long Path Tool’.
