### ISSUE TITLE
Kudu Deployment Script for ASP.NET Core 1.0

### ISSUE THREAD

**Issue by mikeesouth** [Azure/azure-xplat-cli#3057]
CLI Version: **0.10.2**
OS Type: **Win**
Installation via:  **npm**

Description:
Hello,

I've been using azure-cli to generate deployment scripts for my ASP.NET Core application. I'm using Visual Studio Code and Webpack so I can't use the built in tools for publishing from Visual Studio. I guess I need a custom deployment script and it have been working flawlessly with ASP.NET 5 RC1. I used the following command to generate the deployment script:
```shell
azure site deploymentscript --aspNet5 .\server\project.json -p .\server --aspNet5Version "1.0.0-rc1-update1" --aspNet5Runtime clr --aspNet5Architecture x86
```

With the release of ASP.NET Core it is now renamed to ASP.NET Core 1.0 instead of ASP.NET 5. The tools have been renamed from `dnx` to `dotnet`. The latest version of azure-cli still generates variables such as `set DNX_RUNTIME="%USERPROFILE%\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1"`.

Three questions:
1) How can I update these scripts to work with ASP.NET Core 1.0?
2) What is the correct runtime for ASP.NET Core 1.0? `set DNX_RUNTIME="%USERPROFILE%\.dnx\runtimes\dnx-clr-win-x86.1.0.0"`?
3) Can someome point me to a working example of a deployment script for ASP.NET Core 1.0?

**Comment by amarzavery** [comment]
@davidebbo - Can you please take a look at this issue?

**Comment by davidebbo** [comment]
Dup of http://stackoverflow.com/questions/38698263/kudu-deployment-script-for-asp-net-core-1-0/38700484.

**Comment by davidebbo** [comment]
And the xplat cli change is in: c3cc0ecf10ef1d0c9bab0be66224ba2fc925021e. It just needs to propagate to a public release.

**Comment by mikeesouth** [comment]
@davidebbo thanks for answering and sorry for duping, I wasn't sure where to ask. I still don't really get it to work. With or without deployment script. I suggest that we have the troubleshooting discussion here and then I can accept your answer at StackOverflow, I hope that sounds ok to you.

When I try to publish my custom application I get this error when browsing to the site: `You do not have permission to view this directory or page.`. If I navigate to mysite.azurewebsites.net/index.html then I get this error: `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`. I get the same results when trying with or without custom kudu deployment scripts.

I published a simple ASP.NET Core 1.0 application from Visual Studio (that is using the standard MVC template). It works and I've used it to compare to my custom published applications. There are some differences in the uploaded files.

My site has .nuget and .ssh in the root folder, parallell to the data, LogFiles and site folder. I guess this is OK. My site also has a repository folder in the site folder and I assume that it is related to the continous deployment flow that I have setup between VSTS and Azure App Services.

The interesting differences are in the site/wwwroot/ folder.

The ASP.NET Core 1.0 Demo app (from Visual Studio) have three folders and these **relevant** files:
```
/site/refs/
/site/Views/
/site/wwwroot/
/site/appsettings.json
/site/ASPNETCore1.exe
...
/site/libuv.dll
/site/Microsoft.AspNetCore.Antiforgery.dll
...
/site/System.Xml.XPath.XDocument.dll
/site/web.config
```

The /site/wwwroot/ folder is empty but in my project structure I have some sample css, images etc. Also, the generated site references resources such as `/images/banner1.svg` and serves them correctly.

My custom site has alot of locale folders in the wwwroot folder, e.g.:
```
/site/wwwroot/de/
/site/wwwroot/es/
/site/wwwroot/fr/
```

I also have key files such as an .exe file (server.exe), appsettings.json, web.config, libuv.dll, Microsoft DLLs etc. The wwwroot folder is not empty like in the MVC demo app, but instead it has my correct wwwroot contents with files such as: index.html, site.css, img/my_image.jpg etc.

I have the same Program.cs contents, I have `app.UseFileServer()` instead of `app.UseStaticFiles()` in Startup.cs. My project.json looks like this:
```
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
    "Microsoft.AspNetCore.Cors": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "SendGrid": "7.0.6",
    "WindowsAzure.Storage": "7.1.2",
    "System.ComponentModel": "4.0.1"
  },
  "tools": {
    "Microsoft.DotNet.Watcher.Tools": {
      "version": "1.0.0-*",
      "imports": "portable-net451+win8"
    },
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },
  "frameworks": {
    "net461": {}
  },
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "appsettings.json",
      "web.config"
    ]
  },
  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

My project structure that I push to VSTS (using GIT) is a bit custom, it looks like this:
```
/package.json
/webpack.config
/src/(javascript files that are packed with webpack to /server/wwwroot/ folder)
/src/css/(css files that are packed with webpack to /server/wwwroot/ folder)
/server/Controllers/*
/server/wwwroot/index.html
/server/wwwroot/site.css
/server/Program.cs
/server/project.json
/server/Startup.cs
```

**Comment by davidebbo** [comment]
@mikeesouth Best repo for this is https://github.com/projectkudu/kudu, as this is not really related to the xplat CLI. Can you share a repro git repo, per [this page](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)? Thanks!

**Comment by mikeesouth** [comment]
@davidebbo Aha! Thanks for pointing me to that repo, I hadn't found it/thought of it earlier.
Using the documentation I found that this custom `.deployment` file did the trick:
```
[config]
project = server
```

**Comment by davidebbo** [comment]
Awesome!
