### ISSUE TITLE
Autologin for automation and schedule task

### ISSUE THREAD

**Issue by pablolibo** [Azure/azure-xplat-cli#3079]
Hi guys, the question is simple, What is the best way of optimize autologin  for task with azure-cli.

I am using ARM (Not ASM) and "azure -u user -p password -q", but, is it the best way for autologin? 

Thanks!

**Comment by amarzavery** [comment]
@pablolibo - If the user account is an org id and has 2FA disabled then the above command is a good option for automation scenario. If not then you should create a service principal and use it for login. That is the recommended way for automation and scripting scenarios. You can create an sp(service principal) and login as an sp in 3 simple steps. Please take a look at this section in [README](https://github.com/Azure/azure-xplat-cli#non-interactive-authentication) that takes you to a doc that talks more about it.

**Comment by eduardkoller** [comment]
@pablolibo: Does this answer your question?

**Comment by pablolibo** [comment]
Thanks Guys! I will check that!
