### ISSUE TITLE
No ServiceBus command  in the CLI

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-xplat-cli#3083]
CLI Version: 0.10.2
OS Type: Ubuntu
Installation via:  npm 

Mode: ARM

Description:
`-> azure sb `
`-> error:   'sb' is not an azure command. See 'azure help'`

I'm attempting to follow https://buildazure.com/2015/09/24/create-azure-service-bus-namespaces-using-powershell-and-x-plat-cli/ but I don't see the option to work with service bus from the CLI?

**Comment by amarzavery** [comment]
servicebus commands are available in ASM mode. The CLI runs in two modes asm & arm. Please change the mode `azure config mode asm` and then `azure sb -h`

**Comment by amarzavery** [comment]
@bearrito - Hope the above response resolves your issue. I am closing this one for now. If you feel this is not the case then please feel free to re-open the issue
