### ISSUE TITLE
Auto-complete for bash instructions do not work (Ubuntu on Windows)

### ISSUE THREAD

**Issue by darshanrampatel** [Azure/azure-xplat-cli#3084]
CLI Version: **0.9.X**
OS Type: Linux (Ubuntu) (but on Windows 10)
Installation via:  npm

Mode: N/A

Environment: N/A

Description:
[Provided auto-complete instructions](https://github.com/Azure/azure-xplat-cli/blame/dev/README.md#L92) do not work for Bash on Ubuntu on Windows 10.
```
azure --completion >> ~/azure.completion.sh
echo 'source ~/azure.completion.sh' >> ~/.bash_profile
```
Running the above commands does not enable auto-complete. I had to instead run:
```
azure --completion >> ~/azure.completion.sh
echo 'source ~/azure.completion.sh' >> ~/.bashrc
```

Steps to reproduce:
1) Run `azure --completion >> ~/azure.completion.sh`
2) Then run `echo 'source ~/azure.completion.sh' >> ~/.bash_profile`
2) Reload bash - try typing `azure <TAB><TAB>`; nothing will happen.
4) Run `echo 'source ~/azure.completion.sh' >> ~/.bashrc`
5) Reload bash -  try typing `azure <TAB><TAB>` ; auto-complete will work.

Error stack trace: N/A

**Comment by haocs** [comment]
Yes, .bash_profile was not sourced in this case(non-login shell). Please use .bashrc instead. Thank you for reporting this and we will update the documentations for autocomplete setup.

**Comment by haocs** [comment]
Fixed https://github.com/Azure/azure-xplat-cli/pull/3091
