### ISSUE TITLE
How to remove a public ip address from a NIC ipconfig?

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-xplat-cli#3086]
```
$ azure network nic ip-config set -i "" -g "colemick-asdf" -c "debian01" 
  error: option `-i, --public-ip-id <public-ip-id>' argument missing

$ azure network nic ip-config set -p "" -g "colemick-asdf" -c "debian01"
  error: option `-p, --public-ip-name <public-ip-name>' argument missing
```

How do I remove the public ip from this nic's ipconfig?

**Comment by colemickens** [comment]
@sauryadas Any idea on this one?

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you take a look at this?

**Comment by MikhailTryakhov** [comment]
Hi @colemickens 
unfortunately the concept of Azure CLI doesn't get us a chance to remove property in a such way. The only way is recreate it (multiple NICs would be available soon).
But I completely agree that current functionality is unusable in such case.
@DeepakRajendranMsft, I assume such case should be added to task list and implemented. 
Please approve

**Comment by MikhailTryakhov** [comment]
Hi @colemickens 
unfortunately the concept of Azure CLI doesn't get us to remove any property in a such way. 
At this stage you can't remove public-ip from NIC ip config at all, but you can update it to another value using ```public-ip-name``` or ```public-ip-id``` parameters.
Also multiple NIC ip config would be available soon - that would get a chance to create new ip config using ```nic ip-config create -n ipConfig2 ...``` to create the 2nd config with specified params and ```nic ip-config delete -n default-ip-config ...``` to remove an old one.

**Comment by MikhailTryakhov** [comment]
Decided to implement such functionality. Reopen issue

**Comment by MikhailTryakhov** [comment]
Made fixes - they would be published in October release
