### ISSUE TITLE
`azure vm quick-create` needs option for DNS label

### ISSUE THREAD

**Issue by mw007** [Azure/azure-xplat-cli#3118]
- CLI Version: 0.10.3
- OS Type: Linux (RedHat)
- Installation via:  npm
- Mode: ARM
- Environment: AzureCloud

Description:
I'd like to see the `azure vm quick-create` command have an option for the DNS label, similar to the `-w, --public-ip-domain-name` option for the `azure vm create` command.

This would make automation much easier, and prevent me from having to use the `azure vm network public-ip set --domain-name-label` command after using quick-create.

**Comment by amarzavery** [comment]
@huangpf - Can you please take a look at this?
