### ISSUE TITLE
[docs] azure vm extension set --autoUpgradeMinorVersion: Misdocumented

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-xplat-cli#3119]
The #2943 are added the `--autoUpgradeMinorVersion` flag which is misdocumented.

I raised this and  I was ignored:

![image](https://cloud.githubusercontent.com/assets/159209/17982085/4320d5f4-6abb-11e6-80e7-c434d8e1578b.png)

@huangpf @amarzavery don't ignore people, it's a bad habit.

See https://github.com/Azure/azure-cli/issues/753 for an explanation

**Comment by huangpf** [comment]
@ahmetalpbalkan Will apply your suggestion ASAP: ```Pick the highest minor version of the extension```.

We highly appreciate your feedback, as always. Thanks.
