### ISSUE TITLE
Object #<Object> has no method 'isAbsolute'

### ISSUE THREAD

**Issue by glennmate** [Azure/azure-xplat-cli#3130]
CLI Version: **0.10.3**
OS Type: **Ubuntu 14.04 LTS**
Installation via:  **npm version 2.15.1**

Mode: **ASM**

Environment: **AzureCloud**

Description:
This is a brand-new Ubuntu VM 14.04 LTS image from Azure. Installed NPM, then installed Azure-Cli through NPM. Ran the following command, got the below error. No other installed software on the machine. 

Steps to reproduce:
```azure storage blob download -a "mystorageaccountname" -k "secretkey==" --container "mycontainername" -b "myfilename.pem" -d "/home/teamcity/.chef" -q```

Error stack trace:
**Please paste the content of ~/.azure/azure.err or C:\Users\username\\.azure\azure.err over here**
```
2016-08-31T23:12:24.044Z:
{ [TypeError: Object #<Object> has no method 'isAbsolute']
  stack: [Getter/Setter],
  __frame:
   { name: 'downloadAzureBlob',
     line: 1277,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js',
     prev: undefined,
     calls: 0,
     active: true,
     offset: 28,
     col: 15 },
  rawStack: [Getter] }
TypeError: Object #<Object> has no method 'isAbsolute'
  <<< async stack >>>
    at downloadAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:1323:35)
  at downloadAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:1305:16)
  <<< raw stack >>>
    at __$downloadAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:1323:35)
    at __$downloadAzureBlob (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:1306:110)
    at ___ (/usr/lib/node_modules/azure-cli/lib/commands/storage/storage.blob.js:1306:126)
    at ___ (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at /usr/lib/node_modules/azure-cli/lib/util/utils.js:1064:5
    at Object.cb [as oncomplete] (fs.js:169:19)
```

I should note that I was previously using AzureCLI version 9.1.3 and had no issues on Ubuntu 14.04. I've tried running this command in various iterations and it fails across the board. Works great on Windows

Seems to be throwing the error [here](https://github.com/Azure/azure-xplat-cli/blob/e1436a60360555d9d397bd63a52f46eff2e31032/lib/commands/storage/storage.blob._js#L1393)

Doesn't throw an error with the -d parameter if I include not only the path of the directory, but also the file extension as shown below:
```azure storage blob download -a "mystorageaccountname" -k "secretkey==" --container "mycontainername" -b "myfilename.pem" -d "/home/teamcity/.chef/myfilename.pem" -q```
Works either way on Windows operating systems, so I assume it should work both ways on *nix.

**Comment by amarzavery** [comment]
@hasonmsft @yaxia - Can one of you take a look at this issue?

**Comment by hasonmsft** [comment]
@glennmate , what's the node version you are using? Try to upgrade the node version to stable version?

**Comment by glennmate** [comment]
@hasonmsft ```user@server:~$ node --version
v0.10.46```, which has a release date of 2016-06-23 according to the [changelog ](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V010.md#0.10.46)/ [release history
](https://nodejs.org/en/download/releases/).

Is there an alternative version you recommend in particular?

**Comment by amarzavery** [comment]
@glennmate - That is a very old version of node.js. Please use the latest stable in the 4.x.x series.

**Comment by glennmate** [comment]
@amarzavery I ended up refactoring my chef cookbooks to accommodate for the issue, so I don't need a fix. I'm going to also update my node version (I was installing a default version through an old community cookbook which is no longer maintained) and choose a more actively developed community cookbook. I won't be pursuing testing to validate that this is the cause of the issue but I think it's a sane assumption. 

I'll leave the issue open if you choose to investigate further but I believe this can be closed. Thank you.
