### ISSUE TITLE
Cannot convert IP from Dynamic to Static for application-gateway frontend-ip

### ISSUE THREAD

**Issue by hectoralicea** [Azure/azure-xplat-cli#3148]
CLI Version: 0.10.1
OS Type: Mac
Installation via:  npm
Mode: ARM
Environment: AzureCloud
Description:  There's no way to convert IP from Dynamic to Static for application-gateway frontend-ip.  When I create VMs, Load Balancers or Application Gateways, I start with Dynamic IPs, so that an available IP can be assigned to the resource being provisioned.  After the provision is complete I then run a quick azure network nic | lb | application-gateway --json command that pulls the IP address then I run another "set" command to convert it from a dynamic to a static.

The issue with the command `azure network application-gateway frontend-ip` is that I can only `create` or `delete` a  `frontend-ip`.  I cannot `set` / change a setting on an existing frontend-ip such as setting the IP and making it Static.

See help output
```
azure network application-gateway frontend-ip --help
help:    Commands to manage application gateway frontend pis
help:    
help:    Add a frontend ip configuration to an application gateway
help:      network application-gateway frontend-ip create [options] <resource-group> <gateway-name> <name>
help:    
help:    Delete a frontend ip configuration from an application gateway
help:      network application-gateway frontend-ip delete [options] <resource-group> <gateway-name> <name>
help:    
help:    Options:
help:      -h, --help  output usage information
help:    
help:    Current Mode: arm (Azure Resource Management)
```

**Comment by amarzavery** [comment]
@MikhailTryakhov @deepakrajendranmsft - Can you take a look at this issue?

**Comment by MikhailTryakhov** [comment]
Currently it's implemented and published in 0.10.5 release

**Comment by hectoralicea** [comment]
I'm trying this out now.  Thanks for implementing this.  With regards to the --help instructions, I see this option:
 -a, --static-ip-address <static-ip-address>  the static IP address name
I suspect that's the option I need to set the ip address and make it static.  But what confuses me is the word `name` at the end of the help description.  Is this really a name or should it just the IP address in the x.x.x.x format?

**Comment by MikhailTryakhov** [comment]
@hectoralicea You're right, thank you!
Currently it's fixed and would be published in upcoming release.
Thank you for your great work!

**Comment by jmblock** [comment]
This issue has re-appeared in CLI 2.0 .. if you use an already defined IP address and it is static, you get an arm error stating that it must be dynamic.

**Comment by MikhailTryakhov** [comment]
@jmblock that is a repo of CLI 1.0
Please use [CLI 2.0 repo](https://github.com/Azure/azure-cli) to report this issue there.
Thanks!
