### ISSUE TITLE
azure login feature request - automatic browser

### ISSUE THREAD

**Issue by djberg96** [Azure/azure-xplat-cli#3156]
When I run the "azure login" command, it gives me a URL and a code to enter. Why not add a "-b" option that automatically opens up a browser (either your system default or one that you specify) to https://aka.ms/devicelogin and enters the code in the text box? I can then take it from there.

**Comment by amarzavery** [comment]
It is difficult to do that when someone is ssh'ing or puttying into a machine. It is better to keep things simple.

**Comment by djberg96** [comment]
@amarzavery Well, that's why I suggested the "-b" option. You would have to ask for it. I wouldn't make it a default.

**Comment by haocs** [comment]
Also auto-filling could be tricky cross browsers.

**Comment by amarzavery** [comment]
closing this one as it does not fit into the priority list of current items.
