### ISSUE TITLE
azure vm list does not show all VMs

### ISSUE THREAD

**Issue by carnott-redhat** [Azure/azure-xplat-cli#3176]
CLI Version: `0.10.4`
OS Type: Arch Linux
Installation via:  npm ([pacman](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nodejs-azure-cli))
Mode: ARM
Environment: AzureCloud
Description:
`azure vm list` command does not show any VMs in one of my resource groups; appears to be a pagination issue.

Steps to reproduce:
1) Run `azure group deployment create ...`
2) Then run `azure vm list`

Error stack trace:
Source of the problem - you have more VMs that fits in a single response, so it is paged, indication of this is presence of "nextLink" in the response body:

```
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:       },
silly:       body: '{
... "nextLink":"https://management.azure.com/subscriptions/<truncated>"}'
```

note] can provide redacted logs upon request

**Comment by carnott-redhat** [comment]
looping in @BorisB2015 and @djberg96

**Comment by amarzavery** [comment]
Ahh that seems like a bug.
As per the [spec] (https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-03-30/swagger/compute.json#L1148) it is a pageable operation.

so the logic on this [line in CLI source code](https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/vm/virtualMachine._js#L73) seems to be skewed.

@carnott-redhat - Did you provide the `resource group name` while executing the `vm list` command?

@huangpf @sauryadas - This is indeed a bug. Please try to get this fixed ASAP by today, as the next release would be in November.

**Comment by BorisB2015** [comment]
@amarzavery - I have looked at the logs from @carnott-redhat privately. The issue is that when there are many VMs (over 100 in his case), so if there is no resource group is used, the paging is not handled by Azure CLI. If there is resource group provided a different endpoint is called and hence the VM are shown correctly.

**Comment by huangpf** [comment]
@BorisB2015 
Based on the current investigation, I think this is a service API issue in that it doesn't return the ```nextLink``` filed from ```listAll```, but it does so from ```list(rgName)```.

The investigation for our conclusion:
1) CLI handle the return results in the same way:
```
      if (resourceGroupName) {
        vms = this.serviceClients.computeManagementClient.virtualMachines.list(resourceGroupName, _);
      }
      else {
        vms = this.serviceClients.computeManagementClient.virtualMachines.listAll(_);
      }
      var nextPageLink = vms.nextLink;
      while (nextPageLink) {
...
```
2) The response construction code are the same for ```list``` & ```listAll```:
* https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/computeManagement2/lib/operations/virtualMachines.js

Because the ways how the client handles 2 APIs are the same, the only reason for ```listAll``` not returning all VM results is that the service API doesn't include it.

To confirm, please try to collect the logs from ```azure vm list -vv```. Thanks.

**Comment by huangpf** [comment]
@carnott-redhat 
It seems you did see a ```nextLink``` from the ```listAll``` payload? Could you please include more detailed logs, like operation IDs, etc. Thanks.

**Comment by djberg96** [comment]
@huangpf Yes, we do see a nextLink in the response. I'll let Colin provide the info.

**Comment by BorisB2015** [comment]
@huangpf , I have forwarded logs privately to @amarzavery and  @sauryadas.

**Comment by BorisB2015** [comment]
@huangpf, Looking at this code:
```
     if (resourceGroupName) {
        vms = this.serviceClients.computeManagementClient.virtualMachines.list(resourceGroupName, _);
      }
      else {
        vms = this.serviceClients.computeManagementClient.virtualMachines.listAll(_);
      }
      var nextPageLink = vms.nextLink;
```
could you please check how nextLink is obtained from the response? The very first comment by @carnott-redhat shows that it comes as part of the body. If this is not where it should be, please point me to the correct section of the swagger spec so that we can take this to ARM/CRP team if the response is incorrectly formed.

I suppose when RG is specified result set is much smaller. I rarely have seen RGs with more than 50 VMs in them. So this code is never exercised for "list with RG". Please check in the logs I have sent privately that nextLink comes where you expect it to be. 

Thanks!

**Comment by huangpf** [comment]
@BorisB2015 @carnott-redhat 
From the logs, it doesn't seem to be the latest CLI as you indicated in the first post
```
user-agent: 'WindowsAzureXplatCLI/0.10.1'
```

Please update it and try again. Close for now, and please re-open if repro.

**Comment by djberg96** [comment]
@huangpf I saw the same behavior with 0.10.4.

**Comment by BorisB2015** [comment]
I'll get back to testing this during next week and will reopen if repros on 0.10.4. @djberg96 - feel free to reopen now if you see it as you indicate. Thanks!

**Comment by huangpf** [comment]
@djberg96 
Maybe there are some cached ```azure-arm-compute``` packages on your machine. If so, please make sure it's the latest, by cleanup and re-installation. I clone and use the latest ```dev``` branch code (0.10.4), and it's working for me. Here is the partial log that shows CLI gets a ```skiptoken``` URL, and then continue to query it:
```
c:\>azure vm list -vv
info:    Executing command vm list
verbose: Getting virtual machines
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: {
silly:           Content-Type: 'application/json; charset=utf-8',
silly:           accept-language: 'en-US',
silly:           x-ms-client-request-id: '00000000-0000-0000-0000-000000000000',
silly:           user-agent: 'WindowsAzureXplatCLI/0.10.4'
silly:       },
silly:       url: 'https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute/virtualMachines?ap
i-version=2016-03-30',
silly:       body: null
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-original-request-ids: '5c7b1b49-c390-4f28-a9bb-27ca9565cb20, 607b15ab-b0c9-4f66-8e9f-5416e90a3950',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14997',
silly:           x-ms-request-id: 'c0768ce6-98e4-43da-a40b-97828863d938',
silly:           x-ms-correlation-request-id: 'c0768ce6-98e4-43da-a40b-97828863d938',
silly:           x-ms-routing-request-id: 'WESTUS2:20160925T033901Z:c0768ce6-98e4-43da-a40b-97828863d938',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           date: 'Sun, 25 Sep 2016 03:39:00 GMT',
silly:           connection: 'close',
silly:           content-length: '66427'
silly:       },
silly:       body: '{"value":[...],"nextLink":"https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000
/providers/Microsoft.Compute/virtualMachines?api-version=2016-03-30&%24skiptoken=lZDLSsQwGIWfxSLu0lzbtAURES8LC2JnKi6T9K8TapuQpEUc5t3tK7g9HM73cc7Z
Aj%2fp1S5TzJpz9vHYHY5d1mSnlHxsMJ7Vor5ghiXl6ncNkBs3N0JwHFcdTbA%2bWbdEDJyPvKQaFdwwJIyRSFesRrKqSSlJxSupsQ9uswOEiFtrgotuTPmDm%2f2aAG82pFV9t8qc7ALxTnm
Ltr26r98yQktEOOLk5jpOO9JNsKdUSEapRFTSEYlB1khrCaggg6qg0kKM4gp3%2f9d8h%2bjWYOA5uNVH%2fPL2dNhf6VtSM3GP%2b3bX%2f%2bzbgmWXyx8%3d"}'
silly:   }
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: {
silly:           Content-Type: 'application/json; charset=utf-8',
silly:           accept-language: 'en-US',
silly:           x-ms-client-request-id: 'f719b582-bf5d-40e9-aed3-24adef3a9625',
silly:           user-agent: 'WindowsAzureXplatCLI/0.10.4'
silly:       },
silly:       url: 'https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Compute/virtualMachines?ap
i-version=2016-03-30&%24skiptoken=lZDLSsQwGIWfxSLu0lzbtAURES8LC2JnKi6T9K8TapuQpEUc5t3tK7g9HM73cc7ZAj%2fp1S5TzJpz9vHYHY5d1mSnlHxsMJ7Vor5ghiXl6ncNk
Bs3N0JwHFcdTbA%2bWbdEDJyPvKQaFdwwJIyRSFesRrKqSSlJxSupsQ9uswOEiFtrgotuTPmDm%2f2aAG82pFV9t8qc7ALxTnmLtr26r98yQktEOOLk5jpOO9JNsKdUSEapRFTSEYlB1khrCa
ggg6qg0kKM4gp3%2f9d8h%2bjWYOA5uNVH%2fPL2dNhf6VtSM3GP%2b3bX%2f%2bzbgmWXyx8%3d',
silly:       body: null
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-original-request-ids: '8445cfb2-f550-4ef3-b6da-3cde2d7d55fe',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14996',
silly:           x-ms-request-id: '5d8756ee-7cdf-4e6a-96e0-c1fe55915371',
silly:           x-ms-correlation-request-id: '5d8756ee-7cdf-4e6a-96e0-c1fe55915371',
silly:           x-ms-routing-request-id: 'WESTUS2:20160925T033902Z:5d8756ee-7cdf-4e6a-96e0-c1fe55915371',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           date: 'Sun, 25 Sep 2016 03:39:02 GMT',
silly:           connection: 'close',
silly:           content-length: '58355'
silly:       },
silly:       body: '{"value":[{"properties":{"vmId":"7feeec06-12a0-477f-8b20-778fe43d8fcf", 
...
```

I used the following quick template to create 100+ VMs: https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-copy-index-loops

If it still reproduces on your end, I would suspect it's an issue that only occur on your machine or under your subscription that needs further investigation.

**Comment by BorisB2015** [comment]
@huangpf - I was going to suggest to (@djberg96, @carnott-redhat) a check to run Azure CLI in a docker container but it appears that the latest docker image pulls 0.10.3 of Azure CLI - is this expected? (docker pull microsoft/azure-cli; docker run -it microsoft/azure-cli)

**Comment by BorisB2015** [comment]
@djberg96, @carnott-redhat - could you please try running the command in Azure CLI in a container (it was updated to 0.10.4) and see if you still can repro the behavior? Thanks!
