### ISSUE TITLE
Equivalent CLI command for Add-AzureRmVMSecret 

### ISSUE THREAD

**Issue by mayurshintre** [Azure/azure-xplat-cli#3199]
Need equivalent functionality and command for Add-AzureRmVMSecret in the XPLAT CLI.

**Comment by CosmicCubicle** [comment]
I see this has not seen an update since Sept 26th.  Any chance we can get some info on if this is a planned functionality and when?

**Comment by mayurshintre** [comment]
Gentlemen, any updates on when this gets shipped?

**Comment by huangpf** [comment]
Sorry that our resources got a bit shuffled so we couldn't get to it at the initial timeline. Per triage, this is planned to be fix in CLI2.0 @amarzavery, and for CLI1.0 we will try to get to it ASAP, hopefully before vacation. Meanwhile, you can use ```azure resource set``` to update any ARM resources, including VMs.

**Comment by amarzavery** [comment]
@huangpf - Please get this in before December 7, code freeze.

**Comment by huangpf** [comment]
Fixed by: https://github.com/Azure/azure-xplat-cli/pull/3338
