### ISSUE TITLE
`azure login` forces interactive MFA login for OrgID, but continuously errors out

### ISSUE THREAD

**Issue by orekdm** [Azure/azure-xplat-cli#3203]
CLI Version: 0.10.4
OS Type: Ubuntu
Installation via:  npm 

Mode: **ARM / ASM**  (both)

Environment: 

Description:
`azure login` forces interactive MFA login for OrgID, but continuously errors out

Steps to reproduce:
1) Run `azure login`
2) Complete MFA login process
 (To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code ...)

Error stack trace:
Sorry, but we’re having trouble signing you in. 
We received a bad request.

Additional technical information:
Correlation ID: b9a1f6e9-b7d8-4a83-9174-2923fcd06d51
Timestamp: 2016-09-27 18:45:22Z
AADSTS90011: Error when processing DeviceAuthRedirect request.

**Comment by KylieLiang** [comment]
Met same issue. What I tried is 0.10.5 on Ubuntu 16.04 VM. 
Tried 0.10.5 on Windows, no such an issue.

**Comment by amarzavery** [comment]
@orekdm - If the orgId does not have 2FA enabled then please provide the username
`azure login -u <your-user0name>` then it will prompt you for password. If the account is not 2FA enabled then the login should be successful.

The error that you see in the browser, is an ADAL issue. It has got nothing to do with the CLI.
@addev-ashish @RandalliLama @weijjia - Can you guys let us know what could be going wrong over here and what steps should one take when he/she receives such an error?

**Comment by bingosummer** [comment]
Met the same issue.

```
Additional technical information:
Correlation ID: 64850230-886a-4b1c-9419-20c958bf13cd
Timestamp: 2016-10-08 05:57:26Z
AADSTS90011: Error when processing DeviceAuthRedirect request
```

**Comment by bingosummer** [comment]
@amarzavery 

@gossion finds that upgrading Azure CLI and Node can solve the issue in our environment. Not sure whether it's the root cause or not. FYI.
```
Azure CLI: 0.10.5
Node: v4.6.0
```

**Comment by orekdm** [comment]
I have upgraded to 0.10.6 and everything works as expected!
