### ISSUE TITLE
`group deployment create` does not honor defaultValue for template parameters

### ISSUE THREAD

**Issue by thobe** [Azure/azure-xplat-cli#3211]
CLI Version: **0.10.5**
OS Type: Mac
Installation via:  brew

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure group deployment create` command does not allow template parameters with `defaultValue` to be omitted from the parameters file.

Steps to reproduce:
1) Pick a deployment template where some parameters have `defaultValue` entries.
2) Create a parameters file that specifies the parameters that don't have `defaultValue` entries.
3) run `azure group deployment create --template-uri <template-uri> -p <parameters> -g <resource-group> -n <name>`

This works fine using version `0.10.4`, but fails in `0.10.5`

Error stack trace:

```
2016-10-04T10:59:17.013Z:
' Template and Deployment "parameters" objects lengths do not match \n\tDeployment Parameter file does not have { Location,ResourceGroupName,Neo4jVersion,Neo4jMasterBoltPort,Neo4jSlaveBoltPort,Neo4jHttpsPort,Neo4jHttpPort,extensionScript } defined.'
undefined
```

This is the complete content of `~/.azure/azure.err`, so there is not much "stack trace" to go on...

**Comment by amarzavery** [comment]
This is fixed in the hot fix release (0.10.6) that is only available via npm.
