### ISSUE TITLE
Default value being ignored when deploying with parameter file.

### ISSUE THREAD

**Issue by Nepomuceno** [Azure/azure-xplat-cli#3225]
CLI Version: **0.10.5**
OS Type: Mac
Installation via:  npm 

Mode: **ARM**

Environment: **AzureCloud/Azure China Cloud/US Government/Blackforest/Azure Stack**

Description:
`azure group deployment create -f <file-name> -e <deployment-name>` . Will fail when you have default values on the parameter files but does not have this values on the parameter file. Meaning that with this version having default parameters become pointless. I would flag this with high priority since it breaks all the deployments that have defaultParameters and are using this version. 

Steps to reproduce:
1) Remove the `workerSize` parameter from the `arm-deployment-parametersv2.json`
2) Then run the tests they will fail saying that workerSize it is not defined when it actually have a default value.

Error stack trace:
info:    Executing command group template validate
error:    Template and Deployment "parameters" objects lengths do not match 
    Deployment Parameter file does not have { workerSize } defined.

To check this a change would be needed on the line  https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/group/groupUtils._js#L458 to check not the langht but iterate trough the parameters and check if any parameter that has no default don't have the value being supplied trough the user trough a parameter file or tough a parameter passed on the command line.

**Comment by hectoralicea** [comment]
yea, I found this too.  a bit of a pain having to put all the variables in that do not deviate from the default.  Please fix.  Would not mind removing parameters in the future.

**Comment by ravbhatnagar** [comment]
Working on the fix.

**Comment by PatrickLang** [comment]
Affects Windows too

**Comment by ravbhatnagar** [comment]
this is fixed in the latest version

**Comment by ravbhatnagar** [comment]
Please let us know if you still run into issues.
