### ISSUE TITLE
ARM: 'azure usage list ' return encoded continuationToken

### ISSUE THREAD

**Issue by karlti** [Azure/azure-xplat-cli#3239]
CLI Version: **0.10.5**
OS Type: Win 10 bash
Installation via:  npm 

Mode: **ARM**

Environment: **AzureCloud**

Description:
'azure usage list ....'  returns the usage data.
at the end of the output, the "continuationToken for continued results" is returned in the REST URL as Querystring Param.

Example:

---------------------------------------------------------
```
...
...
info:    continuationToken for continued results: https://management.azure.com:443/subscriptions/xxxxxxxxxxx/providers/Microsoft.Commerce/UsageAggregates?api-version=2015-06-01-preview&reportedstartTime=9%2f1%2f2016&reportedEndTime=10%2f10%2f2016&continuationToken=eyJyIjoiMjAxN......LCJzIjoiMDJpaklwOD0ifQ%3d%3d
...
```
-----------------------------------------------------------
But the last two character are in their encoded form "%3d%3d" and not as "==".
This leads to errors.

Workaround:
Manually changing from "%3d%3d" to "==" solves that issue

**Comment by amarzavery** [comment]
@karlti - I have submitted a PR for fixing the paging problem while executing `usage list`.
Now for pagination you can use the `|more switch` like this: `azure usage list 2016-10-01 2016-10-22 --showDetails |more`. Then by pressing `Enter key` you can keep on getting more information.
You can get all pages by executing: `azure usage list 2016-10-01 2016-10-22 --showDetails`.
The PR #3276 will be merged soon and the release 0.10.7 shall be made publicly available by 11/3/2016.
