### ISSUE TITLE
Feature Request: Cross match command name between ARM and ASM modes

### ISSUE THREAD

**Issue by ilatif** [Azure/azure-xplat-cli#3256]
I' am new to `azure-cli` npm package. I was following a tutorial to get live stream of logs of an azure site. I successfully installed npm package globally and authenticated successfully. To my surprise `azure site log tail _sitename_` command was not working and I was getting following error:

```
error:   'site' is not an azure command. See 'azure help'.
The current mode is: arm (Azure Resource Management).
```

After some googling, I found out that I need to change my `mode`. I was thinking if user has entered a valid command but he is currently in different mode like the case I stated above, instead of showing an error message we can output something useful stating clearly that command itself is valid but it belongs to other mode and to change the mode user can run following command.

This will be a very helpful feature.

If this is already present, then I' am sorry, but I wasn't able to find it.

Thanks

**Comment by amarzavery** [comment]
Hi Imran, the cli has two modes. ASM (V1 version of Azure) and ARM (V2 version of Azure). The command that you want to execute is in ASM.
Please execute `azure config mode asm` and then execute `azure site -h`. You should be able to see the command.

**Comment by amarzavery** [comment]
Thanks for the feedback, we will improve the error message.

**Comment by ilatif** [comment]
@amarzavery: Thanks for your reply. Yeah, you are right, changing mode from ARM to ASM would solve the issue. But as I said and as you agree that an improved error message would be quite helpful if the command is correct but belongs to other mode.


Thanks

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-xplat-cli/issues/3272

**Comment by balajikris** [comment]
Fixed with https://github.com/Azure/azure-xplat-cli/pull/3424
