### ISSUE TITLE
azure vm get-serial-output fails outside of AzureCloud 

### ISSUE THREAD

**Issue by ejarvi** [Azure/azure-xplat-cli#3266]
CLI Version: **0.10.6**
OS Type: Linux Ubuntu 16.0.4.1 LTS 
Installation via:  npm
Mode: ARM
Environment: AzureChinaCloud,AzureUSGovernment,AzureGermanCloud (anything but AzureCloud)

Description:
`azure vm get-serial-output` fails outside of AzureCloud environment.   

This command appears to always use a hardcoded AzureCloud endpoint suffix (core.windows.net) for an internal URL it constructs, instead of selecting the correct endpoint suffix for the associated cloud environment.  Since the URL is invalid, the attempt to retrieve it will always fail outside of AzureCloud, and the command will be unable to return the serial output.  Any downstream scenario that relies on being able to retrieve this output will also fail.  

Steps to reproduce:
1) `azure login` to a subscription outside of AzureCloud 
2) `azure account show`  to confirm Environment field is not AzureCloud
3) (if no VM already exists) `azure vm quick-create` 
4) `azure vm get-serial-output -g [groupname] -n [vmname] -s [subscriptionid]` 

Error: 
2016-10-19T22:53:39.568Z:
{ Error: getaddrinfo ENOTFOUND clisto2624540482adetstub.blob.core.windows.net clisto2624540482adetstub.blob.core.windows.net:443
  <<< async stack >>>
  at __1 (/usr/lib/node_modules/azure-cli/lib/util/storage.util.js:479:35)
  at StorageUtil_performStorageOperation__1 (/usr/lib/node_modules/azure-cli/lib/util/storage.util.js:477:5)
  at getSerialOutput__16 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient.js:619:15)
  at __15 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vm.js:355:16)
  <<< raw stack >>>
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:76:26)
  stack: [Getter/Setter],
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'clisto2624540482adetstub.blob.core.windows.net',
  host: 'clisto2624540482adetstub.blob.core.windows.net',
  port: '443',
  __frame: 
   { name: '__1',
     line: 477,
     file: '/usr/lib/node_modules/azure-cli/lib/util/storage.util.js',
     prev: 
      { name: 'StorageUtil_performStorageOperation__1',
        line: 458,
        file: '/usr/lib/node_modules/azure-cli/lib/util/storage.util.js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 19,
        col: 4 },
     calls: 0,
     active: false,
     offset: 2,
     col: 34 },
  rawStack: [Getter] }
Error: getaddrinfo ENOTFOUND clisto2624540482adetstub.blob.core.windows.net clisto2624540482adetstub.blob.core.windows.net:443
  <<< async stack >>>
  at __1 (/usr/lib/node_modules/azure-cli/lib/util/storage.util.js:479:35)
  at StorageUtil_performStorageOperation__1 (/usr/lib/node_modules/azure-cli/lib/util/storage.util.js:477:5)
  at getSerialOutput__16 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient.js:619:15)
  at __15 (/usr/lib/node_modules/azure-cli/lib/commands/arm/vm/vm.js:355:16)
  <<< raw stack >>>
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:76:26)

**Comment by huangpf** [comment]
It seems it's pointing to a public blob. Could you please help check the the ```vm show``` command to see what's the actual link to the console blob?

**Comment by ejarvi** [comment]
The link I see in the vm show command has the correct suffix.  See below.  My theory is that some CLI command logic actually does look at this link, but only takes the storage account name portion and then passes only that portion to a constructor for an object it needs.  This constructor may then be appending the default prod endpoint suffix rather than the environment specific suffix.    Just a theory. I have not yet been able to pinpoint where in the code this might be happening.  
```
data:    Diagnostics Profile:
data:      BootDiagnostics Enabled       :true
data:      BootDiagnostics StorageUri    :https://clisto2624540482adetstub.blob.core.usgovcloudapi.net/
data:    
data:      Diagnostics Instance View:
info:    vm show command OK
```

**Comment by ejarvi** [comment]
I noticed that [vmExtensionProfile._js](https://github.com/Azure/azure-xplat-cli/blob/f059516e2a6fe96a6352e000cecbe6e8c3ae40cd/lib/commands/arm/vm/vmExtensionProfile._js) includes a hardcoded suffix for storageAccountEndPoint.  This would be an incorrect suffix in any cloud other than AzureCloud and seems like it could lead to this type of a failure in get-serial-output. 

```
  _createDiagPrivateConfiguration: function(_) {  
    var config = {  
      storageAccountName: null,  
      storageAccountKey: null,  
      storageAccountEndPoint: 'https://core.windows.net:443/'  
    };

```

**Comment by ejarvi** [comment]
Here is the relevant output I am seeing from the vm show command:

info:    Executing command vm show
+ Looking up the VM "adetstubu1610"
<snip>
data:
data:    Diagnostics Profile:
data:      BootDiagnostics Enabled       :true
data:      BootDiagnostics StorageUri    :https://clisto2624540482adetstub.blob.core.usgovcloudapi.net/
data:
data:      Diagnostics Instance View:
info:    vm show command OK

**Comment by ejarvi** [comment]
I have been spending a little more time researching this, and I think I understand the issue at this point. 

Note that when creating the blob service no endpoint suffix hint is provided (or can be, for that matter):
`var blobService = azureStorage.createBlobService(result.accountName, keys.keys[0].value);`
https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/vm/vmClient._js#L604

Switching to the azure-storage repo we see this exported as follows:
```
exports.createBlobService = function (storageAccountOrConnectionString, storageAccessKey, host) {
  return new BlobService(storageAccountOrConnectionString, storageAccessKey, host, null);
};
```
https://github.com/Azure/azure-storage-node/blob/master/lib/azure-storage.js#L97-L99

It's the wrong number of parameters, but honeybadg^H^H^H... [Javascript don't care](http://stackoverflow.com/a/15323939).  

After that a null endPointSuffix gets passed all the way down:
```
function BlobService(storageAccountOrConnectionString, storageAccessKey, host, sasToken, endpointSuffix) {
  var storageServiceSettings = StorageServiceClient.getStorageSettings(storageAccountOrConnectionString, storageAccessKey, host, sasToken, endpointSuffix);
```
https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.js#L98-L99


`storageServiceSettings = StorageServiceSettings.createExplicitly(storageAccountOrConnectionString, storageAccessKey, host, sasToken, endpointSuffix);`
https://github.com/Azure/azure-storage-node/blob/dev/lib/common/services/storageserviceclient.js#L858-L872


`StorageServiceSettings.createExplicitly = function (storageAccount, storageAccessKey, host, sasToken, endpointSuffix) {`


endpointSuffix was null so it is not added to the settings:
```
  addIfNotNullOrEmpty('endpointsuffix', endpointSuffix);
  return StorageServiceSettings.createFromSettings(settings);
```
https://github.com/Azure/azure-storage-node/blob/dev/lib/common/services/storageservicesettings.js#L154-L156


`return this._createStorageServiceSettings(settings);`
https://github.com/Azure/azure-storage-node/blob/master/lib/common/services/storageservicesettings.js#L185


... still null, so must fall back to StorageServiceClientConstants.CLOUD_BLOB_HOST: 
```
  var blobEndpoint = standardizeHost(
      util.tryGetValueInsensitive(ConnectionStringKeys.BLOB_ENDPOINT_NAME, settings),
      accountName,
      scheme,
      endpointSuffix ? 'blob.' + endpointSuffix : StorageServiceClientConstants.CLOUD_BLOB_HOST);
```
https://github.com/Azure/azure-storage-node/blob/master/lib/common/services/storageservicesettings.js#L377-L380


`    CLOUD_BLOB_HOST: 'blob.' + storageDnsSuffix,`
https://github.com/Azure/azure-storage-node/blob/dev/lib/common/util/constants.js#L2115


Which finally gives us a hardcoded endpoint value that will always be wrong outside of AzureCloud : 
`var storageDnsSuffix = process.env.AZURE_STORAGE_DNS_SUFFIX || 'core.windows.net';`
https://github.com/Azure/azure-storage-node/blob/dev/lib/common/services/storageservicesettings.js#L131

**Comment by ejarvi** [comment]
Looking into providing a 'host' parameter to the createBlobService call, if that can result in pulling the correct endpointSuffix then it may resolve the issue. 

_var blobService = azureStorage.createBlobService(result.accountName, keys.keys[0].value, **[host]**);_

**Comment by ejarvi** [comment]
private tests succeeded, submitted pull request with the proposed fix:  https://github.com/Azure/azure-xplat-cli/pull/3343

**Comment by ejarvi** [comment]
Fix merged.
