### ISSUE TITLE
'download' is not an azure command. 

### ISSUE THREAD

**Issue by bjtucker** [Azure/azure-xplat-cli#3272]
CLI Version: **0.9.X**
OS Type: Mac / Win / Linux (Ubuntu, RedHat, etc.)
Installation via:  npm / brew / win-or-mac installer / docker / github repo

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure account download` falsely states 
error:   'download' is not an azure command. See 'azure help'.

it should give an error message that directs the user in any way on what is wrong. How about:

'download' is not an ARM mode command. 

Steps to reproduce:
1) Run `azure account download`

```
root@64ebb79a3b04:/# azure account download
error:   'download' is not an azure command. See 'azure help'.
The current mode is: arm (Azure Resource Manager).
```

**Comment by eduardkoller** [comment]
We should look into improving the error message

**Comment by balajikris** [comment]
Fixed with https://github.com/Azure/azure-xplat-cli/pull/3424
