### ISSUE TITLE
Feature Request - "partial" parameters file support

### ISSUE THREAD

**Issue by nneul** [Azure/azure-xplat-cli#3274]
Would be really nice to have the deployment function as:

Defaults from template + Overrides from Parameters File(s) + Prompt for anything missing

Even better - allow the parameters file option to be specified more than once. 

This would allow for doing things like having a base template (shared publicly), and a default set of parameters that you use locally for all deployments (storage accounts, ssh keys, etc.) - but have the remainder of properties provided interactively.

**Comment by nneul** [comment]
Seems somewhat related to #3225

**Comment by amarzavery** [comment]
So the main issue reported in #3225 has been fixed. We have an [npm only 0.10,6 hot fix release](https://github.com/Azure/azure-xplat-cli/releases/tag/v0.10.6-October2016).

- Uninstall the previously installed CLI 
    - If you installed via MSI, then uninstall the windows MSI. For mac installer `sudo azure-uninstall -g`
    - If you installed via npm then execute: npm uninstall azure-cli –g
- Clear the global cache: npm cache clear –g
- Delete the .streamline folder from the User’s home profile `C:\Users\<username>\.streamline` | `~/.streamline`, if present. 

Then install from npm.
`npm install -g azure-cli`.

**Comment by amarzavery** [comment]
@ravbhatnagar @vivsriaus - Can you guys take a look at other suggestions provided by @nneul  for improving the experience ?

**Comment by vivsriaus** [comment]
@nneul thanks for the feedback. Prompting for missing parameter values is something that has been supported for a long time. Is this not what you see in your end? 

Please install the latest cli as @amarzavery pointed out above and let us know if the deployment create command experience is less than ideal for your scenarios. Thanks

**Comment by nneul** [comment]
Tested with 0.10.5, will try again as described above.

**Comment by nneul** [comment]
Nope - same symptom. If I pass a parameter file - it has to have 100% of the parameters defined in it or else it shows an error like this:

error:   Deployment parameter file does not have parameters { networkInterfaceId,vmName } defined. 

In this particular test case, I defined adminUserName, storageAccountName, and sshKeyData in my parameters file, but left out networkInterfaceId and vmName. This is exactly the scenario I described above - base template, base parameters, per-vm desired customization.

**Comment by nneul** [comment]
```azure group deployment create -g xxxx -n yyyy --template-file template.json --parameters-file parameters.json```

**Comment by vivsriaus** [comment]
Thanks. @andrew-mestas can you please take a look?

**Comment by amarzavery** [comment]
@nneul - I am sure you would have installed the right/latest version from npm. Just want to be sure that if the previous version was installed via MSI then it was uninstalled correctly.
Can you execute `azure -v` and let us know the output?

**Comment by nneul** [comment]
Pure linux here... 

nneul@skyhawk:~$ azure -v
0.10.6

**Comment by andrew-mestas** [comment]
@nneul Can you try defining the two parameters within the parameters file just leave their values blank. Then you will be prompted for missing values. 

If values in template file are default they can pass without being defined within the parameters file.

If they are not defaulted then we double check if they are defined within the parameters file and their values are not null.

"networkInterfaceId": {
      "value":""
    },
"vmName": {
      "value":""
    },

**Comment by nneul** [comment]
That does work, though not ideal for the described use case of "common parameters" since the parameters file at that point would have to be specific to every template it was used with as opposed to something that could be used across a collection of different templates. (This ties in with the suggestion of allowing multiple instances of --parameters-file.)

**Comment by nneul** [comment]
If changing behavior of parameters file isn't an option - another alternative would be adding '--defaults-file' which would overload the default values. In that case, it would still prompt for everything, but allow you to skip through anything where an override for the default existed in the file.

**Comment by andrew-mestas** [comment]
It wouldn't be difficult to adjust. Currently it does return the missing values, but instead of throwing an error we could pass to prompt. Will discuss further with @vivsriaus and @amarzavery

**Comment by ravbhatnagar** [comment]
Defaults from template + Overrides from Parameters File(s) + Prompt for anything missing
The above has been fixed. Please let us know if you still run into any issues.
