### ISSUE TITLE
inconsistency in case requirement for dns record-set create vs delete

### ISSUE THREAD

**Issue by nneul** [Azure/azure-xplat-cli#3282]
CLI Version: 0.10.6
OS Type: Linux Ubuntu
Installation via:  npm

Mode: ARM

`azure network dns record-set add-record` will accept a type of `-y cname` however, the corresponding 'record-set delete' requires it to be all uppercase 'CNAME'.

Both should require uppercase, or neither should.

**Comment by jtuliani** [comment]
@nneul thanks for flagging, great catch!

@MikhailTryakhov Please can you take a look?  Record type should be case-insensitive across all commands.

**Comment by MikhailTryakhov** [comment]
Hi @nneul 
sorry but I can't reproduce such issue. Type option is case insensitive for both ```add-record``` and ```delete-record``` commands.
[](http://image.prntscr.com/image/0f209118045f49639b3299603d02a129.png)

Please review can it work for you or not. If you still have this problem - please attach screenshot here and I'll reopen this issue

**Comment by nneul** [comment]
delete not delete-record. Looks like the latter works, but the former does not.

```
nneul@skyhawk:/local/misc/tools$ azure network dns record-set delete-record -g ${res_group} -z ${domain} -n app -y CNAME -c ucstg-app-gw.srv.domain.net 
info:    Executing command network dns record-set delete-record
+ Looking up the dns zone "domain.net"                                      
+ Looking up the DNS Record Set "app" of type "CNAME"                          
Delete DNS Record? [y/n]  info:    network dns record-set delete-record command OK


nneul@skyhawk:/local/misc/tools$ azure network dns record-set delete-record -g ${res_group} -z ${domain} -n app -y CNAME -c ucstg-app-gw.srv.domain.net 
info:    Executing command network dns record-set delete-record
+ Looking up the dns zone "domain.net"                                      
+ Looking up the DNS Record Set "app" of type "CNAME"                          
Delete DNS Record? [y/n]  n
info:    network dns record-set delete-record command OK


nneul@skyhawk:/local/misc/tools$ azure network dns record-set delete -g ${res_group} -z ${domain} -n app -y CNAME
info:    Executing command network dns record-set delete
+ Looking up the DNS Record Set "app" of type "CNAME"                          
Delete DNS record set "app" from DNS zone "domain.net"? [y/n]  info:    network dns record-set delete command OK

nneul@skyhawk:/local/misc/tools$ azure network dns record-set delete -g ${res_group} -z ${domain} -n app -y cname
info:    Executing command network dns record-set delete
+ Looking up the DNS Record Set "app" of type "cname"                          
error:   cname is not a valid value. The valid values are: A,AAAA,CNAME,MX,NS,PTR,SOA,SRV,TXT
error:   Error information has been recorded to /users/nneul/.azure/azure.err
error:   network dns record-set delete command failed

```

**Comment by MikhailTryakhov** [comment]
Thanks a lot for clarification, @nneul 
That's interesting, because issue is non on client side but in SDK.

@jtuliani where can we add such info about specified case sensitivity of record set type in **azure-arm-dns -> recordSets -> get** command?

This is fixed and available in [PR#3298](https://github.com/Azure/azure-xplat-cli/pull/3298) and would be published soon

**Comment by jtuliani** [comment]
There is new documentation in the works for the SDK, I'll add this.

**Comment by MikhailTryakhov** [comment]
@jtuliani thank you! please let me know if you'll need any help here
