### ISSUE TITLE
network nsg rule create has undocumented default port range of 80

### ISSUE THREAD

**Issue by nneul** [Azure/azure-xplat-cli#3284]
CLI Version: 0.10.6 / Linux / Ubuntu / npm

Creating a rule appears to default to using port 80 only when no range is specified. A more sensible default would be to block the full port range like the other attributes that default to '*'. If it's going to default to 80 only, that probably should be output in the help information.

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you take a look at this issue?

**Comment by MikhailTryakhov** [comment]
Thanks @nneul 
Just to clarify: do you mean to update helper like on example below?
![](http://image.prntscr.com/image/ff533a142f394dbbbff01b12259e52fa.png)

**Comment by nneul** [comment]
That would work, though I do think 80 as a default isn't very meaningful/good practice for a security group. (To me, default for block should be *, default for grant should be none.) - but that's a separate issue. 

Your change would address the mismatch of doc and default.

**Comment by MikhailTryakhov** [comment]
I agree with you. Actually, as I can see from PowerShell docs - no default values should be set.
But we can't make changes because of possible customers' failures.
Thank you for your help - it would be merged soon
