### ISSUE TITLE
nsg rule create says I can use 'Asterisk' then complains

### ISSUE THREAD

**Issue by nneul** [Azure/azure-xplat-cli#3289]
CLI Version: 0.10.6 / npm / Ubuntu 16.04

umpqua network nsg rule create -g ${res_group} -a ${sg} -n https-443-${idx} -p tcp -u 443 -c Allow -y $((idx++)) -r Inbound -f Asterisk

info:    Executing command network nsg rule create
warn:    Using default --source-port-range *
error:   --source-address-prefix must be in CIDR format. Asterisk, Internet, VirtualNetwork, AzureLoadBalancer can be used also.

If it's going to suggest Asterisk in the same place as other literal strings - it should support accept it. Otherwise it should say that '*' is valid.

**Comment by MikhailTryakhov** [comment]
Hi @nneul,
thank you for a great job again!
Currently it's fixed and would be published in upcoming releast

**Comment by nneul** [comment]
Fix looks like it adds '*' to the description, but doesn't look like it does anything to allow it to accept 'Asterisk' literally.

**Comment by MikhailTryakhov** [comment]
Nope, [this](https://github.com/Azure/azure-xplat-cli/pull/3309/commits/cbbcbda792140ced50b8fd9df6cbccd4f533afc1#diff-c68b62b0f323422bbb34fa6a10f4514eR35) would unblock it
