### ISSUE TITLE
inconsistent args for azure application-gateway

### ISSUE THREAD

**Issue by nneul** [Azure/azure-xplat-cli#3295]
CLI Version:0.10.6 npm linux

Most of the azure network application-gateway commands take "-n" for gateway name, but not the "backend-health show" subcommand. It is using "-w". 

The -n option isn't in use for that sub command, so seems like an oversight. At least would be good to add as an alternative to -w.

**Comment by MikhailTryakhov** [comment]
Thank you @nneul.
It's fixed and would be merged soon
