### ISSUE TITLE
azure-cli data collection & `-q`

### ISSUE THREAD

**Issue by tc0312** [Azure/azure-xplat-cli#3297]
azure-cli is asking me to opt-in to data collection even with flag `-q`.
It does time out but it stills look bad.

Log: https://travis-ci.org/hdinsight/livy/builds/173171289

**Comment by amarzavery** [comment]
It will ask you only one time and that too on the first command execution. However, if the first command executed is `azure telemetry -d` then it wont prompt you.

**Comment by tc0312** [comment]
For scripting scenario (a good example would be my use case, using azure-cli in travis), from the user perspective, it shouldn't ask for any user inputs as long as I'm passing flag `-q`.

**Comment by amarzavery** [comment]
As of today the CLI does timeout after 30 seconds if no input is received from the customer. So at max it adds 30 seconds more to your CI run.

We do support an environment variable - `export AZURE_NON_INTERACTIVE_MODE=1 ` for the CLI. However, this environment variable is not supported for the telemetry command. We will add support for this command as well.

**Comment by balajikris** [comment]
@tc0312 : A fix has been checked in and it should be available by the next release `0.10.9`. With this change, setting this env var `AZURE_NON_INTERACTIVE_MODE=1` will not prompt for data-collection, and that should make your workflow better.

**Comment by tc0312** [comment]
Thank you so much.
