### ISSUE TITLE
breaking out of prompt (C-c) should not result in a "OK" response

### ISSUE THREAD

**Issue by nneul** [Azure/azure-xplat-cli#3299]
0.10.6 / npm / linux

This probably should print out a newline before the prompt and should return a CANCELLED or ERROR status, or something else - right now it's very misleading cause it looks like the operation proceeded even though I cancelled the prompt. 

```
nneul@skyhawk:/local/x$ azure network dns record-set delete-record -g ${res_group} -z ${domain} -n app -y CNAME -c xxxxxxxxxxxxxx 
info:    Executing command network dns record-set delete-record
+ Looking up the dns zone "xxxxxxxxxxxx"                                      
+ Looking up the DNS Record Set "app" of type "CNAME"                          
Delete DNS Record? [y/n]  info:    network dns record-set delete-record command OK

```

**Comment by nneul** [comment]
Similar if you say no - perhaps exit with a "N/A" status.

**Comment by jtuliani** [comment]
@nneul great feedback, thank you
@MikhailTryakhov can we fix this?

**Comment by MikhailTryakhov** [comment]
@nneul, @jtuliani do you mean info message?

**Comment by jtuliani** [comment]
Yes.  We shouldn't show 'command OK' if it was cancelled.

**Comment by MikhailTryakhov** [comment]
It's common style in CLI to show OK, even declining command. 
I propose to add warn/info message here, that action was declined... Or discuss a bit with leads about best implementation

**Comment by jtuliani** [comment]
Agree, let's discuss with SDK/CLI owners what best approach is here, we should be consistent across the CLI.  Please follow up with them.

**Comment by MikhailTryakhov** [comment]
@amarzavery could you please help us to find the best solution?
We wish to make command cancellation very clear and correct. There is an assumption to rework ```delete``` (and some other) commands, which need to be approved by user.
If we have cancelled comman - CLI can return CANCELLED status or any other, but not just OK like we do now...

Please let us know your opinion

**Comment by nneul** [comment]
From a user perspective - I'd be fine with it explicitly printing out an _additional_ message saying that the operation was skipped. , my main objection is the "Oh, *(&@#, it looks like it went and and did it anyway even though I cancelled." reaction.

**Comment by MikhailTryakhov** [comment]
Agree with you, think it would be helpful for all such commands

**Comment by MikhailTryakhov** [comment]
Fixed for DNS and would be published soon.
Related [PR#3419](https://github.com/Azure/azure-xplat-cli/pull/3419)
