### ISSUE TITLE
3rd party image publish in marketplace trying to programatic deploy.

### ISSUE THREAD

**Issue by RicksterCDN** [Azure/azure-xplat-cli#3312]
CLI Version: **0.9.X**
OS Type: Linux 
Mode: **ARM **

Environment: **AzureCloud**

Description: `azure vm quick-create -Q clear-linux-project:clear-linux-os:basic:1.0.5 -M ~/.ssh/id_rsa.pub` fails with cryptic message. 

Steps to reproduce:
1) publish image in portal. 
2) stage it for your account. 
3) Deploy through portal - works fine.
4) enable it for programmatic deploy via command line.
5) deploy using azure vm create with ALL the arguments - it works. 
6) run `azure vm quick-create -Q clear-linux-project:clear-linux-os:basic:1.0.5 -M ~/.ssh/id_rsa.pub` and it FAILS because it is not a platform image and can't use the shorter method of deployment. 

**We need a more graceful exit / error that says it can't deploy with shorter format using quick-create**

here is output. 

rnesius@clr-rockett ~ $ azure vm quick-create -Q clear-linux-project:clear-linux-os:basic:1.0.5 -M ~/.ssh/id_rsa.pub
info:    Executing command vm quick-create
Resource group name: rnesius-cli-test02
Virtual machine name: rnesius02
Location name: westus
Operating system Type [Windows, Linux]: Linux
User name: rnesius
+ Listing virtual machine sizes available in the location "westus"
+ Looking up the VM "rnesius02"
info:    Verifying the public key SSH file: /home/rnesius/.ssh/id_rsa.pub
info:    Using the VM Size "Standard_DS1"
info:    The [OS, Data] Disk or image configuration requires storage account
+ Looking up the storage account cli2136142611395304750
info:    Could not find the storage account "cli2136142611395304750", trying to create new one
+ Creating storage account "cli2136142611395304750" in "westus"
+ Looking up the storage account cli2136142611395304750
+ Looking up the NIC "rnesi-westu-213614261-nic"
info:    An nic with given name "rnesi-westu-213614261-nic" not found, creating a new one
+ Looking up the virtual network "rnesi-westu-213614261-vnet"
info:    Preparing to create new virtual network and subnet
+ Creating a new virtual network "rnesi-westu-213614261-vnet" [address prefix: "10.0.0.0/16"] with subnet "rnesi-westu-213614261-snet" [address prefix: "10.0.1.0/24"]
+ Looking up the virtual network "rnesi-westu-213614261-vnet"
+ Looking up the subnet "rnesi-westu-213614261-snet" under the virtual network "rnesi-westu-213614261-vnet"
info:    Found public ip parameters, trying to setup PublicIP profile
+ Looking up the public ip "rnesi-westu-213614261-pip"
info:    PublicIP with given name "rnesi-westu-213614261-pip" not found, creating a new one
+ Creating public ip "rnesi-westu-213614261-pip"
+ Looking up the public ip "rnesi-westu-213614261-pip"
+ Creating NIC "rnesi-westu-213614261-nic"
+ Looking up the NIC "rnesi-westu-213614261-nic"
+ Looking up the storage account clisto3173950602rnesius0
+ Creating VM "rnesius02"
error:   Long running operation failed with error: 'Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is clif2601a91bd0ed90c-os-1478811079878.'.
info:    Error information has been recorded to /home/rnesius/.azure/azure.err
error:   vm quick-create command failed

**Comment by balajikris** [comment]
@huangpf @sauryadas : hey guys, can you please take a look at this?
