### ISSUE TITLE
Template Parameter Validation is overly strenuous

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-xplat-cli#3316]
See: https://github.com/Azure/acs-engine/issues/92

Why does xplat cli expect that for every parameter declared in the template there is a parameter in the parameters file?

I expected that if the template had a default value, then it could be omitted from the parameters file. If not, what is the point of having default parameter values in the template?

This is not checked by PowerShell or the new python azure-cli.

**Comment by balajikris** [comment]
Hey @colemickens :  can you try the latest release of xplat-cli `0.10.7` and see if this still happens? We recently fixed some issues around this space.

**Comment by stewartadam** [comment]
Note: this is likely related to #3225.

**Comment by amarzavery** [comment]
@ravbhatnagar @vivsriaus @andrew-mestas - We have been seeing lot of issues filed by customers in this area. Can we jot down what the workflow should be over here? This sets the right expectation and can help us iron-out issues. Code freeze for upcoming release is November 30. Please make sure that this can be resolved before that to get into the upcoming release

**Comment by ravbhatnagar** [comment]
@colemickens - This should be addressed in the latest version of the CLI. Can you please confirm?

Here is what will work-
1. Default values for the parameters specified in the template will be honored
2. Missing values for parameters will result in a prompt
3. Parameters file need not have all the parameters defined in the template
4. Default Values will be overwritten by those specified in the template or specified inline

**Comment by colemickens** [comment]
Confirmed, I don't see the buggy behavior on `0.10.7`.
