### ISSUE TITLE
azure cli login failed on SUSE11SP4 due to unable to get local issuer certificate

### ISSUE THREAD

**Issue by Lickkylee** [Azure/azure-xplat-cli#3329]
CLI Version: **0.10.7**
OS Type: Linux (SuSE 11 SP4)
Installation via:  npm

Mode: **ARM / ASM**

Environment: **Azure China Cloud

Description:
'azure login'  unable to get local issure certificate

Steps to reproduce:
1) Run `azure login -e azurechinacloud...`

Error stack trace:

**Please paste the content of ~/.azure/azure.err or C:\Users\username\\.azure\azure.err over here**
SUSE11SP4:~/.azure # cat ./azure.err 
2016-11-18T08:03:34.727Z:
{ Error: unable to get local issuer certificate
  <<< async stack >>>
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/login.js:116:28)
  <<< raw stack >>>
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
  stack: [Getter/Setter],
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  __frame: 
   { name: '__1',
     line: 50,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/login.js',
     prev: undefined,
     calls: 0,
     active: false,
     offset: 66,
     col: 27 },
  rawStack: [Getter] }
Error: unable to get local issuer certificate
  <<< async stack >>>
  at __1 (/usr/local/lib/node_modules/azure-cli/lib/commands/login.js:116:28)
  <<< raw stack >>>
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) 

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).

PS. when we install nodejs on SUSE 11 SP4, there was an dependency ignored by us. Not sure if this is the actual cause. But if not ignore, the installation will fail. 

#zypper in nodejs nodejs-devel                                                                                                                                                                                              Refreshing service 'cloud_update'.

New repository or package signing key received:
Key ID: 01A61473270E2386
Key Name: devel:languages:nodejs OBS Project <devel:languages:nodejs@build.opensuse.org>
Key Fingerprint: 587F4144A9361A72F77AD50001A61473270E2386
Key Created: Fri Sep 25 19:37:30 2015
Key Expires: Sun Dec  3 19:37:30 2017
Repository: Node.js (SLE_11_SP4)

Do you want to reject the key, trust temporarily, or trust always? [r/t/a/? shows all options] (r): a
Building repository 'Node.js (SLE_11_SP4)' cache [done]
Building repository 'node' cache [done]
Loading repository data...
Reading installed packages...
Resolving package dependencies...
2 Problems:
Problem: nothing provides openssl1 needed by nodejs-6.9.1-130.1.x86_64
Problem: nothing provides openssl1 needed by nodejs-6.9.1-130.1.x86_64

Problem: nothing provides openssl1 needed by nodejs-6.9.1-130.1.x86_64
 Solution 1: do not install nodejs-6.9.1-130.1.x86_64
 Solution 2: break nodejs-6.9.1-130.1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or skip, retry or cancel [1/2/s/r/c] (c):2

**Comment by balajikris** [comment]
this doesn't seem like a xplat-cli issue to me, as clearly `openssl` seems to be missing? Also, xplat-cli release `0.10.7` supports `Node LTS 4.x`. 

tagging @yugangw-msft and @amarzavery

**Comment by Lickkylee** [comment]
I have fixed this issue by building nodejs from source code and then installing azure cli. It seems that latest nodejs need openssl version at least 1.0 but suse 11sp4 by default comes with 0.9.8. So it definitely is nodejs issue not azure cli. Thanks everyone. I will close this issue.
