### ISSUE TITLE
azure vm reset-access --password makes insecure changes the SSHD configuration

### ISSUE THREAD

**Issue by vlivech** [Azure/azure-xplat-cli#3335]
CLI Version: 0.10.6 (node: 7.0.0)
OS Type: Mac
Installation via:  brew

Mode: ARM

Environment: AzureCloud

Description:
Using `azure vm reset-access --password`  to reset a Linux users password, makes insecure changes to the SSH servers configuration `/etc/ssh/sshd_config` and allows password logins by changing the value of `PasswordAuthentication` to `yes`.

Steps to reproduce:
1) deploy Linux VM using SSH keys for authentication `-M ~/.ssh/id_rsa.pub` with a user called `ahmet`
2) login to the Linux VM and verify the setting for `PasswordAuthentication` in `/etc/ssh/sshd_config` is `no`
3) from the `azure-cli` reset user Ahmets password - `azure vm reset-access --user-name ahmet --password newPassw0rd`
4) login to the Linux VM and verify the settings for `PasswordAuthentication` in `/etc/ssh/sshd_config` is *now* `yes`

Expected Behavior:

Resetting a users password with vm access-extensions should _only_ change that users password.  

Resetting the Linux SSH configuration using `azure vm reset-access --reset-ssh` _would_ reset the SSH configuration.

`azure vm reset-access` would not make any system wide security changes unless explicitly asked by using the `--reset-ssh` cli flag. 

Current Behavior:

Using `azure vm reset-access` to make changes to a Linux user, has an insecure effect on the entire Linux VM by opening up SSH to password brute forcing attempts by allowing passwords for SSH logins.  All unknown to the admin of the Linux VM.

Error stack trace:
no error logs

bug filed for pycli - https://github.com/Azure/azure-cli/issues/1437

**Comment by balajikris** [comment]
per yugang, we need to do this:
> I would suggest double check it installs the version of 1.4, and doesn't explicitly set auto_upgrade_minor_version to false

I'm not sure which package to audit, will get more context from @yugangw-msft

**Comment by squillace** [comment]
@yugangw-msft @balajikris we do not want this to bite the customer; it **will** cause more than simply irritation. didn't make this one, but needs to be fixed.

**Comment by balajikris** [comment]
I've audited the xplat-cli codebase along with yugang and we found that `autoUpgradeMinorVersion` is always set to `true` in `vmExtensionProfile._js`. Per yugang, this means we're good.

**Comment by balajikris** [comment]
Nothing to do from the CLI's perspective.
