### ISSUE TITLE
`azure network application-gateway create` can't customize some parameters

### ISSUE THREAD

**Issue by zhongyi-zhang** [Azure/azure-xplat-cli#3339]
CLI Version: **0.10.2**
OS Type: Linux
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure network application-gateway create` can't customize some parameters.

Steps to reproduce:
Can't find some parameters in help. And it returns warnings below.

Error stack trace:

warn:    Using default gateway ip name: ipConfig01
warn:    Using default frontend ip name: frontendIp01
warn:    Using default frontend port name: frontendPort01
warn:    Using default address pool name: pool01
warn:    Using default http settings name: httpSettings01
warn:    Using default http listener name: listener01
warn:    Using default request routing rule name: rule01

**Comment by amarzavery** [comment]
@MikhailTryakhov @jtuliani - Please take a look at this issue.

**Comment by MikhailTryakhov** [comment]
It's fixed and would be published in next release on December
