### ISSUE TITLE
`azure network application-gateway` can't specify the custom probe in http settings

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#3346]
CLI Version: **0.10.6**
OS Type: Linux (Ubuntu)
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure network application-gateway http-settings` command doesn't have an option to specify the custom probe.
Even I can create a probe via `azure network application-gateway probe create`, but I can not bind it with the AG.

Steps to reproduce:
1) Run `azure network application-gateway http-settings set -h`

**Comment by bingosummer** [comment]
@MikhailTryakhov @jtuliani

**Comment by MikhailTryakhov** [comment]
This issue duplicates issue [#3283](https://github.com/Azure/azure-xplat-cli/issues/3283).
It's fixed and would be published in next release on December.

@bingosummer  Jonathan doesn't manage App gateways - please ping me for any questions

**Comment by bingosummer** [comment]
Thanks @MikhailTryakhov for your quick response.
