### ISSUE TITLE
local-gateway commands do not support BGP settings

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-xplat-cli#3351]
CLI Version: **0.10.6**
OS Type: **Mac**
Installation via:  **npm**

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure network local-gateway create/update/show` commands do not support BGP peering settings.

Steps to reproduce:
1) Run `azure network local-gateway create/update -h`

The create and update commands do not expose any mechanism of setting the local gateway BGP settings. Additionally, the output of the show command does not display BGP settings (although using --json does).

See the following in the Python CLI repo:
https://github.com/Azure/azure-cli/issues/1416
https://github.com/Azure/azure-cli/issues/1435
https://github.com/Azure/azure-cli/pull/1456

**Comment by MikhailTryakhov** [comment]
Thank you!
It's fixed and would be published in next release (December, 14)
