### ISSUE TITLE
Not able to register application type in Service Fabric

### ISSUE THREAD

**Issue by vmakhaev** [Azure/azure-xplat-cli#3355]
CLI Version: **0.10.7**
OS Type: Mac
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure servicefabric application type register` command doesn't see ApplicationManifest.xml file

Steps to reproduce:
1) Create ApplicationManifest.xml file
2) Run `azure servicefabric application type register .`

➜ ls
ApplicationManifest.xml hello
➜ azure servicefabric application type register .

info:    Executing command servicefabric application type register
+ Register application type
error:   {"Error":{"Code":"FABRIC_E_FILE_NOT_FOUND","Message":"The Application Manifest file '.\/ApplicationManifest.xml' is not found in the store."}}
error:   Error information has been recorded to /Users/vmakhaev/.azure/azure.err
error:   servicefabric application type register command failed

➜ azure servicefabric application type register ./

info:    Executing command servicefabric application type register
+ Register application type
error:   {"Error":{"Code":"FABRIC_E_FILE_NOT_FOUND","Message":"The Application Manifest file '.\/ApplicationManifest.xml' is not found in the store."}}
error:   Error information has been recorded to /Users/vmakhaev/.azure/azure.err
error:   servicefabric application type register command failed

➜ azure servicefabric application type register ~/projects/hello

info:    Executing command servicefabric application type register
+ Register application type
error:   {"Error":{"Code":"FABRIC_E_IMAGEBUILDER_VALIDATION_ERROR","Message":"The path '\/Users\/vmakhaev\/projects\/hello' is not allowed since it is an absolute path. Only relative path is allowed."}}
error:   Error information has been recorded to /Users/vmakhaev/.azure/azure.err
error:   servicefabric application type register command failed

Error stack trace:

{ Error: {"Error":{"Code":"FABRIC_E_FILE_NOT_FOUND","Message":"The Application Manifest file '.\/ApplicationManifest.xml' is not found in the store."}}
  <<< async stack >>>
  at __6 (/usr/local/lib/node_modules/azure-cli/lib/commands/servicefabric/serviceFabricApplication.js:202:43)
  <<< raw stack >>>
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-servicefabric/lib/operations/applicationTypes.js:396:19
    at handleRedirect (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:965:12)
  stack: [Getter/Setter],
  statusCode: 404,
  request:
   { rawResponse: false,
     queryString: {},
     method: 'POST',
     headers: { 'Content-Type': 'application/json; charset=utf-8' },
     url: 'http://innovation2.eastus.cloudapp.azure.com:19080/ApplicationTypes/$/Provision?api-version=3.0-preview',
     body: '{"ApplicationTypeBuildPath":"."}' },
  response:
   { body: '{"Error":{"Code":"FABRIC_E_FILE_NOT_FOUND","Message":"The Application Manifest file \'.\\/ApplicationManifest.xml\' is not found in the store."}}',
     headers:
      { 'content-length': '142',
        'content-type': 'application/octet-stream' },
     statusCode: 404 },
  body:
   { error:
      { code: 'FABRIC_E_FILE_NOT_FOUND',
        message: 'The Application Manifest file \'./ApplicationManifest.xml\' is not found in the store.' } },
  __frame:
   { name: '__6',
     line: 191,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/servicefabric/serviceFabricApplication.js',
     prev: undefined,
     calls: 3,
     active: false,
     offset: 11,
     col: 42 },
  rawStack: [Getter] }
Error: {"Error":{"Code":"FABRIC_E_FILE_NOT_FOUND","Message":"The Application Manifest file '.\/ApplicationManifest.xml' is not found in the store."}}
  <<< async stack >>>
  at __6 (/usr/local/lib/node_modules/azure-cli/lib/commands/servicefabric/serviceFabricApplication.js:202:43)
  <<< raw stack >>>
    at /usr/local/lib/node_modules/azure-cli/node_modules/azure-servicefabric/lib/operations/applicationTypes.js:396:19
    at handleRedirect (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at Request._callback (/usr/local/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/azure-cli/node_modules/request/request.js:965:12)

**Comment by amarzavery** [comment]
@msjeffreychen - please take a look at this issue.

**Comment by msjeffreychen** [comment]
Hi Vladimir:
Thanks for trying it out. The correct way to register an application type is to copy the package to the cluster first, then register the package afterward. You could refer to this [doc](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-remove-applications). This is the powershell version, but the order and the steps are the same. Thanks.

**Comment by vmakhaev** [comment]
@msjeffreychen ok, I was able to upload package with
`azure servicefabric application package copy --application-package-path . --image-store-connection-string fabric:ImageStore`
but, I still not able to register application type. I need path of my package in the store. I see how to specify it with Power Shell while uploading package, but I do not see any way to do it with azure-cli.
Documentation is very poor. Could you provide me list of commands to deploy application to Service Fabric with azure-cli?

**Comment by gladiacxtylish** [comment]
The path will be the directory name of your package you just copied. Could you try the example commands below? Thanks.
`$ azure servicefabric application package copy --application-package-path SamplePackage --image-store-connection-string fabric:ImageStore`
`$ node bin/azure servicefabric application type register --application-type-build-path SamplePackage`

**Comment by msjeffreychen** [comment]
The path will be the directory name of your package you just copied. Could you try the example commands below? Thanks.
`$ azure servicefabric application package copy --application-package-path SamplePackage --image-store-connection-string fabric:ImageStore`
`$ node bin/azure servicefabric application type register --application-type-build-path SamplePackage`

**Comment by amarzavery** [comment]
@vmakhaev - Any update on this?

**Comment by gscott** [comment]
I'm not @vmakhaev but I had the same issue; I made the mistake of using a `.` or a `./` for the directory path when registering the application. You need a directory name...  following your example above worked for me.

**Comment by wralph** [comment]
Hi,
I am following this example https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-create-your-first-linux-application-with-java
When trying to deploy the app using install.sh I am getting the following
```
error:   {"Error":{"Code":"FABRIC_E_FILE_NOT_FOUND","Message":"The Application Manifest file 'myapp\/ApplicationManifest.xml' is not found in the store."}}
error:   Error information has been recorded to /home/ralph/.azure/azure.err
error:   servicefabric application type register command failed
```
To me the path to the manifest looks shaky. 
Any ideas on that?

Thx Ralph

**Comment by mani-ramaswamy** [comment]
Can you open up install.sh and run the commands one at a time? It looks like the copy command didn't work?

**Comment by wralph** [comment]
hi many, 
see my output from the single commands.
```
ralph@rwalnx:~/git/myapp$ azure servicefabric application package copy myapp fabric:ImageStore -v
info:    Executing command servicefabric application package copy
verbose: Copy application package
data:    undefined
info:    servicefabric application package copy command OK
```

and

```
ralph@rwalnx:~/git/myapp$ azure servicefabric application type register myapp
info:    Executing command servicefabric application type register
+ Register application type
error:   {"Error":{"Code":"FABRIC_E_FILE_NOT_FOUND","Message":"The Application Manifest file 'myapp\/ApplicationManifest.xml' is not found in the store."}}
error:   Error information has been recorded to /home/ralph/.azure/azure.err
error:   servicefabric application type register command failed
```

anything obvious to you?
thx for your help

**Comment by mani-ramaswamy** [comment]
Please use user name and password for login. Certificate based auth isn't yet supported as described in https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-azure-cli#troubleshooting.

**Comment by Jose-CF** [comment]
Same problem here. Could you clarify this? Otherwise the whole azure-cli is useless. Cannot register applications... what are other people doing?!

**Comment by Jose-CF** [comment]
I tried almost everything. Is there a working example on how to register an application type just uploaded using xplat cli? 

Powershell example is very beautiful but xplat cli not working the same. For instance, using the powershell api you can specify the path of the package in the store when copying it. With xplat cli you cannot.

I tried also using "Debug" folder as path because in the powershell documentation says it's the default value if you do not specify any. Still getting the same error as the original poster.

Azure 2.0 CLI will ever support servicefabric?

**Comment by mani-ramaswamy** [comment]
The earlier issue was closed because he was using ssh keys which isn't supported.

Did you try the instructions @ https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-azure-cli?

 azure servicefabric cluster connect http://localhost:19080
 azure servicefabric application package copy MySFApp fabric:ImageStore
 azure servicefabric application type register MySFApp
 azure servicefabric application create fabric:/MySFApp MySFApp 1.0

And yes, we’re already working on supporting Azure 2.0 CLI – we should have a preview out next month.

**Comment by Jose-CF** [comment]
Hello,

Now seems to work. The problem was that, according to xplat cli documentation, when using register we pass a "application-package-path" parameter, so I did not understand why it would not get a .\dirname in it. Just writing dirname seems to work.
Thank you!

**Comment by Jose-CF** [comment]
Thank you for your support.
I had two small errors in my commands... 

* Using ./ to indicate the "path" of the application to register. This is a bit confusing.... path is a path, directory name is a directory name....
* double slash for the create command: fabric:// .... also a bit missleading. 

Now working. Again... Thank you!

**Comment by mani-ramaswamy** [comment]
great - will update the docs to make this clearer.

**Comment by Jose-CF** [comment]
Today this issue came up again. Issuing the same commands is not working any more. When registering the application to a local cluster I keep getting the 

`{"Error":{"Code":"FABRIC_E_FILE_NOT_FOUND","Message":"The Application Manifest file 'Debug\\ApplicationManifest.xml' is not found in the store."}}`

error.

I am really puzzle since this was working last week an nothing changed in my local cluster. Publishing to azure seems to work.

**Comment by rajeshm7910** [comment]
Same issue for me as well :
vagrant@vagrant:~/myapp/myapp$ azure servicefabric application type register myapp

info:    Executing command servicefabric application type register
+ Register application type
error:   {"Error":{"Code":"FABRIC_E_FILE_NOT_FOUND","Message":"The Application Manifest file 'myapp\/ApplicationManifest.xml' is not found in the store."}}
error:   Error information has been recorded to /home/vagrant/.azure/azure.err
error:   servicefabric application type register command failed

**Comment by jeffreychenmsft** [comment]
Many of the register failures are due to copy package problem. If copy package did not copy to the right location, the files could not be found. Check your copy package command first.

**Comment by mani-ramaswamy** [comment]
Please let us know if the problem was resolved.

**Comment by Jose-CF** [comment]
For me yes, I do not know the other folks.

**Comment by mani-ramaswamy** [comment]
Great. We're also releasing the CLI 2.0 that shoudl address many issues. I will close this. For the others on the thread, please open a new issue as you find them.

**Comment by Jose-CF** [comment]
I am already using az over here (azure-cli 2.0.8) looks a bit better than xplat :)

**Comment by mani-ramaswamy** [comment]
Great!

**Comment by EwaldStricker** [comment]
Hint: I got same issue by editing ApplicationManifest.xml in Notepad++.  After the error checking the ApplicationManifest.xml content  in Visual Studio results in  file without the application infomation. So the file was there but no matching Content => solved
