### ISSUE TITLE
ARM Command Doesn't Work with Node 0.12 + NPM Install from Git repo

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-xplat-cli#3387]
CLI Version: 0.10.8
OS Type: Win
Installation via:  npm + github repo

Mode: ARM

Environment: AzureCloud

Description:
azure group list would break at line 1335 of the resourceGroups.js file. with the error saying that the 'endsWith' method is not defined.

Per this link, it seems this method has problem in node v0.12

***However, npm install -g azure-cli would work on the same machine & setup.

**Comment by amarzavery** [comment]
Node.js is ending support for 0.12 version on December 31st of this year. Hence we are not using that version anymore. Please upgrade to any 4.x version and then run the command. All the installers are shipping with 4.70 version of node.js

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
