### ISSUE TITLE
Authority should be set to login-us.microsoftonline.com for US Gov

### ISSUE THREAD

**Issue by djberg96** [Azure/azure-xplat-cli#3393]
CLI Version: 0.10.4 (node 4.2.4)
OS Type: Mac
Installation via:  win-or-mac installer

Mode: ARM

Environment: US Government

Description:

It seems that when using the environment is set to US Gov, the CLI is still using the public authority:

`- Authenticating...info:    Wed, 14 Dec 2016 15:11:21 GMT:69c71ecf-xxxx-1234-abcd-12345 - Authority: VERBOSE: Performing instance discovery: https://login.microsoftonline.com/xxxxxx`

While this works, I feel it should default to https://login-us.microsoftonline.com/ instead. Not only do the docs* tell me that this is the proper endpoint, but my contact at Microsoft says, and I quote:

    When using login.microsoftonline.com, traffic passes through systems which are NOT part of US Gov’t Azure.
    Developers who want to make sure that traffic passes only through systems which are part of US Gov’t Azure should use login-us.microsoftonline.com.

Docs: https://docs.microsoft.com/en-us/azure/azure-government-developer-guide#a-nameendpointaendpoint-mapping

**Comment by amarzavery** [comment]
The default environment is the us production environment.  It can never be US government.  However, at the time of login you can use the -e switch and specify the environment. Azure login -h will give you the help.
Azure account env list and azure account env show $envname will tell you more info about the environment.

Once you have successfully logged in a particular environment, you do not have to specify the environment for other commands. The cli figures it out automatically as long as you are using a subscription that is associated to the user or service principal with that environment.

**Comment by djberg96** [comment]
@amarzavery The default environment is the public environment. What I'm saying is that if I set "-e AzureUSGov" then the authority should explicitly use login-us.microsoftonline.com instead of login.microsoftonline.com to get the token used in subsequent requests.

**Comment by amarzavery** [comment]
thanks. I get the problem now. We have updated the endpoint. The release 0.10.8 was out few minutes ago and it has that fix in it.

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-xplat-cli/releases/tag/v0.10.8-December2016

**Comment by djberg96** [comment]
@amarzavery Thanks!

Possibly dumb question - why is that marked 0.10.8, but the .dmg says 0.10.5?

**Comment by amarzavery** [comment]
Oh you are right. I still have to publish the mac installer. I am waiting to get it signed. I did not want to hold off on making other installers available. If you scroll in the downloads section of the release page, I have not yet uploaded the mac installer (.dmg).

I am sorry I should have communicated that. If you have node.js installed on your system then you can execute: `npm install -g azure-cli` and it will install the latest version for you.

If you do not have node.js installed on your system then you can install the latest 4.x version from [here](https://nodejs.org/dist/latest-v4.x/) and then execute `npm install -g azure-cli`.

Make sure to uninstall the old version of the CLI if you have installed via mac installer `sudo azure-uninstall`.

**Comment by amarzavery** [comment]
The signed mac installer should be available now.

**Comment by djberg96** [comment]
@amarzavery Thanks!
