### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE 

### ISSUE THREAD

**Issue by Lickkylee** [Azure/azure-xplat-cli#3397]
CLI Version: **0.10.7**
OS Type:  Linux (SuSe. etc.)
Installation via:  npm 

Mode: **ASM**

Environment: **Azure China Cloud**

Description:
`azure ` command doesn't work in ASM mode. 

Steps to reproduce:
1) Run `azure config mode asm ...`
2) Then run `azure vm list ...` or any other command.. 

Error stack trace:

**Please paste the content of ~/.azure/azure.err or C:\Users\username\\.azure\azure.err over here**

lqi1e-susec-scr:~ # azure config mode asm
info:    Executing command config mode
info:    New mode is asm
info:    config mode command OK
lqi1e-susec-scr:~ # azure vm list
info:    Executing command vm list
+ Getting virtual machines
error:   unable to verify the first certificate
error:   Error information has been recorded to /root/.azure/azure.err
error:   vm list command failed

lqi1e-susec-scr:~ # cat /root/.azure/azure.err
2016-12-15T09:50:40.504Z:
{ Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
lqi1e-susec-scr:~ # azure -v
0.10.7

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).

**Comment by Lickkylee** [comment]
add more information, after testing, I found that this azure cli error occurred when using ASM mode in Mooncake. Azure CLI in both windows and Linux have the same problem. version of azure i used are 0.10.2 and 0.10.7. 

C:\Users\lqi.FAREAST>azure config mode asm
info:    Executing command config mode
info:    New mode is asm
info:    config mode command OK

C:\Users\lqi.FAREAST>azure vm list
info:    Executing command vm list
+ Getting virtual machines
error:   unable to verify the first certificate
error:   Error information has been recorded to C:\Users\lqi.FAREAST\.azure\azure.err
error:   vm list command failed

should it be a platform issue?

**Comment by Lickkylee** [comment]
it was proved that this should be related to nodejs and Mooncake. ASM API in China didn't use a certificate that was in nodejs trusted list. I also tried nodejs v4.7.0. The same problem. 

As a workround, just to set NODE_TLS_REJECT_UNAUTHORIZED=0. 
On Linux: export NODE_TLS_REJECT_UNAUTHORIZED=0 
On Windows: set NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by ultrafastneal** [comment]
Thanks @Lickkylee - That workaround worked!

**Comment by amarzavery** [comment]
This problem is solved in a better way in node.js (version 6.10.0). 
Please set/export this envt. variable NODE_EXTRA_CA_CERTS=\<path to a system generated certificate (.pem) file\>.
Find out more info over [here](https://nodejs.org/dist/latest-v6.x/docs/api/all.html#cli_node_extra_ca_certs_file).
