### ISSUE TITLE
vpn-gateway create and update dont provide an option to configure BGP ASN, which is required for VNET-VNET connections

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-xplat-cli#3409]
CLI Version: **0.10.8**
OS Type: Win 
Installation via:  win-or-mac installer (http://aka.ms/webpi-azure-cli)

Mode: **ARM**

Environment: **AzureCloud**

**Description:**
`azure network vpn-gateway set' and 'azure network vpn-gateway create' should have proper option to configure BGP ASN. Note that for enabling BGP for a VNET-VNET connection the following two steps have to be taken in the stated order
1. Change the ASN at the Gateway level for one of the Gateway
2. Enable BGP at the connection level

Today, #1 cannot be done because the command doesnt provide an option.

**Steps to reproduce:**
C:\WINDOWS\system32>azure network vpn-gateway set -h
help:    Set a virtual network gateway
help:
help:    Usage: network vpn-gateway set [options] <resource-group> <name>
help:
help:    Options:
help:      -h, --help                                   output usage information
help:      -v, --verbose                                use verbose output
help:      -vv                                          more verbose with debug output
help:      --json                                       use json output
help:      -g, --resource-group <resource-group>        the name of the resource group
help:      -n, --name <name>                            the name of the virtual network gateway
help:      -k, --sku-name [sku-name]                    the SKU name
help:           Valid values are [Basic,HighPerformance,Standard]
help:      -d, --default-site-name [default-site-name]  the Local Network Gateway name. This Local Network Gateway must exists in the same resource group as the vnet gateway.
help:           Please use default-site-id if that is not the case.
help:      -i, --default-site-id [default-site-id]      Local Network Gateway identifier.
help:           e.g. /subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Network/localNetworkGateways/<local-gateway-name>
help:      -f, --address-prefixes [address-prefixes]    the comma separated list of address prefixes.
help:           For example, -f "10.0.0.0/24,10.0.1.0/24"
help:      -t, --tags [tags]                            the list of tags.
help:           Can be multiple. In the format of "name=value".
help:           Name is required and value is optional.
help:           Existing tag values will be replaced by the values specified.
help:           For example, -t "tag1=value1;tag2"
help:      -s, --subscription <subscription>            the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you take a look at this issue?

**Comment by MikhailTryakhov** [comment]
Fixed and would be published in next release
