### ISSUE TITLE
azure network vpn-connection create and set commands do not have a parameter to enable BGP

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-xplat-cli#3411]
CLI Version: **0.10.8**
OS Type: Running XPlat on Win 
Installation via:  win-or-mac installer (from this link - http://aka.ms/webpi-azure-cli)

Mode: **ARM**

Environment: **AzureCloud**

Description:
'azure network vpn-connection create' and 'azure network vpn-connection set' dont provide option to enable BGP routing

Steps to reproduce:
1) Run azure network vpn-connection create -h
2) Run azure network vpn-connection set -h

In both the cases there is no parameter to enable BGP. 

Without this capability it is not possible to deploy BGP routing.

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you take a look at this issue?

**Comment by MikhailTryakhov** [comment]
Fixed and would be published in next release
