### ISSUE TITLE
Unable to create a local network Gateway that doesnt have BGP

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-xplat-cli#3413]
CLI Version: **0.10.8**
OS Type: Win 
Installation via:  win-or-mac installer 
Mode: **ARM**

Environment: **AzureCloud**

Description:
I am unable to create a simple local network gateway that uses only static routes, no BGP dynamic routing

Steps to reproduce:
1) Run azure network local-gateway create -g VV2 -n VNet2LNG -i 10.12.10.12 -a "172.25.10.0/24","172.25.20.0/24" --location "East US"

2) I see the following error. It says ASN should not be set to 0 but i am not evev enabling BGP in the first place.
info:    Executing command network local-gateway create
+ Looking up local network gateway "VNet2LNG"
+ Creating local network gateway "VNet2LNG"
error:   The local network gateway /subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV2/providers/Microsoft.Network/localNetworkGateways/VNet2LNG cannot have an ASN of zero
error:   Error information has been recorded to C:\Users\aanandr\.azure\azure.err
error:   network local-gateway create command failed

Error stack trace:
2016-12-24T00:37:41.270Z:
{ [Error: The local network gateway /subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV2/providers/Microsoft.Network/localNetworkGateways/VNet2LNG cannot have an ASN of zero]
  stack: [Getter/Setter],
  statusCode: 400,
  request: 
   { rawResponse: false,
     queryString: {},
     method: 'PUT',
     headers: 
      { 'x-ms-client-request-id': '534266be-608b-4673-8f22-de1509739853',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8',
        'x-ms-command-name': 'network local-gateway create',
        'x-ms-parameter-set-name': '****** -g *** -n ******** -i *********** -a ***************************** --location *******',
        'user-agent': 'AzureXplatCLI/0.10.8;osType:Windows_NT;osVersion:10.0.14393;nodeVersion:v4.7.0;installationType:NPM;userId:b8895888c8b8c18f4e9e0904b5cba70921ec00d505f6f0ade12ee8e5512d7ce5;subscriptionId:e7e33b39-fe28-4822-b65c-a4db8bbff7cb;userType:user;mode:arm' },
     url: 'https://management.azure.com/subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV2/providers/Microsoft.Network/localNetworkGateways/VNet2LNG?api-version=2016-09-01',
     body: '{"location":"East US","properties":{"localNetworkAddressSpace":{"addressPrefixes":["172.25.10.0/24","172.25.20.0/24"]},"gatewayIpAddress":"10.12.10.12","bgpSettings":{}}}' },
  response: 
   { body: '{\r\n  "error": {\r\n    "code": "LocalNetworkGatewayCannotHaveZeroAsn",\r\n    "message": "The local network gateway /subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV2/providers/Microsoft.Network/localNetworkGateways/VNet2LNG cannot have an ASN of zero",\r\n    "details": []\r\n  }\r\n}',
     headers: 
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-length': '296',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'x-ms-request-id': '93d9b743-2e77-4fc6-b9cf-70678875f21f',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
        'x-ms-ratelimit-remaining-subscription-writes': '1199',
        'x-ms-correlation-request-id': 'dd02f91c-d3bb-41b6-9dc9-c314532eb76e',
        'x-ms-routing-request-id': 'WESTUS2:20161224T003740Z:dd02f91c-d3bb-41b6-9dc9-c314532eb76e',
        date: 'Sat, 24 Dec 2016 00:37:40 GMT',
        connection: 'close' },
     statusCode: 400 },
  code: 'LocalNetworkGatewayCannotHaveZeroAsn',
  body: 
   { code: 'LocalNetworkGatewayCannotHaveZeroAsn',
     message: 'The local network gateway /subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV2/providers/Microsoft.Network/localNetworkGateways/VNet2LNG cannot have an ASN of zero',
     details: [] },
  __frame: 
   { name: 'create__1',
     line: 34,
     file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\network\\localNetworkGateway.js',
     prev: 
      { name: '__107',
        line: 2256,
        file: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI\\lib\\commands\\arm\\network\\network.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 8,
        col: 19 },
     calls: 1,
     active: false,
     offset: 19,
     col: 66 },
  rawStack: [Getter] }
Error: The local network gateway /subscriptions/e7e33b39-fe28-4822-b65c-a4db8bbff7cb/resourceGroups/VV2/providers/Microsoft.Network/localNetworkGateways/VNet2LNG cannot have an ASN of zero
  <<< async stack >>>
  at create__1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\network\localNetworkGateway.js:53:67)
  at __107 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\network\network.js:2264:20)
  <<< raw stack >>>
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\azure-arm-network\lib\operations\localNetworkGateways.js:307:19
    at retryCallback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest\lib\filters\redirectFilter.js:36:9)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\utils.js:605:7
    at handleRedirect (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\utils.js:582:9)
    at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\util\logging.js:339:7
    at Request._callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\ms-rest\lib\requestPipeline.js:125:16)
    at Request.self.callback (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\request\request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you take a look at this issue?

**Comment by MikhailTryakhov** [comment]
Fixed and woul be published in next release
