### ISSUE TITLE
The vpn-gateway create command has parameters for local network gateway

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-xplat-cli#3414]
CLI Version: **0.10.8**
OS Type: Win 
Installation via:  win-or-mac installer 

Mode: **ARM**

Environment: **AzureCloud**

Description:
The azure network vpn-gateway create has parameters for local network gateway. This is very misleading because there is already a context, viz. azure network local-gateway, for that. It gives the impression that local network gateway can also be created using the vpn-gateway create context

Steps to reproduce:
Check the help option by running
azure network vpn-gateway create -h

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you take a look at this issue?

**Comment by MikhailTryakhov** [comment]
Hi @aanandr 
if you propose to rename option names for VPN gateways or local gateways - unfortunately we can't do it now becaus of backward compatibility. It would fail all existing scripts which use full option names.

This should be fixed at CLI spec stage or at least on code review stage.
Now we can't fix it so

**Comment by aanandr** [comment]
I am fine with the names. What I am trying to say in the bug is that currently it has parameters that we configure for a local network gateway, which are not applicable to VPN Gateway.

**Comment by MikhailTryakhov** [comment]
sorry @aanandr 
could you please provide an example?

**Comment by amarzavery** [comment]
I think he is talking about default-site-name and default-site-id, as the help description talks about local network gateway over there. I am not sure if the description says that the command will create it. It provides you an option to reference the already created local gateway.

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0>azure network vpn-gateway create -h
help:    Create a virtual network gateway
help:
help:    Usage: network vpn-gateway create [options] <resource-group> <name> <location>
help:
help:    Options:
help:      -h, --help                                   output usage information
help:      -v, --verbose                                use verbose output
help:      -vv                                          more verbose with debug output
help:      --json                                       use json output
help:      -g, --resource-group <resource-group>        the name of the resource group
help:      -n, --name <name>                            the name of the virtual network gateway
help:      -l, --location <location>                    the location
help:      -w, --gateway-type [gateway-type]            the gateway type
help:           Valid values are [Vpn,ExpressRoute]
help:           Default is Vpn
help:      -y, --vpn-type [vpn-type]                    the vpn type
help:           Valid values are [RouteBased,PolicyBased,Dedicated]
help:           Default is RouteBased
help:      -k, --sku-name [sku-name]                    the SKU name
help:           Valid values are [Basic,HighPerformance,Standard]
help:           Default is Basic
help:      -u, --public-ip-id [public-ip-id]            the public ip identifier.
help:           e.g. /subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Network/publicIPAddresses/<public-ip-name>
help:      -p, --public-ip-name [public-ip-name]        the public ip name. This public ip must exists in the same resource group as the vnet gateway.
help:           Please use public-ip-id if that is not the case.
help:      -f, --subnet-id [subnet-id]                  the subnet identifier.
help:           e.g. /subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Network/VirtualNetworks/<vnet-name>/subnets/<subnet-name>
help:      -m, --vnet-name [vnet-name]                  the virtual network name. This virtual network must exists in the same resource group as the vnet gateway.
help:           Please use subnet-id if that is not the case.
help:      -e, --subnet-name [subnet-name]              the subnet name which exists in vnet. Default value is "GatewaySubnet"
help:      -d, --default-site-name [default-site-name]  the Local Network Gateway name. This Local Network Gateway must exists in the same resource group as the vnet gateway.
help:           Please use default-site-id if that is not the case.
help:      -i, --default-site-id [default-site-id]      Local Network Gateway identifier.
help:           e.g. /subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Network/localNetworkGateways/<local-gateway-name>
help:      -f, --address-prefixes [address-prefixes]    the comma separated list of address prefixes.
help:           For example, -f "10.0.0.0/24,10.0.1.0/24"
help:      -b, --enable-bgp [enable-bgp]                enable bgp [true, false]
help:      -t, --tags [tags]                            the list of tags.
help:           Can be multiple. In the format of "name=value".
help:           Name is required and value is optional.
help:           For example, -t "tag1=value1;tag2"
help:      -s, --subscription <subscription>            the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)
```

**Comment by aanandr** [comment]
Yes, that’s correct. I was referring to these params. Gateway creation command shouldn’t have options to specify the local network gateway. You can check Powershell for reference.

Aanand

**Comment by amarzavery** [comment]
@aanandr - The source of truth for anything in the SDK or CLI is the swagger spec. The swagger spec is authored by the service team that develops the feature.
The operation for creating a [`VirtualNetworkGateway_CreateOrUpdate`](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-09-01/swagger/virtualNetworkGateway.json#L44) takes a [VirtualNetworkGateway](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-09-01/swagger/virtualNetworkGateway.json#L1078) as the body parameter. Some levels down (nested) it has a property named ["gatewayDefaultSite"](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-09-01/swagger/virtualNetworkGateway.json#L884) which has the following description:
```
The reference of the LocalNetworkGateway resource which represents local network site having default routes.
```

The CLI is simply exposing that property as a switch on the command line. So the question is
 - What can be done at the CLI level to improve the experience?

(To give an analogy: While creating a VM, one needs to reference a NIC (that does not necessarily imply that the NIC will be created inline. There is a separate API to create a NIC, that needs to be executed first, before creating the VM).
