### ISSUE TITLE
vpn-gateway set command unable to change the GW SKU, lacks capability to modify other GW parameters

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-xplat-cli#3415]
CLI Version: **0.10.8**
OS Type: Win
Installation via:  win-or-mac installer 

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure network vpn-gateway set ` doesnt provide the capability to change Vpntype and as a result cannot modify the SKU type. I had a GW of SKU type Basic and Vpntype Policy. I wanted to change the SKU type to HighPerformance which is not supported for Vpntype policy.

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you take a look at this issue?

**Comment by MikhailTryakhov** [comment]
Hi @aanandr 
as I can see reviewing server side responses ```--vpn-type``` is not a settable option.
![](http://image.prntscr.com/image/ade0a6c8ac92403e8e2169e0148ccec1.png)

**Comment by aanandr** [comment]
I agree. You can ignore the GW type. But there are others which are configurable, viz.

1.       SKU

2.       BGP ASN

3.       Active-Enabling Active config

Aanand

**Comment by MikhailTryakhov** [comment]
@aanandr agree, 
that would be published in next release

Please write me an IM if you wish to test it before publication - I'll deploy test VM for you

**Comment by aanandr** [comment]
You mean to say that you will add the ability to configure the GW parameters I sent only in the next release?

**Comment by aanandr** [comment]
Thanks Mikhail.
I plan to run all my tests and work on step-by-step guides for Xplat once all issues are fixed. Can you let me know when I will get the bits with all the fixes?

**Comment by MikhailTryakhov** [comment]
@aanandr they're published
sent you .rdp with test environment in email thread. did you have a chance to review it?
