### ISSUE TITLE
Trying to make an IP static for an application gateway does not work.

### ISSUE THREAD

**Issue by hectoralicea** [Azure/azure-xplat-cli#3416]
CLI Version: 0.10.8 (node: 5.5.0)
OS Type: Mac & Linux (CentOS 6)
Installation via:  npm 
Mode: ARM
Environment: AzureCloud

Description:
Trying to make an IP static for an application gateway does not work. Going in, the ip was dynamic for an application gateway. I then executed.

`azure network application-gateway frontend-ip set -a 10.0.2.38 -g ESB_DEV_ResourceGroup -w esb-d-lnx-api -n appGatewayFrontendIP`

which returned a bunch of output including:

```
data:    Frontend ip configurations:
data:      Name                          : appGatewayFrontendIP
data:      Allocation method             : Dynamic
data:      Private IP address            : 10.0.2.38

```
Is not the -a option to make the ip static?

and then did a 

`azure network application-gateway frontend-ip show  -g ESB_DEV_ResourceGroup -w esb-d-lnx-api -n appGatewayFrontendIP`

The output showed that the application-gateway was still using a dynamic IP.

```
HLA-MacBookAir:~ hector$ azure network application-gateway frontend-ip show  -g ESB_DEV_ResourceGroup -w esb-d-lnx-api -n appGatewayFrontendIP
info:    Executing command network application-gateway frontend-ip show
+ Looking up an application gateway "esb-d-lnx-api"                            
data:    Id                              : /subscriptions/bb465ba6-6a3d-4d56-854e-0173218a85aa/resourceGroups/ESB_DEV_ResourceGroup/providers/Microsoft.Network/applicationGateways/esb-d-lnx-api/frontendIPConfigurations/appGatewayFrontendIP
data:    Private IP Address              : 10.0.2.38
data:    Private IP Allocation Method    : Dynamic
data:    Subnet:
data:      Id                            : /subscriptions/bb465ba6-6a3d-4d56-854e-0173218a85aa/resourceGroups/HUD_DEV_VNetResourceGroup/providers/Microsoft.Network/virtualNetworks/HUD-DEV-VNet/subnets/EsbSslDevSubnet
data:    Provisioning State              : Succeeded
data:    Name                            : appGatewayFrontendIP
data:    Etag                            : W/"e15db3a6-504b-41dd-ac53-83ebc8643d47"
info:    network application-gateway frontend-ip show command OK
```

Can someone try to replicate this to see if its pilot error on my part?  The App Gateway was initially created using ARM template.

**Comment by amarzavery** [comment]
@MikhailTryakhov - Can you take a look at this issue?

**Comment by MikhailTryakhov** [comment]
Hi @hectoralicea 
thanks for you activities!
there are few tricks working with public IP and App gateways. You can review few helpful articles: [public-ip allocation method](https://github.com/Microsoft/azure-docs/blob/master/articles/virtual-network/virtual-network-ip-addresses-overview-arm.md#at-a-glance).
Also few notes about [frontend IP config](https://docs.microsoft.com/en-us/powershell/resourcemanager/azurerm.network/v3.1.0/set-azurermapplicationgatewayfrontendipconfig)

**Comment by hectoralicea** [comment]
Sorry.  Did not mean to put the thumbs down, was trying to figure out how to reply to your comment.  These are not public-ips that I'm working with here.  Take a look at the output in the original post.
data:    Private IP Address              : 10.0.2.38
data:    Private IP Allocation Method    : Dynamic
Its a private IP and I'm trying to convert it from Dynamic to static.  If the gateway restarts I want it to make sure it re-uses the same IP address.  But at the same time i dont want to assign an IP at provision time.  I want it to come up with one on its own, so I sent to dynamic and then convert the IP to static.
