### ISSUE TITLE
Install 64 bit node.exe on 64 bit windows

### ISSUE THREAD

**Issue by hasonmsft** [Azure/azure-xplat-cli#3451]
CLI Version: 0.10.8
OS Type: Win
Installation via:  installer 

Mode: ALL

Environment: ALL

Description:
The installed node.exe platform is x86 on x64 machine. It's better to install 32-bit on 32-bit windows and 64-bit on 64-bit windows?

**Comment by yugangw-msft** [comment]
@balajikris, thank a lot!
