### ISSUE TITLE
Unable to create a webapp in a Resource Group different than the one containing the App Service Plan

### ISSUE THREAD

**Issue by mxa0079** [Azure/azure-xplat-cli#3485]
CLI Version: 0.10.7 AND 2.0 Preview
OS Type: Bash on Windows
Installation via:  npm & apt-get (for 2.0)

Mode: ARM

Environment: AzureCloud

Description:
I am unable to create a webapp in a Resource Group different to the RG where the App Service Plan is contained (this is allowed and can be done through the portal).

The error description is: "The Resource 'Microsoft.Web/serverFarms/GRT-Prod' under resource group 'ResourceGroupName' was not found."

Steps to reproduce:
1) Create an App Service Plan (lets call it ASP1) in a resource group (RG1)
2) Create a different resource group (lets call it RG2)
3)Try to create a web app using ASP1 inside RG2

**Comment by amarzavery** [comment]
@mxa0079 - Think of resource group as a bucket/container. I am not sure if you can create resources between different resource groups.

@LukaszStem @naveedaz - Can you take a look at this?

**Comment by naveedaz** [comment]
The web app has to be created in the same resource group as the app service plan. This is a hard requirement. Once created you can move the web app to a different resource group though. If the portal lets you do this it is likely a bug or portal is doing the work to move the app to the resource group (less likely)

**Comment by mxa0079** [comment]
This issue should not be closed. 

The portal clearly let's you do this. 

It makes sense, an app service plan contains multiple websites. Therefore it is natural to want to have those sites spread across multiple resource groups.

I'd like technical backup about the quote "The web app has to be created in the same resource group as the app service plan." 

Can we involve someone from webapp team? I am getting the feeling the team is trying to close this out without the proper due dilligence.

**Comment by amarzavery** [comment]
@mxa0079 - @naveedaz is from the webapp team.

**Comment by mxa0079** [comment]
To expand upon why this makes sense: If you look at the flow in the portal, it clearly allows you to select an "App Service Plan" regardless of the resource group selected. This behavior is consistent with the concept of an App Service Plan, create multiple websites that can live on different resource groups. Otherwise the logical organization of an ASP and WebApps would be very limited.

In my opinion, the CLI should take an argument for the RG that contains the ASP and an argument for the RG where the newly created webapp will be located.

**Comment by amarzavery** [comment]
After creating the app service plan you can move the app service plan to the destination group by executing:
```
azure resource move -h
help:    Moves resources from one resource group to another
help:
help:    Usage: resource move [options] <ids> <destination-group> <api-version>
help:
help:    Options:
help:      -h, --help                                                 output usage information
help:      -v, --verbose                                              use verbose output
help:      -vv                                                        more verbose with debug output
help:      --json                                                     use json output
help:      -i --ids <ids>                                             the comma-delimitied resource ids to be moved
help:      -d --destination-group <destination-group>                 the destination resource group name
help:      --destination-subscriptionId <destination-subscriptionId>  the destination subscription identifier
help:      -o --api-version <api-version>                             the API version of the resource provider
help:      -q, --quiet                                                quiet mode (do not ask for move confirmation)
help:      --subscription <subscription>                              the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)
```

I completely understand that it is not a good solution. However, I am trying to help you with the mechanisms that are present right now.

**Comment by mxa0079** [comment]
Thanks @amarzavery -- although this is a good temporary workaround, the ideal behavior would be to do it from a single command. Can we add this as a feature request?

**Comment by amarzavery** [comment]
> In my opinion, the CLI should take an argument for the RG that contains the ASP and an argument for the RG where the newly created webapp will be located.

The problem at hand is that the service does not support this feature. CLI can very well expose a switch to do that. However, if the service does not support it then there is very little that the CLI can do.

Infact, a better user experience would be to not expose the --resource-group at all while creating the webapp. The webapp create command should find the provided ASP and use it's --resource-group for creating the webapp. It will drastically reduce customer frustration.

/cc@johanste @davidebbo 

Btw, we have a new python based CLI (2.0) https://github.com/Azure/azure-cli. Please feel free to give it a try.

**Comment by amarzavery** [comment]
azure webapp create -h
help:    create a web app
help:
help:    Usage: webapp create [options] <resource-group> <name> <location> <plan>
help:
help:    Options:
help:      -h, --help                            output usage information
help:      -v, --verbose                         use verbose output
help:      -vv                                   more verbose with debug output
help:      --json                                use json output
~~help:      -g --resource-group <resource-group>  Name of the resource group~~
help:      -n --name <name>                      the name of the webapp to create
help:      --slot <slot>                         the name of the slot
help:      -l --location <location>              the geographic region to create the webapp,
help:                                              locations found at https://azure.microsoft.com/en-us/status/
help:      -p --plan <plan>                      the name of the app service plan eg: Default1.
help:      -s, --subscription <id>               the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)

**Comment by davidebbo** [comment]
I don't think this is correct. I just tested with https://resources.azure.com/, and at the API level it's possible to create a Web App in a different RG from the Plan. The only requirement is that they exist in the same region (obviously!).

To do this, you need to use the full resource ID of the Plan in the `serverFarmId` field.

**Comment by davidebbo** [comment]
I chatted with @naveedaz, and we can confirm that it is fully supported now (it didn't used to be a while back).

So I would expect the xplat cli to support this as well (not saying it does now, but it can in theory).

**Comment by mxa0079** [comment]
Thank you @davidebbo for the technical research. 

Based on your conclusions, I believe that the ability "to create a web app in create a Web App in a different RG from the Plan" should be added to the backlog of the xplat cli.

**Comment by davidebbo** [comment]
@mxa0079 Agreed. BTW, you can probably already do it using the low level resource commands instead of the webapp commands.

**Comment by naveedaz** [comment]
@LukaszStem Please look at why this is blocked in the CLI.

**Comment by mxa0079** [comment]
Thanks @davidebbo - do you know where can I find the documentation for the low level command?

FWIW - The reason I am using the xplat cli is two folded: 

a) it is much faster than using the portal
b) in the future I will need to automate the task I am currently performing through the cli. This is preparing us for when that time comes.

So using the low level resource commands will help with reason b) but it may defeat the purpose of a).

Thank you all for your engagement. Go Azure!

**Comment by davidebbo** [comment]
@mxa0079 Admittedly, I know how to do this via PowerShell, but I'm less familiar with the xplat. Actually, there are two of them, the old one ('azure' commands) and the new one ('az' commands).

@amarzavery do you know if 'az' has the expressiveness to make arbitrary ARM call the same way as PowerShell?

**Comment by amarzavery** [comment]
@tjprescott - Can you answer the following question posted by @davidebbo for the new CLI.

> do you know if 'az' has the expressiveness to make arbitrary ARM call the same way as PowerShell?

@davidebbo - I would like to get more clarification on this.

1. As of today the current xplat cli has generic resource commands `azure resource -h` which can be used to make REST calls to any RP in ARM. By the above question are you hinting at something else other than what we currently have?
   1. The resource commands `azure resource set|show|delete` also support accepting the ARM resource `-i | --resource-id` (id) as a parameter. If that is provided then one need not provide other parameters like resource-group, resource-type, name, etc. Just the id and the api-version is sufficient for making the REST call.

**Comment by amarzavery** [comment]
@naveedaz - After the recent changes made to the swagger spec, a new version of `azure-arm-websites` node sdk package has not been published. If that is done and taken as a dependency in azure-xplat-cli then the customer will be unblocked (It works in Powershell because it is dependent on the latest .net websites client (sdk) generated from the latest swagger).
@LukaszStem - I would recommend making this as a priority for the upcoming CLI release.

**Comment by LukaszStem** [comment]
I will prioritize to get this in by next release.

**Comment by davidebbo** [comment]
@amarzavery not sure about the old azure cli. I know in the past it had blocking issues with the generic ARM commands, it's possible that they have now been addressed. Though at this point, shouldn't we try to use the new v2 az cli for everything, to reduce confusion?

**Comment by LukaszStem** [comment]
@davidebbo you make a good point. At some point this issue will come up in the v2 az cli as well. It's probably better to push updates there instead. If others ( @tjprescott @amarzavery )  agree, I'll make the change in https://github.com/Azure/azure-cli

**Comment by mxa0079** [comment]
Agree. In our shop we are moving away form the old cli and have started using the new `az`  command.

**Comment by mxa0079** [comment]
Any news on this?

**Comment by amarzavery** [comment]
@yugangw-msft - Is this supported in CLI 2.0?

**Comment by yugangw-msft** [comment]
yes

**Comment by amarzavery** [comment]
cool then lets close this issue here. The recommendation is to use the new CLI. If it still does not work for the new CLI then please open an issue in that repo https://github.com/Azure/azure-cli
