### ISSUE TITLE
ARM Inconsistent location capitalization for some of the new regions (CanadaEast)

### ISSUE THREAD

**Issue by danielestevez** [Azure/azure-xplat-cli#3501]
CLI Version: **0.10.7**
OS Type: Linux (Ubuntu 16.04)
Installation via:  github repo

Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure vm list` and `azure location list` command shows different capitalization for location for some regions such as `CanadaEast` (might also happen in other locations)

Steps to reproduce:
1) Deploy a vm in Canada East
2) Run `azure vm list`
3) run `azure location lists ...`

When you compare outputs you get different capitalization for CanadaEast but other older regions such as `North Europe` are always in lowercase

`
$ azure location list
data:    
data:    Location    :  **canadaeast**
data:    DisplayName :  Canada East
data:    Providers   :  Microsoft.ApiManagement, Microsoft.Batch, Microsoft.ClassicCompute, Microsoft.ClassicNetwork...
`
`
```
10:55 $ azure vm list
info:    Executing command vm list
+ Getting virtual machines                                                     
data:    ResourceGroupName  Name             ProvisioningState  PowerState  Location     Size       
data:    -----------------  ---------------  -----------------  ----------  -----------  -----------
data:    RG2FAILIMPORT      importmustfail   Succeeded          VM running  northeurope  Standard_A1
data:    ABIQUO-CANADAEAST  abq-8e2f880d-7f  Succeeded          VM running  **CanadaEast**   Basic_A0   
data:    ABIQUO-CANADAEAST  abq-db821ef0-b5  Succeeded          VM running  **CanadaEast**   Basic_A0   
info:    vm list command OK
```
`

This behavior is inconsistent and may produce problems with 3rd party tools

**Comment by huangpf** [comment]
@danielestevez 
This seems to be an issue between ARM and CRP on the service side. CLI is not the right place to resolve this conflict. To get the efficient and proper triage, you shall open a CRI using you subscription. Thanks.

**Comment by danielestevez** [comment]
Thanks @huangpf i'll try to submit a ticket then,
