### ISSUE TITLE
Error using azure CLI in version 0.10.10 - no method 'endsWith'

### ISSUE THREAD

**Issue by twallace27603** [Azure/azure-xplat-cli#3518]
CLI Version: **0.10.10**
OS Type: Ubuntu 14.04 Docker image
Installation via:  npm
Mode: **ARM**

Environment: **AzureCloud**

Description:
Azure CLI commands encounter no method 'endsWith' error.  It works fine with 0.10.7. The microsoft/azure-cli image works fine as well.  It is running version 0.10.7 at this time.

Steps to reproduce:
1) Login with an Azure AD account with co-administrator rights
    azure login -u <account>
2) Then run an Azure command.  This has happened azure vm list, azure vm quick-create, azure group list

Error stack trace:

root@xxx:/# azure vm list
info:    Executing command vm list
+ Getting virtual machines
error:   Object https://management.azure.com has no method 'endsWith'
error:   Error information has been recorded to /root/.azure/azure.err
error:   vm list command failed

**Comment by amarzavery** [comment]
please update your node.js version. You are probably running on 0.10.x version of node.js which is too old and has security issues. Even node.js does not support it now. Please follow the instructions in this [link](https://nodejs.org/en/download/package-manager/#installing-node-js-via-package-manager) to install a later version of node.js on ubuntu.

We support 4.x.
So, this 
```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
``` 
should work

**Comment by twallace27603** [comment]
Thank you for the quick reply.  Worked great.
