### ISSUE TITLE
Get-AzureRMVM in Azure Stack throwing error as api version imcompatible 

### ISSUE THREAD

**Issue by harishchakkingal** [Azure/azure-xplat-cli#3521]
CLI Version: **0.9.X**
OS Type: Mac / Win / Linux (Ubuntu, RedHat, etc.)
Installation via:  npm / brew / win-or-mac installer / docker / github repo

Mode: **ARM / ASM**

Environment: **AzureCloud/Azure China Cloud/US Government/Blackforest/Azure Stack**

Description:
Get-AzureRMVM is throwing  error when trying to get Stack VM details 

Steps to reproduce:
1) Connect to Azure Stack Server from a remote node
2) Exectte the Azure RM cmd-lets

Error stack trace:

Get-AzureRmVM : The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api
version '2016-03-30'. The supported api-versions are '2015-06-15'.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : '812d1a79-5d4a-4dd2-b4ff-f2b98355bd84'
At line:1 char:1
+ Get-AzureRmVM
+ ~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureVMCommand
![error](https://cloud.githubusercontent.com/assets/22904071/23292555/ad2db786-fa86-11e6-9329-8cb32dbf0fbb.png)

If the issue is w.r.t `authentication` then please set `AZURE_ADAL_LOGGING_ENABLED=1` and then run the `azure login` command again. 
Please paste the verbose logs over here. (Make sure to delete the password before pasting the contents).

**Comment by huangpf** [comment]
This is a PS issue, please report it in the Azure/azure-powershell repo.
