### ISSUE TITLE
azure telemetry --disable fails on linux

### ISSUE THREAD

**Issue by k0nG** [Azure/azure-xplat-cli#3540]
CLI Version: **0.10.11**
OS Type: Linux (Ubuntu 12.04)
Installation via:  npm

Mode: **ARM / ASM**

Environment: **AzureCloud**

Description:
`azure telemetry --disable` fails with output

We're running this on CircleCI 1.0 during a build to deploy to Azure Storage. 

Steps to reproduce:
1) Run `azure telemetry --disable.`

Error stack trace:

```
/home/ubuntu/nvm/v0.10.33/lib/node_modules/azure-cli/lib/util/telemetry.js:318
  if (os.platform().startsWith('win')) {
                    ^
TypeError: Object linux has no method 'startsWith'
    at _getMacAddressHash (/home/ubuntu/nvm/v0.10.33/lib/node_modules/azure-cli/lib/util/telemetry.js:318:21)
    at Object.exports.start (/home/ubuntu/nvm/v0.10.33/lib/node_modules/azure-cli/lib/util/telemetry.js:246:24)
    at /home/ubuntu/nvm/v0.10.33/lib/node_modules/azure-cli/bin/azure.js:30:19
    at Object.exports.isTelemetryEnabled (/home/ubuntu/nvm/v0.10.33/lib/node_modules/azure-cli/lib/util/utilsCore.js:174:12)
    at Object.<anonymous> (/home/ubuntu/nvm/v0.10.33/lib/node_modules/azure-cli/bin/azure.js:27:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by amarzavery** [comment]
the version of node.js on your system is very old. Please check this [doc](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) on how to get the latest stable version of node.js installed on your box. It is a simple command. Once you have the latest version then you should be good to go.

**Comment by k0nG** [comment]
Thanks for swift reply.

I've updated node on our CI build to `7.7.1` and that seems to have done the job.

**Comment by activars** [comment]
@amarzavery  What's the plan from Microsoft for the node cli project? Is this going to be replaced by the python cli?

**Comment by amarzavery** [comment]
I do not know the exact timeline. However, eventually this project will be replaced by the [python cli](https://github.com/Azure/azure-cli) for ARM (Version 2 of the Azure APIs). The current cli will still be used for ASM (Version 1 of the Azure APIs). Commands for newer services are being supported in the new cli. If you find any command in the node cli project that is not present in the python cli project then please file an issue in the [python cli](https://github.com/Azure/azure-cli) project.

**Comment by activars** [comment]
Thanks for the quick response & clarification.
