### ISSUE TITLE
The help doc of "azure vm image show" doesn't include "version"

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#3548]
CLI Version: **0.10.10**
OS Type: Linux (Ubuntu)
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
The help doc of `azure vm image show` command doesn't output the version.

Steps to reproduce:
1) Run `azure vm image show -h`

It should be `Usage: vm image show [options] <location> <publisher> [offer] [sku] [version]`. In the below output, `[version]` is missed.

```
$ azure vm image show -h
help:    Lists the virtual machines images
help:
help:    Usage: vm image show [options] <location> <publisher> [offer] [sku]
help:
help:    Options:
help:      -h, --help                         output usage information
help:      -v, --verbose                      use verbose output
help:      -vv                                more verbose with debug output
help:      --json                             use json output
help:      -l, --location <location>          the location
help:      -p, --publisher <publisher>        the publisher name
help:      -o, --offer <offer>                the offer
help:      -k, --sku <sku>                    the sku
help:      -e, --version <version>            the version
help:      -s, --subscription <subscription>  the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)
```

**Comment by huangpf** [comment]
Hi @bingosummer -- It's already listed as a ```--``` parameter, which indicates it's a probably and optional input parameter. Similarly, ```-s``` is not listed in the first brief line. And some commands that have quite many optional parameters won't likely include all. 

Close for now.

**Comment by bingosummer** [comment]
If `offer`, `sku` and `version` are optional, why it still asks me to input them? A little confused.
```
$ azure vm image show "westus" "Canonical"
info:    Executing command vm image show
Offer:
error:   Please provide a non empty value for 'Offer: '. You provided - ''.
error:   Error information has been recorded to /home/binxi/.azure/azure.err
error:   vm image show command failed
```

**Comment by huangpf** [comment]
Got it. It turns out to be indeed a required parameter. I will take a look. Sorry for the inconvenience.

**Comment by huangpf** [comment]
fixed & merged.
