### ISSUE TITLE
Documentation Request Availability Set

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-xplat-cli#3558]
CLI Version: **Tool version 0.10.7**
OS Type: Ubuntu
Installation via:  npm

Mode: **ARM**

Environment: **AzureCloud**

Description:
`Document ability to access failure and update domain ids`

Steps to reproduce:
I'm trying to find out if it is feasible to lookup a vm's failure and update domain id's programmatically. 
I have an application that is affinity aware and need to use the f/u domains as part of it's configuration.

They domain id's are available in portal but I cannot figure out how to access them via the cli

**Comment by amarzavery** [comment]
I see. Do you know by any chance what is that property exactly called and what is the data type (string, integer, etc. ) of the value that you would provide?
I was looking at the compute openapi spec over [here](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-04-30-preview/swagger/compute.json) and searched for domain. Got some hit's in the [VirtualMachineInstanceView](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-04-30-preview/swagger/compute.json#L4117) model definition. Not sure if that is one of the properties that you are looking to update.

/cc @huangpf @derekbekoe do you have any idea about this property or how this can be done in the new [python based azure-cli](https://github.com/Azure/azure-cli)

**Comment by bearrito** [comment]
I'm fairly sure it is

```
properties": {
        "platformUpdateDomain": {
          "type": "integer",
          "format": "int32",
          "description": "Specifies the update domain of the virtual machine."
        },
        "platformFaultDomain": {
          "type": "integer",
          "format": "int32",
          "description": "Specifies the fault domain of the virtual machine."
}
```

**Comment by amarzavery** [comment]
I see.

@huangpf, @hyonholee, @singhkays 
Currently, [VirtualMachines_CreateOrUpdate](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-04-30-preview/swagger/compute.json#L1159) is the (PUT) operation that supports creating or updating properties of a **VirtualMachine**.  The [property **"instanceView"** in "VirtualMachineProperties" is **"readOnly"**](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-04-30-preview/swagger/compute.json#L4198); i.e. it can be populated by the server in the response but cannot be sent in the request by the client.

- So, if someone wants to update the properties of the VirtualMachineInstanceView, how should one go about that? 

@bearrito - Has provided his scenario in the issue description? How is it possible to achieve this using a CLI or an sdk?

**Comment by huangpf** [comment]
In C# SDK/PS, there is a way to parse the raw response text, do you think it's feasible by Node/Python SDK & CLI1+2 as well?

If properties are missing from the model definition, a bug should be filed for adding them. Thanks.

**Comment by amarzavery** [comment]
Yes, you can get the raw response in node sdk as well. In the callback we return 4 things `(err, result, rawRequest, rawResponse)`. If you are calling based on a Promise then you should call `...WithHttpOperationResponse()` flavor.

How is that related to the question I asked above?

The question is: 
>  if someone wants to update the properties of the VirtualMachineInstanceView, how should one go about that? (Have provided context about readOnly in previous comment)

**Comment by huangpf** [comment]
By ```property``` do you mean swagger model class property or the actual VM property?

If the former, please refer to my last statement:
```
If properties are missing from the model definition, a bug should be filed for adding them. Thanks.
```

If the latter, then it's not expected for a user to be able to modify the ```view``` property.

**Comment by amarzavery** [comment]
It is the latter. It seems the portal allows updating that (I may be wrong here).
@bearrito - Can you please provide a screenshot of the portal that allows you to update the domain ids.

If the portal does not allow you to update domainIds then this property cannot be updated.
It would be nice if you can explain your end to end scenario in detail (particularly, why do you need to update the domain id). This will help @huangpf  and me to help you :).

**Comment by huangpf** [comment]
It's probably modified by another API. Please check with Portal to see which APIs they are calling:

https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines
https://docs.microsoft.com/en-us/rest/api/compute/availabilitysets

It's very unlikely that you can change the view properties directly.

**Comment by bearrito** [comment]
You cannot update the domain or fault domains. They are set by Azure on creation of a VM inside an Availability Set. I think you are confused by my sentence which read "I'm trying to find out if it is feasible to lookup a vm's failure and update domain id's" I was referring to looking up (failure and update) domains. I was using update as a noun and not a verb.

I need the  domain id because I have an application that is fault and update domain aware. It will store data on different nodes based on this information.

**Comment by amarzavery** [comment]
Ohhh, yes I indeed got confused. In that case, you need to use the optional query parameter `$expand=instanceView` to get detailed information about the instanceView.
This is the command that helps you get the instanceView
`azure vm get-instance-view [options] <resource-group> <name> --json`

A simple node sdk code-snippet would also do the same thing.
```javascript
const msRestAzure = require('ms-rest-azure');
const ComputeClient = require('azure-arm-compute');
let client;
msRestAzure.loginWithServicePrincipalSecret('clientId or appId', 'secret or password', 'domain or tenant').then((credentials) => {
  client = new ComputeClient(credentials, 'subscriptionId');
  let options = {expand: 'instanceView'};
  return client.virtualMachines.get('rg-name', 'vm-name', options);
}).then((vminfo) => {
  console.dir(vminfo, {depth: null, colors: true});
}).catch((err) => {
  console.dir(err, {depth: null, colors: true});
});
```
Here is the [documentation reference](http://azure.github.io/azure-sdk-for-node/azure-arm-compute/latest/VirtualMachines.html#get).

**Comment by bearrito** [comment]
The comment above by @amarzavery solves the issue.

For the record or other users the output will look similar to

```
"instanceView": {
    "platformUpdateDomain": 0,
    "platformFaultDomain": 0,

```

I was unfamiliar with the get-instance-view subcommand. I'll remember it in the future.

Thanks for all the help. I believe this issue can be closed as resolved.

**Comment by highbass** [comment]
man fantastic, I was looking for this! if only Microsoft got its act together and released instance metadata to all regions than this wouldn't be the method of pulling the info.

**Comment by amarzavery** [comment]
@johanste @derekbekoe - Please take a look at this for the [V2 CLI](https://github.com/azure/azure-cli).
