### ISSUE TITLE
shorten the user-agent string for server-side telemetry

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-xplat-cli#3565]
user-agent: 'AzureXplatCLI/0.10.11;osType:Darwin;osVersion:15.3.0;nodeVersion:v7.9.0;installationType:NPM; ~~userId:ffffffffffffffyuyuyufyuyfuyfuyfuyfuyfuyufyufyufyf;subscriptionId:121252375256325634256435263;~~ userType:user;macAddressHash:131263751267356175671546714516745671417456713;~~mode:arm~~'

- Properties that are ~~striked~~ need to be removed for sure.
- Will have to confirm for macAddressHash.

There are no changes to clientside telemetry.

**Comment by balajikris** [comment]
Remove userId,subscriptionId,mode
