### ISSUE TITLE
Attach public IP to NIC

### ISSUE THREAD

**Issue by dhd-dixit** [Azure/azure-xplat-cli#3571]
CLI Version:  0.10.7
OS Type: Linux (Ubuntu)
Installation via:  npm

Mode: ARM

Environment: AzureCloud

Description:
I want to attach public IP to NIC using xplat (version 0.10.7) command line. 
I am using the following command:

azure network nic ip-config create -g <resource_group> -c <nic_name> -n <nam_of_ip_config> --public-ip-name <PUBLIC_IP_NAME>

I am getting the following error:
error:   A public IP address with name <PUBLIC_IP_NAME>  not found in the resource group "<resource_group>"
error:   Error information has been recorded to /home/dushyant/.azure/azure.err
error:   network nic ip-config create command failed

How should I create and attach public IP using only one command? 

NOTE: I was able to do it in the previous version of xplat.

Thanks.

**Comment by EvgenyAgafonchikov** [comment]
Please check are nic and public IP are in the same resource group. If they are not, please try to refer public IP by ID (by name works in the same resource group only).

**Comment by dhd-dixit** [comment]
How do create public IP using commandline ?
was not able to find command to create the public IP. (I was assuming the above command will create and attach public IP)

Thanks.

**Comment by EvgenyAgafonchikov** [comment]
In CLI it just refers existing public-ip. Command:
```
azure network public-ip create [options] <resource-group> <name> <location>
```

**Comment by dhd-dixit** [comment]
Works. Thanks.
