### ISSUE TITLE
Azure CLI 2.0 applies NICs inconsistently

### ISSUE THREAD

**Issue by GuyMacguffin** [Azure/azure-xplat-cli#3574]
CLI Version: 2.0.1
OS Type: Win7 64
Installation via:  win installer

Mode: ARM

Environment: AzureCloud

Description:
Azure CLI 2.0 applies NICs inconsistently

Steps to reproduce:
1) Create two NICs: NIC1. NIC2
2) Create a windows server 2012 R2 VM with the two NICs
3) Wait for Windows VM to launch and then log in to the machine and check the interfaces

Results:
Sometimes NIC1 = ethernet1 and NIC2=ethernet2 on the OS and sometimes NIC1 = ethernet2 and NIC2=ethernet1. This did not reproduce when using CLI v1, the first NIC applied was always ethernet1. Is there any way to get this consistent?

**Comment by amarzavery** [comment]
This looks like an issue with the new python based CLI. The latest version of the CLI published from this repo is 0.10.12. Please file an issue over here: https://github.com/azure/azure-cli

**Comment by GuyMacguffin** [comment]
Thanks amarzavery. I posted over there but I've never heard anything back. I was under the impression that the python based CLI is meant to replace this one, is that the case or should I try this functionality using this CLI?
