### ISSUE TITLE
The link to download Pre-compiled installers for Windows and Mac are not working (404 error)

### ISSUE THREAD

**Issue by JianChengSun** [Azure/azure-xplat-cli#3584]
_Pre-compiled installers
•Windows
•Mac
•Linux_
The above content provides links to download pre-complied installers. But the Windows and Mac links are not working now. When click on the link, it returns 404 error.

**Comment by balajikris** [comment]
are you talking about the links at [latest release page](https://github.com/Azure/azure-xplat-cli/releases/tag/v0.10.12-May2017) ? Seems to work fine for me. May be github was temporarily having an issue?

**Comment by balajikris** [comment]
ah i see what you mean..

This text and links on top is indeed broken 😲 . 
`npm: npm install -g azure-cli | Windows | Mac dmg | Linux tarball | docker: docker run -it microsoft/azure-cli`


For now, could you please scroll down on the same page to the `Downloads` section and get it from there? We'll fix this meanwhile - nice catch!

**Comment by balajikris** [comment]
@JianChengSun -- Fixed now. 😄 All links are now working - thanks for reporting the issue 👍

**Comment by JianChengSun** [comment]
@balajikris   Thanks for your quick fix, it's working now 👍
