### ISSUE TITLE
`azure storage account show` command shows the encryption for files is still enabled after I disable SSE on Azure Portal.

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-xplat-cli#3586]
CLI Version: **0.10.10**
OS Type: Linux (Ubuntu, RedHat, etc.)
Installation via:  npm
Mode: **ARM**

Environment: **AzureCloud**

Description:
`azure storage account show` command shows the encryption for files is still enabled after I disable SSE on Azure Portal.

Steps to reproduce:
1) Enable SSE for a storage account on Azure Portal.
2) Then run `azure storage account show ...`
```
  "encryption": {
    "services": {
      "blob": {
        "enabled": true,
        "lastEnabledTime": "2017-05-16T07:03:30.625Z"
      },
      "file": {
        "enabled": true,
        "lastEnabledTime": "2017-05-16T07:01:59.410Z"
      }
    },
    "keySource": "Microsoft.Storage"
  },
```
3) Disable SSE for a storage account on Azure Portal.
4) Then run `azure storage account show ...`
```
  "encryption": {
    "services": {
      "file": {
        "enabled": true,
        "lastEnabledTime": "2017-05-16T07:01:59.410Z"
      }
    },
    "keySource": "Microsoft.Storage"
  },
```

From my understanding, if I disable SSE on Azure Portal, the output of Azure CLI should be aligned.

**Comment by balajikris** [comment]
@hasonmsft - could you please take a look at this?

**Comment by yaxia** [comment]
@bingosummer It looks only blob encryption is disabled. The portal provides the "Encryption" property for blob service and file service respectively. Could you please double check whether you turned off both?

**Comment by bingosummer** [comment]
@yaxia You are right. Thanks.
I was confused by the `Encryption` properties of blob and file service, since the descriptions of the two `Encryption` are exactly same. My bad. Closing the issue.
