### ISSUE TITLE
how to uninstall azure-cli.0.X.Y.dmg???

### ISSUE THREAD

**Issue by tessus** [Azure/azure-xplat-cli#3591]
The fact that we are supposed to use the new cli 2.0 `curl -L https://aka.ms/InstallAzureCli | bash` doesn't really explain how to actually uninstall the current azure cli package.
It was installed with the azure-cli.0.X.Y.dmg on Mac, but there's no uninstall option.

How do I uninstall it?

**Comment by yugangw-msft** [comment]
Run `azure-uninstall`. You might need `sudo` it

**Comment by tessus** [comment]
Thx, this worked. Can you please add this to the documentation?

e.g. on https://docs.microsoft.com/en-us/azure/cli-install-nodejs and to the README.md?

**Comment by yugangw-msft** [comment]
//cc:@squillace
