### ISSUE TITLE
Networking/Application Gateway API 2017-06-01 for Early July release

### ISSUE THREAD

**Issue by akshaysngupta** [Azure/azure-xplat-cli#3625]
We are pushing to release few features for application gateway in the early July release for CLI.
[Swagger changes](https://github.com/Azure/azure-rest-api-specs/pull/1285) are in for these features. 
**Note**: We are running late as NRP update is running late and hope that it gets over by 27 June.

### Summary of Changes
1)	ApplicationGateway Ssl Policy custom cipher suites feature [new properties added to Sslpolicy Property of ApplciationGatewayPropertiesFormat]
2)	Get AvailableSslOption feature [new resource ApplicationGatewayAvailableSslOptions and child resource ApplicationGatewayPredefinedPolicy]
3)	Redirect Configuration feature [new child resource ApplicationGatewayRedirectConfiguration for Application Gateway, new properties in UrlPathMap, PathRules and RequestRoutingRule]
4)	Azure Websites feature [new properties in ApplicationGatewayBackendHttpSettingsPropertiesFormat, ApplicationGatewayProbePropertiesFormat, schema for property ApplicationGatewayProbeHealthResponseMatch]
5)	Backendhealth nic fix [since powershell references NetworkInterfaceIPConfiguration instead of ResourceChild, returning SubResource for NetworkInterfaceIPConfiguration in Swagger created problem]

**Comment by balajikris** [comment]
@akshaysngupta - assigning to yourself to track this to completion. do you know who will be working on this feature for xplat-cli? @number213 and @EvgenyAgafonchikov are the usual contributors for networking commands. Is it going to be them or someone else?

**Comment by balajikris** [comment]
Adding Anton, as he did the dev work for this. Anton - please feel free to close this issue if its all done.

**Comment by number213** [comment]
@balajikris everything's done. I can't close the issue (there's no "Close Issue" button next to "Comment", looks like I don't have enough permissions), could you please do that for me?

**Comment by balajikris** [comment]
cool, thanks for confirming -- will close.

**Comment by balajikris** [comment]
Fixed by @number213

**Comment by akshaysngupta** [comment]
Thanks all!
