### ISSUE TITLE
Copy configuration from website when creating staging slot

### ISSUE THREAD

**Issue by pawepaw** [Azure/azure-xplat-cli#3678]
Is it possible to create deployment slot for app service and copy configuration from currently running production? Every time i am deploying new version my application/server logs are being disabled.

Currently i am doing that using:
`New-AzureWebsite -Name "SomeSite" -Slot Staging`

In CLI 2.0 it's possible by specifying `--configuration-source` 
https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/slot?view=azure-cli-latest#az_webapp_deployment_slot_create

Is there any chance to do it with 1.0 as well?

**Comment by amarzavery** [comment]
Nope. CLI 1.0 should be used only for ASM (V1 version of Azure APIs). For ARM (V2 version of Azure APIs), CLI 2.0 is the recommended tool.

If you want to see the site commands in ASM mode
```
azure config mode asm
azure site -h
```
But that is for ASM. CLI 1.0 does not have actively developed/supported commands for ARM mode.
