### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by sundaxi** [Azure/azure-xplat-cli#3682]
- CLI Version: 0.10.2 and 0.10.8
- OS Type: CentOS Linux release 7.3.1611 (Core), CentOS Linux release 7.2.1511
- Installation via:  npm / brew / win-or-mac installer / docker / github repo

- Mode: ARM

- Environment: AzureCloud

- Description:
issue happend on 2018-02-14 intermitently.  When run the "azure cli" it prompted SSL error shown as below 

# cat azure.err
2018-02-14T04:16:17.076Z:
{ Error: unable to verify the first certificate
<<< async stack >>>
at __1 (/usr/lib/node_modules/azure-cli/lib/commands/login.js:116:28)
<<< raw stack >>>
at Error (native)
at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
at emitNone (events.js:86:13)
at TLSSocket.emit (events.js:185:7)
at TLSSocket._finishInit (_tls_wrap.js:584:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
stack: [Getter/Setter],
code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
__frame:
{ name: '__1',
line: 50,
file: '/usr/lib/node_modules/azure-cli/lib/commands/login.js',
prev: undefined,
calls: 0,
active: false,
offset: 66,
col: 27 },
rawStack: [Getter] }
Error: unable to verify the first certificate
<<< async stack >>>
at __1 (/usr/lib/node_modules/azure-cli/lib/commands/login.js:116:28)
<<< raw stack >>>
at Error (native)
at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
at emitNone (events.js:86:13)
at TLSSocket.emit (events.js:185:7)
at TLSSocket._finishInit (_tls_wrap.js:584:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)

- Steps to reproduce:
cannot reproduce, the issue migrated automatically after Feb 15th 

I understand that below method could migrate the certificate issue, but my question is there any incident happened during the issue time? Such as certificate expired ?

On Linux: export NODE_TLS_REJECT_UNAUTHORIZED=0
On Windows: set NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by amarzavery** [comment]
@sundaxi - Please use CLI 2.0 https://github.com/azure-cli. This is not the recommended CLI.

**Comment by sundaxi** [comment]
@amarzavery Thanks for your reply. Some customers needs Azure CLI 1.0 to manage their classic VMs and also for encryption purpose. Kindly help to confirm why the error happened intermitantly on Feb 14th. 

Does the certificate expired during the issue time?

**Comment by amarzavery** [comment]
I think it was an intermittent issue.

**Comment by sundaxi** [comment]
@amarzavery  Thanks for your reply. I understand it's an intermittent issue, but my customer and I want to understand the mechanism and identify if the issue was related to CLI client or azure ARM backend?

**Comment by sundaxi** [comment]
Got the RCA below. Please close the issue 
SUMMARY OF IMPACT
Between 18:00 UTC on 13 Feb 2018 and 04:40 UTC on 14 Feb 2018, you were identified as several users using Azure Active Directory who may have experienced difficulties when attempting to authenticate into resources which are dependent on Azure Active Directory.
MITIGATION
Engineers rolled back the recent deployment task to mitigate the issue.
