### ISSUE TITLE
azure ad app set --available false doesn't actually set AvailableToOtherTenants=false

### ISSUE THREAD

**Issue by NoseyNick** [Azure/azure-xplat-cli#3686]
- CLI Version: **0.10.18**
- OS Type: Linux (Ubuntu)
- Installation via:  npm I think

- Mode: **ARM**

- Environment: **AzureCloud**

- Description:
`azure ad app set --available false` command doesn't actually toggle "availableToOtherTenants": false,

- Steps to reproduce:
1) Run `azure ad app show --json --objectId $ID` for an app that is AvailableToOtherTenants: true
2) Run `azure ad app set --available false --objectId $ID`
3) Observe no error, looks successful
4) Run `azure ad app show --json --objectId $ID`
5) Observe nothing changed. App is still AvailableToOtherTenants: true

- Error stack trace:

**N/A - no stack "error" / stack trace, just unexpectedly didn't do what it said it had**

**Comment by amarzavery** [comment]
This CLI is deprecated. Please use the new CLI https://github.com/azure/azure-cli
