### ISSUE TITLE
Template deployment returned the following errors:  The resource 'cim-report-test1' already exists in location 'westus2' in resource group 'Non-Prod-CIMV2'. A resource with the same name cannot be created in location 'westus'. Please select a new resource name.

### ISSUE THREAD

**Issue by singhbibek** [Azure/azure-xplat-cli#3693]
I am not able to create the web apps and getting errors-
Template deployment returned the following errors:  The resource 'cim-report-test1' already exists in location 'westus2' in resource group 'Non-Prod-CIMV2'. A resource with the same name cannot be created in location 'westus'. Please select a new resource name.

Can't we create or update web app with the same name in same resource group as other resources azure function app, app insight, key vault etc?
I am always getting an error for web app only. I have to go again and again to delete the web apps and again trigger the ARM template, it's really hectic. could you please suggest me on this.

**Comment by amarzavery** [comment]
This project is not supported for ARM commands any more. Please use the new CLI (https://github.com/azure/azure-cli). If you were using the new cli then please file an issue over there.
