### ISSUE TITLE
Latest Azure CLI version 0.10.20 doesn't work to show keyvault secret

### ISSUE THREAD

**Issue by swathi-c** [Azure/azure-xplat-cli#3701]
The latest Azure classic CLI is having an issue showing keyvault secret. It worked in the previous version.

- CLI Version: **0.10.20**
- OS Type: Linux (RedHat)
- Installation via:  npm

- Environment: **AzureCloud**

- Description:
`azure keyvault secret show` command doesn't output secret value.

- Steps to reproduce:
1) Run `azure keyvault secret show`
```
azure keyvault secret show --vault-name \<vault-name> --secret-name \<secret-name>
info:    Executing command keyvault secret show
- Getting secret https://daat-global-dev-kv.vault.azure.net/secrets/adAdminGroup(node:10598) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: secretName cannot be null or undefined and it must be of type string.
```

**Comment by amarzavery** [comment]
This CLI has been deprecated. Please use the new cli https://github.com/azure/azure-cli
