### ISSUE TITLE
Unable to open Azure data lake store via azure storage explorer and it is erroring out with below message "tunneling socket could not be established, statusCode=407"... Even though I have the latest azure storage explorer 1.7.0 installed in my desktop....

### ISSUE THREAD

**Issue by lanaindia** [Azure/azure-xplat-cli#3703]
Unable to open Azure data lake store via azure storage explorer and it is erroring out with below message "tunneling socket could not be established, statusCode=407"... Even though I have the latest azure storage explorer 1.7.0 installed in my desktop....

**Comment by lanaindia** [comment]
Anybody trying to access to Azure Data Lake Store via azure storage explorer and having success...

I have seen most of people struggling to connect to data lake via storage explorer.

**Comment by amarzavery** [comment]
This doesn't seem to be the right repo for this issue. Please file an issue over here https://github.com/microsoft/AzureStorageExplorer
