### ISSUE TITLE
Create subscription management library separate from account command

### ISSUE THREAD

**Issue by christav** [Azure/azure-xplat-cli#418]
Right now, all the logic for manipulating publishsettings, the .azure directory, key imports, etc. is inside the account CLI category object. This is a poor place to be. We should split out the subscription management stuff into an explicit API, and then call it from the account object.

Due to the RDFE registration requirements, there's now a registration method that each resource provider's code will have to call on account so that account import works properly. This means that account is now special - it has to load first so it's available for (potentially) all the other commands. This is undesirable for a whole lot of reasons.

Having an explicit API will make it requireable instead of having to go through the CLI extension mechanism.

**Comment by yugangw-msft** [comment]
closing this item due to age.
