### ISSUE TITLE
help documentation fixes

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/azure-xplat-cli#821]
there is a docs inconsistency between ````azure site create``` and ```azure site deployment user set```.

**create** accepts an option of ```--gitusername <gitusername>```
**deployment user set** accepts an option of ```-u, -username <gitusername>```

could we make this consistent in the next release? I would prefer the second option as it provides a short form.

**Comment by yugangw-msft** [comment]
Closing this as it is a low priority item
