### ISSUE TITLE
Azure blob upload feedback on a large file

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/azure-xplat-cli#885]
I was uploading a 64GB file today and got this at the very end; throughout, I'd have the computer go into standby - but when the computer came out of standby, the upload would continue going, as verified by the Mac's Activity Monitor app, and the % increasing in the Azure CLI;

## 1: Uploading more event when networks change - to 100%
So effectively I probably uploaded 10GB first chunk, a few 5GB chunks ("chunk" meaning time the PC was on before going into standby), and then the rest; just odd that the entire thing got uploaded.

## 2: High 100% CPU load
Also interesting, the CPU on my modern Haswell MacBook Air was at 100% or so with the `node` process almost the entire time; running Node.js v0.10.15 here. Working actual memory set was around 430MB. CPU went from about 70%-100%, mostly at about 99%.

I don't know the technical details of how the SDK streams/cuts chunks, etc., but it is odd that is uploads entirely and then fails.

Anyway, after hours of uploading, at the very end, at 100% uploaded, I got this. Expected perhaps, but not sure why it uploaded so much first without failing fast earlier??

```
Mon Aug 12 2013 22:51:01 GMT-0700 (PDT):
{ [Error: read ECONNRESET]
  stack: [Getter/Setter],
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  __frame: 
   { name: '__1',
     line: 169,
     file: '/Users/jeffwilcox/working/azure-sdk-tools-xplat/lib/util/storage.util._js',
     prev: 
      { name: 'StorageUtil_performStorageOperation__1',
        line: 151,
        file: '/Users/jeffwilcox/working/azure-sdk-tools-xplat/lib/util/storage.util._js',
        prev: [Object],
        active: false,
        offset: 18,
        col: 4 },
     active: false,
     offset: 2,
     col: 15 },
  rawStack: [Getter] }
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
    at __1 (/Users/jeffwilcox/working/azure-sdk-tools-xplat/lib/util/storage.util._js:171:15)
    at StorageUtil_performStorageOperation__1 (/Users/jeffwilcox/working/azure-sdk-tools-xplat/lib/util/storage.util._js:169:4)
    at uploadAzureBlob (/Users/jeffwilcox/working/azure-sdk-tools-xplat/lib/commands/storage.blob._js:687:8)
```

## 3: No request ID in the error

In theory I might be able to use support or logging to look up the request ID/s for the upload and look into the issue; however, no request ID is in the message from azure.err.

## 4: 2nd try failed

I then tried again at home via my gigabit Internet; it took about 30 minutes to upload the 64GB or so... no disconnections, I actively used the PC, etc.; right at 100%, I got an EPIPE error:

```
Mon Aug 12 2013 23:44:39 GMT-0700 (PDT):
{ [Error: write EPIPE]
  stack: [Getter/Setter],
  code: 'EPIPE',
  errno: 'EPIPE',
  syscall: 'write',
  __frame: 
   { name: '__1',
     line: 169,
     file: '/Users/jeffwilcox/working/azure-sdk-tools-xplat/lib/util/storage.util._js',
     prev: 
      { name: 'StorageUtil_performStorageOperation__1',
        line: 151,
        file: '/Users/jeffwilcox/working/azure-sdk-tools-xplat/lib/util/storage.util._js',
        prev: [Object],
        active: false,
        offset: 18,
        col: 4 },
     active: false,
     offset: 2,
     col: 15 },
  rawStack: [Getter] }
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
    at __1 (/Users/jeffwilcox/working/azure-sdk-tools-xplat/lib/util/storage.util._js:171:15)
    at StorageUtil_performStorageOperation__1 (/Users/jeffwilcox/working/azure-sdk-tools-xplat/lib/util/storage.util._js:169:4)
    at uploadAzureBlob (/Users/jeffwilcox/working/azure-sdk-tools-xplat/lib/commands/storage.blob._js:687:8)
```

Any idea how to get more information?

Leading up to this things were going Ok...

```
info:    Executing command storage blob upload
+ Checking blob Windows8VM.tar in container vhd                             
+ Uploading Windows8VM.tar to blob Windows8VM.tar in container vhd          
Percentage: 99.0% (65.40GB/65.64GB) Speed: 35.17MB/S Elapsed Time: 00:34:21    
```

**Comment by gangsir** [comment]
@kensykora Sorry for the late reply. We didn't see any repro of this issue in our recent large scale test. We recommend you to try the latest version of Azure CLI and let us know if the issue still exists. Thanks for providing feedback.
