### ISSUE TITLE
azure vm location list returns an invalid location

### ISSUE THREAD

**Issue by nmackenzie** [Azure/azure-xplat-cli#917]
The Service Management REST API List Location operation provides a list of datacenters in which a subscription can host a PaaS cloud service. This is possibly a superset of the datacenters in which a VM cloud service can be hosted. When I invoke either List Location or azure vm location list, the datacenter list includes North Central US which does not support VM cloud services.

Since this is an azure vm command it should return only the list of datacenters which support VM cloud services.

**Comment by kmouss** [comment]
Thank you. By default it will list all locations, but if you need to see details of the services supported in a location use --json.

**Comment by kmouss** [comment]
Closing for now. Please last comment.
