### ISSUE TITLE
Switch to use the new <scmurl>/settings?version=2

### ISSUE THREAD

**Issue by suwatch** [Azure/azure-xplat-cli#986]
This api is used as part of `site show` to list all scm settings.  The new api returns a better json format than existing one.  Another reason to switch is that Kudu team may not support the old format in the future.  This should apply to all SKUs (powershell, nodejs,...) of CLI tools.

Old format, <scmurl>/settings

    [
      {"Key":"deployment_branch","Value":"master"}, 
      {"Key":"SCM_TRACE_LEVEL","Value":"1"},
      …
    ]

New format, <scmurl>/settings?version=2

    {
      deployment_branch: "master",
      SCM_TRACE_LEVEL: "1",
      …
    }

**Comment by yugangw-msft** [comment]
Verified in the latest version of xcli. This has been fixed.
